import type { ImmersiveLessonBlueprint, ImmersiveModuleAuthoring, LessonType } from "./types";
import { A1_REMAINING_IMMERSIVE_MODULES } from "./a1-immersive-modules-expanded";

const exposure = (
  lessonNumber: number,
  mode: ImmersiveLessonBlueprint["exposurePlan"][number]["mode"],
  task: string,
  taskArabic: string,
) => ({ lessonNumber, mode, task, taskArabic });

const lesson = (
  lessonNumber: number,
  type: LessonType,
  title: string,
  titleArabic: string,
  mentorPurpose: string,
  mentorPurposeArabic: string,
  vocabularyAnchors: string[],
  grammarFocus: string,
  grammarFocusArabic: string,
  beginnerExplanation: string,
  beginnerExplanationArabic: string,
  canDo: string,
  canDoArabic: string,
  exposurePlan: ImmersiveLessonBlueprint["exposurePlan"],
  practiceModes: LessonType[],
): ImmersiveLessonBlueprint => ({
  lessonNumber,
  moduleNumber: 1,
  type,
  title,
  titleArabic,
  mentorPurpose,
  mentorPurposeArabic,
  vocabularyAnchors,
  grammarFocus,
  grammarFocusArabic,
  beginnerExplanation,
  beginnerExplanationArabic,
  exposurePlan,
  practiceModes,
  canDo,
  canDoArabic,
});

/**
 * First deep-authoring slice for the new course model.
 *
 * This is intentionally additive: it is a lesson-authoring blueprint, not a
 * replacement for the currently synchronized 20-lesson A1 catalog. Each
 * blueprint makes the intended module arc explicit before content is migrated
 * into the normalized lesson tables and learner route.
 */
export const A1_MEETING_PEOPLE_IMMERSIVE: ImmersiveModuleAuthoring = {
  level: "A1",
  moduleNumber: 1,
  title: "Meeting People: Your First English Community",
  titleArabic: "التعرّف إلى الناس: مجتمعك الأول باللغة الإنجليزية",
  overview:
    "Start almost from zero. The learner builds a small, useful social world: greeting someone, saying a name, asking a name, identifying people, counting, describing simple things, and completing a first supported conversation.",
  overviewArabic:
    "نبدأ من الصفر تقريباً. يبني المتعلم عالماً اجتماعياً صغيراً ومفيداً: يحيّي شخصاً، يقول اسمه، يسأل عن اسم الآخر، يعرّف بالأشخاص، يعدّ، يصف أشياء بسيطة، وينهي أول محادثة مدعومة.",
  mentorOpening:
    "You do not need to know grammar before we begin. We will meet one small group of words at a time, notice how English puts them together, and then use the same words again until they feel familiar. English is not a list to memorize; it is a set of tools you can use with people.",
  mentorOpeningArabic:
    "لا تحتاج إلى معرفة القواعد قبل أن نبدأ. سنلتقي بمجموعة صغيرة من الكلمات في كل مرة، ونلاحظ كيف ترتبها الإنجليزية، ثم نستخدم الكلمات نفسها مرة بعد مرة حتى تصبح مألوفة. الإنجليزية ليست قائمة للحفظ؛ إنها أدوات يمكنك استخدامها مع الناس.",
  lessonBlueprints: [
    lesson(1, "standard", "A first hello", "أول تحية", "Give the learner a safe first success: hearing, recognizing, and saying hello, goodbye, and thank you.", "امنح المتعلم أول نجاح آمن: الاستماع إلى hello وgoodbye وthank you والتعرف إليها ونطقها.", ["hello", "hi", "goodbye", "thank you", "please"], "Words, spaces, and the idea of a sentence", "الكلمات والمسافات وفكرة الجملة", "A sentence is a group of words that gives a complete message. In English, we normally begin with a capital letter and finish with a mark such as a full stop.", "الجملة مجموعة كلمات تعطي رسالة كاملة. في الإنجليزية نبدأ عادة بحرف كبير وننهي بعلامة مثل النقطة.", "Greet someone and say goodbye politely.", "يحيّي شخصاً ويودّعه بأدب.", [exposure(1, "learn", "Match each English greeting to its Arabic meaning, then say it aloud.", "صِل كل تحية إنجليزية بمعناها العربي ثم انطقها بصوت مرتفع."), exposure(1, "hear", "Listen to two short greetings and notice the first sound and the final sound.", "استمع إلى تحيتين قصيرتين ولاحظ الصوت الأول والصوت الأخير."), exposure(2, "retrieve", "Begin the next lesson by choosing the greeting for a morning meeting.", "ابدأ الدرس التالي باختيار التحية المناسبة للقاء صباحي.")], ["standard", "speaking", "review"]),
    lesson(2, "interaction", "My name is…", "اسمي هو…", "Turn isolated greetings into a two-line exchange so the learner feels language working between two people.", "حوّل التحيات المعزولة إلى تبادل من سطرين حتى يشعر المتعلم أن اللغة تعمل بين شخصين.", ["name", "my", "your", "I", "you"], "Subject and possessive words: I, you, my, your", "كلمات الفاعل والملكية: I وyou وmy وyour", "I and you show who we are talking about. My shows something belongs to me; your shows it belongs to the other person. These words come before the noun: my name, your name.", "توضح I وyou من نتحدث عنه. وتوضح my أن الشيء يخصني، بينما توضح your أنه يخص الشخص الآخر. تأتي هذه الكلمات قبل الاسم: my name وyour name.", "Say your name and ask another person's name.", "يقول اسمه ويسأل عن اسم شخص آخر.", [exposure(1, "use", "Complete: Hello, my name is ___. What is your name?", "أكمل: Hello, my name is ___. What is your name?"), exposure(1, "hear", "Replay the dialogue and point to I, you, my, and your when you hear them.", "أعد تشغيل الحوار وأشر إلى I وyou وmy وyour عند سماعها."), exposure(3, "retrieve", "Use my and your in a family introduction.", "استخدم my وyour في تعريف بأحد أفراد العائلة.")], ["interaction", "speaking", "standard"]),
    lesson(3, "standard", "I am / you are", "أنا أكون / أنت تكون", "Introduce the first grammar engine without assuming the learner knows the word verb: English needs am or are in these short identity sentences.", "قدّم أول محرك نحوي من دون افتراض معرفة كلمة فعل: تحتاج الإنجليزية إلى am أو are في جمل الهوية القصيرة.", ["I", "you", "student", "friend", "happy"], "The verb be: I am and you are", "فعل الكينونة be: I am وyou are", "In Arabic, a present sentence can say أنا طالب without a visible verb. English usually needs the small verb am or are: I am a student. You are my friend.", "في العربية يمكن أن نقول أنا طالب من دون فعل ظاهر في المضارع. أما الإنجليزية فتحتاج عادة إلى الفعل الصغير am أو are: I am a student. You are my friend.", "Make a simple sentence about yourself or another person.", "يكون جملة بسيطة عن نفسه أو عن شخص آخر.", [exposure(1, "learn", "Build three sentences with word cards: I am…, You are…, My name is…", "كوّن ثلاث جمل ببطاقات الكلمات: I am… وYou are… وMy name is…"), exposure(2, "use", "Answer: Are you a student? Use Yes, I am or No, I am not.", "أجب: Are you a student? باستخدام Yes, I am أو No, I am not."), exposure(4, "retrieve", "Describe a family member with He is or She is.", "صف أحد أفراد العائلة باستخدام He is أو She is.")], ["standard", "interaction", "review"]),
    lesson(4, "visual-vocabulary", "People around us", "الأشخاص من حولنا", "Make people words concrete through faces, roles, and simple visual choices before adding more grammar.", "اجعل كلمات الأشخاص ملموسة من خلال الوجوه والأدوار والاختيارات البصرية قبل إضافة قواعد جديدة.", ["man", "woman", "child", "boy", "girl", "friend"], "Singular words: one person", "الكلمات المفردة: شخص واحد", "A singular word names one person or thing. We can put a or an before many singular nouns: a friend, a child. We do not say a friends.", "الكلمة المفردة تسمي شخصاً أو شيئاً واحداً. ويمكن أن نضع a أو an قبل كثير من الأسماء المفردة: a friend وa child. لا نقول a friends.", "Identify one person and describe the relationship in a picture.", "يحدد شخصاً واحداً ويصف العلاقة في صورة.", [exposure(2, "see", "Choose the picture that matches friend, child, or woman, then reveal the example sentence.", "اختر الصورة التي تناسب friend أو child أو woman ثم اكشف جملة المثال."), exposure(3, "use", "Say: This is a friend. This is a child.", "قل: This is a friend. وThis is a child."), exposure(5, "retrieve", "Use one people word in a short family reading.", "استخدم كلمة واحدة من كلمات الأشخاص في قراءة قصيرة عن العائلة.")], ["visual-vocabulary", "speaking", "review"]),
    lesson(5, "speaking", "Listen, repeat, meet", "استمع وكرّر وتعارف", "Move from silent recognition to a small spoken routine with pauses, replay, and permission to try more than once.", "انتقل من التعرف الصامت إلى روتين كلامي صغير مع التوقف وإعادة التشغيل والسماح بالمحاولة أكثر من مرة.", ["hello", "name", "student", "friend", "thank you"], "Word order in a greeting", "ترتيب الكلمات في التحية", "English usually places the person or topic before the information about it: My name is Sara. You are a student. The order helps the listener follow you.", "تضع الإنجليزية عادة الشخص أو الموضوع قبل المعلومات عنه: My name is Sara. وYou are a student. يساعد الترتيب المستمع على فهمك.", "Say a four-line introduction with a clear, polite rhythm.", "يقول تعريفاً من أربعة أسطر بإيقاع واضح ومهذب.", [exposure(1, "hear", "Listen to a model introduction once for meaning and once for rhythm.", "استمع إلى تعريف نموذجي مرة للمعنى ومرة للإيقاع."), exposure(5, "use", "Repeat the complete dialogue, then record or say it without looking.", "كرّر الحوار الكامل ثم سجله أو قلْه من دون النظر."), exposure(6, "retrieve", "Open the following numbers lesson by greeting the mentor aloud.", "ابدأ درس الأرقام التالي بتحية المرشد بصوت مرتفع.")], ["speaking", "interaction", "review"]),
    lesson(6, "standard", "Numbers and age", "الأرقام والعمر", "Use a familiar personal topic to make numbers meaningful and to prevent number words from becoming a disconnected list.", "استخدم موضوعاً شخصياً مألوفاً لجعل الأرقام ذات معنى ومنع تحولها إلى قائمة منفصلة.", ["one", "two", "three", "ten", "twenty", "years old"], "Age with be: I am … years old", "العمر مع be: I am … years old", "Age is expressed with be in English: I am twenty years old. Do not translate the Arabic structure word for word or use have for age in this sentence.", "يُعبَّر عن العمر باستخدام be في الإنجليزية: I am twenty years old. لا تترجم تركيب العربية كلمة بكلمة ولا تستخدم have للعمر في هذه الجملة.", "Say your age and understand another person's age.", "يقول عمره ويفهم عمر شخص آخر.", [exposure(3, "use", "Ask and answer How old are you? with a number and years old.", "اسأل وأجب عن How old are you? باستخدام رقم وyears old."), exposure(6, "retrieve", "Use age in a two-line introduction with my name and I am.", "استخدم العمر في تعريف من سطرين مع my name وI am."), exposure(7, "read", "Find the numbers in a short family card.", "ابحث عن الأرقام في بطاقة عائلية قصيرة.")], ["standard", "interaction", "review"]),
    lesson(7, "visual-vocabulary", "Colors and classroom things", "الألوان وأشياء الصف", "Give the learner visible objects to name and describe, creating the first bridge from a word to a phrase.", "امنح المتعلم أشياء مرئية ليسميها ويصفها، لبناء أول جسر من الكلمة إلى العبارة.", ["red", "blue", "green", "book", "pen", "bag"], "Adjectives before nouns: a blue book", "الصفات قبل الأسماء: a blue book", "A describing word is an adjective. In simple English, the adjective usually comes before the noun: a blue book, not a book blue.", "الكلمة التي تصف شيئاً تسمى صفة. في الإنجليزية البسيطة تأتي الصفة عادة قبل الاسم: a blue book وليس a book blue.", "Name a classroom object and describe its color.", "يسمي شيئاً في الصف ويصف لونه.", [exposure(4, "see", "Sort colored classroom pictures into red, blue, and green.", "صنّف صور أشياء الصف إلى red وblue وgreen."), exposure(7, "use", "Say three phrases: a red pen, a blue bag, a green book.", "قل ثلاث عبارات: a red pen وa blue bag وa green book."), exposure(8, "retrieve", "Find a color and object in a short classroom dialogue.", "اعثر على لون وشيء في حوار قصير داخل الصف.")], ["visual-vocabulary", "standard", "review"]),
    lesson(8, "interaction", "In the classroom", "في الصف", "Let the learner survive a first learning environment by asking for repetition, meaning, and a turn.", "ساعد المتعلم على التعامل مع بيئة تعلمه الأولى من خلال طلب التكرار والمعنى والدور.", ["teacher", "student", "book", "listen", "repeat", "understand"], "Imperatives and polite classroom requests", "صيغة الأمر والطلبات الصفية المهذبة", "An imperative begins with the base verb: Listen. Repeat. Look. To make a polite request, use Can you…? or Please: Can you repeat, please?", "تبدأ صيغة الأمر بالفعل الأساسي: Listen وRepeat وLook. وللطلب المهذب استخدم Can you…? أو Please: Can you repeat, please?", "Ask for repetition or say what to do in a lesson.", "يطلب التكرار أو يقول ماذا يفعل في الدرس.", [exposure(2, "use", "Role-play teacher and student: Listen, repeat, look, and Can you repeat, please?", "مثّل دور المعلم والمتعلم: Listen وrepeat وlook وCan you repeat, please?"), exposure(8, "hear", "Listen for the difference between a direction and a polite request.", "استمع إلى الفرق بين التعليمات والطلب المهذب."), exposure(9, "retrieve", "Use one classroom request in a family or work role-play.", "استخدم طلباً صفياً واحداً في تمثيل عن العائلة أو العمل.")], ["interaction", "speaking", "standard"]),
    lesson(9, "reading", "A new student", "طالب جديد", "Bring earlier greetings, names, ages, colors, and classroom words together in a short, kind reading experience.", "اجمع التحيات والأسماء والأعمار والألوان وكلمات الصف في قراءة قصيرة ولطيفة.", ["new", "student", "name", "from", "book", "friend"], "From and simple identity sentences", "from والجمل البسيطة عن الهوية", "Use from to say a place or origin: I am from Cairo. A short reading may repeat the same pattern many times; repetition helps you notice the structure.", "استخدم from لذكر المكان أو الأصل: I am from Cairo. قد تكرر القراءة القصيرة النمط نفسه مرات عدة؛ يساعد التكرار على ملاحظة التركيب.", "Read a short introduction and find who, where, and what.", "يقرأ تعريفاً قصيراً ويحدد من وأين وماذا.", [exposure(2, "read", "Read a six-sentence profile and underline greetings, names, and numbers.", "اقرأ تعريفاً من ست جمل وضع خطاً تحت التحيات والأسماء والأرقام."), exposure(9, "retrieve", "Answer one meaning question without translating every word.", "أجب عن سؤال معنى واحد من دون ترجمة كل كلمة."), exposure(10, "write", "Use the reading as a model for your own three-sentence profile.", "استخدم القراءة نموذجاً لتعريفك الشخصي من ثلاث جمل.")], ["reading", "standard", "review"]),
    lesson(10, "writing", "My first profile", "ملفي التعريفي الأول", "Turn recognition into ownership: the learner writes a tiny real profile using language already met in several contexts.", "حوّل التعرف إلى امتلاك: يكتب المتعلم تعريفاً حقيقياً صغيراً باستخدام لغة ظهرت في سياقات متعددة.", ["name", "from", "student", "family", "favorite", "color"], "Capital I, full stops, and sentence frames", "كتابة I بحرف كبير والنقاط وقوالب الجمل", "I is always written with a capital letter. A full stop tells the reader that the sentence is finished. A frame such as My name is… helps a beginner create a correct message.", "تكتب I دائماً بحرف كبير. وتخبر النقطة القارئ أن الجملة انتهت. ويساعد قالب مثل My name is… المبتدئ على إنشاء رسالة صحيحة.", "Write three to five true sentences about yourself with support.", "يكتب من ثلاث إلى خمس جمل صحيحة عن نفسه مع الدعم.", [exposure(3, "write", "Draft a profile with name, origin, learner role, and one color.", "اكتب مسودة تعريف تتضمن الاسم والأصل والدور كمتعلم ولوناً واحداً."), exposure(10, "use", "Check every sentence for I, a space, and a full stop.", "افحص كل جملة بحثاً عن I والمسافة والنقطة."), exposure(11, "retrieve", "Read your profile aloud and reuse one sentence in a dialogue.", "اقرأ تعريفك بصوت مرتفع وأعد استخدام جملة واحدة في حوار.")], ["writing", "speaking", "review"]),
    lesson(11, "standard", "Family words", "كلمات العائلة", "Open a meaningful personal domain while reusing identity, age, possessive words, and simple descriptions.", "افتح مجالاً شخصياً ذا معنى مع إعادة استخدام الهوية والعمر وكلمات الملكية والأوصاف البسيطة.", ["mother", "father", "brother", "sister", "family", "my"], "Have and possessive my/your", "الفعل have والملكية my/your", "Have can tell us that someone owns or is connected to something: I have a sister. My introduces something connected to me: my family.", "يمكن أن يوضح have أن شخصاً يملك شيئاً أو يرتبط به: I have a sister. وتقدم my شيئاً مرتبطاً بي: my family.", "Introduce one or two family members in simple sentences.", "يعرّف بأحد أفراد العائلة أو اثنين بجمل بسيطة.", [exposure(4, "use", "Say I have… and This is my… with family picture cards.", "قل I have… وThis is my… باستخدام بطاقات صور العائلة."), exposure(11, "retrieve", "Add a family sentence to your first profile.", "أضف جملة عن العائلة إلى تعريفك الأول."), exposure(12, "read", "Find the family relationship and age in a short family note.", "اعثر على صلة القرابة والعمر في ملاحظة قصيرة عن عائلة.")], ["standard", "visual-vocabulary", "review"]),
    lesson(12, "visual-vocabulary", "Jobs people do", "المهن التي يعمل بها الناس", "Introduce professions through people and purposes, not as a list, while revisiting a/an, be, and identity language.", "قدّم المهن من خلال الأشخاص والأدوار لا كقائمة، مع مراجعة a/an وbe ولغة الهوية.", ["teacher", "doctor", "driver", "cook", "student", "worker"], "A/an with professions: She is a doctor", "استخدام a/an مع المهن: She is a doctor", "A singular job is normally preceded by a or an after be: He is a driver. We say an artist because the next sound begins with a vowel sound.", "تأتي a أو an عادة قبل المهنة المفردة بعد be: He is a driver. ونقول an artist لأن الصوت التالي يبدأ بصوت علة.", "Say what someone does using a simple profession sentence.", "يقول ماذا يعمل شخص باستخدام جملة مهنة بسيطة.", [exposure(7, "see", "Match each person picture to a job and reveal the sentence.", "صِل صورة الشخص بالمهنة ثم اكشف الجملة."), exposure(12, "use", "Describe three people: He is a…, She is an…, I am a…", "صف ثلاثة أشخاص: He is a… وShe is an… وI am a…"), exposure(13, "retrieve", "Use one profession in an invitation or meeting dialogue.", "استخدم مهنة واحدة في حوار دعوة أو لقاء.")], ["visual-vocabulary", "standard", "review"]),
    lesson(13, "interaction", "A first real meeting", "أول لقاء حقيقي", "Create a complete, humane interaction that makes the earlier lessons feel like parts of one usable life event.", "أنشئ تفاعلاً إنسانياً كاملاً يجعل الدروس السابقة تبدو أجزاء من موقف حياتي قابل للاستخدام.", ["hello", "name", "from", "family", "job", "nice to meet you"], "Question words: What, Where, Who", "كلمات السؤال: What وWhere وWho", "Question words help us ask for different information: What is your name? Where are you from? Who is she? The question word comes at the beginning.", "تساعدنا كلمات السؤال على طلب معلومات مختلفة: What is your name? وWhere are you from? وWho is she? تأتي كلمة السؤال في البداية.", "Hold a supported first-meeting conversation and ask three questions.", "يجري محادثة مدعومة في لقاء أول ويسأل ثلاثة أسئلة.", [exposure(9, "use", "Choose the right question for a name, place, or person.", "اختر السؤال الصحيح للاسم أو المكان أو الشخص."), exposure(13, "hear", "Listen to a meeting twice: first for the situation, then for question words.", "استمع إلى لقاء مرتين: مرة للموقف ومرة لكلمات السؤال."), exposure(14, "retrieve", "Use one question word in the speaking rehearsal.", "استخدم كلمة سؤال واحدة في تدريب الكلام.")], ["interaction", "speaking", "standard"]),
    lesson(14, "speaking", "Say it with confidence", "قلها بثقة", "Rehearse the whole module with pronunciation, pacing, and choice rather than demanding perfect speech on the first attempt.", "تدرّب على الوحدة كاملة بالنطق والإيقاع والاختيار بدلاً من طلب كلام مثالي من المحاولة الأولى.", ["hello", "name", "age", "family", "job", "friend"], "Review: sentence building with be, have, and question words", "مراجعة: بناء الجملة مع be وhave وكلمات السؤال", "Today the grammar is a toolbox review. Choose the right small word, put the words in a clear order, and make your message understandable. Clear and brave is more useful than silent perfection.", "قواعد اليوم مراجعة لصندوق الأدوات. اختر الكلمة الصغيرة المناسبة، ورتب الكلمات بوضوح، واجعل رسالتك مفهومة. الوضوح والشجاعة أنفع من الكمال الصامت.", "Deliver a 30–45 second introduction and respond to simple questions.", "يقدم تعريفاً من 30 إلى 45 ثانية ويجيب عن أسئلة بسيطة.", [exposure(10, "hear", "Listen for sentence rhythm in the complete model conversation.", "استمع إلى إيقاع الجمل في المحادثة النموذجية الكاملة."), exposure(14, "use", "Repeat in short sections, then perform the conversation in one flow.", "كرّر في مقاطع قصيرة ثم أدِّ المحادثة في تدفق واحد."), exposure(15, "retrieve", "Choose the words you still need to review before the assessment.", "اختر الكلمات التي ما زلت تحتاج إلى مراجعتها قبل التقييم.")], ["speaking", "interaction", "review"]),
    lesson(15, "assessment", "Meeting people: show what you can do", "التعرّف إلى الناس: أثبت ما تستطيع فعله", "Close the module with a supportive performance: recognize, choose, read, write, speak, and reflect on the same core language.", "اختم الوحدة بأداء داعم: يتعرف المتعلم إلى اللغة ويختارها ويقرأها ويكتبها وينطقها ويفكر في تعلمه.", ["hello", "name", "I", "you", "my", "your", "family", "job", "friend"], "Cumulative review: be, have, a/an, word order, and questions", "مراجعة تراكمية: be وhave وa/an وترتيب الكلمات والأسئلة", "An assessment is not a surprise trick. It is a chance to show the language you have practiced in different ways. A mistake tells us what to review next.", "التقييم ليس خدعة مفاجئة. إنه فرصة لإظهار اللغة التي تدربت عليها بطرق مختلفة. والخطأ يخبرنا بما نراجعه بعد ذلك.", "Complete a first-meeting task with at least one reading, writing, speaking, and contextual quiz success.", "ينجز مهمة لقاء أول تتضمن نجاحاً واحداً على الأقل في القراءة والكتابة والكلام واختبار سياقي.", [exposure(15, "retrieve", "Choose eight mixed questions from the module bank without spelling traps.", "اختر ثمانية أسئلة متنوعة من بنك الوحدة من دون فخاخ إملائية."), exposure(15, "read", "Read a short profile and answer who, where, and what questions.", "اقرأ تعريفاً قصيراً وأجب عن أسئلة من وأين وماذا."), exposure(15, "write", "Write a five-sentence introduction using the word bank.", "اكتب تعريفاً من خمس جمل باستخدام بنك الكلمات."), exposure(15, "use", "Say the introduction and answer two follow-up questions.", "قل التعريف وأجب عن سؤالين متابعين."), exposure(15, "retrieve", "Mark words as remembered, understood, or needing another review.", "ضع علامة على الكلمات التي تذكرتها أو فهمتها أو تحتاج إلى مراجعة أخرى.")], ["assessment", "reading", "writing", "speaking", "review"]),
  ],
  assessmentRecipe: [
    "Eight contextual questions: greetings, identity, be, have, a/an, question words, family, and professions.",
    "One short reading profile with who, where, age, and job comprehension checks.",
    "One five-sentence guided introduction using at least six module words.",
    "One spoken first-meeting performance with replay and a second attempt available.",
    "A review decision that returns missed words to the module word bank instead of blocking the learner without guidance.",
  ],
  assessmentRecipeArabic: [
    "ثمانية أسئلة سياقية عن التحيات والهوية وbe وhave وa/an وكلمات السؤال والعائلة والمهن.",
    "قراءة تعريف قصيرة مع أسئلة فهم عن من وأين والعمر والعمل.",
    "تعريف موجّه من خمس جمل باستخدام ست كلمات على الأقل من الوحدة.",
    "أداء شفهي في لقاء أول مع إمكانية إعادة التشغيل والمحاولة الثانية.",
    "قرار مراجعة يعيد الكلمات التي أخطأ فيها المتعلم إلى بنك كلمات الوحدة بدلاً من إيقافه بلا إرشاد.",
  ],
};

export const A1_IMMERSIVE_MODULES: ImmersiveModuleAuthoring[] = [A1_MEETING_PEOPLE_IMMERSIVE, ...A1_REMAINING_IMMERSIVE_MODULES];

export function getA1ImmersiveModule(moduleNumber: number) {
  return A1_IMMERSIVE_MODULES.find((module) => module.moduleNumber === moduleNumber);
}

export function buildImmersiveExposureIndex(module?: ImmersiveModuleAuthoring) {
  const index: Record<string, ImmersiveLessonBlueprint["exposurePlan"]> = {};
  const modules = module ? [module] : A1_IMMERSIVE_MODULES;
  for (const authoredModule of modules) {
    for (const lesson of authoredModule.lessonBlueprints) {
      for (const word of lesson.vocabularyAnchors) {
        index[word] = [...(index[word] ?? []), ...lesson.exposurePlan];
      }
    }
  }
  return index;
}
