import type {
  LessonActivity,
  LessonExperienceStage,
  LessonProgressionStage,
  ProgressiveSupport,
  ReadingCheck,
  VisualVocabularyItem,
} from "./types";

type LegacyBilingualReadingCheck = {
  id: string;
  question: string;
  questionArabic: string;
  answer: string;
  answerArabic?: string;
};

type Module3ActivityDraft = Omit<LessonActivity, "stage" | "progressiveSupports" | "readingChecks"> & {
  stage: LessonProgressionStage | LessonExperienceStage;
  progressiveSupports: Array<ProgressiveSupport | "accessible-tip">;
  readingChecks?: Array<ReadingCheck | LegacyBilingualReadingCheck>;
};

const activityStageMap: Record<LessonExperienceStage, LessonProgressionStage> = {
  orientation: "introduction",
  encounter: "introduction",
  notice: "explanation",
  "supported-practice": "guided-practice",
  "meaningful-use": "real-context",
  retrieval: "review",
  evidence: "assessment",
  "next-bridge": "review",
};

function toLessonActivity(activity: Module3ActivityDraft): LessonActivity {
  const stage: LessonProgressionStage = activity.stage in activityStageMap
    ? activityStageMap[activity.stage as LessonExperienceStage]
    : activity.stage as LessonProgressionStage;
  const readingChecks = activity.readingChecks?.map((check) => {
    if ("prompt" in check) return check;
    return {
      id: check.id,
      type: "detail" as const,
      prompt: check.question,
      promptArabic: check.questionArabic,
      answer: check.answer,
      explanation: check.answerArabic,
    };
  });

  return {
    ...activity,
    stage,
    progressiveSupports: activity.progressiveSupports.map((support) => support === "accessible-tip" ? "tip" : support),
    readingChecks,
  };
}

const fruitBasketVisuals: VisualVocabularyItem[] = [
  { id: "a1-m3-l31-apple", word: "apple", arabic: "تفاحة", pronunciation: "/ˈæpəl/", exampleEN: "The apple is red.", exampleAR: "التفاحة حمراء.", altText: "A red apple in a small fruit basket", category: "Fruit", interactionHint: "Hear apple, find the round red fruit, then say the word once." },
  { id: "a1-m3-l31-banana", word: "banana", arabic: "موزة", pronunciation: "/bəˈnɑːnə/", exampleEN: "I have a banana.", exampleAR: "لدي موزة.", altText: "A yellow banana in a small fruit basket", category: "Fruit", interactionHint: "Hear banana, find the long yellow fruit, then repeat it slowly." },
  { id: "a1-m3-l31-orange", word: "orange", arabic: "برتقالة", pronunciation: "/ˈɒrɪndʒ/", exampleEN: "This orange is sweet.", exampleAR: "هذه البرتقالة حلوة.", altText: "An orange beside an apple and a banana", category: "Fruit", interactionHint: "Hear orange, point to the round orange fruit before opening the English label." },
  { id: "a1-m3-l31-water", word: "water", arabic: "ماء", pronunciation: "/ˈwɔːtə/", exampleEN: "I drink water.", exampleAR: "أنا أشرب الماء.", altText: "A glass of water beside a fruit basket", category: "Drinks", interactionHint: "Hear water, find the drink, and notice that it is not counted one by one today." },
];

const vegetableVisuals: VisualVocabularyItem[] = [
  { id: "a1-m3-l38-tomato", word: "tomato", arabic: "طماطم", pronunciation: "/təˈmɑːtəʊ/", exampleEN: "The tomato is red.", exampleAR: "الطماطم حمراء.", altText: "A red tomato beside other vegetables", category: "Vegetables", interactionHint: "Hear tomato, find the round red vegetable, then choose its English word." },
  { id: "a1-m3-l38-potato", word: "potato", arabic: "بطاطا", pronunciation: "/pəˈteɪtəʊ/", exampleEN: "We need potatoes.", exampleAR: "نحتاج إلى بطاطا.", altText: "Two brown potatoes in a market crate", category: "Vegetables", interactionHint: "Hear potato and notice its first sound before repeating the word." },
  { id: "a1-m3-l38-carrot", word: "carrot", arabic: "جزر", pronunciation: "/ˈkærət/", exampleEN: "The carrot is orange.", exampleAR: "الجزرة برتقالية.", altText: "An orange carrot with green leaves", category: "Vegetables", interactionHint: "Hear carrot, find the long orange vegetable, then use the colour as a clue." },
  { id: "a1-m3-l38-onion", word: "onion", arabic: "بصل", pronunciation: "/ˈʌnjən/", exampleEN: "An onion is on the table.", exampleAR: "بصلة على الطاولة.", altText: "A brown onion on a small market table", category: "Vegetables", interactionHint: "Hear onion, find the round brown vegetable, then try the first sound /ʌ/." },
];

const authoredActivities: Record<number, Module3ActivityDraft[]> = {
  31: [
    {
      id: "a1-m3-l31-fruit-basket",
      kind: "visual-vocabulary",
      title: "Choose from a small fruit basket",
      titleArabic: "اختر من سلة فاكهة صغيرة",
      objective: "Recognise three everyday fruit words and water through a calm picture-and-sound encounter before making a preference sentence.",
      objectiveArabic: "تعرّف على ثلاث كلمات فاكهة يومية وكلمة water عبر صورة وصوت هادئين قبل تكوين جملة تفضيل.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: fruitBasketVisuals,
    },
    {
      id: "a1-m3-l31-basket-choice",
      kind: "interaction",
      title: "Pick one thing for a picnic",
      titleArabic: "اختر شيئاً واحداً للنزهة",
      objective: "Use I like ___ or I want ___ to make one low-pressure choice from the practice basket.",
      objectiveArabic: "استخدم I like ___ أو I want ___ لاختيار بسيط من سلة التدريب من دون ضغط.",
      stage: "guided-practice",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "tip"],
      interactionTurns: [
        { id: "a1-m3-l31-pick-1", speaker: "Picture", text: "apple · banana · water", textArabic: "تفاحة · موزة · ماء", purpose: "Choose one item and complete: I like ___." },
        { id: "a1-m3-l31-pick-2", speaker: "Model", text: "I want water, please.", textArabic: "أريد ماءً، من فضلك.", purpose: "Hear a polite choice that will return at the market." },
      ],
    },
    {
      id: "a1-m3-l31-fruit-recall",
      kind: "review",
      title: "Name one basket item before looking",
      titleArabic: "سمِّ عنصراً واحداً من السلة قبل أن تنظر",
      objective: "Retrieve one new food word without turning the first food lesson into a memorisation test.",
      objectiveArabic: "استرجع كلمة طعام جديدة من دون تحويل أول درس للطعام إلى اختبار حفظ.",
      stage: "review",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["tip"],
      writingPrompt: "Hide the labels for a moment. Can you say apple, banana, orange, or water? One word is enough; then check calmly.",
      writingPromptArabic: "أخفِ الملصقات للحظة. هل تستطيع قول apple أو banana أو orange أو water؟ كلمة واحدة تكفي، ثم تحقق بهدوء.",
      suggestedVocabulary: ["apple", "banana", "orange", "water"],
    },
  ],
  32: [
    {
      id: "a1-m3-l32-like-notice",
      kind: "standard",
      title: "Notice like and do not like",
      titleArabic: "لاحظ like وdo not like",
      objective: "Understand that like expresses a preference and do not like expresses a different preference; both are useful, respectful answers.",
      objectiveArabic: "افهم أن like تعبّر عن تفضيل وdo not like تعبّر عن تفضيل مختلف؛ وكلاهما إجابة مفيدة ومحترمة.",
      stage: "explanation",
      estimatedMinutes: 7,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      sentencePatterns: ["I like apples.", "I like tea.", "I do not like coffee.", "I do not like fish."],
      writingPrompt: "Read the whole helpful chunk: I like ___. For a different choice, add do not: I do not like ___. You are practising English, not defending a real preference.",
      writingPromptArabic: "اقرأ التركيب المفيد كاملاً: I like ___. ولخيار مختلف أضف do not: I do not like ___. أنت تتدرب على الإنجليزية، ولست مضطراً للدفاع عن تفضيل حقيقي.",
    },
    {
      id: "a1-m3-l32-cafe-cards",
      kind: "interaction",
      title: "Match the person to a café card",
      titleArabic: "طابق الشخص مع بطاقة مقهى",
      objective: "Choose a like or do not like sentence from meaning in a small café scene rather than from word shape alone.",
      objectiveArabic: "اختر جملة like أو do not like من المعنى في مشهد مقهى صغير لا من شكل الكلمات وحده.",
      stage: "guided-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l32-card-1", speaker: "Hana", text: "Hana smiles and chooses tea.", textArabic: "تبتسم هنا وتختار الشاي.", purpose: "Choose: I like tea." },
        { id: "a1-m3-l32-card-2", speaker: "Omar", text: "Omar moves the coffee away.", textArabic: "يبعد عمر القهوة عنه.", purpose: "Choose: I do not like coffee." },
        { id: "a1-m3-l32-card-3", speaker: "You", text: "Choose any practice card.", textArabic: "اختر أي بطاقة تدريب.", purpose: "Say one full preference sentence; a fictional choice is fine." },
      ],
    },
    {
      id: "a1-m3-l32-preference-rehearsal",
      kind: "speaking",
      title: "Say one clear preference",
      titleArabic: "قل تفضيلاً واحداً بوضوح",
      objective: "Rehearse the rhythm of I like and I do not like in short lines before a reading lesson uses the phrases naturally.",
      objectiveArabic: "تدرّب على إيقاع I like وI do not like في جمل قصيرة قبل أن يستخدمها درس القراءة بشكل طبيعي.",
      stage: "meaningful-use",
      estimatedMinutes: 5,
      semantic: "activity",
      progressiveSupports: ["transcript", "tip"],
      speakingLines: [
        { id: "a1-m3-l32-line-1", speaker: "Hana", text: "I like apples.", textArabic: "أنا أحب التفاح.", pronunciationHint: "Keep I like together; let apples stay clear at the end.", audioText: "I like apples." },
        { id: "a1-m3-l32-line-2", speaker: "Omar", text: "I do not like coffee.", textArabic: "أنا لا أحب القهوة.", pronunciationHint: "Say do not as two calm words; do not rush the negative.", audioText: "I do not like coffee." },
      ],
    },
  ],
  33: [
    {
      id: "a1-m3-l33-food-drink-sort",
      kind: "interaction",
      title: "Sort food and drinks for a table",
      titleArabic: "رتّب الطعام والشراب لطاولة",
      objective: "Recognise familiar food and drink words by giving them a useful place in a breakfast-table scene.",
      objectiveArabic: "تعرّف على كلمات الطعام والشراب المألوفة بوضعها في مكان مفيد في مشهد طاولة فطور.",
      stage: "encounter",
      estimatedMinutes: 8,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support", "worked-example"],
      interactionTurns: [
        { id: "a1-m3-l33-sort-1", speaker: "Food", text: "bread · rice · egg", textArabic: "خبز · أرز · بيضة", purpose: "Put these useful words on the food side of the table." },
        { id: "a1-m3-l33-sort-2", speaker: "Drinks", text: "water · tea · milk", textArabic: "ماء · شاي · حليب", purpose: "Put these useful words on the drinks side of the table." },
        { id: "a1-m3-l33-sort-3", speaker: "Reminder", text: "A word can be useful before you can explain every grammar rule about it.", textArabic: "يمكن أن تكون الكلمة مفيدة قبل أن تشرح كل قاعدة عنها.", purpose: "Keep the focus on meaning and an ordinary meal." },
      ],
    },
    {
      id: "a1-m3-l33-breakfast-lines",
      kind: "speaking",
      title: "Build a simple breakfast line",
      titleArabic: "ابنِ جملة فطور بسيطة",
      objective: "Say a two-part breakfast choice using familiar food words, without requiring a personal meal description.",
      objectiveArabic: "قل اختيار فطور من جزأين مستخدماً كلمات الطعام المألوفة من دون إلزام بوصف وجبتك الشخصية.",
      stage: "meaningful-use",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "transcript", "word-support"],
      speakingLines: [
        { id: "a1-m3-l33-line-1", speaker: "Model", text: "I have bread and tea.", textArabic: "لدي خبز وشاي.", pronunciationHint: "Say bread and tea as two separate useful food words.", audioText: "I have bread and tea." },
        { id: "a1-m3-l33-line-2", speaker: "Model", text: "I have an egg and milk.", textArabic: "لدي بيضة وحليب.", pronunciationHint: "Notice an before egg; this is a sound-friendly pair.", audioText: "I have an egg and milk." },
      ],
    },
    {
      id: "a1-m3-l33-food-map",
      kind: "review",
      title: "Keep a small food map",
      titleArabic: "احتفظ بخريطة طعام صغيرة",
      objective: "Select two words that will be useful in tomorrow’s breakfast reading instead of trying to carry every food word forward.",
      objectiveArabic: "اختر كلمتين ستكونان مفيدتين في قراءة فطور الغد بدلاً من محاولة حمل كل كلمات الطعام إلى الأمام.",
      stage: "next-bridge",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Choose two words for the next reading: bread, egg, tea, milk, rice, or water. Say them once, then look for them tomorrow.",
      writingPromptArabic: "اختر كلمتين للقراءة التالية: bread أو egg أو tea أو milk أو rice أو water. قلْهما مرة ثم ابحث عنهما غداً.",
      suggestedVocabulary: ["bread", "egg", "tea", "milk", "rice", "water"],
    },
  ],
  34: [
    {
      id: "a1-m3-l34-breakfast-reading",
      kind: "reading",
      title: "Read a small breakfast card",
      titleArabic: "اقرأ بطاقة فطور صغيرة",
      objective: "Read for a simple choice and notice previously met food words in a short, supported message.",
      objectiveArabic: "اقرأ لاكتشاف اختيار بسيط ولاحظ كلمات الطعام التي قابلتها سابقاً في رسالة قصيرة مدعومة.",
      stage: "encounter",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "word-support", "worked-example"],
      readingText: "It is morning. Hana has bread, an egg, and tea. Omar has rice and water. Hana likes tea. Omar does not like tea.",
      readingTextArabic: "إنه الصباح. لدى هنا خبز وبيضة وشاي. لدى عمر أرز وماء. هنا تحب الشاي. عمر لا يحب الشاي.",
      readingChecks: [
        { id: "a1-m3-l34-check-1", question: "What does Hana have?", questionArabic: "ماذا لدى هنا؟", answer: "Bread, an egg, and tea.", answerArabic: "خبز وبيضة وشاي." },
        { id: "a1-m3-l34-check-2", question: "Who does not like tea?", questionArabic: "من لا يحب الشاي؟", answer: "Omar.", answerArabic: "عمر." },
      ],
    },
    {
      id: "a1-m3-l34-reading-clues",
      kind: "standard",
      title: "Find the answer in the line",
      titleArabic: "اعثر على الإجابة في السطر",
      objective: "Practise returning to one relevant line in a reading rather than guessing from a single familiar word.",
      objectiveArabic: "تدرّب على العودة إلى سطر ذي صلة في القراءة بدلاً من التخمين من كلمة مألوفة واحدة.",
      stage: "supported-practice",
      estimatedMinutes: 5,
      semantic: "tip",
      progressiveSupports: ["worked-example", "tip"],
      sentencePatterns: ["Hana has bread, an egg, and tea.", "Omar does not like tea."],
      writingPrompt: "For What does Hana have?, point to the whole line with Hana has. A reading answer lives in the text; you do not need to remember it perfectly.",
      writingPromptArabic: "لسؤال What does Hana have?، أشر إلى السطر الكامل الذي فيه Hana has. إجابة القراءة موجودة في النص؛ لا تحتاج إلى حفظها تماماً.",
    },
    {
      id: "a1-m3-l34-menu-response",
      kind: "interaction",
      title: "Choose one line for a new breakfast card",
      titleArabic: "اختر جملة واحدة لبطاقة فطور جديدة",
      objective: "Use the reading model to choose a true sentence about a fictional breakfast card.",
      objectiveArabic: "استخدم نموذج القراءة لاختيار جملة صحيحة عن بطاقة فطور خيالية.",
      stage: "evidence",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l34-choice-1", speaker: "New card", text: "Amina: milk and bread", textArabic: "أمينة: حليب وخبز", purpose: "Choose: Amina has milk and bread." },
        { id: "a1-m3-l34-choice-2", speaker: "New card", text: "Sami: water; no coffee", textArabic: "سامي: ماء؛ لا قهوة", purpose: "Choose: Sami does not like coffee." },
      ],
    },
  ],
  35: [
    {
      id: "a1-m3-l35-count-notice",
      kind: "standard",
      title: "See food as pieces or a shared amount",
      titleArabic: "شاهد الطعام كقطع أو كمية مشتركة",
      objective: "Notice a practical difference: an egg can be one or two, while rice is treated as an amount in today’s market language.",
      objectiveArabic: "لاحظ فرقاً عملياً: يمكن أن تكون البيضة واحدة أو اثنتين، بينما يُعامل الأرز ككمية في لغة السوق اليوم.",
      stage: "notice",
      estimatedMinutes: 8,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      sentencePatterns: ["one egg", "two eggs", "some rice", "some water"],
      writingPrompt: "Do not learn a long grammar label today. Use this market idea: eggs are easy to count; rice and water are asked for as some or an amount.",
      writingPromptArabic: "لا تتعلم اسماً طويلاً للقاعدة اليوم. استخدم فكرة السوق هذه: من السهل عدّ البيض؛ أما الأرز والماء فنطلب بعضاً منهما أو كمية منهما.",
    },
    {
      id: "a1-m3-l35-basket-builder",
      kind: "interaction",
      title: "Build a basket with the right amount",
      titleArabic: "ابنِ سلة بالكمية الصحيحة",
      objective: "Choose one, two, or some from the meaning of a tiny shopping basket, with a model available when needed.",
      objectiveArabic: "اختر one أو two أو some من معنى سلة تسوق صغيرة مع نموذج متاح عند الحاجة.",
      stage: "guided-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l35-basket-1", speaker: "Basket", text: "🍳 🍳", textArabic: "بيضتان", purpose: "Say: two eggs." },
        { id: "a1-m3-l35-basket-2", speaker: "Basket", text: "A small bowl of rice", textArabic: "وعاء صغير من الأرز", purpose: "Say: some rice." },
        { id: "a1-m3-l35-basket-3", speaker: "Basket", text: "One banana", textArabic: "موزة واحدة", purpose: "Say: one banana." },
      ],
    },
    {
      id: "a1-m3-l35-market-request",
      kind: "speaking",
      title: "Ask for a small amount",
      titleArabic: "اطلب كمية صغيرة",
      objective: "Say a clear request for food using a number or some, preparing the learner for a polite market exchange.",
      objectiveArabic: "قل طلباً واضحاً للطعام باستخدام رقم أو some، تمهيداً لحوار مهذب في السوق.",
      stage: "meaningful-use",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "tip"],
      speakingLines: [
        { id: "a1-m3-l35-line-1", speaker: "Customer", text: "Two eggs, please.", textArabic: "بيضتان، من فضلك.", pronunciationHint: "Pause after eggs; please makes the request friendly.", audioText: "Two eggs, please." },
        { id: "a1-m3-l35-line-2", speaker: "Customer", text: "Some rice, please.", textArabic: "بعض الأرز، من فضلك.", pronunciationHint: "Keep some rice together as one useful market chunk.", audioText: "Some rice, please." },
      ],
    },
  ],
  36: [
    {
      id: "a1-m3-l36-market-entrance",
      kind: "interaction",
      title: "Enter a friendly practice market",
      titleArabic: "ادخل سوق تدريب ودياً",
      objective: "Follow a short customer-and-seller exchange that gives new food language a practical purpose.",
      objectiveArabic: "اتبع تبادلاً قصيراً بين زبون وبائع يمنح لغة الطعام الجديدة غرضاً عملياً.",
      stage: "encounter",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "transcript", "worked-example"],
      interactionTurns: [
        { id: "a1-m3-l36-turn-1", speaker: "Seller", text: "Hello. Can I help you?", textArabic: "مرحباً. هل يمكنني مساعدتك؟", purpose: "Hear a helpful market opening." },
        { id: "a1-m3-l36-turn-2", speaker: "Customer", text: "Yes, please. Two apples.", textArabic: "نعم، من فضلك. تفاحتان.", purpose: "Make a small specific request." },
        { id: "a1-m3-l36-turn-3", speaker: "Seller", text: "Here you are.", textArabic: "تفضل.", purpose: "Notice a common friendly hand-over phrase." },
      ],
    },
    {
      id: "a1-m3-l36-polite-request-builder",
      kind: "standard",
      title: "Build one polite request",
      titleArabic: "ابنِ طلباً مهذباً واحداً",
      objective: "Use Can I have ...? as a complete useful request, not as an isolated grammar formula.",
      objectiveArabic: "استخدم Can I have ...? كطلب مفيد كامل لا كصيغة قواعد معزولة.",
      stage: "supported-practice",
      estimatedMinutes: 6,
      semantic: "example",
      progressiveSupports: ["worked-example", "word-support", "tip"],
      sentencePatterns: ["Can I have two apples, please?", "Can I have some rice, please?", "Can I have water, please?"],
      writingPrompt: "Start with Can I have, add one thing, then finish with please. You can use the practice market and do not need to name a real shop.",
      writingPromptArabic: "ابدأ بـ Can I have، أضف شيئاً واحداً، ثم اختم بـ please. يمكنك استخدام سوق التدريب ولا تحتاج إلى تسمية متجر حقيقي.",
    },
    {
      id: "a1-m3-l36-market-evidence",
      kind: "assessment",
      title: "Choose the helpful market line",
      titleArabic: "اختر جملة السوق المفيدة",
      objective: "Show that you can select a polite request that matches the item and quantity in context.",
      objectiveArabic: "أظهر أنك تستطيع اختيار طلب مهذب يطابق الغرض والكمية في السياق.",
      stage: "evidence",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l36-check-1", speaker: "Need", text: "You need two bananas.", textArabic: "تحتاج إلى موزتين.", purpose: "Choose: Can I have two bananas, please?" },
        { id: "a1-m3-l36-check-2", speaker: "Need", text: "You need rice for the practice meal.", textArabic: "تحتاج إلى أرز لوجبة التدريب.", purpose: "Choose: Can I have some rice, please?" },
      ],
    },
  ],
  37: [
    {
      id: "a1-m3-l37-price-listen",
      kind: "speaking",
      title: "Hear a price, then ask once",
      titleArabic: "استمع إلى سعر ثم اسأل مرة",
      objective: "Hear price as a useful market word and rehearse How much is it? with a small, concrete item.",
      objectiveArabic: "استمع إلى price ككلمة سوق مفيدة وتدرّب على How much is it? مع غرض صغير ومحدد.",
      stage: "encounter",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["transcript", "arabic-help", "tip"],
      speakingLines: [
        { id: "a1-m3-l37-line-1", speaker: "Customer", text: "How much is it?", textArabic: "كم سعره؟", pronunciationHint: "Keep How much together; it is one useful question chunk.", audioText: "How much is it?" },
        { id: "a1-m3-l37-line-2", speaker: "Seller", text: "It is two pounds.", textArabic: "سعره جنيهان.", pronunciationHint: "Listen for two; the exact currency can change, but the price answer pattern stays useful.", audioText: "It is two pounds." },
      ],
    },
    {
      id: "a1-m3-l37-price-pairing",
      kind: "interaction",
      title: "Pair the question and answer",
      titleArabic: "طابق السؤال والإجابة",
      objective: "Connect a price question with its answer before adding numbers to a longer market role-play.",
      objectiveArabic: "اربط سؤال السعر بإجابته قبل إضافة الأرقام إلى تمثيل دور أطول في السوق.",
      stage: "supported-practice",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l37-pair-1", speaker: "Customer", text: "How much is the apple?", textArabic: "كم سعر التفاحة؟", purpose: "Pair it with: It is one pound." },
        { id: "a1-m3-l37-pair-2", speaker: "Customer", text: "How much is the tea?", textArabic: "كم سعر الشاي؟", purpose: "Pair it with: It is two pounds." },
      ],
    },
    {
      id: "a1-m3-l37-price-task",
      kind: "speaking",
      title: "Ask about one market card",
      titleArabic: "اسأل عن بطاقة سوق واحدة",
      objective: "Produce one complete price question aloud, quietly, or in writing; each mode counts as useful rehearsal.",
      objectiveArabic: "أنتج سؤال سعر كاملاً بصوت عالٍ أو بهدوء أو كتابةً؛ كل طريقة تُعد تدريباً مفيداً.",
      stage: "meaningful-use",
      estimatedMinutes: 4,
      semantic: "activity",
      progressiveSupports: ["worked-example", "tip"],
      speakingLines: [
        { id: "a1-m3-l37-line-3", speaker: "Your turn", text: "How much is the ___?", textArabic: "كم سعر الـ___؟", pronunciationHint: "Use apple, banana, water, tea, or a word from the practice cards.", audioText: "How much is the item?" },
      ],
    },
  ],
  38: [
    {
      id: "a1-m3-l38-vegetable-crate",
      kind: "visual-vocabulary",
      title: "Open a vegetable market crate",
      titleArabic: "افتح صندوق خضار في السوق",
      objective: "Recognise four vegetables through colour, shape, and sound before using them in a choice task.",
      objectiveArabic: "تعرّف على أربع خضروات من خلال اللون والشكل والصوت قبل استخدامها في مهمة اختيار.",
      stage: "encounter",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: vegetableVisuals,
    },
    {
      id: "a1-m3-l38-colour-clues",
      kind: "interaction",
      title: "Use a colour clue, then say the word",
      titleArabic: "استخدم دليل اللون ثم قل الكلمة",
      objective: "Choose a vegetable from a concrete clue so meaning, image, and English label stay connected.",
      objectiveArabic: "اختر خضاراً من دليل واضح حتى يبقى المعنى والصورة والملصق الإنجليزي مترابطين.",
      stage: "supported-practice",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l38-clue-1", speaker: "Clue", text: "It is long and orange.", textArabic: "إنها طويلة وبرتقالية.", purpose: "Choose carrot." },
        { id: "a1-m3-l38-clue-2", speaker: "Clue", text: "It is round and red.", textArabic: "إنها مستديرة وحمراء.", purpose: "Choose tomato." },
        { id: "a1-m3-l38-clue-3", speaker: "Clue", text: "It is brown and grows under the ground.", textArabic: "إنها بنية وتنمو تحت الأرض.", purpose: "Choose potato; this is a picture clue, not a scientific test." },
      ],
    },
    {
      id: "a1-m3-l38-vegetable-recall",
      kind: "review",
      title: "Keep two vegetables for the list",
      titleArabic: "احتفظ بخضرواتين للقائمة",
      objective: "Retrieve two vegetable words that will return in the shopping-list reading, without adding a new grammar burden.",
      objectiveArabic: "استرجع كلمتي خضروات ستعودان في قراءة قائمة التسوق من دون إضافة عبء قواعد جديد.",
      stage: "next-bridge",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["tip", "word-support"],
      writingPrompt: "Choose two words to carry to the list: tomato, potato, carrot, or onion. Say them once, then find them in tomorrow’s list.",
      writingPromptArabic: "اختر كلمتين لتحملهما إلى القائمة: tomato أو potato أو carrot أو onion. قلْهما مرة ثم ابحث عنهما في قائمة الغد.",
      suggestedVocabulary: ["tomato", "potato", "carrot", "onion"],
    },
  ],
  39: [
    {
      id: "a1-m3-l39-shopping-list-reading",
      kind: "reading",
      title: "Read a short shopping list",
      titleArabic: "اقرأ قائمة تسوق قصيرة",
      objective: "Read a real-world list for what is needed, using familiar food words and a few quantity clues.",
      objectiveArabic: "اقرأ قائمة من الحياة اليومية لمعرفة المطلوب مستخدماً كلمات الطعام المألوفة وبعض دلائل الكمية.",
      stage: "encounter",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "word-support", "worked-example"],
      readingText: "Shopping list: two apples, some rice, milk, two eggs, tomatoes, and water. We do not need coffee today.",
      readingTextArabic: "قائمة التسوق: تفاحتان، بعض الأرز، حليب، بيضتان، طماطم، وماء. لا نحتاج إلى قهوة اليوم.",
      readingChecks: [
        { id: "a1-m3-l39-check-1", question: "How many apples do we need?", questionArabic: "كم تفاحة نحتاج؟", answer: "Two apples.", answerArabic: "تفاحتان." },
        { id: "a1-m3-l39-check-2", question: "Do we need coffee today?", questionArabic: "هل نحتاج إلى قهوة اليوم؟", answer: "No, we do not.", answerArabic: "لا، لا نحتاج إليها." },
      ],
    },
    {
      id: "a1-m3-l39-list-tick",
      kind: "interaction",
      title: "Tick what is on the list",
      titleArabic: "ضع علامة على ما في القائمة",
      objective: "Distinguish a listed item from a non-listed item by checking the whole text, not simply recognising a food word.",
      objectiveArabic: "ميّز بين غرض موجود وغير موجود في القائمة بالتحقق من النص كله لا بمجرد معرفة كلمة طعام.",
      stage: "supported-practice",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l39-tick-1", speaker: "Item", text: "two eggs", textArabic: "بيضتان", purpose: "Tick it; the list says two eggs." },
        { id: "a1-m3-l39-tick-2", speaker: "Item", text: "fish", textArabic: "سمك", purpose: "Leave it; fish is not on this list." },
        { id: "a1-m3-l39-tick-3", speaker: "Item", text: "coffee", textArabic: "قهوة", purpose: "Notice the sentence says we do not need coffee." },
      ],
    },
    {
      id: "a1-m3-l39-list-bridge",
      kind: "standard",
      title: "Notice a list can prepare a choice",
      titleArabic: "لاحظ أن القائمة تمهّد لاختيار",
      objective: "Connect reading a list to the next lesson’s meaning-and-grammar choices without requiring a written list yet.",
      objectiveArabic: "اربط قراءة القائمة باختيارات المعنى والقواعد في الدرس التالي من دون طلب كتابة قائمة بعد.",
      stage: "next-bridge",
      estimatedMinutes: 3,
      semantic: "tip",
      progressiveSupports: ["tip"],
      writingPrompt: "A shopping list is a reading tool: it tells you what you need. Keep two details in mind—two eggs and some rice—for the next short check.",
      writingPromptArabic: "قائمة التسوق أداة للقراءة: تخبرك بما تحتاج. احتفظ بتفصيلين في ذهنك: two eggs وsome rice للفحص القصير التالي.",
    },
  ],
  40: [
    {
      id: "a1-m3-l40-meaning-choice",
      kind: "standard",
      title: "Choose meaning before grammar labels",
      titleArabic: "اختر المعنى قبل أسماء القواعد",
      objective: "Use food contexts to choose a, an, some, How many, or How much without turning the lesson into a list of abstract terms.",
      objectiveArabic: "استخدم سياقات الطعام لاختيار a أو an أو some أو How many أو How much من دون تحويل الدرس إلى قائمة مصطلحات مجردة.",
      stage: "notice",
      estimatedMinutes: 8,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      sentencePatterns: ["an egg", "some rice", "How many apples?", "How much water?"],
      writingPrompt: "Ask a simple question: can I count the pieces easily? Apples and eggs use How many. Water and rice use How much. Use the model whenever you need it.",
      writingPromptArabic: "اسأل سؤالاً بسيطاً: هل أستطيع عدّ القطع بسهولة؟ نستخدم How many مع apples وeggs. ونستخدم How much مع water وrice. استخدم النموذج متى احتجت.",
    },
    {
      id: "a1-m3-l40-context-check",
      kind: "assessment",
      title: "Complete three market meanings",
      titleArabic: "أكمل ثلاثة معانٍ في السوق",
      objective: "Give low-stakes evidence that food quantity language is selected by meaning in context, not by spelling traps.",
      objectiveArabic: "قدّم دليلاً بسيطاً على أن لغة كمية الطعام تُختار من المعنى في السياق لا من فخاخ التهجئة.",
      stage: "evidence",
      estimatedMinutes: 7,
      semantic: "assessment",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l40-item-1", speaker: "Market card", text: "I need ___ egg.", textArabic: "أحتاج إلى بيضة واحدة.", purpose: "Choose an; egg begins with a vowel sound." },
        { id: "a1-m3-l40-item-2", speaker: "Market card", text: "I need ___ rice.", textArabic: "أحتاج إلى بعض الأرز.", purpose: "Choose some." },
        { id: "a1-m3-l40-item-3", speaker: "Market card", text: "___ bananas do you need?", textArabic: "كم موزة تحتاج؟", purpose: "Choose How many because bananas can be counted." },
      ],
    },
    {
      id: "a1-m3-l40-kind-feedback",
      kind: "review",
      title: "Choose one thing to revisit",
      titleArabic: "اختر شيئاً واحداً لمراجعته",
      objective: "End a compact check by choosing a precise food-language point to review, rather than treating any incorrect answer as failure.",
      objectiveArabic: "اختم فحصاً قصيراً باختيار نقطة محددة من لغة الطعام لمراجعتها بدلاً من اعتبار أي إجابة خاطئة فشلاً.",
      stage: "review",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["tip", "word-support"],
      writingPrompt: "Choose one calm review target: an egg, some rice, How many apples?, or How much water? Say the complete useful chunk once.",
      writingPromptArabic: "اختر هدف مراجعة هادئاً واحداً: an egg أو some rice أو How many apples? أو How much water? قل التركيب المفيد كاملاً مرة.",
    },
  ],
  41: [
    {
      id: "a1-m3-l41-meal-retrieval",
      kind: "review",
      title: "Choose three words for a practice meal",
      titleArabic: "اختر ثلاث كلمات لوجبة تدريب",
      objective: "Retrieve only the food words needed for a short meal description, giving the learner a manageable writing start.",
      objectiveArabic: "استرجع فقط كلمات الطعام اللازمة لوصف وجبة قصيرة، لتمنح المتعلم بداية كتابة قابلة للإدارة.",
      stage: "retrieval",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Choose three words from the practice food cards: bread, rice, egg, milk, apple, banana, tomato, or water. A fictional meal is welcome.",
      writingPromptArabic: "اختر ثلاث كلمات من بطاقات طعام التدريب: bread أو rice أو egg أو milk أو apple أو banana أو tomato أو water. الوجبة الخيالية مرحب بها.",
      suggestedVocabulary: ["bread", "rice", "egg", "milk", "apple", "banana", "tomato", "water"],
    },
    {
      id: "a1-m3-l41-meal-writing",
      kind: "writing",
      title: "Write a tiny meal card",
      titleArabic: "اكتب بطاقة وجبة صغيرة",
      objective: "Write two or three supported sentences about a real or invented meal, using one food choice and one clear full stop.",
      objectiveArabic: "اكتب جملتين أو ثلاثاً مدعومة عن وجبة حقيقية أو خيالية مستخدماً اختيار طعام واحداً ونقطة واضحة واحدة.",
      stage: "meaningful-use",
      estimatedMinutes: 10,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "worked-example", "word-support", "tip"],
      writingPrompt: "Use this small model: I have bread and tea. I like apples. I do not like coffee. Change one or two food words. You may write about a practice meal, not your own meal.",
      writingPromptArabic: "استخدم هذا النموذج الصغير: I have bread and tea. I like apples. I do not like coffee. غيّر كلمة طعام أو كلمتين. يمكنك الكتابة عن وجبة تدريب لا عن وجبتك الخاصة.",
      suggestedVocabulary: ["I have", "I like", "I do not like", "bread", "tea", "apples", "coffee"],
      sentencePatterns: ["I have ___.", "I like ___.", "I do not like ___."],
    },
    {
      id: "a1-m3-l41-writing-self-check",
      kind: "standard",
      title: "Check one sentence at a time",
      titleArabic: "تحقق من جملة واحدة في كل مرة",
      objective: "Build a beginner-safe writing habit: check a capital I, one full stop, and whether a chosen food word matches the intended meaning.",
      objectiveArabic: "ابنِ عادة كتابة آمنة للمبتدئ: تحقق من حرف I الكبير ونقطة واحدة وما إذا كانت كلمة الطعام المختارة تطابق المعنى المقصود.",
      stage: "evidence",
      estimatedMinutes: 5,
      semantic: "tip",
      progressiveSupports: ["worked-example", "tip"],
      writingPrompt: "Read one line only. Is I a capital letter? Is there a full stop? Does the food word say what you mean? Fix one thing, then stop; a short clear card is a success.",
      writingPromptArabic: "اقرأ سطراً واحداً فقط. هل I حرف كبير؟ هل توجد نقطة؟ هل تقول كلمة الطعام ما تقصده؟ أصلح شيئاً واحداً ثم توقف؛ البطاقة القصيرة الواضحة نجاح.",
    },
  ],
  42: [
    {
      id: "a1-m3-l42-market-mission",
      kind: "interaction",
      title: "Choose a small market mission",
      titleArabic: "اختر مهمة سوق صغيرة",
      objective: "Pick a fictional shopping goal and use only the language needed for that goal, rather than performing a long fixed dialogue.",
      objectiveArabic: "اختر هدف تسوق خيالياً واستخدم فقط اللغة اللازمة له بدلاً من أداء حوار طويل ثابت.",
      stage: "orientation",
      estimatedMinutes: 4,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l42-mission-1", speaker: "Mission A", text: "Buy two apples and ask the price.", textArabic: "اشترِ تفاحتين واسأل عن السعر.", purpose: "Use two apples and How much is it?" },
        { id: "a1-m3-l42-mission-2", speaker: "Mission B", text: "Ask for some rice politely.", textArabic: "اطلب بعض الأرز بأدب.", purpose: "Use Can I have some rice, please?" },
      ],
    },
    {
      id: "a1-m3-l42-role-play-turns",
      kind: "interaction",
      title: "Take the customer or seller role",
      titleArabic: "خذ دور الزبون أو البائع",
      objective: "Build a flexible four-turn market exchange by choosing a role and responding to a meaningful prompt.",
      objectiveArabic: "ابنِ تبادلاً مرناً من أربعة أدوار في السوق باختيار دور والرد على مطالبة ذات معنى.",
      stage: "meaningful-use",
      estimatedMinutes: 10,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "word-support", "tip"],
      interactionTurns: [
        { id: "a1-m3-l42-turn-1", speaker: "Seller", text: "Hello. Can I help you?", textArabic: "مرحباً. هل يمكنني مساعدتك؟", purpose: "Begin the exchange." },
        { id: "a1-m3-l42-turn-2", speaker: "Customer", text: "Can I have two apples, please?", textArabic: "هل يمكنني الحصول على تفاحتين، من فضلك؟", purpose: "Make the request." },
        { id: "a1-m3-l42-turn-3", speaker: "Customer", text: "How much is it?", textArabic: "كم سعره؟", purpose: "Ask the price if this fits the selected mission." },
        { id: "a1-m3-l42-turn-4", speaker: "Seller", text: "It is two pounds. Here you are.", textArabic: "سعره جنيهان. تفضل.", purpose: "Close with a clear, friendly response." },
      ],
    },
    {
      id: "a1-m3-l42-market-repair",
      kind: "speaking",
      title: "Use one repair line if you need it",
      titleArabic: "استخدم جملة إصلاح واحدة إذا احتجتها",
      objective: "Practise a polite repair phrase so uncertainty in a role-play becomes a normal communication moment.",
      objectiveArabic: "تدرّب على عبارة إصلاح مهذبة حتى يصبح عدم اليقين في تمثيل الدور لحظة تواصل طبيعية.",
      stage: "evidence",
      estimatedMinutes: 4,
      semantic: "example",
      progressiveSupports: ["transcript", "tip"],
      speakingLines: [
        { id: "a1-m3-l42-repair-1", speaker: "Customer", text: "Can you repeat, please?", textArabic: "هل يمكنك الإعادة، من فضلك؟", pronunciationHint: "Use this calm line if the price answer is too fast.", audioText: "Can you repeat, please?" },
        { id: "a1-m3-l42-repair-2", speaker: "Seller", text: "It is two pounds.", textArabic: "سعره جنيهان.", pronunciationHint: "Listen again after the repair; asking is part of successful communication.", audioText: "It is two pounds." },
      ],
    },
  ],
  43: [
    {
      id: "a1-m3-l43-listen-first",
      kind: "speaking",
      title: "Hear a market basket before seeing it",
      titleArabic: "استمع إلى سلة سوق قبل رؤيتها",
      objective: "Listen for one food item and one quantity in short lines, using the transcript only after a first calm attempt.",
      objectiveArabic: "استمع إلى غرض طعام واحد وكمية واحدة في جمل قصيرة مستخدماً النص فقط بعد محاولة هادئة أولى.",
      stage: "encounter",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["transcript", "arabic-help", "tip"],
      speakingLines: [
        { id: "a1-m3-l43-line-1", speaker: "Seller", text: "Two bananas, please.", textArabic: "موزتان، من فضلك.", pronunciationHint: "Listen for two and bananas before checking the transcript.", audioText: "Two bananas, please." },
        { id: "a1-m3-l43-line-2", speaker: "Customer", text: "Some rice, please.", textArabic: "بعض الأرز، من فضلك.", pronunciationHint: "Listen for some rice as one useful chunk.", audioText: "Some rice, please." },
        { id: "a1-m3-l43-line-3", speaker: "Customer", text: "How much is the water?", textArabic: "كم سعر الماء؟", pronunciationHint: "Listen for the item after How much is.", audioText: "How much is the water?" },
      ],
    },
    {
      id: "a1-m3-l43-basket-choice",
      kind: "interaction",
      title: "Choose the basket you heard",
      titleArabic: "اختر السلة التي سمعتها",
      objective: "Match a spoken line to a small visual basket, proving listening through meaning instead of word-by-word translation.",
      objectiveArabic: "طابق جملة مسموعة مع سلة بصرية صغيرة لإثبات الاستماع من خلال المعنى لا الترجمة كلمة بكلمة.",
      stage: "supported-practice",
      estimatedMinutes: 7,
      semantic: "assessment",
      progressiveSupports: ["worked-example", "transcript", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l43-basket-1", speaker: "Heard", text: "Two bananas, please.", textArabic: "موزتان، من فضلك.", purpose: "Choose the basket with two bananas, not one banana or two apples." },
        { id: "a1-m3-l43-basket-2", speaker: "Heard", text: "Some rice, please.", textArabic: "بعض الأرز، من فضلك.", purpose: "Choose the basket with rice, not the basket with eggs." },
      ],
    },
    {
      id: "a1-m3-l43-response-choice",
      kind: "standard",
      title: "Give the next helpful response",
      titleArabic: "أعطِ الرد المفيد التالي",
      objective: "Respond to a simple heard request with Here you are or a price answer, without adding new language for its own sake.",
      objectiveArabic: "استجب لطلب مسموع بسيط بـ Here you are أو إجابة سعر من دون إضافة لغة جديدة لمجرد الإضافة.",
      stage: "meaningful-use",
      estimatedMinutes: 4,
      semantic: "example",
      progressiveSupports: ["worked-example", "tip"],
      sentencePatterns: ["Here you are.", "It is two pounds.", "Can you repeat, please?"],
      writingPrompt: "Choose the next useful line after the request. You do not need a perfect accent; a clear response or quiet rehearsal counts.",
      writingPromptArabic: "اختر الجملة المفيدة التالية بعد الطلب. لا تحتاج إلى نطق مثالي؛ الرد الواضح أو التدريب الهادئ يُحسب.",
    },
  ],
  44: [
    {
      id: "a1-m3-l44-market-tray-recall",
      kind: "review",
      title: "Pack a market tray from memory",
      titleArabic: "جهّز صينية سوق من الذاكرة",
      objective: "Retrieve a small, purposeful mix of fruit, vegetables, and requests from the module rather than reviewing every item in one dense list.",
      objectiveArabic: "استرجع مزيجاً صغيراً وذا غرض من الفاكهة والخضار والطلبات من الوحدة بدلاً من مراجعة كل العناصر في قائمة كثيفة واحدة.",
      stage: "retrieval",
      estimatedMinutes: 6,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Without looking, name one fruit, one vegetable, and one request: for example apple, tomato, and Can I have ___, please? Then reveal only the words you need.",
      writingPromptArabic: "من دون النظر، سمِّ فاكهة واحدة وخضاراً واحداً وطلباً واحداً: مثلاً apple وtomato وCan I have ___, please? ثم اكشف فقط الكلمات التي تحتاجها.",
      suggestedVocabulary: ["apple", "banana", "tomato", "potato", "Can I have", "How much is it"],
    },
    {
      id: "a1-m3-l44-meaning-paths",
      kind: "interaction",
      title: "Follow two meaning paths",
      titleArabic: "اتبع مسارين للمعنى",
      objective: "Choose language that fits either a preference path or a market-request path, showing that familiar words can do different jobs.",
      objectiveArabic: "اختر لغة تناسب إما مسار التفضيل أو مسار طلب السوق لإظهار أن الكلمات المألوفة يمكن أن تؤدي وظائف مختلفة.",
      stage: "supported-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m3-l44-path-1", speaker: "Preference", text: "You want to say tea is good for you.", textArabic: "تريد أن تقول إن الشاي مناسب لك.", purpose: "Choose: I like tea." },
        { id: "a1-m3-l44-path-2", speaker: "Market", text: "You need two eggs from a seller.", textArabic: "تحتاج إلى بيضتين من بائع.", purpose: "Choose: Can I have two eggs, please?" },
        { id: "a1-m3-l44-path-3", speaker: "Price", text: "You want to know the cost of water.", textArabic: "تريد معرفة سعر الماء.", purpose: "Choose: How much is the water?" },
      ],
    },
    {
      id: "a1-m3-l44-checkpoint-bridge",
      kind: "review",
      title: "Choose a checkpoint helper",
      titleArabic: "اختر مساعداً لاختبار الوحدة",
      objective: "Select one support strategy for tomorrow’s checkpoint so the learner arrives with a plan, not anxiety.",
      objectiveArabic: "اختر استراتيجية دعم واحدة لاختبار الغد حتى يصل المتعلم بخطة لا بقلق.",
      stage: "next-bridge",
      estimatedMinutes: 3,
      semantic: "tip",
      progressiveSupports: ["tip", "accessible-tip"],
      writingPrompt: "For the checkpoint, choose one helper: read the whole sentence, use the picture clue, replay a line, or say one request slowly. A helper is a learning tool, not cheating.",
      writingPromptArabic: "للاختبار، اختر مساعداً واحداً: اقرأ الجملة كاملة، استخدم دليل الصورة، أعد تشغيل الجملة، أو قل طلباً ببطء. المساعد أداة تعلم وليس غشاً.",
    },
  ],
  45: [
    {
      id: "a1-m3-l45-checkpoint-recall",
      kind: "review",
      title: "Warm up with three useful chunks",
      titleArabic: "استعد بثلاثة تراكيب مفيدة",
      objective: "Retrieve one food word, one quantity phrase, and one polite request before the checkpoint begins.",
      objectiveArabic: "استرجع كلمة طعام واحدة وعبارة كمية واحدة وطلباً مهذباً واحداً قبل بدء الاختبار.",
      stage: "retrieval",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Choose three chunks: apple or tomato; two eggs or some rice; Can I have ___, please? A calm start is enough.",
      writingPromptArabic: "اختر ثلاثة تراكيب: apple أو tomato؛ two eggs أو some rice؛ Can I have ___, please? البداية الهادئة تكفي.",
    },
    {
      id: "a1-m3-l45-market-meal-check",
      kind: "assessment",
      title: "Show what you can use at a market and meal",
      titleArabic: "أظهر ما يمكنك استخدامه في السوق والوجبة",
      objective: "Complete small contextual tasks that combine food meaning, quantity, reading, and a polite request without introducing new language.",
      objectiveArabic: "أكمل مهاماً سياقية صغيرة تجمع معنى الطعام والكمية والقراءة وطلباً مهذباً من دون تقديم لغة جديدة.",
      stage: "assessment",
      estimatedMinutes: 12,
      semantic: "assessment",
      progressiveSupports: ["worked-example", "word-support", "transcript", "tip"],
      interactionTurns: [
        { id: "a1-m3-l45-task-1", speaker: "Picture task", text: "A basket has two apples and water.", textArabic: "تحتوي السلة على تفاحتين وماء.", purpose: "Choose the sentence that describes the basket accurately." },
        { id: "a1-m3-l45-task-2", speaker: "Reading task", text: "List: some rice, two eggs, milk. No coffee.", textArabic: "القائمة: بعض الأرز، بيضتان، حليب. لا قهوة.", purpose: "Answer one question by returning to the list." },
        { id: "a1-m3-l45-task-3", speaker: "Market task", text: "You need two bananas.", textArabic: "تحتاج إلى موزتين.", purpose: "Choose or say the polite request that fits." },
        { id: "a1-m3-l45-task-4", speaker: "Listening task", text: "How much is the water? It is two pounds.", textArabic: "كم سعر الماء؟ سعره جنيهان.", purpose: "Match the question to the answer after listening once." },
      ],
    },
    {
      id: "a1-m3-l45-next-step",
      kind: "review",
      title: "Choose one useful next step",
      titleArabic: "اختر خطوة تالية مفيدة",
      objective: "Leave the checkpoint with a precise review choice and a bridge into time and daily-life language, not a judgement about ability.",
      objectiveArabic: "اخرج من الاختبار بخيار مراجعة محدد وجسر إلى لغة الوقت والحياة اليومية، لا بحكم على القدرة.",
      stage: "next-bridge",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["tip", "accessible-tip", "word-support"],
      writingPrompt: "This checkpoint is not a judgement. Choose one useful next step: replay a market line, revisit some and two, reread the list, or carry one food word into tomorrow’s daily-life topic.",
      writingPromptArabic: "هذا الاختبار ليس حكماً. اختر خطوة تالية مفيدة: أعد تشغيل جملة سوق، راجع some وtwo، أعد قراءة القائمة، أو احمل كلمة طعام واحدة إلى موضوع الحياة اليومية غداً.",
    },
  ],
};

export function authoredActivitiesForA1Module3(lessonNumber: number) {
  return authoredActivities[lessonNumber]?.map(toLessonActivity);
}
