import type { LessonActivity, VisualVocabularyItem } from "./types";

const familyVisuals: VisualVocabularyItem[] = [
  { id: "a1-m2-l16-mother", word: "mother", arabic: "أم", pronunciation: "/ˈmʌðə/", exampleEN: "This is my mother.", exampleAR: "هذه أمي.", altText: "A neutral illustration of a mother", category: "Family", interactionHint: "Hear mother, then choose the adult woman in the family picture." },
  { id: "a1-m2-l16-father", word: "father", arabic: "أب", pronunciation: "/ˈfɑːðə/", exampleEN: "This is my father.", exampleAR: "هذا أبي.", altText: "A neutral illustration of a father", category: "Family", interactionHint: "Hear father, then choose the adult man in the family picture." },
  { id: "a1-m2-l16-sister", word: "sister", arabic: "أخت", pronunciation: "/ˈsɪstə/", exampleEN: "This is my sister.", exampleAR: "هذه أختي.", altText: "A neutral illustration of a sister", category: "Family", interactionHint: "Hear sister, then choose the younger female person in the family picture." },
  { id: "a1-m2-l16-brother", word: "brother", arabic: "أخ", pronunciation: "/ˈbrʌðə/", exampleEN: "This is my brother.", exampleAR: "هذا أخي.", altText: "A neutral illustration of a brother", category: "Family", interactionHint: "Hear brother, then choose the younger male person in the family picture." },
];

const roomVisuals: VisualVocabularyItem[] = [
  { id: "a1-m2-l19-home", word: "home", arabic: "منزل", pronunciation: "/həʊm/", exampleEN: "This is our home.", exampleAR: "هذا منزلنا.", altText: "A small home from the outside", category: "Home", interactionHint: "Hear home, then choose the whole building." },
  { id: "a1-m2-l19-kitchen", word: "kitchen", arabic: "مطبخ", pronunciation: "/ˈkɪtʃɪn/", exampleEN: "The kitchen is here.", exampleAR: "المطبخ هنا.", altText: "A simple kitchen with a table", category: "Rooms", interactionHint: "Hear kitchen, then choose the room for cooking." },
  { id: "a1-m2-l19-bedroom", word: "bedroom", arabic: "غرفة نوم", pronunciation: "/ˈbedruːm/", exampleEN: "My bedroom is small.", exampleAR: "غرفة نومي صغيرة.", altText: "A calm bedroom with a bed", category: "Rooms", interactionHint: "Hear bedroom, then choose the room with a bed." },
  { id: "a1-m2-l19-room", word: "room", arabic: "غرفة", pronunciation: "/ruːm/", exampleEN: "This is a room.", exampleAR: "هذه غرفة.", altText: "A simple room", category: "Rooms", interactionHint: "Say room after you hear it; it is the general word." },
];

const furnitureVisuals: VisualVocabularyItem[] = [
  { id: "a1-m2-l21-table", word: "table", arabic: "طاولة", pronunciation: "/ˈteɪbl/", exampleEN: "The book is on the table.", exampleAR: "الكتاب على الطاولة.", altText: "A simple table with a book", category: "Furniture", interactionHint: "Hear table, point to the flat piece of furniture, then reuse the book sentence." },
  { id: "a1-m2-l21-chair", word: "chair", arabic: "كرسي", pronunciation: "/tʃeə/", exampleEN: "The bag is on the chair.", exampleAR: "الحقيبة على الكرسي.", altText: "A simple chair with a bag", category: "Furniture", interactionHint: "Hear chair, point to the seat, then say chair once." },
  { id: "a1-m2-l21-bag", word: "bag", arabic: "حقيبة", pronunciation: "/bæɡ/", exampleEN: "This is my bag.", exampleAR: "هذه حقيبتي.", altText: "A school bag beside a chair", category: "Belongings", interactionHint: "Hear bag, then choose the item that can carry books." },
  { id: "a1-m2-l21-book", word: "book", arabic: "كتاب", pronunciation: "/bʊk/", exampleEN: "This is a book.", exampleAR: "هذا كتاب.", altText: "A closed book on a table", category: "Belongings", interactionHint: "You already met book. Say it once before revealing the label." },
];

const petVisuals: VisualVocabularyItem[] = [
  { id: "a1-m2-l25-cat", word: "cat", arabic: "قطة", pronunciation: "/kæt/", exampleEN: "The cat is at home.", exampleAR: "القطة في المنزل.", altText: "A calm cat sitting beside a small home", category: "Pets", interactionHint: "Hear cat, then choose the animal with pointed ears." },
  { id: "a1-m2-l25-dog", word: "dog", arabic: "كلب", pronunciation: "/dɒɡ/", exampleEN: "The dog is in the garden.", exampleAR: "الكلب في الحديقة.", altText: "A friendly dog near a home", category: "Pets", interactionHint: "Hear dog, then choose the animal beside the home." },
  { id: "a1-m2-l25-bird", word: "bird", arabic: "طائر", pronunciation: "/bɜːd/", exampleEN: "The bird is small.", exampleAR: "الطائر صغير.", altText: "A small bird near a window", category: "Pets", interactionHint: "Hear bird, then find the animal with wings." },
  { id: "a1-m2-l25-fish", word: "fish", arabic: "سمكة", pronunciation: "/fɪʃ/", exampleEN: "The fish is in the water.", exampleAR: "السمكة في الماء.", altText: "A small fish in a bowl", category: "Pets", interactionHint: "Hear fish, then find the animal in the water." },
];

const authoredActivities: Record<number, LessonActivity[]> = {
  16: [
    {
      id: "a1-m2-l16-family-picture",
      kind: "visual-vocabulary",
      title: "Meet a family through a picture",
      titleArabic: "تعرّف إلى عائلة من خلال صورة",
      objective: "Recognise four family words through people in a picture, without asking the learner to disclose personal family information.",
      objectiveArabic: "تعرّف على أربع كلمات للعائلة من خلال أشخاص في صورة، من دون مطالبة المتعلم بمشاركة معلومات شخصية عن عائلته.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: familyVisuals,
    },
    {
      id: "a1-m2-l16-family-frame",
      kind: "standard",
      title: "A safe family sentence frame",
      titleArabic: "قالب آمن لجملة عن العائلة",
      objective: "Use This is my ___ with a fictional picture first, then choose whether to use a real or invented example.",
      objectiveArabic: "استخدم This is my ___ مع صورة خيالية أولاً، ثم اختر إن كنت تريد استخدام مثال حقيقي أو خيالي.",
      stage: "guided-practice",
      estimatedMinutes: 6,
      semantic: "example",
      progressiveSupports: ["worked-example", "tip"],
      sentencePatterns: ["This is my mother.", "This is my brother.", "This is my family."],
      writingPrompt: "Point to a person in the practice picture and say: This is my ___. You may keep using the picture; personal information is optional.",
      writingPromptArabic: "أشر إلى شخص في صورة التدريب وقل: This is my ___. يمكنك الاستمرار في استخدام الصورة؛ فالمعلومات الشخصية اختيارية.",
    },
    {
      id: "a1-m2-l16-family-recall",
      kind: "review",
      title: "One word before you look",
      titleArabic: "كلمة واحدة قبل أن تنظر",
      objective: "Retrieve one family word from the picture and reuse the sentence frame once.",
      objectiveArabic: "استرجع كلمة واحدة للعائلة من الصورة وأعد استخدام قالب الجملة مرة واحدة.",
      stage: "review",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["tip"],
      writingPrompt: "Close the picture for a moment. What is brother or sister in English? Open it only after one calm attempt.",
      writingPromptArabic: "أغلق الصورة للحظة. ما كلمة brother أو sister بالإنجليزية؟ افتحها فقط بعد محاولة هادئة واحدة.",
      suggestedVocabulary: ["mother", "father", "sister", "brother"],
    },
  ],
  17: [
    {
      id: "a1-m2-l17-warm-family-retrieval",
      kind: "review",
      title: "Choose a person from yesterday’s picture",
      titleArabic: "اختر شخصاً من صورة الأمس",
      objective: "Bring one family word into today’s short introduction without forcing a real-life example.",
      objectiveArabic: "استخدم كلمة واحدة للعائلة في تقديم قصير اليوم من دون فرض مثال من حياتك الخاصة.",
      stage: "introduction",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Choose a person from the practice picture: mother, father, sister, or brother. Say only the word first.",
      writingPromptArabic: "اختر شخصاً من صورة التدريب: mother أو father أو sister أو brother. قل الكلمة فقط أولاً.",
    },
    {
      id: "a1-m2-l17-show-and-ask",
      kind: "interaction",
      title: "Show, name, and ask",
      titleArabic: "أشر وسمِّ واسأل",
      objective: "Take two short conversational turns: introduce a person and ask Who is this? in a friendly picture-based exchange.",
      objectiveArabic: "خذ دورين قصيرين في المحادثة: عرّف شخصاً واسأل Who is this? في تبادل ودّي قائم على الصورة.",
      stage: "real-context",
      estimatedMinutes: 10,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l17-turn-1", speaker: "Hana", text: "Who is this?", textArabic: "من هذه؟", purpose: "Ask about a person in the practice picture." },
        { id: "a1-m2-l17-turn-2", speaker: "Omar", text: "This is my sister.", textArabic: "هذه أختي.", purpose: "Name the person with one complete short line." },
        { id: "a1-m2-l17-turn-3", speaker: "Hana", text: "Nice to meet her.", textArabic: "سعيدة بلقائها.", purpose: "Notice that a friendly response can follow the answer." },
      ],
    },
    {
      id: "a1-m2-l17-family-evidence",
      kind: "assessment",
      title: "Choose the line that fits the picture",
      titleArabic: "اختر الجملة المناسبة للصورة",
      objective: "Show that you can connect a family word with a person and a useful question in context.",
      objectiveArabic: "أظهر أنك تستطيع ربط كلمة للعائلة بشخص وسؤال مفيد في السياق.",
      stage: "assessment",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["worked-example"],
      interactionTurns: [
        { id: "a1-m2-l17-check-1", speaker: "Picture", text: "A boy points to his father.", textArabic: "يشير ولد إلى أبيه.", purpose: "Choose: This is my father." },
        { id: "a1-m2-l17-check-2", speaker: "Picture", text: "You want to ask about a woman in a photo.", textArabic: "تريد السؤال عن امرأة في صورة.", purpose: "Choose: Who is this?" },
      ],
    },
  ],
  18: [
    {
      id: "a1-m2-l18-have-has-notice",
      kind: "standard",
      title: "Notice who uses have and has",
      titleArabic: "لاحظ من يستخدم have وhas",
      objective: "Notice have with I and you, and has with he and she, through small familiar family statements.",
      objectiveArabic: "لاحظ have مع I وyou وhas مع he وshe من خلال جمل عائلية مألوفة قصيرة.",
      stage: "explanation",
      estimatedMinutes: 8,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      sentencePatterns: ["I have a brother.", "You have a sister.", "She has a cat.", "He has a dog."],
      writingPrompt: "Do not memorise a rule paragraph. Read the names: I / you → have; he / she → has. Then say one line about the practice characters.",
      writingPromptArabic: "لا تحفظ فقرة قاعدة. اقرأ الأسماء: I / you ← have؛ he / she ← has. ثم قل جملة واحدة عن شخصيات التدريب.",
    },
    {
      id: "a1-m2-l18-family-card-sort",
      kind: "interaction",
      title: "Match the person to the sentence",
      titleArabic: "طابق الشخص مع الجملة",
      objective: "Choose have or has from the meaning of the person, not by guessing from the word’s spelling.",
      objectiveArabic: "اختر have أو has من معنى الشخص، لا بالتخمين من تهجئة الكلمة.",
      stage: "guided-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l18-card-1", speaker: "Maya", text: "Maya ___ a sister.", textArabic: "لدى مايا أخت.", purpose: "Choose has because Maya is she." },
        { id: "a1-m2-l18-card-2", speaker: "You and Ali", text: "You ___ a book.", textArabic: "لديك كتاب.", purpose: "Choose have because the sentence says you." },
        { id: "a1-m2-l18-card-3", speaker: "I", text: "I ___ a bag.", textArabic: "لدي حقيبة.", purpose: "Choose have because the sentence says I." },
      ],
    },
    {
      id: "a1-m2-l18-fictional-profile",
      kind: "writing",
      title: "Make a tiny fictional profile",
      titleArabic: "أنشئ تعريفاً خيالياً صغيراً",
      objective: "Write two safe sentences about an invented person using have or has and one familiar noun.",
      objectiveArabic: "اكتب جملتين آمنتين عن شخص خيالي باستخدام have أو has واسم مألوف واحد.",
      stage: "independent-practice",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"],
      writingPrompt: "Invent a person: Ali has a cat. He has a sister. Or choose your own fictional name. Check only one thing: does I/you use have and does he/she use has?",
      writingPromptArabic: "اخترع شخصاً: Ali has a cat. He has a sister. أو اختر اسماً خيالياً آخر. تحقق من شيء واحد فقط: هل يستخدم I/you كلمة have وهل يستخدم he/she كلمة has؟",
      suggestedVocabulary: ["have", "has", "sister", "brother", "cat", "dog"],
    },
  ],
  19: [
    {
      id: "a1-m2-l19-room-scene",
      kind: "visual-vocabulary",
      title: "Walk through a small home",
      titleArabic: "تجوّل في منزل صغير",
      objective: "Recognise home, room, kitchen, and bedroom in a connected picture rather than as an isolated room list.",
      objectiveArabic: "تعرّف على home وroom وkitchen وbedroom في صورة مترابطة بدلاً من قائمة غرف معزولة.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: roomVisuals,
    },
    {
      id: "a1-m2-l19-home-tour-listen",
      kind: "speaking",
      title: "Hear a two-room home tour",
      titleArabic: "استمع إلى جولة في غرفتين",
      objective: "Hear room words inside a short home tour and repeat only the line that helps you point to the correct place.",
      objectiveArabic: "استمع إلى كلمات الغرف داخل جولة منزل قصيرة وردد فقط الجملة التي تساعدك على الإشارة إلى المكان الصحيح.",
      stage: "guided-practice",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["transcript", "tip"],
      speakingLines: [
        { id: "a1-m2-l19-line-1", speaker: "Guide", text: "This is the kitchen.", textArabic: "هذا هو المطبخ.", pronunciationHint: "Keep this is together as one calm group.", audioText: "This is the kitchen." },
        { id: "a1-m2-l19-line-2", speaker: "Guide", text: "This is my bedroom.", textArabic: "هذه غرفة نومي.", pronunciationHint: "Make bedroom one word, not two separate words.", audioText: "This is my bedroom." },
      ],
    },
    {
      id: "a1-m2-l19-room-choice",
      kind: "review",
      title: "Choose the room for the moment",
      titleArabic: "اختر الغرفة المناسبة للموقف",
      objective: "Retrieve a room word from a simple everyday purpose without adding unrelated old vocabulary.",
      objectiveArabic: "استرجع كلمة غرفة من غرض يومي بسيط من دون إضافة مفردات قديمة غير مرتبطة.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["tip"],
      interactionTurns: [
        { id: "a1-m2-l19-choice-1", speaker: "Need", text: "You cook food here.", textArabic: "تطبخ الطعام هنا.", purpose: "Choose kitchen." },
        { id: "a1-m2-l19-choice-2", speaker: "Need", text: "You sleep here.", textArabic: "تنام هنا.", purpose: "Choose bedroom." },
      ],
    },
  ],
  20: [
    {
      id: "a1-m2-l20-book-scene",
      kind: "interaction",
      title: "Ask about a book in a room",
      titleArabic: "اسأل عن كتاب في غرفة",
      objective: "Use Where is the book? as a purposeful question while looking at a small room scene.",
      objectiveArabic: "استخدم Where is the book? كسؤال له غرض أثناء النظر إلى مشهد غرفة صغير.",
      stage: "introduction",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l20-turn-1", speaker: "Hana", text: "Where is the book?", textArabic: "أين الكتاب؟", purpose: "Ask about the object in the room picture." },
        { id: "a1-m2-l20-turn-2", speaker: "Omar", text: "It is on the table.", textArabic: "إنه على الطاولة.", purpose: "Give one useful location answer." },
      ],
    },
    {
      id: "a1-m2-l20-place-notice",
      kind: "standard",
      title: "Notice the small location word",
      titleArabic: "لاحظ كلمة المكان الصغيرة",
      objective: "Notice on in a useful answer before meeting more location words in later lessons.",
      objectiveArabic: "لاحظ on في إجابة مفيدة قبل مقابلة كلمات مكان أكثر في دروس لاحقة.",
      stage: "explanation",
      estimatedMinutes: 5,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example"],
      sentencePatterns: ["The book is on the table.", "The bag is on the chair."],
      writingPrompt: "Point first, then say the whole answer: It is on the table. Today, on is enough; you will meet other location words later.",
      writingPromptArabic: "أشر أولاً ثم قل الإجابة كاملة: It is on the table. اليوم تكفي on؛ ستقابل كلمات مكان أخرى لاحقاً.",
    },
    {
      id: "a1-m2-l20-room-mission",
      kind: "interaction",
      title: "Give one room mission",
      titleArabic: "أعطِ مهمة واحدة في الغرفة",
      objective: "Ask and answer one location question in a new room scene with a choice of spoken or written response.",
      objectiveArabic: "اسأل وأجب عن سؤال مكان واحد في مشهد غرفة جديد مع خيار الإجابة المنطوقة أو المكتوبة.",
      stage: "real-context",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "tip"],
      writingPrompt: "Choose a picture: a book is on a table / a bag is on a chair. Ask Where is the ___? Then answer It is on the ___. You can say or write it.",
      writingPromptArabic: "اختر صورة: كتاب على طاولة / حقيبة على كرسي. اسأل Where is the ___? ثم أجب It is on the ___. يمكنك قولها أو كتابتها.",
      suggestedVocabulary: ["where", "book", "bag", "table", "chair", "on"],
    },
  ],
  21: [
    {
      id: "a1-m2-l21-furniture-scene",
      kind: "visual-vocabulary",
      title: "Find four useful things in one room",
      titleArabic: "اعثر على أربعة أشياء مفيدة في غرفة واحدة",
      objective: "Recognise table, chair, bag, and book in one connected room scene, including two words that now return naturally from the location question.",
      objectiveArabic: "تعرّف على table وchair وbag وbook في مشهد غرفة مترابط، بما في ذلك كلمتان تعودان الآن بصورة طبيعية من سؤال المكان.",
      stage: "introduction",
      estimatedMinutes: 8,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: furnitureVisuals,
    },
    {
      id: "a1-m2-l21-room-caption",
      kind: "standard",
      title: "Use a useful furniture chunk",
      titleArabic: "استخدم تركيباً مفيداً للأثاث",
      objective: "Use a table, a chair, a bag, and a book as useful chunks rather than learning a long article rule before it is needed.",
      objectiveArabic: "استخدم a table وa chair وa bag وa book كتراكيب مفيدة بدلاً من تعلم قاعدة طويلة عن أدوات التنكير قبل الحاجة إليها.",
      stage: "guided-practice",
      estimatedMinutes: 5,
      semantic: "example",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      sentencePatterns: ["This is a table.", "This is a chair.", "This is my bag.", "This is a book."],
      writingPrompt: "Point to one thing in the practice room. Build one whole line: This is a ___. Keep the old word book only when it fits the scene.",
      writingPromptArabic: "أشر إلى شيء واحد في غرفة التدريب. كوّن جملة كاملة: This is a ___. استخدم كلمة book القديمة فقط عندما تناسب المشهد.",
    },
    {
      id: "a1-m2-l21-place-and-item",
      kind: "interaction",
      title: "Put one belonging in the right place",
      titleArabic: "ضع غرضاً واحداً في المكان الصحيح",
      objective: "Reuse on from the previous lesson only where a room picture makes it useful.",
      objectiveArabic: "أعد استخدام on من الدرس السابق فقط عندما يجعلها مشهد الغرفة مفيدة.",
      stage: "real-context",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l21-turn-1", speaker: "Picture", text: "A book and a table", textArabic: "كتاب وطاولة", purpose: "Say: The book is on the table." },
        { id: "a1-m2-l21-turn-2", speaker: "Picture", text: "A bag and a chair", textArabic: "حقيبة وكرسي", purpose: "Say: The bag is on the chair." },
      ],
    },
  ],
  22: [
    {
      id: "a1-m2-l22-there-is-notice",
      kind: "standard",
      title: "Notice there is in a room",
      titleArabic: "لاحظ there is في غرفة",
      objective: "Understand there is as a useful way to say that one thing exists in a room or home.",
      objectiveArabic: "افهم there is كطريقة مفيدة لقول إن شيئاً واحداً موجود في غرفة أو منزل.",
      stage: "explanation",
      estimatedMinutes: 8,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "extended-rationale"],
      sentencePatterns: ["There is a kitchen.", "There is a table in the room.", "There is a book on the table."],
      writingPrompt: "Read the beginning as one helpful chunk: There is. It tells us that something is present. Today, use it for one thing only.",
      writingPromptArabic: "اقرأ البداية كتركيب مفيد واحد: There is. إنها تخبرنا أن شيئاً موجود. اليوم استخدمها لشيء واحد فقط.",
    },
    {
      id: "a1-m2-l22-room-choice",
      kind: "interaction",
      title: "Choose what the room has",
      titleArabic: "اختر ما يوجد في الغرفة",
      objective: "Select a truthful there is line from a room picture and explain the choice with one visible clue.",
      objectiveArabic: "اختر جملة صحيحة بـ there is من صورة غرفة وفسر الاختيار بدليل مرئي واحد.",
      stage: "guided-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l22-choice-1", speaker: "Room", text: "One table, one chair", textArabic: "طاولة واحدة وكرسي واحد", purpose: "Choose: There is a table in the room." },
        { id: "a1-m2-l22-choice-2", speaker: "Kitchen", text: "A kitchen in the small home", textArabic: "مطبخ في المنزل الصغير", purpose: "Choose: There is a kitchen." },
      ],
    },
    {
      id: "a1-m2-l22-invented-home",
      kind: "writing",
      title: "Describe an invented home",
      titleArabic: "صِف منزلاً خيالياً",
      objective: "Write two short there is sentences about an invented room so personal home details remain optional.",
      objectiveArabic: "اكتب جملتين قصيرتين بـ there is عن غرفة خيالية حتى تبقى تفاصيل منزلك الشخصية اختيارية.",
      stage: "independent-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"],
      writingPrompt: "Invent a small room. Write two lines, for example: There is a table. There is a book on the table. You may use the practice room instead of your real home.",
      writingPromptArabic: "اخترع غرفة صغيرة. اكتب سطرين، مثلاً: There is a table. There is a book on the table. يمكنك استخدام غرفة التدريب بدلاً من منزلك الحقيقي.",
      suggestedVocabulary: ["there is", "table", "chair", "book", "kitchen"],
    },
  ],
  23: [
    {
      id: "a1-m2-l23-tour-recall",
      kind: "review",
      title: "Pack three words for a home tour",
      titleArabic: "جهّز ثلاث كلمات لجولة منزلية",
      objective: "Bring only home, kitchen, and bedroom into a short tour; leave unrelated vocabulary behind.",
      objectiveArabic: "استخدم فقط home وkitchen وbedroom في جولة قصيرة؛ واترك المفردات غير المرتبطة خارجاً.",
      stage: "introduction",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Before you listen, say three room words: home, kitchen, bedroom. You do not need every word from earlier lessons today.",
      writingPromptArabic: "قبل أن تستمع، قل ثلاث كلمات للغرف: home وkitchen وbedroom. لا تحتاج إلى كل كلمات الدروس السابقة اليوم.",
    },
    {
      id: "a1-m2-l23-home-tour-model",
      kind: "speaking",
      title: "Hear a calm two-room tour",
      titleArabic: "استمع إلى جولة هادئة في غرفتين",
      objective: "Follow a short home tour and repeat the two lines that help a visitor understand the place.",
      objectiveArabic: "اتبع جولة منزلية قصيرة وردد السطرين اللذين يساعدان الزائر على فهم المكان.",
      stage: "guided-practice",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["transcript", "arabic-help", "tip"],
      speakingLines: [
        { id: "a1-m2-l23-line-1", speaker: "Maya", text: "Welcome to my home.", textArabic: "مرحباً بك في منزلي.", pronunciationHint: "Keep welcome to together; do not rush my home.", audioText: "Welcome to my home." },
        { id: "a1-m2-l23-line-2", speaker: "Maya", text: "This is the kitchen.", textArabic: "هذا هو المطبخ.", pronunciationHint: "Say kitchen as one word.", audioText: "This is the kitchen." },
        { id: "a1-m2-l23-line-3", speaker: "Maya", text: "This is the bedroom.", textArabic: "هذه غرفة النوم.", pronunciationHint: "Make bedroom one word.", audioText: "This is the bedroom." },
      ],
    },
    {
      id: "a1-m2-l23-tour-choice",
      kind: "interaction",
      title: "Guide a visitor through a picture",
      titleArabic: "أرشد زائراً عبر صورة",
      objective: "Give a two-line tour using a picture, a fictional home, or a simple diagram instead of a personal address or photo.",
      objectiveArabic: "قدّم جولة من سطرين باستخدام صورة أو منزل خيالي أو مخطط بسيط بدلاً من عنوانك أو صورة شخصية لمنزلك.",
      stage: "real-context",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "transcript", "word-support"],
      writingPrompt: "Choose the practice house. Say: Welcome to my home. This is the ___. This is the ___. You may record it, say it quietly, or write it.",
      writingPromptArabic: "اختر منزل التدريب. قل: Welcome to my home. This is the ___. This is the ___. يمكنك تسجيلها أو قولها بهدوء أو كتابتها.",
      suggestedVocabulary: ["welcome", "home", "kitchen", "bedroom"],
    },
  ],
  24: [
    {
      id: "a1-m2-l24-small-home-reading",
      kind: "reading",
      title: "Read: My small home",
      titleArabic: "اقرأ: منزلي الصغير",
      objective: "Read a short home description for the main places and objects, using familiar words as anchors rather than translating every line.",
      objectiveArabic: "اقرأ وصفاً قصيراً للمنزل من أجل الأماكن والأشياء الرئيسية، مستخدماً الكلمات المألوفة كمرتكزات بدلاً من ترجمة كل سطر.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "transcript", "word-support"],
      readingText: "This is Noor's small home. There is a kitchen and a bedroom. There is a table in the kitchen. A book is on the table. Noor has a cat.",
      readingTextArabic: "هذا منزل نور الصغير. يوجد مطبخ وغرفة نوم. توجد طاولة في المطبخ. يوجد كتاب على الطاولة. لدى نور قطة.",
      readingChecks: [
        { id: "a1-m2-l24-check-1", type: "detail", prompt: "Where is the table?", promptArabic: "أين الطاولة؟", choices: ["In the kitchen", "In the bedroom", "On the cat"], answer: "In the kitchen", explanation: "The text says: There is a table in the kitchen." },
        { id: "a1-m2-l24-check-2", type: "detail", prompt: "What is on the table?", promptArabic: "ما الموجود على الطاولة؟", choices: ["A book", "A dog", "A chair"], answer: "A book", explanation: "The text says: A book is on the table." },
        { id: "a1-m2-l24-check-3", type: "true-false", prompt: "Noor has a cat.", promptArabic: "لدى نور قطة.", choices: ["True", "False"], answer: "True", explanation: "The final sentence says Noor has a cat." },
      ],
    },
    {
      id: "a1-m2-l24-reading-map",
      kind: "standard",
      title: "Mark the words that guide you",
      titleArabic: "حدّد الكلمات التي ترشدك",
      objective: "Notice how names, room words, and there is help a beginner locate meaning in a short text.",
      objectiveArabic: "لاحظ كيف تساعد الأسماء وكلمات الغرف وthere is المبتدئ على إيجاد المعنى في نص قصير.",
      stage: "guided-practice",
      estimatedMinutes: 5,
      semantic: "tip",
      progressiveSupports: ["worked-example", "tip"],
      writingPrompt: "Read again and underline Noor, kitchen, bedroom, table, book, and cat. These are your meaning anchors. You do not need to stop at every small word.",
      writingPromptArabic: "اقرأ مرة أخرى وضع خطاً تحت Noor وkitchen وbedroom وtable وbook وcat. هذه مرتكزات المعنى. لا تحتاج إلى التوقف عند كل كلمة صغيرة.",
    },
    {
      id: "a1-m2-l24-reading-evidence",
      kind: "assessment",
      title: "Answer with evidence from the text",
      titleArabic: "أجب بدليل من النص",
      objective: "Give two short reading answers by returning to the exact sentence that proves them.",
      objectiveArabic: "أعطِ إجابتين قصيرتين للقراءة بالعودة إلى الجملة الدقيقة التي تثبتهما.",
      stage: "assessment",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["worked-example"],
      writingPrompt: "Answer: Is there a bedroom? What animal does Noor have? Look back at the sentence before you answer; careful reading is the skill.",
      writingPromptArabic: "أجب: هل توجد غرفة نوم؟ ما الحيوان الذي لدى نور؟ ارجع إلى الجملة قبل الإجابة؛ القراءة الدقيقة هي المهارة.",
    },
  ],
  25: [
    {
      id: "a1-m2-l25-pet-picture",
      kind: "visual-vocabulary",
      title: "Meet four animals near a home",
      titleArabic: "تعرّف على أربعة حيوانات قرب منزل",
      objective: "Recognise cat, dog, bird, and fish through a home scene without assuming that every learner owns or wants a pet.",
      objectiveArabic: "تعرّف على cat وdog وbird وfish من خلال مشهد منزلي من دون افتراض أن كل متعلم يملك أو يريد حيواناً أليفاً.",
      stage: "introduction",
      estimatedMinutes: 8,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: petVisuals,
    },
    {
      id: "a1-m2-l25-home-animal-dialogue",
      kind: "interaction",
      title: "Ask about an animal in the picture",
      titleArabic: "اسأل عن حيوان في الصورة",
      objective: "Use a short question and answer about a fictional animal while hearing has return naturally from the family lesson.",
      objectiveArabic: "استخدم سؤالاً وجواباً قصيرين عن حيوان خيالي مع سماع has تعود بصورة طبيعية من درس العائلة.",
      stage: "real-context",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l25-turn-1", speaker: "Omar", text: "What is this?", textArabic: "ما هذا؟", purpose: "Ask about the animal in the practice picture." },
        { id: "a1-m2-l25-turn-2", speaker: "Hana", text: "It is a cat.", textArabic: "إنها قطة.", purpose: "Name the animal." },
        { id: "a1-m2-l25-turn-3", speaker: "Omar", text: "Noor has a cat.", textArabic: "لدى نور قطة.", purpose: "Reuse has with a fictional person, not a personal question." },
      ],
    },
    {
      id: "a1-m2-l25-animal-recall",
      kind: "review",
      title: "Name one animal and one place",
      titleArabic: "سمِّ حيواناً واحداً ومكاناً واحداً",
      objective: "Retrieve one new animal and connect it to home only when the sentence is natural.",
      objectiveArabic: "استرجع حيواناً جديداً واحداً واربطه بالمنزل فقط عندما تكون الجملة طبيعية.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["tip", "word-support"],
      writingPrompt: "Choose one: The cat is at home. / The fish is in water. Do not force all four animals into one sentence.",
      writingPromptArabic: "اختر واحدة: The cat is at home. / The fish is in water. لا تُجبر الحيوانات الأربعة كلها في جملة واحدة.",
      suggestedVocabulary: ["cat", "dog", "bird", "fish", "home"],
    },
  ],
  26: [
    {
      id: "a1-m2-l26-room-word-bank",
      kind: "review",
      title: "Choose words for a small room description",
      titleArabic: "اختر كلمات لوصف غرفة صغيرة",
      objective: "Retrieve only the words needed for a short room description, including one place word and two useful objects.",
      objectiveArabic: "استرجع فقط الكلمات اللازمة لوصف غرفة قصير، بما في ذلك كلمة مكان وشيئان مفيدان.",
      stage: "introduction",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      suggestedVocabulary: ["room", "bedroom", "table", "chair", "book", "bag", "there is"],
      writingPrompt: "Choose three or four words from the room bank. You do not need family, pets, and furniture all at once.",
      writingPromptArabic: "اختر ثلاث أو أربع كلمات من بنك الغرفة. لا تحتاج إلى العائلة والحيوانات والأثاث كلها في وقت واحد.",
    },
    {
      id: "a1-m2-l26-invented-room-writing",
      kind: "writing",
      title: "Write about an invented room",
      titleArabic: "اكتب عن غرفة خيالية",
      objective: "Write three connected beginner sentences about an invented room, with a clear model and no expectation of sharing a private photo or address.",
      objectiveArabic: "اكتب ثلاث جمل مترابطة للمبتدئين عن غرفة خيالية، مع نموذج واضح ومن دون توقع مشاركة صورة خاصة أو عنوان.",
      stage: "independent-practice",
      estimatedMinutes: 10,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"],
      writingPrompt: "Invent a room called the blue room. Write three lines: This is the blue room. There is a table. There is a book on the table. You may change blue, table, and book.",
      writingPromptArabic: "اخترع غرفة اسمها الغرفة الزرقاء. اكتب ثلاثة أسطر: This is the blue room. There is a table. There is a book on the table. يمكنك تغيير blue وtable وbook.",
      sentencePatterns: ["This is the ___ room.", "There is a ___.", "There is a ___ on the ___."],
      suggestedVocabulary: ["room", "table", "chair", "book", "bag", "there is"],
    },
    {
      id: "a1-m2-l26-kind-feedback",
      kind: "standard",
      title: "Check one thing at a time",
      titleArabic: "تحقق من شيء واحد في كل مرة",
      objective: "Review a short description for a capital letter, a full stop, and a meaningful room word before asking for outside feedback.",
      objectiveArabic: "راجع وصفاً قصيراً لحرف كبير ونقطة وكلمة غرفة ذات معنى قبل طلب ملاحظات خارجية.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "tip",
      progressiveSupports: ["worked-example", "tip"],
      writingPrompt: "Read your three lines once. Check: 1) capital letter, 2) full stop, 3) the object matches the room picture. That is enough for today.",
      writingPromptArabic: "اقرأ أسطرك الثلاثة مرة واحدة. تحقق من: 1) حرف كبير، 2) نقطة، 3) أن الشيء يناسب صورة الغرفة. هذا كافٍ لليوم.",
    },
  ],
  27: [
    {
      id: "a1-m2-l27-picture-scan",
      kind: "visual-vocabulary",
      title: "See the sentence clues in a picture",
      titleArabic: "شاهد دلائل الجملة في صورة",
      objective: "Identify who, what, and where in a calm illustrated home picture before trying to write a sentence.",
      objectiveArabic: "حدّد من وماذا وأين في صورة منزل هادئة قبل محاولة كتابة جملة.",
      stage: "introduction",
      estimatedMinutes: 6,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "worked-example", "word-support"],
      writingPrompt: "Look for three clues: a person, an object, and a room. Say the words first; sentences come after the picture is clear.",
      writingPromptArabic: "ابحث عن ثلاثة دلائل: شخص وشيء وغرفة. قل الكلمات أولاً؛ تأتي الجمل بعد أن تتضح الصورة.",
      suggestedVocabulary: ["mother", "brother", "kitchen", "bedroom", "table", "book"],
    },
    {
      id: "a1-m2-l27-picture-build",
      kind: "interaction",
      title: "Build one true picture sentence",
      titleArabic: "ابنِ جملة صحيحة واحدة عن الصورة",
      objective: "Select and say the one sentence that the picture supports; do not use a spelling trap or an implausible distractor.",
      objectiveArabic: "اختر وقل الجملة الوحيدة التي تدعمها الصورة؛ لا تستخدم فخاً إملائياً أو خياراً غير منطقي.",
      stage: "guided-practice",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l27-pic-1", speaker: "Picture", text: "A book on a table in the kitchen", textArabic: "كتاب على طاولة في المطبخ", purpose: "Build: There is a book on the table." },
        { id: "a1-m2-l27-pic-2", speaker: "Picture", text: "A sister at the door", textArabic: "أخت عند الباب", purpose: "Build: This is my sister." },
        { id: "a1-m2-l27-pic-3", speaker: "Picture", text: "A cat in a small home", textArabic: "قطة في منزل صغير", purpose: "Build: The cat is at home." },
      ],
    },
    {
      id: "a1-m2-l27-sentence-choice",
      kind: "assessment",
      title: "Choose meaning, not a near-miss spelling",
      titleArabic: "اختر المعنى، لا تهجئة قريبة مضللة",
      objective: "Choose between complete context-appropriate sentences that reuse familiar home language.",
      objectiveArabic: "اختر بين جمل مكتملة ومناسبة للسياق تعيد استخدام لغة المنزل المألوفة.",
      stage: "assessment",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["worked-example"],
      writingPrompt: "For a picture of a chair in a bedroom, choose the sentence that means what you see: There is a chair in the bedroom. Explain by pointing to chair and bedroom.",
      writingPromptArabic: "لصورة كرسي في غرفة نوم، اختر الجملة التي تعني ما تراه: There is a chair in the bedroom. اشرح بالإشارة إلى chair وbedroom.",
    },
  ],
  28: [
    {
      id: "a1-m2-l28-visit-listen",
      kind: "interaction",
      title: "Meet someone during a family visit",
      titleArabic: "قابل شخصاً أثناء زيارة عائلية",
      objective: "Follow a polite, fictional family-visit exchange that joins greeting language with family vocabulary.",
      objectiveArabic: "اتبع تبادلاً مهذباً وخيالياً لزيارة عائلية يجمع لغة التحية مع مفردات العائلة.",
      stage: "introduction",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "transcript", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l28-turn-1", speaker: "Visitor", text: "Hello. Welcome to your home.", textArabic: "مرحباً. أهلاً بك في منزلكم.", purpose: "Open the fictional visit politely." },
        { id: "a1-m2-l28-turn-2", speaker: "Hana", text: "Thank you. This is my mother.", textArabic: "شكراً. هذه أمي.", purpose: "Introduce one family member." },
        { id: "a1-m2-l28-turn-3", speaker: "Mother", text: "Hello. Nice to meet you.", textArabic: "مرحباً. سعيد/سعيدة بلقائك.", purpose: "Respond with a familiar meeting phrase." },
      ],
    },
    {
      id: "a1-m2-l28-visit-choices",
      kind: "standard",
      title: "Choose a friendly reply",
      titleArabic: "اختر رداً ودياً",
      objective: "Choose a short reply that fits a first meeting instead of memorising a long dialogue.",
      objectiveArabic: "اختر رداً قصيراً يناسب اللقاء الأول بدلاً من حفظ حوار طويل.",
      stage: "guided-practice",
      estimatedMinutes: 5,
      semantic: "example",
      progressiveSupports: ["worked-example", "tip"],
      sentencePatterns: ["Hello.", "Nice to meet you.", "This is my brother.", "Welcome to my home."],
      writingPrompt: "A new person says: Hello. Choose one friendly answer: Hello. / Nice to meet you. Then add one introduction only if the practice picture gives you someone to introduce.",
      writingPromptArabic: "يقول شخص جديد: Hello. اختر جواباً ودياً واحداً: Hello. / Nice to meet you. ثم أضف تعارفاً واحداً فقط إذا أعطتك صورة التدريب شخصاً لتعرّفه.",
    },
    {
      id: "a1-m2-l28-visit-role-choice",
      kind: "speaking",
      title: "Try two visit lines your way",
      titleArabic: "جرّب سطرين للزيارة بطريقتك",
      objective: "Rehearse two short lines aloud, quietly, or in writing with a fictional family card; speaking is offered, not forced.",
      objectiveArabic: "تدرّب على سطرين قصيرين بصوت عالٍ أو بهدوء أو كتابةً مع بطاقة عائلة خيالية؛ التحدث معروض وليس مفروضاً.",
      stage: "real-context",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "tip"],
      speakingLines: [
        { id: "a1-m2-l28-say-1", text: "Hello. Nice to meet you.", textArabic: "مرحباً. سعيد/سعيدة بلقائك.", pronunciationHint: "Pause after Hello; keep nice to meet you as one friendly phrase.", audioText: "Hello. Nice to meet you." },
        { id: "a1-m2-l28-say-2", text: "This is my brother.", textArabic: "هذا أخي.", pronunciationHint: "Make brother one clear word.", audioText: "This is my brother." },
      ],
    },
  ],
  29: [
    {
      id: "a1-m2-l29-listen-description",
      kind: "speaking",
      title: "Listen to a room description",
      titleArabic: "استمع إلى وصف غرفة",
      objective: "Listen for the two details that matter in a short room description, then repeat one clear sentence.",
      objectiveArabic: "استمع إلى التفاصيل المهمة في وصف غرفة قصير، ثم كرر جملة واضحة واحدة.",
      stage: "introduction",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["transcript", "arabic-help", "word-support"],
      speakingLines: [
        { id: "a1-m2-l29-listen-1", speaker: "Guide", text: "There is a table in the kitchen.", textArabic: "توجد طاولة في المطبخ.", pronunciationHint: "Listen for table and kitchen.", audioText: "There is a table in the kitchen." },
        { id: "a1-m2-l29-listen-2", speaker: "Guide", text: "A book is on the table.", textArabic: "يوجد كتاب على الطاولة.", pronunciationHint: "Listen for book and table.", audioText: "A book is on the table." },
      ],
    },
    {
      id: "a1-m2-l29-detail-select",
      kind: "interaction",
      title: "Choose the details you heard",
      titleArabic: "اختر التفاصيل التي سمعتها",
      objective: "Identify a room and an object from the spoken description without turning listening into an unfamiliar grammar test.",
      objectiveArabic: "حدّد غرفة وشيئاً من الوصف المسموع من دون تحويل الاستماع إلى اختبار قواعد غير مألوف.",
      stage: "guided-practice",
      estimatedMinutes: 5,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m2-l29-detail-1", speaker: "Question", text: "Where is the table?", textArabic: "أين الطاولة؟", purpose: "Choose: In the kitchen." },
        { id: "a1-m2-l29-detail-2", speaker: "Question", text: "What is on the table?", textArabic: "ما الموجود على الطاولة؟", purpose: "Choose: A book." },
      ],
    },
    {
      id: "a1-m2-l29-describe-choice",
      kind: "speaking",
      title: "Describe one new picture",
      titleArabic: "صِف صورة جديدة واحدة",
      objective: "Produce one or two familiar room lines from a new fictional picture while choosing speech, quiet rehearsal, or written practice.",
      objectiveArabic: "أنتج سطراً أو سطرين مألوفين عن صورة خيالية جديدة مع اختيار التحدث أو التدريب الهادئ أو الكتابة.",
      stage: "independent-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"],
      writingPrompt: "Use a new practice picture. Say or write: There is a ___. The ___ is in/on the ___. Use only words that the picture supports.",
      writingPromptArabic: "استخدم صورة تدريب جديدة. قل أو اكتب: There is a ___. The ___ is in/on the ___. استخدم فقط الكلمات التي تدعمها الصورة.",
      sentencePatterns: ["There is a ___.", "The ___ is in the ___.", "The ___ is on the ___."],
    },
  ],
  30: [
    {
      id: "a1-m2-l30-checkpoint-plan",
      kind: "review",
      title: "Prepare for a kind checkpoint",
      titleArabic: "استعد لاختبار داعم",
      objective: "Recall a small set of family-and-home anchors before the checkpoint without trying to revise every word in the module.",
      objectiveArabic: "استرجع مجموعة صغيرة من مرتكزات العائلة والمنزل قبل الاختبار من دون محاولة مراجعة كل كلمة في الوحدة.",
      stage: "introduction",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      suggestedVocabulary: ["mother", "brother", "home", "kitchen", "table", "book", "cat", "there is"],
      writingPrompt: "Choose four anchors: one person, one room, one object, and one animal or pattern. A checkpoint shows what to revisit; it is not a judgement of you.",
      writingPromptArabic: "اختر أربعة مرتكزات: شخصاً واحداً وغرفة واحدة وشيئاً واحداً وحيواناً أو تركيباً واحداً. الاختبار يوضح ما يجب مراجعته؛ وليس حكماً عليك.",
    },
    {
      id: "a1-m2-l30-context-check",
      kind: "assessment",
      title: "Family and home in context",
      titleArabic: "العائلة والمنزل في السياق",
      objective: "Show meaning through short picture, dialogue, reading, and sentence tasks that use familiar words correctly in context.",
      objectiveArabic: "أظهر المعنى من خلال مهام قصيرة للصورة والحوار والقراءة والجملة تستخدم كلمات مألوفة بصورة صحيحة في السياق.",
      stage: "assessment",
      estimatedMinutes: 12,
      semantic: "assessment",
      progressiveSupports: ["worked-example", "word-support"],
      writingPrompt: "The checkpoint has four small parts: identify a picture word, choose a truthful room sentence, understand one dialogue line, and write one fictional home line. Take one part at a time.",
      writingPromptArabic: "يتكون الاختبار من أربعة أجزاء صغيرة: حدّد كلمة من صورة، واختر جملة صحيحة عن غرفة، وافهم سطر حوار واحد، واكتب سطراً واحداً عن منزل خيالي. خذ جزءاً واحداً في كل مرة.",
    },
    {
      id: "a1-m2-l30-next-step",
      kind: "review",
      title: "Choose one useful next review",
      titleArabic: "اختر مراجعة مفيدة واحدة تالية",
      objective: "Turn a result into one practical next action: replay a word, reread a short text, or rebuild one sentence.",
      objectiveArabic: "حوّل النتيجة إلى خطوة تالية عملية واحدة: أعد سماع كلمة أو اقرأ نصاً قصيراً مرة أخرى أو أعد بناء جملة واحدة.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["tip", "worked-example"],
      writingPrompt: "If a word was difficult, replay the word. If a sentence was difficult, rebuild one sentence. If a reading answer was difficult, find the proof line. Choose one, not all three.",
      writingPromptArabic: "إذا كانت كلمة صعبة، أعد سماع الكلمة. إذا كانت جملة صعبة، أعد بناء جملة واحدة. إذا كانت إجابة قراءة صعبة، اعثر على سطر الدليل. اختر واحدة، لا الثلاثة كلها.",
    },
  ],
};

export function authoredActivitiesForA1Module2(lessonNumber: number): LessonActivity[] | undefined {
  return authoredActivities[lessonNumber];
}
