import type { LessonActivity, VisualVocabularyItem } from "./types";

const peopleVisuals: VisualVocabularyItem[] = [
  { id: "a1-m1-l4-man", word: "man", arabic: "رجل", pronunciation: "/mæn/", exampleEN: "This is a man.", exampleAR: "هذا رجل.", altText: "A neutral illustration of a man", category: "People", interactionHint: "Listen, choose the picture, then say the full sentence." },
  { id: "a1-m1-l4-woman", word: "woman", arabic: "امرأة", pronunciation: "/ˈwʊmən/", exampleEN: "This is a woman.", exampleAR: "هذه امرأة.", altText: "A neutral illustration of a woman", category: "People", interactionHint: "Listen, choose the picture, then say the full sentence." },
  { id: "a1-m1-l4-child", word: "child", arabic: "طفل / طفلة", pronunciation: "/tʃaɪld/", exampleEN: "This is a child.", exampleAR: "هذا طفل / هذه طفلة.", altText: "A neutral illustration of a child", category: "People", interactionHint: "Listen, choose the picture, then say the full sentence." },
  { id: "a1-m1-l4-girl", word: "girl", arabic: "بنت", pronunciation: "/ɡɜːl/", exampleEN: "This is a girl.", exampleAR: "هذه بنت.", altText: "A neutral illustration of a girl with a school bag", category: "People", interactionHint: "Listen, choose the picture, then say the full sentence." },
];

const authoredActivities: Record<number, LessonActivity[]> = {
  1: [
    {
      id: "a1-m1-l1-greeting-words",
      kind: "visual-vocabulary",
      title: "Words for meeting and leaving",
      titleArabic: "كلمات للقاء والوداع",
      objective: "Recognise hello, hi, goodbye, please, and thank you in a first classroom encounter.",
      objectiveArabic: "تعرّف على hello وhi وgoodbye وplease وthank you في لقاء صفّي أول.",
      stage: "introduction",
      estimatedMinutes: 8,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: [
        { id: "a1-m1-l1-hello", word: "hello", arabic: "مرحباً", pronunciation: "/həˈləʊ/", exampleEN: "Hello, Sara.", exampleAR: "مرحباً يا سارة.", altText: "Two classmates meeting and saying hello", category: "Greetings", interactionHint: "Press the sound button to hear only: hello." },
        { id: "a1-m1-l1-goodbye", word: "goodbye", arabic: "إلى اللقاء", pronunciation: "/ɡʊdˈbaɪ/", exampleEN: "Goodbye, Omar.", exampleAR: "إلى اللقاء يا عمر.", altText: "Two classmates leaving and saying goodbye", category: "Greetings", interactionHint: "Press the sound button to hear only: goodbye." },
        { id: "a1-m1-l1-thank-you", word: "thank you", arabic: "شكراً", pronunciation: "/ˈθæŋk juː/", exampleEN: "Thank you for the book.", exampleAR: "شكراً على الكتاب.", altText: "A learner receiving a book and saying thank you", category: "Politeness", interactionHint: "Press the sound button to hear only: thank you." },
      ],
    },
    {
      id: "a1-m1-l1-echo",
      kind: "speaking",
      title: "Hear it, pause, then say it",
      titleArabic: "استمع، توقّف، ثم قلها",
      objective: "Practise a friendly greeting and closing in short, low-pressure turns.",
      objectiveArabic: "تدرّب على تحية ووداع ودّيين في أدوار قصيرة بلا ضغط.",
      stage: "guided-practice",
      estimatedMinutes: 7,
      semantic: "activity",
      progressiveSupports: ["transcript", "tip"],
      speakingLines: [
        { id: "a1-m1-l1-echo-1", speaker: "Maya", text: "Hello!", textArabic: "مرحباً!", pronunciationHint: "/həˈləʊ/", audioText: "Hello" },
        { id: "a1-m1-l1-echo-2", speaker: "Adam", text: "Hi!", textArabic: "أهلاً!", pronunciationHint: "/haɪ/", audioText: "Hi" },
        { id: "a1-m1-l1-echo-3", speaker: "Adam", text: "Thank you.", textArabic: "شكراً.", pronunciationHint: "/ˈθæŋk juː/", audioText: "Thank you" },
        { id: "a1-m1-l1-echo-4", speaker: "Maya", text: "Goodbye!", textArabic: "إلى اللقاء!", pronunciationHint: "/ɡʊdˈbaɪ/", audioText: "Goodbye" },
      ],
    },
    {
      id: "a1-m1-l1-situation-choice",
      kind: "interaction",
      title: "Choose the phrase for the moment",
      titleArabic: "اختر العبارة المناسبة للموقف",
      objective: "Choose a greeting, a polite response, or a closing from the situation rather than from spelling clues.",
      objectiveArabic: "اختر تحية أو رداً مهذباً أو وداعاً من الموقف، لا من دلائل الإملاء.",
      stage: "real-context",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["worked-example"],
      interactionTurns: [
        { id: "a1-m1-l1-turn-1", speaker: "Situation", text: "You enter English class at 9:00.", textArabic: "تدخل حصة الإنجليزية الساعة 9:00.", purpose: "Choose hello. You are meeting people." },
        { id: "a1-m1-l1-turn-2", speaker: "Situation", text: "Your teacher gives you a pen.", textArabic: "تعطيك معلمتك قلماً.", purpose: "Choose thank you. Someone has helped you." },
        { id: "a1-m1-l1-turn-3", speaker: "Situation", text: "You leave class at the end.", textArabic: "تغادر الحصة في النهاية.", purpose: "Choose goodbye. You are leaving." },
      ],
    },
    {
      id: "a1-m1-l1-retrieval",
      kind: "review",
      title: "Remember before you look",
      titleArabic: "تذكّر قبل أن تنظر",
      objective: "Retrieve the word for leaving and complete one two-line greeting.",
      objectiveArabic: "استرجع كلمة الوداع وأكمل تحية من سطرين.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["tip"],
      writingPrompt: "Look away. Which word do you use when you leave? Then say: Hello, ____. Thank you. Goodbye.",
      writingPromptArabic: "انظر بعيداً. ما الكلمة التي تستخدمها عندما تغادر؟ ثم قل: Hello, ____. Thank you. Goodbye.",
      suggestedVocabulary: ["hello", "thank you", "goodbye"],
    },
  ],
  2: [
    {
      id: "a1-m1-l2-warm-retrieval",
      kind: "review",
      title: "Open the conversation again",
      titleArabic: "ابدأ المحادثة مرة أخرى",
      objective: "Bring one greeting from Lesson 1 into today’s name exchange.",
      objectiveArabic: "استخدم تحية واحدة من الدرس الأول في تبادل الأسماء اليوم.",
      stage: "introduction",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["word-support"],
      writingPrompt: "It is morning. You meet a new person. Say one greeting: Hello or Hi.",
      writingPromptArabic: "إنه الصباح. تقابل شخصاً جديداً. قل تحية واحدة: Hello أو Hi.",
      suggestedVocabulary: ["hello", "hi"],
    },
    {
      id: "a1-m1-l2-name-exchange",
      kind: "interaction",
      title: "A name exchange",
      titleArabic: "تبادل الأسماء",
      objective: "Ask for a name and give a name in a four-line conversation.",
      objectiveArabic: "اسأل عن الاسم واذكر اسمك في محادثة من أربعة أسطر.",
      stage: "guided-practice",
      estimatedMinutes: 10,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "arabic-help"],
      interactionTurns: [
        { id: "a1-m1-l2-turn-1", speaker: "Noor", text: "Hello. My name is Noor. What is your name?", textArabic: "مرحباً. اسمي نور. ما اسمك؟", purpose: "Open and ask about the other person." },
        { id: "a1-m1-l2-turn-2", speaker: "Ali", text: "Hi. My name is Ali.", textArabic: "أهلاً. اسمي علي.", purpose: "Give a name." },
        { id: "a1-m1-l2-turn-3", speaker: "Noor", text: "Thank you, Ali.", textArabic: "شكراً يا علي.", purpose: "Respond politely." },
        { id: "a1-m1-l2-turn-4", speaker: "Ali", text: "Goodbye, Noor.", textArabic: "إلى اللقاء يا نور.", purpose: "Close politely." },
      ],
    },
    {
      id: "a1-m1-l2-my-your",
      kind: "standard",
      title: "Notice my and your in the turns",
      titleArabic: "لاحظ my وyour في الحوار",
      objective: "Notice my name for the speaker and your name for the other person.",
      objectiveArabic: "لاحظ my name للمتحدث وyour name للشخص الآخر.",
      stage: "explanation",
      estimatedMinutes: 5,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example"],
      writingPrompt: "Complete: My name is ____. Ask: What is your name? Do not say: What your name? English needs is in this question.",
      writingPromptArabic: "أكمل: My name is ____. واسأل: What is your name? لا تقل: What your name? تحتاج الإنجليزية إلى is في هذا السؤال.",
      sentencePatterns: ["My name is ___.", "What is your name?"],
    },
    {
      id: "a1-m1-l2-roleplay",
      kind: "speaking",
      title: "Say your own version",
      titleArabic: "قل نسختك الخاصة",
      objective: "Use the exchange with a chosen name or an imaginary name if privacy is preferred.",
      objectiveArabic: "استخدم الحوار باسم تختاره أو باسم خيالي إذا فضّلت الخصوصية.",
      stage: "independent-practice",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["word-support", "external-ai-prompt"],
      speakingLines: [
        { id: "a1-m1-l2-speak-1", speaker: "Learner", text: "Hello. My name is ___.", textArabic: "مرحباً. اسمي ___.", pronunciationHint: "/həˈləʊ/ /maɪ neɪm ɪz/" },
        { id: "a1-m1-l2-speak-2", speaker: "Learner", text: "What is your name?", textArabic: "ما اسمك؟", pronunciationHint: "/wɒt ɪz jɔː neɪm/" },
      ],
    },
  ],
  3: [
    {
      id: "a1-m1-l3-arabic-contrast",
      kind: "standard",
      title: "A small English connection word",
      titleArabic: "كلمة إنجليزية صغيرة للربط",
      objective: "Understand that English usually needs am or are between a person and information.",
      objectiveArabic: "افهم أن الإنجليزية تحتاج غالباً إلى am أو are بين الشخص والمعلومة.",
      stage: "explanation",
      estimatedMinutes: 10,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "extended-rationale", "worked-example"],
      writingPrompt: "Arabic can say: أنا طالب. English says: I am a student. Choose I am with I. Choose you are with you.",
      writingPromptArabic: "تستطيع العربية أن تقول: أنا طالب. وتقول الإنجليزية: I am a student. اختر I am مع I، واختر you are مع you.",
      sentencePatterns: ["I am a student.", "You are my friend."],
    },
    {
      id: "a1-m1-l3-sentence-ladder",
      kind: "writing",
      title: "Build a true sentence in steps",
      titleArabic: "ابنِ جملة حقيقية خطوة خطوة",
      objective: "Produce one I am sentence and one you are sentence from a clear model.",
      objectiveArabic: "أنتج جملة واحدة بـ I am وجملة واحدة بـ you are من نموذج واضح.",
      stage: "guided-practice",
      estimatedMinutes: 9,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      writingPrompt: "Step 1: I am ____. Step 2: I am a ____. Step 3: You are my ____. You may choose an imaginary identity.",
      writingPromptArabic: "الخطوة 1: I am ____. الخطوة 2: I am a ____. الخطوة 3: You are my ____. يمكنك اختيار هوية خيالية.",
      suggestedVocabulary: ["student", "friend", "happy"],
      sentencePatterns: ["I am ___.", "I am a ___.", "You are my ___."],
    },
    {
      id: "a1-m1-l3-meaning-choice",
      kind: "assessment",
      title: "Choose meaning before form",
      titleArabic: "اختر المعنى قبل الشكل",
      objective: "Match the person to the correct am or are sentence.",
      objectiveArabic: "طابق الشخص مع جملة am أو are الصحيحة.",
      stage: "assessment",
      estimatedMinutes: 6,
      semantic: "assessment",
      progressiveSupports: ["tip"],
      interactionTurns: [
        { id: "a1-m1-l3-check-1", speaker: "Meaning", text: "أنا سعيد.", textArabic: "أنا سعيد.", purpose: "Choose: I am happy." },
        { id: "a1-m1-l3-check-2", speaker: "Meaning", text: "أنت صديقي.", textArabic: "أنت صديقي.", purpose: "Choose: You are my friend." },
        { id: "a1-m1-l3-check-3", speaker: "Meaning", text: "أنا طالب.", textArabic: "أنا طالب.", purpose: "Choose: I am a student." },
      ],
    },
  ],
  4: [
    {
      id: "a1-m1-l4-picture-listen",
      kind: "visual-vocabulary",
      title: "Picture English: people around you",
      titleArabic: "إنجليزية بالصور: الناس من حولك",
      objective: "Connect people words to sound, image, and a short correct caption.",
      objectiveArabic: "اربط كلمات الأشخاص بالصوت والصورة ووصف قصير صحيح.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: peopleVisuals,
    },
    {
      id: "a1-m1-l4-useful-chunk",
      kind: "standard",
      title: "One useful chunk: a person word",
      titleArabic: "تركيب مفيد: a مع كلمة شخص",
      objective: "Use a before a singular people word without asking the learner to master every a/an rule yet.",
      objectiveArabic: "استخدم a قبل كلمة شخص مفردة من دون مطالبة المتعلم بإتقان كل قواعد a/an الآن.",
      stage: "explanation",
      estimatedMinutes: 5,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "tip"],
      writingPrompt: "Say the useful chunks: a man, a woman, a child, a friend. Today learn these correct chunks; more a/an rules come later.",
      writingPromptArabic: "قل التراكيب المفيدة: a man وa woman وa child وa friend. اليوم تعلّم هذه التراكيب الصحيحة؛ وستأتي قواعد a/an الأخرى لاحقاً.",
      sentencePatterns: ["This is a ___.", "This is my friend."],
    },
    {
      id: "a1-m1-l4-caption-builder",
      kind: "interaction",
      title: "Build a picture caption",
      titleArabic: "ابنِ وصفاً للصورة",
      objective: "Select meaningful word chunks to describe one person in a picture.",
      objectiveArabic: "اختر مقاطع كلمات ذات معنى لوصف شخص واحد في صورة.",
      stage: "guided-practice",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["worked-example"],
      interactionTurns: [
        { id: "a1-m1-l4-caption-1", speaker: "Picture", text: "A girl with a school bag", textArabic: "بنت تحمل حقيبة مدرسية", purpose: "Build: This is a girl." },
        { id: "a1-m1-l4-caption-2", speaker: "Picture", text: "A woman in a photo", textArabic: "امرأة في صورة", purpose: "Build: This is a woman." },
        { id: "a1-m1-l4-caption-3", speaker: "Picture", text: "A friend beside you", textArabic: "صديق بجانبك", purpose: "Build: This is my friend." },
      ],
    },
    {
      id: "a1-m1-l4-return",
      kind: "review",
      title: "Bring back one sentence",
      titleArabic: "أعد جملة واحدة",
      objective: "Reconnect a people word with an earlier I am or you are sentence only where it sounds natural.",
      objectiveArabic: "أعد ربط كلمة شخص بجملة سابقة بـ I am أو you are فقط عندما يبدو ذلك طبيعياً.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["worked-example"],
      writingPrompt: "Choose one: I am a student. / You are my friend. Then add: This is a woman. Do not force every old word into the sentence.",
      writingPromptArabic: "اختر واحدة: I am a student. / You are my friend. ثم أضف: This is a woman. لا تُجبر كل الكلمات القديمة على الدخول في الجملة.",
    },
  ],
  5: [
    {
      id: "a1-m1-l5-retrieval-chain",
      kind: "review",
      title: "Bring four small pieces together",
      titleArabic: "اجمع أربع قطع صغيرة معاً",
      objective: "Retrieve one useful item from each of the first four lessons before a conversation rehearsal.",
      objectiveArabic: "استرجع عنصراً مفيداً من كل واحد من الدروس الأربعة الأولى قبل تدريب المحادثة.",
      stage: "introduction",
      estimatedMinutes: 5,
      semantic: "retrieval",
      progressiveSupports: ["word-support"],
      writingPrompt: "Remember one item from each lesson: Hello or Goodbye; My name is…; I am…; friend or woman/man/child.",
      writingPromptArabic: "تذكّر عنصراً واحداً من كل درس: Hello أو Goodbye؛ My name is…؛ I am…؛ friend أو woman/man/child.",
      suggestedVocabulary: ["hello", "my name is", "I am", "friend"],
    },
    {
      id: "a1-m1-l5-model",
      kind: "speaking",
      title: "Listen to a first complete conversation",
      titleArabic: "استمع إلى أول محادثة كاملة",
      objective: "Hear a greeting, name, simple fact, and closing as separate, understandable lines.",
      objectiveArabic: "استمع إلى تحية واسم ومعلومة بسيطة ووداع كجمل منفصلة مفهومة.",
      stage: "guided-practice",
      estimatedMinutes: 9,
      semantic: "example",
      progressiveSupports: ["transcript", "arabic-help"],
      speakingLines: [
        { id: "a1-m1-l5-model-1", speaker: "Amina", text: "Hello. My name is Amina.", textArabic: "مرحباً. اسمي أمينة.", pronunciationHint: "/həˈləʊ/ /maɪ neɪm ɪz/" },
        { id: "a1-m1-l5-model-2", speaker: "Samir", text: "Hi, Amina. My name is Samir.", textArabic: "أهلاً يا أمينة. اسمي سمير.", pronunciationHint: "/haɪ/ /maɪ neɪm ɪz/" },
        { id: "a1-m1-l5-model-3", speaker: "Amina", text: "I am a student. This is my friend, Noor.", textArabic: "أنا طالبة. هذه صديقتي نور.", pronunciationHint: "/aɪ æm ə ˈstjuːdnt/" },
        { id: "a1-m1-l5-model-4", speaker: "Samir", text: "Hello, Noor. Thank you. Goodbye.", textArabic: "مرحباً يا نور. شكراً. إلى اللقاء.", pronunciationHint: "/ˈθæŋk juː/ /ɡʊdˈbaɪ/" },
      ],
    },
    {
      id: "a1-m1-l5-roleplay",
      kind: "interaction",
      title: "Role-play: meet a classmate",
      titleArabic: "لعب أدوار: قابل زميلاً في الصف",
      objective: "Rehearse a four-line exchange with the option to speak, type, or practise silently first.",
      objectiveArabic: "تدرّب على تبادل من أربعة أسطر مع خيار التحدث أو الكتابة أو التدريب الصامت أولاً.",
      stage: "real-context",
      estimatedMinutes: 10,
      semantic: "activity",
      progressiveSupports: ["worked-example", "transcript", "word-support"],
      interactionTurns: [
        { id: "a1-m1-l5-role-1", speaker: "Rami", text: "Hello. My name is Rami. What is your name?", textArabic: "مرحباً. اسمي رامي. ما اسمك؟", purpose: "Give your name." },
        { id: "a1-m1-l5-role-2", speaker: "Learner", text: "Hi. My name is ___.", textArabic: "أهلاً. اسمي ___.", purpose: "Use an actual or imaginary name." },
        { id: "a1-m1-l5-role-3", speaker: "Learner", text: "I am a student. This is my friend, ___.", textArabic: "أنا طالب / طالبة. هذا صديقي / هذه صديقتي، ___.", purpose: "Add one simple fact." },
        { id: "a1-m1-l5-role-4", speaker: "Learner", text: "Thank you. Goodbye.", textArabic: "شكراً. إلى اللقاء.", purpose: "Close politely." },
      ],
    },
    {
      id: "a1-m1-l5-self-check",
      kind: "assessment",
      title: "Check the communication pieces",
      titleArabic: "تحقق من أجزاء التواصل",
      objective: "Check for a greeting, a name, one fact, and a polite closing; accent is never graded.",
      objectiveArabic: "تحقق من وجود تحية واسم ومعلومة واحدة ووداع مهذب؛ لا يُقيَّم النطق أو اللكنة.",
      stage: "assessment",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["tip"],
      writingPrompt: "After your first attempt, tick: greeting / name / one fact / polite closing. Choose one missing piece and try once more.",
      writingPromptArabic: "بعد المحاولة الأولى، ضع علامة: تحية / اسم / معلومة واحدة / وداع مهذب. اختر جزءاً ناقصاً وحاول مرة أخرى.",
    },
  ],
  6: [
    {
      id: "a1-m1-l6-number-meaning",
      kind: "standard",
      title: "Numbers that say something about you",
      titleArabic: "أرقام تقول شيئاً عنك",
      objective: "Meet a small set of number words through a meaningful question about age, not as an isolated list.",
      objectiveArabic: "تعرّف إلى مجموعة صغيرة من كلمات الأرقام من خلال سؤال ذي معنى عن العمر، لا كقائمة منفصلة.",
      stage: "introduction",
      estimatedMinutes: 6,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      suggestedVocabulary: ["one", "two", "three", "ten", "twenty", "years old"],
      writingPrompt: "Look at the number cards: 1, 2, 3, 10, 20. Say each English word once, then choose the number you use most in your real life today.",
      writingPromptArabic: "انظر إلى بطاقات الأرقام: 1 و2 و3 و10 و20. قل كل كلمة إنجليزية مرة، ثم اختر الرقم الذي تستخدمه أكثر في حياتك اليوم.",
    },
    {
      id: "a1-m1-l6-age-pattern",
      kind: "speaking",
      title: "One English age pattern",
      titleArabic: "نمط واحد للعمر بالإنجليزية",
      objective: "Notice that English says I am ... years old, including the small verb that Arabic does not show in the same way.",
      objectiveArabic: "لاحظ أن الإنجليزية تقول I am ... years old، بما في ذلك الفعل الصغير الذي لا يظهر بالطريقة نفسها في العربية.",
      stage: "explanation",
      estimatedMinutes: 7,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      speakingLines: [
        { id: "a1-m1-l6-pattern-1", speaker: "Model", text: "I am twenty years old.", textArabic: "عمري عشرون سنة.", pronunciationHint: "/aɪ æm ˈtwenti jɪəz əʊld/", audioText: "I am twenty years old." },
        { id: "a1-m1-l6-pattern-2", speaker: "Tip", text: "Do not say: I have twenty years.", textArabic: "لا تقل: I have twenty years.", pronunciationHint: "Use I am for age in English.", audioText: "I am twenty years old." },
        { id: "a1-m1-l6-pattern-3", speaker: "Model", text: "How old are you?", textArabic: "كم عمرك؟", pronunciationHint: "/haʊ əʊld ɑː juː/", audioText: "How old are you?" },
      ],
    },
    {
      id: "a1-m1-l6-age-card",
      kind: "interaction",
      title: "Read a name card, then answer naturally",
      titleArabic: "اقرأ بطاقة اسم ثم أجب بطريقة طبيعية",
      objective: "Use an age pattern with either a real, invented, or private age; the learner never has to disclose personal information.",
      objectiveArabic: "استخدم نمط العمر بعمر حقيقي أو متخيَّل أو خاص؛ لا يتوجب على المتعلم الإفصاح عن معلوماته الشخصية.",
      stage: "real-context",
      estimatedMinutes: 9,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m1-l6-card-1", speaker: "Name card", text: "Nour — 20", textArabic: "نور — 20", purpose: "Say: Nour is twenty years old." },
        { id: "a1-m1-l6-card-2", speaker: "Partner", text: "How old are you?", textArabic: "كم عمرك؟", purpose: "Choose a real, invented, or private answer: I am ___ years old." },
        { id: "a1-m1-l6-card-3", speaker: "Partner", text: "Thank you.", textArabic: "شكراً.", purpose: "Notice that a short answer is enough; do not add unnecessary personal detail." },
      ],
    },
    {
      id: "a1-m1-l6-bridge",
      kind: "review",
      title: "Add one new detail to your introduction",
      titleArabic: "أضف تفصيلاً جديداً واحداً إلى تعريفك",
      objective: "Reuse the name introduction from Lesson 2 only where it helps a natural two-line introduction.",
      objectiveArabic: "أعد استخدام تعريف الاسم من الدرس 2 فقط عندما يساعد في تكوين تعريف طبيعي من سطرين.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["worked-example"],
      writingPrompt: "Choose one: Hello, my name is ___. / I am ___ years old. Say the two lines together once. You do not need every old word today.",
      writingPromptArabic: "اختر: Hello, my name is ___. / I am ___ years old. قل السطرين معاً مرة. لا تحتاج إلى كل الكلمات القديمة اليوم.",
    },
  ],
  7: [
    {
      id: "a1-m1-l7-colour-object-gallery",
      kind: "visual-vocabulary",
      title: "Look, hear, and name classroom things",
      titleArabic: "انظر، واستمع، وسمِّ أشياء الصف",
      objective: "Connect a colour and an everyday classroom object through image, sound, and a short useful phrase.",
      objectiveArabic: "اربط لوناً وشيئاً يومياً في الصف بالصورة والصوت وعبارة قصيرة مفيدة.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: [
        { id: "a1-m1-l7-red-pen", word: "red pen", arabic: "قلم أحمر", pronunciation: "/red pen/", exampleEN: "It is a red pen.", exampleAR: "إنه قلم أحمر.", altText: "A simple red pen on a neutral desk", category: "Classroom", interactionHint: "Hear red, then hear pen. Say the phrase together." },
        { id: "a1-m1-l7-blue-bag", word: "blue bag", arabic: "حقيبة زرقاء", pronunciation: "/bluː bæɡ/", exampleEN: "It is a blue bag.", exampleAR: "إنها حقيبة زرقاء.", altText: "A simple blue school bag", category: "Classroom", interactionHint: "Hear blue, then hear bag. Say the phrase together." },
        { id: "a1-m1-l7-green-book", word: "green book", arabic: "كتاب أخضر", pronunciation: "/ɡriːn bʊk/", exampleEN: "It is a green book.", exampleAR: "إنه كتاب أخضر.", altText: "A simple green book with no text", category: "Classroom", interactionHint: "Hear green, then hear book. Say the phrase together." },
      ],
    },
    {
      id: "a1-m1-l7-word-order-notice",
      kind: "standard",
      title: "Notice the order: colour first",
      titleArabic: "لاحظ الترتيب: اللون أولاً",
      objective: "Notice one useful English pattern—colour before object—without adding a long adjective lecture.",
      objectiveArabic: "لاحظ نمطاً إنجليزياً مفيداً واحداً—اللون قبل الشيء—من دون إضافة شرح طويل عن الصفات.",
      stage: "explanation",
      estimatedMinutes: 5,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      sentencePatterns: ["a red pen", "a blue bag", "a green book"],
      writingPrompt: "English says a red pen. Put the colour first, then the thing. Today you only need this useful pattern.",
      writingPromptArabic: "تقول الإنجليزية a red pen. ضع اللون أولاً ثم الشيء. اليوم تحتاج فقط إلى هذا النمط المفيد.",
    },
    {
      id: "a1-m1-l7-classroom-scan",
      kind: "interaction",
      title: "Find it in a calm classroom scene",
      titleArabic: "اعثر عليه في مشهد صف هادئ",
      objective: "Choose the phrase that describes an object in context instead of matching words by spelling alone.",
      objectiveArabic: "اختر العبارة التي تصف شيئاً في السياق بدلاً من مطابقة الكلمات عبر الإملاء فقط.",
      stage: "guided-practice",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["worked-example", "arabic-help"],
      interactionTurns: [
        { id: "a1-m1-l7-scan-1", speaker: "Scene", text: "A book on Layla’s desk is green.", textArabic: "هناك كتاب أخضر على مكتب ليلى.", purpose: "Choose: a green book." },
        { id: "a1-m1-l7-scan-2", speaker: "Scene", text: "Omar has a bag. The bag is blue.", textArabic: "لدى عمر حقيبة. الحقيبة زرقاء.", purpose: "Choose: a blue bag." },
        { id: "a1-m1-l7-scan-3", speaker: "Scene", text: "The teacher gives Aya a red pen.", textArabic: "تعطي المعلمة آية قلماً أحمر.", purpose: "Choose: a red pen." },
      ],
    },
    {
      id: "a1-m1-l7-choice-task",
      kind: "speaking",
      title: "Describe one thing you can see",
      titleArabic: "صِف شيئاً واحداً تراه",
      objective: "Make one self-chosen phrase about a real or imagined object, with a choice to speak, point, or type.",
      objectiveArabic: "كوِّن عبارة واحدة من اختيارك عن شيء حقيقي أو متخيَّل، مع خيار التحدث أو الإشارة أو الكتابة.",
      stage: "real-context",
      estimatedMinutes: 6,
      semantic: "activity",
      progressiveSupports: ["word-support", "tip"],
      speakingLines: [
        { id: "a1-m1-l7-choice-1", speaker: "Frame", text: "It is a ___ ___.", textArabic: "إنه / إنها ___ ___.", pronunciationHint: "Colour first, object second.", audioText: "It is a blue bag." },
        { id: "a1-m1-l7-choice-2", speaker: "Example", text: "It is a blue bag.", textArabic: "إنها حقيبة زرقاء.", pronunciationHint: "/ɪt ɪz ə bluː bæɡ/", audioText: "It is a blue bag." },
      ],
    },
  ],
  8: [
    {
      id: "a1-m1-l8-classroom-return",
      kind: "review",
      title: "Use a word you already know in class",
      titleArabic: "استخدم كلمة تعرفها مسبقاً في الصف",
      objective: "Retrieve one familiar item—book, pen, hello, or thank you—because it genuinely belongs in a classroom moment.",
      objectiveArabic: "استرجع عنصراً مألوفاً واحداً—book أو pen أو hello أو thank you—لأنه ينتمي فعلاً إلى موقف صفي.",
      stage: "introduction",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support"],
      writingPrompt: "Your teacher gives you a blue pen. What can you say? Choose: Thank you. / Hello. Then name the object: a blue pen.",
      writingPromptArabic: "تعطيك المعلمة قلماً أزرق. ماذا يمكنك أن تقول؟ اختر: Thank you. / Hello. ثم سمِّ الشيء: a blue pen.",
    },
    {
      id: "a1-m1-l8-direction-or-request",
      kind: "interaction",
      title: "Listen: a direction or a kind request?",
      titleArabic: "استمع: هل هي تعليمات أم طلب لطيف؟",
      objective: "Hear the useful difference between Listen or Repeat and Can you repeat, please? before trying it in a role-play.",
      objectiveArabic: "استمع إلى الفرق المفيد بين Listen أو Repeat وCan you repeat, please? قبل تجربته في لعب أدوار.",
      stage: "explanation",
      estimatedMinutes: 7,
      semantic: "example",
      progressiveSupports: ["transcript", "arabic-help", "tip"],
      speakingLines: [
        { id: "a1-m1-l8-notice-1", speaker: "Teacher", text: "Listen.", textArabic: "استمع.", pronunciationHint: "/ˈlɪsn/", audioText: "Listen." },
        { id: "a1-m1-l8-notice-2", speaker: "Teacher", text: "Repeat: blue bag.", textArabic: "كرّر: blue bag.", pronunciationHint: "/rɪˈpiːt/", audioText: "Repeat: blue bag." },
        { id: "a1-m1-l8-notice-3", speaker: "Learner", text: "Can you repeat, please?", textArabic: "هل يمكنك أن تكرر من فضلك؟", pronunciationHint: "/kæn juː rɪˈpiːt pliːz/", audioText: "Can you repeat, please?" },
      ],
    },
    {
      id: "a1-m1-l8-help-roleplay",
      kind: "interaction",
      title: "Ask for help when a word is new",
      titleArabic: "اطلب المساعدة عندما تكون الكلمة جديدة",
      objective: "Take part in a short classroom exchange that gives the learner a useful repair phrase rather than pretending to understand.",
      objectiveArabic: "شارك في تبادل صفي قصير يمنح المتعلم عبارة مفيدة لطلب التوضيح بدلاً من الادعاء بأنه فهم.",
      stage: "real-context",
      estimatedMinutes: 10,
      semantic: "activity",
      progressiveSupports: ["worked-example", "transcript", "word-support"],
      interactionTurns: [
        { id: "a1-m1-l8-role-1", speaker: "Teacher", text: "Look at the green book.", textArabic: "انظر إلى الكتاب الأخضر.", purpose: "You understand green book." },
        { id: "a1-m1-l8-role-2", speaker: "Teacher", text: "Open your notebook.", textArabic: "افتح دفترك.", purpose: "Notebook is new. You can ask instead of guessing." },
        { id: "a1-m1-l8-role-3", speaker: "Learner", text: "Can you repeat, please?", textArabic: "هل يمكنك أن تكرر من فضلك؟", purpose: "Use the polite repair phrase." },
        { id: "a1-m1-l8-role-4", speaker: "Teacher", text: "Notebook. This is a notebook.", textArabic: "Notebook. هذا دفتر.", purpose: "The learner receives the meaning and can try again." },
      ],
    },
    {
      id: "a1-m1-l8-confidence-check",
      kind: "assessment",
      title: "A classroom confidence check",
      titleArabic: "تحقق من الثقة داخل الصف",
      objective: "Identify one phrase you can already use and one phrase you want to practise again; this is reflection, not a graded accent test.",
      objectiveArabic: "حدّد عبارة واحدة يمكنك استخدامها بالفعل وعبارة واحدة تريد التدرّب عليها مرة أخرى؛ هذا تأمل وليس اختباراً للّكنة.",
      stage: "assessment",
      estimatedMinutes: 4,
      semantic: "assessment",
      progressiveSupports: ["tip"],
      writingPrompt: "Tick one: I can say Listen. / I can say Repeat. / I can ask Can you repeat, please? Choose one phrase for one more calm attempt.",
      writingPromptArabic: "ضع علامة على واحدة: يمكنني قول Listen. / يمكنني قول Repeat. / يمكنني سؤال Can you repeat, please? اختر عبارة واحدة لمحاولة هادئة أخرى.",
    },
  ],
  9: [
    {
      id: "a1-m1-l9-kind-reading",
      kind: "reading",
      title: "Read a small welcome card",
      titleArabic: "اقرأ بطاقة ترحيب قصيرة",
      objective: "Read a short, kind profile for meaning, using repetition as help rather than trying to translate every word.",
      objectiveArabic: "اقرأ تعريفاً قصيراً ولطيفاً من أجل المعنى، واستخدم التكرار كمساعدة بدلاً من محاولة ترجمة كل كلمة.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "activity",
      progressiveSupports: ["arabic-help", "transcript", "word-support"],
      writingPrompt: "Read slowly: Hello. My name is Hana. I am a new student. I am from Cairo. I have a blue book. Ali is my friend. You do not need every word; find the name, place, and object.",
      writingPromptArabic: "اقرأ ببطء: Hello. My name is Hana. I am a new student. I am from Cairo. I have a blue book. Ali is my friend. لا تحتاج إلى كل كلمة؛ ابحث عن الاسم والمكان والشيء.",
      suggestedVocabulary: ["new", "student", "from", "book", "friend"],
    },
    {
      id: "a1-m1-l9-from-notice",
      kind: "standard",
      title: "One useful reading pattern: from",
      titleArabic: "نمط قراءة مفيد واحد: from",
      objective: "Notice that from connects a person to a place in a simple identity sentence.",
      objectiveArabic: "لاحظ أن from تربط الشخص بمكان في جملة هوية بسيطة.",
      stage: "explanation",
      estimatedMinutes: 5,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      writingPrompt: "In the card, Hana says: I am from Cairo. Read the whole small pattern together. Do not learn a place list today.",
      writingPromptArabic: "تقول هناء في البطاقة: I am from Cairo. اقرأ النمط الصغير كاملاً. لا تتعلم قائمة أماكن اليوم.",
      sentencePatterns: ["I am from Cairo.", "She is from ___."],
    },
    {
      id: "a1-m1-l9-reading-check",
      kind: "interaction",
      title: "Find the answer in the card",
      titleArabic: "اعثر على الإجابة في البطاقة",
      objective: "Answer simple meaning questions by returning to the exact line, not by guessing from an isolated word.",
      objectiveArabic: "أجب عن أسئلة المعنى البسيطة بالعودة إلى السطر نفسه، لا بالتخمين من كلمة منفردة.",
      stage: "guided-practice",
      estimatedMinutes: 9,
      semantic: "activity",
      progressiveSupports: ["worked-example", "arabic-help", "word-support"],
      interactionTurns: [
        { id: "a1-m1-l9-check-1", speaker: "Question", text: "What is the new student’s name?", textArabic: "ما اسم الطالب الجديد؟", purpose: "Return to: My name is Hana. Answer: Hana." },
        { id: "a1-m1-l9-check-2", speaker: "Question", text: "Where is Hana from?", textArabic: "من أين هناء؟", purpose: "Return to: I am from Cairo. Answer: Cairo." },
        { id: "a1-m1-l9-check-3", speaker: "Question", text: "What colour is Hana’s book?", textArabic: "ما لون كتاب هناء؟", purpose: "Return to: a blue book. Answer: blue." },
      ],
    },
    {
      id: "a1-m1-l9-gentle-recall",
      kind: "review",
      title: "Carry one line forward",
      titleArabic: "خذ سطراً واحداً معك",
      objective: "Keep one useful line from the reading ready for the next profile-writing lesson without forcing unrelated old vocabulary into it.",
      objectiveArabic: "احتفظ بسطر مفيد واحد من القراءة جاهزاً لدرس كتابة التعريف التالي من دون فرض مفردات قديمة غير مناسبة.",
      stage: "review",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["worked-example"],
      writingPrompt: "Choose one line to remember: My name is Hana. / I am from Cairo. Say it once, then close the card.",
      writingPromptArabic: "اختر سطراً واحداً لتتذكره: My name is Hana. / I am from Cairo. قلْه مرة ثم أغلق البطاقة.",
    },
  ],
  10: [
    {
      id: "a1-m1-l10-profile-pieces",
      kind: "review",
      title: "Choose only the details you want to write",
      titleArabic: "اختر فقط التفاصيل التي تريد كتابتها",
      objective: "Collect familiar profile pieces while keeping real personal information optional.",
      objectiveArabic: "اجمع أجزاء تعريف مألوفة مع إبقاء المعلومات الشخصية الحقيقية اختيارية.",
      stage: "introduction",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Choose a real or invented name, place, role, family detail, or favourite colour. You can leave any detail private.",
      writingPromptArabic: "اختر اسماً أو مكاناً أو دوراً أو تفصيلاً عائلياً أو لوناً مفضلاً حقيقياً أو متخيلاً. يمكنك إبقاء أي تفصيل خاصاً.",
      suggestedVocabulary: ["name", "from", "student", "family", "colour"],
    },
    {
      id: "a1-m1-l10-small-writing-rules",
      kind: "standard",
      title: "Make each small sentence easy to read",
      titleArabic: "اجعل كل جملة صغيرة سهلة القراءة",
      objective: "Use capital I and a full stop as reader-friendly signals rather than as a large punctuation lecture.",
      objectiveArabic: "استخدم I الكبيرة والنقطة كإشارات تساعد القارئ بدلاً من محاضرة طويلة عن علامات الترقيم.",
      stage: "explanation",
      estimatedMinutes: 6,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      writingPrompt: "Write I with a capital letter every time. Finish one thought with a full stop. Try: I am a student. Not: i am a student",
      writingPromptArabic: "اكتب I بحرف كبير كل مرة. أنهِ الفكرة الواحدة بنقطة. جرّب: I am a student. وليس: i am a student",
      sentencePatterns: ["My name is ___.", "I am from ___.", "I am a student."],
    },
    {
      id: "a1-m1-l10-guided-profile",
      kind: "writing",
      title: "Write your first three to five lines",
      titleArabic: "اكتب أول ثلاثة إلى خمسة أسطر لك",
      objective: "Write a short, supported profile using language already met in greetings, identity, age, colours, and the reading card.",
      objectiveArabic: "اكتب تعريفاً قصيراً مدعوماً باستخدام لغة ظهرت سابقاً في التحيات والهوية والعمر والألوان وبطاقة القراءة.",
      stage: "guided-practice",
      estimatedMinutes: 12,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "arabic-help", "external-ai-prompt"],
      writingPrompt: "Use only the frames you need: Hello. My name is ___. I am from ___. I am a student. I have a ___ book. My favourite colour is ___. Write three to five lines; an invented profile is welcome.",
      writingPromptArabic: "استخدم القوالب التي تحتاجها فقط: Hello. My name is ___. I am from ___. I am a student. I have a ___ book. My favourite colour is ___. اكتب من ثلاثة إلى خمسة أسطر؛ التعريف المتخيَّل مرحب به.",
      suggestedVocabulary: ["hello", "name", "from", "student", "book", "colour"],
      sentencePatterns: ["My name is ___.", "I am from ___.", "I am a ___.", "I have a ___ book."],
    },
    {
      id: "a1-m1-l10-reader-check",
      kind: "assessment",
      title: "Read your profile as a friendly reader",
      titleArabic: "اقرأ تعريفك كقارئ ودود",
      objective: "Check only the few features taught today—capital I, a full stop, and one clear message—before deciding what to practise next.",
      objectiveArabic: "تحقق فقط من الأمور القليلة التي تعلّمتها اليوم—I الكبيرة والنقطة ورسالة واضحة واحدة—قبل تحديد ما ستتدرب عليه لاحقاً.",
      stage: "assessment",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["worked-example", "tip"],
      writingPrompt: "Read your lines slowly. Tick: I is capital. / Each finished line has a full stop. / I can understand one message. Then choose one line to keep or improve.",
      writingPromptArabic: "اقرأ أسطرك ببطء. ضع علامة: I كبيرة. / كل سطر مكتمل له نقطة. / أستطيع فهم رسالة واحدة. ثم اختر سطراً واحداً تحتفظ به أو تحسّنه.",
    },
  ],
  11: [
    {
      id: "a1-m1-l11-family-gallery",
      kind: "visual-vocabulary",
      title: "A small family picture story",
      titleArabic: "قصة مصورة قصيرة عن العائلة",
      objective: "Meet a few family words through a fictional picture story, with no requirement to discuss the learner’s own family.",
      objectiveArabic: "تعرّف على بعض كلمات العائلة من خلال قصة مصورة خيالية من دون حاجة إلى الحديث عن عائلة المتعلم.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: [
        { id: "a1-m1-l11-mother", word: "mother", arabic: "أم", pronunciation: "/ˈmʌðə/", exampleEN: "This is my mother.", exampleAR: "هذه أمي.", altText: "A neutral fictional family card labelled mother", category: "Family", interactionHint: "Hear mother, point to the card, then say the whole line." },
        { id: "a1-m1-l11-father", word: "father", arabic: "أب", pronunciation: "/ˈfɑːðə/", exampleEN: "This is my father.", exampleAR: "هذا أبي.", altText: "A neutral fictional family card labelled father", category: "Family", interactionHint: "Hear father, point to the card, then say the whole line." },
        { id: "a1-m1-l11-sister", word: "sister", arabic: "أخت", pronunciation: "/ˈsɪstə/", exampleEN: "I have a sister.", exampleAR: "لدي أخت.", altText: "A neutral fictional family card labelled sister", category: "Family", interactionHint: "Hear sister, then say I have a sister." },
      ],
    },
    {
      id: "a1-m1-l11-have-my",
      kind: "standard",
      title: "Two useful family patterns",
      titleArabic: "نَمَطان مفيدان عن العائلة",
      objective: "Choose between I have a ... and This is my ... because each pattern serves a different simple meaning.",
      objectiveArabic: "اختر بين I have a ... وThis is my ... لأن كل نمط يخدم معنى بسيطاً مختلفاً.",
      stage: "explanation",
      estimatedMinutes: 7,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      writingPrompt: "Use I have a sister when you say someone is in your family. Use This is my sister when you point to or introduce that person.",
      writingPromptArabic: "استخدم I have a sister عندما تقول إن شخصاً في عائلتك. واستخدم This is my sister عندما تشير إلى هذا الشخص أو تعرّف به.",
      sentencePatterns: ["I have a sister.", "This is my mother.", "This is my father."],
    },
    {
      id: "a1-m1-l11-fictional-family-card",
      kind: "interaction",
      title: "Introduce a fictional family card",
      titleArabic: "عرّف ببطاقة عائلة خيالية",
      objective: "Use one family pattern in a safe fictional scenario, then choose whether to connect it to a real life detail or not.",
      objectiveArabic: "استخدم نمط عائلة واحداً في موقف خيالي آمن، ثم اختر إن كنت تريد ربطه بتفصيل حقيقي أم لا.",
      stage: "real-context",
      estimatedMinutes: 9,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "tip"],
      interactionTurns: [
        { id: "a1-m1-l11-card-1", speaker: "Card", text: "Mona has a sister. Her name is Salma.", textArabic: "لدى منى أخت. اسمها سلمى.", purpose: "Say: Mona has a sister." },
        { id: "a1-m1-l11-card-2", speaker: "Card", text: "This is Mona’s mother.", textArabic: "هذه أم منى.", purpose: "Say: This is my mother only if you choose a personal version; otherwise keep the fictional card." },
        { id: "a1-m1-l11-card-3", speaker: "Choice", text: "Choose a fictional person or a person you want to introduce.", textArabic: "اختر شخصاً خيالياً أو شخصاً ترغب في التعريف به.", purpose: "Make one short line. Privacy is always your choice." },
      ],
    },
    {
      id: "a1-m1-l11-profile-optional-bridge",
      kind: "review",
      title: "Choose one optional profile addition",
      titleArabic: "اختر إضافة اختيارية واحدة إلى تعريفك",
      objective: "Offer a family sentence as one possible profile addition, never as a requirement or a forced retrieval item.",
      objectiveArabic: "قدّم جملة عن العائلة كإضافة ممكنة إلى التعريف، وليس كمتطلب أو استرجاع مفروض.",
      stage: "review",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["tip", "word-support"],
      writingPrompt: "Optional: add I have a ___. to yesterday’s profile. Or keep your profile exactly as it is and practise a fictional family line instead.",
      writingPromptArabic: "اختياري: أضف I have a ___. إلى تعريف الأمس. أو أبقِ تعريفك كما هو وتدرّب على سطر عن عائلة خيالية بدلاً من ذلك.",
    },
  ],
  12: [
    {
      id: "a1-m1-l12-job-picture-set",
      kind: "visual-vocabulary",
      title: "People and the work they do",
      titleArabic: "الناس والعمل الذي يقومون به",
      objective: "Meet a small set of professions through people and purposes rather than memorising a long word list.",
      objectiveArabic: "تعرّف على مجموعة صغيرة من المهن من خلال الأشخاص والأدوار بدلاً من حفظ قائمة طويلة من الكلمات.",
      stage: "introduction",
      estimatedMinutes: 9,
      semantic: "vocabulary",
      progressiveSupports: ["arabic-help", "word-support"],
      visualItems: [
        { id: "a1-m1-l12-teacher", word: "teacher", arabic: "معلّم / معلّمة", pronunciation: "/ˈtiːtʃə/", exampleEN: "She is a teacher.", exampleAR: "هي معلّمة.", altText: "A neutral teacher in a classroom", category: "Jobs", interactionHint: "Hear teacher, then choose the classroom picture." },
        { id: "a1-m1-l12-doctor", word: "doctor", arabic: "طبيب / طبيبة", pronunciation: "/ˈdɒktə/", exampleEN: "He is a doctor.", exampleAR: "هو طبيب.", altText: "A neutral doctor at a clinic", category: "Jobs", interactionHint: "Hear doctor, then choose the clinic picture." },
        { id: "a1-m1-l12-cook", word: "cook", arabic: "طباخ / طباخة", pronunciation: "/kʊk/", exampleEN: "She is a cook.", exampleAR: "هي طباخة.", altText: "A neutral cook preparing food", category: "Jobs", interactionHint: "Hear cook, then choose the kitchen picture." },
      ],
    },
    {
      id: "a1-m1-l12-job-chunk-notice",
      kind: "standard",
      title: "One job sentence chunk",
      titleArabic: "تركيب جملة واحد عن المهنة",
      objective: "Use a or an with a singular job word as a useful sentence chunk, without turning the lesson into an exception list.",
      objectiveArabic: "استخدم a أو an مع كلمة مهنة مفردة كتركيب مفيد في الجملة، من دون تحويل الدرس إلى قائمة استثناءات.",
      stage: "explanation",
      estimatedMinutes: 6,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      writingPrompt: "Say whole chunks: a teacher, a doctor, a cook. Later you will meet an artist because it begins with a vowel sound. Today, let the useful chunks lead.",
      writingPromptArabic: "قل التراكيب كاملة: a teacher وa doctor وa cook. ستقابل لاحقاً an artist لأنها تبدأ بصوت علة. اليوم دع التراكيب المفيدة تقودك.",
      sentencePatterns: ["She is a teacher.", "He is a doctor.", "I am a student."],
    },
    {
      id: "a1-m1-l12-job-scene-choice",
      kind: "interaction",
      title: "Choose the right job in a scene",
      titleArabic: "اختر المهنة المناسبة في مشهد",
      objective: "Use the new words in a simple setting and revisit is only when it naturally carries the sentence.",
      objectiveArabic: "استخدم الكلمات الجديدة في موقف بسيط وراجع is فقط عندما تحمل الجملة بشكل طبيعي.",
      stage: "guided-practice",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support"],
      interactionTurns: [
        { id: "a1-m1-l12-scene-1", speaker: "Scene", text: "Mariam works with students in a classroom.", textArabic: "تعمل مريم مع الطلاب في صف.", purpose: "Choose: She is a teacher." },
        { id: "a1-m1-l12-scene-2", speaker: "Scene", text: "Ahmed works with people at a clinic.", textArabic: "يعمل أحمد مع الناس في عيادة.", purpose: "Choose: He is a doctor." },
        { id: "a1-m1-l12-scene-3", speaker: "Scene", text: "Nora makes food in a kitchen.", textArabic: "تعد نورا الطعام في مطبخ.", purpose: "Choose: She is a cook." },
      ],
    },
    {
      id: "a1-m1-l12-meeting-bridge",
      kind: "review",
      title: "Save one job line for a meeting",
      titleArabic: "احتفظ بسطر مهنة واحد للقاء",
      objective: "Bring one profession sentence into tomorrow’s first-meeting conversation only because it adds a natural new detail.",
      objectiveArabic: "خذ جملة مهنة واحدة إلى محادثة اللقاء غداً فقط لأنها تضيف تفصيلاً جديداً طبيعياً.",
      stage: "review",
      estimatedMinutes: 3,
      semantic: "retrieval",
      progressiveSupports: ["word-support"],
      writingPrompt: "Choose one line to keep: I am a student. / She is a teacher. You will decide whether it belongs in the next conversation.",
      writingPromptArabic: "اختر سطراً واحداً للاحتفاظ به: I am a student. / She is a teacher. ستقرر إن كان يناسب المحادثة التالية.",
    },
  ],
  13: [
    {
      id: "a1-m1-l13-meeting-goal",
      kind: "review",
      title: "Choose the details a first meeting needs",
      titleArabic: "اختر التفاصيل التي يحتاجها اللقاء الأول",
      objective: "Retrieve only the language that belongs in a first meeting—greeting, name, place, or role—rather than reciting the whole word bank.",
      objectiveArabic: "استرجع فقط اللغة التي تنتمي إلى اللقاء الأول—التحية والاسم والمكان أو الدور—بدلاً من تكرار بنك الكلمات كاملاً.",
      stage: "introduction",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Choose two meeting details: Hello. / My name is ___. / I am from ___. / I am a student. You do not need all four.",
      writingPromptArabic: "اختر تفصيلين للقاء: Hello. / My name is ___. / I am from ___. / I am a student. لا تحتاج إلى الأربعة كلها.",
    },
    {
      id: "a1-m1-l13-question-word-notice",
      kind: "standard",
      title: "Three question words, three purposes",
      titleArabic: "ثلاث كلمات سؤال، ثلاث وظائف",
      objective: "Notice What for a name or thing, Where for a place, and Who for a person in a live conversation context.",
      objectiveArabic: "لاحظ What للاسم أو الشيء وWhere للمكان وWho للشخص في سياق محادثة حي.",
      stage: "explanation",
      estimatedMinutes: 7,
      semantic: "grammar",
      progressiveSupports: ["arabic-help", "worked-example", "tip"],
      writingPrompt: "What is your name? Where are you from? Who is she? The question word comes first and tells you what information you need.",
      writingPromptArabic: "What is your name? Where are you from? Who is she? تأتي كلمة السؤال أولاً وتخبرك بالمعلومة التي تحتاجها.",
      sentencePatterns: ["What is your name?", "Where are you from?", "Who is she?"],
    },
    {
      id: "a1-m1-l13-supported-meeting",
      kind: "interaction",
      title: "A first meeting with choices",
      titleArabic: "لقاء أول مع اختيارات",
      objective: "Carry out a short first meeting, choosing which question is useful next instead of reading a fixed dialogue without meaning.",
      objectiveArabic: "نفّذ لقاءً أول قصيراً باختيار السؤال المفيد التالي بدلاً من قراءة حوار ثابت بلا معنى.",
      stage: "real-context",
      estimatedMinutes: 12,
      semantic: "activity",
      progressiveSupports: ["transcript", "worked-example", "word-support", "arabic-help"],
      interactionTurns: [
        { id: "a1-m1-l13-turn-1", speaker: "Hana", text: "Hello. My name is Hana. What is your name?", textArabic: "مرحباً. اسمي هناء. ما اسمك؟", purpose: "Give a greeting and ask for a name." },
        { id: "a1-m1-l13-turn-2", speaker: "Omar", text: "Hi. My name is Omar. I am from Alexandria.", textArabic: "أهلاً. اسمي عمر. أنا من الإسكندرية.", purpose: "Give one new detail." },
        { id: "a1-m1-l13-turn-3", speaker: "Hana", text: "Where are you from?", textArabic: "من أين أنت؟", purpose: "Ask only if the place is not already known; meaningful questions respond to the conversation." },
        { id: "a1-m1-l13-turn-4", speaker: "Omar", text: "I am a student. Who is she?", textArabic: "أنا طالب. من هي؟", purpose: "Use a role and ask about another person in the scene." },
      ],
    },
    {
      id: "a1-m1-l13-three-question-check",
      kind: "assessment",
      title: "Choose the question that fits",
      titleArabic: "اختر السؤال المناسب",
      objective: "Show that you can distinguish the purpose of What, Where, and Who in context without a spelling-trick quiz.",
      objectiveArabic: "أظهر أنك تستطيع تمييز وظيفة What وWhere وWho في السياق من دون اختبار خداعي في الإملاء.",
      stage: "assessment",
      estimatedMinutes: 5,
      semantic: "assessment",
      progressiveSupports: ["worked-example"],
      interactionTurns: [
        { id: "a1-m1-l13-check-1", speaker: "Need", text: "You want to know a new person’s name.", textArabic: "تريد معرفة اسم شخص جديد.", purpose: "Choose: What is your name?" },
        { id: "a1-m1-l13-check-2", speaker: "Need", text: "You want to know a person’s city.", textArabic: "تريد معرفة مدينة شخص.", purpose: "Choose: Where are you from?" },
        { id: "a1-m1-l13-check-3", speaker: "Need", text: "You see a new woman in a photo.", textArabic: "ترى امرأة جديدة في صورة.", purpose: "Choose: Who is she?" },
      ],
    },
  ],
  14: [
    {
      id: "a1-m1-l14-model-listen",
      kind: "speaking",
      title: "Hear a whole first meeting",
      titleArabic: "استمع إلى لقاء أول كامل",
      objective: "Hear a short, familiar conversation as connected speech and notice that clear rhythm matters more than copying an accent.",
      objectiveArabic: "استمع إلى محادثة قصيرة مألوفة ككلام متصل ولاحظ أن الإيقاع الواضح أهم من تقليد لهجة.",
      stage: "introduction",
      estimatedMinutes: 7,
      semantic: "example",
      progressiveSupports: ["transcript", "arabic-help", "tip"],
      speakingLines: [
        { id: "a1-m1-l14-model-1", speaker: "Hana", text: "Hello. My name is Hana. What is your name?", textArabic: "مرحباً. اسمي هناء. ما اسمك؟", pronunciationHint: "Pause after Hello and Hana.", audioText: "Hello. My name is Hana. What is your name?" },
        { id: "a1-m1-l14-model-2", speaker: "Omar", text: "Hi. My name is Omar. I am from Alexandria.", textArabic: "أهلاً. اسمي عمر. أنا من الإسكندرية.", pronunciationHint: "Keep I am together as one small rhythm group.", audioText: "Hi. My name is Omar. I am from Alexandria." },
        { id: "a1-m1-l14-model-3", speaker: "Hana", text: "Nice to meet you, Omar.", textArabic: "سعيدة بلقائك يا عمر.", pronunciationHint: "Aim for a friendly, understandable message, not a perfect accent.", audioText: "Nice to meet you, Omar." },
      ],
    },
    {
      id: "a1-m1-l14-choice-rehearsal",
      kind: "interaction",
      title: "Build the version you can say",
      titleArabic: "ابنِ النسخة التي يمكنك قولها",
      objective: "Rehearse a 30–45 second introduction by choosing a short, medium, or full version rather than demanding the same performance from every learner.",
      objectiveArabic: "تدرّب على تعريف من 30 إلى 45 ثانية باختيار نسخة قصيرة أو متوسطة أو كاملة بدلاً من طلب الأداء نفسه من كل متعلم.",
      stage: "real-context",
      estimatedMinutes: 12,
      semantic: "activity",
      progressiveSupports: ["worked-example", "transcript", "word-support", "tip"],
      interactionTurns: [
        { id: "a1-m1-l14-short", speaker: "Short version", text: "Hello. My name is ___. Nice to meet you.", textArabic: "مرحباً. اسمي ___. سعيد بلقائك.", purpose: "Use this if you need one calm first attempt." },
        { id: "a1-m1-l14-medium", speaker: "Medium version", text: "Hello. My name is ___. I am from ___. I am a student.", textArabic: "مرحباً. اسمي ___. أنا من ___. أنا طالب / طالبة.", purpose: "Add two details if they feel comfortable." },
        { id: "a1-m1-l14-full", speaker: "Full version", text: "Hello. My name is ___. I am from ___. I am a student. I have a ___. Nice to meet you.", textArabic: "مرحباً. اسمي ___. أنا من ___. أنا طالب / طالبة. لدي ___. سعيد بلقائك.", purpose: "Choose this only when it feels useful, not because longer is always better." },
      ],
    },
    {
      id: "a1-m1-l14-learner-review",
      kind: "review",
      title: "Choose one thing to make clearer",
      titleArabic: "اختر شيئاً واحداً لتجعله أوضح",
      objective: "Reflect on clarity, pacing, or one needed word without grading the learner’s accent or demanding a perfect recording.",
      objectiveArabic: "تأمل في الوضوح أو الإيقاع أو كلمة تحتاجها من دون تقييم لهجة المتعلم أو طلب تسجيل مثالي.",
      stage: "review",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["tip"],
      writingPrompt: "Choose one: I can say my name clearly. / I can pause after a sentence. / I need one word from the word bank. Practise only that one thing once more.",
      writingPromptArabic: "اختر واحداً: أستطيع قول اسمي بوضوح. / أستطيع التوقف بعد جملة. / أحتاج كلمة واحدة من بنك الكلمات. تدرب على هذا الشيء فقط مرة أخرى.",
    },
  ],
  15: [
    {
      id: "a1-m1-l15-kind-assessment-intro",
      kind: "assessment",
      title: "Show the language you have practised",
      titleArabic: "أظهر اللغة التي تدربت عليها",
      objective: "Understand that the module check is a supported chance to show useful language, not a surprise trick or a test of accent.",
      objectiveArabic: "افهم أن تقييم الوحدة فرصة مدعومة لإظهار لغة مفيدة، وليس خدعة مفاجئة أو اختباراً للّكنة.",
      stage: "introduction",
      estimatedMinutes: 4,
      semantic: "assessment",
      progressiveSupports: ["arabic-help", "tip"],
      writingPrompt: "Today you will read, choose, write, and speak a little. A mistake tells you what to review next; it does not erase what you can already do.",
      writingPromptArabic: "اليوم ستقرأ وتختار وتكتب وتتحدث قليلاً. يخبرك الخطأ بما تراجعه لاحقاً؛ ولا يمحو ما تستطيع فعله بالفعل.",
    },
    {
      id: "a1-m1-l15-profile-reading",
      kind: "reading",
      title: "Read a new learner profile",
      titleArabic: "اقرأ تعريف متعلم جديد",
      objective: "Find who, where, age, and role in a short new profile using the same reading strategies practised in the module.",
      objectiveArabic: "اعثر على من وأين والعمر والدور في تعريف جديد قصير باستخدام استراتيجيات القراءة التي تدربت عليها في الوحدة.",
      stage: "guided-practice",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["transcript", "word-support", "worked-example"],
      writingPrompt: "Read: Hello. My name is Karim. I am twenty years old. I am from Amman. I am a student. My sister is a teacher. Answer: What is his name? Where is he from? Who is a teacher?",
      writingPromptArabic: "اقرأ: Hello. My name is Karim. I am twenty years old. I am from Amman. I am a student. My sister is a teacher. أجب: ما اسمه؟ من أين هو؟ من هو المعلّم؟",
    },
    {
      id: "a1-m1-l15-profile-writing",
      kind: "writing",
      title: "Write a five-line first-meeting profile",
      titleArabic: "اكتب تعريفاً من خمسة أسطر للقاء أول",
      objective: "Create a short supported introduction using a choice of safe real or fictional information and at least six module words.",
      objectiveArabic: "أنشئ تعريفاً قصيراً مدعوماً باستخدام معلومات حقيقية أو خيالية آمنة وباستخدام ست كلمات من الوحدة على الأقل.",
      stage: "independent-practice",
      estimatedMinutes: 12,
      semantic: "activity",
      progressiveSupports: ["worked-example", "word-support", "external-ai-prompt", "tip"],
      writingPrompt: "Write five small lines. You may use: Hello. / My name is ___. / I am from ___. / I am ___ years old. / I am a ___. / I have a ___. / Nice to meet you. Use real or invented details.",
      writingPromptArabic: "اكتب خمسة أسطر قصيرة. يمكنك استخدام: Hello. / My name is ___. / I am from ___. / I am ___ years old. / I am a ___. / I have a ___. / Nice to meet you. استخدم تفاصيل حقيقية أو خيالية.",
      suggestedVocabulary: ["hello", "name", "from", "years old", "student", "family", "teacher", "friend"],
    },
    {
      id: "a1-m1-l15-speaking-showcase",
      kind: "speaking",
      title: "Say a first-meeting version",
      titleArabic: "قل نسخة من لقاء أول",
      objective: "Use the written profile to give a short, understandable introduction and answer one or two meaning-focused follow-up questions.",
      objectiveArabic: "استخدم التعريف المكتوب لتقديم مقدمة قصيرة مفهومة والإجابة عن سؤال أو سؤالين متابعين يركزان على المعنى.",
      stage: "real-context",
      estimatedMinutes: 8,
      semantic: "activity",
      progressiveSupports: ["transcript", "word-support", "tip"],
      speakingLines: [
        { id: "a1-m1-l15-say-1", speaker: "Learner", text: "Hello. My name is ___. I am from ___.", textArabic: "مرحباً. اسمي ___. أنا من ___.", pronunciationHint: "Pause after each complete thought; clear words are the goal.", audioText: "Hello. My name is ___. I am from ___." },
        { id: "a1-m1-l15-say-2", speaker: "Partner", text: "What is your name? Where are you from?", textArabic: "ما اسمك؟ من أين أنت؟", pronunciationHint: "Answer one question at a time.", audioText: "What is your name? Where are you from?" },
      ],
    },
    {
      id: "a1-m1-l15-next-review-decision",
      kind: "review",
      title: "Choose your next review target",
      titleArabic: "اختر هدف المراجعة التالي",
      objective: "Turn each missed word or pattern into one specific next review choice instead of blocking progress without guidance.",
      objectiveArabic: "حوّل كل كلمة أو نمط لم يثبت بعد إلى خيار مراجعة محدد تالٍ بدلاً من إيقاف التقدم من دون توجيه.",
      stage: "assessment",
      estimatedMinutes: 4,
      semantic: "retrieval",
      progressiveSupports: ["word-support", "tip"],
      writingPrompt: "Choose one next step: review greeting words / practise I am and you are / read the profile again / say one question word. One target is enough for a useful next session.",
      writingPromptArabic: "اختر خطوة تالية واحدة: راجع كلمات التحية / تدرب على I am وyou are / اقرأ التعريف مرة أخرى / قل كلمة سؤال واحدة. هدف واحد يكفي لجلسة تالية مفيدة.",
    },
  ],
};

/**
 * Module 1 is the live authoring pilot. Later A1 modules continue to use the
 * existing generator until their own authoring waves provide equally explicit
 * activity evidence.
 */
export function authoredActivitiesForA1Module1(lessonNumber: number): LessonActivity[] | undefined {
  return authoredActivities[lessonNumber];
}
