import type { LessonActivity, VisualVocabularyItem } from "./types";

function memoryScene(label: string, colour: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 180" role="img" aria-label="${label}"><rect width="320" height="180" fill="${colour}"/><rect x="42" y="28" width="236" height="122" rx="18" fill="#fffdf7"/><circle cx="112" cy="80" r="25" fill="#f7c7a7"/><path d="M88 124c12-27 37-27 49 0" fill="#52708d"/><path d="M165 65h74M165 91h52M165 117h64" stroke="#253453" stroke-width="8" stroke-linecap="round"/><text x="160" y="170" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" font-weight="700" fill="#253453">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const storyVisuals: VisualVocabularyItem[] = [
  { id: "a2-m4-first", word: "first", arabic: "أولاً", pronunciation: "/fɜːst/", exampleEN: "First, we arrived at the park.", exampleAR: "أولاً، وصلنا إلى الحديقة.", altText: "A simple story card labelled First", category: "Story sequence", interactionHint: "Say first, then name the opening event.", imageUrl: memoryScene("First", "#e3eefb") },
  { id: "a2-m4-suddenly", word: "suddenly", arabic: "فجأة", pronunciation: "/ˈsʌd.ən.li/", exampleEN: "Suddenly, the lights went out.", exampleAR: "فجأة، انطفأت الأضواء.", altText: "A simple story card showing an unexpected change", category: "Story sequence", interactionHint: "Use suddenly for an event that changes the story quickly.", imageUrl: memoryScene("Suddenly", "#fff0d8") },
  { id: "a2-m4-finally", word: "finally", arabic: "أخيراً", pronunciation: "/ˈfaɪ.nəl.i/", exampleEN: "Finally, we found the bus stop.", exampleAR: "أخيراً، وجدنا موقف الحافلات.", altText: "A simple story card labelled Finally", category: "Story sequence", interactionHint: "Use finally to close a sequence.", imageUrl: memoryScene("Finally", "#e7f4e8") },
];

export const A2_MODULE_4_AUTHORED_ACTIVITIES: Record<number, LessonActivity[]> = {
  46: [{ id: "a2-m4-l46-memory-lines", kind: "standard", title: "Build a memorable-day timeline", titleArabic: "ابنِ خطاً زمنياً ليوم لا يُنسى", objective: "Use past simple affirmative and negative forms to place three fictional events on one timeline.", objectiveArabic: "استخدم إثبات ونفي الماضي البسيط لوضع ثلاثة أحداث خيالية على خط زمني واحد.", stage: "explanation", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Complete: Yesterday, I ___ (visit) my aunt, but I ___ (not stay) late.", writingPromptArabic: "أكمل: Yesterday, I ___ (visit) my aunt, but I ___ (not stay) late.", sentencePatterns: ["I ___ yesterday.", "I did not ___."] }],
  47: [{ id: "a2-m4-l47-scene-reading", kind: "reading", title: "Read the opening scene", titleArabic: "اقرأ بداية المشهد", objective: "Find where the story happened and which adjectives set the scene.", objectiveArabic: "اعثر على مكان القصة والصفات التي تصف المشهد.", stage: "introduction", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "word-support", "tip"], readingText: "There was a small café beside the river. It was quiet and warm, and there were only two people inside. Outside, the street was wet after the rain.", readingTextArabic: "كان هناك مقهى صغير بجانب النهر. كان هادئاً ودافئاً، وكان هناك شخصان فقط في الداخل. في الخارج، كان الشارع مبللاً بعد المطر.", readingChecks: [{ id: "a2-m4-l47-place", type: "detail", prompt: "Where was the café?", promptArabic: "أين كان المقهى؟", choices: ["Beside the river", "Inside a station", "Near a school"], answer: "Beside the river", explanation: "The first sentence gives the location." }, { id: "a2-m4-l47-scene", type: "main-idea", prompt: "Which words describe the café?", promptArabic: "أي كلمات تصف المقهى؟", choices: ["Quiet and warm", "Busy and noisy", "Cold and dark"], answer: "Quiet and warm", explanation: "These adjectives create the opening scene." }] }],
  48: [{ id: "a2-m4-l48-while-question", kind: "standard", title: "Ask about the moment", titleArabic: "اسأل عن اللحظة", objective: "Form and answer one past continuous question about an action in progress.", objectiveArabic: "كوّن وأجب عن سؤال واحد في الماضي المستمر عن فعل كان جارياً.", stage: "guided-practice", estimatedMinutes: 7, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Put the words in order: you / what / doing / were / at 7? Then answer with one true or fictional idea.", writingPromptArabic: "رتّب الكلمات: you / what / doing / were / at 7? ثم أجب بفكرة حقيقية أو خيالية واحدة.", sentencePatterns: ["What were you doing at ___?", "I was ___."] }],
  49: [{ id: "a2-m4-l49-story-cards", kind: "visual-vocabulary", title: "Order a picture story", titleArabic: "رتّب قصة بالصور", objective: "Use first, suddenly, and finally to give three picture moments a clear sequence.", objectiveArabic: "استخدم first وsuddenly وfinally لإعطاء ثلاث لحظات مصورة ترتيباً واضحاً.", stage: "introduction", estimatedMinutes: 8, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support", "tip"], visualItems: storyVisuals }],
  50: [{ id: "a2-m4-l50-surprise-turns", kind: "interaction", title: "Follow an unexpected moment", titleArabic: "تابع لحظة غير متوقعة", objective: "Connect a background action to a surprise using when or while.", objectiveArabic: "اربط فعلاً في الخلفية بمفاجأة باستخدام when أو while.", stage: "real-context", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m4-l50-a", speaker: "Rami", text: "I was walking home when I saw a small dog alone near the road.", textArabic: "كنت أمشي إلى المنزل عندما رأيت كلباً صغيراً وحده قرب الطريق.", purpose: "Set a background action and a sudden event." }, { id: "a2-m4-l50-b", speaker: "Nour", text: "What did you do while you were waiting for its owner?", textArabic: "ماذا فعلت بينما كنت تنتظر صاحبه؟", purpose: "Ask about an action in progress." }, { id: "a2-m4-l50-c", speaker: "Rami", text: "I called a local shelter and stayed with the dog.", textArabic: "اتصلت بمأوى محلي وبقيت مع الكلب.", purpose: "Give a calm past-simple response." }] }],
  51: [{ id: "a2-m4-l51-feeling-lines", kind: "speaking", title: "Say how the moment felt", titleArabic: "قل كيف شعرت اللحظة", objective: "Contrast one -ed feeling adjective with one -ing description in a short spoken response.", objectiveArabic: "قارن صفة شعور منتهية بـ -ed مع وصف منتهٍ بـ -ing في استجابة منطوقة قصيرة.", stage: "guided-practice", estimatedMinutes: 6, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "tip"], speakingLines: [{ id: "a2-m4-l51-one", speaker: "Model", text: "I was excited because the trip was exciting.", textArabic: "كنت متحمساً لأن الرحلة كانت مثيرة.", pronunciationHint: "Stress excited and exciting differently; pause before because.", audioText: "I was excited because the trip was exciting." }, { id: "a2-m4-l51-two", speaker: "Model", text: "She felt worried because the film was frightening.", textArabic: "شعرت بالقلق لأن الفيلم كان مخيفاً.", pronunciationHint: "The person feels worried; the film is frightening.", audioText: "She felt worried because the film was frightening." }] }],
  52: [{ id: "a2-m4-l52-kindness-reading", kind: "reading", title: "Read a small act of kindness", titleArabic: "اقرأ موقفاً صغيراً من اللطف", objective: "Track who each pronoun refers to and connect the reason to the helpful action.", objectiveArabic: "تتبّع مرجع كل ضمير واربط السبب بالفعل المساعد.", stage: "introduction", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "word-support", "worked-example"], readingText: "Maha saw an older woman carrying two heavy bags. She offered to help because the woman looked tired. They walked to the bus stop together, and the woman thanked her warmly.", readingTextArabic: "رأت مها امرأة أكبر سناً تحمل حقيبتين ثقيلتين. عرضت المساعدة لأن المرأة بدت متعبة. مشتا معاً إلى موقف الحافلات، وشكرتها المرأة بحرارة.", readingChecks: [{ id: "a2-m4-l52-she", type: "detail", prompt: "Who does She refer to in the second sentence?", promptArabic: "إلى من يعود الضمير She في الجملة الثانية؟", choices: ["Maha", "The older woman", "The bus stop"], answer: "Maha", explanation: "Maha is the person who offered help." }, { id: "a2-m4-l52-why", type: "inference", prompt: "Why did Maha offer help?", promptArabic: "لماذا عرضت مها المساعدة؟", choices: ["The woman looked tired", "She missed a bus", "She wanted new bags"], answer: "The woman looked tired", explanation: "The reason is stated after because." }] }],
  53: [{ id: "a2-m4-l53-past-endings", kind: "speaking", title: "Hear regular past endings", titleArabic: "اسمع نهايات الماضي المنتظم", objective: "Say regular past forms clearly in three short story chunks.", objectiveArabic: "قل صيغ الماضي المنتظم بوضوح في ثلاث عبارات قصصية قصيرة.", stage: "guided-practice", estimatedMinutes: 6, semantic: "activity", progressiveSupports: ["transcript", "tip"], speakingLines: [{ id: "a2-m4-l53-one", speaker: "Model", text: "I walked to the shop and asked for help.", textArabic: "مشيت إلى المتجر وطلبت المساعدة.", pronunciationHint: "Keep walked short; let asked finish clearly without adding an extra syllable.", audioText: "I walked to the shop and asked for help." }, { id: "a2-m4-l53-two", speaker: "Model", text: "She waited and decided to call her friend.", textArabic: "انتظرت وقررت الاتصال بصديقتها.", pronunciationHint: "Say waited and decided with an extra /ɪd/ sound.", audioText: "She waited and decided to call her friend." }] }],
  54: [{ id: "a2-m4-l54-childhood-note", kind: "writing", title: "Write one childhood memory", titleArabic: "اكتب ذكرى واحدة من الطفولة", objective: "Use used to in a short fictional or low-detail childhood-memory paragraph.", objectiveArabic: "استخدم used to في فقرة قصيرة خيالية أو قليلة التفاصيل عن ذكرى من الطفولة.", stage: "assessment", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "word-support"], writingPrompt: "Write 3–4 sentences about a fictional childhood habit. Include one thing the person used to do and one thing they did not use to do. Do not use private names or locations.", writingPromptArabic: "اكتب 3–4 جمل عن عادة خيالية في الطفولة. ضع شيئاً كان الشخص يفعله وشيئاً لم يكن يفعله. لا تستخدم أسماء أو أماكن خاصة.", sentencePatterns: ["When I was younger, I used to ___.", "I did not use to ___."] }],
  55: [{ id: "a2-m4-l55-before-after", kind: "standard", title: "Notice the earlier event", titleArabic: "لاحظ الحدث الأسبق", objective: "Identify which of two past events happened first using before, after, and already.", objectiveArabic: "حدّد أي حدثين في الماضي وقع أولاً باستخدام before وafter وalready.", stage: "explanation", estimatedMinutes: 7, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Choose the earlier event: 'The film started after we had found our seats.' What happened first?", writingPromptArabic: "اختر الحدث الأسبق: 'The film started after we had found our seats.' ما الذي حدث أولاً؟", sentencePatterns: ["Before ___, ___.", "After ___, ___."] }],
  56: [{ id: "a2-m4-l56-yesterday-message", kind: "interaction", title: "Send a friendly yesterday message", titleArabic: "أرسل رسالة ودّية عن الأمس", objective: "Use an informal opening, a contraction, and simple punctuation in a short message about yesterday.", objectiveArabic: "استخدم بداية غير رسمية واختصاراً وترقيماً بسيطاً في رسالة قصيرة عن الأمس.", stage: "real-context", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "tip"], interactionTurns: [{ id: "a2-m4-l56-a", speaker: "Ali", text: "Hi Sara, I’m sorry I missed the walk yesterday. I was helping my neighbour.", textArabic: "مرحباً سارة، آسف لأنني فاتتني النزهة أمس. كنت أساعد جارتي.", purpose: "Open informally and explain the absence." }, { id: "a2-m4-l56-b", speaker: "Sara", text: "No problem! We had a nice time. Let’s go next week.", textArabic: "لا مشكلة! قضينا وقتاً لطيفاً. لنذهب الأسبوع القادم.", purpose: "Respond warmly with a future suggestion." }] }],
  57: [{ id: "a2-m4-l57-story-sort", kind: "review", title: "Sort a story toolkit", titleArabic: "رتّب أدوات القصة", objective: "Retrieve a tense, a sequence word, a feeling word, and a cohesion choice for one small story.", objectiveArabic: "استرجع زمناً وكلمة ترتيب وكلمة شعور وخيار ترابط لقصة صغيرة واحدة.", stage: "review", estimatedMinutes: 8, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], writingPrompt: "Put each item in the best place: yesterday / while / excited / because. Then use two items in one short story sentence.", writingPromptArabic: "ضع كل عنصر في أفضل مكان: yesterday / while / excited / because. ثم استخدم عنصرين في جملة قصة قصيرة." }],
  58: [{ id: "a2-m4-l58-connected-memory", kind: "writing", title: "Write a connected memory", titleArabic: "اكتب ذكرى مترابطة", objective: "Draft a safe, connected four-sentence memory with a topic, details, and a final reflection.", objectiveArabic: "اكتب مسودة ذكرى آمنة مترابطة من أربع جمل مع موضوع وتفاصيل وتأمل أخير.", stage: "assessment", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "word-support"], writingPrompt: "Write about a fictional memorable afternoon: opening, one event, one feeling, and one final reflection. Keep people and places invented.", writingPromptArabic: "اكتب عن ظهيرة خيالية لا تُنسى: بداية وحدث واحد وشعور واحد وتأمل أخير. اجعل الأشخاص والأماكن خيالية.", sentencePatterns: ["One afternoon, ___.", "I felt ___ because ___.", "I still remember it because ___."] }],
  59: [{ id: "a2-m4-l59-retell", kind: "speaking", title: "Retell and improve", titleArabic: "أعد السرد وحسّن", objective: "Retell a three-event story and replace one repeated word with a clearer choice.", objectiveArabic: "أعد سرد قصة من ثلاثة أحداث واستبدل كلمة مكررة واحدة باختيار أوضح.", stage: "real-context", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["transcript", "worked-example", "tip"], speakingLines: [{ id: "a2-m4-l59-one", speaker: "Model", text: "First, I missed the bus. Then I asked a neighbour for help. Finally, I arrived on time.", textArabic: "أولاً، فاتتني الحافلة. ثم طلبت المساعدة من جار. أخيراً، وصلت في الوقت.", pronunciationHint: "Pause after each sequence word and keep the three events distinct.", audioText: "First, I missed the bus. Then I asked a neighbour for help. Finally, I arrived on time." }] }],
  60: [{ id: "a2-m4-l60-story-checkpoint", kind: "assessment", title: "Stories and memories checkpoint", titleArabic: "اختبار القصص والذكريات", objective: "Show connected control of past events, reaction language, and a short reflective memory.", objectiveArabic: "أظهر تحكماً مترابطاً في أحداث الماضي ولغة رد الفعل وذكرى قصيرة تأملية.", stage: "assessment", estimatedMinutes: 12, semantic: "assessment", progressiveSupports: ["arabic-help", "worked-example", "tip"], writingPrompt: "Choose a fictional prompt: a surprising journey, a helpful stranger, or a childhood habit. Write 4–5 sentences with a sequence word, one past action, one feeling, and a final reflection.", writingPromptArabic: "اختر موضوعاً خيالياً: رحلة مفاجئة أو شخص مساعد أو عادة طفولة. اكتب 4–5 جمل فيها كلمة ترتيب وفعل ماضٍ وشعور وتأمل أخير.", suggestedVocabulary: ["first", "suddenly", "while", "excited", "finally", "remember"] }],
};
