import type {
  LessonActivity,
  LessonExperienceStage,
  LessonProgressionStage,
  ProgressiveSupport,
  VisualVocabularyItem,
} from "./types";

type ActivityDraft = Omit<LessonActivity, "stage"> & {
  stage: LessonProgressionStage | LessonExperienceStage;
  progressiveSupports?: ProgressiveSupport[];
};

const stageMap: Record<LessonExperienceStage, LessonProgressionStage> = {
  orientation: "introduction",
  encounter: "introduction",
  notice: "explanation",
  "supported-practice": "guided-practice",
  "meaningful-use": "real-context",
  retrieval: "review",
  evidence: "assessment",
  "next-bridge": "review",
};

function activity(draft: ActivityDraft): LessonActivity {
  return {
    ...draft,
    stage: draft.stage in stageMap
      ? stageMap[draft.stage as LessonExperienceStage]
      : draft.stage as LessonProgressionStage,
  };
}

function scene(label: string, colour: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 180" role="img" aria-label="${label}"><rect width="320" height="180" fill="${colour}"/><rect x="91" y="28" width="138" height="112" rx="12" fill="#fffdf7"/><path d="M118 64h84M118 87h62M118 110h76" stroke="#253453" stroke-width="8" stroke-linecap="round"/><text x="160" y="165" text-anchor="middle" font-family="Arial, sans-serif" font-size="17" font-weight="700" fill="#253453">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const skillVisuals: VisualVocabularyItem[] = [
  { id: "a2-m2-skill", word: "skill", arabic: "مهارة", pronunciation: "/skɪl/", exampleEN: "Listening is an important skill at work.", exampleAR: "الاستماع مهارة مهمة في العمل.", altText: "A simple skill card with a checklist", category: "Learning and work", interactionHint: "Say skill once, then name a skill you can practise.", imageUrl: scene("Skill", "#e4edf8") },
  { id: "a2-m2-practice", word: "practise", arabic: "يتدرّب", pronunciation: "/ˈpræktɪs/", exampleEN: "I practise English for fifteen minutes.", exampleAR: "أتدرّب على الإنجليزية لمدة خمس عشرة دقيقة.", altText: "A practice card with three calm checkmarks", category: "Learning and work", interactionHint: "The verb ends in -ise in British English: practise.", imageUrl: scene("Practise", "#e7f4e8") },
  { id: "a2-m2-goal", word: "goal", arabic: "هدف", pronunciation: "/ɡəʊl/", exampleEN: "Her goal is to write a clear email.", exampleAR: "هدفها هو كتابة رسالة بريد إلكتروني واضحة.", altText: "A goal card with a target-like circle", category: "Learning and work", interactionHint: "Connect goal with one small next step, not a perfect result.", imageUrl: scene("Goal", "#fff0d7") },
];

export const A2_MODULE_2_AUTHORED_ACTIVITIES: Record<number, LessonActivity[]> = {
  16: [
    activity({ id: "a2-m2-l16-now-or-usually", kind: "standard", title: "Sort now and usually", titleArabic: "صنّف الآن وعادةً", objective: "Notice the difference between a repeated learning routine and an action happening now.", objectiveArabic: "لاحظ الفرق بين روتين تعلم متكرر وفعل يحدث الآن.", stage: "orientation", estimatedMinutes: 7, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Place each sentence on a card: 'Omar studies after dinner.' / 'Omar is studying for a test now.' Then add one word: usually or now.", writingPromptArabic: "ضع كل جملة على بطاقة: 'Omar studies after dinner.' / 'Omar is studying for a test now.' ثم أضف كلمة واحدة: usually أو now.", sentencePatterns: ["I usually ___.", "I am ___ing now."] }),
    activity({ id: "a2-m2-l16-a1-time-bridge", kind: "review", title: "Carry forward an A1 time phrase", titleArabic: "انقل عبارة وقت من A1", objective: "Reuse a familiar A1 time phrase so the new contrast has a meaningful anchor.", objectiveArabic: "أعد استخدام عبارة وقت مألوفة من A1 ليكون للتباين الجديد مرساة ذات معنى.", stage: "retrieval", estimatedMinutes: 4, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], writingPrompt: "Complete one true or fictional line: In the morning, I usually ___. Right now, I am ___.", writingPromptArabic: "أكمل سطراً حقيقياً أو خيالياً: In the morning, I usually ___. Right now, I am ___.", sentencePatterns: ["In the morning, I usually ___.", "Right now, I am ___."] }),
  ],
  17: [
    activity({ id: "a2-m2-l17-skill-cards", kind: "visual-vocabulary", title: "Choose three useful skill cards", titleArabic: "اختر ثلاث بطاقات مهارات مفيدة", objective: "Meet skill, practise, and goal through visual cards before using can and be good at in a learning context.", objectiveArabic: "تعرّف إلى skill وpractise وgoal عبر بطاقات بصرية قبل استخدام can وbe good at في سياق تعلم.", stage: "encounter", estimatedMinutes: 8, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support", "tip"], visualItems: skillVisuals }),
    activity({ id: "a2-m2-l17-ability-profile", kind: "writing", title: "Build a fictional skill profile", titleArabic: "ابنِ ملف مهارات خيالي", objective: "Describe what a fictional learner can do and what they are becoming better at without requiring personal disclosure.", objectiveArabic: "صِف ما يستطيع متعلم خيالي فعله وما يتحسن فيه دون طلب كشف شخصي.", stage: "meaningful-use", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"], writingPrompt: "Choose a character: Lina / Samir. Write two lines: 'She can ___.' and 'She is good at ___.'", writingPromptArabic: "اختر شخصية: Lina / Samir. اكتب سطرين: 'She can ___.' و'She is good at ___.'", suggestedVocabulary: ["skill", "practise", "English", "organise", "explain"], sentencePatterns: ["She can ___.", "She is good at ___."] }),
  ],
  18: [
    activity({ id: "a2-m2-l18-workday-reading", kind: "reading", title: "Read a busy workday diary", titleArabic: "اقرأ يوميات يوم عمل مزدحم", objective: "Follow when and while in a short diary without turning the reading into a tense worksheet.", objectiveArabic: "اتبع when وwhile في يوميات قصيرة دون تحويل القراءة إلى ورقة عمل أزمنة.", stage: "encounter", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "word-support"], readingText: "When Faris arrived at work, his team was discussing a new task. While they were talking, the manager sent a short message. Faris wrote the main points down, then he helped a colleague after lunch.", readingTextArabic: "عندما وصل فارس إلى العمل، كان فريقه يناقش مهمة جديدة. وبينما كانوا يتحدثون، أرسل المدير رسالة قصيرة. دوّن فارس النقاط الرئيسة، ثم ساعد زميلاً بعد الغداء.", readingChecks: [{ id: "a2-m2-l18-main", type: "main-idea", prompt: "What is the diary mainly about?", promptArabic: "ما الفكرة الرئيسة في اليوميات؟", choices: ["A busy day with connected events", "A holiday at home", "A job interview"], answer: "A busy day with connected events", explanation: "The diary follows work events in order." }, { id: "a2-m2-l18-detail", type: "detail", prompt: "What happened while the team was talking?", promptArabic: "ماذا حدث بينما كان الفريق يتحدث؟", choices: ["The manager sent a message", "Faris went home", "Lunch started"], answer: "The manager sent a message", explanation: "This detail follows while in the second sentence." }] }),
  ],
  19: [
    activity({ id: "a2-m2-l19-rules-dialogue", kind: "interaction", title: "Clarify the team rules", titleArabic: "وضّح قواعد الفريق", objective: "Distinguish have to, do not have to, and must in a friendly first-day conversation.", objectiveArabic: "ميّز بين have to وdo not have to وmust في محادثة ودية عن أول يوم.", stage: "orientation", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m2-l19-a", speaker: "Maya", text: "Do I have to arrive at eight?", textArabic: "هل يجب أن أصل في الثامنة؟", purpose: "Ask about a regular responsibility." }, { id: "a2-m2-l19-b", speaker: "Colleague", text: "You have to be ready by eight, but you do not have to wear a uniform.", textArabic: "يجب أن تكون مستعداً بحلول الثامنة، لكن لا يجب أن ترتدي زياً موحداً.", purpose: "Separate a requirement from something optional." }, { id: "a2-m2-l19-c", speaker: "Colleague", text: "You must keep customer information private.", textArabic: "يجب أن تحافظ على خصوصية معلومات العملاء.", purpose: "Identify an important firm rule." }] }),
    activity({ id: "a2-m2-l19-rule-signs", kind: "standard", title: "Read three rule signs", titleArabic: "اقرأ ثلاث لافتات قواعد", objective: "Choose the strongest useful obligation word for each short workplace sign.", objectiveArabic: "اختر كلمة الالتزام الأنسب والأقوى لكل لافتة عمل قصيرة.", stage: "notice", estimatedMinutes: 5, semantic: "grammar", progressiveSupports: ["worked-example", "arabic-help"], writingPrompt: "Complete: You ___ wear an ID card. / You ___ bring lunch; there is a café. / You ___ share passwords.", writingPromptArabic: "أكمل: You ___ wear an ID card. / You ___ bring lunch; there is a café. / You ___ share passwords.", sentencePatterns: ["You have to ___.", "You do not have to ___.", "You must not ___."] }),
  ],
  20: [
    activity({ id: "a2-m2-l20-plan-ladder", kind: "writing", title: "Make a small study plan", titleArabic: "ضع خطة دراسة صغيرة", objective: "Use be going to for two realistic intentions and a manageable next step.", objectiveArabic: "استخدم be going to لنِيّتين واقعيتين وخطوة تالية قابلة للإدارة.", stage: "orientation", estimatedMinutes: 8, semantic: "objective", progressiveSupports: ["arabic-help", "worked-example", "word-support"], writingPrompt: "A fictional learner has a goal: speak more clearly. Write: 'This week, I am going to ___. On Friday, I am going to ___." , writingPromptArabic: "لدى متعلم خيالي هدف: التحدث بوضوح أكبر. اكتب: 'This week, I am going to ___. On Friday, I am going to ___.'", suggestedVocabulary: ["practise", "listen", "review", "goal", "Friday"], sentencePatterns: ["This week, I am going to ___.", "On Friday, I am going to ___."] }),
    activity({ id: "a2-m2-l20-plan-check", kind: "speaking", title: "Say the plan with calm rhythm", titleArabic: "قل الخطة بإيقاع هادئ", objective: "Practise be going to as one connected chunk, not word by word.", objectiveArabic: "تدرّب على be going to كوحدة مترابطة لا كلمة كلمة.", stage: "supported-practice", estimatedMinutes: 4, semantic: "activity", progressiveSupports: ["transcript", "tip"], speakingLines: [{ id: "a2-m2-l20-line", speaker: "Model", text: "I am going to practise for ten minutes after dinner.", textArabic: "سأتدرّب عشر دقائق بعد العشاء.", pronunciationHint: "Let going to flow together; stress practise and ten minutes.", audioText: "I am going to practise for ten minutes after dinner." }] }),
  ],
  21: [
    activity({ id: "a2-m2-l21-helpful-colleague", kind: "interaction", title: "Offer help without pressure", titleArabic: "اعرض المساعدة دون ضغط", objective: "Use object pronouns and a polite offer in a short colleague exchange.", objectiveArabic: "استخدم ضمائر المفعول وعرضاً مهذباً في تبادل قصير بين زملاء.", stage: "encounter", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m2-l21-a", speaker: "Hadi", text: "I cannot find the meeting link.", textArabic: "لا أستطيع العثور على رابط الاجتماع.", purpose: "State a simple problem." }, { id: "a2-m2-l21-b", speaker: "Rana", text: "I can send it to you. Would you like me to show you where it is?", textArabic: "يمكنني إرساله إليك. هل تريد أن أريك أين هو؟", purpose: "Offer help with it and you accurately." }, { id: "a2-m2-l21-c", speaker: "Hadi", text: "Yes, please. That would help me.", textArabic: "نعم، من فضلك. هذا سيساعدني.", purpose: "Accept help politely." }] }),
  ],
  22: [
    activity({ id: "a2-m2-l22-week-wins", kind: "standard", title: "Notice this week's results", titleArabic: "لاحظ نتائج هذا الأسبوع", objective: "Use present perfect for a recent result that matters now, with already as a useful clue.", objectiveArabic: "استخدم المضارع التام لنتيجة حديثة تهم الآن مع already كدليل مفيد.", stage: "notice", estimatedMinutes: 7, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "extended-rationale"], writingPrompt: "Compare the cards: 'I finished the report yesterday.' / 'I have finished the report already.' Which one connects the result to now? Then complete: We have ___ the first task.", writingPromptArabic: "قارن البطاقتين: 'I finished the report yesterday.' / 'I have finished the report already.' أيهما يربط النتيجة بالآن؟ ثم أكمل: We have ___ the first task.", sentencePatterns: ["I have finished ___.", "We have already ___."] }),
    activity({ id: "a2-m2-l22-progress-update", kind: "speaking", title: "Give a two-line progress update", titleArabic: "قدّم تحديث تقدم من سطرين", objective: "Say a short update that combines one completed action and one next step.", objectiveArabic: "قل تحديثاً قصيراً يجمع فعلاً مكتملاً وخطوة تالية.", stage: "meaningful-use", estimatedMinutes: 5, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], speakingLines: [{ id: "a2-m2-l22-model", speaker: "Model", text: "I have finished the first exercise. Next, I am going to check my answers.", textArabic: "أنهيت التمرين الأول. بعد ذلك، سأراجع إجاباتي.", pronunciationHint: "Pause after exercise, then make next clear.", audioText: "I have finished the first exercise. Next, I am going to check my answers." }] }),
  ],
  23: [
    activity({ id: "a2-m2-l23-profile-reading", kind: "reading", title: "Read a short experience profile", titleArabic: "اقرأ ملف خبرة قصيراً", objective: "Find ever, never, and before in a realistic learner profile and understand what each asks about experience.", objectiveArabic: "اعثر على ever وnever وbefore في ملف متعلم واقعي وافهم ما الذي يسأل عنه كل منها في الخبرة.", stage: "encounter", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "word-support"], readingText: "Noura has worked in a small shop before. She has never managed a large team, but she has already helped new colleagues. Have you ever taught someone a new task? Noura enjoys learning from other people.", readingTextArabic: "عملت نورة في متجر صغير من قبل. لم تدِر فريقاً كبيراً أبداً، لكنها ساعدت زملاء جدداً بالفعل. هل سبق أن علمت شخصاً مهمة جديدة؟ تستمتع نورة بالتعلم من الآخرين.", readingChecks: [{ id: "a2-m2-l23-detail", type: "detail", prompt: "What has Noura never done?", promptArabic: "ما الذي لم تفعله نورة أبداً؟", choices: ["Managed a large team", "Worked in a shop", "Helped new colleagues"], answer: "Managed a large team", explanation: "Never directly describes managing a large team." }, { id: "a2-m2-l23-vocab", type: "vocabulary", prompt: "What does before mean here?", promptArabic: "ماذا تعني before هنا؟", choices: ["At an earlier time", "Every morning", "In the future"], answer: "At an earlier time", explanation: "It refers to Noura's earlier shop experience." }] }),
  ],
  24: [
    activity({ id: "a2-m2-l24-learning-compare", kind: "standard", title: "Compare two study choices", titleArabic: "قارن بين خياري دراسة", objective: "Choose comparatives and as...as to compare learning choices fairly, without claiming that one method suits everyone.", objectiveArabic: "اختر صيغ المقارنة وas...as لمقارنة خيارات التعلم بعدل دون الادعاء أن طريقة واحدة تناسب الجميع.", stage: "supported-practice", estimatedMinutes: 7, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "tip"], writingPrompt: "Complete the comparison cards: A short video is ___ than a long lecture for this task. Reading is not as ___ as listening for Ali today.", writingPromptArabic: "أكمل بطاقات المقارنة: A short video is ___ than a long lecture for this task. Reading is not as ___ as listening for Ali today.", sentencePatterns: ["___ is more useful than ___.", "___ is not as useful as ___."] }),
  ],
  25: [
    activity({ id: "a2-m2-l25-feedback-rehearsal", kind: "speaking", title: "Ask for feedback politely", titleArabic: "اطلب ملاحظات بأدب", objective: "Rehearse an indirect question that makes a request for feedback sound respectful and clear.", objectiveArabic: "تدرّب على سؤال غير مباشر يجعل طلب الملاحظات محترماً وواضحاً.", stage: "supported-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], speakingLines: [{ id: "a2-m2-l25-model", speaker: "Model", text: "Could you tell me how I can improve this paragraph?", textArabic: "هل يمكنك أن تخبرني كيف يمكنني تحسين هذه الفقرة؟", pronunciationHint: "Keep Could you tell me as one polite opening.", audioText: "Could you tell me how I can improve this paragraph?" }, { id: "a2-m2-l25-option", speaker: "Option", text: "Could you tell me which part is clear?", textArabic: "هل يمكنك أن تخبرني أي جزء واضح؟", pronunciationHint: "Stress which part and clear.", audioText: "Could you tell me which part is clear?" }] }),
  ],
  26: [
    activity({ id: "a2-m2-l26-second-chance", kind: "reading", title: "Read a second-chance story", titleArabic: "اقرأ قصة فرصة ثانية", objective: "Notice how past simple tells an earlier event while present perfect connects experience to the present.", objectiveArabic: "لاحظ كيف يحكي الماضي البسيط حدثاً سابقاً بينما يربط المضارع التام الخبرة بالحاضر.", stage: "encounter", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "extended-rationale"], readingText: "Last year, Karim missed an interview because he arrived at the wrong address. Since then, he has checked every detail before leaving home. He has also practised answering questions with a friend. This month, he applied again and felt much calmer.", readingTextArabic: "في العام الماضي، فاتت كريم مقابلة لأنه وصل إلى عنوان خاطئ. ومنذ ذلك الحين، راجع كل تفصيل قبل مغادرة المنزل. كما تدرب على الإجابة عن الأسئلة مع صديق. هذا الشهر، تقدم مرة أخرى وشعر بهدوء أكبر.", readingChecks: [{ id: "a2-m2-l26-sequence", type: "detail", prompt: "What did Karim do after the earlier interview?", promptArabic: "ماذا فعل كريم بعد المقابلة السابقة؟", choices: ["He began checking details", "He stopped applying", "He changed his name"], answer: "He began checking details", explanation: "Since then introduces the change that continued after the earlier event." }, { id: "a2-m2-l26-inference", type: "inference", prompt: "Why did Karim feel calmer this month?", promptArabic: "لماذا شعر كريم بهدوء أكبر هذا الشهر؟", choices: ["He had prepared more carefully", "The interview was cancelled", "He did not have questions"], answer: "He had prepared more carefully", explanation: "The text links his checking and practice to his later confidence." }] }),
  ],
  27: [
    activity({ id: "a2-m2-l27-problem-solver", kind: "interaction", title: "Explain a small work problem", titleArabic: "اشرح مشكلة عمل صغيرة", objective: "Use because, so, and but to explain a practical problem and suggest a next step.", objectiveArabic: "استخدم because وso وbut لشرح مشكلة عملية واقتراح خطوة تالية.", stage: "meaningful-use", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "transcript"], interactionTurns: [{ id: "a2-m2-l27-a", speaker: "Nadia", text: "The printer is not working, so I cannot print the forms.", textArabic: "الطابعة لا تعمل، لذلك لا أستطيع طباعة الاستمارات.", purpose: "State a result clearly." }, { id: "a2-m2-l27-b", speaker: "Nadia", text: "I checked the paper, but the problem is still there.", textArabic: "تحققت من الورق، لكن المشكلة ما زالت موجودة.", purpose: "Add a contrast without blaming someone." }, { id: "a2-m2-l27-c", speaker: "Colleague", text: "I can call support because they can check the connection.", textArabic: "يمكنني الاتصال بالدعم لأنهم يستطيعون فحص الاتصال.", purpose: "Give a reason for a practical solution." }] }),
  ],
  28: [
    activity({ id: "a2-m2-l28-work-review-grid", kind: "review", title: "Build a learning-and-work grid", titleArabic: "ابنِ شبكة التعلم والعمل", objective: "Retrieve one example for ability, obligation, recent experience, comparison, and polite feedback from meaningful earlier lessons.", objectiveArabic: "استرجع مثالاً واحداً للقدرة والالتزام والخبرة الحديثة والمقارنة وطلب الملاحظات من دروس سابقة ذات معنى.", stage: "retrieval", estimatedMinutes: 9, semantic: "retrieval", progressiveSupports: ["word-support", "worked-example", "arabic-help"], writingPrompt: "Fill five small boxes with one useful sentence frame: I can ___. / I have to ___. / I have ___. / ___ is more useful than ___. / Could you tell me ___?", writingPromptArabic: "املأ خمسة مربعات صغيرة بقالب جملة مفيد: I can ___. / I have to ___. / I have ___. / ___ is more useful than ___. / Could you tell me ___?", sentencePatterns: ["I can ___.", "I have to ___.", "I have ___.", "___ is more useful than ___.", "Could you tell me ___?"] }),
  ],
  29: [
    activity({ id: "a2-m2-l29-progress-report", kind: "writing", title: "Write a short progress report", titleArabic: "اكتب تقرير تقدم قصيراً", objective: "Write a compact three-sentence update with a clear opening, one detail, and a calm next step.", objectiveArabic: "اكتب تحديثاً موجزاً من ثلاث جمل بافتتاح واضح وتفصيل واحد وخطوة تالية هادئة.", stage: "evidence", estimatedMinutes: 10, semantic: "assessment", progressiveSupports: ["arabic-help", "worked-example", "external-ai-prompt"], writingPrompt: "Use the fictional learner card. Write three sentences: 1) 'This week, I have ...' 2) 'I can ...' 3) 'Next week, I am going to ...' Check capitals, one comma if useful, and a full stop at the end.", writingPromptArabic: "استخدم بطاقة المتعلم الخيالية. اكتب ثلاث جمل: 1) 'This week, I have ...' 2) 'I can ...' 3) 'Next week, I am going to ...' راجع الحروف الكبيرة وفاصلة واحدة إن كانت مفيدة ونقطة في النهاية.", suggestedVocabulary: ["progress", "practise", "goal", "feedback", "next week"], sentencePatterns: ["This week, I have ___.", "I can ___.", "Next week, I am going to ___."] }),
    activity({ id: "a2-m2-l29-editing-lens", kind: "standard", title: "Use a three-point editing lens", titleArabic: "استخدم عدسة مراجعة من ثلاث نقاط", objective: "Check capitals, commas, and a clear closing without rewriting the whole report.", objectiveArabic: "راجع الحروف الكبيرة والفواصل والخاتمة الواضحة دون إعادة كتابة التقرير كله.", stage: "next-bridge", estimatedMinutes: 4, semantic: "tip", progressiveSupports: ["worked-example", "tip"], writingPrompt: "Read: 'this week i have practised speaking, and i can ask for feedback next week i am going to write a report' Add capitals, a full stop, and one helpful comma.", writingPromptArabic: "اقرأ: 'this week i have practised speaking, and i can ask for feedback next week i am going to write a report' أضف حروفاً كبيرة ونقطة وفاصلة مفيدة واحدة." }),
  ],
  30: [
    activity({ id: "a2-m2-l30-work-checkpoint", kind: "assessment", title: "Learning and work checkpoint", titleArabic: "اختبار التعلم والعمل", objective: "Show connected control of experience, plans, responsibility, comparison, and problem-solving through short contextual choices.", objectiveArabic: "أظهر تحكماً مترابطاً في الخبرة والخطط والمسؤولية والمقارنة وحل المشكلات من خلال اختيارات سياقية قصيرة.", stage: "evidence", estimatedMinutes: 12, semantic: "assessment", progressiveSupports: ["arabic-help", "extended-rationale"], writingPrompt: "Complete the checkpoint card: 'I have ___ this week. I am going to ___ next week. At work, I have to ___. If a task is difficult, I can ___.'", writingPromptArabic: "أكمل بطاقة الاختبار: 'I have ___ this week. I am going to ___ next week. At work, I have to ___. If a task is difficult, I can ___.'", sentencePatterns: ["I have ___ this week.", "I am going to ___ next week.", "I have to ___.", "If a task is difficult, I can ___."] }),
    activity({ id: "a2-m2-l30-ahead", kind: "review", title: "Take one practical phrase forward", titleArabic: "خذ عبارة عملية واحدة إلى الأمام", objective: "Choose one polite, useful phrase to carry into the next module's practical service situations.", objectiveArabic: "اختر عبارة مهذبة ومفيدة واحدة لتحملها إلى مواقف الخدمات العملية في الوحدة التالية.", stage: "next-bridge", estimatedMinutes: 3, semantic: "retrieval", progressiveSupports: ["word-support"], sentencePatterns: ["Could you tell me ___?", "Would you like me to ___?", "I am going to ___."] }),
  ],
};
