import type { LessonActivity, VisualVocabularyItem } from "./types";

function natureCard(label: string, colour: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 180" role="img" aria-label="${label}"><rect width="320" height="180" fill="${colour}"/><path d="M0 132c42-30 78-20 116-5 44-44 97-52 204-18v71H0z" fill="#6b9d64"/><circle cx="245" cy="50" r="22" fill="#f2c94c"/><path d="M72 132V83m0 20 30-24m-30 8-24-20" stroke="#315a3b" stroke-width="10" stroke-linecap="round"/><rect x="22" y="22" width="144" height="34" rx="12" fill="#fffdf7"/><text x="94" y="45" text-anchor="middle" font-family="Arial, sans-serif" font-size="16" font-weight="700" fill="#253453">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const placeVisuals: VisualVocabularyItem[] = [
  { id: "a2-m5-place", word: "place", arabic: "مكان", pronunciation: "/pleɪs/", exampleEN: "This is a quiet place to read and walk.", exampleAR: "هذا مكان هادئ للقراءة والمشي.", altText: "Illustrated green place with a path, tree, and sun", category: "Nature and community", interactionHint: "Describe the fictional place with one adjective.", imageUrl: natureCard("Place", "#e8f3ea") },
  { id: "a2-m5-beautiful", word: "beautiful", arabic: "جميل", pronunciation: "/ˈbjuː.tɪ.fəl/", exampleEN: "The park is beautiful in the morning.", exampleAR: "الحديقة جميلة في الصباح.", altText: "Illustrated park card labelled Beautiful", category: "Nature and community", interactionHint: "Pair beautiful with place, park, or view.", imageUrl: natureCard("Beautiful", "#e6f0ff") },
  { id: "a2-m5-visit", word: "visit", arabic: "يزور", pronunciation: "/ˈvɪz.ɪt/", exampleEN: "Many people visit the small garden on weekends.", exampleAR: "يزور كثير من الناس الحديقة الصغيرة في عطلات نهاية الأسبوع.", altText: "Illustrated garden card labelled Visit", category: "Nature and community", interactionHint: "Say who can visit a fictional place.", imageUrl: natureCard("Visit", "#fff2dc") },
];

const habitatVisuals: VisualVocabularyItem[] = [
  { id: "a2-m5-animal", word: "animal", arabic: "حيوان", pronunciation: "/ˈæn.ɪ.məl/", exampleEN: "The animal lives near the river.", exampleAR: "يعيش الحيوان قرب النهر.", altText: "Illustrated habitat with a small fictional animal near water", category: "Animals and habitats", interactionHint: "Use animal with can or cannot.", imageUrl: natureCard("Animal", "#edf5df") },
  { id: "a2-m5-habitat", word: "habitat", arabic: "موئل", pronunciation: "/ˈhæb.ɪ.tæt/", exampleEN: "A wet habitat can support many birds.", exampleAR: "يمكن أن يدعم الموئل الرطب كثيراً من الطيور.", altText: "Illustrated wetland habitat card", category: "Animals and habitats", interactionHint: "Connect habitat to a place where an animal lives.", imageUrl: natureCard("Habitat", "#dff1f4") },
  { id: "a2-m5-live", word: "live", arabic: "يعيش", pronunciation: "/lɪv/", exampleEN: "It is an animal that lives in the trees.", exampleAR: "إنه حيوان يعيش في الأشجار.", altText: "Illustrated tree habitat card labelled Live", category: "Animals and habitats", interactionHint: "Complete: It is an animal that lives ___.", imageUrl: natureCard("Live", "#f6ebd9") },
];

export const A2_MODULE_5_AUTHORED_ACTIVITIES: Record<number, LessonActivity[]> = {
  61: [{ id: "a2-m5-l61-place-cards", kind: "visual-vocabulary", title: "Explore a place worth visiting", titleArabic: "استكشف مكاناً يستحق الزيارة", objective: "Use three place words and an adjective to describe a fictional local place.", objectiveArabic: "استخدم ثلاث كلمات عن المكان وصفة لوصف مكان محلي خيالي.", stage: "introduction", estimatedMinutes: 8, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support", "tip"], visualItems: placeVisuals }],
  62: [{ id: "a2-m5-l62-shared-space-rules", kind: "standard", title: "Choose clear shared-space rules", titleArabic: "اختر قواعد واضحة للمكان المشترك", objective: "Distinguish must, must not, and have to in a fictional park notice.", objectiveArabic: "ميّز بين must وmust not وhave to في لافتة خيالية لحديقة.", stage: "explanation", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "tip"], writingPrompt: "Complete three park rules: Visitors must ___. Visitors must not ___. Staff have to ___.", writingPromptArabic: "أكمل ثلاث قواعد للحديقة: Visitors must ___. Visitors must not ___. Staff have to ___.", sentencePatterns: ["Visitors must ___.", "Visitors must not ___.", "Staff have to ___."] }],
  63: [{ id: "a2-m5-l63-cleaner-neighbourhood", kind: "reading", title: "Read a cleaner-neighbourhood plan", titleArabic: "اقرأ خطة لحي أنظف", objective: "Find one comparison and one too/enough problem in a short community notice.", objectiveArabic: "اعثر على مقارنة واحدة ومشكلة باستخدام too/enough في إشعار مجتمعي قصير.", stage: "introduction", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "word-support", "worked-example"], readingText: "The east street is cleaner than it was last year, but there are still too many bins near the school. The new recycling point is close enough for most families to use after work.", readingTextArabic: "الشارع الشرقي أنظف مما كان عليه العام الماضي، لكن لا تزال هناك حاويات كثيرة جداً قرب المدرسة. نقطة إعادة التدوير الجديدة قريبة بما يكفي لمعظم العائلات لاستخدامها بعد العمل.", readingChecks: [{ id: "a2-m5-l63-comparison", type: "detail", prompt: "What is cleaner than last year?", promptArabic: "ما الذي أصبح أنظف من العام الماضي؟", choices: ["The east street", "The school bins", "The recycling point"], answer: "The east street", explanation: "The first sentence makes this comparison." }, { id: "a2-m5-l63-enough", type: "main-idea", prompt: "Why can many families use the recycling point?", promptArabic: "لماذا يمكن لكثير من العائلات استخدام نقطة إعادة التدوير؟", choices: ["It is close enough", "It is open at night", "It has more bins"], answer: "It is close enough", explanation: "The notice states that it is close enough for most families." }] }],
  64: [{ id: "a2-m5-l64-park-directions", kind: "interaction", title: "Give directions in a park", titleArabic: "أعطِ اتجاهات في حديقة", objective: "Use an imperative, a preposition, and a sequence word to guide a visitor along a fictional path.", objectiveArabic: "استخدم فعل الأمر وحرف جر وكلمة ترتيب لإرشاد زائر في مسار خيالي.", stage: "real-context", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m5-l64-a", speaker: "Visitor", text: "How can I get to the community garden?", textArabic: "كيف أصل إلى الحديقة المجتمعية؟", purpose: "Ask for a route." }, { id: "a2-m5-l64-b", speaker: "Guide", text: "First, walk along the main path. Then turn left at the pond. The garden is behind the library.", textArabic: "أولاً، امشِ على طول المسار الرئيسي. ثم انعطف يساراً عند البركة. الحديقة خلف المكتبة.", purpose: "Give sequenced directions." }] }],
  65: [{ id: "a2-m5-l65-weather-plan", kind: "speaking", title: "Link weather to a plan", titleArabic: "اربط الطقس بخطة", objective: "Say a likely first-conditional result about a fictional outdoor plan.", objectiveArabic: "قل نتيجة محتملة بالشرط الأول حول خطة خارجية خيالية.", stage: "guided-practice", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "tip"], speakingLines: [{ id: "a2-m5-l65-line", speaker: "Model", text: "If it rains tomorrow, we will meet in the community hall instead.", textArabic: "إذا هطل المطر غداً، فسنلتقي في القاعة المجتمعية بدلاً من ذلك.", pronunciationHint: "Keep if it rains together, then pause before we will.", audioText: "If it rains tomorrow, we will meet in the community hall instead." }] }],
  66: [{ id: "a2-m5-l66-habitat-cards", kind: "visual-vocabulary", title: "Notice animals and habitats", titleArabic: "لاحظ الحيوانات وموائلها", objective: "Use can, cannot, and a simple relative clause to describe a fictional animal and its habitat.", objectiveArabic: "استخدم can وcannot وجملة موصولة بسيطة لوصف حيوان خيالي وموئله.", stage: "introduction", estimatedMinutes: 8, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support", "worked-example"], visualItems: habitatVisuals }],
  67: [{ id: "a2-m5-l67-community-project", kind: "reading", title: "Read a community project update", titleArabic: "اقرأ تحديثاً عن مشروع مجتمعي", objective: "Identify the purpose, sequence, and cause in a short project update.", objectiveArabic: "حدّد الغرض والترتيب والسبب في تحديث قصير عن مشروع.", stage: "introduction", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "word-support", "worked-example"], readingText: "The River Path Project began because local residents wanted a safer walking route. First, volunteers collected ideas. Next, the council repaired the path. As a result, more people can now walk to the library safely.", readingTextArabic: "بدأ مشروع مسار النهر لأن السكان المحليين أرادوا طريقاً أكثر أماناً للمشي. أولاً، جمع المتطوعون الأفكار. بعد ذلك، أصلح المجلس المسار. ونتيجة لذلك، يستطيع عدد أكبر من الناس الآن المشي إلى المكتبة بأمان.", readingChecks: [{ id: "a2-m5-l67-purpose", type: "main-idea", prompt: "Why did the project begin?", promptArabic: "لماذا بدأ المشروع؟", choices: ["Residents wanted a safer route", "The library moved", "Volunteers needed work"], answer: "Residents wanted a safer route", explanation: "The first sentence gives the purpose." }, { id: "a2-m5-l67-result", type: "detail", prompt: "What happened after the path was repaired?", promptArabic: "ماذا حدث بعد إصلاح المسار؟", choices: ["More people could walk safely", "The council collected ideas", "The library closed"], answer: "More people could walk safely", explanation: "The final sentence gives this result." }] }],
  68: [{ id: "a2-m5-l68-useful-change", kind: "interaction", title: "Suggest a useful change", titleArabic: "اقترح تغييراً مفيداً", objective: "Make and respond to a practical suggestion with should, could, or why not.", objectiveArabic: "قدّم واقبل أو ناقش اقتراحاً عملياً باستخدام should أو could أو why not.", stage: "real-context", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m5-l68-a", speaker: "Noura", text: "The path is dark after school. We could add two lights near the entrance.", textArabic: "المسار مظلم بعد المدرسة. يمكننا إضافة مصباحين قرب المدخل.", purpose: "Offer a practical change." }, { id: "a2-m5-l68-b", speaker: "Sam", text: "That is a good idea. Why not ask the community group to help?", textArabic: "هذه فكرة جيدة. لماذا لا نطلب من المجموعة المجتمعية المساعدة؟", purpose: "Build on a suggestion." }] }],
  69: [{ id: "a2-m5-l69-nature-families", kind: "standard", title: "Build nature word families", titleArabic: "ابنِ عائلات كلمات الطبيعة", objective: "Connect protect, protection, and protected to useful environmental collocations.", objectiveArabic: "اربط بين protect وprotection وprotected وتلازمات بيئية مفيدة.", stage: "explanation", estimatedMinutes: 7, semantic: "grammar", progressiveSupports: ["arabic-help", "word-support", "worked-example"], writingPrompt: "Complete: We should protect ___. This protection helps ___. The area is protected because ___.", writingPromptArabic: "أكمل: We should protect ___. This protection helps ___. The area is protected because ___.", sentencePatterns: ["We should protect ___.", "This protection helps ___.", "The area is protected because ___."] }],
  70: [{ id: "a2-m5-l70-local-problem", kind: "writing", title: "Describe a local problem clearly", titleArabic: "صِف مشكلة محلية بوضوح", objective: "Write a short fictional problem description with there is/are, a quantifier, and clear punctuation.", objectiveArabic: "اكتب وصفاً قصيراً لمشكلة خيالية باستخدام there is/are ومحدد كمية وترقيم واضح.", stage: "assessment", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "word-support"], writingPrompt: "Write 45–60 words about a fictional street or park problem. Include there is/are, many or too much, one effect, and one full-stop-separated suggestion. Do not use real addresses.", writingPromptArabic: "اكتب 45–60 كلمة عن مشكلة خيالية في شارع أو حديقة. أدرج there is/are وmany أو too much وأثراً واحداً واقتراحاً واحداً بجملة مكتملة. لا تستخدم عناوين حقيقية.", sentencePatterns: ["There are too many ___.", "This means ___.", "The community could ___."] }],
  71: [{ id: "a2-m5-l71-respectful-disagreement", kind: "speaking", title: "Disagree with respect", titleArabic: "اختلف باحترام", objective: "Give an opinion, agree with one point, and express uncertainty politely.", objectiveArabic: "قدّم رأياً ووافق على نقطة واحدة وعبّر عن عدم اليقين بأدب.", stage: "guided-practice", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "tip"], speakingLines: [{ id: "a2-m5-l71-one", speaker: "Model", text: "I think more bins would help. I agree that the park needs care, but I am not sure that bins are the only answer.", textArabic: "أعتقد أن مزيداً من الحاويات سيساعد. أوافق أن الحديقة تحتاج إلى عناية، لكنني لست متأكداً أن الحاويات هي الحل الوحيد.", pronunciationHint: "Stress think, agree, and not sure so the listener hears your balanced opinion.", audioText: "I think more bins would help. I agree that the park needs care, but I am not sure that bins are the only answer." }] }],
  72: [{ id: "a2-m5-l72-community-toolkit", kind: "review", title: "Retrieve the community toolkit", titleArabic: "استرجع أدوات المجتمع", objective: "Select and use language for rules, conditions, suggestions, and descriptions in four short prompts.", objectiveArabic: "اختر واستخدم لغة القواعد والشروط والاقتراحات والأوصاف في أربعة مواقف قصيرة.", stage: "review", estimatedMinutes: 8, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], writingPrompt: "Choose one tool for each prompt: must not, if it rains, we will, we could, or there are too many. Then write one complete community sentence.", writingPromptArabic: "اختر أداة واحدة لكل موقف: must not أو if it rains, we will أو we could أو there are too many. ثم اكتب جملة مجتمعية مكتملة.", sentencePatterns: ["Visitors must not ___.", "If ___, we will ___.", "We could ___."] }],
  73: [{ id: "a2-m5-l73-community-proposal", kind: "writing", title: "Write a community proposal", titleArabic: "اكتب اقتراحاً مجتمعياً", objective: "Draft a short problem-solution proposal with a recommendation and reason.", objectiveArabic: "اكتب اقتراح مشكلة وحل قصيراً مع توصية وسبب.", stage: "assessment", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "word-support"], writingPrompt: "Write 60–75 words about a fictional community improvement. Name the problem, explain one effect, recommend a solution, and give a reason. Do not identify a real place or person.", writingPromptArabic: "اكتب 60–75 كلمة عن تحسين مجتمعي خيالي. سمِّ المشكلة واشرح أثراً واحداً وأوصِ بحل واذكر سبباً. لا تحدد مكاناً أو شخصاً حقيقياً.", sentencePatterns: ["The problem is ___.", "This affects ___.", "I recommend __ because ___."] }],
  74: [{ id: "a2-m5-l74-map-and-rule", kind: "speaking", title: "Explain a map and a rule", titleArabic: "اشرح خريطة وقاعدة", objective: "Explain a short route and check the listener understands a shared-space rule.", objectiveArabic: "اشرح مساراً قصيراً وتأكد من أن المستمع يفهم قاعدة للمكان المشترك.", stage: "real-context", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], speakingLines: [{ id: "a2-m5-l74-one", speaker: "Model", text: "First, go past the pond and turn right at the gate. Please remember: you must keep bicycles on the marked path. Does that make sense?", textArabic: "أولاً، مرّ بجانب البركة وانعطف يميناً عند البوابة. تذكّر من فضلك: يجب أن تبقي الدراجات على المسار المعلّم. هل هذا واضح؟", pronunciationHint: "Pause after the route, then use a friendly rising tone for Does that make sense?", audioText: "First, go past the pond and turn right at the gate. Please remember: you must keep bicycles on the marked path. Does that make sense?" }] }],
  75: [{ id: "a2-m5-l75-nature-checkpoint", kind: "assessment", title: "Nature and community checkpoint", titleArabic: "اختبار الطبيعة والمجتمع", objective: "Show connected control of a description, a rule, a likely result, and a short community proposal.", objectiveArabic: "أظهر تحكماً مترابطاً في وصف وقاعدة ونتيجة محتملة واقتراح مجتمعي قصير.", stage: "assessment", estimatedMinutes: 12, semantic: "assessment", progressiveSupports: ["arabic-help", "worked-example", "tip"], writingPrompt: "For a fictional community park: write one description, one must or must not rule, one if sentence, and a two-sentence improvement proposal. Check each sentence has a clear full stop.", writingPromptArabic: "لحديقة مجتمعية خيالية: اكتب وصفاً واحداً وقاعدة must أو must not وجملة if واقتراح تحسين من جملتين. تحقق من أن كل جملة تنتهي بنقطة واضحة.", sentencePatterns: ["The park is ___.", "Visitors must not ___.", "If ___, we will ___.", "The community should __ because ___."] }],
};
