import type {
  LessonActivity,
  LessonExperienceStage,
  LessonProgressionStage,
  ProgressiveSupport,
  ReadingCheck,
  VisualVocabularyItem,
} from "./types";

type ActivityDraft = Omit<LessonActivity, "stage"> & {
  stage: LessonProgressionStage | LessonExperienceStage;
};

const stageMap: Record<LessonExperienceStage, LessonProgressionStage> = {
  orientation: "introduction",
  encounter: "introduction",
  notice: "explanation",
  "supported-practice": "guided-practice",
  "meaningful-use": "real-context",
  retrieval: "review",
  evidence: "assessment",
  "next-bridge": "review",
};

function activity(draft: ActivityDraft): LessonActivity {
  return { ...draft, stage: draft.stage in stageMap ? stageMap[draft.stage as LessonExperienceStage] : draft.stage as LessonProgressionStage };
}

function scene(label: string, colour: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 180" role="img" aria-label="${label}"><rect width="320" height="180" fill="${colour}"/><circle cx="160" cy="62" r="28" fill="#fffdf7"/><path d="M105 155c8-38 30-57 55-57s47 19 55 57" fill="#fffdf7"/><text x="160" y="170" text-anchor="middle" font-family="Arial, sans-serif" font-size="18" font-weight="700" fill="#253453">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const energyVisuals: VisualVocabularyItem[] = [
  { id: "a2-m1-meal", word: "meal", arabic: "وجبة", pronunciation: "/miːl/", exampleEN: "A healthy meal can give you energy.", exampleAR: "يمكن أن تمنحك الوجبة الصحية طاقة.", altText: "A simple healthy meal on a plate", category: "Food and health", interactionHint: "Say meal once, then connect it with breakfast or lunch.", imageUrl: scene("Healthy meal", "#dff3e5") },
  { id: "a2-m1-vegetable", word: "vegetable", arabic: "خضار", pronunciation: "/ˈvedʒtəbl/", exampleEN: "There are some vegetables in the soup.", exampleAR: "هناك بعض الخضار في الحساء.", altText: "A bowl with colourful vegetables", category: "Food and health", interactionHint: "Hear veg-e-ta-ble slowly; the middle sound is often light.", imageUrl: scene("Vegetables", "#e8f5d7") },
  { id: "a2-m1-water", word: "water", arabic: "ماء", pronunciation: "/ˈwɔːtə/", exampleEN: "I drink water during the day.", exampleAR: "أشرب الماء خلال اليوم.", altText: "A glass of water beside a meal", category: "Food and health", interactionHint: "Use water with some, not a, in this lesson.", imageUrl: scene("Water", "#dbeafe") },
];

const weekReadingChecks: ReadingCheck[] = [
  { id: "a2-m1-week-main", type: "main-idea", prompt: "What is the message mainly about?", promptArabic: "ما الفكرة الرئيسة في الرسالة؟", choices: ["Making a few realistic health changes", "Buying expensive sports equipment", "Studying for a science exam"], answer: "Making a few realistic health changes", explanation: "The writer describes small routine changes across one week." },
  { id: "a2-m1-week-detail", type: "detail", prompt: "What did Noor do after work on Wednesday?", promptArabic: "ماذا فعلت نور بعد العمل يوم الأربعاء؟", choices: ["She walked for twenty minutes", "She visited the pharmacy", "She cooked for friends"], answer: "She walked for twenty minutes", explanation: "The detail follows the Wednesday time marker." },
  { id: "a2-m1-week-inference", type: "inference", prompt: "Why does Noor say the plan was possible?", promptArabic: "لماذا تقول نور إن الخطة كانت ممكنة؟", choices: ["The changes were small", "The week was shorter", "Her doctor gave her a new job"], answer: "The changes were small", explanation: "She chose small actions that fit an ordinary week." },
];

const authored: Record<number, ActivityDraft[]> = {
  1: [
    { id: "a2-m1-l1-routine-map", kind: "standard", title: "Map one ordinary morning", titleArabic: "ارسم خريطة لصباح عادي", objective: "Notice routine adverbs in a short, realistic morning sequence before using one for a fictional learner.", objectiveArabic: "لاحظ ظروف التكرار في تسلسل صباحي واقعي قصير قبل استخدام واحد منها لمتعلم خيالي.", stage: "orientation", estimatedMinutes: 7, semantic: "objective", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Read: Salma usually eats breakfast, but she sometimes skips it. Underline usually and sometimes. Then choose one card: Amina always drinks water / Amina never drinks water.", writingPromptArabic: "اقرأ: Salma usually eats breakfast, but she sometimes skips it. ضع خطاً تحت usually وsometimes. ثم اختر بطاقة واحدة: Amina always drinks water / Amina never drinks water.", sentencePatterns: ["I usually ___.", "I sometimes ___.", "I never ___."] },
    { id: "a2-m1-l1-routine-retrieve", kind: "review", title: "Bridge from an A1 time phrase", titleArabic: "اربطها بعبارة وقت من A1", objective: "Reuse one familiar A1 time phrase with a routine adverb so retrieval has a clear purpose.", objectiveArabic: "أعد استخدام عبارة وقت مألوفة من A1 مع ظرف تكرار حتى يكون للاسترجاع غرض واضح.", stage: "retrieval", estimatedMinutes: 4, semantic: "retrieval", progressiveSupports: ["tip", "word-support"], sentencePatterns: ["In the morning, I usually ___.", "At night, I sometimes ___."] },
  ],
  2: [
    { id: "a2-m1-l2-small-habits-reading", kind: "reading", title: "Read a small-habits note", titleArabic: "اقرأ ملاحظة عن عادات صغيرة", objective: "Follow a short note and distinguish a reason with because from a result with so.", objectiveArabic: "اتبع ملاحظة قصيرة وميّز السبب مع because عن النتيجة مع so.", stage: "encounter", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "word-support"], readingText: "Maha wants more energy in the afternoon, so she prepares fruit before work. She walks for ten minutes because the park is near her home. These habits are small, but they help her feel ready for the day.", readingTextArabic: "تريد مها طاقة أكثر بعد الظهر، لذلك تجهز فاكهة قبل العمل. تمشي عشر دقائق لأن الحديقة قريبة من منزلها. هذه العادات صغيرة، لكنها تساعدها على الشعور بالاستعداد لليوم.", readingChecks: [{ id: "a2-m1-l2-cause", type: "multiple-choice", prompt: "Why does Maha walk for ten minutes?", promptArabic: "لماذا تمشي مها عشر دقائق؟", choices: ["Because the park is near", "So she can prepare fruit", "Because work finishes early"], answer: "Because the park is near", explanation: "Because introduces Maha's reason." }] },
    { id: "a2-m1-l2-reason-sort", kind: "standard", title: "Sort reason and result", titleArabic: "صنّف السبب والنتيجة", objective: "Build two connected statements by choosing whether because or so carries the intended meaning.", objectiveArabic: "ابنِ عبارتين مترابطتين باختيار whether لأن because أو so تحمل المعنى المقصود.", stage: "supported-practice", estimatedMinutes: 6, semantic: "grammar", progressiveSupports: ["worked-example", "arabic-help"], writingPrompt: "Complete the cards: The bus was late, ___ I walked. / I walked ___ the bus was late.", writingPromptArabic: "أكمل البطاقات: The bus was late, ___ I walked. / I walked ___ the bus was late.", sentencePatterns: ["___, so ___.", "___ because ___."] },
  ],
  3: [
    { id: "a2-m1-l3-energy-picture-basket", kind: "visual-vocabulary", title: "Build an energy basket", titleArabic: "ابنِ سلة طاقة", objective: "Meet meal, vegetable, and water through calm visual cards before choosing some or any in a food context.", objectiveArabic: "تعرّف إلى meal وvegetable وwater عبر بطاقات بصرية هادئة قبل اختيار some أو any في سياق طعام.", stage: "encounter", estimatedMinutes: 8, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support", "tip"], visualItems: energyVisuals },
    { id: "a2-m1-l3-some-any-kitchen", kind: "standard", title: "Open the kitchen cupboard", titleArabic: "افتح خزانة المطبخ", objective: "Notice some in a positive statement and any in a question or negative statement without a dense grammar lecture.", objectiveArabic: "لاحظ some في عبارة مثبتة وany في سؤال أو عبارة منفية دون محاضرة قواعد كثيفة.", stage: "notice", estimatedMinutes: 6, semantic: "grammar", progressiveSupports: ["worked-example", "arabic-help"], writingPrompt: "Choose the useful word: There is ___ water. / Is there ___ fruit? / There is not ___ soup.", writingPromptArabic: "اختر الكلمة المناسبة: There is ___ water. / Is there ___ fruit? / There is not ___ soup.", sentencePatterns: ["There is some ___.", "Is there any ___?", "There is not any ___."] },
  ],
  4: [
    { id: "a2-m1-l4-frequency-interview", kind: "interaction", title: "Ask about a character's week", titleArabic: "اسأل عن أسبوع شخصية", objective: "Use How often ...? and frequency expressions in a low-pressure interview about a fictional weekly routine.", objectiveArabic: "استخدم How often ...? وعبارات التكرار في مقابلة دون ضغط عن روتين أسبوعي لشخصية خيالية.", stage: "orientation", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "transcript"], interactionTurns: [{ id: "a2-m1-l4-q", speaker: "Interviewer", text: "How often do you exercise?", textArabic: "كم مرة تمارس الرياضة؟", purpose: "Ask about frequency, not ability." }, { id: "a2-m1-l4-a", speaker: "Yara", text: "I exercise twice a week.", textArabic: "أمارس الرياضة مرتين في الأسبوع.", purpose: "Give one clear frequency answer." }, { id: "a2-m1-l4-follow", speaker: "Interviewer", text: "That is a good start.", textArabic: "هذه بداية جيدة.", purpose: "Respond supportively without judging the amount." }] },
    { id: "a2-m1-l4-frequency-choice", kind: "speaking", title: "Say one frequency answer", titleArabic: "قل إجابة تكرار واحدة", objective: "Practise one whole answer with a natural frequency phrase and a familiar A1 activity.", objectiveArabic: "تدرّب على إجابة كاملة واحدة بعبارة تكرار طبيعية ونشاط مألوف من A1.", stage: "meaningful-use", estimatedMinutes: 4, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], speakingLines: [{ id: "a2-m1-l4-line-1", speaker: "Model", text: "I walk three times a week.", textArabic: "أمشي ثلاث مرات في الأسبوع.", pronunciationHint: "Keep three times together as one small rhythm.", audioText: "I walk three times a week." }, { id: "a2-m1-l4-line-2", speaker: "Your turn", text: "I sometimes play sport after work.", textArabic: "أمارس الرياضة أحياناً بعد العمل.", pronunciationHint: "Choose the fictional schedule card if you prefer not to speak personally.", audioText: "I sometimes play sport after work." }] },
  ],
  5: [
    { id: "a2-m1-l5-advice-voice", kind: "speaking", title: "Offer gentle advice", titleArabic: "قدّم نصيحة لطيفة", objective: "Use should and should not to give one calm, practical suggestion rather than an order.", objectiveArabic: "استخدم should وshould not لتقديم اقتراح عملي هادئ بدلاً من أمر.", stage: "supported-practice", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "transcript"], speakingLines: [{ id: "a2-m1-l5-model", speaker: "Model", text: "You should rest and drink some water.", textArabic: "ينبغي أن ترتاح وتشرب بعض الماء.", pronunciationHint: "Should is gentle here; stress rest and water.", audioText: "You should rest and drink some water." }, { id: "a2-m1-l5-contrast", speaker: "Model", text: "You should not skip every meal.", textArabic: "لا ينبغي أن تتخطى كل وجبة.", pronunciationHint: "Keep should not together; do not make it sound angry.", audioText: "You should not skip every meal." }] },
    { id: "a2-m1-l5-advice-card", kind: "writing", title: "Write advice for a scenario card", titleArabic: "اكتب نصيحة لبطاقة موقف", objective: "Write one supported suggestion for a fictional person, keeping personal health information optional.", objectiveArabic: "اكتب اقتراحاً واحداً مدعوماً لشخصية خيالية مع إبقاء المعلومات الصحية الشخصية اختيارية.", stage: "meaningful-use", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"], writingPrompt: "Choose a card: 'Nabil feels tired after late nights.' Write two gentle lines: He should ___. He should not ___.", writingPromptArabic: "اختر بطاقة: 'Nabil feels tired after late nights.' اكتب سطرين لطيفين: He should ___. He should not ___.", suggestedVocabulary: ["rest", "water", "sleep", "meal", "should"], sentencePatterns: ["He should ___.", "He should not ___."] },
  ],
  6: [
    { id: "a2-m1-l6-pharmacy-dialogue", kind: "interaction", title: "A respectful pharmacy request", titleArabic: "طلب محترم في الصيدلية", objective: "Follow a short pharmacy exchange and choose can or could according to the level of politeness.", objectiveArabic: "اتبع تبادلاً قصيراً في الصيدلية واختر can أو could وفق مستوى الأدب.", stage: "encounter", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m1-l6-open", speaker: "Customer", text: "Could you help me, please?", textArabic: "هل يمكنك مساعدتي من فضلك؟", purpose: "Open a polite request." }, { id: "a2-m1-l6-detail", speaker: "Customer", text: "I need something for a sore throat.", textArabic: "أحتاج إلى شيء لالتهاب الحلق.", purpose: "State a simple need." }, { id: "a2-m1-l6-reply", speaker: "Pharmacist", text: "Yes. Can you describe the symptom?", textArabic: "نعم. هل يمكنك وصف العرض؟", purpose: "Ask a calm follow-up question." }] },
    { id: "a2-m1-l6-polite-ladder", kind: "standard", title: "Make a request softer", titleArabic: "اجعل الطلب ألطف", objective: "Compare Can you ...? and Could you ...? as practical request choices in the same situation.", objectiveArabic: "قارن Can you ...? وCould you ...? كخيارين عمليين للطلب في الموقف نفسه.", stage: "notice", estimatedMinutes: 5, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Put the request cards in a useful order: Hello. / Could you help me, please? / Thank you.", writingPromptArabic: "رتّب بطاقات الطلب بشكل مفيد: Hello. / Could you help me, please? / Thank you.", sentencePatterns: ["Could you ___, please?", "Can you ___, please?"] },
  ],
  7: [
    { id: "a2-m1-l7-symptom-observation", kind: "standard", title: "Describe, do not diagnose", titleArabic: "صِف ولا تشخّص", objective: "Use have, feel, look, and sound to describe simple fictional symptoms without giving medical diagnosis.", objectiveArabic: "استخدم have وfeel وlook وsound لوصف أعراض خيالية بسيطة من دون تقديم تشخيص طبي.", stage: "notice", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "tip"], writingPrompt: "Match the safe descriptions: I have a headache. / I feel tired. / You look pale. / That sounds painful.", writingPromptArabic: "طابق الأوصاف الآمنة: I have a headache. / I feel tired. / You look pale. / That sounds painful.", sentencePatterns: ["I have a ___.", "I feel ___.", "You look ___.", "That sounds ___."] },
    { id: "a2-m1-l7-symptom-message", kind: "writing", title: "Send a short absence message", titleArabic: "أرسل رسالة غياب قصيرة", objective: "Write a respectful two-sentence message about a fictional absence using a description and a practical next step.", objectiveArabic: "اكتب رسالة محترمة من جملتين عن غياب خيالي باستخدام وصف وخطوة عملية تالية.", stage: "meaningful-use", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"], writingPrompt: "Use the fictional card: 'Mina feels unwell today.' Write: Hello ___. Mina feels ___. She can come tomorrow / needs to rest today.", writingPromptArabic: "استخدم البطاقة الخيالية: 'Mina feels unwell today.' اكتب: Hello ___. Mina feels ___. She can come tomorrow / needs to rest today.", suggestedVocabulary: ["feel", "tired", "rest", "tomorrow", "message"] },
  ],
  8: [
    { id: "a2-m1-l8-yesterday-timeline", kind: "standard", title: "Place three moments on yesterday's line", titleArabic: "ضع ثلاث لحظات على خط الأمس", objective: "Meet past simple be and regular verbs through a visual yesterday timeline before building one short account.", objectiveArabic: "تعرّف إلى الماضي البسيط من be والأفعال المنتظمة عبر خط زمني لليوم السابق قبل بناء قصة قصيرة.", stage: "encounter", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "tip"], writingPrompt: "Put the cards in order: Yesterday, I was tired. / I walked home. / I rested after dinner.", writingPromptArabic: "رتّب البطاقات: Yesterday, I was tired. / I walked home. / I rested after dinner.", sentencePatterns: ["Yesterday, I was ___.", "I walked ___.", "I rested ___."] },
    { id: "a2-m1-l8-past-echo", kind: "speaking", title: "Retell one calm yesterday", titleArabic: "أعد سرد يوم هادئ أمس", objective: "Say a two-line fictional yesterday account with one past form and one time word.", objectiveArabic: "قل قصة خيالية من سطرين عن الأمس مع صيغة ماضية واحدة وكلمة وقت واحدة.", stage: "supported-practice", estimatedMinutes: 5, semantic: "activity", progressiveSupports: ["worked-example", "transcript"], speakingLines: [{ id: "a2-m1-l8-line", speaker: "Model", text: "Yesterday, I was tired, so I rested at home.", textArabic: "كنت متعباً أمس، لذلك ارتحت في المنزل.", pronunciationHint: "Link was tired and pause before so.", audioText: "Yesterday, I was tired, so I rested at home." }] },
  ],
  9: [
    { id: "a2-m1-l9-week-changes", kind: "reading", title: "Read a week of changes", titleArabic: "اقرأ أسبوعاً من التغييرات", objective: "Read a connected A2 diary and follow before, after, and then across one realistic week.", objectiveArabic: "اقرأ يوميات A2 مترابطة واتبع before وafter وthen خلال أسبوع واقعي واحد.", stage: "encounter", estimatedMinutes: 11, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "word-support"], readingText: "Before Monday, Noor often skipped breakfast. On Monday, she prepared fruit and water. After work on Wednesday, she walked for twenty minutes. Then she wrote the plan in her notebook. By Friday, she felt more organised because the changes were small and possible.", readingTextArabic: "قبل يوم الاثنين، كانت نور غالباً تتخطى الفطور. يوم الاثنين، جهزت فاكهة وماء. بعد العمل يوم الأربعاء، مشت عشرين دقيقة. ثم كتبت الخطة في دفترها. بحلول الجمعة، شعرت بتنظيم أكبر لأن التغييرات كانت صغيرة وممكنة.", readingChecks: weekReadingChecks },
    { id: "a2-m1-l9-sequence-strip", kind: "standard", title: "Keep the order visible", titleArabic: "اجعل الترتيب واضحاً", objective: "Rebuild the diary sequence with time markers rather than answering only isolated grammar questions.", objectiveArabic: "أعد بناء ترتيب اليوميات بعلامات الوقت بدلاً من الإجابة عن أسئلة قواعد معزولة فقط.", stage: "supported-practice", estimatedMinutes: 5, semantic: "retrieval", progressiveSupports: ["worked-example", "tip"], sentencePatterns: ["Before ___, ___.", "After ___, ___.", "Then ___."] },
  ],
  10: [
    { id: "a2-m1-l10-choice-paragraph", kind: "writing", title: "Write a healthy-choice paragraph", titleArabic: "اكتب فقرة عن اختيار صحي", objective: "Build an 80-word supported paragraph around a fictional healthy choice using first, then, and finally.", objectiveArabic: "ابنِ فقرة مدعومة من 80 كلمة حول اختيار صحي خيالي باستخدام first وthen وfinally.", stage: "meaningful-use", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"], writingPrompt: "Choose the character card, not your private health data. Explain a three-step plan: First, Omar prepares ___. Then, he ___. Finally, he ___. Add one because sentence.", writingPromptArabic: "اختر بطاقة الشخصية لا بياناتك الصحية الخاصة. اشرح خطة من ثلاث خطوات: First, Omar prepares ___. Then, he ___. Finally, he ___. أضف جملة واحدة مع because.", suggestedVocabulary: ["meal", "water", "walk", "rest", "because", "first", "then", "finally"], sentencePatterns: ["First, ___.", "Then, ___.", "Finally, ___.", "___ because ___."] },
    { id: "a2-m1-l10-revision-lens", kind: "review", title: "Use a three-point revision lens", titleArabic: "استخدم عدسة مراجعة من ثلاث نقاط", objective: "Check sequence, one reason, and final punctuation before using an optional external feedback prompt.", objectiveArabic: "تحقق من الترتيب وسبب واحد وعلامة الترقيم النهائية قبل استخدام طلب ملاحظات خارجي اختياري.", stage: "evidence", estimatedMinutes: 5, semantic: "assessment", progressiveSupports: ["tip", "external-ai-prompt"], writingPrompt: "Before sharing your paragraph, tick: I used first/then/finally. I used because correctly. Every sentence ends with punctuation.", writingPromptArabic: "قبل مشاركة فقرتك، ضع علامة: استخدمت first/then/finally. استخدمت because بشكل صحيح. تنتهي كل جملة بعلامة ترقيم." },
  ],
  11: [
    { id: "a2-m1-l11-question-lab", kind: "standard", title: "Turn ideas into useful questions", titleArabic: "حوّل الأفكار إلى أسئلة مفيدة", objective: "Notice how present and past questions need different helpers in a practical health-information task.", objectiveArabic: "لاحظ كيف تحتاج أسئلة الحاضر والماضي إلى أدوات مختلفة في مهمة معلومات صحية عملية.", stage: "notice", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "tip"], writingPrompt: "Sort the question cards: Do you exercise? / Did you walk yesterday? / How often do you rest? / What happened after lunch?", writingPromptArabic: "صنّف بطاقات الأسئلة: Do you exercise? / Did you walk yesterday? / How often do you rest? / What happened after lunch?", sentencePatterns: ["Do you ___?", "Did you ___?", "How often do you ___?", "What happened ___?"] },
    { id: "a2-m1-l11-question-mission", kind: "interaction", title: "Choose two questions for a health coach", titleArabic: "اختر سؤالين لمدرب صحة", objective: "Choose two relevant questions for a fictional health coach and explain what each question discovers.", objectiveArabic: "اختر سؤالين مناسبين لمدرب صحة خيالي واشرح ما الذي يكشفه كل سؤال.", stage: "meaningful-use", estimatedMinutes: 6, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], interactionTurns: [{ id: "a2-m1-l11-turn", speaker: "Coach", text: "How often do you walk after work?", textArabic: "كم مرة تمشي بعد العمل؟", purpose: "Ask about a current routine." }, { id: "a2-m1-l11-answer", speaker: "Character", text: "I walked yesterday, but I do not usually walk after work.", textArabic: "مشيت أمس، لكنني لا أمشي عادة بعد العمل.", purpose: "Contrast one past event with a present habit." }] },
  ],
  12: [
    { id: "a2-m1-l12-clarify-listen", kind: "speaking", title: "Listen, clarify, then answer", titleArabic: "استمع واطلب التوضيح ثم أجب", objective: "Practise clarification phrases as a confident communication tool when a health instruction is not clear.", objectiveArabic: "تدرّب على عبارات طلب التوضيح كأداة تواصل واثقة عندما لا تكون التعليمات الصحية واضحة.", stage: "orientation", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], speakingLines: [{ id: "a2-m1-l12-request", speaker: "Learner", text: "Could you repeat that, please?", textArabic: "هل يمكنك تكرار ذلك، من فضلك؟", pronunciationHint: "Could you is one gentle request chunk.", audioText: "Could you repeat that, please?" }, { id: "a2-m1-l12-check", speaker: "Learner", text: "Do you mean I should rest today?", textArabic: "هل تقصد أن ينبغي أن أرتاح اليوم؟", pronunciationHint: "Raise your voice a little at the end to check meaning.", audioText: "Do you mean I should rest today?" }] },
    { id: "a2-m1-l12-clarification-choice", kind: "interaction", title: "Choose the helpful follow-up", titleArabic: "اختر سؤال المتابعة المفيد", objective: "Select a clarification question that fits a short instruction instead of pretending to understand.", objectiveArabic: "اختر سؤال توضيح يناسب تعليمة قصيرة بدلاً من التظاهر بالفهم.", stage: "supported-practice", estimatedMinutes: 5, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "a2-m1-l12-instruction", speaker: "Nurse", text: "Take the medicine after food.", textArabic: "تناول الدواء بعد الطعام.", purpose: "Give a simple instruction." }, { id: "a2-m1-l12-follow", speaker: "Learner", text: "Sorry, after breakfast or after dinner?", textArabic: "عذراً، بعد الإفطار أم بعد العشاء؟", purpose: "Ask a precise follow-up." }] },
  ],
  13: [
    { id: "a2-m1-l13-health-map", kind: "review", title: "Reconnect the health map", titleArabic: "أعد وصل خريطة الصحة", objective: "Retrieve advice, reasons, frequency, and one past event through a choice-based map rather than a long final recap.", objectiveArabic: "استرجع النصيحة والأسباب والتكرار وحدثاً ماضياً عبر خريطة قائمة على الاختيار بدلاً من تلخيص نهائي طويل.", stage: "retrieval", estimatedMinutes: 10, semantic: "retrieval", progressiveSupports: ["arabic-help", "word-support", "tip"], writingPrompt: "Choose four map cards and connect them: usually / because / should / yesterday. Make two short connected sentences.", writingPromptArabic: "اختر أربع بطاقات من الخريطة واربطها: usually / because / should / yesterday. كوّن جملتين قصيرتين مترابطتين.", sentencePatterns: ["I usually ___ because ___.", "Yesterday, I ___.", "You should ___."] },
    { id: "a2-m1-l13-choose-your-gap", kind: "standard", title: "Choose one thing to revisit", titleArabic: "اختر شيئاً واحداً لمراجعته", objective: "Identify one language choice to revisit, giving the learner agency before the module's final writing and checkpoint.", objectiveArabic: "حدّد اختياراً لغوياً واحداً لمراجعته لإعطاء المتعلم دوراً قبل الكتابة النهائية واختبار الوحدة.", stage: "next-bridge", estimatedMinutes: 4, semantic: "tip", progressiveSupports: ["arabic-help", "tip"], writingPrompt: "Choose one: I need more practice with advice / reasons / past events. Reopen only that card before the next lesson.", writingPromptArabic: "اختر واحداً: أحتاج إلى تدريب أكثر على advice / reasons / past events. أعد فتح تلك البطاقة فقط قبل الدرس التالي." },
  ],
  14: [
    { id: "a2-m1-l14-practical-message", kind: "writing", title: "Write a practical health message", titleArabic: "اكتب رسالة صحية عملية", objective: "Write a clear, respectful message to a fictional friend or colleague using an opening, a suggestion, and accurate punctuation.", objectiveArabic: "اكتب رسالة واضحة ومحترمة لصديق أو زميل خيالي باستخدام افتتاح واقتراح وعلامات ترقيم دقيقة.", stage: "meaningful-use", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"], writingPrompt: "Use a fictional situation: 'Sara has a busy week and feels tired.' Write 80–100 words. Include a greeting, two gentle suggestions, one because sentence, and a polite closing.", writingPromptArabic: "استخدم موقفاً خيالياً: 'Sara has a busy week and feels tired.' اكتب 80–100 كلمة. أضف تحية واقتراحين لطيفين وجملة because وختاماً مهذباً.", suggestedVocabulary: ["rest", "meal", "water", "walk", "should", "because", "message"], sentencePatterns: ["Hi ___.", "You should ___.", "This may help because ___.", "Take care,"] },
    { id: "a2-m1-l14-punctuation-pass", kind: "review", title: "Make the message easy to read", titleArabic: "اجعل الرسالة سهلة القراءة", objective: "Revise capitals, full stops, and the greeting line as reader-friendly choices rather than isolated rules.", objectiveArabic: "راجع الحروف الكبيرة والنقاط وسطر التحية كاختيارات تسهّل القراءة بدلاً من قواعد معزولة.", stage: "evidence", estimatedMinutes: 5, semantic: "assessment", progressiveSupports: ["worked-example", "tip", "external-ai-prompt"], writingPrompt: "Read your draft aloud once. Check: capital letter at the beginning, full stop at the end, and a separate greeting line.", writingPromptArabic: "اقرأ مسودتك بصوت عالٍ مرة. تحقق: حرف كبير في البداية، نقطة في النهاية، وسطر تحية منفصل." },
  ],
  15: [
    { id: "a2-m1-l15-health-checkpoint", kind: "assessment", title: "Health and habits checkpoint", titleArabic: "اختبار الصحة والعادات", objective: "Show connected control of present routines, one past event, advice, and a reason in a practical fictional scenario.", objectiveArabic: "أظهر تحكماً مترابطاً في الروتين الحالي وحدث ماضٍ ونصيحة وسبب ضمن موقف خيالي عملي.", stage: "evidence", estimatedMinutes: 16, semantic: "assessment", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Read the character card. Complete four short parts: (1) a routine with usually, (2) advice with should, (3) one yesterday sentence, and (4) a reason with because. Then choose the best polite clarification question.", writingPromptArabic: "اقرأ بطاقة الشخصية. أكمل أربعة أجزاء قصيرة: (1) روتين مع usually، (2) نصيحة مع should، (3) جملة واحدة عن الأمس، و(4) سبب مع because. ثم اختر أفضل سؤال توضيح مهذب.", sentencePatterns: ["I usually ___.", "You should ___.", "Yesterday, ___.", "___ because ___."] },
    { id: "a2-m1-l15-forward-bridge", kind: "review", title: "Carry one useful pattern forward", titleArabic: "احمل نمطاً مفيداً إلى الأمام", objective: "Choose one health-and-habits pattern to carry into the learning-and-work module, where routines and responsibilities become more independent.", objectiveArabic: "اختر نمطاً واحداً من الصحة والعادات لتحمله إلى وحدة التعلم والعمل حيث تصبح الروتينات والمسؤوليات أكثر استقلالاً.", stage: "next-bridge", estimatedMinutes: 4, semantic: "retrieval", progressiveSupports: ["tip", "word-support"], sentencePatterns: ["I usually ___.", "I should ___.", "Could you repeat that, please?"] },
  ],
};

export const A2_MODULE_1_AUTHORED_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(
  Object.entries(authored).map(([lessonNumber, activities]) => [Number(lessonNumber), activities.map(activity)]),
);
