import type {
  LessonActivity,
  LessonExperienceStage,
  LessonProgressionStage,
  ProgressiveSupport,
  VisualVocabularyItem,
} from "./types";

type ActivityDraft = Omit<LessonActivity, "stage"> & {
  stage: LessonProgressionStage | LessonExperienceStage;
  progressiveSupports?: ProgressiveSupport[];
};

const stageMap: Record<LessonExperienceStage, LessonProgressionStage> = {
  orientation: "introduction",
  encounter: "introduction",
  notice: "explanation",
  "supported-practice": "guided-practice",
  "meaningful-use": "real-context",
  retrieval: "review",
  evidence: "assessment",
  "next-bridge": "review",
};

function activity(draft: ActivityDraft): LessonActivity {
  return {
    ...draft,
    stage: draft.stage in stageMap
      ? stageMap[draft.stage as LessonExperienceStage]
      : draft.stage as LessonProgressionStage,
  };
}

function scene(label: string, colour: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 180" role="img" aria-label="${label}"><rect width="320" height="180" fill="${colour}"/><rect x="58" y="35" width="204" height="88" rx="14" fill="#fffdf7"/><path d="M92 68h136M92 91h98" stroke="#253453" stroke-width="8" stroke-linecap="round"/><text x="160" y="158" text-anchor="middle" font-family="Arial, sans-serif" font-size="18" font-weight="700" fill="#253453">${label}</text></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const stationVisuals: VisualVocabularyItem[] = [
  { id: "a2-m3-station", word: "station", arabic: "محطة", pronunciation: "/ˈsteɪʃən/", exampleEN: "The station is across the road.", exampleAR: "المحطة عبر الطريق.", altText: "A station sign on a calm information board", category: "Travel", interactionHint: "Say station, then point to the place where a journey begins.", imageUrl: scene("Station", "#e4edf8") },
  { id: "a2-m3-ticket", word: "ticket", arabic: "تذكرة", pronunciation: "/ˈtɪkɪt/", exampleEN: "Please keep your ticket with you.", exampleAR: "يرجى الاحتفاظ بتذكرتك معك.", altText: "A simple travel ticket on a pale card", category: "Travel", interactionHint: "Ticket is a countable noun: one ticket, two tickets.", imageUrl: scene("Ticket", "#fff0d7") },
  { id: "a2-m3-platform", word: "platform", arabic: "رصيف المحطة", pronunciation: "/ˈplætfɔːm/", exampleEN: "The train leaves from platform four.", exampleAR: "يغادر القطار من الرصيف الرابع.", altText: "A platform number on a station board", category: "Travel", interactionHint: "Use platform with a number when checking travel details.", imageUrl: scene("Platform", "#e7f4e8") },
];

export const A2_MODULE_3_AUTHORED_ACTIVITIES: Record<number, LessonActivity[]> = {
  31: [
    activity({ id: "a2-m3-l31-arrangement-board", kind: "standard", title: "Read the short-trip arrangement board", titleArabic: "اقرأ لوحة ترتيبات الرحلة القصيرة", objective: "Notice how present continuous can describe a firm future arrangement.", objectiveArabic: "لاحظ كيف يمكن للمضارع المستمر وصف ترتيب مستقبلي مؤكد.", stage: "orientation", estimatedMinutes: 7, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], writingPrompt: "Read: 'Maya is meeting her cousin at 9. They are taking the bus at 10.' Underline the arrangement verb, then complete: 'They are ___ at ___." , writingPromptArabic: "اقرأ: 'Maya is meeting her cousin at 9. They are taking the bus at 10.' ضع خطاً تحت فعل الترتيب، ثم أكمل: 'They are ___ at ___.'", sentencePatterns: ["I am meeting ___ at ___.", "We are leaving at ___."] }),
    activity({ id: "a2-m3-l31-plan-bridge", kind: "review", title: "Choose a clear time bridge", titleArabic: "اختر عبارة وقت واضحة", objective: "Connect the arrangement to familiar A1 and A2 time language.", objectiveArabic: "اربط الترتيب بلغة الوقت المألوفة من A1 وA2.", stage: "retrieval", estimatedMinutes: 4, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], writingPrompt: "Add one time phrase: tomorrow morning / at half past eight / after lunch. 'We are checking in ___.'", writingPromptArabic: "أضف عبارة وقت واحدة: tomorrow morning / at half past eight / after lunch. 'We are checking in ___.'", sentencePatterns: ["We are ___ tomorrow."] }),
  ],
  32: [
    activity({ id: "a2-m3-l32-station-cards", kind: "visual-vocabulary", title: "Open three station cards", titleArabic: "افتح ثلاث بطاقات للمحطة", objective: "Meet station, ticket, and platform through accessible visual cards before using them in a journey.", objectiveArabic: "تعرّف إلى station وticket وplatform عبر بطاقات بصرية ميسرة قبل استخدامها في رحلة.", stage: "encounter", estimatedMinutes: 8, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support", "tip"], visualItems: stationVisuals }),
    activity({ id: "a2-m3-l32-ticket-detail", kind: "standard", title: "Find the useful ticket detail", titleArabic: "اعثر على تفصيل التذكرة المفيد", objective: "Use travel compound nouns to identify a simple station detail.", objectiveArabic: "استخدم مفردات السفر لتحديد تفصيل بسيط في المحطة.", stage: "meaningful-use", estimatedMinutes: 5, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Complete the card: Train ___ / platform ___ / return ___. Choose: ticket, 4, station.", writingPromptArabic: "أكمل البطاقة: Train ___ / platform ___ / return ___. اختر: ticket, 4, station.", sentencePatterns: ["My train leaves from platform ___."] }),
  ],
  33: [
    activity({ id: "a2-m3-l33-check-in-dialogue", kind: "interaction", title: "Check into a hotel politely", titleArabic: "سجّل الوصول إلى الفندق بأدب", objective: "Use can, could, and would in a realistic hotel check-in without memorising a long script.", objectiveArabic: "استخدم can وcould وwould في تسجيل وصول واقعي إلى الفندق دون حفظ نص طويل.", stage: "encounter", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m3-l33-a", speaker: "Guest", text: "Hello. Could I check in, please?", textArabic: "مرحباً. هل يمكنني تسجيل الوصول، من فضلك؟", purpose: "Make a polite opening request." }, { id: "a2-m3-l33-b", speaker: "Receptionist", text: "Certainly. Can I have your reservation name?", textArabic: "بالتأكيد. هل يمكنني معرفة اسم الحجز؟", purpose: "Ask for a needed detail politely." }, { id: "a2-m3-l33-c", speaker: "Guest", text: "It is under Amal Hassan. Would it be possible to have a quiet room?", textArabic: "الحجز باسم أمل حسن. هل سيكون ممكناً الحصول على غرفة هادئة؟", purpose: "Make an additional courteous request." }] }),
  ],
  34: [
    activity({ id: "a2-m3-l34-delay-reading", kind: "reading", title: "Read a delayed-journey update", titleArabic: "اقرأ تحديثاً عن رحلة متأخرة", objective: "Use past continuous to understand the background of a travel problem.", objectiveArabic: "استخدم الماضي المستمر لفهم خلفية مشكلة سفر.", stage: "encounter", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "word-support"], readingText: "At six o'clock, Tariq was waiting on platform two. It was raining heavily, and the train was moving very slowly. A staff member announced the delay, so Tariq sent a short message to his hotel. He arrived later, but he had a clear plan.", readingTextArabic: "في الساعة السادسة، كان طارق ينتظر على الرصيف الثاني. كانت تمطر بغزارة، وكان القطار يتحرك ببطء شديد. أعلن أحد الموظفين عن التأخير، لذلك أرسل طارق رسالة قصيرة إلى فندقه. وصل لاحقاً، لكن كانت لديه خطة واضحة.", readingChecks: [{ id: "a2-m3-l34-main", type: "main-idea", prompt: "Why was Tariq late?", promptArabic: "لماذا تأخر طارق؟", choices: ["His train was delayed", "He forgot his ticket", "His hotel was closed"], answer: "His train was delayed", explanation: "The staff member announced a delay while Tariq was waiting." }, { id: "a2-m3-l34-inference", type: "inference", prompt: "Why did Tariq message the hotel?", promptArabic: "لماذا أرسل طارق رسالة إلى الفندق؟", choices: ["To explain the changed arrival time", "To reserve a new room", "To ask for a ticket"], answer: "To explain the changed arrival time", explanation: "The delay meant that he would arrive later than planned." }] }),
  ],
  35: [
    activity({ id: "a2-m3-l35-service-order", kind: "speaking", title: "Ask for what you need", titleArabic: "اطلب ما تحتاج إليه", objective: "Say would like as a polite connected request in a service situation.", objectiveArabic: "قل would like كطلب مهذب مترابط في موقف خدمة.", stage: "supported-practice", estimatedMinutes: 6, semantic: "activity", progressiveSupports: ["transcript", "worked-example", "arabic-help"], speakingLines: [{ id: "a2-m3-l35-model", speaker: "Model", text: "I would like a map of the area, please.", textArabic: "أود خريطة للمنطقة، من فضلك.", pronunciationHint: "Keep would like together; make map and area clear.", audioText: "I would like a map of the area, please." }, { id: "a2-m3-l35-option", speaker: "Model", text: "Would you like help with your bags?", textArabic: "هل ترغب في المساعدة في حقائبك؟", pronunciationHint: "Use a gentle rising tone for the offer.", audioText: "Would you like help with your bags?" }] }),
  ],
  36: [
    activity({ id: "a2-m3-l36-landmark-route", kind: "standard", title: "Build a route with landmarks", titleArabic: "ابنِ مساراً باستخدام المعالم", objective: "Use movement verbs and prepositions to make a short route clear.", objectiveArabic: "استخدم أفعال الحركة وحروف الجر لجعل مسار قصير واضحاً.", stage: "notice", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "word-support"], writingPrompt: "Complete the route: Go ___ the bank. Walk ___ the bridge. The museum is ___ the café. Choose: past, across, opposite.", writingPromptArabic: "أكمل المسار: Go ___ the bank. Walk ___ the bridge. The museum is ___ the café. اختر: past, across, opposite.", sentencePatterns: ["Go past the ___.", "Walk across the ___.", "It is opposite the ___."] }),
    activity({ id: "a2-m3-l36-map-say", kind: "speaking", title: "Say one calm direction", titleArabic: "قل اتجاهاً واحداً بهدوء", objective: "Practise one complete direction as a listener would hear it on a street.", objectiveArabic: "تدرّب على اتجاه كامل واحد كما يسمعه المستمع في الشارع.", stage: "meaningful-use", estimatedMinutes: 4, semantic: "activity", progressiveSupports: ["transcript", "tip"], speakingLines: [{ id: "a2-m3-l36-line", speaker: "Model", text: "Walk past the bank, then turn left at the bridge.", textArabic: "امشِ بجوار البنك، ثم انعطف يساراً عند الجسر.", pronunciationHint: "Pause after bank; stress turn left and bridge.", audioText: "Walk past the bank, then turn left at the bridge." }] }),
  ],
  37: [
    activity({ id: "a2-m3-l37-change-dialogue", kind: "interaction", title: "Respond when a plan changes", titleArabic: "استجب عندما تتغير الخطة", objective: "Use if and when to offer a practical alternative when a travel plan changes.", objectiveArabic: "استخدم if وwhen لتقديم بديل عملي عندما تتغير خطة سفر.", stage: "encounter", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m3-l37-a", speaker: "Nabil", text: "What will you do if the bus is late?", textArabic: "ماذا ستفعل إذا تأخرت الحافلة؟", purpose: "Ask about a practical condition." }, { id: "a2-m3-l37-b", speaker: "Salma", text: "If it is late, I will take the metro. When I arrive, I will call the hotel.", textArabic: "إذا تأخرت، سأستخدم المترو. عندما أصل، سأتصل بالفندق.", purpose: "Give a calm alternative and a next action." }] }),
  ],
  38: [
    activity({ id: "a2-m3-l38-message-reading", kind: "reading", title: "Read a useful travel message", titleArabic: "اقرأ رسالة سفر مفيدة", objective: "Find dates, times, and the action needed in a short travel message.", objectiveArabic: "اعثر على التواريخ والأوقات والإجراء المطلوب في رسالة سفر قصيرة.", stage: "encounter", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "word-support"], readingText: "Hi Noor — your coach leaves on Fri 14 June at 07:45 from Central Station, platform 6. Please arrive 20 mins early and keep this message with your ticket. If you need help, call the travel desk before 18:00 today. Safe journey!", readingTextArabic: "مرحباً نور — تغادر حافلتك يوم الجمعة 14 يونيو الساعة 07:45 من المحطة المركزية، الرصيف 6. يرجى الوصول قبل 20 دقيقة والاحتفاظ بهذه الرسالة مع تذكرتك. إذا احتجت إلى مساعدة، اتصل بمكتب السفر قبل 18:00 اليوم. رحلة آمنة!", readingChecks: [{ id: "a2-m3-l38-detail", type: "detail", prompt: "Where does Noor need to go?", promptArabic: "إلى أين تحتاج نور أن تذهب؟", choices: ["Platform 6 at Central Station", "A hotel reception", "The airport desk"], answer: "Platform 6 at Central Station", explanation: "The message gives both the station and platform." }, { id: "a2-m3-l38-main", type: "main-idea", prompt: "What should Noor do before the journey?", promptArabic: "ماذا ينبغي أن تفعل نور قبل الرحلة؟", choices: ["Arrive early and keep the message", "Buy a new suitcase", "Change the travel date"], answer: "Arrive early and keep the message", explanation: "These are the two direct instructions in the message." }] }),
  ],
  39: [
    activity({ id: "a2-m3-l39-booking-problem", kind: "interaction", title: "Explain a booking problem", titleArabic: "اشرح مشكلة حجز", objective: "Explain a simple booking error and ask for a solution politely.", objectiveArabic: "اشرح خطأً بسيطاً في الحجز واطلب حلاً بأدب.", stage: "meaningful-use", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m3-l39-a", speaker: "Guest", text: "Excuse me, I think there is a problem with my booking.", textArabic: "عفواً، أعتقد أن هناك مشكلة في حجزي.", purpose: "Open a problem calmly." }, { id: "a2-m3-l39-b", speaker: "Agent", text: "I am sorry to hear that. What seems to be wrong?", textArabic: "يؤسفني سماع ذلك. ما المشكلة على ما يبدو؟", purpose: "Invite a clear explanation." }, { id: "a2-m3-l39-c", speaker: "Guest", text: "The date is wrong. Could you check whether another room is available?", textArabic: "التاريخ غير صحيح. هل يمكنك التحقق مما إذا كانت غرفة أخرى متاحة؟", purpose: "State the issue and request a solution." }] }),
  ],
  40: [
    activity({ id: "a2-m3-l40-choice-table", kind: "standard", title: "Compare three travel choices", titleArabic: "قارن ثلاثة خيارات سفر", objective: "Use comparatives and a superlative to choose a travel option for a clear reason.", objectiveArabic: "استخدم المقارنة والتفضيل لاختيار خيار سفر لسبب واضح.", stage: "notice", estimatedMinutes: 8, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example", "word-support"], writingPrompt: "Choose from bus, train, and taxi. Complete: 'The bus is ___ than the taxi. The train is the ___ option for comfort.'", writingPromptArabic: "اختر من الحافلة والقطار وسيارة الأجرة. أكمل: 'The bus is ___ than the taxi. The train is the ___ option for comfort.'", suggestedVocabulary: ["cheap", "comfortable", "quick", "best"], sentencePatterns: ["The ___ is cheaper than ___.", "The ___ is the most comfortable option."] }),
  ],
  41: [
    activity({ id: "a2-m3-l41-travel-note", kind: "writing", title: "Write a useful travel note", titleArabic: "اكتب ملاحظة سفر مفيدة", objective: "Write a compact fictional travel note with a route, sequence, and polite practical reminder.", objectiveArabic: "اكتب ملاحظة سفر خيالية مختصرة تتضمن مساراً وترتيباً وتذكيراً عملياً مهذباً.", stage: "meaningful-use", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["arabic-help", "worked-example", "external-ai-prompt", "tip"], writingPrompt: "Write 45–60 words for a fictional visitor. Include: first action, one landmark direction, ticket reminder, and a kind closing. Do not use your real address or travel plans.", writingPromptArabic: "اكتب 45–60 كلمة لزائر خيالي. ضمّن: الإجراء الأول، اتجاه مع معلم واحد، تذكير بالتذكرة، وخاتمة لطيفة. لا تستخدم عنوانك الحقيقي أو خطط سفرك.", suggestedVocabulary: ["first", "then", "platform", "ticket", "please"], sentencePatterns: ["First, ___.", "Then, go ___.", "Please remember to ___."] }),
  ],
  42: [
    activity({ id: "a2-m3-l42-confirmation-listening", kind: "speaking", title: "Listen for the important detail", titleArabic: "استمع إلى التفصيل المهم", objective: "Confirm a date, time, and place rather than repeating every word of a travel message.", objectiveArabic: "أكد تاريخاً ووقتاً ومكاناً بدلاً من تكرار كل كلمة من رسالة سفر.", stage: "supported-practice", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["transcript", "arabic-help", "worked-example"], speakingLines: [{ id: "a2-m3-l42-model", speaker: "Agent", text: "To confirm: your train is on Tuesday at quarter past nine from platform three.", textArabic: "للتأكيد: قطارك يوم الثلاثاء الساعة التاسعة والربع من الرصيف الثالث.", pronunciationHint: "Pause after confirm and Tuesday; make the numbers clear.", audioText: "To confirm: your train is on Tuesday at quarter past nine from platform three." }, { id: "a2-m3-l42-response", speaker: "Traveller", text: "Thank you. Tuesday, 9:15, platform three.", textArabic: "شكراً. الثلاثاء، 9:15، الرصيف الثالث.", pronunciationHint: "Say the key details separately and calmly.", audioText: "Thank you. Tuesday, 9:15, platform three." }] }),
  ],
  43: [
    activity({ id: "a2-m3-l43-service-retrieval", kind: "review", title: "Retrieve a calm service response", titleArabic: "استرجع استجابة خدمة هادئة", objective: "Choose the most useful request, condition, direction, and comparison from the module.", objectiveArabic: "اختر الطلب والشرط والاتجاه والمقارنة الأكثر فائدة من الوحدة.", stage: "retrieval", estimatedMinutes: 9, semantic: "retrieval", progressiveSupports: ["arabic-help", "word-support", "worked-example"], writingPrompt: "Complete four small cards: a polite request / an if sentence / one direction / one comparison. Use the word bank if needed.", writingPromptArabic: "أكمل أربع بطاقات صغيرة: طلب مهذب / جملة if / اتجاه واحد / مقارنة واحدة. استخدم بنك الكلمات عند الحاجة.", sentencePatterns: ["Could I ___, please?", "If ___, I will ___.", "Go past the ___.", "___ is cheaper than ___."] }),
  ],
  44: [
    activity({ id: "a2-m3-l44-complete-service-conversation", kind: "interaction", title: "Build a complete service conversation", titleArabic: "ابنِ محادثة خدمة كاملة", objective: "Connect opening, problem, request, response, and closing in one manageable fictional conversation.", objectiveArabic: "اربط الافتتاح والمشكلة والطلب والاستجابة والخاتمة في محادثة خيالية واحدة قابلة للإدارة.", stage: "meaningful-use", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["arabic-help", "transcript", "worked-example"], interactionTurns: [{ id: "a2-m3-l44-a", speaker: "Traveller", text: "Good afternoon. Could you help me with my ticket, please?", textArabic: "مساء الخير. هل يمكنك مساعدتي في تذكرتي، من فضلك؟", purpose: "Open politely and state the topic." }, { id: "a2-m3-l44-b", speaker: "Agent", text: "Of course. What seems to be the problem?", textArabic: "بالتأكيد. ما المشكلة على ما يبدو؟", purpose: "Invite a clear explanation." }, { id: "a2-m3-l44-c", speaker: "Traveller", text: "I booked Friday, but I am travelling on Saturday. Is it possible to change it?", textArabic: "حجزت يوم الجمعة، لكنني أسافر يوم السبت. هل من الممكن تغييره؟", purpose: "Explain the mismatch and request a solution." }, { id: "a2-m3-l44-d", speaker: "Agent", text: "Yes. I can change it if there is a seat available.", textArabic: "نعم. يمكنني تغييره إذا كان هناك مقعد متاح.", purpose: "Offer a conditional solution." }] }),
  ],
  45: [
    activity({ id: "a2-m3-l45-travel-checkpoint", kind: "assessment", title: "Travel and services checkpoint", titleArabic: "اختبار السفر والخدمات", objective: "Show connected control of arrangements, requests, directions, travel detail, and problem-solving in short practical prompts.", objectiveArabic: "أظهر تحكماً مترابطاً في الترتيبات والطلبات والاتجاهات وتفاصيل السفر وحل المشكلات في مهام عملية قصيرة.", stage: "evidence", estimatedMinutes: 14, semantic: "assessment", progressiveSupports: ["arabic-help", "word-support", "extended-rationale"], writingPrompt: "Complete four short fictional prompts: confirm a time, ask for a service, give one direction, and explain one booking problem. Keep names and plans fictional.", writingPromptArabic: "أكمل أربع مهام خيالية قصيرة: أكد وقتاً، اطلب خدمة، أعطِ اتجاهاً واحداً، واشرح مشكلة حجز واحدة. اجعل الأسماء والخطط خيالية.", suggestedVocabulary: ["confirm", "platform", "could", "if", "booking"], sentencePatterns: ["I am ___ at ___.", "Could I ___, please?", "Go ___ the ___.", "If ___, I will ___."] }),
  ],
};
