import rawDraft from "./a2-draft.json";
import { enrichLesson } from "./activity-plan";
import { A2_MODULE_1_AUTHORED_ACTIVITIES } from "./a2-module-1-authored-activities";
import { A2_MODULE_2_AUTHORED_ACTIVITIES } from "./a2-module-2-authored-activities";
import { A2_MODULE_3_AUTHORED_ACTIVITIES } from "./a2-module-3-authored-activities";
import { A2_MODULE_4_AUTHORED_ACTIVITIES } from "./a2-module-4-authored-activities";
import { A2_MODULE_5_AUTHORED_ACTIVITIES } from "./a2-module-5-authored-activities";
import { A2_MODULE_6_AUTHORED_ACTIVITIES } from "./a2-module-6-authored-activities";
import { A2_MODULE_7_AUTHORED_ACTIVITIES } from "./a2-module-7-authored-activities";
import { createLessonExperience } from "./lesson-experience";
import { buildModuleDefinitions } from "./module-definitions";
import { getProgressiveImmersiveModules } from "./progressive-immersive";
import type {
  CourseDefinition,
  GrammarTopic,
  ImmersiveLessonBlueprint,
  LessonExperience,
  LessonDefinition,
  LessonStep,
  VocabularyItem,
} from "./types";

type DraftVocabulary = {
  word: string;
  arabic: string;
  partOfSpeech: string;
  definition: string;
  exampleEN: string;
  exampleAR: string;
};

type DraftLesson = { vocabulary: DraftVocabulary[] };

/**
 * The original A2 draft remains a curated bilingual vocabulary seed.  The
 * active lesson sequence now comes from the nine authored immersive modules,
 * allowing every seed word to reappear in a wider set of communicative tasks.
 */
const SEEDED_VOCABULARY: VocabularyItem[] = (rawDraft as DraftLesson[])
  .flatMap((lesson) => lesson.vocabulary)
  .map((item, index) => ({
    id: `a2-seed-${index + 1}`,
    word: item.word,
    arabic: item.arabic,
    ipa: "",
    phoneticRespelling: item.word,
    partOfSpeech: item.partOfSpeech,
    definition: item.definition,
    exampleEN: item.exampleEN,
    exampleAR: item.exampleAR,
  }));

const seedByWord = new Map(SEEDED_VOCABULARY.map((item) => [item.word.toLocaleLowerCase(), item]));

const A2_STEPS: LessonStep[] = [
  { id: "start", title: "Connect", titleArabic: "اربط", purpose: "Retrieve a useful A1 phrase and identify today's situation.", estimatedMinutes: 5 },
  { id: "explore", title: "Meet the language", titleArabic: "تعرّف إلى اللغة", purpose: "Notice new words and a grammar choice in a practical context.", estimatedMinutes: 10 },
  { id: "notice", title: "Notice the choice", titleArabic: "لاحظ الاختيار", purpose: "Compare meaning, form, and an Arabic-speaker risk before using the pattern.", estimatedMinutes: 10 },
  { id: "build", title: "Build a response", titleArabic: "ابنِ استجابة", purpose: "Shape short connected sentences with support and feedback.", estimatedMinutes: 10 },
  { id: "respond", title: "Use it for a purpose", titleArabic: "استخدمها لغرض", purpose: "Speak or write for a real audience, situation, and goal.", estimatedMinutes: 15 },
  { id: "prove", title: "Check and retrieve", titleArabic: "تحقق واسترجع", purpose: "Check contextual understanding and schedule a short review.", estimatedMinutes: 10 },
];

function uniqueVocabulary(items: VocabularyItem[]) {
  return Array.from(new Map(items.map((item) => [item.word.toLocaleLowerCase(), item])).values());
}

function anchorVocabulary(anchor: string, blueprint: ImmersiveLessonBlueprint): VocabularyItem {
  const normalized = anchor.toLocaleLowerCase();
  const existing = seedByWord.get(normalized);
  if (existing) return existing;
  const id = `a2-anchor-${blueprint.lessonNumber}-${normalized.replace(/[^a-z0-9]+/g, "-")}`;
  return {
    id,
    word: anchor,
    arabic: `مفردة أساسية في درس «${blueprint.titleArabic}»`,
    ipa: "",
    phoneticRespelling: anchor,
    partOfSpeech: "useful word or phrase",
    definition: `A key word or phrase for the ${blueprint.title} situation.`,
    exampleEN: `Use “${anchor}” when you ${blueprint.canDo.toLocaleLowerCase().replace(/^i can /, "")}.`,
    exampleAR: `استخدم «${anchor}» عندما تنفذ هدف درس «${blueprint.titleArabic}».`,
  };
}

function vocabularyForBlueprint(blueprint: ImmersiveLessonBlueprint) {
  const anchorWords = blueprint.vocabularyAnchors.map((anchor) => anchorVocabulary(anchor, blueprint));
  const rotationStart = ((blueprint.lessonNumber - 1) * 3) % SEEDED_VOCABULARY.length;
  const rotatedSeeds = Array.from({ length: 4 }, (_, index) => SEEDED_VOCABULARY[(rotationStart + index) % SEEDED_VOCABULARY.length]);
  // A seed intentionally appears again in later lessons for retrieval practice.
  // Persisted vocabulary rows are lesson-owned, however, so every occurrence
  // needs a lesson-scoped key even when its word and definition are shared.
  return uniqueVocabulary([...anchorWords, ...rotatedSeeds]).map((word) => ({
    ...word,
    id: `a2-lesson-${blueprint.lessonNumber}-${word.id}`,
  }));
}

function grammarForBlueprint(blueprint: ImmersiveLessonBlueprint): GrammarTopic {
  const focus = blueprint.grammarFocus;
  return {
    id: `a2-grammar-${blueprint.lessonNumber}`,
    lessonNumber: blueprint.lessonNumber,
    topic: focus,
    arabicName: blueprint.grammarFocusArabic,
    concept: blueprint.beginnerExplanation,
    represents: `Choose ${focus} to make your meaning clear in the ${blueprint.title} situation.`,
    arabicComparison: blueprint.beginnerExplanationArabic,
    useWhen: [
      `the ${blueprint.title} situation matches your purpose`,
      "you need to connect two short ideas clearly instead of translating word by word",
    ],
    doNotUseWhen: ["a shorter A1 pattern already expresses exactly the meaning you need"],
    commonMistakes: [{
      wrong: "Translating the Arabic sentence word by word before checking the English pattern.",
      correct: `Choose the ${focus} pattern, then check the meaning and punctuation.`,
      explanation: "English word order and grammar choices carry meaning. Start from the communicative purpose, not from a literal translation.",
    }],
    structure: {
      positive: `Use ${focus} in a clear affirmative sentence about ${blueprint.title.toLocaleLowerCase()}.`,
      negative: `Make the negative form carefully when ${focus} requires it.`,
      question: `Ask one useful follow-up question using ${focus}.`,
    },
    examples: [{
      en: `In this situation, I can ${blueprint.canDo.replace(/^I can /, "")}.`,
      ar: `في هذا الموقف، ${blueprint.canDoArabic.replace(/^أستطيع /, "أستطيع ")}`,
    }],
    practice: [],
  };
}

const A2_MODULE_1_EXPERIENCES: Record<number, LessonExperience> = {
  1: createLessonExperience({ archetype: "discover", density: "light", archetypeRationale: "Frequency language begins with familiar morning routines.", selectedStages: ["orientation", "encounter", "retrieval", "next-bridge"], firstView: { whatItIs: "A routine-language discovery", whatToDo: "Map one morning and choose one frequency phrase.", whatMatters: "Usually and sometimes change how true a routine is.", whatNext: "Carry one time phrase forward." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  2: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A connected note gives reasons and results a clear purpose.", selectedStages: ["encounter", "notice", "supported-practice", "retrieval"], firstView: { whatItIs: "A reason-and-result reading", whatToDo: "Read for the reason, then sort because and so.", whatMatters: "The connector changes the relationship between ideas.", whatNext: "Use one connector with food language." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  3: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Visual food language gives some and any concrete meaning.", selectedStages: ["encounter", "notice", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A visual food-and-energy lesson", whatToDo: "Explore three cards, then open the kitchen task.", whatMatters: "Some and any depend on the message you make.", whatNext: "Use the words in a weekly routine." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  4: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Frequency becomes useful in a supportive interview.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A weekly-routine interview", whatToDo: "Ask one question and give one supported answer.", whatMatters: "How often asks about a pattern, not a single event.", whatNext: "Use frequency to make advice specific." }, progressiveSupports: ["arabic-help", "worked-example", "transcript"] }),
  5: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Advice needs a calm spoken model before extended feedback.", selectedStages: ["notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A gentle-advice rehearsal", whatToDo: "Hear two models, then write for a character.", whatMatters: "Should suggests; it does not command.", whatNext: "Use respectful tone in a pharmacy exchange." }, progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"] }),
  6: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "A pharmacy interaction gives polite requests a real listener and purpose.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A practical pharmacy conversation", whatToDo: "Follow the dialogue and choose the softer request.", whatMatters: "Could you helps you sound clear and respectful.", whatNext: "Describe a simple symptom safely." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  7: createLessonExperience({ archetype: "writing", density: "normal", archetypeRationale: "Description language is practised in a privacy-safe fictional message.", selectedStages: ["notice", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A safe description-and-message lesson", whatToDo: "Match descriptions, then write for a fictional person.", whatMatters: "Describe what you notice; do not diagnose.", whatNext: "Place one event on yesterday's timeline." }, progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"] }),
  8: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "A visual time line makes past forms meaningful.", selectedStages: ["encounter", "notice", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A yesterday time-line lesson", whatToDo: "Order three moments, then retell a calm day.", whatMatters: "Past forms locate an event before now.", whatNext: "Read a fuller week of small changes." }, progressiveSupports: ["arabic-help", "worked-example", "transcript"] }),
  9: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A connected diary checks sequence, detail, and inference at A2.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A connected weekly diary", whatToDo: "Read once for the main idea, then trace time markers.", whatMatters: "Before, after, and then organise a story.", whatNext: "Use that structure in a paragraph." }, progressiveSupports: ["arabic-help", "transcript", "word-support"] }),
  10: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The learner can now plan, draft, and review a short paragraph.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A guided healthy-choice paragraph", whatToDo: "Plan three linked actions for a character.", whatMatters: "Clear order and one reason guide the reader.", whatNext: "Turn the same ideas into questions." }, progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"] }),
  11: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Question helpers are compared through a useful information task.", selectedStages: ["notice", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A practical question workshop", whatToDo: "Sort current and past questions, then choose two.", whatMatters: "The helper shows whether a question is about now or before.", whatNext: "Ask for clarification with confidence." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  12: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "Clarification phrases are short heard-and-repeated tools.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A listening-and-clarifying practice", whatToDo: "Hear an instruction and choose a follow-up.", whatMatters: "Clarifying is active communication, not failure.", whatNext: "Reconnect the module's key choices." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  13: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "This lesson retrieves and lets the learner choose a gap to revisit.", selectedStages: ["retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A choice-based health map", whatToDo: "Connect four cards, then select one gap.", whatMatters: "Retrieval makes final writing more independent.", whatNext: "Reopen only the card you chose." }, progressiveSupports: ["arabic-help", "word-support", "tip"] }),
  14: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A practical message joins routines, advice, reasons, and punctuation.", selectedStages: ["orientation", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A practical supportive message", whatToDo: "Write for a fictional reader, then revise for clarity.", whatMatters: "Tone and punctuation help a reader trust you.", whatNext: "Use the connected language in the checkpoint." }, progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"] }),
  15: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "A checkpoint gathers connected evidence before broader independent-life topics.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A health-and-habits checkpoint", whatToDo: "Complete four short scenario tasks.", whatMatters: "You are connecting ideas, not reciting perfectly.", whatNext: "Carry one strong pattern to the next module." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
};

const A2_MODULE_2_EXPERIENCES: Record<number, LessonExperience> = {
  16: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A focused contrast makes routine and in-progress work language meaningful before more extended practice.", selectedStages: ["orientation", "notice", "retrieval", "next-bridge"], firstView: { whatItIs: "A now-or-usually contrast", whatToDo: "Sort two short sentences, then carry one A1 time phrase forward.", whatMatters: "The verb form tells the reader whether an action is routine or happening now.", whatNext: "Use that contrast when describing a learner's skills." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  17: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Visual skill cards make new learning-and-work words concrete before a low-risk profile-writing task.", selectedStages: ["encounter", "notice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A visual skills lesson", whatToDo: "Explore three cards, then build a fictional learner profile.", whatMatters: "Can and be good at describe different kinds of ability.", whatNext: "Meet those abilities inside a connected workday." }, progressiveSupports: ["arabic-help", "word-support", "worked-example", "external-ai-prompt"] }),
  18: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A short workday diary gives when and while a natural sequence and a reason for close reading.", selectedStages: ["encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A workday diary reading", whatToDo: "Read the sequence, then locate what happened during another action.", whatMatters: "When and while organise connected events differently.", whatNext: "Use the same precision when checking team rules." }, progressiveSupports: ["arabic-help", "transcript", "word-support"] }),
  19: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "Workplace signs and a first-day dialogue make responsibility language useful rather than abstract.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use"], firstView: { whatItIs: "A first-day rules conversation", whatToDo: "Follow a colleague exchange, then choose the strength of each rule.", whatMatters: "Have to, do not have to, and must not communicate different responsibilities.", whatNext: "Turn one responsibility into a practical plan." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  20: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A small study-plan rehearsal develops future-intention language without asking for an extended personal plan.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A small-plan rehearsal", whatToDo: "Write two fictional intentions, then say one calmly.", whatMatters: "Be going to connects a plan with a specific next time.", whatNext: "Use planning language to offer help." }, progressiveSupports: ["arabic-help", "worked-example", "word-support", "transcript"] }),
  21: createLessonExperience({ archetype: "interaction", density: "light", archetypeRationale: "Offering help is best learned through a short exchange where object pronouns matter to the listener.", selectedStages: ["encounter", "notice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A helpful-colleague exchange", whatToDo: "Follow the link problem, then repeat one clear offer.", whatMatters: "It and you prevent unnecessary repetition in a helpful response.", whatNext: "Give a brief update on a task you have finished." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  22: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Recent results need a concise present-perfect contrast and a purposeful spoken progress update.", selectedStages: ["notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A recent-results workshop", whatToDo: "Compare result cards, then give a two-line update.", whatMatters: "Present perfect links a finished action with now.", whatNext: "Read how experience changes a work profile." }, progressiveSupports: ["arabic-help", "worked-example", "extended-rationale"] }),
  23: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A profile gives ever, never, and before a human experience context instead of an isolated exercise.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "An experience-profile reading", whatToDo: "Read for earlier experience and identify what has never happened.", whatMatters: "Ever, never, and before describe experience without naming an exact time.", whatNext: "Compare two useful ways to learn." }, progressiveSupports: ["arabic-help", "transcript", "word-support"] }),
  24: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "A focused comparison task supports fair choices about learning strategies without an overloaded grammar lecture.", selectedStages: ["notice", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A fair-comparison workshop", whatToDo: "Complete two comparison cards about study choices.", whatMatters: "Comparatives explain why one option fits a purpose.", whatNext: "Ask for feedback on your choice politely." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  25: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "Feedback requests are short, high-value phrases that benefit from gentle listening-and-speaking rehearsal.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A polite feedback rehearsal", whatToDo: "Repeat two respectful question openings, then select one for a task.", whatMatters: "An indirect question protects both clarity and tone.", whatNext: "Notice how preparation changes a later experience." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  26: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A second-chance story makes the relationship between an earlier event and current preparation meaningful at A2.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A second-chance story", whatToDo: "Trace the earlier event, then find actions that still matter.", whatMatters: "Past simple tells the earlier event; present perfect connects experience to now.", whatNext: "Use linked reasons and results to solve a practical problem." }, progressiveSupports: ["arabic-help", "transcript", "extended-rationale"] }),
  27: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A small work problem creates a natural need for because, so, and but as problem-solving connectors.", selectedStages: ["encounter", "notice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A calm problem-solving dialogue", whatToDo: "Follow the printer problem and identify its reason, result, and contrast.", whatMatters: "Connectors make a problem and proposed solution easier to understand.", whatNext: "Retrieve the module's strongest learning-and-work patterns." }, progressiveSupports: ["arabic-help", "worked-example", "transcript"] }),
  28: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "A compact grid enables intentional retrieval across the module without forcing every skill into another full lesson.", selectedStages: ["retrieval", "supported-practice", "evidence", "next-bridge"], firstView: { whatItIs: "A learning-and-work retrieval grid", whatToDo: "Fill five small boxes, then choose one pattern to revisit.", whatMatters: "Retrieval shows what is ready to use and what needs another look.", whatNext: "Use your chosen patterns in a concise progress report." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  29: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A bounded progress report gives the learner a connected, assessable writing purpose with focused editing.", selectedStages: ["orientation", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A three-sentence progress report", whatToDo: "Draft for a fictional learner, then revise capitals, a comma, and the closing.", whatMatters: "A reader needs a clear update, one useful detail, and a next step.", whatNext: "Use the same connected control in the module checkpoint." }, progressiveSupports: ["arabic-help", "worked-example", "external-ai-prompt", "tip"] }),
  30: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "A contextual checkpoint gathers evidence of plans, progress, responsibilities, and solutions before service situations.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A learning-and-work checkpoint", whatToDo: "Complete four short connected prompts, then keep one practical phrase.", whatMatters: "The goal is connected communication, not a perfect recital.", whatNext: "Carry a respectful request into the next module's service situations." }, progressiveSupports: ["arabic-help", "extended-rationale", "word-support"] }),
};

const A2_MODULE_3_EXPERIENCES: Record<number, LessonExperience> = {
  31: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "A short arrangement board makes future present continuous meaningful before the learner has to plan anything extensive.", selectedStages: ["orientation", "notice", "retrieval", "next-bridge"], firstView: { whatItIs: "A future-arrangement board", whatToDo: "Read two arrangements, then add one clear time phrase.", whatMatters: "Present continuous can describe an arrangement that is already organised.", whatNext: "Use station words to make the arrangement more specific." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  32: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Accessible station cards give travel nouns a concrete reference before short detail work.", selectedStages: ["encounter", "notice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A visual station-language lesson", whatToDo: "Explore three cards and complete one ticket detail.", whatMatters: "A journey becomes easier when you can identify place, ticket, and platform.", whatNext: "Use those details in a polite hotel arrival." }, progressiveSupports: ["arabic-help", "word-support", "tip"] }),
  33: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Hotel check-in creates a natural reason to distinguish can, could, and would.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A polite hotel check-in", whatToDo: "Follow the exchange and notice the respectful request.", whatMatters: "Polite language is clear without being demanding.", whatNext: "Understand a journey problem described in the past." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  34: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A delayed-journey update gives past continuous a useful background situation and supports inferential reading.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A delayed-journey update", whatToDo: "Read once for the problem, then find what was happening during it.", whatMatters: "Past continuous sets the scene around a key event.", whatNext: "Ask for a service with a calm connected phrase." }, progressiveSupports: ["arabic-help", "transcript", "word-support"] }),
  35: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "Would like is a high-value service phrase best built through a short spoken rehearsal.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A polite service rehearsal", whatToDo: "Listen to two requests and say one at a comfortable pace.", whatMatters: "Would like keeps a request friendly and direct.", whatNext: "Give someone a clear route with a landmark." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  36: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Route building lets movement prepositions show their meaning through an actual listener journey.", selectedStages: ["encounter", "notice", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A landmark-route workshop", whatToDo: "Complete a short route, then say one complete direction.", whatMatters: "A clear preposition helps another person picture where to go.", whatNext: "Offer an alternative when a route changes." }, progressiveSupports: ["arabic-help", "worked-example", "word-support", "transcript"] }),
  37: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A changed travel plan is an authentic reason to use if and when for a practical alternative.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use"], firstView: { whatItIs: "A changed-plan conversation", whatToDo: "Follow one delay and select the calm alternative.", whatMatters: "If introduces a possible problem; when introduces the next expected step.", whatNext: "Read a message for the exact details that matter." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  38: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A concise travel message develops selective reading for real information rather than extended narrative reading.", selectedStages: ["encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A travel-detail reading", whatToDo: "Scan for place, time, and the action you need to take.", whatMatters: "Travel messages often hide the most important detail in a short line.", whatNext: "Use these details to explain a booking issue." }, progressiveSupports: ["arabic-help", "transcript", "word-support"] }),
  39: createLessonExperience({ archetype: "interaction", density: "deep", archetypeRationale: "A booking problem requires a complete sequence of polite opening, explanation, request, and solution.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use", "evidence"], firstView: { whatItIs: "A booking-problem dialogue", whatToDo: "Follow the problem, then identify the sentence that asks for a solution.", whatMatters: "Clear facts plus a respectful request make service conversations easier.", whatNext: "Compare practical options before choosing one." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  40: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A compact choice table supports comparison language without turning a practical decision into a long lecture.", selectedStages: ["notice", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A travel-choice comparison", whatToDo: "Complete two sentences that compare three options.", whatMatters: "Comparatives explain a difference; a superlative identifies one standout option.", whatNext: "Turn your choice into a useful note for a visitor." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  41: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A fictional visitor note brings sequence, direction, reminders, and audience awareness into one bounded task.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A useful fictional travel note", whatToDo: "Plan a route, draft a short note, then revise for a visitor.", whatMatters: "Order and an explicit reminder let a reader act confidently.", whatNext: "Listen for the details that a traveller should repeat back." }, progressiveSupports: ["arabic-help", "worked-example", "word-support", "external-ai-prompt"] }),
  42: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "Confirmation language is deliberately small and oral so the learner can focus on accurate key details.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A detail-confirmation rehearsal", whatToDo: "Hear a travel detail and repeat only date, time, and place.", whatMatters: "Checking key details prevents a practical misunderstanding.", whatNext: "Retrieve the module's strongest travel tools." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  43: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "A compact card retrieval lets the learner reconnect requests, conditions, directions, and comparisons without another full task of each type.", selectedStages: ["retrieval", "supported-practice", "evidence", "next-bridge"], firstView: { whatItIs: "A travel-language retrieval set", whatToDo: "Complete four small cards and reopen one uncertain pattern.", whatMatters: "Retrieval shows which phrases are ready for a real service conversation.", whatNext: "Use those cards in one complete conversation." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  44: createLessonExperience({ archetype: "integration", density: "normal", archetypeRationale: "A complete service conversation deliberately combines the module's language choices into one manageable interaction.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A complete service conversation", whatToDo: "Follow the five-part exchange and name its polite solution.", whatMatters: "Opening, explanation, request, and closing each help the listener cooperate.", whatNext: "Show your connected travel language in the checkpoint." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  45: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "Short practical prompts gather evidence of travel planning and service problem-solving without overloading one response.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A travel-and-services checkpoint", whatToDo: "Respond to four small fictional travel situations.", whatMatters: "The evidence is clear, useful communication across connected tasks.", whatNext: "Carry one confident request into stories and memories." }, progressiveSupports: ["arabic-help", "word-support", "extended-rationale"] }),
};

const A2_MODULE_4_EXPERIENCES: Record<number, LessonExperience> = {
  46: createLessonExperience({ archetype: "notice", density: "normal", archetypeRationale: "A timeline lets past affirmative and negative forms show events rather than rules.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A memorable-day timeline", whatToDo: "Place three fictional events, including one negative past form.", whatMatters: "Past simple tells the main events of a finished story.", whatNext: "Read how a setting prepares a story." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  47: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A compact opening scene makes setting vocabulary purposeful before a learner writes their own event.", selectedStages: ["encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "An opening-scene reading", whatToDo: "Find the place and the words that create its mood.", whatMatters: "A setting helps a reader imagine the story before events begin.", whatNext: "Ask about an action already in progress." }, progressiveSupports: ["arabic-help", "word-support", "tip"] }),
  48: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "One focused question-and-answer exchange makes past continuous form useful immediately.", selectedStages: ["notice", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A past-moment question", whatToDo: "Build one question and answer it with a short scene.", whatMatters: "Past continuous describes an action already happening at a particular moment.", whatNext: "Use sequence words to organise the story." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  49: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Visual sequence cards make story connectors concrete before longer narrative work.", selectedStages: ["encounter", "notice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A picture-story sequence", whatToDo: "Order three visual cards and narrate their connectors.", whatMatters: "Sequence words guide a listener through what changed.", whatNext: "Connect a background action to a surprise." }, progressiveSupports: ["arabic-help", "word-support", "tip"] }),
  50: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "An unexpected moment gives when and while a clear narrative purpose.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A surprise-moment dialogue", whatToDo: "Follow the background action and identify the sudden event.", whatMatters: "While frames an action; when introduces the event that changes it.", whatNext: "Say how a moment felt." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  51: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A tiny contrast rehearsal lets learners hear the meaning difference between -ed and -ing adjectives.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A feeling-and-description rehearsal", whatToDo: "Repeat two contrasts, then make one of your own.", whatMatters: "People feel excited; events can be exciting.", whatNext: "Read how an act of kindness connects people in a story." }, progressiveSupports: ["arabic-help", "transcript", "tip"] }),
  52: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A small kindness story creates a natural need to track people and reasons across sentences.", selectedStages: ["encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A kindness-story reading", whatToDo: "Track who each pronoun means and why the person helped.", whatMatters: "Pronouns and because connect a story without repeating every noun.", whatNext: "Make regular past endings clear in speech." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  53: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "Short past-tense chunks put intelligible regular endings ahead of accent imitation.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A past-ending sound check", whatToDo: "Repeat two story lines slowly, then at a natural pace.", whatMatters: "Clear endings help another person hear that an event is finished.", whatNext: "Connect past habits to childhood memories." }, progressiveSupports: ["transcript", "tip"] }),
  54: createLessonExperience({ archetype: "writing", density: "normal", archetypeRationale: "A short fictional memory gives used to a meaningful contrast without requiring private disclosure.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A safe childhood-memory note", whatToDo: "Write a fictional habit and a contrasting non-habit.", whatMatters: "Used to describes a past routine that is not true now.", whatNext: "Notice which past event happened earlier." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  55: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A comparison of two events keeps before and after visible without another long narrative task.", selectedStages: ["notice", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "An earlier-event workshop", whatToDo: "Choose what happened first and complete one before/after sentence.", whatMatters: "Time links let a listener follow the order of past events.", whatNext: "Use that order in a friendly message about yesterday." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  56: createLessonExperience({ archetype: "interaction", density: "light", archetypeRationale: "A short friendly message puts contractions and past explanation into a familiar social context.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A yesterday-message exchange", whatToDo: "Read two turns and identify the apology, reason, and warm reply.", whatMatters: "A brief reason and friendly next step can repair a missed plan.", whatNext: "Retrieve the story tools that now feel most useful." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  57: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "Sorting a small narrative toolkit prompts recall across grammar, sequence, feeling, and cohesion without another full story.", selectedStages: ["retrieval", "supported-practice", "evidence", "next-bridge"], firstView: { whatItIs: "A story-language toolkit", whatToDo: "Sort four tools, then use two in one story sentence.", whatMatters: "Retrieval reveals which tools you can select when you need them.", whatNext: "Use a chosen set to draft a connected memory." }, progressiveSupports: ["word-support", "tip"] }),
  58: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A bounded fictional memory lets the learner integrate narrative shape, feeling, and reflection deliberately.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A connected-memory draft", whatToDo: "Plan four sentences, draft, then check your ending reflects on the event.", whatMatters: "A clear opening, event, feeling, and reflection make a small story satisfying.", whatNext: "Retell the same event aloud with fewer repeated words." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  59: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A three-event retell builds fluency through a small complete story rather than isolated sentences.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A three-event retell", whatToDo: "Retell the model, then improve one repeated word.", whatMatters: "Sequence words and clear actions help a listener stay with your story.", whatNext: "Show your connected story choices in the checkpoint." }, progressiveSupports: ["transcript", "worked-example", "tip"] }),
  60: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "Small, fictional story prompts provide evidence of connected past language without demanding personal disclosure.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A stories-and-memories checkpoint", whatToDo: "Choose one fictional prompt and write four or five connected sentences.", whatMatters: "The evidence is a clear sequence, a past event, a feeling, and reflection.", whatNext: "Carry one confident story tool into the next A2 module." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
};

const A2_MODULE_5_EXPERIENCES: Record<number, LessonExperience> = {
  61: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Visual place cards make descriptive language concrete before a learner forms a short local-place description.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use"], firstView: { whatItIs: "A place-description discovery", whatToDo: "Open three cards and describe one fictional place with an adjective.", whatMatters: "A precise adjective helps another person imagine a place.", whatNext: "Set clear rules for people who use shared places." }, progressiveSupports: ["arabic-help", "word-support", "tip"] }),
  62: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A small rule notice lets learners notice how must, must not, and have to communicate distinct obligations before using them.", selectedStages: ["notice", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A shared-space rule workshop", whatToDo: "Complete three short park rules, then name who each rule helps.", whatMatters: "Must, must not, and have to communicate different kinds of obligation.", whatNext: "Read how one neighbourhood compares its old and new situation." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  63: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A brief notice gives too/enough and comparative forms a clear information-finding purpose.", selectedStages: ["encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A cleaner-neighbourhood notice", whatToDo: "Find one comparison and one problem in the notice.", whatMatters: "Comparisons and quantities help us judge whether a change is useful.", whatNext: "Give a visitor a clear route through a park." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  64: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A two-turn route exchange requires the learner to sequence directions for a real listener.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A park-directions exchange", whatToDo: "Trace the route, then adapt one direction for a different landmark.", whatMatters: "Sequence words and prepositions prevent a route from becoming confusing.", whatNext: "Connect a weather change to an outdoor plan." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  65: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A single likely weather result is a focused way to rehearse first conditional stress and meaning.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A weather-and-plan rehearsal", whatToDo: "Repeat the model, then make one likely plan change.", whatMatters: "If plus present, then will helps listeners anticipate a practical result.", whatNext: "Use visible habitat details to describe where an animal can live." }, progressiveSupports: ["arabic-help", "transcript", "tip"] }),
  66: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Habitat cards support can/cannot and a relative clause before the learner makes an independent animal description.", selectedStages: ["encounter", "notice", "supported-practice", "meaningful-use"], firstView: { whatItIs: "An animals-and-habitats scene", whatToDo: "Explore the cards and complete one it is an animal that... sentence.", whatMatters: "A relative clause adds one useful fact without starting a new sentence.", whatNext: "Read how a community project moved from reason to result." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  67: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "The project update lets learners track purpose, sequence, and result across an informative text.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A community-project update", whatToDo: "Find why the project began and what changed as a result.", whatMatters: "Purpose and result explain why a sequence of actions matters.", whatNext: "Suggest one useful next change for the shared space." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  68: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A short proposal exchange lets suggestions develop collaboratively around a credible shared-space decision.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A useful-change conversation", whatToDo: "Identify the suggestion, then add one practical follow-up.", whatMatters: "Could and why not create options without sounding like orders.", whatNext: "Build a small family of words for protecting a place." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  69: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "One word family gives learners a compact route from a verb to its related noun and adjective.", selectedStages: ["notice", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A nature word-family workshop", whatToDo: "Complete three linked protect forms in a fictional sentence set.", whatMatters: "Word families make it easier to choose the form a sentence needs.", whatNext: "Describe a local problem clearly enough for someone to help." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  70: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A bounded fictional problem description joins quantity language, consequence, punctuation, and a possible solution safely.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A local-problem description", whatToDo: "Plan the problem, draft a short description, then check every sentence ends clearly.", whatMatters: "A reader can act on a problem only when its effect is clear.", whatNext: "Express a different opinion without dismissing another person." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  71: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A balanced model makes agreement and uncertainty hearable before a learner frames a respectful disagreement.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A respectful-disagreement rehearsal", whatToDo: "Repeat the balance phrases, then state one fictional opinion and one uncertainty.", whatMatters: "Agreeing with one point keeps disagreement constructive.", whatNext: "Retrieve the language tools that support a community decision." }, progressiveSupports: ["arabic-help", "transcript", "tip"] }),
  72: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "Selecting a tool for four different community purposes provides natural retrieval without repeating every activity type.", selectedStages: ["retrieval", "supported-practice", "evidence", "next-bridge"], firstView: { whatItIs: "A nature-and-community toolkit", whatToDo: "Match four language tools to their purpose, then write one complete sentence.", whatMatters: "Retrieval shows whether you can choose the right tool for a new situation.", whatNext: "Use the most useful tools in a short community proposal." }, progressiveSupports: ["word-support", "tip"] }),
  73: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A fictional proposal gives problem-solution structure an authentic audience and a clear recommendation.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A community-improvement proposal", whatToDo: "Name a fictional problem, explain its effect, and recommend a solution with a reason.", whatMatters: "A recommendation is stronger when it responds directly to a stated problem.", whatNext: "Explain a route and a rule aloud while checking your listener understands." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  74: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Combining a route, a rule, and a comprehension check produces a purposeful, connected spoken explanation.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A map-and-rule explanation", whatToDo: "Rehearse the route, state the rule, then ask the listener to confirm.", whatMatters: "A comprehension check prevents a clear explanation from becoming one-sided.", whatNext: "Bring description, obligation, condition, and proposal together in the checkpoint." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  75: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "Four connected fictional prompts provide evidence across description, rules, condition, and proposal without requiring private information.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A nature-and-community checkpoint", whatToDo: "Complete the four short parts, then check each sentence is complete.", whatMatters: "The evidence is a useful connection between language choice and community purpose.", whatNext: "Carry one practical problem-solving tool into the next A2 module." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
};

const A2_MODULE_6_EXPERIENCES: Record<number, LessonExperience> = {
  76: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "A compact choice lens lets learners add degree and support to an opinion before comparing full options.", selectedStages: ["orientation", "notice", "supported-practice", "next-bridge"], firstView: { whatItIs: "A supported-opinion workshop", whatToDo: "Choose one fictional option and add an adjective, an intensifier, and a reason.", whatMatters: "A reason makes an opinion useful to another person.", whatNext: "Read how stronger comparison words change two opportunities." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  77: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A short opportunity comparison makes much, a little, and far meaningful as precise reading evidence.", selectedStages: ["encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A two-opportunity reading", whatToDo: "Read for each advantage, then locate the comparison that makes it stronger.", whatMatters: "Comparison words show how large or small a difference is.", whatNext: "Use future language to plan one month ahead." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  78: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A bounded fictional plan separates an intention from a prediction without requiring personal disclosure.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A next-month plan", whatToDo: "Plan for a fictional learner, then separate what they intend from what you predict.", whatMatters: "Going to expresses an intention; will can express a prediction.", whatNext: "Turn a plan into a shared weekend suggestion." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  79: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A three-turn exchange makes suggestion, alternative, and agreement visible as a shared decision.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A weekend-plan conversation", whatToDo: "Follow the suggestion, offer an alternative, then identify the agreed plan.", whatMatters: "A good shared plan includes both an idea and a response.", whatNext: "Consider both sides of an option with contrast language." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  80: createLessonExperience({ archetype: "notice", density: "normal", archetypeRationale: "Contrast connectors give learners a deliberate way to balance a benefit against a limitation.", selectedStages: ["encounter", "notice", "supported-practice", "retrieval"], firstView: { whatItIs: "A pros-and-cons contrast lab", whatToDo: "Connect one advantage and one limitation with the right linker.", whatMatters: "Although and however keep both sides of a choice visible.", whatNext: "Hear and say preference language in a calm question-and-answer exchange." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  81: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Preference questions need a low-pressure spoken model before learners describe their own fictional choice.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A preference rehearsal", whatToDo: "Repeat the question chunks, then answer for a fictional learner.", whatMatters: "Would rather and prefer help you compare choices politely.", whatNext: "Read a longer decision for reasons and results." }, progressiveSupports: ["arabic-help", "transcript", "tip"] }),
  82: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A connected work-and-study decision supplies a believable chain from reasons to a final choice and its result.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A difficult-decision reading", whatToDo: "Find the choice, trace its reasons, and explain one result.", whatMatters: "A decision text is clearer when the reader can follow why one option won.", whatNext: "Make a back-up plan for a likely problem." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  83: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A practical plan B makes first-conditionals purposeful rather than a disconnected grammar exercise.", selectedStages: ["encounter", "notice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A plan-around-a-problem task", whatToDo: "Read the likely problem, then state its back-up plan.", whatMatters: "If links a real condition to the action you will take.", whatNext: "Compare price, value, and what someone can afford." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  84: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Visual value cards make an abstract choice vocabulary set easier to distinguish before a comparison.", selectedStages: ["encounter", "notice", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A price-and-value card set", whatToDo: "Explore three word cards, then compare two fictional options.", whatMatters: "A lower price does not always mean better value.", whatNext: "Use value language in supportive advice." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  85: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A short fictional advice note joins modal choice, a reason, a linker, and an appropriately supportive tone.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A supportive advice note", whatToDo: "Choose a safe study option for a fictional friend and link your reason to a calm suggestion.", whatMatters: "Should and could guide without giving orders.", whatNext: "Say the reason for a choice aloud with a useful example." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  86: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A concise spoken model gives for example and such as a clear rhythmic role in explanation.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A reason-and-example rehearsal", whatToDo: "Follow the pauses, then explain one fictional choice with an example.", whatMatters: "An example shows a listener what your reason looks like in practice.", whatNext: "Retrieve the module tools before a longer recommendation." }, progressiveSupports: ["arabic-help", "transcript", "tip"] }),
  87: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "A selective toolkit lets learners retrieve the language function a new choice prompt actually needs.", selectedStages: ["retrieval", "supported-practice", "evidence", "next-bridge"], firstView: { whatItIs: "A choice-language toolkit", whatToDo: "Match the prompt to its most useful language tool, then write one complete sentence.", whatMatters: "Independent language use begins with choosing the right tool, not using every tool.", whatNext: "Use the strongest tools in a balanced recommendation." }, progressiveSupports: ["word-support", "tip"] }),
  88: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A balanced recommendation creates a purposeful paragraph in which comparison and contrast lead to a clear conclusion.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A balanced recommendation", whatToDo: "Compare two fictional workshops, acknowledge one limitation, and make a final recommendation.", whatMatters: "A strong recommendation is clear about both its reason and its limit.", whatNext: "Negotiate a plan when another person has a different priority." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  89: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A short negotiation teaches learners to soften a disagreement and turn alternatives into an agreement.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A shared-plan negotiation", whatToDo: "Identify the soft disagreement, propose an alternative, and finish with the agreement.", whatMatters: "Softening language protects the relationship while the plan changes.", whatNext: "Bring comparison, planning, and recommendation together in the checkpoint." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  90: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "Three linked fictional tasks collect evidence of comparison, future planning, contrast, and recommendation without a universal lesson route.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A choices-and-plans checkpoint", whatToDo: "Complete the three short fictional decisions and check your connector choices.", whatMatters: "The goal is to make a reasoned choice that another reader can follow.", whatNext: "Carry one decision-making pattern into communication-and-technology topics." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
};

const A2_MODULE_7_EXPERIENCES: Record<number, LessonExperience> = {
  91: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "A short message-repair task lets learners see sentence boundaries as a reader's support, not as an abstract rule.", selectedStages: ["orientation", "notice", "supported-practice", "next-bridge"], firstView: { whatItIs: "A clear-message repair", whatToDo: "Find the sentence starts and ends, then revise the short course message.", whatMatters: "Capital letters and full stops help a reader follow one idea at a time.", whatNext: "Use everyday device-action words in a visual card set." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  92: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Visual device cards make useful phrasal verbs concrete before learners see them in a message or instruction.", selectedStages: ["encounter", "notice", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A device-action card set", whatToDo: "Explore the three cards, say each action, then give one fictional instruction.", whatMatters: "A phrasal verb is more useful when learners can link it to a visible action.", whatNext: "Use clear technology language in a purposeful email." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  93: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A bounded fictional email turns opening, request, and closing into a real communicative structure without asking for private contact details.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A useful-email task", whatToDo: "Write a short fictional request with a greeting, a clear purpose, and a calm closing.", whatMatters: "An email is easier to answer when its request is explicit and polite.", whatNext: "Use present-continuous language to keep a phone call clear." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  94: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A short disrupted-call exchange gives present continuous a communicative job: explaining what is happening now.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A call-clarity exchange", whatToDo: "Follow the problem, listen for the current action, then identify the solution.", whatMatters: "Clear questions prevent a small technical problem from becoming a misunderstanding.", whatNext: "Give short, sequenced reset instructions aloud." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  95: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Short reset steps reward deliberate pauses and sequence words before a learner tries a more complex support conversation.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A reset-step rehearsal", whatToDo: "Repeat the short instruction chunks, keeping the order clear for a fictional user.", whatMatters: "A listener can only act on an instruction when the order is easy to hear.", whatNext: "Scan a notice for the date, condition, and necessary action." }, progressiveSupports: ["arabic-help", "transcript", "tip"] }),
  96: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A concise notice develops scanning for action-critical details rather than reading every word at the same speed.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "An online-notice scan", whatToDo: "Find the date, the condition, and the action a booked learner needs to take.", whatMatters: "Digital notices often hide the most important action in one short condition.", whatNext: "Say a repeated message another way without changing its meaning." }, progressiveSupports: ["arabic-help", "word-support", "worked-example"] }),
  97: createLessonExperience({ archetype: "notice", density: "normal", archetypeRationale: "A micro-paraphrase task makes synonym choice accountable to meaning, not just to swapping a word.", selectedStages: ["encounter", "notice", "supported-practice", "retrieval"], firstView: { whatItIs: "A paraphrase check", whatToDo: "Replace one repeated word, then check whether the reader would understand the same message.", whatMatters: "A synonym fits only when it keeps the intended meaning in this sentence.", whatNext: "Repair a small misunderstanding with a polite correction." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  98: createLessonExperience({ archetype: "interaction", density: "light", archetypeRationale: "One carefully modelled correction shows learners how acknowledgement and precise repair protect a practical conversation.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A polite-correction exchange", whatToDo: "Find the incorrect detail, then practise the gentle correction that fixes it.", whatMatters: "Sorry, I meant is a useful way to correct information without blaming the listener.", whatNext: "Read simple safety guidance for a digital choice." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  99: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Safety guidance gives must, should, and conditional warnings an immediate and responsible purpose in a short text.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A digital-safety guide", whatToDo: "Separate the rule, the advice, and the condition before answering the checks.", whatMatters: "A safe response begins with noticing what information should remain private.", whatNext: "Turn safe advice into concise steps for a fictional friend." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  100: createLessonExperience({ archetype: "writing", density: "normal", archetypeRationale: "Numbered instructions reward concise imperatives and a specific safety reminder rather than long, unfocused explanation.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A concise-instructions task", whatToDo: "Write four ordered steps that help a fictional friend join an online class safely.", whatMatters: "Useful instructions tell a reader what to do next and what not to share.", whatNext: "Hear common request and plan phrases as connected speech chunks." }, progressiveSupports: ["arabic-help", "worked-example", "word-support"] }),
  101: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "Two high-frequency chunks introduce connection and weak forms without asking a learner to manage a long speaking performance.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "retrieval"], firstView: { whatItIs: "A connected-speech rehearsal", whatToDo: "Listen for the linked chunks, copy the rhythm, then say each request slowly and clearly.", whatMatters: "Connected speech can sound smoother while the key words remain clear.", whatNext: "Retrieve the module tool that fits each short communication prompt." }, progressiveSupports: ["arabic-help", "transcript", "tip"] }),
  102: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "A selective retrieval toolkit asks learners to choose a language function before producing a sentence, avoiding an indiscriminate review list.", selectedStages: ["retrieval", "supported-practice", "evidence", "next-bridge"], firstView: { whatItIs: "A communication toolkit", whatToDo: "Match each fictional message problem to its most useful language tool, then write one example.", whatMatters: "Good communication depends on choosing the right tool, not using every word you know.", whatNext: "Apply several tools across one complete digital-support chat." }, progressiveSupports: ["word-support", "tip"] }),
  103: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "A complete support-chat route combines opening, diagnosis, clarification, and closure in a realistic but entirely fictional learner setting.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use", "evidence"], firstView: { whatItIs: "A complete support chat", whatToDo: "Trace how each turn moves from the problem to a safe, sequenced next step.", whatMatters: "A helpful support conversation asks before it assumes and confirms the next action.", whatNext: "Edit a repeated note until every sentence earns its place." }, progressiveSupports: ["arabic-help", "transcript", "worked-example"] }),
  104: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A constrained clarity rewrite asks learners to preserve key information while making a message more economical and readable.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A clarity-rewrite task", whatToDo: "Keep the important course information, combine what belongs together, and remove the repeated detail.", whatMatters: "Clear writing respects the reader's time without losing the action they need to take.", whatNext: "Show the module's communication tools in a compact checkpoint." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
  105: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "Three linked fictional tasks gather evidence of message clarity, correction, sequencing, and safety without presenting one universal lesson sequence.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A communication-and-technology checkpoint", whatToDo: "Complete each short task, then reread for a clear message, a polite repair, and a safe next step.", whatMatters: "The goal is practical clarity: another person should know what happened and what to do.", whatNext: "Carry one clear request and one safe instruction into food, shopping, and service conversations." }, progressiveSupports: ["arabic-help", "worked-example", "tip"] }),
};

function lessonFromBlueprint(blueprint: ImmersiveLessonBlueprint, module: ReturnType<typeof getProgressiveImmersiveModules>[number]): LessonDefinition {
  const words = vocabularyForBlueprint(blueprint);
  const generatedLesson = enrichLesson({
    level: "A2",
    lessonNumber: blueprint.lessonNumber,
    moduleNumber: blueprint.moduleNumber,
    title: blueprint.title,
    titleArabic: blueprint.titleArabic,
    words,
    grammar: grammarForBlueprint(blueprint),
    learningPlan: {
      outcome: {
        canDo: blueprint.canDo,
        canDoArabic: blueprint.canDoArabic,
        scenario: module.overview,
        scenarioArabic: module.overviewArabic,
      },
      steps: A2_STEPS,
      retrieval: blueprint.exposurePlan.slice(0, 3).map((exposure) => ({
        sourceLevel: "A1" as const,
        language: exposure.task,
        prompt: `Retrieve one phrase, then use it for the ${blueprint.title} situation.`,
        purpose: exposure.taskArabic,
      })),
      englishFirst: true,
      studio: "A2 Life Lab",
    },
    lexicalNetworks: [{
      id: `a2-network-${blueprint.lessonNumber}`,
      theme: module.title,
      themeArabic: module.titleArabic,
      anchor: blueprint.vocabularyAnchors[0] ?? blueprint.title,
      wordFamilies: [],
      relatedWords: words.slice(0, 6).map((word) => word.word),
      chunks: ["Could you explain that, please?", "I think this is useful because…", "What happened after that?"],
      collocations: blueprint.vocabularyAnchors.slice(0, 3).map((word) => `use ${word} in context`),
      register: "mixed",
      priorLevelLinks: ["A1 greetings", "A1 everyday questions", "A1 basic time and place language"],
      learningNote: blueprint.mentorPurpose,
      learningNoteArabic: blueprint.mentorPurposeArabic,
    }],
    practiceBrief: {
      readingBrief: `Read a connected A2 text about ${module.title.toLocaleLowerCase()}, identify the main purpose, and notice ${blueprint.grammarFocus}.`,
      writingPrompt: `Write 80–100 words for the ${blueprint.title} situation. Show that you can ${blueprint.canDo.replace(/^I can /, "").replace(/\.$/, "")}. Use at least three lesson words naturally, connect your ideas, and revise punctuation before checking your work.`,
    },
    domainFocus: module.overview,
    domainFocusArabic: module.overviewArabic,
    beginnerScaffold: blueprint.beginnerExplanation,
    beginnerScaffoldArabic: blueprint.beginnerExplanationArabic,
    lessonType: blueprint.type,
  });

  const authoredActivities = A2_MODULE_1_AUTHORED_ACTIVITIES[blueprint.lessonNumber]
    ?? A2_MODULE_2_AUTHORED_ACTIVITIES[blueprint.lessonNumber]
    ?? A2_MODULE_3_AUTHORED_ACTIVITIES[blueprint.lessonNumber]
    ?? A2_MODULE_4_AUTHORED_ACTIVITIES[blueprint.lessonNumber]
    ?? A2_MODULE_5_AUTHORED_ACTIVITIES[blueprint.lessonNumber]
    ?? A2_MODULE_6_AUTHORED_ACTIVITIES[blueprint.lessonNumber]
    ?? A2_MODULE_7_AUTHORED_ACTIVITIES[blueprint.lessonNumber];
  const experience = A2_MODULE_1_EXPERIENCES[blueprint.lessonNumber]
    ?? A2_MODULE_2_EXPERIENCES[blueprint.lessonNumber]
    ?? A2_MODULE_3_EXPERIENCES[blueprint.lessonNumber]
    ?? A2_MODULE_4_EXPERIENCES[blueprint.lessonNumber]
    ?? A2_MODULE_5_EXPERIENCES[blueprint.lessonNumber]
    ?? A2_MODULE_6_EXPERIENCES[blueprint.lessonNumber]
    ?? A2_MODULE_7_EXPERIENCES[blueprint.lessonNumber];
  return authoredActivities || experience
    ? { ...generatedLesson, activities: authoredActivities ?? generatedLesson.activities, experience: experience ?? generatedLesson.experience }
    : generatedLesson;
}

const A2_MODULES = getProgressiveImmersiveModules("A2");

export const A2_LESSONS: LessonDefinition[] = A2_MODULES.flatMap((module) =>
  module.lessonBlueprints.map((blueprint, index) => lessonFromBlueprint({
    ...blueprint,
    lessonNumber: ((module.moduleNumber - 1) * 15) + index + 1,
  }, module)),
);

export const A2_VOCABULARY = A2_LESSONS.flatMap((lesson) => lesson.words);
export const A2_GRAMMAR = A2_LESSONS.map((lesson) => lesson.grammar);

export const A2_COURSE: CourseDefinition = {
  level: "A2",
  title: "A2: Connected English for everyday independence",
  titleArabic: "A2: إنجليزية مترابطة للاستقلالية اليومية",
  totalLessons: 135,
  lessonsPerModule: 15,
  estimatedMinutes: 135 * 55,
  lessons: A2_LESSONS,
  modules: buildModuleDefinitions("A2", A2_LESSONS),
};

export function getA2Lesson(lessonNumber: number) {
  return A2_LESSONS.find((lesson) => lesson.lessonNumber === lessonNumber);
}
