import type { LessonActivity } from "./types";

const scene = (label: string, tint = "#5a4969") => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420"><rect width="720" height="420" rx="30" fill="${tint}"/><rect x="116" y="108" width="488" height="204" rx="18" fill="#f8f3ea" opacity=".96"/><path d="M206 334h308" stroke="#d9b46e" stroke-width="18" stroke-linecap="round"/><circle cx="192" cy="210" r="40" fill="#d9b46e"/><path d="M272 176h242M272 220h184M272 264h220" stroke="#5a4969" stroke-width="18" stroke-linecap="round"/><text x="360" y="74" text-anchor="middle" fill="#fff" font-family="Arial" font-size="30" font-weight="700">${label}</text></svg>`)}`;

const visualWords = (lesson: number, items: Array<[string, string, string]>) => items.map(([word, arabic, example], index) => ({
  id: `b1-m8-${lesson}-visual-${index + 1}`,
  word,
  arabic,
  pronunciation: word,
  exampleEN: example,
  exampleAR: "استخدم الكلمة لوصف تجربة أو مجتمع أو وجهة نظر باحترام ودون تعميم.",
  imageUrl: scene(word, index % 2 ? "#765f86" : "#5a4969"),
  altText: `Illustrated Culture and Identity concept card for ${word}`,
  category: "Culture and identity",
  interactionHint: "Read the example, then say whether the word describes belonging, a practice, a perspective, or respectful participation.",
}));

export const B1_MODULE_8_AUTHORED_ACTIVITIES: Record<number, readonly LessonActivity[]> = {
  106: [
    { id: "b1-m8-106-map", kind: "visual-vocabulary", title: "Map culture, identity, and belonging", titleArabic: "ارسم خريطة للثقافة والهوية والانتماء", objective: "Separate a personal experience, a shared practice, a community, and an assumption without treating any group as identical.", objectiveArabic: "ميّز بين تجربة شخصية وممارسة مشتركة ومجتمع وافتراض دون معاملة أي مجموعة وكأنها متطابقة.", stage: "introduction", estimatedMinutes: 13, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(106, [["belonging", "الانتماء", "A sense of belonging can grow through small, repeated acts of welcome."], ["heritage", "التراث", "Heritage can include stories, languages, skills, and places that people value."], ["perspective", "وجهة نظر", "A perspective is shaped by experience, but it does not represent everyone."]]) },
    { id: "b1-m8-106-observe", kind: "speaking", title: "Describe a shared space carefully", titleArabic: "صف مساحة مشتركة بعناية", objective: "Describe a fictional or familiar shared space using one observation and one careful question rather than a cultural label.", objectiveArabic: "صف مساحة مشتركة خيالية أو مألوفة باستخدام ملاحظة واحدة وسؤال حذر بدلاً من تصنيف ثقافي.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example"], speakingLines: [{ id: "model", speaker: "Model", text: "At the community library, people use several languages on the noticeboard. I wonder which languages would help more visitors feel included.", textArabic: "في مكتبة المجتمع يستخدم الناس عدة لغات في لوحة الإعلانات. أتساءل أي اللغات قد تساعد مزيداً من الزوار على الشعور بالاندماج." }, { id: "you", speaker: "You", text: "Describe one detail you notice in a shared space and ask one question about access or welcome.", textArabic: "صف تفصيلاً واحداً تلاحظه في مساحة مشتركة واسأل سؤالاً واحداً عن الوصول أو الترحيب." }] },
  ],
  107: [
    { id: "b1-m8-107-language", kind: "standard", title: "Use careful language about groups", titleArabic: "استخدم لغة حذرة عن المجموعات", objective: "Use some, many, a few, and individual to make a statement more accurate and less absolute.", objectiveArabic: "استخدم some وmany وa few وindividual لجعل العبارة أدق وأقل إطلاقاً.", stage: "explanation", estimatedMinutes: 12, semantic: "grammar", progressiveSupports: ["worked-example", "tip"], sentencePatterns: ["Some families in the area prefer …", "Many visitors said …, although not everyone agreed.", "One individual experience cannot represent …"] },
    { id: "b1-m8-107-rewrite", kind: "writing", title: "Rewrite an overgeneralised notice", titleArabic: "أعد كتابة إعلان يعمم كثيراً", objective: "Revise a short public notice so it invites participation without making claims about every member of a group.", objectiveArabic: "راجع إعلاناً عاماً قصيراً ليشجع المشاركة دون ادعاء معرفة كل أفراد مجموعة ما.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Rewrite this in 60–80 words: ‘This neighbourhood does not care about local history.’ State what the writer actually observed, add one limitation, and invite a response from people with different experiences.", writingPromptArabic: "أعد كتابة هذا في 60–80 كلمة: «هذا الحي لا يهتم بالتاريخ المحلي». اذكر ما لاحظه الكاتب فعلاً وأضف قيداً واحداً وادعُ إلى رد من أشخاص لهم تجارب مختلفة.", suggestedVocabulary: ["some residents", "observation", "may", "however", "invite"], sentencePatterns: ["One observation is …", "This may not reflect …", "We would welcome views from …"] },
  ],
  108: [
    { id: "b1-m8-108-pattern", kind: "reading", title: "Notice voice and viewpoint", titleArabic: "لاحظ الصوت ووجهة النظر", objective: "Identify when a short account describes one person’s experience and when it makes a broader, supported claim.", objectiveArabic: "حدّد متى يصف النص القصير تجربة شخص واحد ومتى يقدم ادعاءً أوسع ومدعوماً.", stage: "explanation", estimatedMinutes: 14, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A youth arts group collected short memories about a market square before its renovation. One volunteer wrote that the square reminded her of weekend visits with her grandfather. Other contributors described it as a meeting place, a route to work, or a noisy area they avoided. The group did not claim that one memory explained the square for everyone. Instead, it displayed several accounts beside a map of the proposed changes.", readingTextArabic: "نص قصير يبين الفرق بين الذكرى الفردية والوصف الأوسع المدعوم بأصوات متعددة.", readingChecks: [{ id: "detail", type: "detail", prompt: "What did the group display beside the proposed changes?", promptArabic: "ماذا عرضت المجموعة بجانب التغييرات المقترحة؟", choices: ["Several accounts and a map.", "One official opinion only.", "A list of market prices."], answer: "Several accounts and a map." }, { id: "inference", type: "inference", prompt: "Why did the group include several accounts?", promptArabic: "لماذا أدرجت المجموعة عدة روايات؟", choices: ["One memory could not explain the square for everyone.", "The square had no history.", "Visitors refused to use a map."], answer: "One memory could not explain the square for everyone." }] },
  ],
  109: [
    { id: "b1-m8-109-dialogue", kind: "interaction", title: "Ask about a meaningful practice", titleArabic: "اسأل عن ممارسة ذات معنى", objective: "Ask a respectful follow-up question about a practice someone chooses to share, without demanding a personal explanation.", objectiveArabic: "اطرح سؤال متابعة محترماً عن ممارسة يختار شخص مشاركتها دون طلب تفسير شخصي منه.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "colleague", speaker: "Colleague", text: "Our team meeting starts five minutes later today because I need a short quiet moment first.", textArabic: "سيبدأ اجتماع فريقنا بعد خمس دقائق اليوم لأنني أحتاج إلى لحظة هادئة قصيرة أولاً.", purpose: "Share a boundary without inviting personal investigation." }, { id: "you", speaker: "You", text: "Thank you for letting us know. Would it help if we adjusted the agenda as well, or is starting a little later enough?", textArabic: "شكراً لإخبارنا. هل سيساعد تعديل جدول الأعمال أيضاً، أم أن البدء متأخرين قليلاً يكفي؟", purpose: "Offer practical support without requesting private detail." }] },
  ],
  110: [
    { id: "b1-m8-110-respond", kind: "speaking", title: "Respond to an unfamiliar custom", titleArabic: "استجب لعُرف غير مألوف", objective: "Show curiosity, state what you understand, and ask a practical question without treating unfamiliarity as a problem.", objectiveArabic: "أظهر الفضول واذكر ما تفهمه واسأل سؤالاً عملياً دون اعتبار عدم الألفة مشكلة.", stage: "guided-practice", estimatedMinutes: 11, semantic: "activity", progressiveSupports: ["transcript", "word-support"], speakingLines: [{ id: "speaker", speaker: "Host", text: "At the welcome event, visitors can add a greeting in any language to the shared wall if they wish.", textArabic: "في فعالية الترحيب يمكن للزوار إضافة تحية بأي لغة إلى الجدار المشترك إذا أرادوا." }, { id: "you", speaker: "You", text: "I understand that people can choose a language that matters to them. How will the wall remain easy to read for new visitors?", textArabic: "أفهم أن الناس يمكنهم اختيار لغة مهمة لهم. كيف سيبقى الجدار سهل القراءة للزوار الجدد؟" }] },
  ],
  111: [
    { id: "b1-m8-111-feature", kind: "reading", title: "Read a community-history feature", titleArabic: "اقرأ مقالة عن تاريخ المجتمع", objective: "Trace the source, voices, and limitation in a short feature about a community place.", objectiveArabic: "تتبّع المصدر والأصوات والقيد في مقالة قصيرة عن مكان مجتمعي.", stage: "explanation", estimatedMinutes: 16, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A local museum planned a small exhibition about a former railway workshop. Its volunteers used photographs from the town archive, interviews with two retired workers, and a notice asking residents to lend copies of family pictures. The opening panel says that the exhibition is a starting point, not a complete history. It also notes that the project has few records from workers who moved away before the archive began collecting interviews.", readingTextArabic: "مقال قصير يوضح استخدام مصادر متعددة مع الاعتراف بالأصوات والسجلات الغائبة.", readingChecks: [{ id: "source", type: "detail", prompt: "Which source did the volunteers use besides interviews?", promptArabic: "أي مصدر استخدمه المتطوعون إضافة إلى المقابلات؟", choices: ["Photographs from the town archive.", "A national television programme.", "A single online comment."], answer: "Photographs from the town archive." }, { id: "limitation", type: "inference", prompt: "Why does the opening panel call the exhibition a starting point?", promptArabic: "لماذا تصف اللوحة الافتتاحية المعرض بأنه نقطة بداية؟", choices: ["Some voices and records are still missing.", "The museum has no photographs.", "The workshop never existed."], answer: "Some voices and records are still missing." }] },
  ],
  112: [
    { id: "b1-m8-112-paragraph", kind: "writing", title: "Write about belonging without a stereotype", titleArabic: "اكتب عن الانتماء دون صورة نمطية", objective: "Write a connected paragraph about a fictional or chosen place of belonging, using one specific detail and one qualifying sentence.", objectiveArabic: "اكتب فقرة مترابطة عن مكان انتماء خيالي أو تختاره مستخدماً تفصيلاً محدداً وجملة فيها تحفّظ.", stage: "independent-practice", estimatedMinutes: 20, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 130–160 words about a place, group, activity, or language that can create belonging. You may use a fictional example. Describe one concrete detail, explain why it matters to one person or group, and add a sentence that avoids claiming the experience is the same for everyone.", writingPromptArabic: "اكتب 130–160 كلمة عن مكان أو مجموعة أو نشاط أو لغة يمكن أن تخلق شعوراً بالانتماء. يمكنك استخدام مثال خيالي. صف تفصيلاً ملموساً واشرح لماذا يهم شخصاً أو مجموعة وأضف جملة تتجنب الادعاء بأن التجربة متشابهة للجميع.", suggestedVocabulary: ["belonging", "shared", "individual", "however", "perspective"], sentencePatterns: ["For one person, … may …", "A specific detail is …", "However, this experience will not be the same for …"] },
  ],
  113: [
    { id: "b1-m8-113-compare", kind: "interaction", title: "Compare two welcome-event plans", titleArabic: "قارن بين خطتين لفعالية ترحيب", objective: "Compare two event plans using access, choice, clarity, and representation as criteria.", objectiveArabic: "قارن بين خطتين لفعالية ترحيب باستخدام الوصول والاختيار والوضوح والتمثيل كمعايير.", stage: "real-context", estimatedMinutes: 15, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "plan-a", speaker: "Plan A", text: "Invite one well-known speaker to explain the area’s traditions to all new residents.", textArabic: "ادعُ متحدثاً معروفاً واحداً لشرح تقاليد المنطقة لجميع السكان الجدد.", purpose: "Offer a simple but narrow plan." }, { id: "plan-b", speaker: "Plan B", text: "Offer short optional stations where local groups and visitors can share practical information, stories, or activities.", textArabic: "قدّم محطات اختيارية قصيرة حيث يمكن للمجموعات المحلية والزوار مشاركة معلومات أو قصص أو أنشطة عملية.", purpose: "Offer a wider, participatory plan." }, { id: "you", speaker: "You", text: "Plan … may be clearer for …, whereas Plan … gives more choice. I would combine … by …", textArabic: "قد تكون الخطة … أوضح لـ …، بينما تمنح الخطة … اختياراً أكبر. سأجمع بين … من خلال …", purpose: "Make a qualified recommendation using explicit criteria." }] },
  ],
  114: [
    { id: "b1-m8-114-repair", kind: "interaction", title: "Repair an assumption about identity", titleArabic: "أصلح افتراضاً عن الهوية", objective: "Acknowledge an assumption, correct it without defensiveness, and return to the shared practical question.", objectiveArabic: "اعترف بافتراض وصححه دون دفاعية ثم عُد إلى السؤال العملي المشترك.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["worked-example", "transcript"], interactionTurns: [{ id: "assumption", speaker: "Volunteer", text: "You should lead the language table because you come from that community.", textArabic: "ينبغي أن تقود طاولة اللغة لأنك من ذلك المجتمع.", purpose: "Present an identity-based assumption about responsibility." }, { id: "you", speaker: "You", text: "I appreciate that you want the table to be welcoming. I do not speak for everyone in that community, but I can help us ask who would like to contribute and what support they need.", textArabic: "أقدّر رغبتك في أن تكون الطاولة مرحبة. أنا لا أتحدث باسم الجميع في ذلك المجتمع، لكن يمكنني مساعدتنا في السؤال عمّن يرغب بالمساهمة وما الدعم الذي يحتاجه.", purpose: "Correct the assumption and reframe participation fairly." }] },
  ],
  115: [
    { id: "b1-m8-115-purpose", kind: "speaking", title: "Give an inclusive welcome", titleArabic: "قدّم ترحيباً شاملاً", objective: "Deliver a short welcome that explains choice, access, and how people can contribute without pressuring anyone to share personal information.", objectiveArabic: "قدّم ترحيباً قصيراً يشرح الاختيار والوصول وكيف يمكن للناس المساهمة دون الضغط على أحد لمشاركة معلومات شخصية.", stage: "independent-practice", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [{ id: "frame", speaker: "Framework", text: "Welcome to …; you can choose to …; if you need …, please …; you are welcome to contribute by … or simply listen.", textArabic: "مرحباً بكم في …؛ يمكنكم اختيار أن …؛ إذا احتجتم إلى …، يرجى …؛ يمكنكم المساهمة عبر … أو الاستماع فقط." }, { id: "you", speaker: "You", text: "Give a one-minute welcome for a fictional community event. Include one access detail and one voluntary way to participate.", textArabic: "قدّم ترحيباً لمدة دقيقة لفعالية مجتمعية خيالية. ضمّن تفصيلاً واحداً عن الوصول وطريقة مشاركة اختيارية واحدة." }] },
  ],
  116: [
    { id: "b1-m8-116-network", kind: "review", title: "Review the belonging network", titleArabic: "راجع شبكة الانتماء", objective: "Retrieve language by linking perspective, belonging, heritage, participation, and assumption.", objectiveArabic: "استرجع اللغة بربط وجهة النظر والانتماء والتراث والمشاركة والافتراض.", stage: "review", estimatedMinutes: 12, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], sentencePatterns: ["One perspective is …", "A shared place can …", "It would be inaccurate to assume …"] },
    { id: "b1-m8-116-transfer", kind: "speaking", title: "Use three words in a new context", titleArabic: "استخدم ثلاث كلمات في سياق جديد", objective: "Apply retrieved language to a new welcome situation instead of reciting definitions.", objectiveArabic: "طبّق اللغة المسترجعة على موقف ترحيب جديد بدلاً من ترديد التعريفات.", stage: "independent-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["tip"], speakingLines: [{ id: "prompt", speaker: "Prompt", text: "A sports club wants to welcome new members who have different levels of confidence. Use belonging, perspective, and participation to describe one response.", textArabic: "يريد نادٍ رياضي الترحيب بأعضاء جدد لديهم مستويات ثقة مختلفة. استخدم belonging وperspective وparticipation لوصف استجابة واحدة." }] },
  ],
  117: [
    { id: "b1-m8-117-source", kind: "reading", title: "Interpret visitor feedback carefully", titleArabic: "فسّر ملاحظات الزوار بعناية", objective: "Separate a feedback pattern, a limitation, and a reasonable next step in a short visitor survey.", objectiveArabic: "ميّز بين نمط في الملاحظات وقيد وخطوة تالية معقولة في مسح قصير للزوار.", stage: "explanation", estimatedMinutes: 15, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A community festival asked 92 visitors which parts of the event helped them feel welcome. Many mentioned clear signs, a quiet seating area, and volunteers who explained activities without assuming prior knowledge. The survey was completed only by people who chose to respond, and it did not include people who left early. The organisers proposed testing clearer signs and a second quiet area at the next event, then asking a wider range of visitors for feedback.", readingTextArabic: "مصدر قصير يوضح استخدام ملاحظات الزوار مع الانتباه إلى من لم يشملهم المسح.", readingChecks: [{ id: "pattern", type: "detail", prompt: "Which feature did many respondents mention?", promptArabic: "أي ميزة ذكرها كثير من المشاركين؟", choices: ["Clear signs.", "Longer speeches.", "More expensive tickets."], answer: "Clear signs." }, { id: "inference", type: "inference", prompt: "Why do the organisers want more feedback after the next event?", promptArabic: "لماذا يريد المنظمون مزيداً من الملاحظات بعد الفعالية التالية؟", choices: ["The first survey did not include every type of visitor.", "The festival has no volunteers.", "Clear signs cannot be tested."], answer: "The first survey did not include every type of visitor." }] },
  ],
  118: [
    { id: "b1-m8-118-draft", kind: "writing", title: "Draft and revise an inclusive invitation", titleArabic: "صغ وراجع دعوة شاملة", objective: "Write a concise invitation that explains access and choice, then revise one sentence that assumes too much about the audience.", objectiveArabic: "اكتب دعوة موجزة تشرح الوصول والاختيار ثم راجع جملة تفترض الكثير عن الجمهور.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 120–150 words inviting people to a fictional local event. Explain what will happen, name one access or language support, state that participation is optional, and revise one sentence that could make readers feel excluded.", writingPromptArabic: "اكتب 120–150 كلمة تدعو فيها الناس إلى فعالية محلية خيالية. اشرح ما سيحدث واذكر دعماً واحداً للوصول أو اللغة وبيّن أن المشاركة اختيارية وراجع جملة قد تجعل القراء يشعرون بالإقصاء.", suggestedVocabulary: ["welcome", "accessible", "optional", "contribute", "perspective"], sentencePatterns: ["You are welcome to …", "If you would like support with …", "Participation can include …"] },
  ],
  119: [
    { id: "b1-m8-119-task", kind: "interaction", title: "Plan a shared event under constraints", titleArabic: "خطط لفعالية مشتركة ضمن قيود", objective: "Choose a feasible first version of an event, explain one trade-off, and set a question for later review.", objectiveArabic: "اختر نسخة أولى قابلة للتنفيذ من فعالية واشرح مقايضة واحدة وحدد سؤالاً للمراجعة لاحقاً.", stage: "real-context", estimatedMinutes: 16, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Brief", text: "A library has a small budget, one accessible room, limited volunteer time, and requests for a multilingual welcome event. Some people want a large programme; others prefer a short event with clearer access information and time for conversation.", textArabic: "لدى مكتبة ميزانية صغيرة وغرفة واحدة مهيأة ووقت محدود للمتطوعين وطلبات لفعالية ترحيب متعددة اللغات. يريد بعض الناس برنامجاً كبيراً بينما يفضّل آخرون فعالية قصيرة بمعلومات وصول أوضح ووقت للمحادثة.", purpose: "Present real constraints without a single correct solution." }, { id: "you", speaker: "You", text: "I would begin with … because … . This would not provide … immediately, but it would allow us to learn … . We should ask participants …", textArabic: "سأبدأ بـ … لأن … . لن يوفّر هذا … فوراً، لكنه سيسمح لنا بتعلّم … . ينبغي أن نسأل المشاركين …", purpose: "Make a bounded choice with a review question." }] },
  ],
  120: [
    { id: "b1-m8-120-checkpoint", kind: "assessment", title: "Culture and identity checkpoint", titleArabic: "نقطة تحقق: الثقافة والهوية", objective: "Use careful group language, source awareness, and an inclusive recommendation in a new community situation.", objectiveArabic: "استخدم لغة حذرة عن المجموعات ووعياً بالمصادر وتوصية شاملة في موقف مجتمعي جديد.", stage: "assessment", estimatedMinutes: 22, semantic: "assessment", progressiveSupports: ["tip"], writingPrompt: "A community centre wants to improve its welcome for people with different languages and experiences. Write 150–180 words recommending a first action. Use one limited piece of feedback, avoid speaking for every group, acknowledge one constraint, and end with a respectful invitation to contribute.", writingPromptArabic: "يريد مركز مجتمعي تحسين ترحيبه بأشخاص لهم لغات وتجارب مختلفة. اكتب 150–180 كلمة توصي فيها بعمل أول. استخدم ملاحظة محدودة واحدة وتجنب التحدث باسم كل مجموعة واعترف بقيد واحد وأنهِ بدعوة محترمة للمساهمة.", suggestedVocabulary: ["belonging", "perspective", "accessible", "feedback", "although", "participate"], sentencePatterns: ["The feedback suggests …", "A sensible first step would be …", "Although …, visitors could …"] },
  ],
};
