import type { LessonActivity } from "./types";

const scene = (label: string, tint = "#475b7a") => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420"><rect width="720" height="420" rx="30" fill="${tint}"/><rect x="114" y="112" width="492" height="196" rx="18" fill="#f4f0e7" opacity=".95"/><path d="M220 336h280" stroke="#d7b968" stroke-width="18" stroke-linecap="round"/><circle cx="190" cy="210" r="38" fill="#d7b968"/><path d="M260 180h260M260 220h198M260 260h228" stroke="#475b7a" stroke-width="18" stroke-linecap="round"/><text x="360" y="74" text-anchor="middle" fill="#fff" font-family="Arial" font-size="30" font-weight="700">${label}</text></svg>`)}`;

const visualWords = (lesson: number, items: Array<[string, string, string]>) => items.map(([word, arabic, example], index) => ({
  id: `b1-m6-${lesson}-visual-${index + 1}`,
  word,
  arabic,
  pronunciation: word,
  exampleEN: example,
  exampleAR: "استخدم الكلمة لوصف رسالة أو مصدر أو قرار رقمي بدقة واحترام.",
  imageUrl: scene(word, index % 2 ? "#536d91" : "#475b7a"),
  altText: `Illustrated Media and Digital Life concept card for ${word}`,
  category: "Media and digital life",
  interactionHint: "Read the example, then identify whether the word describes a source, a claim, a setting, or a response.",
}));

export const B1_MODULE_6_AUTHORED_ACTIVITIES: Record<number, readonly LessonActivity[]> = {
  76: [
    { id: "b1-m6-76-map", kind: "visual-vocabulary", title: "Map your media environment", titleArabic: "ارسم خريطة لبيئتك الإعلامية", objective: "Separate a platform, a source, a claim, and a response in a connected digital-life example.", objectiveArabic: "ميّز بين منصة ومصدر وادعاء واستجابة في مثال مترابط من الحياة الرقمية.", stage: "introduction", estimatedMinutes: 12, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(76, [["feed", "خلاصة المحتوى", "Her feed mixes local news, friends’ updates, and promotional posts."], ["source", "مصدر", "A source should be identifiable before you repeat its claim."], ["notification", "إشعار", "A notification can interrupt a task even when it is not urgent."]]) },
    { id: "b1-m6-76-sort", kind: "speaking", title: "Name one digital habit and its effect", titleArabic: "اذكر عادة رقمية واحدة وأثرها", objective: "Describe one ordinary media habit and one effect without judging yourself or others.", objectiveArabic: "صف عادة إعلامية يومية وأثراً واحداً دون الحكم على نفسك أو الآخرين.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example"], speakingLines: [{ id: "model", speaker: "Model", text: "I check my news feed during breakfast, which helps me feel informed but sometimes makes me late.", textArabic: "أتفقد خلاصة الأخبار أثناء الإفطار، وهذا يساعدني على الشعور بالاطلاع لكنه يجعلني أتأخر أحياناً." }, { id: "you", speaker: "You", text: "Name one habit, say what it gives you, and add one possible drawback.", textArabic: "اذكر عادة واحدة وما الذي تمنحك إياه وأضف عيباً محتملاً واحداً." }] },
  ],
  77: [
    { id: "b1-m6-77-language", kind: "standard", title: "Choose verbs for sharing information", titleArabic: "اختر أفعالاً لمشاركة المعلومات", objective: "Use report, post, forward, verify, and misquote to describe how information moves online.", objectiveArabic: "استخدم report وpost وforward وverify وmisquote لوصف انتقال المعلومات عبر الإنترنت.", stage: "explanation", estimatedMinutes: 12, semantic: "grammar", progressiveSupports: ["worked-example", "tip"], sentencePatterns: ["The article reports that …", "Before I forward it, I will verify …", "The speaker was misquoted in …"] },
    { id: "b1-m6-77-precision", kind: "writing", title: "Rewrite an imprecise post", titleArabic: "أعد كتابة منشور غير دقيق", objective: "Turn a vague online post into a short, precise message that names its source and limit.", objectiveArabic: "حوّل منشوراً غامضاً إلى رسالة قصيرة دقيقة تذكر مصدره وحده.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Rewrite this in 60–80 words: ‘Everyone says the new rule is terrible.’ State what you actually know, identify a source you would check, and avoid presenting a rumour as fact.", writingPromptArabic: "أعد كتابة هذا في 60–80 كلمة: «الجميع يقول إن القاعدة الجديدة سيئة». اذكر ما تعرفه فعلاً وحدّد مصدراً ستتحقق منه وتجنب تقديم الإشاعة كحقيقة.", suggestedVocabulary: ["according to", "appears to", "official update", "verify", "claim"], sentencePatterns: ["According to …", "I have not yet verified whether …"] },
  ],
  78: [
    { id: "b1-m6-78-notice", kind: "reading", title: "Notice fact, opinion, and clickbait", titleArabic: "لاحظ الحقيقة والرأي والعنوان المثير", objective: "Recognise wording that signals evidence, opinion, or an attention-seeking claim.", objectiveArabic: "تعرّف إلى الصياغة التي تشير إلى دليل أو رأي أو ادعاء يهدف إلى جذب الانتباه.", stage: "explanation", estimatedMinutes: 13, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A local page announced, ‘This simple change will transform every commute.’ The linked article was more careful: it described a three-month trial on one bus route and quoted two passengers with different views. The transport office had not yet published a full evaluation. The headline invited an immediate reaction, while the article gave a smaller, incomplete piece of evidence.", readingTextArabic: "نص قصير يوضح الفرق بين عنوان مبالغ فيه ومقال أكثر حذراً وأدلة جزئية.", readingChecks: [{ id: "detail", type: "detail", prompt: "What had the transport office not yet published?", promptArabic: "ما الذي لم ينشره مكتب النقل بعد؟", choices: ["A full evaluation.", "A new bus route.", "A list of passengers."], answer: "A full evaluation." }, { id: "inference", type: "inference", prompt: "Why is the headline described as attention-seeking?", promptArabic: "لماذا يوصف العنوان بأنه يجذب الانتباه؟", choices: ["It promises a universal transformation from limited evidence.", "It gives two passengers’ views.", "It names a three-month trial."], answer: "It promises a universal transformation from limited evidence." }] },
  ],
  79: [
    { id: "b1-m6-79-dialogue", kind: "interaction", title: "Ask before you share", titleArabic: "اسأل قبل أن تشارك", objective: "Question a claim politely, ask for its source, and explain why checking matters.", objectiveArabic: "اسأل بلطف عن ادعاء واطلب مصدره واشرح لماذا يهم التحقق.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "friend", speaker: "Friend", text: "I am forwarding this warning now because it says the service will close tomorrow.", textArabic: "سأعيد توجيه هذا التحذير الآن لأنه يقول إن الخدمة ستغلق غداً.", purpose: "Present an urgent, unverified claim." }, { id: "you", speaker: "You", text: "It may be useful, but do you know where it came from? Let’s check the service’s official page before we pass it on.", textArabic: "قد يكون مفيداً، لكن هل تعرف من أين جاء؟ لنتحقق من الصفحة الرسمية للخدمة قبل إعادة توجيهه.", purpose: "Request evidence without accusing the speaker." }] },
  ],
  80: [
    { id: "b1-m6-80-respond", kind: "speaking", title: "Hear a privacy concern and respond", titleArabic: "استمع إلى قلق بشأن الخصوصية واستجب", objective: "Identify a concern about personal data and ask one calm, useful follow-up question.", objectiveArabic: "حدّد قلقاً يتعلق بالبيانات الشخصية واسأل سؤال متابعة هادئاً ومفيداً.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["transcript", "word-support"], speakingLines: [{ id: "speaker", speaker: "Speaker", text: "The app asked for access to my location, contacts, and microphone before I could use a simple feature.", textArabic: "طلب التطبيق الوصول إلى موقعي وجهات اتصالي والميكروفون قبل أن أتمكن من استخدام ميزة بسيطة." }, { id: "you", speaker: "You", text: "Which permission is necessary for that feature, and have you checked whether there is a more limited setting?", textArabic: "أي إذن ضروري لهذه الميزة، وهل تحققت مما إذا كان هناك إعداد أكثر محدودية؟" }] },
  ],
  81: [
    { id: "b1-m6-81-detail", kind: "reading", title: "Read a digital-safety guide", titleArabic: "اقرأ دليلاً للسلامة الرقمية", objective: "Trace advice, reasons, and practical limits in a short digital-safety guide.", objectiveArabic: "تتبّع النصيحة والأسباب والحدود العملية في دليل قصير للسلامة الرقمية.", stage: "explanation", estimatedMinutes: 16, semantic: "example", progressiveSupports: ["word-support"], readingText: "A youth centre updated its account-security guide after several volunteers received messages that looked as if they came from the coordinator. The guide recommends using a different password for each important service and confirming unusual requests through a second channel. It does not promise that a person will never face a scam. Instead, it focuses on creating a short pause between receiving a surprising message and responding to it.", readingTextArabic: "دليل قصير يشرح إجراءات أمان عملية دون ادعاء إزالة المخاطر بالكامل.", readingChecks: [{ id: "advice", type: "detail", prompt: "How should volunteers confirm an unusual request?", promptArabic: "كيف ينبغي للمتطوعين تأكيد طلب غير معتاد؟", choices: ["Through a second channel.", "By answering immediately.", "By sharing a password."], answer: "Through a second channel." }, { id: "purpose", type: "inference", prompt: "What is the guide’s main aim?", promptArabic: "ما الهدف الرئيسي للدليل؟", choices: ["To create a pause for checking before responding.", "To guarantee that scams disappear.", "To stop volunteers using online services."], answer: "To create a pause for checking before responding." }] },
  ],
  82: [
    { id: "b1-m6-82-paragraph", kind: "writing", title: "Write a connected media-use paragraph", titleArabic: "اكتب فقرة مترابطة عن استخدام الإعلام", objective: "Describe one media choice, its benefit, its risk, and a boundary you would use.", objectiveArabic: "صف اختياراً إعلامياً واحداً وفائدته وخطره وحداً ستضعه لنفسك.", stage: "independent-practice", estimatedMinutes: 20, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 130–160 words about one way you use media or messaging. Explain what it helps you do, identify one risk or distraction, and describe a boundary that would keep the benefit without claiming that one rule works for everyone.", writingPromptArabic: "اكتب 130–160 كلمة عن طريقة تستخدم بها الإعلام أو المراسلة. اشرح ما الذي تساعدك عليه وحدد خطراً أو تشتيتاً واحداً وصف حداً يحافظ على الفائدة دون الادعاء بأن قاعدة واحدة تناسب الجميع.", suggestedVocabulary: ["benefit", "boundary", "interrupt", "reliable", "deliberately"], sentencePatterns: ["One benefit is … whereas one risk is …", "To keep this manageable, I …"] },
  ],
  83: [
    { id: "b1-m6-83-compare", kind: "interaction", title: "Compare two ways to get news", titleArabic: "قارن بين طريقتين للحصول على الأخبار", objective: "Compare two news habits using reliability, speed, range, and effort as criteria.", objectiveArabic: "قارن بين عادتي أخبار باستخدام الموثوقية والسرعة والتنوع والجهد كمعايير.", stage: "real-context", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "option-a", speaker: "Option A", text: "Follow short updates from several social-media accounts throughout the day.", textArabic: "تابع تحديثات قصيرة من عدة حسابات على وسائل التواصل طوال اليوم.", purpose: "Present a fast, varied approach." }, { id: "option-b", speaker: "Option B", text: "Read one longer weekly briefing that links to its sources.", textArabic: "اقرأ ملخصاً أسبوعياً أطول يربط بمصادره.", purpose: "Present a slower, source-led approach." }, { id: "you", speaker: "You", text: "Option A is faster, whereas Option B may make checking easier. For … I would choose … because …", textArabic: "الخيار أ أسرع، بينما قد يجعل الخيار ب التحقق أسهل. من أجل … سأختار … لأن …", purpose: "Make a qualified, context-dependent recommendation." }] },
  ],
  84: [
    { id: "b1-m6-84-repair", kind: "interaction", title: "Repair a message that sounded abrupt", titleArabic: "أصلح رسالة بدت حادة", objective: "Clarify intention, acknowledge impact, and rewrite a short digital message in a more cooperative tone.", objectiveArabic: "وضّح النية واعترف بالأثر وأعد كتابة رسالة رقمية بنبرة أكثر تعاوناً.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["worked-example", "transcript"], interactionTurns: [{ id: "message", speaker: "Original message", text: "Send the file now. This should have been finished yesterday.", textArabic: "أرسل الملف الآن. كان ينبغي أن ينتهي هذا أمس.", purpose: "Show an abrupt message with no context." }, { id: "repair", speaker: "You", text: "Sorry if my earlier message sounded sharp. I need the file for a meeting at 3 p.m.; could you let me know what is still needed and when you expect to send it?", textArabic: "أعتذر إن بدت رسالتي السابقة حادة. أحتاج الملف لاجتماع الساعة الثالثة؛ هل يمكنك إخباري بما الذي لا يزال مطلوباً ومتى تتوقع إرساله؟", purpose: "Repair tone while keeping the request clear." }] },
  ],
  85: [
    { id: "b1-m6-85-purpose", kind: "speaking", title: "Recommend a communication channel", titleArabic: "أوصِ بقناة تواصل", objective: "Recommend a communication channel for a specific purpose and justify it with two criteria.", objectiveArabic: "أوصِ بقناة تواصل لغرض محدد وبرّرها بمعيارين.", stage: "independent-practice", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [{ id: "prompt", speaker: "Scenario", text: "A volunteer team needs to agree a shift change, retain a record of the decision, and avoid interrupting everyone late at night.", textArabic: "يحتاج فريق متطوعين إلى الاتفاق على تغيير مناوبة والاحتفاظ بسجل للقرار وتجنب إزعاج الجميع في وقت متأخر.", }, { id: "you", speaker: "You", text: "Recommend a channel. Explain how it supports clarity, timing, and a record of the decision; then name one limitation.", textArabic: "أوصِ بقناة. اشرح كيف تدعم الوضوح والتوقيت وسجل القرار، ثم اذكر حداً واحداً." }] },
  ],
  86: [
    { id: "b1-m6-86-network", kind: "review", title: "Rebuild the digital-life word network", titleArabic: "أعد بناء شبكة مفردات الحياة الرقمية", objective: "Retrieve and connect words for sources, claims, privacy, tone, and digital routines.", objectiveArabic: "استرجع واربط كلمات للمصادر والادعاءات والخصوصية والنبرة والعادات الرقمية.", stage: "review", estimatedMinutes: 14, semantic: "retrieval", progressiveSupports: ["arabic-help", "word-support"], vocabularyIds: ["source", "claim", "verify", "notification", "permission", "privacy", "tone", "boundary"], sentencePatterns: ["Before I share a claim, I …", "The message sounded … because …", "A useful boundary is …"] },
  ],
  87: [
    { id: "b1-m6-87-source", kind: "reading", title: "Interpret a short platform update", titleArabic: "فسّر تحديثاً قصيراً لمنصة", objective: "Distinguish what a platform update confirms, what it does not confirm, and what a reader should check next.", objectiveArabic: "ميّز بين ما يؤكده تحديث المنصة وما لا يؤكده وما ينبغي للقارئ التحقق منه لاحقاً.", stage: "explanation", estimatedMinutes: 16, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A messaging platform stated that it would introduce a new setting for group administrators next month. The update explained that administrators could limit who changes a group description, but it did not say that every existing group would automatically use the setting. Several posts then claimed that all group messages would become private by default. That conclusion went beyond the wording of the update.", readingTextArabic: "تحديث قصير يطلب من المتعلم التمييز بين المعلومة المؤكدة والاستنتاج الذي يتجاوز النص.", readingChecks: [{ id: "confirmed", type: "detail", prompt: "What does the update confirm?", promptArabic: "ماذا يؤكد التحديث؟", choices: ["Administrators can limit who changes a group description.", "All group messages become private.", "Every group uses the setting automatically."], answer: "Administrators can limit who changes a group description." }, { id: "beyond", type: "inference", prompt: "Why do the later posts go beyond the update?", promptArabic: "لماذا تتجاوز المنشورات اللاحقة التحديث؟", choices: ["They add a privacy claim the update did not make.", "They repeat the administration setting exactly.", "They quote the date incorrectly."], answer: "They add a privacy claim the update did not make." }] },
  ],
  88: [
    { id: "b1-m6-88-revise", kind: "writing", title: "Draft and revise a responsible announcement", titleArabic: "صغ وراجع إعلاناً مسؤولاً", objective: "Draft a concise group announcement, then revise it for source, tone, and next action.", objectiveArabic: "صغ إعلاناً موجزاً للمجموعة ثم راجعه من حيث المصدر والنبرة والخطوة التالية.", stage: "independent-practice", estimatedMinutes: 20, semantic: "activity", progressiveSupports: ["worked-example", "tip"], writingPrompt: "Draft an 110–140-word announcement for a study group about a schedule change. Say where the information came from, what is confirmed, what members should do next, and a polite way to ask questions. Then underline one sentence you would revise to make the tone clearer.", writingPromptArabic: "صغ إعلاناً من 110–140 كلمة لمجموعة دراسة عن تغيير في الجدول. اذكر مصدر المعلومة وما تم تأكيده وما ينبغي للأعضاء فعله لاحقاً وطريقة مهذبة لطرح الأسئلة. ثم ضع خطاً تحت جملة ستراجعها لجعل النبرة أوضح.", suggestedVocabulary: ["confirmed", "update", "please note", "reply", "clarify"], sentencePatterns: ["According to …", "If anything is unclear, please …"] },
  ],
  89: [
    { id: "b1-m6-89-task", kind: "interaction", title: "Handle an urgent-looking online request", titleArabic: "تعامل مع طلب إلكتروني يبدو عاجلاً", objective: "Slow down an urgent-looking request, identify what to verify, and propose a safe next step.", objectiveArabic: "أبطئ الاستجابة لطلب يبدو عاجلاً وحدد ما يجب التحقق منه واقترح خطوة تالية آمنة.", stage: "real-context", estimatedMinutes: 15, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "request", speaker: "Message", text: "URGENT: I am locked out of the team account. Send the verification code you just received so I can restore access.", textArabic: "عاجل: تم قفل حساب الفريق. أرسل رمز التحقق الذي تلقيته للتو كي أستعيد الوصول.", purpose: "Present an urgent request for sensitive information." }, { id: "you", speaker: "You", text: "I will not share a verification code. I will contact the account owner through the usual number and check the official support process first.", textArabic: "لن أشارك رمز التحقق. سأتواصل مع مالك الحساب عبر الرقم المعتاد وأتحقق أولاً من إجراء الدعم الرسمي.", purpose: "State a safe, calm, verifiable response." }] },
  ],
  90: [
    { id: "b1-m6-90-checkpoint", kind: "assessment", title: "Module checkpoint: make a responsible digital response", titleArabic: "نقطة تحقق الوحدة: قدّم استجابة رقمية مسؤولة", objective: "Use media vocabulary, source awareness, tone repair, and a practical next step in a connected response.", objectiveArabic: "استخدم مفردات الإعلام ووعي المصدر وإصلاح النبرة وخطوة تالية عملية في استجابة مترابطة.", stage: "assessment", estimatedMinutes: 22, semantic: "assessment", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "A group member shares an alarming message, then sends a short reply that sounds impatient when questioned. Write 140–170 words that (1) separates what is known from what needs checking, (2) suggests a safe verification step, and (3) repairs the discussion so the group can act respectfully.", writingPromptArabic: "يشارك عضو في المجموعة رسالة مقلقة ثم يرسل رداً قصيراً يبدو غير صبور عند سؤاله. اكتب 140–170 كلمة تفصل فيها بين ما هو معروف وما يحتاج إلى تحقق وتقترح خطوة تحقق آمنة وتصلح النقاش كي تتصرف المجموعة باحترام.", suggestedVocabulary: ["source", "verify", "official", "misunderstanding", "clarify", "respectfully"], sentencePatterns: ["What we know so far is …", "Before acting, we should …", "I did not mean to sound …"] },
  ],
};
