import type { LessonActivity } from "./types";

const scene = (label: string, tint = "#5d3f6e") => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420"><rect width="720" height="420" rx="30" fill="${tint}"/><path d="M88 313c70-123 158-164 266-164 98 0 178 49 276 164" fill="#f7f2e8" opacity=".92"/><path d="M122 102h164v112H122z" fill="#edc36a"/><path d="M430 92h166v126H430z" fill="#dbe9ee"/><text x="360" y="136" text-anchor="middle" fill="#fff" font-family="Arial" font-size="34" font-weight="700">${label}</text><text x="360" y="184" text-anchor="middle" fill="#ede6f4" font-family="Arial" font-size="21">Tell · question · justify</text></svg>`)}`;

const visualWords = (lesson: number, items: Array<[string, string, string]>) => items.map(([word, arabic, example], index) => ({
  id: `b1-m4-${lesson}-visual-${index + 1}`,
  word,
  arabic,
  pronunciation: word,
  exampleEN: example,
  exampleAR: "استخدم الكلمة لتعرض قصة أو رأياً بوضوح واحترام.",
  imageUrl: scene(word, index % 2 ? "#765246" : "#5d3f6e"),
  altText: `Illustrated stories and opinions concept card for ${word}`,
  category: "Stories and opinions",
  interactionHint: "Read the example, then decide whether the word signals a fact, an interpretation, or a judgement.",
}));

export const B1_MODULE_4_AUTHORED_ACTIVITIES: Record<number, readonly LessonActivity[]> = {
  46: [
    { id: "b1-m4-46-map", kind: "visual-vocabulary", title: "Map fact, viewpoint, and story", titleArabic: "ارسم خريطة للحقيقة ووجهة النظر والقصة", objective: "Separate an event, a narrator’s viewpoint, and the evidence behind an opinion.", objectiveArabic: "ميّز بين الحدث ووجهة نظر الراوي والدليل وراء الرأي.", stage: "introduction", estimatedMinutes: 11, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(46, [["viewpoint", "وجهة نظر", "From her viewpoint, the ending was hopeful rather than predictable."], ["evidence", "دليل", "The reviewer gave evidence from two scenes."], ["assumption", "افتراض", "That conclusion depends on an assumption about the character."]]) },
    { id: "b1-m4-46-position", kind: "speaking", title: "Give a careful first opinion", titleArabic: "قدّم رأياً أولياً متأنياً", objective: "State an initial response and distinguish it from a proven fact.", objectiveArabic: "اذكر استجابة أولية وميّزها عن حقيقة مثبتة.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example"], speakingLines: [{ id: "model", speaker: "Model", text: "The ending seems unfair to me, although the writer gives us reasons to understand it.", textArabic: "تبدو النهاية غير عادلة لي، رغم أن الكاتب يقدم لنا أسباباً لفهمها." }, { id: "you", speaker: "You", text: "Choose a film, book, or true event. Give one reaction and one reason without presenting your view as a fact.", textArabic: "اختر فيلماً أو كتاباً أو حدثاً حقيقياً. قدّم رد فعل واحداً وسبباً واحداً دون عرض رأيك كحقيقة." }] },
  ],
  47: [
    { id: "b1-m4-47-language", kind: "standard", title: "Build a balanced viewpoint", titleArabic: "ابنِ وجهة نظر متوازنة", objective: "Use reporting verbs, hedging, and contrast to make an opinion precise.", objectiveArabic: "استخدم أفعال النقل والتخفيف والتباين لجعل الرأي دقيقاً.", stage: "explanation", estimatedMinutes: 12, semantic: "grammar", progressiveSupports: ["worked-example", "tip"], sentencePatterns: ["I would argue that the story is effective because …", "Some readers may find …, whereas others value …", "The narrator seems to suggest that …"] },
    { id: "b1-m4-47-reframe", kind: "writing", title: "Reframe an absolute claim", titleArabic: "أعد صياغة ادعاء مطلق", objective: "Turn an overconfident judgement into a fair, evidence-aware claim.", objectiveArabic: "حوّل حكماً واثقاً بشكل مبالغ فيه إلى ادعاء عادل واعٍ بالدليل.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example"], writingPrompt: "Rewrite this claim in 45–60 words: ‘This programme is obviously the best because everyone likes it.’ Keep a clear opinion, add one reason, and acknowledge one possible limitation.", writingPromptArabic: "أعد كتابة الادعاء في 45–60 كلمة مع رأي واضح وسبب واحد وحد واحد محتمل.", suggestedVocabulary: ["appears", "in my view", "however", "audience", "limitation"], sentencePatterns: ["It appears to be … because …", "However, this may not appeal to …"] },
  ],
  48: [
    { id: "b1-m4-48-pattern", kind: "reading", title: "Notice the narrator’s distance", titleArabic: "لاحظ مسافة الراوي", objective: "Notice how adverbs and reporting phrases show certainty, doubt, or distance from a claim.", objectiveArabic: "لاحظ كيف تُظهر الظروف وعبارات النقل اليقين أو الشك أو المسافة عن الادعاء.", stage: "explanation", estimatedMinutes: 12, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "Mina later claimed that she had recognised the stranger immediately. Yet her diary from that evening says that the person ‘looked familiar’ and that she was not completely sure. The difference matters: the first version makes the meeting sound dramatic, while the earlier note leaves room for doubt.", readingTextArabic: "نص قصير يقارن بين رواية لاحقة ووصف أقرب إلى الحدث لتوضيح اليقين والشك.", readingChecks: [{ id: "distance", type: "detail", prompt: "Which phrase shows that Mina was uncertain at first?", promptArabic: "أي عبارة تدل على أن مينا لم تكن متأكدة في البداية؟", choices: ["looked familiar", "recognised immediately", "the difference matters"], answer: "looked familiar" }, { id: "effect", type: "inference", prompt: "Why does the writer compare the two versions?", promptArabic: "لماذا يقارن الكاتب الروايتين؟", choices: ["To show how certainty can increase in retelling.", "To prove the stranger was dishonest.", "To explain a grammar rule only."], answer: "To show how certainty can increase in retelling." }] },
  ],
  49: [
    { id: "b1-m4-49-dialogue", kind: "interaction", title: "Disagree about an ending without dismissing it", titleArabic: "اختلف حول نهاية دون رفضها", objective: "Respond to a different interpretation with a question, a reason, and a respectful concession.", objectiveArabic: "استجب لتفسير مختلف بسؤال وسبب وتنازل محترم.", stage: "real-context", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "partner", speaker: "Partner", text: "I thought the main character was selfish at the end. She only protected herself.", textArabic: "اعتقدت أن الشخصية الرئيسية كانت أنانية في النهاية. لقد حمت نفسها فقط.", purpose: "Offer an interpretation." }, { id: "you", speaker: "You", text: "I can see why you read it that way. Could it also be that she had no safe option left? The earlier scene at the station suggests she had already tried to help.", textArabic: "أفهم لماذا قرأتها بهذا الشكل. هل يمكن أيضاً أنها لم تعد تملك خياراً آمناً؟ يوحي المشهد السابق في المحطة بأنها حاولت المساعدة بالفعل.", purpose: "Question and support an alternative reading." }] },
  ],
  50: [
    { id: "b1-m4-50-listen", kind: "speaking", title: "Hear a review and respond", titleArabic: "استمع إلى مراجعة واستجب", objective: "Identify a reviewer’s claim and reply with one focused agreement or challenge.", objectiveArabic: "حدّد ادعاء المراجع وردّ باتفاق أو اعتراض محدد.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["transcript", "word-support"], speakingLines: [{ id: "reviewer", speaker: "Reviewer", text: "The documentary is moving because it allows the people affected to speak for themselves, although it gives very little historical context.", textArabic: "الفيلم الوثائقي مؤثر لأنه يتيح للمتأثرين التحدث بأنفسهم، رغم أنه يقدم سياقاً تاريخياً قليلاً جداً." }, { id: "you", speaker: "You", text: "I agree that the voices are powerful. However, I would need more background before accepting its wider conclusion.", textArabic: "أتفق أن الأصوات مؤثرة، لكنني سأحتاج إلى خلفية أكثر قبل قبول استنتاجه الأوسع." }] },
  ],
  51: [
    { id: "b1-m4-51-detail", kind: "reading", title: "Read a local-story feature for detail", titleArabic: "اقرأ تقريراً تفصيلياً عن قصة محلية", objective: "Trace an event, two viewpoints, and the evidence used in a local feature.", objectiveArabic: "تتبّع حدثاً ووجهتي نظر والدليل المستخدم في تقرير محلي.", stage: "explanation", estimatedMinutes: 16, semantic: "example", progressiveSupports: ["word-support"], readingText: "When the old cinema closed, several residents described it as the end of a meeting place, not simply the loss of a building. The council said that repairs would have cost more than the site could earn. In response, a volunteer group collected photographs, ticket stubs, and short recordings from former staff. Their exhibition did not claim that the cinema should have remained open forever; instead, it asked the town to remember why the place had mattered.", readingTextArabic: "مقال قصير يوازن بين قرار عملي وذكريات السكان ودليل مشروع محلي.", readingChecks: [{ id: "council", type: "detail", prompt: "What reason did the council give for closing the cinema?", promptArabic: "ما السبب الذي قدمه المجلس لإغلاق السينما؟", choices: ["Repairs were financially unrealistic.", "Residents did not care about films.", "The volunteer group requested closure."], answer: "Repairs were financially unrealistic." }, { id: "purpose", type: "inference", prompt: "What is the exhibition’s main purpose?", promptArabic: "ما الهدف الأساسي للمعرض؟", choices: ["To preserve the cinema’s social meaning.", "To promise that the cinema will reopen.", "To prove that the council lied."], answer: "To preserve the cinema’s social meaning." }] },
  ],
  52: [
    { id: "b1-m4-52-paragraph", kind: "writing", title: "Write a connected cultural opinion", titleArabic: "اكتب رأياً ثقافياً مترابطاً", objective: "Write a 140–170-word paragraph that develops an opinion through an example, contrast, and conclusion.", objectiveArabic: "اكتب فقرة من 140–170 كلمة تطور رأياً عبر مثال وتباين وخاتمة.", stage: "independent-practice", estimatedMinutes: 20, semantic: "activity", progressiveSupports: ["worked-example"], writingPrompt: "Write 140–170 words on this question: Should communities spend money preserving old cultural places when they also need modern services? State your view, develop one example, acknowledge a competing need, and reach a measured conclusion.", writingPromptArabic: "اكتب 140–170 كلمة: هل ينبغي للمجتمعات إنفاق المال على حفظ الأماكن الثقافية القديمة مع حاجتها إلى خدمات حديثة؟", suggestedVocabulary: ["preserve", "heritage", "practical need", "whereas", "on balance"], sentencePatterns: ["Although …, I would argue that …", "On balance, the stronger priority is …"] },
  ],
  53: [
    { id: "b1-m4-53-compare", kind: "interaction", title: "Compare two ways to tell one story", titleArabic: "قارن بين طريقتين لرواية قصة واحدة", objective: "Compare a personal account and a news report for purpose, detail, and reliability.", objectiveArabic: "قارن بين رواية شخصية وتقرير إخباري من حيث الغرض والتفصيل والموثوقية.", stage: "real-context", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "source-a", speaker: "Source A", text: "My train was cancelled and nobody cared. It was a complete disaster.", textArabic: "أُلغي قطاري ولم يهتم أحد. كانت كارثة كاملة.", purpose: "Personal reaction." }, { id: "source-b", speaker: "Source B", text: "The 18:10 service was cancelled because of a signal fault. Passengers were directed to the next available service.", textArabic: "أُلغيت خدمة 18:10 بسبب عطل في الإشارة، ووُجّه الركاب إلى الخدمة التالية المتاحة.", purpose: "Factual report." }, { id: "you", speaker: "You", text: "Source A shows the passenger’s experience, but Source B is more useful for checking what happened. I would use both, for different reasons.", textArabic: "يوضح المصدر أ تجربة الراكب، لكن المصدر ب أكثر فائدة للتحقق مما حدث. سأستخدم كليهما لأسباب مختلفة.", purpose: "Make a qualified comparison." }] },
  ],
  54: [
    { id: "b1-m4-54-repair", kind: "interaction", title: "Repair a misquoted opinion", titleArabic: "أصلح رأياً نُقل بشكل خاطئ", objective: "Correct a paraphrase without accusing the other person and clarify the intended position.", objectiveArabic: "صحح إعادة صياغة دون اتهام الطرف الآخر ووضّح الموقف المقصود.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "misquote", speaker: "Colleague", text: "So you said the festival should be cancelled because it is too expensive.", textArabic: "إذن قلت إن المهرجان يجب إلغاؤه لأنه مكلف جداً.", purpose: "Report an inaccurate summary." }, { id: "repair", speaker: "You", text: "Not exactly. I said the current plan may be too expensive for one year. I still support the festival if the organisers publish a realistic budget.", textArabic: "ليس تماماً. قلت إن الخطة الحالية قد تكون مكلفة جداً لسنة واحدة. ما زلت أدعم المهرجان إذا نشر المنظمون ميزانية واقعية.", purpose: "Clarify a qualified position." }] },
  ],
  55: [
    { id: "b1-m4-55-purpose", kind: "speaking", title: "Recommend a story with a reason", titleArabic: "رشّح قصة مع سبب", objective: "Give a one-minute recommendation that matches a story to a specific audience.", objectiveArabic: "قدّم توصية لمدة دقيقة تطابق قصة مع جمهور محدد.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["word-support", "worked-example"], speakingLines: [{ id: "frame", speaker: "Plan", text: "Name the audience, give one strength, mention one possible difficulty, and finish with your recommendation.", textArabic: "سمِّ الجمهور، وقدّم نقطة قوة واحدة، واذكر صعوبة محتملة، ثم اختم بتوصيتك." }, { id: "you", speaker: "You", text: "Recommend a film, book, podcast, or local story to a learner who wants to understand a viewpoint different from their own.", textArabic: "رشّح فيلماً أو كتاباً أو بودكاست أو قصة محلية لمتعلم يريد فهم وجهة نظر مختلفة عن وجهة نظره." }] },
  ],
  56: [
    { id: "b1-m4-56-network", kind: "review", title: "Reconnect the stories-and-opinions network", titleArabic: "أعد ربط شبكة القصص والآراء", objective: "Retrieve language by its role: telling, qualifying, challenging, supporting, and concluding.", objectiveArabic: "استرجع اللغة بحسب دورها: السرد والتخفيف والاعتراض والدعم والخلاصة.", stage: "review", estimatedMinutes: 11, semantic: "retrieval", progressiveSupports: ["arabic-help", "word-support"], sentencePatterns: ["The account suggests that …", "A stronger interpretation would need …", "I accept that …; nevertheless, …"] },
  ],
  57: [
    { id: "b1-m4-57-source", kind: "reading", title: "Interpret a short opinion source", titleArabic: "فسّر مصدراً قصيراً للرأي", objective: "Identify a source’s claim, evidence, audience, and unanswered question.", objectiveArabic: "حدّد ادعاء المصدر ودليله وجمهوره وسؤالاً لم يُجب عنه.", stage: "explanation", estimatedMinutes: 14, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A local blogger argues that the town should replace its printed events guide with a phone app. She notes that the app could be updated quickly and would cost less to print. However, her article gives no figures for the number of residents who use smartphones, and it does not include the views of older readers who currently collect the guide from libraries.", readingTextArabic: "مصدر رأي قصير يقدم ادعاءً ودليلين وحدوداً مهمة في الأدلة.", readingChecks: [{ id: "claim", type: "detail", prompt: "What change does the blogger support?", promptArabic: "ما التغيير الذي تدعمه المدونة؟", choices: ["Replacing the printed guide with an app.", "Closing the local libraries.", "Making the guide more expensive."], answer: "Replacing the printed guide with an app." }, { id: "gap", type: "inference", prompt: "What important evidence is missing?", promptArabic: "ما الدليل المهم المفقود؟", choices: ["Whether all intended users can use the app.", "The colour of the printed guide.", "The blogger’s favourite event."], answer: "Whether all intended users can use the app." }] },
  ],
  58: [
    { id: "b1-m4-58-revise", kind: "writing", title: "Draft and revise a reader response", titleArabic: "صغ وراجع رد قارئ", objective: "Improve a short response by making its claim specific, fair, and supported.", objectiveArabic: "حسّن رداً قصيراً بجعل ادعائه محدداً وعادلاً ومدعوماً.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example"], writingPrompt: "Draft 90–120 words responding to the events-app article. Then revise one sentence to add a limit or a question. Your final version should make a clear recommendation without pretending that the source is complete.", writingPromptArabic: "اكتب 90–120 كلمة رداً على مقالة تطبيق الفعاليات، ثم راجع جملة واحدة لإضافة حد أو سؤال.", suggestedVocabulary: ["recommend", "accessible", "evidence", "unless", "in addition"], sentencePatterns: ["I would support this change if …", "Before deciding, the council should ask …"] },
  ],
  59: [
    { id: "b1-m4-59-task", kind: "interaction", title: "Plan a fair story display", titleArabic: "خطط لعرض قصص عادل", objective: "Choose stories for a community display, justify the balance, and explain one selection rule.", objectiveArabic: "اختر قصصاً لعرض مجتمعي وبرّر التوازن واشرح قاعدة اختيار واحدة.", stage: "real-context", estimatedMinutes: 16, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Coordinator", text: "We have room for only six stories. Some are well-known, while others represent groups who are rarely heard.", textArabic: "لدينا مكان لست قصص فقط. بعضها معروف، بينما تمثل أخرى مجموعات نادراً ما يُسمع صوتها.", purpose: "Present a realistic selection problem." }, { id: "you", speaker: "You", text: "I would include some familiar stories, but I would reserve at least half the space for less-heard voices. The display should show a wider picture, not only the easiest stories to recognise.", textArabic: "سأضم بعض القصص المألوفة، لكنني سأخصص نصف المساحة على الأقل لأصوات أقل سماعاً. يجب أن يقدم العرض صورة أوسع لا القصص الأسهل للتعرف عليها فقط.", purpose: "Recommend a fair rule with a reason." }] },
  ],
  60: [
    { id: "b1-m4-60-checkpoint", kind: "assessment", title: "Stories and opinions checkpoint", titleArabic: "نقطة تحقق القصص والآراء", objective: "Interpret a short account, make a qualified recommendation, and support it with relevant evidence.", objectiveArabic: "فسّر رواية قصيرة وقدّم توصية متوازنة وادعمها بدليل مناسب.", stage: "assessment", estimatedMinutes: 25, semantic: "assessment", progressiveSupports: ["tip"], readingText: "A youth centre is deciding whether to record local residents’ stories as short podcasts. Supporters say that recordings can preserve different voices and allow young people to learn interviewing skills. Critics worry that short clips may remove context or make private experiences public too quickly. The centre has promised that every participant can approve the final recording before it is shared.", readingTextArabic: "نص تقويمي عن فائدة توثيق القصص المحلية وحدود ذلك.", readingChecks: [{ id: "safeguard", type: "detail", prompt: "What safeguard does the centre promise?", promptArabic: "ما الإجراء الوقائي الذي يعد به المركز؟", choices: ["Participants approve the final recording.", "All stories will be anonymous.", "Only staff may listen."], answer: "Participants approve the final recording." }, { id: "recommend", type: "inference", prompt: "Which recommendation best reflects the source?", promptArabic: "أي توصية تعكس المصدر أفضل؟", choices: ["Proceed with informed consent and careful context.", "Record every story immediately.", "Cancel the idea because stories are private."], answer: "Proceed with informed consent and careful context." }], writingPrompt: "Write 130–160 words recommending how the youth centre should run the podcast project. Include one benefit, one risk, and two practical safeguards.", writingPromptArabic: "اكتب 130–160 كلمة توصي فيها بكيفية تنفيذ مشروع البودكاست مع فائدة وخطر وإجرائين وقائيين.", suggestedVocabulary: ["consent", "context", "participant", "protect", "publish"], sentencePatterns: ["I would recommend … provided that …", "One risk is …, which could be reduced by …"] },
  ],
};
