import type { LessonActivity } from "./types";

/** Explicit learner journeys for B1 Module 10: Future Pathways and Projects (Lessons 136–150). */
export const B1_MODULE_10_ACTIVITIES: Record<number, LessonActivity[]> = {
  136: [
    { id: "b1-m10-136-map", kind: "visual-vocabulary", title: "Map a future pathway", titleArabic: "ارسم خريطة لمسار مستقبلي", objective: "Distinguish a goal, pathway, application, deadline, evidence, and mentor when planning a realistic next step.", objectiveArabic: "ميّز بين الهدف والمسار والطلب والموعد النهائي والدليل والمرشد عند تخطيط خطوة تالية واقعية.", stage: "introduction", estimatedMinutes: 13, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: [{ id: "goal", word: "goal", arabic: "هدف", pronunciation: "/ɡəʊl/", exampleEN: "Her goal is to gain practical experience.", exampleAR: "هدفها هو اكتساب خبرة عملية." }, { id: "pathway", word: "pathway", arabic: "مسار", pronunciation: "/ˈpɑːθ.weɪ/", exampleEN: "There is more than one pathway into the field.", exampleAR: "هناك أكثر من مسار واحد للدخول إلى المجال." }, { id: "application", word: "application", arabic: "طلب / استمارة تقديم", pronunciation: "/ˌæp.lɪˈkeɪ.ʃən/", exampleEN: "Submit the application before Friday.", exampleAR: "قدّم الطلب قبل يوم الجمعة." }, { id: "deadline", word: "deadline", arabic: "موعد نهائي", pronunciation: "/ˈded.laɪn/", exampleEN: "The deadline is at noon on 12 May.", exampleAR: "الموعد النهائي هو الساعة الثانية عشرة ظهر 12 مايو." }, { id: "evidence", word: "evidence", arabic: "دليل", pronunciation: "/ˈev.ɪ.dəns/", exampleEN: "The portfolio is evidence of her work.", exampleAR: "ملف الأعمال دليل على عملها." }, { id: "mentor", word: "mentor", arabic: "مرشد", pronunciation: "/ˈmen.tɔː/", exampleEN: "A mentor gave him useful feedback.", exampleAR: "قدّم له مرشد ملاحظات مفيدة." }] },
    { id: "b1-m10-136-scene", kind: "visual-vocabulary", title: "See a pathway as connected steps", titleArabic: "انظر إلى المسار كخطوات مترابطة", objective: "Connect a future goal to the evidence, deadline, and support that make a first step realistic.", objectiveArabic: "اربط الهدف المستقبلي بالدليل والموعد النهائي والدعم الذي يجعل الخطوة الأولى واقعية.", stage: "guided-practice", estimatedMinutes: 5, semantic: "example", progressiveSupports: ["arabic-help", "tip"], visualItems: [{ id: "pathway-scene", word: "pathway", arabic: "مسار", pronunciation: "/ˈpɑːθ.weɪ/", exampleEN: "A pathway connects a goal to practical steps.", exampleAR: "يربط المسار الهدف بخطوات عملية.", imageUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='512' height='320' viewBox='0 0 512 320'%3E%3Crect width='512' height='320' fill='%23eef4ee'/%3E%3Cpath d='M70 245 C165 210 190 120 290 130 S390 92 450 55' fill='none' stroke='%232d6a4f' stroke-width='14' stroke-linecap='round'/%3E%3Ccircle cx='70' cy='245' r='16' fill='%2389b88e'/%3E%3Ccircle cx='290' cy='130' r='16' fill='%2389b88e'/%3E%3Ccircle cx='450' cy='55' r='16' fill='%2389b88e'/%3E%3Ctext x='256' y='292' text-anchor='middle' font-family='Arial' font-size='25' fill='%23213b2d'%3Egoal %E2%86%92 steps %E2%86%92 opportunity%3C/text%3E%3C/svg%3E", altText: "A curved pathway joining a starting point, practical steps, and an opportunity." }] },
    { id: "b1-m10-136-route", kind: "interaction", title: "Choose a realistic first step", titleArabic: "اختر خطوة أولى واقعية", objective: "Separate a long-term ambition from an action that can begin this week.", objectiveArabic: "افصل بين طموح طويل المدى وإجراء يمكن أن يبدأ هذا الأسبوع.", stage: "guided-practice", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Brief", text: "Mina wants to work in design one day. She has two free hours a week, no portfolio yet, and a local library with free computer access.", textArabic: "تريد مينا العمل في التصميم يوماً ما. لديها ساعتان حرتان أسبوعياً، وليس لديها ملف أعمال بعد، ومكتبة محلية تتيح استخدام الحاسوب مجاناً.", purpose: "Identify resources and limits without promising an instant outcome." }, { id: "you", speaker: "You", text: "Her long-term goal is … . A realistic first step would be … because …", textArabic: "هدفها طويل المدى هو … . خطوة أولى واقعية ستكون … لأن …", purpose: "Turn a broad ambition into a practical action." }] }
  ],
  137: [
    { id: "b1-m10-137-forms", kind: "standard", title: "Plan, predict, and arrange", titleArabic: "خطط وتوقّع ورتّب", objective: "Choose will, going to, present continuous, and present simple for a future plan, prediction, arrangement, or timetable.", objectiveArabic: "اختر will وgoing to والمضارع المستمر والمضارع البسيط لخطة أو توقع أو ترتيب أو جدول مستقبلي.", stage: "explanation", estimatedMinutes: 15, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], sentencePatterns: ["I am going to update my portfolio this month.", "I am meeting my mentor on Tuesday.", "The course starts in September.", "I think the project will take longer than expected."] },
    { id: "b1-m10-137-update", kind: "speaking", title: "Give a project update", titleArabic: "قدّم تحديثاً عن مشروع", objective: "Say what is planned, fixed, and uncertain in a short project update.", objectiveArabic: "اذكر ما هو مخطط وثابت وغير مؤكد في تحديث قصير عن مشروع.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [{ id: "model", speaker: "Model", text: "We are meeting the library manager on Wednesday. The workshop starts at ten, and I think we will need an extra volunteer.", textArabic: "سنقابل مدير المكتبة يوم الأربعاء. تبدأ الورشة الساعة العاشرة، وأعتقد أننا سنحتاج إلى متطوع إضافي." }, { id: "you", speaker: "You", text: "Describe a fictional event using one arrangement, one timetable fact, and one prediction.", textArabic: "صف فعالية خيالية مستخدماً ترتيباً واحداً وحقيقة من جدول وتوقعاً واحداً." }] }
  ],
  138: [
    { id: "b1-m10-138-pattern", kind: "reading", title: "Notice how experience supports an application", titleArabic: "لاحظ كيف تدعم الخبرة طلب التقديم", objective: "Notice how a writer links a past action to a present skill without making an unsupported claim.", objectiveArabic: "لاحظ كيف يربط الكاتب عملاً سابقاً بمهارة حالية دون ادعاء غير مدعوم.", stage: "explanation", estimatedMinutes: 14, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "Last autumn, I helped organise a neighbourhood book swap. I contacted three local groups, made a simple timetable, and welcomed visitors on the day. The event taught me how to explain plans clearly and respond when arrangements changed. I would now like to develop these skills in a volunteer role at the community arts centre.", readingTextArabic: "فقرة قصيرة تشرح خبرة سابقة وما المهارة التي اكتسبها الكاتب منها، دون مبالغة.", readingChecks: [{ id: "evidence", type: "detail", prompt: "Which action is evidence that the writer organised the event?", promptArabic: "أي إجراء يعد دليلاً على أن الكاتب نظم الفعالية؟", choices: ["They contacted three local groups.", "They visited an arts centre.", "They changed the event name."], answer: "They contacted three local groups." }, { id: "link", type: "inference", prompt: "Why does the writer mention responding when arrangements changed?", promptArabic: "لماذا يذكر الكاتب الاستجابة لتغير الترتيبات؟", choices: ["To show a relevant skill for the volunteer role.", "To complain about the book swap.", "To avoid naming the event."], answer: "To show a relevant skill for the volunteer role." }] },
    { id: "b1-m10-138-rewrite", kind: "writing", title: "Turn an action into evidence", titleArabic: "حوّل إجراءً إلى دليل", objective: "Write one evidence-based sentence that connects a past action with a skill you can use now.", objectiveArabic: "اكتب جملة مبنية على دليل تربط إجراءً سابقاً بمهارة يمكنك استخدامها الآن.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example"], writingPrompt: "Complete: When I …, I learned how to … . This would help me to … .", writingPromptArabic: "أكمل: عندما …، تعلمت كيف … . سيساعدني ذلك على … .", sentencePatterns: ["When I …, I learned how to …", "This would help me to …"] }
  ],
  139: [
    { id: "b1-m10-139-dialogue", kind: "interaction", title: "Ask for useful pathway advice", titleArabic: "اطلب نصيحة مفيدة عن المسار", objective: "Ask focused follow-up questions about opportunities, requirements, and next actions in a guidance conversation.", objectiveArabic: "اطرح أسئلة متابعة مركزة عن الفرص والمتطلبات والإجراءات التالية في محادثة إرشادية.", stage: "independent-practice", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "transcript"], interactionTurns: [{ id: "adviser", speaker: "Adviser", text: "The programme accepts beginners, but applicants need to show that they can attend regularly for eight weeks.", textArabic: "يقبل البرنامج المبتدئين، لكن على المتقدمين أن يثبتوا قدرتهم على الحضور بانتظام لثمانية أسابيع.", purpose: "Offer a relevant requirement, not a complete answer." }, { id: "you", speaker: "You", text: "Could you tell me …? What would count as evidence that …? If I cannot …, is there another …?", textArabic: "هل يمكنك أن تخبرني …؟ ما الذي سيعد دليلاً على أن …؟ إذا لم أستطع …، فهل يوجد … آخر؟", purpose: "Ask for precise information before deciding." }] }
  ],
  140: [
    { id: "b1-m10-140-hear", kind: "interaction", title: "Hear priorities in a mentor conversation", titleArabic: "استمع إلى الأولويات في محادثة مع مرشد", objective: "Identify a speaker's goal, concern, and agreed next step from a short guidance transcript.", objectiveArabic: "حدّد هدف المتحدث وقلقه والخطوة التالية المتفق عليها من نص إرشادي قصير.", stage: "guided-practice", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["transcript", "word-support"], interactionTurns: [{ id: "learner", speaker: "Learner", text: "I want to apply for the course, but I am worried that my written English is not strong enough yet.", textArabic: "أريد التقدم للدورة، لكنني قلق من أن لغتي الإنجليزية المكتوبة ليست قوية بما يكفي بعد.", purpose: "State a goal and a concern." }, { id: "mentor", speaker: "Mentor", text: "The application asks for a short paragraph, not a perfect essay. Draft it this week, and we can look at the structure together before the deadline.", textArabic: "يطلب التقديم فقرة قصيرة لا مقالاً مثالياً. اكتب مسودة هذا الأسبوع، ويمكننا النظر إلى البنية معاً قبل الموعد النهائي.", purpose: "Give a manageable and time-bound next step." }, { id: "you", speaker: "You", text: "The learner wants to … . The concern is … . They have agreed to … before …", textArabic: "يريد المتعلم أن … . والقلق هو … . وقد اتفقا على … قبل …", purpose: "Summarise the practical agreement accurately." }] }
  ],
  141: [
    { id: "b1-m10-141-detail", kind: "reading", title: "Read an opportunity notice for detail", titleArabic: "اقرأ إعلان فرصة بحثاً عن التفاصيل", objective: "Identify eligibility, commitment, support, and an unanswered question in a realistic opportunity notice.", objectiveArabic: "حدّد الأهلية والالتزام والدعم وسؤالاً بلا إجابة في إعلان فرصة واقعي.", stage: "explanation", estimatedMinutes: 16, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "Neighbourhood Makers is offering a six-week introduction to digital fabrication for people aged 18–25 who live in the borough. Sessions take place on Tuesday evenings from 6–8 pm. No previous technical experience is required, and travel costs can be discussed with the coordinator. Participants will create a small portfolio project and present it at a local showcase. Applications close on 4 October.", readingTextArabic: "إعلان فرصة قصير يحتوي على شروط والتزام ودعم محتمل وتفاصيل يجب التحقق منها.", readingChecks: [{ id: "eligibility", type: "detail", prompt: "Who can apply for the programme?", promptArabic: "من يمكنه التقدم للبرنامج؟", choices: ["People aged 18–25 who live in the borough.", "Anyone who has a technical degree.", "Only people who own fabrication equipment."], answer: "People aged 18–25 who live in the borough." }, { id: "question", type: "inference", prompt: "Which question would a careful applicant still need to ask?", promptArabic: "أي سؤال يحتاج المتقدم الحريص إلى طرحه؟", choices: ["How travel-cost support is arranged.", "Whether the programme has six weeks.", "Whether there is a closing date."], answer: "How travel-cost support is arranged." }] }
  ],
  142: [
    { id: "b1-m10-142-paragraph", kind: "writing", title: "Write a connected pathway paragraph", titleArabic: "اكتب فقرة مترابطة عن المسار", objective: "Write 130–160 words explaining a realistic next step, supporting evidence, a likely challenge, and a response.", objectiveArabic: "اكتب 130–160 كلمة تشرح خطوة تالية واقعية ودليلاً داعماً وتحدياً محتملاً واستجابة له.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 130–160 words about a fictional learner's next pathway. Explain their goal, give one piece of evidence from past experience, name a likely challenge, and describe what they are going to do next. Use because, although, and so that to connect your ideas.", writingPromptArabic: "اكتب 130–160 كلمة عن المسار التالي لمتعلم خيالي. اشرح هدفه وقدّم دليلاً واحداً من خبرة سابقة واذكر تحدياً محتملاً وصف ما سيفعله لاحقاً. استخدم because وalthough وso that لربط الأفكار.", suggestedVocabulary: ["pathway", "evidence", "challenge", "deadline", "goal"], sentencePatterns: ["My goal is to …", "Although …, I am going to …", "I will … so that …"] }
  ],
  143: [
    { id: "b1-m10-143-compare", kind: "interaction", title: "Compare two future pathways", titleArabic: "قارن بين مسارين مستقبليين", objective: "Compare two feasible pathways by weighing access, time, cost, and likely learning without claiming that one is perfect.", objectiveArabic: "قارن بين مسارين قابلين للتنفيذ بموازنة الوصول والوقت والتكلفة والتعلم المحتمل دون الادعاء أن أحدهما مثالي.", stage: "independent-practice", estimatedMinutes: 15, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "options", speaker: "Options", text: "Pathway A is a free online course with flexible study hours but no local tutor. Pathway B is a short evening course with feedback from a tutor, but it costs £40 and requires travel.", textArabic: "المسار أ دورة مجانية عبر الإنترنت بساعات دراسة مرنة ولكن دون مرشد محلي. المسار ب دورة مسائية قصيرة مع ملاحظات من مرشد، لكنها تكلف 40 جنيهاً وتتطلب السفر.", purpose: "Present two feasible pathways with different advantages and limits." }, { id: "you", speaker: "You", text: "Pathway A is more …, whereas Pathway B offers … . For someone who …, I would recommend … because …", textArabic: "المسار أ أكثر …، بينما يقدم المسار ب … . لشخص …، أوصي بـ … لأن …", purpose: "Make a context-sensitive recommendation." }] }
  ],
  144: [
    { id: "b1-m10-144-repair", kind: "interaction", title: "Repair an overconfident claim", titleArabic: "أصلح ادعاءً مفرط الثقة", objective: "Replace an absolute statement about a pathway with an accurate, evidence-aware explanation.", objectiveArabic: "استبدل عبارة مطلقة عن مسار بشرح دقيق يراعي الأدلة.", stage: "guided-practice", estimatedMinutes: 12, semantic: "common-mistake", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "claim", speaker: "Claim", text: "This short course will guarantee a job in design.", textArabic: "ستضمن هذه الدورة القصيرة وظيفة في التصميم.", purpose: "Show an unsupported promise that should be repaired." }, { id: "you", speaker: "You", text: "The course may help learners to …, but it cannot guarantee … . It could be useful because …", textArabic: "قد تساعد الدورة المتعلمين على …، لكنها لا يمكن أن تضمن … . وقد تكون مفيدة لأنها …", purpose: "Make a useful claim without exaggeration." }] },
    { id: "b1-m10-144-rewrite", kind: "writing", title: "Write a measured course description", titleArabic: "اكتب وصفاً متزناً للدورة", objective: "Rewrite a promise as an accurate two-sentence description of possible benefit and one limitation.", objectiveArabic: "أعد كتابة وعد على شكل وصف دقيق من جملتين لفائدة ممكنة وقيد واحد.", stage: "guided-practice", estimatedMinutes: 7, semantic: "activity", progressiveSupports: ["worked-example"], writingPrompt: "Write two sentences: what the course may help a learner develop, and what it cannot promise.", writingPromptArabic: "اكتب جملتين: ما الذي قد تساعد الدورة المتعلم على تطويره وما الذي لا يمكنها وعده به.", suggestedVocabulary: ["may", "could", "develop", "opportunity", "guarantee"] }
  ],
  145: [
    { id: "b1-m10-145-purpose", kind: "speaking", title: "Present a next-step plan", titleArabic: "قدّم خطة للخطوة التالية", objective: "Give a one-minute plan that states a goal, evidence, a timetable, and one request for support.", objectiveArabic: "قدّم خطة لمدة دقيقة تذكر هدفاً ودليلاً وجدولاً زمنياً وطلباً واحداً للدعم.", stage: "independent-practice", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [{ id: "structure", speaker: "Structure", text: "My goal is … . I have already … . I am going to … by … . Could you advise me on …?", textArabic: "هدفي هو … . لقد … بالفعل. سأقوم بـ … بحلول … . هل يمكنك نصحي بشأن …؟" }, { id: "you", speaker: "You", text: "Present a fictional next-step plan to a mentor. Aim for clarity, not an impressive story.", textArabic: "قدّم خطة خيالية للخطوة التالية إلى مرشد. استهدف الوضوح لا قصة مثيرة للإعجاب." }] }
  ],
  146: [
    { id: "b1-m10-146-network", kind: "review", title: "Retrieve the pathway network", titleArabic: "استرجع شبكة المسار", objective: "Retrieve linked vocabulary for goals, evidence, support, applications, and constraints in a new planning context.", objectiveArabic: "استرجع مفردات مترابطة للأهداف والأدلة والدعم والطلبات والقيود في سياق تخطيط جديد.", stage: "review", estimatedMinutes: 12, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], sentencePatterns: ["One possible pathway is …", "The evidence for this is …", "Before the deadline, I need to …", "It would be useful to ask a mentor …"] },
    { id: "b1-m10-146-transfer", kind: "speaking", title: "Use the network in a new context", titleArabic: "استخدم الشبكة في سياق جديد", objective: "Use three retrieved expressions to plan for a different person and situation without reciting definitions.", objectiveArabic: "استخدم ثلاثة تعبيرات مسترجعة للتخطيط لشخص وموقف مختلفين دون ترديد التعريفات.", stage: "independent-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["tip"], speakingLines: [{ id: "prompt", speaker: "Prompt", text: "A friend wants to start a small community garden. Explain one pathway, one piece of evidence they could collect, and one person they could ask for support.", textArabic: "يريد صديق بدء حديقة مجتمعية صغيرة. اشرح مساراً واحداً ودليلاً يمكنه جمعه وشخصاً يمكنه طلب دعمه." }] }
  ],
  147: [
    { id: "b1-m10-147-visual", kind: "visual-vocabulary", title: "See the pathway-support evidence", titleArabic: "شاهد دليل دعم المسار", objective: "Connect feedback, an application, a deadline, and support before interpreting a limited survey.", objectiveArabic: "اربط الملاحظات وطلب التقديم والموعد النهائي والدعم قبل تفسير مسح محدود.", stage: "introduction", estimatedMinutes: 6, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: [{ id: "feedback", word: "feedback", arabic: "ملاحظات", pronunciation: "/ˈfiːd.bæk/", exampleEN: "Feedback can improve an application paragraph.", exampleAR: "يمكن للملاحظات أن تحسن فقرة طلب التقديم.", imageUrl: "data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='512' height='320' viewBox='0 0 512 320'%3E%3Crect width='512' height='320' fill='%23edf4ff'/%3E%3Crect x='110' y='55' width='292' height='190' rx='18' fill='%23ffffff' stroke='%234767a8' stroke-width='8'/%3E%3Cpath d='M155 110h150M155 150h190M155 190h110' stroke='%234767a8' stroke-width='10' stroke-linecap='round'/%3E%3Ccircle cx='360' cy='198' r='34' fill='%2389b4e8'/%3E%3Cpath d='M344 198l11 11 23-27' fill='none' stroke='%23ffffff' stroke-width='9' stroke-linecap='round' stroke-linejoin='round'/%3E%3C/svg%3E", altText: "A written application page with clear feedback marks and a confirmation tick." }] },
    { id: "b1-m10-147-source", kind: "reading", title: "Interpret a short pathway source", titleArabic: "فسّر مصدراً قصيراً عن مسار", objective: "Distinguish what a short destination survey shows, what it cannot show, and what a team plans to test next.", objectiveArabic: "ميّز بين ما يظهره مسح قصير عن الوجهات وما لا يمكنه إظهاره وما يخطط الفريق لاختباره لاحقاً.", stage: "explanation", estimatedMinutes: 15, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A college surveyed 60 recent learners about the support they found most useful when applying for further study or work. Forty-two respondents chose feedback on application paragraphs, while 29 chose practice interviews. The survey did not ask learners who had left the course early. The college will run two short support sessions next term and compare attendance with completion of applications.", readingTextArabic: "ملخص مسح قصير يبيّن ما تقوله البيانات المحدودة وما يحتاج إلى اختبار لاحق.", readingChecks: [{ id: "detail", type: "detail", prompt: "Which support did forty-two respondents choose?", promptArabic: "أي دعم اختاره اثنان وأربعون مشاركاً؟", choices: ["Feedback on application paragraphs.", "Practice interviews only.", "Travel to college."], answer: "Feedback on application paragraphs." }, { id: "limit", type: "inference", prompt: "Why should the college be cautious about generalising the results?", promptArabic: "لماذا ينبغي أن يكون المعهد حذراً عند تعميم النتائج؟", choices: ["Learners who left early were not asked.", "The survey had no respondents.", "The support sessions have already finished."], answer: "Learners who left early were not asked." }] }
  ],
  148: [
    { id: "b1-m10-148-revise", kind: "writing", title: "Draft and revise a pathway message", titleArabic: "صغ وراجع رسالة عن المسار", objective: "Write a connected pathway message and revise one sentence that makes a claim stronger than the evidence allows.", objectiveArabic: "اكتب رسالة مترابطة عن المسار وراجع جملة تجعل الادعاء أقوى مما تسمح به الأدلة.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 140–170 words to a fictional mentor about your next pathway. Explain your goal, mention one relevant experience, ask one focused question, and describe your next action. Revise one sentence so it uses may, could, or likely instead of making a guarantee.", writingPromptArabic: "اكتب 140–170 كلمة إلى مرشد خيالي عن مسارك التالي. اشرح هدفك واذكر خبرة ذات صلة واطرح سؤالاً مركزاً وصف إجراءك التالي. راجع جملة واحدة لتستخدم may أو could أو likely بدلاً من تقديم ضمان.", suggestedVocabulary: ["pathway", "application", "evidence", "mentor", "likely"], sentencePatterns: ["I am writing to ask …", "One relevant experience is …", "I am likely to …", "Could you advise me on …?"] },
    { id: "b1-m10-148-reply", kind: "interaction", title: "Clarify a mentor reply", titleArabic: "وضّح رد المرشد", objective: "Ask one respectful follow-up question after receiving incomplete pathway advice.", objectiveArabic: "اطرح سؤال متابعة محترماً بعد تلقي نصيحة غير مكتملة عن المسار.", stage: "guided-practice", estimatedMinutes: 6, semantic: "activity", progressiveSupports: ["transcript"], interactionTurns: [{ id: "mentor", speaker: "Mentor", text: "Your experience is relevant; check the placement requirements before you apply.", textArabic: "خبرتك ذات صلة؛ تحقق من متطلبات الفرصة قبل التقديم.", purpose: "Provide limited but useful guidance that warrants a focused follow-up." }, { id: "you", speaker: "You", text: "Could you clarify which requirement I should check first?", textArabic: "هل يمكنك توضيح أي متطلب ينبغي أن أتحقق منه أولاً؟", purpose: "Ask for the next actionable detail without repeating the adviser’s words." }] }
  ],
  149: [
    { id: "b1-m10-149-task", kind: "interaction", title: "Solve a realistic pathway task", titleArabic: "حل مهمة واقعية عن المسار", objective: "Build a feasible application plan with a deadline, evidence, support request, and contingency for a practical constraint.", objectiveArabic: "ابنِ خطة تقديم قابلة للتنفيذ بموعد نهائي ودليل وطلب دعم وخطة بديلة لقيد عملي.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Brief", text: "You have ten days to apply for a youth project. The form needs a 150-word statement and one reference. You have worked on a school event, but your teacher is away until next Monday. You can visit the library on two evenings.", textArabic: "لديك عشرة أيام للتقدم لمشروع للشباب. يحتاج النموذج إلى بيان من 150 كلمة ومرجع واحد. عملت في فعالية مدرسية، لكن معلمك غائب حتى الاثنين المقبل. يمكنك زيارة المكتبة مساءين.", purpose: "Present time, evidence, and access constraints." }, { id: "you", speaker: "You", text: "By …, I will … . I can use … as evidence. I will ask … for a reference. If …, I will …", textArabic: "بحلول …، سأقوم بـ … . يمكنني استخدام … دليلاً. سأطلب من … مرجعاً. إذا …، فسأقوم بـ …", purpose: "Create a specific plan with a contingency." }] },
    { id: "b1-m10-149-say", kind: "speaking", title: "Say the plan aloud", titleArabic: "قل الخطة بصوت عالٍ", objective: "Rehearse a concise deadline, evidence, and contingency update.", objectiveArabic: "تدرّب على تحديث موجز يتضمن موعداً نهائياً ودليلاً وخطة بديلة.", stage: "independent-practice", estimatedMinutes: 5, semantic: "activity", progressiveSupports: ["tip"], speakingLines: [{ id: "prompt", speaker: "Prompt", text: "By Friday, I will … . If I cannot …, I will …", textArabic: "بحلول الجمعة، سأقوم بـ … . إذا لم أستطع …، فسأقوم بـ …" }] }
  ],
  150: [
    { id: "b1-m10-150-brief", kind: "reading", title: "Read the placement brief", titleArabic: "اقرأ موجز الفرصة", objective: "Identify one requirement and one practical limitation in the checkpoint scenario.", objectiveArabic: "حدّد متطلباً واحداً وقيداً عملياً واحداً في سيناريو التحقق.", stage: "introduction", estimatedMinutes: 5, semantic: "example", progressiveSupports: ["word-support"], readingText: "The community-centre placement lasts four Saturday mornings. Applicants should explain one relevant experience and arrange their own travel. A mentor will give feedback on one draft application, but the placement cannot guarantee later employment.", readingTextArabic: "موجز قصير يوضح المتطلبات والدعم وحدود الفرصة.", readingChecks: [{ id: "requirement", type: "detail", prompt: "What should applicants explain?", promptArabic: "ماذا ينبغي أن يشرح المتقدمون؟", choices: ["One relevant experience.", "A guaranteed job.", "A travel discount."], answer: "One relevant experience." }] },
    { id: "b1-m10-150-checkpoint", kind: "assessment", title: "Future pathways and projects checkpoint", titleArabic: "نقطة تحقق: المسارات والمشروعات المستقبلية", objective: "Use evidence, measured future language, accurate comparison, and a practical plan to explain a realistic next pathway.", objectiveArabic: "استخدم الدليل ولغة مستقبلية متدرجة ومقارنة دقيقة وخطة عملية لشرح مسار تالٍ واقعي.", stage: "assessment", estimatedMinutes: 24, semantic: "assessment", progressiveSupports: ["tip"], writingPrompt: "A fictional community centre is offering a small project placement. Write 160–200 words recommending whether a learner should apply. Refer to one relevant experience, explain one practical constraint, compare the placement with another pathway, state a realistic next step, and include one careful sentence that does not overpromise the result.", writingPromptArabic: "يقدم مركز مجتمعي خيالي فرصة مشروع صغيرة. اكتب 160–200 كلمة توصي فيها بما إذا كان ينبغي لمتعلم التقدم. أشر إلى خبرة ذات صلة واشرح قيداً عملياً وقارن الفرصة بمسار آخر واذكر خطوة تالية واقعية وضمّن جملة حذرة لا تعد بنتيجة مضمونة.", suggestedVocabulary: ["pathway", "evidence", "constraint", "application", "deadline"], sentencePatterns: ["One relevant experience is …", "Although …, …", "If the learner applies …, they may …", "A realistic next step would be …"] }
  ],
};
