import type { LessonActivity } from "./types";

const scene = (label: string, tint = "#315775") => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420"><rect width="720" height="420" rx="30" fill="${tint}"/><circle cx="122" cy="126" r="62" fill="#f5cb67"/><path d="M85 315c30-93 84-133 151-133s122 40 152 133" fill="#f7f2e8" opacity=".92"/><text x="364" y="142" text-anchor="middle" fill="#fff" font-family="Arial" font-size="36" font-weight="700">${label}</text><text x="364" y="192" text-anchor="middle" fill="#dbe9ee" font-family="Arial" font-size="22">Look · compare · explain</text></svg>`)}`;

const visualWords = (lesson: number, items: Array<[string, string, string]>) => items.map(([word, arabic, example], index) => ({
  id: `b1-m2-${lesson}-visual-${index + 1}`,
  word,
  arabic,
  pronunciation: word,
  exampleEN: example,
  exampleAR: "استخدم الكلمة لوصف معنى محدد في السياق.",
  imageUrl: scene(word, index % 2 ? "#7c4e3c" : "#315775"),
  altText: `Illustrated concept card for ${word}`,
  category: "Relationships and society",
  interactionHint: "Read the example, then say why this word is useful here.",
}));

export const B1_MODULE_2_AUTHORED_ACTIVITIES: Record<number, readonly LessonActivity[]> = {
  16: [
    { id: "b1-m2-16-survey", kind: "reading", title: "Read beyond the survey result", titleArabic: "اقرأ ما وراء نتيجة الاستبيان", objective: "Separate a supported finding from a claim the data cannot prove.", objectiveArabic: "ميّز بين نتيجة تدعمها البيانات وادعاء لا تستطيع البيانات إثباته.", stage: "explanation", estimatedMinutes: 12, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A neighbourhood survey received 84 replies. Sixty-one respondents said that the 8:10 bus was often late. However, the survey did not include people who travel after 9:30 or residents who do not use the bus. The group can report a concern about the 8:10 service, but it cannot claim that every local route is unreliable.", readingTextArabic: "استبيان قصير عن خدمة الحافلات وحدود ما يمكن أن تثبته البيانات.", readingChecks: [
      { id: "finding", type: "detail", prompt: "Which claim is directly supported?", promptArabic: "أي ادعاء تدعمه البيانات مباشرة؟", choices: ["The 8:10 bus is often late for many respondents.", "Every local bus is unreliable.", "Nobody travels after 9:30."], answer: "The 8:10 bus is often late for many respondents." },
      { id: "limit", type: "inference", prompt: "Why should the group be cautious?", promptArabic: "لماذا يجب أن تكون المجموعة حذرة؟", choices: ["The survey has limits in who replied.", "The bus company wrote the survey.", "There were no results."], answer: "The survey has limits in who replied." },
    ] },
    { id: "b1-m2-16-email", kind: "writing", title: "Recommend a careful next step", titleArabic: "اقترح خطوة تالية بحذر", objective: "Write a short, evidence-based recommendation that names uncertainty.", objectiveArabic: "اكتب توصية قصيرة مبنية على دليل وتذكر جانب عدم اليقين.", stage: "independent-practice", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Write 90–110 words to the neighbourhood group: state one result, explain one limitation, and recommend a cautious next step. Use may, might, or could at least twice.", writingPromptArabic: "اكتب 90–110 كلمة للمجموعة: اذكر نتيجة وحداً واحداً واقترح خطوة تالية بحذر.", suggestedVocabulary: ["respondents", "suggest", "limitation", "may indicate", "collect further data"], sentencePatterns: ["The survey suggests that …", "However, it may not show …", "The group could …"] },
  ],
  17: [
    { id: "b1-m2-17-custom", kind: "visual-vocabulary", title: "Name a custom with respect", titleArabic: "صف عادةً باحترام", objective: "Use respectful language for traditions without presenting one choice as universal.", objectiveArabic: "استخدم لغة محترمة للتقاليد دون تقديم اختيار واحد كأنه عالمي.", stage: "introduction", estimatedMinutes: 9, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(17, [["custom", "عادة", "This custom helps relatives stay connected."], ["background", "خلفية ثقافية", "People from different backgrounds may celebrate differently."], ["whereas", "بينما", "Whereas some families meet weekly, others meet on holidays."]]) },
    { id: "b1-m2-17-share", kind: "speaking", title: "Share one everyday tradition", titleArabic: "تحدث عن تقليد يومي", objective: "Explain a personal custom and acknowledge another valid choice.", objectiveArabic: "اشرح عادة شخصية واعترف بأن اختيارات أخرى صحيحة أيضاً.", stage: "real-context", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example"], speakingLines: [
      { id: "model", speaker: "Model", text: "In my family, we usually eat together on Friday. It matters because it gives us time to talk, although other families may prefer a different routine.", textArabic: "في عائلتي نتناول الطعام معاً يوم الجمعة عادة. هذا مهم لأنه يمنحنا وقتاً للحديث، رغم أن عائلات أخرى قد تفضل روتيناً مختلفاً." },
      { id: "prompt", speaker: "You", text: "Describe one custom, why it matters to you, and one respectful contrast.", textArabic: "صف عادة واحدة وسبب أهميتها لك ومقارنة محترمة واحدة." },
    ] },
  ],
  18: [
    { id: "b1-m2-18-review-map", kind: "standard", title: "Build a fair review", titleArabic: "ابنِ مراجعة عادلة", objective: "Notice how a review balances summary, evidence, evaluation, and recommendation.", objectiveArabic: "لاحظ كيف توازن المراجعة بين الملخص والدليل والتقييم والتوصية.", stage: "guided-practice", estimatedMinutes: 10, semantic: "grammar", progressiveSupports: ["worked-example"], sentencePatterns: ["The film explores …", "What worked especially well was …", "I would recommend it to …, although …"] },
    { id: "b1-m2-18-review", kind: "writing", title: "Review with a point of view", titleArabic: "اكتب مراجعة ذات رأي", objective: "Write a concise review supported by concrete examples and a clear recommendation.", objectiveArabic: "اكتب مراجعة موجزة تدعمها أمثلة محددة وتوصية واضحة.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["tip", "external-ai-prompt"], writingPrompt: "Write a 140–180-word review for a student magazine about a book, film, exhibition, or cultural experience. Give two examples and end with a recommendation that includes one limitation.", writingPromptArabic: "اكتب مراجعة من 140–180 كلمة لمجلة طلابية عن كتاب أو فيلم أو تجربة ثقافية مع مثالين وتوصية متوازنة.", suggestedVocabulary: ["engaging", "thought-provoking", "uneven", "portray", "worth seeing"], sentencePatterns: ["Although …, the experience succeeds because …", "I would recommend it to readers who …"] },
  ],
  19: [
    { id: "b1-m2-19-progress", kind: "interaction", title: "Ask for useful feedback", titleArabic: "اطلب ملاحظات مفيدة", objective: "Explain recent learning progress and make two specific requests for support.", objectiveArabic: "اشرح تقدّمك في التعلم واطلب نوعين محددين من الدعم.", stage: "guided-practice", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [
      { id: "tutor", speaker: "Tutor", text: "What have you been working on recently?", textArabic: "ما الذي تعمل عليه مؤخراً؟", purpose: "Invite a precise progress report." },
      { id: "learner", speaker: "Learner", text: "I have been recording short summaries, and I have noticed that my paragraphs are clearer. Could you give me feedback on my linking words?", textArabic: "كنت أسجل ملخصات قصيرة ولاحظت أن فقراتي أصبحت أوضح. هل يمكنك أن تعطيني ملاحظات عن أدوات الربط؟", purpose: "Use present perfect continuous and request feedback." },
      { id: "follow-up", speaker: "Tutor", text: "Yes. What else would help you progress?", textArabic: "نعم. ما الذي سيساعدك أيضاً على التقدم؟", purpose: "Elicit a second targeted request." },
    ] },
  ],
  20: [
    { id: "b1-m2-20-career", kind: "speaking", title: "Prepare a career conversation", titleArabic: "استعد لمحادثة مهنية", objective: "Connect qualifications, experience, goals, and a realistic next step in a professional exchange.", objectiveArabic: "اربط بين مؤهلاتك وخبرتك وأهدافك وخطوة تالية واقعية في حديث مهني.", stage: "real-context", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["word-support", "worked-example"], speakingLines: [
      { id: "advisor", speaker: "Advisor", text: "What kind of work are you aiming for?", textArabic: "ما نوع العمل الذي تهدف إليه؟" },
      { id: "you", speaker: "You", text: "I have worked in customer service, and I am interested in training roles. I might take a short course before applying for a supervisor position.", textArabic: "عملت في خدمة العملاء وأنا مهتم بأدوار التدريب. قد آخذ دورة قصيرة قبل التقدم لوظيفة مشرف." },
    ] },
    { id: "b1-m2-20-email", kind: "writing", title: "Follow up professionally", titleArabic: "تابع بشكل مهني", objective: "Turn a spoken career goal into an organised, polite email request.", objectiveArabic: "حوّل هدفاً مهنياً شفهياً إلى طلب بريد منظم ومهذب.", stage: "independent-practice", estimatedMinutes: 16, semantic: "activity", progressiveSupports: ["external-ai-prompt"], writingPrompt: "Write 140–180 words to a career adviser. Summarise relevant experience, state your goal, and ask which course or next step might be useful.", writingPromptArabic: "اكتب 140–180 كلمة لمستشار مهني عن خبرتك وهدفك والخطوة أو الدورة المحتملة.", suggestedVocabulary: ["qualification", "relevant experience", "career goal", "could lead to", "advice"], sentencePatterns: ["I am writing to ask for …", "This experience may help me …"] },
  ],
  21: [
    { id: "b1-m2-21-disruption", kind: "reading", title: "Follow a changed travel plan", titleArabic: "تتبّع خطة سفر تغيّرت", objective: "Trace what happened, what the traveller had already done, and what solution is reasonable.", objectiveArabic: "تتبّع ما حدث وما فعله المسافر مسبقاً والحل المعقول.", stage: "explanation", estimatedMinutes: 12, semantic: "example", progressiveSupports: ["word-support"], readingText: "Maya arrived at the airport after she had checked in online. Her flight was cancelled because of severe weather. She had already booked a hotel at her destination, so she asked the airline to move her to the earliest available flight or explain how she could claim compensation. The agent offered a flight the next morning and a meal voucher.", readingTextArabic: "رسالة عن تعطّل سفر توضح التسلسل والأثر والطلب المحدد.", readingChecks: [
      { id: "sequence", type: "detail", prompt: "What had Maya done before she arrived?", promptArabic: "ماذا فعلت مايا قبل وصولها؟", choices: ["She checked in online.", "She changed her hotel.", "She claimed compensation."], answer: "She checked in online." },
      { id: "reasonable", type: "inference", prompt: "Why is Maya’s request specific and reasonable?", promptArabic: "لماذا طلب مايا محدد ومعقول؟", choices: ["It explains the impact and asks for a practical option.", "It ignores the cancellation.", "It asks the agent to book any flight."], answer: "It explains the impact and asks for a practical option." },
    ] },
    { id: "b1-m2-21-repair", kind: "interaction", title: "Request a travel solution", titleArabic: "اطلب حلاً للسفر", objective: "Make a polite, specific request after explaining disruption and impact.", objectiveArabic: "قدّم طلباً مهذباً ومحدداً بعد شرح التعطل والأثر.", stage: "real-context", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example"], interactionTurns: [
      { id: "agent", speaker: "Airline agent", text: "How has the cancellation affected your plans?", textArabic: "كيف أثّر الإلغاء في خططك؟", purpose: "Elicit a concise impact statement." },
      { id: "request", speaker: "Traveller", text: "I had already booked accommodation, so I would appreciate the earliest possible alternative or clear advice about compensation.", textArabic: "كنت قد حجزت الإقامة بالفعل، لذلك أقدّر توفير أقرب بديل ممكن أو نصيحة واضحة حول التعويض.", purpose: "Model a clear, polite request." },
    ] },
  ],
  22: [
    { id: "b1-m2-22-effects", kind: "visual-vocabulary", title: "See a small choice spread", titleArabic: "شاهد أثر الاختيار الصغير", objective: "Describe immediate and wider effects of one practical community action.", objectiveArabic: "صف الآثار المباشرة والأوسع لفعل عملي واحد في المجتمع.", stage: "introduction", estimatedMinutes: 9, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(22, [["pilot", "تجربة أولية", "The street could run a one-month pilot."], ["trade-off", "مفاضلة", "Every plan has a benefit and a trade-off."], ["ripple effect", "أثر متسلسل", "A safer crossing can have a ripple effect for local shops."]]) },
    { id: "b1-m2-22-proposal", kind: "writing", title: "Propose one local action", titleArabic: "اقترح إجراءً محلياً", objective: "Write a modest proposal that makes a condition and acknowledges a trade-off.", objectiveArabic: "اكتب مقترحاً متواضعاً يذكر شرطاً ويعترف بمفاضلة.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Write 140–180 words to a local councillor proposing one small action for your street. Explain the likely benefit, one trade-off, and what could happen if the plan were tried for one month.", writingPromptArabic: "اكتب 140–180 كلمة لمجلس محلي تقترح إجراءً صغيراً وتذكر الفائدة والمفاضلة ونتيجة محتملة للتجربة.", suggestedVocabulary: ["pilot", "benefit", "trade-off", "if implemented", "monitor"], sentencePatterns: ["If the council ran a pilot, … could …", "One possible drawback is …"] },
  ],
  23: [
    { id: "b1-m2-23-debate", kind: "speaking", title: "Make room for disagreement", titleArabic: "اترك مساحة للاختلاف", objective: "State a position, concede one reasonable concern, and return to a recommendation.", objectiveArabic: "اذكر موقفك واعترف بقلق معقول ثم عد إلى توصيتك.", stage: "guided-practice", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [
      { id: "stance", speaker: "You", text: "On balance, I support the traffic scheme because it may make the centre safer.", textArabic: "في المجمل، أؤيد خطة المرور لأنها قد تجعل المركز أكثر أماناً." },
      { id: "concession", speaker: "You", text: "I understand that some shop owners are concerned about deliveries; however, a timed access plan could reduce that problem.", textArabic: "أتفهم أن بعض أصحاب المتاجر قلقون بشأن التوصيل؛ لكن خطة وصول في أوقات محددة قد تخفف المشكلة." },
    ] },
    { id: "b1-m2-23-letter", kind: "writing", title: "Write a balanced recommendation", titleArabic: "اكتب توصية متوازنة", objective: "Develop a civic opinion with evidence, concession, and a clear conclusion.", objectiveArabic: "طوّر رأياً مدنياً بدليل واعتراف بنقطة مقابلة وخلاصة واضحة.", stage: "independent-practice", estimatedMinutes: 18, semantic: "assessment", progressiveSupports: ["external-ai-prompt"], writingPrompt: "Write 140–180 words to the town council about a proposed traffic scheme. Give two reasons, concede one sensible objection, and end with a recommendation.", writingPromptArabic: "اكتب 140–180 كلمة لمجلس المدينة عن خطة مرور مع سببين واعتراض معقول وتوصية.", suggestedVocabulary: ["on balance", "evidence", "concede", "access", "recommend"], sentencePatterns: ["Although …, I believe …", "A practical response would be …"] },
  ],
  24: [
    { id: "b1-m2-24-next", kind: "writing", title: "Plan the next chapter", titleArabic: "خطّط للفصل القادم", objective: "Reflect on a past experience and set out future steps with confidence and realism.", objectiveArabic: "تأمل تجربة سابقة وحدد خطوات مستقبلية بثقة وواقعية.", stage: "real-context", estimatedMinutes: 15, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Write a 140–180-word email to a close friend about your next chapter. Reflect on one experience, explain a decision, and describe two next steps using two different future forms.", writingPromptArabic: "اكتب رسالة 140–180 كلمة لصديق عن فصلك القادم: تأمل تجربة وقراراً وخطوتين قادمتين.", suggestedVocabulary: ["reflect on", "decide", "going to", "arranged to", "next step"], sentencePatterns: ["Looking back, I realise …", "I am going to …, and I am meeting … next week."] },
  ],
  25: [
    { id: "b1-m2-25-purpose", kind: "speaking", title: "Speak with a social purpose", titleArabic: "تحدث لغرض اجتماعي", objective: "Give a structured spoken response about how relationships shape local society.", objectiveArabic: "قدّم استجابة شفهية منظمة عن أثر العلاقات في المجتمع المحلي.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["tip", "word-support"], speakingLines: [
      { id: "opening", speaker: "Opening", text: "Strong local relationships are not only personal; they can make practical support easier to organise.", textArabic: "العلاقات المحلية القوية ليست شخصية فقط؛ بل يمكنها أن تجعل تنظيم الدعم العملي أسهل." },
      { id: "challenge", speaker: "Challenge", text: "Add two developed points, one example, and one limitation before your closing recommendation.", textArabic: "أضف نقطتين مطورتين ومثالاً وحداً واحداً قبل توصيتك الختامية." },
    ] },
  ],
  26: [
    { id: "b1-m2-26-network", kind: "review", title: "Reconnect the relationship network", titleArabic: "راجع شبكة العلاقات", objective: "Retrieve key words and organise them by support, disagreement, belonging, and cooperation.", objectiveArabic: "استرجع الكلمات الرئيسية ونظمها حسب الدعم والاختلاف والانتماء والتعاون.", stage: "review", estimatedMinutes: 11, semantic: "retrieval", progressiveSupports: ["word-support"], suggestedVocabulary: ["mutual", "boundary", "belonging", "compromise", "contribute", "reliable"], sentencePatterns: ["A healthy relationship depends on …", "A community works better when …"] },
  ],
  27: [
    { id: "b1-m2-27-source", kind: "reading", title: "Interpret a short community source", titleArabic: "فسّر مصدراً مجتمعياً قصيراً", objective: "Distinguish a source’s central claim, its evidence, and a missing perspective.", objectiveArabic: "ميّز بين الادعاء المركزي للمصدر ودليله ومنظور مفقود.", stage: "explanation", estimatedMinutes: 13, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A youth centre reported that attendance at its weekly workshops had doubled in six months. The report linked this increase to free transport vouchers and peer invitations. It also noted that the centre had not yet asked non-attenders why they chose not to participate. The programme appears promising, but its full reach is still unclear.", readingTextArabic: "تقرير قصير عن مركز شباب يوضح دليلاً وحدوداً في الوقت نفسه.", readingChecks: [
      { id: "claim", type: "main-idea", prompt: "What is the report’s main message?", promptArabic: "ما الرسالة الرئيسية للتقرير؟", choices: ["The workshops appear promising but need broader evidence.", "Every young person attends the workshops.", "Transport does not matter."], answer: "The workshops appear promising but need broader evidence." },
      { id: "gap", type: "inference", prompt: "What information is missing?", promptArabic: "ما المعلومات الناقصة؟", choices: ["Why non-attenders did not join.", "The workshop timetable.", "The name of the centre."], answer: "Why non-attenders did not join." },
    ] },
  ],
  28: [
    { id: "b1-m2-28-revise", kind: "writing", title: "Draft, test, revise", titleArabic: "اكتب وراجع", objective: "Improve a short social argument by revising one unclear claim and one inappropriate register choice.", objectiveArabic: "حسّن حجة اجتماعية قصيرة بمراجعة ادعاء غير واضح وخيار أسلوبي غير مناسب.", stage: "independent-practice", estimatedMinutes: 16, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Draft 150–170 words about one change that could help people feel more connected locally. Then label one sentence you revised for clarity and one you revised for register.", writingPromptArabic: "اكتب 150–170 كلمة عن تغيير يساعد الناس على الشعور بترابط محلي أكبر، ثم حدد جملة راجعتها للوضوح وأخرى للأسلوب.", suggestedVocabulary: ["connection", "initiative", "accessible", "take part", "as a result"], sentencePatterns: ["One useful initiative would be …", "This could matter because …"] },
  ],
  29: [
    { id: "b1-m2-29-solve", kind: "interaction", title: "Solve a shared-space problem", titleArabic: "حل مشكلة مساحة مشتركة", objective: "Negotiate a practical solution by making a proposal, a condition, and a compromise.", objectiveArabic: "تفاوض على حل عملي عبر تقديم مقترح وشرط وتسوية.", stage: "real-context", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["worked-example", "transcript"], interactionTurns: [
      { id: "neighbour", speaker: "Neighbour A", text: "The shared room is too noisy after 8 p.m.", textArabic: "الغرفة المشتركة صاخبة جداً بعد الساعة الثامنة مساءً.", purpose: "State a specific problem." },
      { id: "proposal", speaker: "Neighbour B", text: "If we reserve quiet time after 8, people could still book earlier sessions. Would that be a fair compromise?", textArabic: "إذا خصصنا وقت هدوء بعد الثامنة، يمكن للناس حجز جلسات أبكر. هل سيكون ذلك حلاً وسطاً عادلاً؟", purpose: "Offer a conditional compromise." },
      { id: "agreement", speaker: "Neighbour A", text: "That seems reasonable, provided the timetable is clear.", textArabic: "يبدو ذلك معقولاً، بشرط أن يكون الجدول واضحاً.", purpose: "Accept with a condition." },
    ] },
  ],
  30: [
    { id: "b1-m2-30-brief", kind: "assessment", title: "Relationships and society checkpoint", titleArabic: "تقييم العلاقات والمجتمع", objective: "Use module language to make a respectful, evidence-aware recommendation for a local community issue.", objectiveArabic: "استخدم لغة الوحدة لتقديم توصية محترمة ومدركة للدليل لقضية محلية.", stage: "assessment", estimatedMinutes: 22, semantic: "assessment", progressiveSupports: ["tip", "external-ai-prompt"], writingPrompt: "Choose a realistic local issue involving relationships or community participation. Write 160–220 words with an opening, two developed points, one concession or limitation, and a final recommendation. Revise one sentence for clarity and one for register.", writingPromptArabic: "اختر قضية محلية واقعية تتعلق بالعلاقات أو المشاركة المجتمعية. اكتب 160–220 كلمة بمقدمة ونقطتين وتنازل أو حد وتوصية نهائية، ثم راجع جملتين.", suggestedVocabulary: ["participation", "evidence", "compromise", "inclusive", "on balance", "recommend"], sentencePatterns: ["The available evidence suggests …", "Although …, a balanced response would be …"] },
    { id: "b1-m2-30-reflect", kind: "review", title: "Name your next transfer", titleArabic: "حدد تطبيقك القادم", objective: "Identify one language choice to reuse in a future workplace, travel, or community situation.", objectiveArabic: "حدد اختياراً لغوياً واحداً ستعيد استخدامه في موقف عمل أو سفر أو مجتمع لاحق.", stage: "review", estimatedMinutes: 5, semantic: "retrieval", progressiveSupports: ["tip"], sentencePatterns: ["Next time I need to disagree respectfully, I will …"] },
  ],
};
