import type { LessonActivity } from "./types";

const scene = (label: string, tint = "#315775") => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420"><rect width="720" height="420" rx="30" fill="${tint}"/><path d="M74 310c70-108 142-162 218-162s154 54 232 162" fill="#f7f2e8" opacity=".9"/><circle cx="122" cy="114" r="56" fill="#f5cb67"/><path d="M410 91h208v116H410z" fill="#dbe9ee" opacity=".92"/><text x="364" y="135" text-anchor="middle" fill="#fff" font-family="Arial" font-size="34" font-weight="700">${label}</text><text x="364" y="184" text-anchor="middle" fill="#dbe9ee" font-family="Arial" font-size="21">Notice · adapt · explain</text></svg>`)}`;

const visualWords = (lesson: number, items: Array<[string, string, string]>) => items.map(([word, arabic, example], index) => ({
  id: `b1-m3-${lesson}-visual-${index + 1}`,
  word,
  arabic,
  pronunciation: word,
  exampleEN: example,
  exampleAR: "استخدم الكلمة لتشرح تغيّراً أو خياراً حقيقياً في السياق.",
  imageUrl: scene(word, index % 2 ? "#7a4a3a" : "#315775"),
  altText: `Illustrated travel and change concept card for ${word}`,
  category: "Travel and change",
  interactionHint: "Read the example, then connect the word to a change you know.",
}));

export const B1_MODULE_3_AUTHORED_ACTIVITIES: Record<number, readonly LessonActivity[]> = {
  31: [
    { id: "b1-m3-31-map", kind: "visual-vocabulary", title: "Map a journey of change", titleArabic: "ارسم خريطة لرحلة تغيّر", objective: "Use precise language to separate a trigger, an adjustment, and an outcome.", objectiveArabic: "استخدم لغة دقيقة للتمييز بين السبب والتكيّف والنتيجة.", stage: "introduction", estimatedMinutes: 10, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(31, [["departure", "مغادرة", "The departure marked the beginning of a difficult adjustment."], ["settle in", "يتأقلم", "It took her several weeks to settle in."], ["unexpected", "غير متوقع", "An unexpected delay changed the whole route."]]) },
    { id: "b1-m3-31-story", kind: "speaking", title: "Tell the change in three moves", titleArabic: "احكِ التغيّر في ثلاث مراحل", objective: "Give a short connected account of a travel or life change.", objectiveArabic: "قدّم رواية قصيرة مترابطة عن سفر أو تغيّر في الحياة.", stage: "real-context", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example"], speakingLines: [{ id: "model", speaker: "Model", text: "When I moved for study, the first week was confusing. Gradually, I found a routine and began to feel at home.", textArabic: "عندما انتقلت للدراسة، كان الأسبوع الأول مربكاً. تدريجياً وجدت روتيناً وبدأت أشعر أنني في مكان مألوف." }, { id: "you", speaker: "You", text: "Describe one change: what started it, how you adapted, and what changed afterwards.", textArabic: "صف تغيراً واحداً: ما الذي بدأه، وكيف تكيّفت، وما الذي تغيّر بعد ذلك." }] },
  ],
  32: [
    { id: "b1-m3-32-language", kind: "standard", title: "Choose the language of adjustment", titleArabic: "اختر لغة التكيّف", objective: "Notice how present perfect, past simple, and change verbs give a clear timeline.", objectiveArabic: "لاحظ كيف تعطي أزمنة الحاضر التام والماضي البسيط وأفعال التغيّر خطاً زمنياً واضحاً.", stage: "explanation", estimatedMinutes: 11, semantic: "grammar", progressiveSupports: ["worked-example", "tip"], sentencePatterns: ["Since arriving, I have become more independent.", "At first, I found the commute difficult, but it became easier.", "The move has changed how I plan my week."] },
    { id: "b1-m3-32-advice", kind: "writing", title: "Give grounded moving advice", titleArabic: "قدّم نصيحة واقعية عن الانتقال", objective: "Write a helpful response that balances preparation with uncertainty.", objectiveArabic: "اكتب رداً مساعداً يوازن بين الاستعداد وعدم اليقين.", stage: "independent-practice", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Write 100–130 words to a friend who is moving to a new city for the first time. Give three practical suggestions, explain one likely adjustment, and avoid promising that everything will be easy.", writingPromptArabic: "اكتب 100–130 كلمة لصديق ينتقل إلى مدينة جديدة. قدّم ثلاث نصائح عملية واشرح تكيّفاً متوقعاً دون وعود مبالغ فيها.", suggestedVocabulary: ["settle in", "routine", "initially", "gradually", "keep an open mind"], sentencePatterns: ["You may find that … at first.", "One thing that helped me was …"] },
  ],
  33: [
    { id: "b1-m3-33-notice", kind: "reading", title: "Notice what had changed", titleArabic: "لاحظ ما الذي كان قد تغيّر", objective: "Interpret how past perfect marks an earlier event in a travel narrative.", objectiveArabic: "فسّر كيف يحدد الماضي التام حدثاً أسبق في قصة سفر.", stage: "explanation", estimatedMinutes: 12, semantic: "example", progressiveSupports: ["word-support", "extended-rationale"], readingText: "By the time Farid reached the station, the platform had changed. The earlier train had left, and the information board had been updated. Because he had saved the new timetable on his phone, he could quickly choose another route instead of panicking.", readingTextArabic: "نص قصير يوضح كيف نذكر حدثاً أسبق ثم نبيّن أثره في قرار سفر جديد.", readingChecks: [{ id: "earlier", type: "detail", prompt: "Which event happened before Farid reached the station?", promptArabic: "أي حدث وقع قبل وصول فريد إلى المحطة؟", choices: ["The earlier train left.", "Farid chose a new route.", "Farid reached the station."], answer: "The earlier train left." }, { id: "effect", type: "inference", prompt: "Why could Farid react calmly?", promptArabic: "لماذا استطاع فريد أن يتصرف بهدوء؟", choices: ["He had prepared useful information.", "The station closed early.", "He ignored the change."], answer: "He had prepared useful information." }] },
  ],
  34: [
    { id: "b1-m3-34-dialogue", kind: "interaction", title: "Re-plan a changed journey", titleArabic: "أعد تخطيط رحلة تغيّرت", objective: "Clarify a changed plan, suggest an alternative, and check agreement.", objectiveArabic: "وضّح خطة تغيّرت واقترح بديلاً وتحقق من الاتفاق.", stage: "guided-practice", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "friend", speaker: "Friend", text: "I thought we were meeting at the museum, but I have just seen that it is closed today.", textArabic: "ظننت أننا سنلتقي في المتحف، لكنني رأيت للتو أنه مغلق اليوم.", purpose: "Present a change without blame." }, { id: "reply", speaker: "You", text: "Thanks for letting me know. Shall we meet at the library café instead, or would tomorrow be easier for you?", textArabic: "شكراً لإخباري. هل نلتقي في مقهى المكتبة بدلاً من ذلك، أم أن الغد أسهل لك؟", purpose: "Offer a flexible alternative." }, { id: "check", speaker: "Friend", text: "The library café works. What time should we aim for?", textArabic: "مقهى المكتبة مناسب. ما الوقت الذي نستهدفه؟", purpose: "Confirm the revised plan." }] },
  ],
  35: [
    { id: "b1-m3-35-respond", kind: "speaking", title: "Hear the update and respond", titleArabic: "استمع إلى التحديث واستجب", objective: "Respond to a delayed announcement with a calm, practical question.", objectiveArabic: "استجب لإعلان تأخير بسؤال هادئ وعملي.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["transcript", "word-support"], speakingLines: [{ id: "announcement", speaker: "Announcement", text: "Passengers for the 14:20 service: the departure has been delayed by forty minutes because of a signal problem.", textArabic: "للركاب في خدمة 14:20: تم تأخير المغادرة أربعين دقيقة بسبب مشكلة في الإشارة." }, { id: "response", speaker: "You", text: "Could you tell me whether the connection at Central Station will still be possible?", textArabic: "هل يمكنك أن تخبرني إن كان الانتقال في المحطة المركزية سيظل ممكناً؟" }] },
  ],
  36: [
    { id: "b1-m3-36-detail", kind: "reading", title: "Read a relocation diary for detail", titleArabic: "اقرأ يوميات انتقال بتفصيل", objective: "Trace concrete challenges, strategies, and changes in a connected account.", objectiveArabic: "تتبّع التحديات والاستراتيجيات والتغيّرات في رواية مترابطة.", stage: "explanation", estimatedMinutes: 15, semantic: "example", progressiveSupports: ["word-support"], readingText: "In her first month in Manchester, Salma spent too much time travelling because she had chosen a flat without testing the bus route at rush hour. Rather than moving again, she changed her schedule, joined a car-share group twice a week, and began working from the library on Fridays. The journey is still longer than she would like, but the changes have made it manageable and helped her meet people outside work.", readingTextArabic: "يوميات انتقال عن تحدٍّ عملي وخطوات تكيف واقعية ونتيجة غير مثالية لكنها مفيدة.", readingChecks: [{ id: "challenge", type: "detail", prompt: "What practical difficulty did Salma face?", promptArabic: "ما الصعوبة العملية التي واجهتها سلمى؟", choices: ["Her commute was too long.", "She could not find work.", "The library was closed."], answer: "Her commute was too long." }, { id: "judgement", type: "inference", prompt: "Which description best fits the ending?", promptArabic: "أي وصف يناسب النهاية؟", choices: ["A partial solution with wider benefits.", "A perfect solution with no cost.", "A problem that she ignored."], answer: "A partial solution with wider benefits." }] },
  ],
  37: [
    { id: "b1-m3-37-paragraph", kind: "writing", title: "Write a connected change paragraph", titleArabic: "اكتب فقرة مترابطة عن تغيير", objective: "Organise a 130–160-word paragraph around change, response, and reflection.", objectiveArabic: "نظّم فقرة من 130–160 كلمة حول تغيير واستجابة وتأمل.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Write 130–160 words about a change to a journey, routine, school, work, or neighbourhood. Explain what was different, how you responded, and what you would do differently next time. Use at least four sequencing or contrast links.", writingPromptArabic: "اكتب 130–160 كلمة عن تغيير في رحلة أو روتين أو دراسة أو عمل أو حي. اشرح ما الذي اختلف وكيف استجبت وما الذي ستفعله بشكل مختلف لاحقاً.", suggestedVocabulary: ["initially", "as a result", "whereas", "eventually", "adapt"], sentencePatterns: ["At first, … whereas …", "As a result, I decided to …"] },
  ],
  38: [
    { id: "b1-m3-38-compare", kind: "interaction", title: "Compare two routes honestly", titleArabic: "قارن بين مسارين بصدق", objective: "Compare two travel or relocation choices using criteria, trade-offs, and a reasoned choice.", objectiveArabic: "قارن بين خيارين للسفر أو الانتقال باستخدام معايير ومفاضلات واختيار مبرر.", stage: "real-context", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "option-a", speaker: "Partner", text: "Route A is cheaper, but it involves two changes and may be unreliable in winter.", textArabic: "المسار أ أرخص، لكنه يتضمن تبديلين وقد لا يكون موثوقاً في الشتاء.", purpose: "Present a trade-off." }, { id: "reason", speaker: "You", text: "Although Route B costs more, I would choose it because it is direct and gives us a better chance of arriving on time.", textArabic: "رغم أن المسار ب يكلف أكثر، سأختاره لأنه مباشر ويمنحنا فرصة أفضل للوصول في الوقت." , purpose: "Make a qualified choice." }] },
  ],
  39: [
    { id: "b1-m3-39-repair", kind: "interaction", title: "Repair a travel misunderstanding", titleArabic: "أصلح سوء فهم في السفر", objective: "Clarify an assumption, acknowledge the confusion, and agree a next action.", objectiveArabic: "وضّح افتراضاً واعترف بالالتباس واتفق على الخطوة التالية.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "misunderstanding", speaker: "Host", text: "I understood that you were arriving on Friday evening, not Saturday morning.", textArabic: "فهمت أنك ستصل مساء الجمعة لا صباح السبت.", purpose: "State the mismatch neutrally." }, { id: "repair", speaker: "You", text: "I am sorry — I should have checked the date more carefully. I meant Saturday morning. Would it help if I booked a nearby hotel for Friday night?", textArabic: "أعتذر، كان ينبغي أن أتحقق من التاريخ بدقة أكبر. كنت أقصد صباح السبت. هل يساعد أن أحجز فندقاً قريباً لليلة الجمعة؟", purpose: "Take responsibility and suggest a repair." }] },
  ],
  40: [
    { id: "b1-m3-40-purpose", kind: "speaking", title: "Give a practical travel briefing", titleArabic: "قدّم إحاطة سفر عملية", objective: "Give a structured one-minute briefing for a visitor with reasons for each recommendation.", objectiveArabic: "قدّم إحاطة منظمة لمدة دقيقة لزائر مع أسباب لكل توصية.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["word-support", "worked-example"], speakingLines: [{ id: "structure", speaker: "Plan", text: "Start with the most important change, then give transport, timing, and one backup option.", textArabic: "ابدأ بأهم تغيير ثم قدّم النقل والتوقيت وخياراً احتياطياً واحداً." }, { id: "prompt", speaker: "You", text: "Brief a visitor whose usual route is unavailable today. Explain what they should do, why, and what to do if the first option fails.", textArabic: "قدّم إحاطة لزائر لا يتوفر مساره المعتاد اليوم. اشرح ما الذي ينبغي فعله ولماذا وما العمل إذا فشل الخيار الأول." }] },
  ],
  41: [
    { id: "b1-m3-41-network", kind: "review", title: "Reconnect the travel-and-change network", titleArabic: "أعد ربط شبكة السفر والتغيّر", objective: "Retrieve words and chunks by role: movement, disruption, adjustment, and outcome.", objectiveArabic: "استرجع الكلمات والعبارات بحسب دورها: حركة وتعطل وتكيف ونتيجة.", stage: "review", estimatedMinutes: 11, semantic: "retrieval", progressiveSupports: ["arabic-help", "word-support"], sentencePatterns: ["The disruption meant that …", "I adjusted by …", "In the long run, …"] },
  ],
  42: [
    { id: "b1-m3-42-source", kind: "reading", title: "Interpret a short travel source", titleArabic: "فسّر مصدراً قصيراً عن السفر", objective: "Distinguish an official travel update from one traveller’s interpretation.", objectiveArabic: "ميّز بين تحديث سفر رسمي وتفسير مسافر واحد.", stage: "explanation", estimatedMinutes: 13, semantic: "example", progressiveSupports: ["tip", "extended-rationale"], readingText: "Official update: From Monday, the bridge will close for six weeks. A replacement shuttle will run every thirty minutes between 6:00 and 22:00. Traveller post: ‘The town will be impossible to reach.’ The official update confirms a disruption, but it does not prove that every journey will be impossible. People should check the shuttle timetable and allow extra time before making a decision.", readingTextArabic: "مصدر قصير يقارن بين تحديث رسمي وتفسير مبالغ فيه لمسافر.", readingChecks: [{ id: "official", type: "detail", prompt: "Which fact comes from the official update?", promptArabic: "أي حقيقة تأتي من التحديث الرسمي؟", choices: ["A replacement shuttle will operate.", "The town will be impossible to reach.", "Every journey will take six weeks."], answer: "A replacement shuttle will operate." }, { id: "evaluation", type: "inference", prompt: "Why is the traveller post too strong?", promptArabic: "لماذا منشور المسافر مبالغ فيه؟", choices: ["It turns a disruption into an unsupported certainty.", "It gives the shuttle timetable.", "It quotes the official source exactly."], answer: "It turns a disruption into an unsupported certainty." }] },
  ],
  43: [
    { id: "b1-m3-43-revise", kind: "writing", title: "Draft, test, and revise a change message", titleArabic: "اكتب رسالة تغيير ثم اختبرها وراجعها", objective: "Revise a practical message for clarity, tone, and a usable next action.", objectiveArabic: "راجع رسالة عملية من أجل الوضوح والنبرة والخطوة التالية القابلة للتنفيذ.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Draft a 120–150-word message to a group whose weekend plan must change. State the change, explain only the relevant reason, offer two options, and end with a clear question. Then revise one sentence to sound calmer and more direct.", writingPromptArabic: "اكتب مسودة رسالة من 120–150 كلمة لمجموعة يجب أن تتغير خطتها. اذكر التغيير والسبب المناسب وخيارين وأنهِ بسؤال واضح، ثم راجع جملة لتصبح أهدأ وأكثر مباشرة.", suggestedVocabulary: ["unfortunately", "alternative", "available", "confirm", "work around"], sentencePatterns: ["Because …, we will need to …", "Would you prefer … or …?"] },
  ],
  44: [
    { id: "b1-m3-44-task", kind: "interaction", title: "Solve a relocation-day problem", titleArabic: "حل مشكلة يوم الانتقال", objective: "Plan a calm response to two linked practical problems with priorities and contingencies.", objectiveArabic: "خطط لاستجابة هادئة لمشكلتين عمليتين مرتبطتين مع أولويات وخطط بديلة.", stage: "real-context", estimatedMinutes: 16, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Situation", text: "Your train is delayed, the letting agent closes in ninety minutes, and your phone battery is low. You have a friend’s number and a portable charger in your bag.", textArabic: "قطارك متأخر ووكيل السكن يغلق بعد تسعين دقيقة وبطارية هاتفك منخفضة. لديك رقم صديق وشاحن محمول في الحقيبة.", purpose: "Present linked constraints." }, { id: "plan", speaker: "You", text: "First, I would charge my phone and contact the agent with my updated arrival time. If I could not arrive before closing, I would ask whether my friend could collect the key or whether a later arrangement was possible.", textArabic: "أولاً سأشحن هاتفي وأتصل بالوكيل بوقت وصولي الجديد. إذا لم أستطع الوصول قبل الإغلاق، فسأسأل هل يمكن لصديقي استلام المفتاح أو ترتيب وقت لاحق.", purpose: "Prioritise and offer contingencies." }] },
  ],
  45: [
    { id: "b1-m3-45-checkpoint", kind: "assessment", title: "Travel and change checkpoint", titleArabic: "تقييم السفر والتغيّر", objective: "Show that you can interpret a change, choose a response, and communicate it clearly for an audience.", objectiveArabic: "أظهر أنك تستطيع تفسير تغير واختيار استجابة والتواصل بها بوضوح لجمهور محدد.", stage: "assessment", estimatedMinutes: 22, semantic: "assessment", progressiveSupports: ["tip", "external-ai-prompt"], writingPrompt: "A visiting colleague has a cancelled train, a meeting tomorrow morning, and two possible alternatives. Write 150–190 words: compare the alternatives, recommend one with reasons and one limitation, then draft the key message they should send to the organiser.", writingPromptArabic: "لدى زميل زائر قطار ملغى واجتماع صباح الغد وبديلان. اكتب 150–190 كلمة تقارن البديلين وتوصي بأحدهما مع سبب وحد واحد، ثم صغ الرسالة الأساسية التي يرسلها للمنظم.", suggestedVocabulary: ["disruption", "alternative", "reliable", "manage", "confirm"], sentencePatterns: ["Given that …, the most reliable option would be …", "Although …, it would still allow …"] },
  ],
};
