import type { LessonActivity } from "./types";

const scene = (label: string, tint = "#47665a") => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420"><rect width="720" height="420" rx="30" fill="${tint}"/><path d="M90 326h540" stroke="#c9dfbf" stroke-width="22" stroke-linecap="round"/><path d="M170 326V190l78-70 78 70v136M396 326V162l68-58 68 58v164" fill="#f5f0e6"/><path d="M248 180c14-62 68-92 111-108-7 62-42 106-111 108Z" fill="#b7d891"/><path d="M235 246h42m-21-21v42M440 226h48m-24-24v48" stroke="${tint}" stroke-width="15" stroke-linecap="round"/><text x="360" y="64" text-anchor="middle" fill="#fff" font-family="Arial" font-size="29" font-weight="700">${label}</text></svg>`)}`;

const visualWords = (lesson: number, items: Array<[string, string, string]>) => items.map(([word, arabic, example], index) => ({
  id: `b1-m7-${lesson}-visual-${index + 1}`,
  word,
  arabic,
  pronunciation: word,
  exampleEN: example,
  exampleAR: "استخدم الكلمة لتشرح مشكلة بيئية أو خطوة مجتمعية بصورة دقيقة وعملية.",
  imageUrl: scene(word, index % 2 ? "#5c806e" : "#47665a"),
  altText: `Illustrated Environment and Community Action concept card for ${word}`,
  category: "Environment and community action",
  interactionHint: "Name the relationship: problem, resource, action, result, or community role.",
}));

export const B1_MODULE_7_AUTHORED_ACTIVITIES: Record<number, readonly LessonActivity[]> = {
  91: [
    { id: "b1-m7-91-map", kind: "visual-vocabulary", title: "Map a local environmental system", titleArabic: "ارسم خريطة لنظام بيئي محلي", objective: "Connect a resource, a form of waste, a community action, and a result in one local example.", objectiveArabic: "اربط مورداً ونوعاً من النفايات وعملاً مجتمعياً ونتيجة في مثال محلي واحد.", stage: "introduction", estimatedMinutes: 12, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(91, [["renewable", "متجدد", "The library chose renewable electricity for its roof project."], ["resource", "مورد", "Clean water is a shared resource, not an unlimited supply."], ["waste", "نفايات", "Food waste increased after the event because portions were too large."]]) },
    { id: "b1-m7-91-link", kind: "speaking", title: "Explain one connected local issue", titleArabic: "اشرح قضية محلية مترابطة", objective: "Use because or although to link one local problem to a realistic response.", objectiveArabic: "استخدم because أو although لربط مشكلة محلية باستجابة واقعية.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example"], speakingLines: [{ id: "model", speaker: "Model", text: "Although the park has enough bins, litter remains because people leave before the evening collection.", textArabic: "مع أن الحديقة فيها حاويات كافية، تبقى النفايات لأن الناس يغادرون قبل جمع المساء." }, { id: "you", speaker: "You", text: "Name a local issue, connect two facts, and suggest one possible response.", textArabic: "اذكر قضية محلية واربط حقيقتين واقترح استجابة ممكنة واحدة." }] },
  ],
  92: [
    { id: "b1-m7-92-language", kind: "standard", title: "Build cause-and-contrast sentences", titleArabic: "ابنِ جملاً للسبب والتباين", objective: "Use because, although, and while to make relationships between environmental ideas clear.", objectiveArabic: "استخدم because وalthough وwhile لجعل العلاقات بين الأفكار البيئية واضحة.", stage: "explanation", estimatedMinutes: 13, semantic: "grammar", progressiveSupports: ["worked-example", "tip"], sentencePatterns: ["The group reduced waste because …", "Although the proposal costs more at first, …", "While one street has trees, another has …"] },
    { id: "b1-m7-92-rewrite", kind: "writing", title: "Connect a campaign note", titleArabic: "اربط ملاحظة عن حملة", objective: "Turn separate campaign facts into a short connected note without overstating the evidence.", objectiveArabic: "حوّل حقائق منفصلة عن حملة إلى ملاحظة قصيرة مترابطة دون المبالغة في الأدلة.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 70–90 words for a neighbourhood notice. Explain why a refill station is being tested, mention one limitation, and invite one practical response. Use at least two linking expressions.", writingPromptArabic: "اكتب 70–90 كلمة لإعلان في الحي. اشرح سبب اختبار محطة إعادة التعبئة، واذكر قيداً واحداً، وادعُ إلى استجابة عملية. استخدم عبارتي ربط على الأقل.", suggestedVocabulary: ["reduce", "trial", "although", "resource", "take part"], sentencePatterns: ["The station is being tested because …", "Although …, residents can …"] },
  ],
  93: [
    { id: "b1-m7-93-notice", kind: "reading", title: "Notice what a claim can prove", titleArabic: "لاحظ ما الذي يمكن أن يثبته الادعاء", objective: "Distinguish a measured result, a hopeful prediction, and a claim that needs more evidence.", objectiveArabic: "ميّز بين نتيجة مقاسة وتوقع متفائل وادعاء يحتاج إلى أدلة أكثر.", stage: "explanation", estimatedMinutes: 14, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A residents’ group reported that its monthly repair café kept 180 small appliances out of landfill during its first six months. A volunteer then wrote, ‘Our neighbourhood has solved its waste problem.’ The group’s coordinator changed the sentence before publication. She explained that the figure showed one useful result, while other waste streams still needed attention. The report invited residents to bring broken items, record what was repaired, and suggest what the next session should improve.", readingTextArabic: "نص قصير يفرق بين نتيجة محددة وادعاء أوسع من الأدلة المتاحة.", readingChecks: [{ id: "detail", type: "detail", prompt: "What had the repair café done in its first six months?", promptArabic: "ماذا حقق مقهى الإصلاح خلال الأشهر الستة الأولى؟", choices: ["Kept 180 small appliances out of landfill.", "Solved all neighbourhood waste.", "Opened a new landfill."], answer: "Kept 180 small appliances out of landfill." }, { id: "inference", type: "inference", prompt: "Why did the coordinator change the volunteer’s sentence?", promptArabic: "لماذا غيّرت المنسقة جملة المتطوع؟", choices: ["It claimed more than the evidence showed.", "It lacked a date.", "It was too short."], answer: "It claimed more than the evidence showed." }] },
  ],
  94: [
    { id: "b1-m7-94-dialogue", kind: "interaction", title: "Agree on a small action", titleArabic: "اتفق على عمل صغير", objective: "Suggest an action, recognise a practical concern, and negotiate a next step with a community partner.", objectiveArabic: "اقترح عملاً واعترف بقلق عملي وتفاوض على خطوة تالية مع شريك مجتمعي.", stage: "real-context", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "organiser", speaker: "Organiser", text: "We could ask every shop to stop using single-use bags next month.", textArabic: "يمكننا أن نطلب من كل متجر التوقف عن استخدام الأكياس ذات الاستخدام الواحد الشهر القادم.", purpose: "Offer an ambitious proposal." }, { id: "shopkeeper", speaker: "Shopkeeper", text: "I support the aim, but some customers still need a practical option while they learn the new system.", textArabic: "أؤيد الهدف، لكن بعض الزبائن ما زالوا يحتاجون إلى خيار عملي أثناء تعلمهم للنظام الجديد.", purpose: "Introduce a practical concern." }, { id: "you", speaker: "You", text: "What if we begin with a two-week trial, offer low-cost reusable bags, and collect feedback before making a wider decision?", textArabic: "ما رأيك أن نبدأ بتجربة أسبوعين، ونوفر أكياساً قابلة لإعادة الاستخدام بتكلفة منخفضة، ونجمع الملاحظات قبل اتخاذ قرار أوسع؟", purpose: "Find a realistic shared step." }] },
  ],
  95: [
    { id: "b1-m7-95-respond", kind: "speaking", title: "Hear a concern and respond constructively", titleArabic: "استمع إلى قلق واستجب بصورة بنّاءة", objective: "Identify the speaker’s concern and ask one question that helps make an action more workable.", objectiveArabic: "حدّد قلق المتحدث واسأل سؤالاً يساعد على جعل العمل أكثر قابلية للتنفيذ.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["transcript", "word-support"], speakingLines: [{ id: "speaker", speaker: "Neighbour", text: "The new planting plan sounds positive, but I am worried that volunteers will not be able to water the trees during the summer.", textArabic: "تبدو خطة الزراعة الجديدة إيجابية، لكنني قلق من أن المتطوعين لن يتمكنوا من ري الأشجار في الصيف." }, { id: "you", speaker: "You", text: "That is a useful concern. Which places already have access to water, and could the plan start with those areas?", textArabic: "هذا قلق مفيد. أي الأماكن لديها بالفعل مصدر ماء، وهل يمكن أن تبدأ الخطة بهذه المناطق؟" }] },
  ],
  96: [
    { id: "b1-m7-96-detail", kind: "reading", title: "Read a community-energy proposal", titleArabic: "اقرأ مقترحاً لطاقة مجتمعية", objective: "Trace a proposal’s aim, evidence, cost, and unanswered question in a practical community text.", objectiveArabic: "تتبّع هدف المقترح ودليله وتكلفته وسؤاله غير المجاب عنه في نص مجتمعي عملي.", stage: "explanation", estimatedMinutes: 17, semantic: "example", progressiveSupports: ["word-support"], readingText: "A sports centre is considering solar panels after its electricity bills rose for two years. A feasibility note estimates that the panels could provide roughly one third of the centre’s daytime electricity in summer. The note also explains that installation would require an initial investment and that winter output would be lower. Rather than presenting the proposal as an instant solution, the committee asks members to compare the long-term savings with other priorities, such as repairing the changing rooms. A public meeting will share the full estimate before a decision is made.", readingTextArabic: "نص عملي عن مقترح للطاقة يوازن الفائدة والتكلفة والأسئلة التي ما زالت مفتوحة.", readingChecks: [{ id: "detail", type: "detail", prompt: "What share of daytime electricity could the panels provide in summer?", promptArabic: "ما الحصة التي يمكن أن توفرها الألواح من كهرباء النهار في الصيف؟", choices: ["Roughly one third.", "All of it.", "None of it."], answer: "Roughly one third." }, { id: "inference", type: "inference", prompt: "Why does the committee hold a public meeting?", promptArabic: "لماذا تعقد اللجنة اجتماعاً عاماً؟", choices: ["To share the estimate before deciding between priorities.", "To promise an instant solution.", "To stop repairs to the changing rooms."], answer: "To share the estimate before deciding between priorities." }] },
  ],
  97: [
    { id: "b1-m7-97-paragraph", kind: "writing", title: "Write a connected action paragraph", titleArabic: "اكتب فقرة مترابطة عن عمل", objective: "Develop a balanced paragraph that explains a local action, its likely benefit, and one condition for success.", objectiveArabic: "طوّر فقرة متوازنة تشرح عملاً محلياً وفائدته المحتملة وشرطاً واحداً للنجاح.", stage: "independent-practice", estimatedMinutes: 20, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 140–170 words proposing one realistic environmental or community action for a place you know. Explain the problem, describe the action, give one likely benefit, and name one condition or limitation. Use at least four target words and two connectors.", writingPromptArabic: "اكتب 140–170 كلمة تقترح فيها عملاً بيئياً أو مجتمعياً واقعياً لمكان تعرفه. اشرح المشكلة وصف العمل واذكر فائدة محتملة وشرطاً أو قيداً واحداً. استخدم أربع كلمات مستهدفة على الأقل وأداتي ربط.", suggestedVocabulary: ["resource", "reduce", "renewable", "participate", "practical", "although"], sentencePatterns: ["One practical response would be to …", "This could …, although …"] },
  ],
  98: [
    { id: "b1-m7-98-compare", kind: "interaction", title: "Compare two routes to cleaner travel", titleArabic: "قارن بين طريقين لنقل أنظف", objective: "Compare two transport actions against impact, access, cost, and time rather than choosing a universally best option.", objectiveArabic: "قارن بين عملي نقل من حيث الأثر والوصول والتكلفة والوقت دون اختيار خيار أفضل للجميع.", stage: "real-context", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "option-a", speaker: "Option A", text: "Create protected cycling routes near the station.", textArabic: "أنشئ مسارات دراجات محمية قرب المحطة.", purpose: "Present an active-travel option." }, { id: "option-b", speaker: "Option B", text: "Increase the evening bus service for routes that have no safe cycling connection.", textArabic: "زد خدمة الحافلات المسائية للطرق التي لا ترتبط بمسار دراجات آمن.", purpose: "Present a public-transport option." }, { id: "you", speaker: "You", text: "Cycling routes may reduce short car trips, whereas evening buses may improve access for different residents. For …, I would prioritise … because …", textArabic: "قد تقلل مسارات الدراجات الرحلات القصيرة بالسيارة، بينما قد تحسن الحافلات المسائية الوصول لمقيمين مختلفين. بالنسبة إلى … سأعطي الأولوية لـ … لأن …", purpose: "Make a contextual comparison." }] },
  ],
  99: [
    { id: "b1-m7-99-repair", kind: "interaction", title: "Repair a misunderstanding about priorities", titleArabic: "أصلح سوء فهم حول الأولويات", objective: "Clarify a proposal without dismissing another person’s concern or presenting a false choice.", objectiveArabic: "وضّح مقترحاً دون رفض قلق شخص آخر أو تقديم اختيار زائف.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["worked-example", "transcript"], interactionTurns: [{ id: "message", speaker: "Resident", text: "So you care about planting flowers more than you care about people who need affordable food?", textArabic: "إذن أنت تهتم بزراعة الأزهار أكثر من اهتمامك بمن يحتاجون إلى طعام بأسعار معقولة؟", purpose: "Present a false either-or interpretation." }, { id: "you", speaker: "You", text: "I can see why it sounded that way. I am not suggesting that one need should replace the other; I am asking whether the unused space can support a small food-growing project alongside the existing support service.", textArabic: "أفهم لماذا بدا الأمر كذلك. لا أقترح أن تحل حاجة محل الأخرى؛ أسأل إن كانت المساحة غير المستخدمة يمكن أن تدعم مشروعاً صغيراً لزراعة الغذاء بجانب خدمة الدعم الحالية.", purpose: "Clarify scope and keep both concerns visible." }] },
  ],
  100: [
    { id: "b1-m7-100-purpose", kind: "speaking", title: "Make a two-minute proposal", titleArabic: "قدّم مقترحاً لمدة دقيقتين", objective: "Present a practical community idea with a purpose, evidence, a possible obstacle, and a direct request.", objectiveArabic: "قدّم فكرة مجتمعية عملية تتضمن هدفاً ودليلاً وعقبة محتملة وطلباً مباشراً.", stage: "independent-practice", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [{ id: "frame", speaker: "Framework", text: "The issue is …; one useful piece of evidence is …; I propose …; a likely obstacle is …; I am asking the group to …", textArabic: "المشكلة هي …؛ دليل مفيد واحد هو …؛ أقترح …؛ عقبة محتملة هي …؛ أطلب من المجموعة أن …" }, { id: "you", speaker: "You", text: "Choose a real or fictional local issue. Give a two-minute proposal, then state what feedback would help you improve it.", textArabic: "اختر قضية محلية حقيقية أو خيالية. قدّم مقترحاً لمدة دقيقتين ثم اذكر ما الملاحظات التي ستساعدك على تحسينه." }] },
  ],
  101: [
    { id: "b1-m7-101-network", kind: "review", title: "Review the action network", titleArabic: "راجع شبكة العمل", objective: "Retrieve words and phrases by linking issue, evidence, action, stakeholder, and result.", objectiveArabic: "استرجع الكلمات والعبارات بربط القضية والدليل والعمل وصاحب المصلحة والنتيجة.", stage: "review", estimatedMinutes: 12, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], sentencePatterns: ["A resource can be protected by …", "The evidence suggests …, although …", "Residents could take part by …"] },
    { id: "b1-m7-101-retrieval", kind: "speaking", title: "Use three words in a new situation", titleArabic: "استخدم ثلاث كلمات في موقف جديد", objective: "Apply three retrieved items to a different community situation instead of reciting definitions.", objectiveArabic: "طبّق ثلاثة عناصر مسترجعة على موقف مجتمعي مختلف بدلاً من ترديد التعريفات.", stage: "independent-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["tip"], speakingLines: [{ id: "prompt", speaker: "Prompt", text: "A youth centre is running out of water during summer events. Use resource, reduce, and practical to explain one response.", textArabic: "ينفد الماء من مركز شباب أثناء فعاليات الصيف. استخدم resource وreduce وpractical لشرح استجابة واحدة." }] },
  ],
  102: [
    { id: "b1-m7-102-source", kind: "reading", title: "Interpret a short local source", titleArabic: "فسّر مصدراً محلياً قصيراً", objective: "Separate the finding, the limitation, and the decision a short survey can reasonably support.", objectiveArabic: "ميّز بين النتيجة والقيد والقرار الذي يمكن لمسح قصير دعمه بصورة معقولة.", stage: "explanation", estimatedMinutes: 15, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A school survey received 146 responses from families about travelling to morning activities. Sixty percent said they would consider walking more often if there were safer crossings near the main road. The survey did not ask every family, and it did not measure how far people lived from the school. The parent committee therefore proposed a one-month crossing steward trial and a follow-up count of walkers. It did not claim that the survey proved every family could walk.", readingTextArabic: "مصدر قصير يوضح كيف يمكن استخدام نتيجة مسح مع الاعتراف بالقيود.", readingChecks: [{ id: "finding", type: "detail", prompt: "What did sixty percent of respondents say?", promptArabic: "ماذا قال ستون بالمئة من المشاركين؟", choices: ["They would consider walking more with safer crossings.", "They already walked every day.", "They wanted more parking."], answer: "They would consider walking more with safer crossings." }, { id: "inference", type: "inference", prompt: "Why is a one-month trial more reasonable than a permanent claim?", promptArabic: "لماذا تعد التجربة لشهر أكثر معقولية من ادعاء دائم؟", choices: ["The survey has useful findings but also clear limits.", "The school has no families.", "Crossings cannot be changed."], answer: "The survey has useful findings but also clear limits." }] },
  ],
  103: [
    { id: "b1-m7-103-draft", kind: "writing", title: "Draft and revise a civic message", titleArabic: "صغ وراجع رسالة مدنية", objective: "Write a concise request to a local group, then revise one sentence for clarity and one for a cooperative tone.", objectiveArabic: "اكتب طلباً موجزاً لمجموعة محلية ثم راجع جملة للوضوح وأخرى لنبرة تعاونية.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 120–150 words to a local association asking it to consider one practical environmental or community action. Name the issue, provide one observation or small piece of evidence, make a feasible request, and invite a response. Then revise one sentence that sounds too absolute.", writingPromptArabic: "اكتب 120–150 كلمة إلى جمعية محلية تطلب منها النظر في عمل بيئي أو مجتمعي عملي. اذكر القضية وقدّم ملاحظة أو دليلاً صغيراً واطلب طلباً قابلاً للتنفيذ وادعُ إلى رد. ثم راجع جملة تبدو حاسمة أكثر من اللازم.", suggestedVocabulary: ["consider", "evidence", "feasible", "although", "participation"], sentencePatterns: ["I am writing to ask whether …", "One indication is …", "I would welcome your view on …"] },
  ],
  104: [
    { id: "b1-m7-104-task", kind: "interaction", title: "Solve a realistic community task", titleArabic: "حل مهمة مجتمعية واقعية", objective: "Choose a first step for a shared-space problem, explain trade-offs, and assign a check-in point.", objectiveArabic: "اختر خطوة أولى لمشكلة في مساحة مشتركة واشرح المقايضات وحدد نقطة متابعة.", stage: "real-context", estimatedMinutes: 16, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Brief", text: "A shared courtyard has overflowing bins, no clear recycling signs, and limited funds. Residents disagree about whether to buy new bins or start with clearer information and a volunteer rota.", textArabic: "تحتوي ساحة مشتركة على حاويات ممتلئة ولافتات إعادة تدوير غير واضحة وأموال محدودة. يختلف السكان حول شراء حاويات جديدة أو البدء بمعلومات أوضح وجدول متطوعين." , purpose: "Present constraints without a single obvious answer." }, { id: "you", speaker: "You", text: "I would begin with … because … . This does not solve … immediately, although it lets us test … . We should review the result after …", textArabic: "سأبدأ بـ … لأن … . هذا لا يحل … فوراً، لكنه يسمح لنا باختبار … . ينبغي أن نراجع النتيجة بعد …", purpose: "Make a bounded decision with review criteria." }] },
  ],
  105: [
    { id: "b1-m7-105-checkpoint", kind: "assessment", title: "Environment and community checkpoint", titleArabic: "نقطة تحقق: البيئة والعمل المجتمعي", objective: "Use connected language, evidence awareness, and a practical recommendation in a new community-action situation.", objectiveArabic: "استخدم لغة مترابطة ووعياً بالأدلة وتوصية عملية في موقف جديد عن عمل مجتمعي.", stage: "assessment", estimatedMinutes: 22, semantic: "assessment", progressiveSupports: ["tip"], writingPrompt: "A community hall wants to reduce waste at its weekly events. Write 150–180 words recommending a first action. Explain the situation, use one limited piece of evidence, acknowledge one constraint, and end with a request for participation or feedback.", writingPromptArabic: "تريد قاعة مجتمعية تقليل النفايات في فعالياتها الأسبوعية. اكتب 150–180 كلمة توصي فيها بعمل أول. اشرح الموقف واستخدم دليلاً محدوداً واحداً واعترف بقيد واحد وأنهِ بطلب مشاركة أو ملاحظات.", suggestedVocabulary: ["waste", "resource", "reduce", "evidence", "although", "participate"], sentencePatterns: ["The evidence available suggests …", "A sensible first step would be …", "Although …, the group could …"] },
  ],
};
