import type { LessonActivity } from "./types";

/** Explicit learner journeys for B1 Module 9: Problem-solving and Decisions (Lessons 121–135). */
export const B1_MODULE_9_ACTIVITIES: Record<number, LessonActivity[]> = {
  121: [
    { id: "b1-m9-121-map", kind: "visual-vocabulary", title: "Map a decision before choosing", titleArabic: "ارسم خريطة للقرار قبل الاختيار", objective: "Recognise the difference between an option, a priority, a constraint, a consequence, and a compromise in one everyday decision.", objectiveArabic: "ميّز بين الخيار والأولوية والقيد والنتيجة والتسوية في قرار يومي واحد.", stage: "introduction", estimatedMinutes: 13, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: [{ id: "option", word: "option", arabic: "خيار", pronunciation: "/ˈɒp.ʃən/", exampleEN: "Taking the bus is one option.", exampleAR: "ركوب الحافلة خيار واحد." }, { id: "priority", word: "priority", arabic: "أولوية", pronunciation: "/praɪˈɒr.ə.ti/", exampleEN: "Safety is our first priority.", exampleAR: "السلامة هي أولويتنا الأولى." }, { id: "constraint", word: "constraint", arabic: "قيد", pronunciation: "/kənˈstreɪnt/", exampleEN: "Our budget is a constraint.", exampleAR: "ميزانيتنا قيد." }, { id: "consequence", word: "consequence", arabic: "نتيجة", pronunciation: "/ˈkɒn.sɪ.kwəns/", exampleEN: "Every choice has a consequence.", exampleAR: "لكل اختيار نتيجة." }, { id: "compromise", word: "compromise", arabic: "تسوية", pronunciation: "/ˈkɒm.prə.maɪz/", exampleEN: "They reached a compromise.", exampleAR: "توصلوا إلى تسوية." }] },
    { id: "b1-m9-121-brief", kind: "interaction", title: "Name what matters", titleArabic: "حدّد ما يهم", objective: "Sort facts from priorities before suggesting a solution to a shared problem.", objectiveArabic: "صنّف الحقائق والأولويات قبل اقتراح حل لمشكلة مشتركة.", stage: "guided-practice", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Brief", text: "A study group has one quiet room for two hours. Three members need to revise, and one needs to practise a presentation aloud.", textArabic: "لدى مجموعة دراسة غرفة هادئة واحدة لساعتين. يحتاج ثلاثة أعضاء إلى المراجعة ويحتاج عضو واحد إلى التدريب على عرض بصوت عالٍ.", purpose: "Separate the fixed facts from the needs that should guide a decision." }, { id: "you", speaker: "You", text: "One constraint is … . Our priority should be … . A possible compromise is …", textArabic: "أحد القيود هو … . ينبغي أن تكون أولويتنا … . تسوية ممكنة هي …", purpose: "Use the decision language to prepare a fair choice." }] }
  ],
  122: [
    { id: "b1-m9-122-change", kind: "standard", title: "Connect experience to recent change", titleArabic: "اربط الخبرة بالتغيير الحديث", objective: "Choose present perfect forms when an earlier experience still matters now, and distinguish them from finished past events.", objectiveArabic: "اختر صيغة المضارع التام عندما تظل الخبرة السابقة مهمة الآن وميّزها عن أحداث ماضية منتهية.", stage: "explanation", estimatedMinutes: 14, semantic: "grammar", progressiveSupports: ["arabic-help", "worked-example"], sentencePatterns: ["We have tried two options so far.", "The timetable changed last week.", "Have you ever dealt with a similar problem?"] },
    { id: "b1-m9-122-evidence", kind: "speaking", title: "Report what has changed", titleArabic: "اذكر ما الذي تغيّر", objective: "Give a short update that combines one completed event with one present result.", objectiveArabic: "قدّم تحديثاً قصيراً يجمع حدثاً منتهياً ونتيجة حالية واحدة.", stage: "guided-practice", estimatedMinutes: 9, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [{ id: "model", speaker: "Model", text: "We changed the meeting time on Monday, and attendance has improved since then.", textArabic: "غيّرنا وقت الاجتماع يوم الاثنين، وقد تحسن الحضور منذ ذلك الحين." }, { id: "you", speaker: "You", text: "Describe one small change in a fictional project: say when it happened and what result it has produced.", textArabic: "صف تغييراً صغيراً في مشروع خيالي: قل متى حدث وما النتيجة التي نتجت عنه." }] }
  ],
  123: [
    { id: "b1-m9-123-timeline", kind: "reading", title: "Notice the problem in a timeline", titleArabic: "لاحظ المشكلة في خط زمني", objective: "Use past simple and past continuous to reconstruct what was happening when a problem began.", objectiveArabic: "استخدم الماضي البسيط والماضي المستمر لإعادة بناء ما كان يحدث عندما بدأت المشكلة.", stage: "explanation", estimatedMinutes: 14, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "While volunteers were setting up the school fair, the electricity failed. One team looked for the caretaker, while another team moved the food outside. The caretaker arrived ten minutes later and explained that a cable had become loose during the morning delivery.", readingTextArabic: "تقرير قصير يوضح حدثاً مستمراً قاطعه حدث آخر وماذا فعل الناس بعده.", readingChecks: [{ id: "ongoing", type: "detail", prompt: "What were the volunteers doing when the electricity failed?", promptArabic: "ماذا كان المتطوعون يفعلون عندما انقطعت الكهرباء؟", choices: ["They were setting up the fair.", "They were leaving the school.", "They were repairing a cable."], answer: "They were setting up the fair." }, { id: "cause", type: "inference", prompt: "What caused the failure, according to the caretaker?", promptArabic: "ما الذي سبب الانقطاع بحسب العامل؟", choices: ["A loose cable during a delivery.", "The food outside.", "A late school fair."], answer: "A loose cable during a delivery." }] },
    { id: "b1-m9-123-reconstruct", kind: "writing", title: "Reconstruct two moments", titleArabic: "أعد بناء لحظتين", objective: "Write two accurate timeline sentences instead of listing events without connection.", objectiveArabic: "اكتب جملتين دقيقتين عن خط زمني بدلاً من سرد أحداث بلا ترابط.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example"], writingPrompt: "Complete a two-sentence incident report: While the team was …, … happened. After that, … .", writingPromptArabic: "أكمل تقرير حادث من جملتين: بينما كان الفريق …، حدث … . بعد ذلك، … .", sentencePatterns: ["While … was/were …, … happened.", "After that, …"] }
  ],
  124: [
    { id: "b1-m9-124-relay", kind: "interaction", title: "Relay a proposal accurately", titleArabic: "انقل اقتراحاً بدقة", objective: "Report what different people said without changing their meaning or presenting a claim as your own.", objectiveArabic: "انقل ما قاله أشخاص مختلفون دون تغيير المعنى أو تقديم كلامهم على أنه كلامك.", stage: "independent-practice", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "transcript"], interactionTurns: [{ id: "organiser", speaker: "Organiser", text: "I think we should test the new booking system for one month before we replace the old one.", textArabic: "أعتقد أنه ينبغي أن نختبر نظام الحجز الجديد شهراً واحداً قبل استبدال القديم." , purpose: "Provide a cautious proposal to report." }, { id: "volunteer", speaker: "Volunteer", text: "I am worried that some visitors will need help with the new form.", textArabic: "أخشى أن يحتاج بعض الزوار إلى مساعدة في النموذج الجديد.", purpose: "Provide a concern that should not be ignored." }, { id: "you", speaker: "You", text: "The organiser said that … . A volunteer was concerned that … . I suggest that we …", textArabic: "قال المنظم إن … . وكان أحد المتطوعين قلقاً من أن … . أقترح أن …", purpose: "Attribute both views and add one carefully marked recommendation." }] }
  ],
  125: [
    { id: "b1-m9-125-respond", kind: "interaction", title: "Respond to a practical dilemma", titleArabic: "استجب لمأزق عملي", objective: "Use advice, obligation, and possibility modals to suggest a proportionate response rather than an absolute answer.", objectiveArabic: "استخدم أفعال النصح والالتزام والإمكان لاقتراح استجابة متناسبة بدلاً من إجابة مطلقة.", stage: "guided-practice", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["transcript", "tip"], interactionTurns: [{ id: "message", speaker: "Message", text: "The community hall has double-booked Saturday afternoon. Cancelling either group will disappoint people, but both events cannot use the main room.", textArabic: "حجزت القاعة المجتمعية فترة بعد ظهر السبت مرتين. سيخيّب إلغاء أي مجموعة آمال الناس، لكن لا يمكن للحدثين استخدام الغرفة الرئيسية." , purpose: "Present a bounded practical dilemma." }, { id: "you", speaker: "You", text: "We should … . We may be able to … . We must tell both groups …", textArabic: "ينبغي أن … . قد نتمكن من … . يجب أن نخبر المجموعتين …", purpose: "Make advice, possibility, and obligation distinct." }] },
    { id: "b1-m9-125-tone", kind: "speaking", title: "Make advice less absolute", titleArabic: "اجعل النصيحة أقل إطلاقاً", objective: "Practise choosing could, might, should, and must for the strength of the message.", objectiveArabic: "تدرّب على اختيار could وmight وshould وmust بحسب قوة الرسالة.", stage: "guided-practice", estimatedMinutes: 7, semantic: "tip", progressiveSupports: ["worked-example"], speakingLines: [{ id: "prompt", speaker: "Prompt", text: "Say the same idea three ways: a possible option, a recommendation, and a necessary action.", textArabic: "قل الفكرة نفسها بثلاث طرق: خيار ممكن وتوصية وإجراء ضروري." }] }
  ],
  126: [
    { id: "b1-m9-126-proposal", kind: "reading", title: "Read a proposal for useful detail", titleArabic: "اقرأ مقترحاً بحثاً عن التفاصيل المفيدة", objective: "Identify which relative-clause details define a solution and which merely add context.", objectiveArabic: "حدّد تفاصيل جمل الوصل التي تعرّف الحل وتلك التي تضيف سياقاً فقط.", stage: "explanation", estimatedMinutes: 16, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "The library plans to lend small study kits to learners who do not have a quiet place at home. Each kit includes headphones, which can be borrowed for seven days, and a desk lamp that uses very little electricity. The pilot will begin at the branch that has the longest waiting list. Staff will review comments from users before ordering more kits.", readingTextArabic: "مقترح قصير يحتوي على تفاصيل تحدد الأشخاص والأشياء وتفاصيل إضافية عن الحُلول.", readingChecks: [{ id: "define", type: "detail", prompt: "Which learners are the study kits for?", promptArabic: "لمن خُصصت حقائب الدراسة؟", choices: ["Learners who do not have a quiet place at home.", "All library staff.", "Visitors who need a lamp."], answer: "Learners who do not have a quiet place at home." }, { id: "evaluate", type: "inference", prompt: "Why will staff review user comments before ordering more kits?", promptArabic: "لماذا سيراجع الموظفون تعليقات المستخدمين قبل طلب مزيد من الحقائب؟", choices: ["To learn whether the pilot works before expanding it.", "To remove all headphones.", "To shorten the waiting list immediately."], answer: "To learn whether the pilot works before expanding it." }] }
  ],
  127: [
    { id: "b1-m9-127-conditional", kind: "writing", title: "Write a consequence-aware paragraph", titleArabic: "اكتب فقرة تراعي النتائج", objective: "Compare a realistic likely result with an imagined alternative by using first and second conditionals accurately.", objectiveArabic: "قارن نتيجة محتملة واقعية ببديل متخيّل باستخدام الشرط الأول والثاني بدقة.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 130–160 words for a neighbourhood notice. Explain what will happen if residents use a new recycling point, then compare it with what you would do if you had a larger budget. Finish with one practical next step.", writingPromptArabic: "اكتب 130–160 كلمة لإعلان في الحي. اشرح ما سيحدث إذا استخدم السكان نقطة إعادة تدوير جديدة، ثم قارن ذلك بما كنت ستفعله لو كانت لديك ميزانية أكبر. اختم بخطوة عملية واحدة.", suggestedVocabulary: ["consequence", "reduce", "improve", "budget", "if"], sentencePatterns: ["If residents use …, … will …", "If we had …, we would …", "A practical next step is …"] }
  ],
  128: [
    { id: "b1-m9-128-compare", kind: "interaction", title: "Compare two workable choices", titleArabic: "قارن بين خيارين قابلين للتنفيذ", objective: "Evaluate two options with comparatives and degree language while acknowledging a limitation in each.", objectiveArabic: "قيّم خيارين باستخدام المقارنة ودرجة التفضيل مع الاعتراف بقيد في كل منهما.", stage: "real-context", estimatedMinutes: 15, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "options", speaker: "Options", text: "Option A: run a free one-hour online workshop for many people. Option B: run a smaller in-person session with translation support, but only for twenty people.", textArabic: "الخيار أ: ورشة مجانية عبر الإنترنت لمدة ساعة لعدد كبير. الخيار ب: جلسة حضورية أصغر مع دعم ترجمة لكن لعشرين شخصاً فقط.", purpose: "Provide two imperfect but feasible alternatives." }, { id: "you", speaker: "You", text: "Option A is more … than …, whereas Option B is … . Although …, I would choose … because …", textArabic: "الخيار أ أكثر … من …، بينما الخيار ب … . رغم أن …، سأختار … لأن …", purpose: "Make a balanced comparison rather than announce a single obvious answer." }] }
  ],
  129: [
    { id: "b1-m9-129-clarify", kind: "interaction", title: "Repair a misunderstanding in public information", titleArabic: "أصلح سوء فهم في معلومة عامة", objective: "Clarify a misleading passive statement by identifying who is responsible and what action is actually planned.", objectiveArabic: "وضّح عبارة مبنية للمجهول قد تضلل القارئ بتحديد من المسؤول وما الإجراء المخطط فعلاً.", stage: "real-context", estimatedMinutes: 13, semantic: "common-mistake", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "notice", speaker: "Notice", text: "The park entrance will be closed for repairs.", textArabic: "سيُغلق مدخل الحديقة لإجراء إصلاحات.", purpose: "Present public information that leaves out useful responsibility and timing." }, { id: "resident", speaker: "Resident", text: "Does that mean the whole park is closed? Who is doing the repairs?", textArabic: "هل يعني ذلك أن الحديقة كلها مغلقة؟ من سيجري الإصلاحات؟", purpose: "Ask the clarification questions a reader needs." }, { id: "you", speaker: "You", text: "The council will close only the east entrance while a local company repairs the path. The other entrances will remain open.", textArabic: "سيغلق المجلس المدخل الشرقي فقط بينما تصلح شركة محلية الممر. ستبقى المداخل الأخرى مفتوحة.", purpose: "Repair the message with responsible, precise information." }] }
  ],
  130: [
    { id: "b1-m9-130-briefing", kind: "speaking", title: "Give a decision briefing", titleArabic: "قدّم إحاطة عن قرار", objective: "Deliver a one-minute recommendation that distinguishes a planned arrangement from a prediction and gives a reason.", objectiveArabic: "قدّم توصية لمدة دقيقة تميّز بين ترتيب مخطط وتوقّع وتقدم سبباً.", stage: "independent-practice", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], speakingLines: [{ id: "structure", speaker: "Structure", text: "We are meeting …; the team is going to …; I think this will … because …", textArabic: "سنلتقي …؛ سيقوم الفريق بـ …؛ أعتقد أن هذا سوف … لأن …" }, { id: "you", speaker: "You", text: "Recommend a practical first step for a fictional school, club, or workplace problem. Include one arrangement and one prediction.", textArabic: "أوصِ بخطوة أولى عملية لمشكلة خيالية في مدرسة أو نادٍ أو مكان عمل. ضمّن ترتيباً واحداً وتوقعاً واحداً." }] }
  ],
  131: [
    { id: "b1-m9-131-network", kind: "review", title: "Retrieve the decision network", titleArabic: "استرجع شبكة القرار", objective: "Retrieve language for options, constraints, consequences, priorities, and compromise through connected prompts.", objectiveArabic: "استرجع لغة الخيارات والقيود والنتائج والأولويات والتسوية عبر مطالب مترابطة.", stage: "review", estimatedMinutes: 12, semantic: "retrieval", progressiveSupports: ["word-support", "tip"], sentencePatterns: ["One option would be to …", "The main constraint is …", "We decided to … rather than …", "It is worth considering …"] },
    { id: "b1-m9-131-transfer", kind: "speaking", title: "Explain a choice without a script", titleArabic: "اشرح اختياراً دون نص جاهز", objective: "Use three retrieved expressions in a new context without repeating their definitions.", objectiveArabic: "استخدم ثلاثة تعبيرات مسترجعة في سياق جديد دون تكرار تعريفاتها.", stage: "independent-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["tip"], speakingLines: [{ id: "prompt", speaker: "Prompt", text: "Your club can either buy new equipment or fund a free trial session. Explain a choice using priority, consequence, and worth considering.", textArabic: "يمكن لناديك إما شراء معدات جديدة أو تمويل جلسة تجريبية مجانية. اشرح اختياراً مستخدماً priority وconsequence وworth considering." }] }
  ],
  132: [
    { id: "b1-m9-132-source", kind: "reading", title: "Interpret a short decision source", titleArabic: "فسّر مصدراً قصيراً عن قرار", objective: "Distinguish reported feedback, the question it answers, and the uncertainty that remains in a short survey summary.", objectiveArabic: "ميّز بين الملاحظات المنقولة والسؤال الذي تجيب عنه وحالة عدم اليقين المتبقية في ملخص مسح قصير.", stage: "explanation", estimatedMinutes: 15, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "A youth centre asked 48 regular visitors whether it should extend its evening opening hours. Thirty-one respondents said they would use one later evening each week, especially during exam periods. The survey did not include young people who do not currently visit the centre. The manager said that the team would test a Thursday evening for six weeks and ask visitors why they did or did not attend.", readingTextArabic: "ملخص مصدر قصير يوضح ما تقوله ملاحظات محدودة وما لا تستطيع إثباته بعد.", readingChecks: [{ id: "detail", type: "detail", prompt: "What did thirty-one respondents say?", promptArabic: "ماذا قال واحد وثلاثون مشاركاً؟", choices: ["They would use one later evening each week.", "They would stop visiting the centre.", "They wanted a new building."], answer: "They would use one later evening each week." }, { id: "limitation", type: "inference", prompt: "What is the main limitation of the survey?", promptArabic: "ما القيد الرئيسي للمسح؟", choices: ["It did not include young people who do not already visit.", "It had no questions about evenings.", "It included too many exam periods."], answer: "It did not include young people who do not already visit." }] }
  ],
  133: [
    { id: "b1-m9-133-revise", kind: "writing", title: "Draft and revise a decision update", titleArabic: "صغ وراجع تحديثاً عن قرار", objective: "Write a connected update that sequences action, explains contrast, and revises one sentence that overstates the evidence.", objectiveArabic: "اكتب تحديثاً مترابطاً يرتب الإجراء ويشرح التباين ويراجع جملة تبالغ في الدليل.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "word-support"], writingPrompt: "Write 140–170 words updating members about a fictional decision. First explain the issue, then describe two options. Use because, although, and while to explain your recommendation. Revise one sentence so it says what the evidence suggests rather than what it proves.", writingPromptArabic: "اكتب 140–170 كلمة لتحديث الأعضاء عن قرار خيالي. اشرح المشكلة أولاً ثم صف خيارين. استخدم because وalthough وwhile لشرح توصيتك. راجع جملة واحدة لتقول ما الذي تشير إليه الأدلة لا ما الذي تثبته.", suggestedVocabulary: ["option", "evidence", "recommend", "although", "consequence"], sentencePatterns: ["Although …, …", "While …, …", "The feedback suggests …"] }
  ],
  134: [
    { id: "b1-m9-134-task", kind: "interaction", title: "Solve a realistic scheduling task", titleArabic: "حل مهمة جدولة واقعية", objective: "Choose a feasible first action under time, access, and budget constraints, justify a trade-off, and set a review question.", objectiveArabic: "اختر إجراء أولاً قابلاً للتنفيذ ضمن قيود الوقت والوصول والميزانية، وبرر مقايضة وحدد سؤالاً للمراجعة.", stage: "real-context", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Brief", text: "A volunteer group has £200, two Saturday mornings, and requests for a repair workshop. The room is accessible but has space for only twelve people. Some participants need tools; others want a session in Arabic and English.", textArabic: "لدى مجموعة متطوعين 200 جنيه إسترليني وصباحا سبت وطلبات لورشة إصلاح. الغرفة مهيأة لكنها تتسع لاثني عشر شخصاً فقط. يحتاج بعض المشاركين أدوات ويريد آخرون جلسة بالعربية والإنجليزية.", purpose: "Present real constraints without pretending there is one perfect solution." }, { id: "you", speaker: "You", text: "I would begin with … because … . This means that … will not happen yet; however, … . We should review … after …", textArabic: "سأبدأ بـ … لأن … . هذا يعني أن … لن يحدث بعد؛ لكن … . ينبغي أن نراجع … بعد …", purpose: "Make a bounded recommendation and keep it open to evidence." }] }
  ],
  135: [
    { id: "b1-m9-135-checkpoint", kind: "assessment", title: "Problem-solving and decisions checkpoint", titleArabic: "نقطة تحقق: حل المشكلات والقرارات", objective: "Use connected evidence, measured modal language, conditional consequences, and a clear recommendation in a new practical situation.", objectiveArabic: "استخدم دليلاً مترابطاً وأفعالاً مساعدة متدرجة ونتائج شرطية وتوصية واضحة في موقف عملي جديد.", stage: "assessment", estimatedMinutes: 23, semantic: "assessment", progressiveSupports: ["tip"], writingPrompt: "A local sports club needs to decide how to spend a small grant: improve changing rooms, buy equipment, or offer low-cost sessions. Write 160–190 words recommending a first action. Refer to one limited piece of feedback, explain one constraint, compare two options, and state what the club should review after the decision.", writingPromptArabic: "يحتاج نادٍ رياضي محلي إلى تقرير كيفية إنفاق منحة صغيرة: تحسين غرف تبديل الملابس أو شراء معدات أو تقديم جلسات منخفضة التكلفة. اكتب 160–190 كلمة توصي فيها بإجراء أول. أشر إلى ملاحظة محدودة واحدة واشرح قيداً واحداً وقارن بين خيارين واذكر ما الذي ينبغي للنادي مراجعته بعد القرار.", suggestedVocabulary: ["priority", "constraint", "consequence", "feedback", "recommend"], sentencePatterns: ["The feedback suggests …", "A sensible first action would be …", "If the club …, it will …", "Although …, …"] }
  ],
};
