import type { LessonActivity } from "./types";

const scene = (label: string, tint = "#3f6b63") => `data:image/svg+xml,${encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="420" viewBox="0 0 720 420"><rect width="720" height="420" rx="30" fill="${tint}"/><path d="M90 310c68-118 160-166 270-166 102 0 180 50 270 166" fill="#f5f1e8" opacity=".92"/><circle cx="176" cy="142" r="55" fill="#e9bc68"/><path d="M436 92h150v142H436z" fill="#d7e8df"/><text x="360" y="138" text-anchor="middle" fill="#fff" font-family="Arial" font-size="32" font-weight="700">${label}</text><text x="360" y="185" text-anchor="middle" fill="#e5f0ea" font-family="Arial" font-size="20">notice · choose · review</text></svg>`)}`;

const visualWords = (lesson: number, items: Array<[string, string, string]>) => items.map(([word, arabic, example], index) => ({
  id: `b1-m5-${lesson}-visual-${index + 1}`,
  word,
  arabic,
  pronunciation: word,
  exampleEN: example,
  exampleAR: "استخدم الكلمة لوصف اختيار يومي أو أثره بوضوح ودون مبالغة.",
  imageUrl: scene(word, index % 2 ? "#58776e" : "#3f6b63"),
  altText: `Illustrated health and everyday choices concept card for ${word}`,
  category: "Health and choices",
  interactionHint: "Read the example, then decide whether it describes a habit, a trade-off, or a realistic next step.",
}));

export const B1_MODULE_5_AUTHORED_ACTIVITIES: Record<number, readonly LessonActivity[]> = {
  61: [
    { id: "b1-m5-61-map", kind: "visual-vocabulary", title: "Map wellbeing and everyday choices", titleArabic: "ارسم خريطة للعافية والاختيارات اليومية", objective: "Separate a daily habit, its likely effect, and one realistic adjustment.", objectiveArabic: "ميّز بين عادة يومية وأثرها المحتمل وتعديل واقعي واحد.", stage: "introduction", estimatedMinutes: 11, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(61, [["routine", "روتين", "A stable routine can make a busy week easier to manage."], ["balance", "توازن", "Balance does not mean that every day looks the same."], ["recharge", "يستعيد الطاقة", "A quiet walk helps her recharge after a demanding shift."]]) },
    { id: "b1-m5-61-scan", kind: "speaking", title: "Name one choice without judging yourself", titleArabic: "اذكر اختياراً واحداً دون الحكم على نفسك", objective: "Describe one ordinary choice and a small change you could test.", objectiveArabic: "صف اختياراً عادياً وتغييراً صغيراً يمكنك تجربته.", stage: "guided-practice", estimatedMinutes: 8, semantic: "activity", progressiveSupports: ["worked-example"], speakingLines: [{ id: "model", speaker: "Model", text: "I often answer messages late at night, so I am trying to leave my phone outside the room for thirty minutes before sleep.", textArabic: "غالباً ما أجيب عن الرسائل في وقت متأخر، لذلك أحاول ترك هاتفي خارج الغرفة لمدة ثلاثين دقيقة قبل النوم." }, { id: "you", speaker: "You", text: "Describe one everyday choice, its possible effect, and one small experiment. This is reflection, not medical advice.", textArabic: "صف اختياراً يومياً واحداً وأثره المحتمل وتجربة صغيرة. هذا تأمل وليس نصيحة طبية." }] },
  ],
  62: [
    { id: "b1-m5-62-language", kind: "standard", title: "Choose advice with the right strength", titleArabic: "اختر نصيحة بالقوة المناسبة", objective: "Use should, could, might, and tend to to make careful, practical suggestions.", objectiveArabic: "استخدم should وcould وmight وtend to لتقديم اقتراحات عملية متأنية.", stage: "explanation", estimatedMinutes: 12, semantic: "grammar", progressiveSupports: ["worked-example", "tip"], sentencePatterns: ["You could begin with one change that fits your week.", "A shorter break might help you return with more focus.", "People tend to keep habits that are easy to repeat."] },
    { id: "b1-m5-62-reframe", kind: "writing", title: "Reframe an unrealistic health rule", titleArabic: "أعد صياغة قاعدة صحية غير واقعية", objective: "Turn an absolute rule into a flexible suggestion with a clear limit.", objectiveArabic: "حوّل قاعدة مطلقة إلى اقتراح مرن مع حد واضح.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["worked-example"], writingPrompt: "Rewrite this claim in 55–70 words: ‘Everyone must follow the same perfect routine.’ Offer a practical alternative, name one difference between people, and avoid giving medical advice.", writingPromptArabic: "أعد كتابة الادعاء في 55–70 كلمة: «يجب على الجميع اتباع الروتين المثالي نفسه». قدّم بديلاً عملياً واذكر اختلافاً واحداً بين الناس وتجنب النصيحة الطبية.", suggestedVocabulary: ["may", "could", "realistic", "depending on", "sustainable"], sentencePatterns: ["A more realistic approach may be …", "This can depend on …"] },
  ],
  63: [
    { id: "b1-m5-63-notice", kind: "reading", title: "Notice cause, result, and uncertainty", titleArabic: "لاحظ السبب والنتيجة وعدم اليقين", objective: "Notice how a writer links a habit to an effect without claiming certainty.", objectiveArabic: "لاحظ كيف يربط الكاتب عادة بأثر دون ادعاء اليقين.", stage: "explanation", estimatedMinutes: 12, semantic: "example", progressiveSupports: ["word-support", "tip"], readingText: "After several weeks of taking a short break away from her screen at lunchtime, Hala found that she returned to difficult tasks with more patience. She did not claim that the break solved every stressful moment; however, it gave her a clear point at which to pause and reset. On days when meetings filled the afternoon, the same routine was harder to protect.", readingTextArabic: "نص قصير يوضح علاقة محتملة بين استراحة قصيرة والتركيز دون ادعاء أن الحل يناسب الجميع.", readingChecks: [{ id: "evidence", type: "detail", prompt: "What change did Hala make?", promptArabic: "ما التغيير الذي أجرته هالة؟", choices: ["She took a short screen-free lunch break.", "She cancelled all afternoon meetings.", "She stopped working on difficult tasks."], answer: "She took a short screen-free lunch break." }, { id: "caution", type: "inference", prompt: "Which detail makes the account careful rather than absolute?", promptArabic: "أي تفصيل يجعل الرواية متأنية وليست مطلقة؟", choices: ["It did not solve every stressful moment.", "The tasks were difficult.", "The afternoon had meetings."], answer: "It did not solve every stressful moment." }] },
  ],
  64: [
    { id: "b1-m5-64-dialogue", kind: "interaction", title: "Discuss a busy-week choice", titleArabic: "ناقش اختياراً في أسبوع مزدحم", objective: "Ask about a priority, propose a manageable option, and check that it fits the other person.", objectiveArabic: "اسأل عن أولوية واقترح خياراً قابلاً للتنفيذ وتحقق أنه يناسب الطرف الآخر.", stage: "real-context", estimatedMinutes: 13, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "partner", speaker: "Partner", text: "I want to cook more, but I arrive home late three evenings a week and then I give up on the plan.", textArabic: "أريد أن أطبخ أكثر، لكنني أصل متأخراً إلى المنزل ثلاث أمسيات في الأسبوع ثم أتخلى عن الخطة.", purpose: "Describe a constraint without asking for a perfect answer." }, { id: "you", speaker: "You", text: "That sounds difficult to maintain. Would it help to prepare one simple meal on a quieter day, or would that add more pressure?", textArabic: "يبدو أن الاستمرار في ذلك صعب. هل سيساعد تحضير وجبة بسيطة في يوم أهدأ أم سيضيف ذلك ضغطاً أكبر؟", purpose: "Offer and test a flexible option." }] },
  ],
  65: [
    { id: "b1-m5-65-respond", kind: "speaking", title: "Hear a wellbeing claim and respond carefully", titleArabic: "استمع إلى ادعاء عن العافية واستجب بحذر", objective: "Identify a speaker’s main claim and reply with a useful question or qualification.", objectiveArabic: "حدّد الادعاء الرئيسي للمتحدث وردّ بسؤال مفيد أو توضيح متأنٍ.", stage: "guided-practice", estimatedMinutes: 10, semantic: "activity", progressiveSupports: ["transcript", "word-support"], speakingLines: [{ id: "speaker", speaker: "Colleague", text: "I have started a very early workout before work and I feel productive, so I think everyone should do it.", textArabic: "بدأت تمريناً مبكراً جداً قبل العمل وأشعر بالإنتاجية، لذلك أعتقد أن على الجميع فعله." }, { id: "you", speaker: "You", text: "It seems to work for you. How does it fit with your sleep and work schedule? Other people may need a different approach.", textArabic: "يبدو أنه يناسبك. كيف يتوافق مع نومك وجدول عملك؟ قد يحتاج الآخرون إلى طريقة مختلفة." }] },
  ],
  66: [
    { id: "b1-m5-66-detail", kind: "reading", title: "Read a workplace wellbeing proposal", titleArabic: "اقرأ مقترحاً للعافية في مكان العمل", objective: "Trace a problem, a proposed change, its likely benefit, and its practical limit.", objectiveArabic: "تتبّع مشكلة وتغييراً مقترحاً وفائدته المحتملة وحده العملي.", stage: "explanation", estimatedMinutes: 16, semantic: "example", progressiveSupports: ["word-support"], readingText: "A small customer-support team noticed that complex calls were often followed immediately by another demanding task. Their supervisor proposed a five-minute reset period after selected calls, during which staff could write a short note and check whether they needed help. The plan did not reduce the total workload, and it required careful scheduling. Still, after a trial month, several staff said that the pause made handovers clearer and prevented small problems from being carried into the next conversation.", readingTextArabic: "مقترح قصير يوازن بين فائدة استراحة منظمة وحدودها العملية في مكان العمل.", readingChecks: [{ id: "proposal", type: "detail", prompt: "What did the reset period allow staff to do?", promptArabic: "ماذا أتاحت فترة الاستراحة للموظفين؟", choices: ["Write a note and check if they needed help.", "Leave work early every day.", "Avoid difficult customer calls."], answer: "Write a note and check if they needed help." }, { id: "limit", type: "inference", prompt: "Why is the proposal presented as realistic rather than perfect?", promptArabic: "لماذا يُعرض المقترح على أنه واقعي وليس مثالياً؟", choices: ["It still needed scheduling and did not reduce workload.", "All staff rejected it.", "It applied only to customers."], answer: "It still needed scheduling and did not reduce workload." }] },
  ],
  67: [
    { id: "b1-m5-67-paragraph", kind: "writing", title: "Write a connected self-management paragraph", titleArabic: "اكتب فقرة مترابطة عن إدارة الذات", objective: "Write a 130–160-word paragraph about one sustainable choice, its challenge, and how you will review it.", objectiveArabic: "اكتب فقرة من 130–160 كلمة عن اختيار مستدام وتحديه وكيف ستراجعه.", stage: "independent-practice", estimatedMinutes: 20, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Write 130–160 words about one everyday habit you want to manage more deliberately. Explain why it matters to you, name one obstacle, describe a realistic adjustment, and state how you will decide whether it is helping. Do not present the paragraph as health advice for others.", writingPromptArabic: "اكتب 130–160 كلمة عن عادة يومية تريد إدارتها بوعي أكبر. اشرح أهميتها لك وعائقاً واحداً وتعديلاً واقعياً وكيف ستقرر إن كان يساعدك. لا تقدّمها كنصيحة صحية للآخرين.", suggestedVocabulary: ["priority", "manageable", "obstacle", "adjust", "review"], sentencePatterns: ["One change I can realistically maintain is …", "If it proves unhelpful, I will …"] },
  ],
  68: [
    { id: "b1-m5-68-compare", kind: "interaction", title: "Compare two ways to protect energy", titleArabic: "قارن بين طريقتين لحماية الطاقة", objective: "Compare two everyday approaches using criteria, trade-offs, and a conditional recommendation.", objectiveArabic: "قارن بين طريقتين يوميتين باستخدام معايير ومفاضلات وتوصية شرطية.", stage: "real-context", estimatedMinutes: 14, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "option-a", speaker: "Option A", text: "Plan every hour of the week in advance, including breaks.", textArabic: "خطط لكل ساعة من الأسبوع مسبقاً، بما في ذلك فترات الاستراحة.", purpose: "Present a highly structured approach." }, { id: "option-b", speaker: "Option B", text: "Choose three priorities each morning and leave some space for change.", textArabic: "اختر ثلاث أولويات كل صباح واترك مساحة للتغيير.", purpose: "Present a flexible approach." }, { id: "you", speaker: "You", text: "Option A may help someone with a predictable schedule, whereas Option B could suit a week with changing demands. I would choose … because …", textArabic: "قد يساعد الخيار أ شخصاً لديه جدول متوقع، بينما قد يناسب الخيار ب أسبوعاً تتغير فيه المتطلبات. سأختار … لأن …", purpose: "Make a qualified recommendation." }] },
  ],
  69: [
    { id: "b1-m5-69-repair", kind: "interaction", title: "Repair an assumption about someone’s choice", titleArabic: "أصلح افتراضاً حول اختيار شخص ما", objective: "Correct an assumption about a personal habit while keeping the conversation respectful.", objectiveArabic: "صحح افتراضاً حول عادة شخصية مع الحفاظ على احترام الحوار.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["transcript", "worked-example"], interactionTurns: [{ id: "assumption", speaker: "Friend", text: "You never join us after work because you do not care about the team.", textArabic: "أنت لا تنضم إلينا أبداً بعد العمل لأنك لا تهتم بالفريق.", purpose: "Make an unfair assumption." }, { id: "repair", speaker: "You", text: "I do care about the team. I have been protecting one evening for family responsibilities, but I could join a short lunch once a week if that would help us stay connected.", textArabic: "أنا أهتم بالفريق. كنت أحافظ على أمسية واحدة لمسؤوليات عائلية، لكن يمكنني الانضمام لغداء قصير مرة أسبوعياً إذا كان ذلك يساعدنا على البقاء على تواصل.", purpose: "Clarify a boundary and offer connection." }] },
  ],
  70: [
    { id: "b1-m5-70-purpose", kind: "speaking", title: "Lead a realistic wellbeing check-in", titleArabic: "قد اجتماعاً واقعياً للاطمئنان على العافية", objective: "Lead a one-minute check-in that names a pressure, a boundary, and a practical request.", objectiveArabic: "قدّم حديثاً لمدة دقيقة يذكر ضغطاً وحداً وطلباً عملياً.", stage: "real-context", estimatedMinutes: 12, semantic: "activity", progressiveSupports: ["word-support", "worked-example"], speakingLines: [{ id: "frame", speaker: "Plan", text: "Name the situation, explain its effect without blaming anyone, set one boundary, and make one actionable request.", textArabic: "اذكر الموقف واشرح أثره دون لوم أحد وحدد حداً واحداً واطلب طلباً قابلاً للتنفيذ." }, { id: "you", speaker: "You", text: "Practise a short check-in for a study group, workplace, or home schedule. Keep the request specific and respectful.", textArabic: "تدرّب على حديث قصير لمجموعة دراسة أو مكان عمل أو جدول منزلي. اجعل الطلب محدداً ومحترماً." }] },
  ],
  71: [
    { id: "b1-m5-71-network", kind: "review", title: "Review the choices word network", titleArabic: "راجع شبكة كلمات الاختيارات", objective: "Retrieve language for routine, pressure, balance, boundaries, and gradual change.", objectiveArabic: "استرجع لغة الروتين والضغط والتوازن والحدود والتغيير التدريجي.", stage: "independent-practice", estimatedMinutes: 13, semantic: "vocabulary", progressiveSupports: ["arabic-help", "word-support"], visualItems: visualWords(71, [["boundary", "حد", "A clear boundary protects time without rejecting people."], ["pressure", "ضغط", "Too much pressure can make a useful plan impossible to continue."], ["gradual", "تدريجي", "A gradual adjustment is often easier to review."]]) },
  ],
  72: [
    { id: "b1-m5-72-source", kind: "reading", title: "Interpret a short wellbeing source", titleArabic: "فسّر مصدراً قصيراً عن العافية", objective: "Evaluate what a short survey result suggests, what it does not prove, and what question remains.", objectiveArabic: "قيّم ما تشير إليه نتيجة استطلاع قصيرة وما لا تثبته والسؤال الذي يبقى.", stage: "explanation", estimatedMinutes: 15, semantic: "example", progressiveSupports: ["tip", "word-support"], readingText: "A student association asked 84 learners which part of the week felt most difficult to organise. Fifty-one selected ‘the evening before a deadline’. The result suggests that deadlines may be a useful point for practical support, such as planning sessions or clearer reminders. It does not show why those evenings are difficult, and it cannot tell us whether the same pattern would appear in other groups.", readingTextArabic: "مصدر قصير يوضح كيف نفسر نتيجة استطلاع مع الاعتراف بما لا تثبته.", readingChecks: [{ id: "suggests", type: "detail", prompt: "What practical support does the source suggest?", promptArabic: "ما الدعم العملي الذي يقترحه المصدر؟", choices: ["Planning sessions or clearer reminders.", "Cancelling all deadlines.", "Giving every learner the same schedule."], answer: "Planning sessions or clearer reminders." }, { id: "limit", type: "inference", prompt: "Which question remains unanswered?", promptArabic: "أي سؤال يبقى بلا إجابة؟", choices: ["Why those evenings are difficult.", "How many learners answered the survey.", "Which week the survey happened."], answer: "Why those evenings are difficult." }] },
  ],
  73: [
    { id: "b1-m5-73-revise", kind: "writing", title: "Draft and revise a balanced suggestion", titleArabic: "صغ وراجع اقتراحاً متوازناً", objective: "Revise a suggestion after checking audience, evidence, practicality, and tone.", objectiveArabic: "راجع اقتراحاً بعد فحص الجمهور والدليل والعملية والنبرة.", stage: "independent-practice", estimatedMinutes: 18, semantic: "activity", progressiveSupports: ["worked-example", "external-ai-prompt"], writingPrompt: "Draft 120–150 words for a student group that wants one small change to make busy weeks easier. Give a reason from the survey, offer a practical action, acknowledge one limit, and invite feedback. Then revise one sentence that sounds too absolute.", writingPromptArabic: "اكتب مسودة من 120–150 كلمة لمجموعة طلاب تريد تغييراً صغيراً لتسهيل الأسابيع المزدحمة. استخدم سبباً من الاستطلاع وفعلًا عملياً وحداً واحداً وادعُ للتغذية الراجعة، ثم راجع جملة تبدو مطلقة أكثر من اللازم.", suggestedVocabulary: ["suggest", "evidence", "trial", "limitation", "feedback"], sentencePatterns: ["The survey suggests that …", "We could trial …, although …"] },
  ],
  74: [
    { id: "b1-m5-74-task", kind: "interaction", title: "Solve a realistic scheduling task", titleArabic: "حل مهمة جدولة واقعية", objective: "Negotiate a shared plan that protects a priority while accommodating a real constraint.", objectiveArabic: "تفاوض على خطة مشتركة تحمي أولوية مع مراعاة قيد واقعي.", stage: "real-context", estimatedMinutes: 16, semantic: "activity", progressiveSupports: ["worked-example", "tip"], interactionTurns: [{ id: "brief", speaker: "Brief", text: "Your study group has one free hour this week. Two members want revision time, one member needs a break after a long shift, and the group also needs to plan a deadline.", textArabic: "لدى مجموعة الدراسة ساعة مجانية واحدة هذا الأسبوع. يريد عضوان وقت مراجعة ويحتاج عضو إلى استراحة بعد وردية طويلة، وتحتاج المجموعة أيضاً إلى التخطيط لموعد نهائي.", purpose: "State competing needs and a fixed constraint." }, { id: "you", speaker: "You", text: "Propose a plan, explain one trade-off, and ask whether it is workable for everyone. Offer a smaller alternative if it is not.", textArabic: "اقترح خطة واشرح مفاضلة واحدة واسأل إن كانت مناسبة للجميع. قدّم بديلاً أصغر إذا لم تكن مناسبة.", purpose: "Negotiate a workable shared solution." }] },
  ],
  75: [
    { id: "b1-m5-75-checkpoint", kind: "assessment", title: "Health and choices checkpoint", titleArabic: "نقطة تحقق: الصحة والاختيارات", objective: "Transfer careful advice, comparison, source limits, and respectful repair into one realistic response.", objectiveArabic: "انقل النصيحة المتأنية والمقارنة وحدود المصدر والإصلاح المحترم إلى استجابة واقعية واحدة.", stage: "assessment", estimatedMinutes: 24, semantic: "assessment", progressiveSupports: ["tip", "external-ai-prompt"], writingPrompt: "A learner says: ‘I need a perfect routine, but my schedule changes every day.’ Write 150–180 words that ask two clarifying questions, offer two flexible options, explain one trade-off, and note when a personal concern may need professional support rather than advice from classmates.", writingPromptArabic: "يقول متعلم: «أحتاج إلى روتين مثالي، لكن جدولي يتغير كل يوم». اكتب 150–180 كلمة تسأل سؤالين توضيحيين وتقدم خيارين مرنين وتشرح مفاضلة واحدة وتذكر متى قد يحتاج القلق الشخصي إلى دعم مهني بدلاً من نصيحة الزملاء.", suggestedVocabulary: ["realistic", "priority", "adjustment", "depending on", "professional support"], sentencePatterns: ["It may help to ask … first.", "If this concern is affecting your wellbeing significantly, it may be worth speaking to a qualified professional."] },
  ],
};
