import rawDraft from "./b1-draft.json";
import type { CourseDefinition, GrammarTopic, LessonDefinition, LessonExperience, LessonStep, VocabularyItem } from "./types";
import { enrichLesson } from "./activity-plan";
import { buildModuleDefinitions } from "./module-definitions";
import { createLessonExperience } from "./lesson-experience";
import { B1_MODULE_1_AUTHORED_ACTIVITIES } from "./b1-module-1-authored-activities";
import { B1_MODULE_2_AUTHORED_ACTIVITIES } from "./b1-module-2-authored-activities";
import { B1_MODULE_3_AUTHORED_ACTIVITIES } from "./b1-module-3-authored-activities";
import { B1_MODULE_4_AUTHORED_ACTIVITIES } from "./b1-module-4-authored-activities";
import { B1_MODULE_5_AUTHORED_ACTIVITIES } from "./b1-module-5-authored-activities";
import { B1_MODULE_6_AUTHORED_ACTIVITIES } from "./b1-module-6-authored-activities";
import { B1_MODULE_7_AUTHORED_ACTIVITIES } from "./b1-module-7-authored-activities";

type DraftVocabulary = { word: string; arabic: string; partOfSpeech: string; definition: string; exampleEN: string; exampleAR: string };
type DraftLesson = {
  lessonNumber: number;
  title: string;
  titleArabic: string;
  outcome: { canDo: string; canDoArabic: string; scenario: string; scenarioArabic: string };
  retrieval: Array<{ language: string; prompt: string; purpose: string }>;
  network: {
    theme: string; themeArabic: string; anchor: string; relatedWords: string[]; chunks: string[]; collocations: string[];
    register: "neutral" | "informal" | "formal" | "mixed"; priorLevelLinks: string[]; learningNote: string; learningNoteArabic: string;
    wordFamilies: Array<{ headword: string; forms: string[]; note: string; noteArabic: string }>;
  };
  vocabulary: DraftVocabulary[];
  grammar: { topic: string; arabicName: string; concept: string; arabicComparison: string; structure: string; commonError: string; exampleEN: string; exampleAR: string };
  readingBrief: string;
  writingPrompt: string;
};

const STEPS: LessonStep[] = [
  { id: "start", title: "Start here", titleArabic: "ابدأ هنا", purpose: "Take a position and reactivate A2 language needed for this scenario.", estimatedMinutes: 6 },
  { id: "explore", title: "Explore", titleArabic: "استكشف", purpose: "Study useful B1 chunks, collocations, word families, and tone.", estimatedMinutes: 12 },
  { id: "notice", title: "Notice", titleArabic: "لاحظ", purpose: "Trace grammar and discourse choices through a connected example.", estimatedMinutes: 12 },
  { id: "build", title: "Build", titleArabic: "ابنِ", purpose: "Shape a coherent paragraph, comparison, story segment, or practical response.", estimatedMinutes: 14 },
  { id: "respond", title: "Respond", titleArabic: "استجب", purpose: "Interpret an original source and respond for a real audience and purpose.", estimatedMinutes: 20 },
  { id: "prove", title: "Prove it", titleArabic: "أثبت إتقانك", purpose: "Transfer the language to a new task, receive feedback, and schedule review.", estimatedMinutes: 16 },
];

function asVocabularyItem(item: DraftVocabulary, lessonNumber: number, index: number): VocabularyItem {
  return { id: `b1-${lessonNumber}-${index + 1}`, word: item.word, arabic: item.arabic, ipa: "", phoneticRespelling: item.word, partOfSpeech: item.partOfSpeech, definition: item.definition, exampleEN: item.exampleEN, exampleAR: item.exampleAR };
}

function asGrammarTopic(lesson: DraftLesson): GrammarTopic {
  const grammar = lesson.grammar;
  return {
    id: `b1-grammar-${lesson.lessonNumber}`, lessonNumber: lesson.lessonNumber, topic: grammar.topic, arabicName: grammar.arabicName,
    concept: grammar.concept, represents: "Use this B1 pattern to make the meaning, relationship, or stance in your response precise.", arabicComparison: grammar.arabicComparison,
    useWhen: ["you need to connect ideas across a paragraph", "the B1 scenario requires a clear stance, sequence, or degree of certainty"],
    doNotUseWhen: ["a shorter A2 sentence already communicates the exact intended meaning"],
    commonMistakes: [{ wrong: grammar.commonError, correct: grammar.structure, explanation: "Check how the form changes the connection between your ideas." }],
    structure: { positive: grammar.structure, negative: `Check the limiting or negative form in: ${grammar.exampleEN}`, question: `Ask an AI follow-up question about ${grammar.topic}` },
    examples: [{ en: grammar.exampleEN, ar: grammar.exampleAR }], practice: [],
  };
}

const B1_MODULE_1_EXPERIENCES: Record<number, LessonExperience> = {
  1: createLessonExperience({ archetype: "speaking", density: "deep", archetypeRationale: "A turning point becomes memorable when learners rehearse a connected account before writing it.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A spoken story studio", whatToDo: "Rehearse a personal turning point with time signals.", whatMatters: "Sequence creates meaning, not only accuracy.", whatNext: "Turn your spoken account into a reflective email." }, progressiveSupports: ["worked-example", "word-support"] }),
  2: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Conditional choices are best learned by weighing consequences in a genuine group decision.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A community decision", whatToDo: "Compare what may happen with what you would choose.", whatMatters: "Separate likely results from imagined alternatives.", whatNext: "Carry this decision language into future advice." }, progressiveSupports: ["worked-example", "extended-rationale"] }),
  3: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "The first priority is noticing how calm boundary language differs from blame.", selectedStages: ["orientation", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A language-noticing lesson", whatToDo: "Read a disagreement and identify the boundary and repair.", whatMatters: "A specific need is clearer than a personal attack.", whatNext: "Rehearse a respectful repair conversation." }, progressiveSupports: ["arabic-help", "extended-rationale"] }),
  4: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A habit diary offers enough context to explore change, setback, and support critically.", selectedStages: ["encounter", "notice", "retrieval", "evidence"], firstView: { whatItIs: "A realistic habit diary", whatToDo: "Trace the writer’s change, setback, and support.", whatMatters: "Progress can be uneven and still be real.", whatNext: "Use this language to form your own sustainable plan." }, progressiveSupports: ["word-support"] }),
  5: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A qualified opinion needs deliberate planning, contrast, and a fair conclusion rather than a quick answer.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A balanced opinion task", whatToDo: "Write a fair view of a local issue with one clear limit.", whatMatters: "B1 opinions earn trust by acknowledging complexity.", whatNext: "Reuse hedging when making practical requests and proposals." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  6: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Email tone has a purpose and audience, so learners compare drafts before producing a request.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "An email tone workshop", whatToDo: "Choose the tone, then make a request that someone can act on.", whatMatters: "A clear action and timing matter as much as politeness.", whatNext: "Send a short, structured request." }, progressiveSupports: ["worked-example", "tip"] }),
  7: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Modal language gains force when tied to visible local priorities and a brief spoken pitch.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval"], firstView: { whatItIs: "A neighbourhood-priority map", whatToDo: "Sort what the area must, should, and could do.", whatMatters: "Each modal changes the strength of your claim.", whatNext: "Give a one-minute community pitch." }, progressiveSupports: ["arabic-help", "word-support"] }),
  8: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Reported speech serves a real collaborative purpose when a team must turn views into a fair plan.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A team-meeting reconstruction", whatToDo: "Report what each person said, then propose a fair action.", whatMatters: "Fair solutions begin with accurate listening.", whatNext: "Use this reporting skill for workplace and community tasks." }, progressiveSupports: ["transcript", "worked-example"] }),
  9: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A clear complaint demonstrates how chronological facts and passive forms make a practical problem understandable.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A service-problem case", whatToDo: "Separate the facts, impact, and requested solution.", whatMatters: "A reader should be able to act without guessing what happened.", whatNext: "Apply this clarity in formal messages." }, progressiveSupports: ["word-support", "extended-rationale"] }),
  10: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "Work choices are personal and practical, so a concise profile is more useful than a generic grammar drill.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A work-fit profile", whatToDo: "Connect your strengths, preferences, and a realistic next role.", whatMatters: "Use grammar to explain reasons, not to label yourself permanently.", whatNext: "Carry this self-knowledge into a proposal and team discussion." }, progressiveSupports: ["worked-example", "word-support"] }),
  11: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A proposal requires audience awareness, measured benefits, and an honest risk rather than a list of wishes.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A proposal-writing studio", whatToDo: "Recommend one improvement, its benefit, and how to manage a risk.", whatMatters: "Persuasion is stronger when it anticipates a concern.", whatNext: "Use this proposal structure in community action tasks." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  12: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A volunteer case lets learners evaluate impact and sustainability instead of repeating a positive slogan.", selectedStages: ["encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A community-project case study", whatToDo: "Assess the project’s impact and its practical limit.", whatMatters: "Support is worth judging by evidence and sustainability.", whatNext: "Transfer the reasoning to a source-based report." }, progressiveSupports: ["tip", "word-support"] }),
  13: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Source evaluation needs careful comparison, so the experience focuses on tracing a claim to reliable evidence.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence"], firstView: { whatItIs: "A source-check investigation", whatToDo: "Compare a claim with direct and reported sources.", whatMatters: "The loudest claim is not automatically the strongest evidence.", whatNext: "Apply this source language to media and design topics." }, progressiveSupports: ["extended-rationale", "tip"] }),
  14: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "A visual attention loop makes an abstract cause-and-effect pattern concrete before learners argue for a change.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use"], firstView: { whatItIs: "A design-and-habit investigation", whatToDo: "Identify one feature, its effect, and a calmer alternative.", whatMatters: "Design choices can shape behaviour without removing all choice.", whatNext: "Defend your change aloud using evidence." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  15: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The module ends by asking learners to make a persuasive claim while showing they can distinguish support from exaggeration.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A truthful campaign pitch", whatToDo: "Present and defend an idea with a justified comparison.", whatMatters: "A persuasive message should remain honest about its evidence.", whatNext: "Carry this critical voice into later B1 media work." }, progressiveSupports: ["tip", "external-ai-prompt"] }),
};

const B1_MODULE_2_EXPERIENCES: Record<number, LessonExperience> = {
  16: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Data literacy begins with a focused reading route that separates evidence from overreach.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A cautious-data case", whatToDo: "Identify what the survey supports and what remains unknown.", whatMatters: "Reliable communication names its limits.", whatNext: "Turn evidence and uncertainty into a practical recommendation." }, progressiveSupports: ["word-support", "tip"] }),
  17: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A short spoken custom-sharing route makes inclusive language observable before a longer cultural response.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A respectful custom exchange", whatToDo: "Describe one custom and contrast it without ranking cultures.", whatMatters: "Personal experience is not a universal rule.", whatNext: "Use the same respectful contrast in a review or discussion." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  18: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A review earns its recommendation through evidence, evaluation, and one measured limitation.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A student-review studio", whatToDo: "Evaluate a cultural experience with two concrete examples.", whatMatters: "A fair limitation makes a recommendation more credible.", whatNext: "Reuse this balance when arguing for local choices." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  19: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Feedback language becomes useful when learners practise choosing exactly what help to request.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A tutor-feedback conversation", whatToDo: "Report progress and ask for two specific forms of help.", whatMatters: "Specific feedback requests make learning more actionable.", whatNext: "Carry this reflective language into career conversations." }, progressiveSupports: ["transcript", "worked-example"] }),
  20: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "Career language matters most when a spoken profile develops into an audience-aware written request.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A career direction workshop", whatToDo: "Connect experience, goals, and a realistic next step.", whatMatters: "Professional clarity can remain honest about uncertainty.", whatNext: "Use this profile in future workplace and project lessons." }, progressiveSupports: ["word-support", "external-ai-prompt"] }),
  21: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A disrupted journey needs chronological facts followed by a request another person can act upon.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use", "evidence"], firstView: { whatItIs: "A travel-repair case", whatToDo: "Explain what happened, its impact, and the solution you need.", whatMatters: "A concise request makes a stressful situation easier to solve.", whatNext: "Apply this sequence to formal service messages." }, progressiveSupports: ["word-support", "worked-example"] }),
  22: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "Visual cause-and-effect language lets learners explore a modest action before defending a proposal.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use"], firstView: { whatItIs: "A small-action map", whatToDo: "Trace a local action, its benefit, and its trade-off.", whatMatters: "Good proposals explain both gains and limits.", whatNext: "Build a formal proposal from this map." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  23: createLessonExperience({ archetype: "speaking", density: "deep", archetypeRationale: "A civic debate gives concession language a real purpose before learners turn it into a formal recommendation.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A balanced civic debate", whatToDo: "State a view, acknowledge one concern, and defend a practical response.", whatMatters: "Respectful disagreement strengthens rather than weakens an argument.", whatNext: "Write your balanced council recommendation." }, progressiveSupports: ["worked-example", "tip"] }),
  24: createLessonExperience({ archetype: "writing", density: "normal", archetypeRationale: "A future-focused personal email gives learners a bounded place to connect reflection, decision, and planning.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A next-chapter message", whatToDo: "Reflect on one choice and describe two future steps.", whatMatters: "Different future forms signal different degrees of planning.", whatNext: "Transfer this planning language to professional goals." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  25: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A structured short talk helps learners develop a social idea without depending on a long written scaffold.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A purposeful B1 talk", whatToDo: "Give two developed points about relationships and society.", whatMatters: "A clear opening and closing help listeners follow your reasoning.", whatNext: "Retrieve this structure for the module checkpoint." }, progressiveSupports: ["word-support", "tip"] }),
  26: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "A deliberate lexical review makes relationship and society language easier to select in later independent work.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A word-network review", whatToDo: "Group and retrieve language for support, disagreement, and cooperation.", whatMatters: "A network is more useful than a disconnected list.", whatNext: "Use your strongest retrieved words in the source task." }, progressiveSupports: ["word-support"] }),
  27: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Interpreting a community source trains learners to identify evidence and missing perspectives, not merely repeat a claim.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A source-interpretation task", whatToDo: "Find the claim, its evidence, and one missing voice.", whatMatters: "Evidence can be promising without being complete.", whatNext: "Use source-aware language in a revised argument." }, progressiveSupports: ["word-support", "tip"] }),
  28: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Revision is the central learning goal, so learners draft briefly and make their improvements visible.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A draft-and-revise studio", whatToDo: "Improve one social argument for clarity and register.", whatMatters: "Strong writers can explain why a revision helps their reader.", whatNext: "Use these revision checks for your final checkpoint." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  29: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A shared-space problem makes conditional compromise language necessary rather than ornamental.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A shared-space negotiation", whatToDo: "Offer, test, and refine a compromise with a condition.", whatMatters: "Good solutions explain what each side can accept.", whatNext: "Bring this practical reasoning into the checkpoint." }, progressiveSupports: ["transcript", "worked-example"] }),
  30: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The final task asks learners to combine respectful tone, evidence awareness, concession, and revision in an original recommendation.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A relationships-and-society checkpoint", whatToDo: "Recommend a response to a local issue with evidence and a realistic limit.", whatMatters: "An independent B1 response stays fair when the issue is complex.", whatNext: "Carry this social and professional voice into Module 3." }, progressiveSupports: ["tip", "external-ai-prompt"] }),
};

const B1_MODULE_3_EXPERIENCES: Record<number, LessonExperience> = {
  31: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "A visual map lets learners organise travel and adjustment language before they tell a connected account.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A journey-of-change map", whatToDo: "Name the trigger, adjustment, and outcome of one change.", whatMatters: "A clear map makes a connected story easier to tell.", whatNext: "Use this timeline language when giving advice." }, progressiveSupports: ["arabic-help", "word-support"] }),
  32: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Timeline language is useful when learners connect a completed event to an ongoing adjustment and a practical recommendation.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "An adjustment-language workshop", whatToDo: "Choose the tense and change verb that makes your timeline clear.", whatMatters: "A precise timeline helps advice sound grounded rather than generic.", whatNext: "Write useful moving advice for a real reader." }, progressiveSupports: ["worked-example", "tip"] }),
  33: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "The key goal is to spot how one earlier event explains a later travel decision.", selectedStages: ["orientation", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A timeline-noticing lesson", whatToDo: "Find the earlier event and explain its later effect.", whatMatters: "Past perfect helps a reader follow the order without guessing.", whatNext: "Apply the pattern in a changed-plan conversation." }, progressiveSupports: ["word-support", "extended-rationale"] }),
  34: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Replanning is inherently collaborative: learners must acknowledge a change and make a usable alternative.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A changed-plan dialogue", whatToDo: "Clarify what changed, offer an option, and check agreement.", whatMatters: "A flexible suggestion is clearer when it ends with a check.", whatNext: "Respond to a spoken travel update." }, progressiveSupports: ["transcript", "worked-example"] }),
  35: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "A short disruption update rewards focused listening and one practical follow-up question.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A live travel update", whatToDo: "Hear the change, then ask the question that affects your route.", whatMatters: "The most useful question targets impact, not every detail.", whatNext: "Read a fuller relocation account." }, progressiveSupports: ["transcript", "word-support"] }),
  36: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A relocation diary supports detailed inference about a partial solution, trade-offs, and unexpected benefits.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A realistic relocation diary", whatToDo: "Trace the problem, response, cost, and wider outcome.", whatMatters: "A workable solution does not need to be perfect.", whatNext: "Write about a change with the same honest balance." }, progressiveSupports: ["word-support", "tip"] }),
  37: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A connected paragraph gives learners time to move beyond a list of events into response and reflection.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A connected-change writing studio", whatToDo: "Organise a change, your response, and a reflection in one paragraph.", whatMatters: "Links show the reader how events and choices relate.", whatNext: "Compare two practical options with the same care." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  38: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "Comparison language becomes purposeful when two routes have real costs, timing, and reliability trade-offs.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A route-choice decision", whatToDo: "Compare two options and justify one with a relevant trade-off.", whatMatters: "A good recommendation names the reason someone should accept a cost.", whatNext: "Repair a misunderstanding before it becomes a larger problem." }, progressiveSupports: ["worked-example", "tip"] }),
  39: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Repair language is only meaningful when a learner can acknowledge an error and propose a considerate next action.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A misunderstanding repair", whatToDo: "Clarify the mismatch, take responsibility, and offer one solution.", whatMatters: "Repair starts with accuracy and ends with a practical action.", whatNext: "Use the same calm tone in a visitor briefing." }, progressiveSupports: ["transcript", "worked-example"] }),
  40: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A short briefing makes learners select only essential information for a visitor facing a changed route.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A visitor travel briefing", whatToDo: "Give the important change, one route, and one backup.", whatMatters: "A listener needs priorities, not every fact you know.", whatNext: "Retrieve this useful language before checking a source." }, progressiveSupports: ["word-support", "worked-example"] }),
  41: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "Deliberate retrieval makes the network of disruption, adjustment, and outcome easier to access independently.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A travel-and-change word-network review", whatToDo: "Retrieve language by its role in a change story.", whatMatters: "A network helps you choose language instead of searching for it.", whatNext: "Use your strongest words to assess a travel source." }, progressiveSupports: ["arabic-help", "word-support"] }),
  42: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Source evaluation requires learners to separate official facts from a stronger personal interpretation.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A travel-source check", whatToDo: "Identify the official fact and test the traveller’s conclusion.", whatMatters: "A disruption is not proof that every outcome is impossible.", whatNext: "Draft a calm message that uses only relevant information." }, progressiveSupports: ["tip", "extended-rationale"] }),
  43: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Revision is visible when learners make an audience-aware message calmer, clearer, and easier to act on.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A message-revision studio", whatToDo: "Draft a changed plan, then improve one sentence for tone and clarity.", whatMatters: "A clear next question helps people make a decision.", whatNext: "Use the same priority logic in a linked-problem task." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  44: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "A relocation-day scenario makes prioritising, contingency planning, and concise communication necessary together.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A relocation-day problem", whatToDo: "Prioritise the first action, then make a contingency plan.", whatMatters: "Good problem-solving protects the most time-sensitive action first.", whatNext: "Bring your decision-making to the module checkpoint." }, progressiveSupports: ["worked-example", "tip"] }),
  45: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint brings comparison, limitation, recommendation, and audience-aware messaging into one independent transfer task.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A travel-and-change checkpoint", whatToDo: "Compare options, recommend one, then write the message it requires.", whatMatters: "A credible recommendation explains both its strength and its limit.", whatNext: "Carry this adaptive voice into later B1 projects." }, progressiveSupports: ["tip", "external-ai-prompt"] }),
};

const B1_MODULE_4_EXPERIENCES: Record<number, LessonExperience> = {
  46: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "A visual distinction between event, viewpoint, and evidence gives learners a grounded entry to opinion language.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval"], firstView: { whatItIs: "A story-and-viewpoint map", whatToDo: "Separate what happened from how a person interprets it.", whatMatters: "An opinion becomes clearer when it does not pretend to be a fact.", whatNext: "Build a balanced viewpoint with precise language." }, progressiveSupports: ["arabic-help", "word-support"] }),
  47: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Hedging and reporting verbs matter when learners turn an absolute reaction into a fair, supported position.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A balanced-viewpoint workshop", whatToDo: "Soften an overconfident claim without losing your meaning.", whatMatters: "Precision makes a reader more likely to trust your judgement.", whatNext: "Notice certainty and doubt in a short account." }, progressiveSupports: ["worked-example", "tip"] }),
  48: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A compact comparison lets learners spot how retelling can quietly increase certainty.", selectedStages: ["orientation", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A narrator-distance lesson", whatToDo: "Find the phrase that makes a claim more cautious.", whatMatters: "Small wording choices change how reliable a story sounds.", whatNext: "Use this care in a live interpretation discussion." }, progressiveSupports: ["word-support", "tip"] }),
  49: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Interpretive disagreement needs a real exchange where a learner questions, concedes, and supports an alternative view.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "An ending-interpretation dialogue", whatToDo: "Respond to another reading with a respectful question and reason.", whatMatters: "Disagreement can add evidence instead of closing the conversation.", whatNext: "Hear a review and choose a focused response." }, progressiveSupports: ["transcript", "worked-example"] }),
  50: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "A short review response focuses attention on one claim and one meaningful qualification.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A review-response rehearsal", whatToDo: "Identify the reviewer’s claim, then agree or challenge one part.", whatMatters: "A useful response targets the claim rather than repeating the whole review.", whatNext: "Read a fuller local story for evidence and viewpoint." }, progressiveSupports: ["transcript", "word-support"] }),
  51: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "The cinema feature supports detailed inference about practical decisions, memory, and a careful community response.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A local-story feature", whatToDo: "Trace the decision, two viewpoints, and what the evidence can support.", whatMatters: "A cultural loss can be recognised without denying a practical constraint.", whatNext: "Develop your own measured cultural opinion in writing." }, progressiveSupports: ["word-support", "tip"] }),
  52: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A public-culture question requires a developed opinion that genuinely acknowledges a competing practical need.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A connected-opinion writing studio", whatToDo: "Build a viewpoint through an example, a concession, and a conclusion.", whatMatters: "A strong B1 paragraph gives a reader a reason to trust its balance.", whatNext: "Compare two ways of telling the same event." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  53: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "Comparing a reaction with an official report lets learners choose a source for its purpose, not as a winner.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A source-choice comparison", whatToDo: "Compare what each source offers and select one for a task.", whatMatters: "Personal experience and factual detail can both be useful in different ways.", whatNext: "Repair a position when someone has misunderstood it." }, progressiveSupports: ["worked-example", "tip"] }),
  54: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A misquoted position creates a natural need for calm correction and precise qualification.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A misquote-repair dialogue", whatToDo: "Correct a summary, clarify your position, and keep the exchange constructive.", whatMatters: "Repair begins by naming what you actually meant.", whatNext: "Recommend a story to a specific audience." }, progressiveSupports: ["transcript", "worked-example"] }),
  55: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A short recommendation works when its listener and possible difficulty shape the language selected.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A purpose-led recommendation", whatToDo: "Recommend one story to a defined listener and explain why.", whatMatters: "A fair recommendation names both value and a possible difficulty.", whatNext: "Retrieve the language that has helped you qualify and conclude." }, progressiveSupports: ["word-support", "worked-example"] }),
  56: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "Retrieving the roles of opinion language makes it easier to select a useful phrase independently.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A stories-and-opinions word-network review", whatToDo: "Group language for telling, qualifying, challenging, and concluding.", whatMatters: "A network is more useful than a list when you must respond in real time.", whatNext: "Apply the same network to a short source investigation." }, progressiveSupports: ["arabic-help", "word-support"] }),
  57: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A short opinion source trains learners to identify evidence and the important question it leaves unanswered.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "An opinion-source investigation", whatToDo: "Find the claim, its support, its audience, and one evidence gap.", whatMatters: "A plausible claim still needs evidence from the people it affects.", whatNext: "Draft a response that stays fair about that gap." }, progressiveSupports: ["word-support", "tip"] }),
  58: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Revision is the learning goal, so learners visibly strengthen a recommendation by adding a limit or a question.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A reader-response revision studio", whatToDo: "Draft a response, then improve one sentence for fairness and evidence.", whatMatters: "A revision is meaningful when it changes what a reader can understand or trust.", whatNext: "Use that fairness to plan a community story display." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  59: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "A story-selection task turns abstract representation into a practical decision with an explicit rule and reason.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A community-story selection task", whatToDo: "Choose stories for a display and explain the rule behind your balance.", whatMatters: "Fair representation asks whose voice is missing, not only what is familiar.", whatNext: "Bring ethical evidence and recommendations into the checkpoint." }, progressiveSupports: ["worked-example", "tip"] }),
  60: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint asks learners to weigh benefits, risks, consent, and practical safeguards in one independent recommendation.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A stories-and-opinions checkpoint", whatToDo: "Interpret the account and recommend a responsible podcast plan.", whatMatters: "Ethical recommendations name a benefit, a risk, and an action that protects people.", whatNext: "Carry this evidence-aware voice into later B1 projects." }, progressiveSupports: ["tip", "external-ai-prompt"] }),
};

const B1_MODULE_5_EXPERIENCES: Record<number, LessonExperience> = {
  61: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "Visible concepts make wellbeing language concrete before learners reflect on a small choice without judging themselves.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A wellbeing-and-choices map", whatToDo: "Separate one habit, its possible effect, and a small experiment.", whatMatters: "A useful reflection is specific and non-judgemental.", whatNext: "Use careful language when suggesting a manageable change." }, progressiveSupports: ["arabic-help", "word-support"] }),
  62: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Advice is more responsible when learners choose a level of certainty that fits a real person and context.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A careful-advice workshop", whatToDo: "Turn an absolute rule into a flexible, realistic suggestion.", whatMatters: "Could and might leave room for different lives and needs.", whatNext: "Notice careful cause-and-effect language in a short account." }, progressiveSupports: ["worked-example", "tip"] }),
  63: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A compact account helps learners notice how evidence and uncertainty can coexist in a personal reflection.", selectedStages: ["orientation", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A cause-and-caution reading", whatToDo: "Find the habit, effect, and phrase that prevents overclaiming.", whatMatters: "One experience can be useful without becoming a universal rule.", whatNext: "Ask a person-centred question about a busy-week choice." }, progressiveSupports: ["word-support", "tip"] }),
  64: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A busy-week conversation lets learners test an option against another person’s actual constraint.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A busy-week decision dialogue", whatToDo: "Ask about a priority, offer an option, and check whether it adds pressure.", whatMatters: "Advice begins with listening to the constraint.", whatNext: "Respond carefully when you hear an overly broad wellbeing claim." }, progressiveSupports: ["transcript", "worked-example"] }),
  65: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "A short claim-response rehearsal trains learners to question generalisations without rejecting a speaker’s experience.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A claim-response rehearsal", whatToDo: "Identify one broad claim and reply with a respectful qualification.", whatMatters: "A question can make a conversation more accurate, not less supportive.", whatNext: "Read a workplace proposal for its benefit and its limit." }, progressiveSupports: ["transcript", "word-support"] }),
  66: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "The workplace case supports a detailed route through a problem, trial change, practical restriction, and reported effect.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A workplace wellbeing case", whatToDo: "Trace the problem, proposed change, practical limit, and reported effect.", whatMatters: "A proposal is stronger when it recognises what it cannot change.", whatNext: "Write a self-management plan with one genuine review point." }, progressiveSupports: ["word-support", "tip"] }),
  67: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A self-management paragraph needs a purpose, obstacle, adjustment, and review criterion—not a promise of perfection.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A sustainable-plan writing studio", whatToDo: "Explain one choice, its obstacle, a realistic adjustment, and how you will review it.", whatMatters: "Specific review language turns intention into an experiment.", whatNext: "Compare two approaches using clear criteria and trade-offs." }, progressiveSupports: ["worked-example", "tip"] }),
  68: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Comparing planning styles gives conditional recommendation language an immediate practical purpose.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A trade-off comparison", whatToDo: "Compare two approaches and recommend one for a defined situation.", whatMatters: "A useful recommendation names the condition under which it works.", whatNext: "Repair an unfair assumption about someone’s priorities." }, progressiveSupports: ["worked-example", "tip"] }),
  69: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Boundary language matters when learners need to correct an assumption while keeping a relationship open.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A respectful-repair dialogue", whatToDo: "Clarify your boundary, correct the assumption, and offer one realistic connection.", whatMatters: "A boundary can protect a commitment without rejecting another person.", whatNext: "Lead a focused wellbeing check-in for a shared situation." }, progressiveSupports: ["transcript", "worked-example"] }),
  70: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A short check-in becomes meaningful when it includes a real pressure, a boundary, and a precise request.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A practical check-in", whatToDo: "Name a pressure, set one boundary, and ask for one workable action.", whatMatters: "Specific requests help others respond without guessing.", whatNext: "Retrieve the language that connects pressure, balance, and gradual change." }, progressiveSupports: ["worked-example", "word-support"] }),
  71: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "A word-network route helps learners retrieve choices language by function before they interpret a new source.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A choices word-network review", whatToDo: "Group language for routine, pressure, boundaries, and gradual adjustment.", whatMatters: "Selecting a word for its function is more useful than recalling a list.", whatNext: "Use the network to evaluate what a short survey can actually support." }, progressiveSupports: ["arabic-help", "word-support"] }),
  72: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "The survey result gives learners a compact source to interpret for implication, limitation, and an unanswered question.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A careful-source investigation", whatToDo: "Identify what the result suggests, what it cannot prove, and what to ask next.", whatMatters: "A number needs context before it becomes a recommendation.", whatNext: "Draft a balanced suggestion and revise an absolute sentence." }, progressiveSupports: ["word-support", "tip"] }),
  73: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A suggestion improves through deliberate revision for evidence, audience, practicality, and tone.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A balanced-suggestion revision studio", whatToDo: "Use one survey finding, propose an action, acknowledge a limit, then soften one overclaim.", whatMatters: "Revision shows how a writer improves trust, not only grammar.", whatNext: "Negotiate a shared plan under competing time and energy constraints." }, progressiveSupports: ["worked-example", "tip"] }),
  74: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A scheduling problem asks learners to negotiate a meaningful compromise rather than state a generic preference.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A shared-schedule task", whatToDo: "Protect a priority, acknowledge a trade-off, and test whether the plan works for everyone.", whatMatters: "A fair solution adapts when the constraint is real.", whatNext: "Bring flexible advice, evidence, and repair into the module checkpoint." }, progressiveSupports: ["worked-example", "tip"] }),
  75: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint asks learners to transfer questioning, flexible options, trade-offs, and safe support language into a realistic response.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A health-and-choices checkpoint", whatToDo: "Respond to a changing routine with questions, options, a trade-off, and an appropriate support boundary.", whatMatters: "Careful language respects both personal differences and situations that need qualified help.", whatNext: "Carry adaptable, evidence-aware choices language into the next B1 module." }, progressiveSupports: ["tip", "word-support"] }),
};

const B1_MODULE_6_EXPERIENCES: Record<number, LessonExperience> = {
  76: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "A media-environment map gives learners visible distinctions before they describe a habit with nuance.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A media-environment map", whatToDo: "Separate the platform, source, claim, and response in one ordinary digital example.", whatMatters: "A claim travels differently from its source.", whatNext: "Use these distinctions to make an online post more precise." }, progressiveSupports: ["arabic-help", "word-support"] }),
  77: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Information verbs become meaningful when learners revise a vague claim into a source-aware message.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A precision-writing workshop", whatToDo: "Choose accurate sharing verbs and name what still needs checking.", whatMatters: "Reporting a claim is not the same as confirming it.", whatNext: "Spot the difference between evidence, opinion, and clickbait." }, progressiveSupports: ["worked-example", "tip"] }),
  78: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A paired headline and article makes the gap between attention-seeking language and limited evidence concrete.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A headline investigation", whatToDo: "Compare the dramatic headline with the more careful article.", whatMatters: "Strong wording can exceed the evidence it appears to describe.", whatNext: "Ask calmly for a source before sharing a claim." }, progressiveSupports: ["word-support", "tip"] }),
  79: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A real-time forwarding decision lets learners request evidence without treating another person as careless.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A source-check dialogue", whatToDo: "Question an urgent claim politely and suggest an official check.", whatMatters: "Checking can protect a group without blaming its members.", whatNext: "Use the same calm questioning with privacy concerns." }, progressiveSupports: ["transcript", "worked-example"] }),
  80: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A short privacy response helps learners practise one precise question rather than memorise abstract rules.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A privacy-question rehearsal", whatToDo: "Identify a permission concern and ask what is necessary.", whatMatters: "A useful question focuses on the feature and its actual data need.", whatNext: "Read how a safety guide creates a pause before responding." }, progressiveSupports: ["transcript", "word-support"] }),
  81: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "The safety guide supports close reading of advice, reasoning, and a realistic limitation without promising risk-free technology.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A digital-safety guide", whatToDo: "Trace the advice, the reason for it, and the pause it creates.", whatMatters: "Safe habits reduce pressure; they do not promise certainty.", whatNext: "Write a personal media boundary that preserves a benefit." }, progressiveSupports: ["word-support", "tip"] }),
  82: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A personal media paragraph needs a benefit, risk, and workable boundary rather than a universal rule.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A media-boundary writing studio", whatToDo: "Explain one useful habit, one risk, and a boundary you could sustain.", whatMatters: "The strongest reflection is specific without judging everyone else.", whatNext: "Compare news routines using clear criteria." }, progressiveSupports: ["worked-example", "word-support"] }),
  83: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Comparing news habits turns abstract reliability language into a qualified recommendation for a real context.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A news-habit comparison", whatToDo: "Weigh speed, range, effort, and reliability before choosing.", whatMatters: "The best choice depends on the purpose and the context.", whatNext: "Repair a digital message while keeping its practical request clear." }, progressiveSupports: ["worked-example", "tip"] }),
  84: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Tone repair is most useful in a realistic exchange where learners keep the request while acknowledging its impact.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A message-repair dialogue", whatToDo: "Clarify your intention, acknowledge impact, and make a cooperative request.", whatMatters: "A repair can retain urgency without treating another person unfairly.", whatNext: "Choose a channel for a team decision with a clear reason." }, progressiveSupports: ["worked-example", "transcript"] }),
  85: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Channel recommendations reveal whether learners can connect a communication tool to timing, record-keeping, and a limitation.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A channel-choice pitch", whatToDo: "Recommend one channel for a team situation and justify it with criteria.", whatMatters: "No channel solves every communication problem.", whatNext: "Retrieve the vocabulary network that supports safer digital decisions." }, progressiveSupports: ["worked-example", "tip"] }),
  86: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "A functional word network helps learners retrieve source, privacy, tone, and boundary language before a new platform update.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A digital-life word-network review", whatToDo: "Connect language for sources, claims, privacy, tone, and routines.", whatMatters: "Choose language by its job in a response, not by a memorised list.", whatNext: "Interpret exactly what an official update confirms." }, progressiveSupports: ["arabic-help", "word-support"] }),
  87: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A concise platform update trains learners to separate confirmation, assumption, and the next question to check.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A platform-update investigation", whatToDo: "Identify what the update confirms, what it does not, and what to check next.", whatMatters: "An inference can sound certain while exceeding the original wording.", whatNext: "Draft a responsible announcement for a group." }, progressiveSupports: ["word-support", "tip"] }),
  88: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "An announcement needs source, confirmation, next action, and a deliberate tone revision for a real group audience.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A responsible-announcement studio", whatToDo: "Draft a group update, then revise one sentence for clearer tone or action.", whatMatters: "A useful announcement tells readers what is known and what they should do.", whatNext: "Respond safely to an urgent-looking request." }, progressiveSupports: ["worked-example", "tip"] }),
  89: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A suspicious urgent request requires a calm, verifiable response rather than an abstract list of safety rules.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A safe-response task", whatToDo: "Slow down, identify what needs checking, and choose a second channel.", whatMatters: "Urgency is a reason to verify, not a reason to share sensitive information.", whatNext: "Bring source awareness, tone, and practical steps into the module checkpoint." }, progressiveSupports: ["worked-example", "tip"] }),
  90: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint combines evidence, verification, tone repair, and next-step language in one authentic group response.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A responsible-digital-response checkpoint", whatToDo: "Separate what is known from what needs checking, propose a safe action, and repair the discussion.", whatMatters: "Responsible communication is factual, safe, and respectful at the same time.", whatNext: "Carry this source-aware voice into later B1 work." }, progressiveSupports: ["worked-example", "word-support"] }),
};

const B1_MODULE_7_EXPERIENCES: Record<number, LessonExperience> = {
  91: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "A system map gives learners the language to connect a local issue, the people involved, and one realistic point of action.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A community-systems map", whatToDo: "Trace one local issue from cause to people to a possible action.", whatMatters: "Useful action starts by seeing relationships, not by blaming one person.", whatNext: "Turn a broad concern into a clear, evidence-aware campaign note." }, progressiveSupports: ["arabic-help", "word-support"] }),
  92: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "A campaign note makes cautious recommendation language matter because it must be clear enough to invite action without promising certainty.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A careful-campaign workshop", whatToDo: "Revise a broad request so it names a realistic action, reason, and limitation.", whatMatters: "A credible message distinguishes a proposal from a guarantee.", whatNext: "Test whether a local claim is supported by the evidence beside it." }, progressiveSupports: ["worked-example", "tip"] }),
  93: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Claim-evidence comparison lets learners test whether persuasive language actually matches the local source.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A claim-and-evidence investigation", whatToDo: "Match each claim to its source, identify one overreach, and ask one useful question.", whatMatters: "A strong concern still needs proportionate evidence.", whatNext: "Use evidence and priorities to negotiate a small shared action." }, progressiveSupports: ["word-support", "tip"] }),
  94: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Small-action negotiation gives learners a reason to balance time, cost, benefit, and another person’s concern.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A small-action negotiation", whatToDo: "Suggest an action, respond to a concern, and agree on a manageable first step.", whatMatters: "Collaboration improves when people can name a trade-off without losing the shared aim.", whatNext: "Respond calmly when a neighbour questions the value of a proposed action." }, progressiveSupports: ["transcript", "worked-example"] }),
  95: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A short spoken response practises concern and evidence language without asking learners to deliver a full speech.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A concern-response rehearsal", whatToDo: "Acknowledge a concern, give one reason, and invite one practical alternative.", whatMatters: "A respectful response keeps disagreement connected to the problem.", whatNext: "Read how a proposal connects energy use, cost, and community benefit." }, progressiveSupports: ["transcript", "word-support"] }),
  96: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "The community-energy proposal develops source literacy around benefit, cost, uncertainty, and who is affected.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A community-energy proposal", whatToDo: "Identify the proposal, its evidence, its trade-off, and one unanswered question.", whatMatters: "Responsible proposals show what they can and cannot claim.", whatNext: "Write a focused paragraph that turns one shared concern into an action." }, progressiveSupports: ["word-support", "tip"] }),
  97: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "An action paragraph needs a defined audience, evidence, a practical step, and a revision for clear civic tone.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A community-action writing studio", whatToDo: "Use one local detail, propose one action, acknowledge one limit, and revise for a cooperative tone.", whatMatters: "Specific writing helps readers see where they can participate.", whatNext: "Compare travel options using environmental and social criteria." }, progressiveSupports: ["worked-example", "tip"] }),
  98: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A cleaner-travel comparison requires learners to apply criteria rather than repeat a universal recommendation.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A practical-travel comparison", whatToDo: "Compare two travel choices for a real local journey and recommend one conditionally.", whatMatters: "The better option depends on access, time, cost, and impact.", whatNext: "Repair a conversation after a community priority has been misunderstood." }, progressiveSupports: ["worked-example", "tip"] }),
  99: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A priority-repair dialogue helps learners correct an assumption while preserving a shared goal and relationship.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A priority-repair dialogue", whatToDo: "Clarify what matters to you, recognise the other priority, and suggest a fair adjustment.", whatMatters: "Repair turns a disagreement into a more accurate shared plan.", whatNext: "Deliver a concise proposal that names an action, benefit, and limitation." }, progressiveSupports: ["transcript", "worked-example"] }),
  100: createLessonExperience({ archetype: "speaking", density: "deep", archetypeRationale: "A two-minute proposal brings evidence, audience, feasibility, and response to questions into one coherent spoken task.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A two-minute action proposal", whatToDo: "Present a realistic change, support it with one reason, name a limit, and answer one concern.", whatMatters: "A persuasive proposal stays open to adjustment.", whatNext: "Retrieve the language that links evidence, participation, priorities, and change." }, progressiveSupports: ["worked-example", "word-support"] }),
  101: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "A functional retrieval route lets learners choose language for evidence, impact, participation, and repair before interpreting a new source.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A community-action word-network review", whatToDo: "Reconnect language for claims, evidence, priorities, participation, and practical change.", whatMatters: "Retrieval is stronger when you choose language by its job in a response.", whatNext: "Interpret a short local source without adding claims it does not make." }, progressiveSupports: ["arabic-help", "word-support"] }),
  102: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A short local source offers a manageable way to separate confirmed information, implication, and a question worth investigating.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A local-source interpretation", whatToDo: "Identify what the source confirms, what it suggests, and what you still need to know.", whatMatters: "Interpretation becomes reliable when it stays close to the source.", whatNext: "Draft a civic message that tells readers what is known and what they can do." }, progressiveSupports: ["word-support", "tip"] }),
  103: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A civic message gives learners a concrete audience for balancing information, action, accessibility, and respectful tone.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A civic-message drafting studio", whatToDo: "Explain one confirmed issue, invite one practical action, and revise a sentence for clarity and inclusion.", whatMatters: "A useful public message is clear about both evidence and next steps.", whatNext: "Work with others to solve a shared-space issue under real constraints." }, progressiveSupports: ["worked-example", "tip"] }),
  104: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A shared-space task asks learners to combine priorities, evidence, and a feasible decision instead of offering a slogan.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A shared-space action task", whatToDo: "Choose a practical change, explain its benefit and limitation, and agree how to check it.", whatMatters: "Community choices work when responsibility and review are explicit.", whatNext: "Bring evidence, participation, repair, and practical action into the module checkpoint." }, progressiveSupports: ["worked-example", "tip"] }),
  105: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint asks learners to interpret evidence, respond to a concern, and propose an achievable community action with a review point.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "An environment-and-community checkpoint", whatToDo: "Use a local source to propose one action, address one concern, and state how the group could review it.", whatMatters: "Effective civic language is evidence-aware, respectful, and actionable.", whatNext: "Carry this practical public voice into the next B1 module." }, progressiveSupports: ["worked-example", "word-support"] }),
};

export const B1_LESSONS: LessonDefinition[] = (rawDraft as DraftLesson[]).map((draft) => ({
  level: "B1" as const, lessonNumber: draft.lessonNumber, moduleNumber: Math.ceil(draft.lessonNumber / 15), title: draft.title, titleArabic: draft.titleArabic,
  words: draft.vocabulary.map((item, index) => asVocabularyItem(item, draft.lessonNumber, index)), grammar: asGrammarTopic(draft),
  learningPlan: { outcome: draft.outcome, steps: STEPS, retrieval: draft.retrieval.map((item) => ({ sourceLevel: "A2" as const, language: item.language, prompt: item.prompt, purpose: item.purpose })), englishFirst: true, studio: "Story & Society Studio" },
  lexicalNetworks: [{ id: `b1-network-${draft.lessonNumber}`, theme: draft.network.theme, themeArabic: draft.network.themeArabic, anchor: draft.network.anchor, wordFamilies: draft.network.wordFamilies, relatedWords: draft.network.relatedWords, chunks: draft.network.chunks, collocations: draft.network.collocations, register: draft.network.register, priorLevelLinks: draft.network.priorLevelLinks, learningNote: draft.network.learningNote, learningNoteArabic: draft.network.learningNoteArabic }],
  practiceBrief: { readingBrief: draft.readingBrief, writingPrompt: draft.writingPrompt },
  activities: B1_MODULE_1_AUTHORED_ACTIVITIES[draft.lessonNumber]
    ? [...B1_MODULE_1_AUTHORED_ACTIVITIES[draft.lessonNumber]]
    : B1_MODULE_2_AUTHORED_ACTIVITIES[draft.lessonNumber]
      ? [...B1_MODULE_2_AUTHORED_ACTIVITIES[draft.lessonNumber]]
      : B1_MODULE_3_AUTHORED_ACTIVITIES[draft.lessonNumber]
        ? [...B1_MODULE_3_AUTHORED_ACTIVITIES[draft.lessonNumber]]
        : B1_MODULE_4_AUTHORED_ACTIVITIES[draft.lessonNumber]
          ? [...B1_MODULE_4_AUTHORED_ACTIVITIES[draft.lessonNumber]]
          : B1_MODULE_5_AUTHORED_ACTIVITIES[draft.lessonNumber]
            ? [...B1_MODULE_5_AUTHORED_ACTIVITIES[draft.lessonNumber]]
            : B1_MODULE_6_AUTHORED_ACTIVITIES[draft.lessonNumber]
              ? [...B1_MODULE_6_AUTHORED_ACTIVITIES[draft.lessonNumber]]
              : B1_MODULE_7_AUTHORED_ACTIVITIES[draft.lessonNumber]
                ? [...B1_MODULE_7_AUTHORED_ACTIVITIES[draft.lessonNumber]]
                : undefined,
  experience: B1_MODULE_1_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_2_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_3_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_4_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_5_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_6_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_7_EXPERIENCES[draft.lessonNumber],
})).map(enrichLesson);

export const B1_VOCABULARY = B1_LESSONS.flatMap((lesson) => lesson.words);
export const B1_GRAMMAR = B1_LESSONS.map((lesson) => lesson.grammar);
export const B1_COURSE: CourseDefinition = { level: "B1", title: "Connected lives and informed choices", titleArabic: "حياة مترابطة وخيارات واعية", totalLessons: 150, lessonsPerModule: 15, estimatedMinutes: 150 * 60, lessons: B1_LESSONS, modules: buildModuleDefinitions("B1", B1_LESSONS) };
export function getB1Lesson(lessonNumber: number) { return B1_LESSONS.find((lesson) => lesson.lessonNumber === lessonNumber); }
