import rawDraft from "./b1-draft.json";
import type { CourseDefinition, GrammarTopic, LessonDefinition, LessonExperience, LessonStep, VocabularyItem } from "./types";
import { enrichLesson } from "./activity-plan";
import { buildModuleDefinitions } from "./module-definitions";
import { createLessonExperience } from "./lesson-experience";
import { B1_MODULE_1_AUTHORED_ACTIVITIES } from "./b1-module-1-authored-activities";
import { B1_MODULE_2_AUTHORED_ACTIVITIES } from "./b1-module-2-authored-activities";
import { B1_MODULE_3_AUTHORED_ACTIVITIES } from "./b1-module-3-authored-activities";

type DraftVocabulary = { word: string; arabic: string; partOfSpeech: string; definition: string; exampleEN: string; exampleAR: string };
type DraftLesson = {
  lessonNumber: number;
  title: string;
  titleArabic: string;
  outcome: { canDo: string; canDoArabic: string; scenario: string; scenarioArabic: string };
  retrieval: Array<{ language: string; prompt: string; purpose: string }>;
  network: {
    theme: string; themeArabic: string; anchor: string; relatedWords: string[]; chunks: string[]; collocations: string[];
    register: "neutral" | "informal" | "formal" | "mixed"; priorLevelLinks: string[]; learningNote: string; learningNoteArabic: string;
    wordFamilies: Array<{ headword: string; forms: string[]; note: string; noteArabic: string }>;
  };
  vocabulary: DraftVocabulary[];
  grammar: { topic: string; arabicName: string; concept: string; arabicComparison: string; structure: string; commonError: string; exampleEN: string; exampleAR: string };
  readingBrief: string;
  writingPrompt: string;
};

const STEPS: LessonStep[] = [
  { id: "start", title: "Start here", titleArabic: "ابدأ هنا", purpose: "Take a position and reactivate A2 language needed for this scenario.", estimatedMinutes: 6 },
  { id: "explore", title: "Explore", titleArabic: "استكشف", purpose: "Study useful B1 chunks, collocations, word families, and tone.", estimatedMinutes: 12 },
  { id: "notice", title: "Notice", titleArabic: "لاحظ", purpose: "Trace grammar and discourse choices through a connected example.", estimatedMinutes: 12 },
  { id: "build", title: "Build", titleArabic: "ابنِ", purpose: "Shape a coherent paragraph, comparison, story segment, or practical response.", estimatedMinutes: 14 },
  { id: "respond", title: "Respond", titleArabic: "استجب", purpose: "Interpret an original source and respond for a real audience and purpose.", estimatedMinutes: 20 },
  { id: "prove", title: "Prove it", titleArabic: "أثبت إتقانك", purpose: "Transfer the language to a new task, receive feedback, and schedule review.", estimatedMinutes: 16 },
];

function asVocabularyItem(item: DraftVocabulary, lessonNumber: number, index: number): VocabularyItem {
  return { id: `b1-${lessonNumber}-${index + 1}`, word: item.word, arabic: item.arabic, ipa: "", phoneticRespelling: item.word, partOfSpeech: item.partOfSpeech, definition: item.definition, exampleEN: item.exampleEN, exampleAR: item.exampleAR };
}

function asGrammarTopic(lesson: DraftLesson): GrammarTopic {
  const grammar = lesson.grammar;
  return {
    id: `b1-grammar-${lesson.lessonNumber}`, lessonNumber: lesson.lessonNumber, topic: grammar.topic, arabicName: grammar.arabicName,
    concept: grammar.concept, represents: "Use this B1 pattern to make the meaning, relationship, or stance in your response precise.", arabicComparison: grammar.arabicComparison,
    useWhen: ["you need to connect ideas across a paragraph", "the B1 scenario requires a clear stance, sequence, or degree of certainty"],
    doNotUseWhen: ["a shorter A2 sentence already communicates the exact intended meaning"],
    commonMistakes: [{ wrong: grammar.commonError, correct: grammar.structure, explanation: "Check how the form changes the connection between your ideas." }],
    structure: { positive: grammar.structure, negative: `Check the limiting or negative form in: ${grammar.exampleEN}`, question: `Ask an AI follow-up question about ${grammar.topic}` },
    examples: [{ en: grammar.exampleEN, ar: grammar.exampleAR }], practice: [],
  };
}

const B1_MODULE_1_EXPERIENCES: Record<number, LessonExperience> = {
  1: createLessonExperience({ archetype: "speaking", density: "deep", archetypeRationale: "A turning point becomes memorable when learners rehearse a connected account before writing it.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A spoken story studio", whatToDo: "Rehearse a personal turning point with time signals.", whatMatters: "Sequence creates meaning, not only accuracy.", whatNext: "Turn your spoken account into a reflective email." }, progressiveSupports: ["worked-example", "word-support"] }),
  2: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Conditional choices are best learned by weighing consequences in a genuine group decision.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A community decision", whatToDo: "Compare what may happen with what you would choose.", whatMatters: "Separate likely results from imagined alternatives.", whatNext: "Carry this decision language into future advice." }, progressiveSupports: ["worked-example", "extended-rationale"] }),
  3: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "The first priority is noticing how calm boundary language differs from blame.", selectedStages: ["orientation", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A language-noticing lesson", whatToDo: "Read a disagreement and identify the boundary and repair.", whatMatters: "A specific need is clearer than a personal attack.", whatNext: "Rehearse a respectful repair conversation." }, progressiveSupports: ["arabic-help", "extended-rationale"] }),
  4: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A habit diary offers enough context to explore change, setback, and support critically.", selectedStages: ["encounter", "notice", "retrieval", "evidence"], firstView: { whatItIs: "A realistic habit diary", whatToDo: "Trace the writer’s change, setback, and support.", whatMatters: "Progress can be uneven and still be real.", whatNext: "Use this language to form your own sustainable plan." }, progressiveSupports: ["word-support"] }),
  5: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A qualified opinion needs deliberate planning, contrast, and a fair conclusion rather than a quick answer.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A balanced opinion task", whatToDo: "Write a fair view of a local issue with one clear limit.", whatMatters: "B1 opinions earn trust by acknowledging complexity.", whatNext: "Reuse hedging when making practical requests and proposals." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  6: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Email tone has a purpose and audience, so learners compare drafts before producing a request.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "An email tone workshop", whatToDo: "Choose the tone, then make a request that someone can act on.", whatMatters: "A clear action and timing matter as much as politeness.", whatNext: "Send a short, structured request." }, progressiveSupports: ["worked-example", "tip"] }),
  7: createLessonExperience({ archetype: "vocabulary", density: "normal", archetypeRationale: "Modal language gains force when tied to visible local priorities and a brief spoken pitch.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval"], firstView: { whatItIs: "A neighbourhood-priority map", whatToDo: "Sort what the area must, should, and could do.", whatMatters: "Each modal changes the strength of your claim.", whatNext: "Give a one-minute community pitch." }, progressiveSupports: ["arabic-help", "word-support"] }),
  8: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Reported speech serves a real collaborative purpose when a team must turn views into a fair plan.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A team-meeting reconstruction", whatToDo: "Report what each person said, then propose a fair action.", whatMatters: "Fair solutions begin with accurate listening.", whatNext: "Use this reporting skill for workplace and community tasks." }, progressiveSupports: ["transcript", "worked-example"] }),
  9: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A clear complaint demonstrates how chronological facts and passive forms make a practical problem understandable.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A service-problem case", whatToDo: "Separate the facts, impact, and requested solution.", whatMatters: "A reader should be able to act without guessing what happened.", whatNext: "Apply this clarity in formal messages." }, progressiveSupports: ["word-support", "extended-rationale"] }),
  10: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "Work choices are personal and practical, so a concise profile is more useful than a generic grammar drill.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A work-fit profile", whatToDo: "Connect your strengths, preferences, and a realistic next role.", whatMatters: "Use grammar to explain reasons, not to label yourself permanently.", whatNext: "Carry this self-knowledge into a proposal and team discussion." }, progressiveSupports: ["worked-example", "word-support"] }),
  11: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A proposal requires audience awareness, measured benefits, and an honest risk rather than a list of wishes.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A proposal-writing studio", whatToDo: "Recommend one improvement, its benefit, and how to manage a risk.", whatMatters: "Persuasion is stronger when it anticipates a concern.", whatNext: "Use this proposal structure in community action tasks." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  12: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A volunteer case lets learners evaluate impact and sustainability instead of repeating a positive slogan.", selectedStages: ["encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A community-project case study", whatToDo: "Assess the project’s impact and its practical limit.", whatMatters: "Support is worth judging by evidence and sustainability.", whatNext: "Transfer the reasoning to a source-based report." }, progressiveSupports: ["tip", "word-support"] }),
  13: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Source evaluation needs careful comparison, so the experience focuses on tracing a claim to reliable evidence.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence"], firstView: { whatItIs: "A source-check investigation", whatToDo: "Compare a claim with direct and reported sources.", whatMatters: "The loudest claim is not automatically the strongest evidence.", whatNext: "Apply this source language to media and design topics." }, progressiveSupports: ["extended-rationale", "tip"] }),
  14: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "A visual attention loop makes an abstract cause-and-effect pattern concrete before learners argue for a change.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use"], firstView: { whatItIs: "A design-and-habit investigation", whatToDo: "Identify one feature, its effect, and a calmer alternative.", whatMatters: "Design choices can shape behaviour without removing all choice.", whatNext: "Defend your change aloud using evidence." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  15: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The module ends by asking learners to make a persuasive claim while showing they can distinguish support from exaggeration.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A truthful campaign pitch", whatToDo: "Present and defend an idea with a justified comparison.", whatMatters: "A persuasive message should remain honest about its evidence.", whatNext: "Carry this critical voice into later B1 media work." }, progressiveSupports: ["tip", "external-ai-prompt"] }),
};

const B1_MODULE_2_EXPERIENCES: Record<number, LessonExperience> = {
  16: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Data literacy begins with a focused reading route that separates evidence from overreach.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A cautious-data case", whatToDo: "Identify what the survey supports and what remains unknown.", whatMatters: "Reliable communication names its limits.", whatNext: "Turn evidence and uncertainty into a practical recommendation." }, progressiveSupports: ["word-support", "tip"] }),
  17: createLessonExperience({ archetype: "speaking", density: "light", archetypeRationale: "A short spoken custom-sharing route makes inclusive language observable before a longer cultural response.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A respectful custom exchange", whatToDo: "Describe one custom and contrast it without ranking cultures.", whatMatters: "Personal experience is not a universal rule.", whatNext: "Use the same respectful contrast in a review or discussion." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  18: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A review earns its recommendation through evidence, evaluation, and one measured limitation.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A student-review studio", whatToDo: "Evaluate a cultural experience with two concrete examples.", whatMatters: "A fair limitation makes a recommendation more credible.", whatNext: "Reuse this balance when arguing for local choices." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  19: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Feedback language becomes useful when learners practise choosing exactly what help to request.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A tutor-feedback conversation", whatToDo: "Report progress and ask for two specific forms of help.", whatMatters: "Specific feedback requests make learning more actionable.", whatNext: "Carry this reflective language into career conversations." }, progressiveSupports: ["transcript", "worked-example"] }),
  20: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "Career language matters most when a spoken profile develops into an audience-aware written request.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A career direction workshop", whatToDo: "Connect experience, goals, and a realistic next step.", whatMatters: "Professional clarity can remain honest about uncertainty.", whatNext: "Use this profile in future workplace and project lessons." }, progressiveSupports: ["word-support", "external-ai-prompt"] }),
  21: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A disrupted journey needs chronological facts followed by a request another person can act upon.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use", "evidence"], firstView: { whatItIs: "A travel-repair case", whatToDo: "Explain what happened, its impact, and the solution you need.", whatMatters: "A concise request makes a stressful situation easier to solve.", whatNext: "Apply this sequence to formal service messages." }, progressiveSupports: ["word-support", "worked-example"] }),
  22: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "Visual cause-and-effect language lets learners explore a modest action before defending a proposal.", selectedStages: ["orientation", "encounter", "notice", "meaningful-use"], firstView: { whatItIs: "A small-action map", whatToDo: "Trace a local action, its benefit, and its trade-off.", whatMatters: "Good proposals explain both gains and limits.", whatNext: "Build a formal proposal from this map." }, progressiveSupports: ["arabic-help", "worked-example"] }),
  23: createLessonExperience({ archetype: "speaking", density: "deep", archetypeRationale: "A civic debate gives concession language a real purpose before learners turn it into a formal recommendation.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A balanced civic debate", whatToDo: "State a view, acknowledge one concern, and defend a practical response.", whatMatters: "Respectful disagreement strengthens rather than weakens an argument.", whatNext: "Write your balanced council recommendation." }, progressiveSupports: ["worked-example", "tip"] }),
  24: createLessonExperience({ archetype: "writing", density: "normal", archetypeRationale: "A future-focused personal email gives learners a bounded place to connect reflection, decision, and planning.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A next-chapter message", whatToDo: "Reflect on one choice and describe two future steps.", whatMatters: "Different future forms signal different degrees of planning.", whatNext: "Transfer this planning language to professional goals." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  25: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A structured short talk helps learners develop a social idea without depending on a long written scaffold.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A purposeful B1 talk", whatToDo: "Give two developed points about relationships and society.", whatMatters: "A clear opening and closing help listeners follow your reasoning.", whatNext: "Retrieve this structure for the module checkpoint." }, progressiveSupports: ["word-support", "tip"] }),
  26: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "A deliberate lexical review makes relationship and society language easier to select in later independent work.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A word-network review", whatToDo: "Group and retrieve language for support, disagreement, and cooperation.", whatMatters: "A network is more useful than a disconnected list.", whatNext: "Use your strongest retrieved words in the source task." }, progressiveSupports: ["word-support"] }),
  27: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Interpreting a community source trains learners to identify evidence and missing perspectives, not merely repeat a claim.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A source-interpretation task", whatToDo: "Find the claim, its evidence, and one missing voice.", whatMatters: "Evidence can be promising without being complete.", whatNext: "Use source-aware language in a revised argument." }, progressiveSupports: ["word-support", "tip"] }),
  28: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Revision is the central learning goal, so learners draft briefly and make their improvements visible.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A draft-and-revise studio", whatToDo: "Improve one social argument for clarity and register.", whatMatters: "Strong writers can explain why a revision helps their reader.", whatNext: "Use these revision checks for your final checkpoint." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  29: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A shared-space problem makes conditional compromise language necessary rather than ornamental.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A shared-space negotiation", whatToDo: "Offer, test, and refine a compromise with a condition.", whatMatters: "Good solutions explain what each side can accept.", whatNext: "Bring this practical reasoning into the checkpoint." }, progressiveSupports: ["transcript", "worked-example"] }),
  30: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The final task asks learners to combine respectful tone, evidence awareness, concession, and revision in an original recommendation.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A relationships-and-society checkpoint", whatToDo: "Recommend a response to a local issue with evidence and a realistic limit.", whatMatters: "An independent B1 response stays fair when the issue is complex.", whatNext: "Carry this social and professional voice into Module 3." }, progressiveSupports: ["tip", "external-ai-prompt"] }),
};

const B1_MODULE_3_EXPERIENCES: Record<number, LessonExperience> = {
  31: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "A visual map lets learners organise travel and adjustment language before they tell a connected account.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A journey-of-change map", whatToDo: "Name the trigger, adjustment, and outcome of one change.", whatMatters: "A clear map makes a connected story easier to tell.", whatNext: "Use this timeline language when giving advice." }, progressiveSupports: ["arabic-help", "word-support"] }),
  32: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Timeline language is useful when learners connect a completed event to an ongoing adjustment and a practical recommendation.", selectedStages: ["orientation", "encounter", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "An adjustment-language workshop", whatToDo: "Choose the tense and change verb that makes your timeline clear.", whatMatters: "A precise timeline helps advice sound grounded rather than generic.", whatNext: "Write useful moving advice for a real reader." }, progressiveSupports: ["worked-example", "tip"] }),
  33: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "The key goal is to spot how one earlier event explains a later travel decision.", selectedStages: ["orientation", "notice", "supported-practice", "evidence"], firstView: { whatItIs: "A timeline-noticing lesson", whatToDo: "Find the earlier event and explain its later effect.", whatMatters: "Past perfect helps a reader follow the order without guessing.", whatNext: "Apply the pattern in a changed-plan conversation." }, progressiveSupports: ["word-support", "extended-rationale"] }),
  34: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Replanning is inherently collaborative: learners must acknowledge a change and make a usable alternative.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A changed-plan dialogue", whatToDo: "Clarify what changed, offer an option, and check agreement.", whatMatters: "A flexible suggestion is clearer when it ends with a check.", whatNext: "Respond to a spoken travel update." }, progressiveSupports: ["transcript", "worked-example"] }),
  35: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "A short disruption update rewards focused listening and one practical follow-up question.", selectedStages: ["orientation", "encounter", "supported-practice", "evidence"], firstView: { whatItIs: "A live travel update", whatToDo: "Hear the change, then ask the question that affects your route.", whatMatters: "The most useful question targets impact, not every detail.", whatNext: "Read a fuller relocation account." }, progressiveSupports: ["transcript", "word-support"] }),
  36: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A relocation diary supports detailed inference about a partial solution, trade-offs, and unexpected benefits.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A realistic relocation diary", whatToDo: "Trace the problem, response, cost, and wider outcome.", whatMatters: "A workable solution does not need to be perfect.", whatNext: "Write about a change with the same honest balance." }, progressiveSupports: ["word-support", "tip"] }),
  37: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A connected paragraph gives learners time to move beyond a list of events into response and reflection.", selectedStages: ["orientation", "notice", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A connected-change writing studio", whatToDo: "Organise a change, your response, and a reflection in one paragraph.", whatMatters: "Links show the reader how events and choices relate.", whatNext: "Compare two practical options with the same care." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  38: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "Comparison language becomes purposeful when two routes have real costs, timing, and reliability trade-offs.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A route-choice decision", whatToDo: "Compare two options and justify one with a relevant trade-off.", whatMatters: "A good recommendation names the reason someone should accept a cost.", whatNext: "Repair a misunderstanding before it becomes a larger problem." }, progressiveSupports: ["worked-example", "tip"] }),
  39: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Repair language is only meaningful when a learner can acknowledge an error and propose a considerate next action.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A misunderstanding repair", whatToDo: "Clarify the mismatch, take responsibility, and offer one solution.", whatMatters: "Repair starts with accuracy and ends with a practical action.", whatNext: "Use the same calm tone in a visitor briefing." }, progressiveSupports: ["transcript", "worked-example"] }),
  40: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A short briefing makes learners select only essential information for a visitor facing a changed route.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "evidence"], firstView: { whatItIs: "A visitor travel briefing", whatToDo: "Give the important change, one route, and one backup.", whatMatters: "A listener needs priorities, not every fact you know.", whatNext: "Retrieve this useful language before checking a source." }, progressiveSupports: ["word-support", "worked-example"] }),
  41: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "Deliberate retrieval makes the network of disruption, adjustment, and outcome easier to access independently.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A travel-and-change word-network review", whatToDo: "Retrieve language by its role in a change story.", whatMatters: "A network helps you choose language instead of searching for it.", whatNext: "Use your strongest words to assess a travel source." }, progressiveSupports: ["arabic-help", "word-support"] }),
  42: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Source evaluation requires learners to separate official facts from a stronger personal interpretation.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A travel-source check", whatToDo: "Identify the official fact and test the traveller’s conclusion.", whatMatters: "A disruption is not proof that every outcome is impossible.", whatNext: "Draft a calm message that uses only relevant information." }, progressiveSupports: ["tip", "extended-rationale"] }),
  43: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Revision is visible when learners make an audience-aware message calmer, clearer, and easier to act on.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A message-revision studio", whatToDo: "Draft a changed plan, then improve one sentence for tone and clarity.", whatMatters: "A clear next question helps people make a decision.", whatNext: "Use the same priority logic in a linked-problem task." }, progressiveSupports: ["worked-example", "external-ai-prompt"] }),
  44: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "A relocation-day scenario makes prioritising, contingency planning, and concise communication necessary together.", selectedStages: ["orientation", "encounter", "meaningful-use", "retrieval", "evidence"], firstView: { whatItIs: "A relocation-day problem", whatToDo: "Prioritise the first action, then make a contingency plan.", whatMatters: "Good problem-solving protects the most time-sensitive action first.", whatNext: "Bring your decision-making to the module checkpoint." }, progressiveSupports: ["worked-example", "tip"] }),
  45: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint brings comparison, limitation, recommendation, and audience-aware messaging into one independent transfer task.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A travel-and-change checkpoint", whatToDo: "Compare options, recommend one, then write the message it requires.", whatMatters: "A credible recommendation explains both its strength and its limit.", whatNext: "Carry this adaptive voice into later B1 projects." }, progressiveSupports: ["tip", "external-ai-prompt"] }),
};

export const B1_LESSONS: LessonDefinition[] = (rawDraft as DraftLesson[]).map((draft) => ({
  level: "B1" as const, lessonNumber: draft.lessonNumber, moduleNumber: Math.ceil(draft.lessonNumber / 15), title: draft.title, titleArabic: draft.titleArabic,
  words: draft.vocabulary.map((item, index) => asVocabularyItem(item, draft.lessonNumber, index)), grammar: asGrammarTopic(draft),
  learningPlan: { outcome: draft.outcome, steps: STEPS, retrieval: draft.retrieval.map((item) => ({ sourceLevel: "A2" as const, language: item.language, prompt: item.prompt, purpose: item.purpose })), englishFirst: true, studio: "Story & Society Studio" },
  lexicalNetworks: [{ id: `b1-network-${draft.lessonNumber}`, theme: draft.network.theme, themeArabic: draft.network.themeArabic, anchor: draft.network.anchor, wordFamilies: draft.network.wordFamilies, relatedWords: draft.network.relatedWords, chunks: draft.network.chunks, collocations: draft.network.collocations, register: draft.network.register, priorLevelLinks: draft.network.priorLevelLinks, learningNote: draft.network.learningNote, learningNoteArabic: draft.network.learningNoteArabic }],
  practiceBrief: { readingBrief: draft.readingBrief, writingPrompt: draft.writingPrompt },
  activities: B1_MODULE_1_AUTHORED_ACTIVITIES[draft.lessonNumber]
    ? [...B1_MODULE_1_AUTHORED_ACTIVITIES[draft.lessonNumber]]
    : B1_MODULE_2_AUTHORED_ACTIVITIES[draft.lessonNumber]
      ? [...B1_MODULE_2_AUTHORED_ACTIVITIES[draft.lessonNumber]]
      : B1_MODULE_3_AUTHORED_ACTIVITIES[draft.lessonNumber]
        ? [...B1_MODULE_3_AUTHORED_ACTIVITIES[draft.lessonNumber]]
        : undefined,
  experience: B1_MODULE_1_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_2_EXPERIENCES[draft.lessonNumber] ?? B1_MODULE_3_EXPERIENCES[draft.lessonNumber],
})).map(enrichLesson);

export const B1_VOCABULARY = B1_LESSONS.flatMap((lesson) => lesson.words);
export const B1_GRAMMAR = B1_LESSONS.map((lesson) => lesson.grammar);
export const B1_COURSE: CourseDefinition = { level: "B1", title: "Connected lives and informed choices", titleArabic: "حياة مترابطة وخيارات واعية", totalLessons: 150, lessonsPerModule: 15, estimatedMinutes: 150 * 60, lessons: B1_LESSONS, modules: buildModuleDefinitions("B1", B1_LESSONS) };
export function getB1Lesson(lessonNumber: number) { return B1_LESSONS.find((lesson) => lesson.lessonNumber === lessonNumber); }
