import type { LessonActivity, LessonProgressionStage, LessonType } from "./types";

type Spec = {
  kind: LessonType;
  title: string;
  titleArabic: string;
  objective: string;
  objectiveArabic: string;
  stage: LessonProgressionStage;
  semantic: "objective" | "example" | "tip" | "common-mistake" | "vocabulary" | "grammar" | "activity" | "retrieval" | "assessment";
  minutes: number;
  prompt?: string;
  promptArabic?: string;
  readingText?: string;
  readingTextArabic?: string;
  speakingLines?: LessonActivity["speakingLines"];
  interactionTurns?: LessonActivity["interactionTurns"];
  sentencePatterns?: string[];
};

const specs: Record<number, Spec> = {
  121: { kind: "standard", title: "Triage a public claim", titleArabic: "افحص ادعاءً عاماً", objective: "Separate a public claim from its evidence and uncertainty before recommending one verification step.", objectiveArabic: "افصل بين الادعاء العام ودليله ودرجة عدم اليقين قبل اقتراح خطوة واحدة للتحقق.", stage: "explanation", semantic: "common-mistake", minutes: 16, sentencePatterns: ["The claim suggests …, but the evidence only shows …", "This appears to be … rather than …", "Before publishing, we should verify …"] },
  122: { kind: "reading", title: "Find the hidden cost", titleArabic: "اكتشف التكلفة الخفية", objective: "Evaluate who pays the hidden cost of a convenient service and qualify a recommendation for a mixed audience.", objectiveArabic: "قيّم من يدفع التكلفة الخفية لخدمة مريحة وقيّد توصية لجمهور متنوع.", stage: "explanation", semantic: "example", minutes: 21, readingText: "A fictional delivery service promises effortless shopping. Customers save time, yet drivers receive unstable schedules and small shops lose local trade. The report supports convenience, provided that the company publishes labour standards and gives neighbourhood shops a fair route into the platform.", readingTextArabic: "تَعِد خدمة توصيل خيالية بتسوق بلا جهد. يوفر العملاء الوقت، لكن السائقين يحصلون على جداول غير مستقرة وتخسر المتاجر الصغيرة تجارتها المحلية. يؤيد التقرير السهولة بشرط أن تنشر الشركة معايير العمل وتمنح متاجر الأحياء مساراً عادلاً إلى المنصة." },
  123: { kind: "interaction", title: "Interview for values", titleArabic: "أجرِ مقابلة عن القيم", objective: "Ask about workplace values, reformulate a colleague's priority, and propose one evidence-aware improvement.", objectiveArabic: "اسأل عن قيم مكان العمل، وأعد صياغة أولوية زميل، واقترح تحسيناً واحداً قائماً على الدليل.", stage: "real-context", semantic: "activity", minutes: 17, interactionTurns: [{ id: "colleague", speaker: "Colleague", text: "A good workplace is one that pays well, even if the schedule changes often.", textArabic: "مكان العمل الجيد هو الذي يدفع أجراً جيداً، حتى لو تغيّر الجدول كثيراً.", purpose: "State one workplace priority." }, { id: "you", speaker: "You", text: "If I understand you, financial security matters most. I agree it matters, but could we also test … because …?", textArabic: "إذا فهمتك، فإن الأمان المالي هو الأهم. أتفق على أهميته، لكن هل يمكننا أيضاً اختبار… لأن…؟", purpose: "Reformulate and propose." }] },
  124: { kind: "listening", title: "Follow a system failure", titleArabic: "تابع فشل النظام", objective: "Listen for the sequence and consequences of a service failure, then identify the most responsible next action.", objectiveArabic: "استمع إلى تسلسل فشل خدمة وعواقبه، ثم حدّد الخطوة التالية الأكثر مسؤولية.", stage: "explanation", semantic: "activity", minutes: 17, speakingLines: [{ id: "briefing", speaker: "Incident lead", text: "At 8:10 the payment system slowed. By 8:30, several users had been charged twice. The team first paused new payments, then checked the logs before contacting affected customers. We still need to explain the delay and publish a correction.", textArabic: "في الساعة 8:10 تباطأ نظام الدفع. وبحلول 8:30، تم تحصيل الرسوم من عدة مستخدمين مرتين. أوقف الفريق المدفوعات الجديدة أولاً، ثم فحص السجلات قبل التواصل مع العملاء المتأثرين. ما زلنا بحاجة إلى شرح التأخير ونشر تصحيح." }] },
  125: { kind: "reading", title: "Read behind the number", titleArabic: "اقرأ ما وراء الرقم", objective: "Interpret a statistic by distinguishing its measurement, comparison, and implied conclusion.", objectiveArabic: "فسّر إحصائية من خلال التمييز بين قياسها ومقارنتها والنتيجة التي توحي بها.", stage: "explanation", semantic: "common-mistake", minutes: 20, readingText: "A council report says complaints fell by 30% after a new online form was introduced. The figure compares six weeks with the previous six weeks, but it does not show whether residents who cannot use the form stopped reporting problems. The report therefore supports a cautious conclusion, not proof that the service improved for everyone.", readingTextArabic: "يقول تقرير للمجلس إن الشكاوى انخفضت بنسبة 30٪ بعد تقديم نموذج إلكتروني جديد. يقارن الرقم ستة أسابيع بالأسابيع الستة السابقة، لكنه لا يوضح ما إذا كان السكان الذين لا يستطيعون استخدام النموذج قد توقفوا عن الإبلاغ عن المشكلات. لذلك يدعم التقرير نتيجة حذرة، لا دليلاً على تحسن الخدمة للجميع." },
  126: { kind: "writing", title: "Write a difficult decision note", titleArabic: "اكتب مذكرة عن قرار صعب", objective: "Write a concise decision note that acknowledges competing interests and recommends an ethically and financially defensible option.", objectiveArabic: "اكتب مذكرة قرار موجزة تعترف بالمصالح المتنافسة وتوصي بخيار يمكن الدفاع عنه أخلاقياً ومالياً.", stage: "real-context", semantic: "activity", minutes: 22, prompt: "Write 170–210 words to a community director deciding whether to cancel a programme after budget cuts. Acknowledge two affected groups, concede one financial constraint, and recommend a revised plan with a review date.", promptArabic: "اكتب 170–210 كلمة إلى مدير مجتمع يقرر إلغاء برنامج بعد خفض الميزانية. اعترف بمجموعتين متأثرتين، وسلّم بقيد مالي واحد، واقترح خطة معدلة مع موعد مراجعة." },
  127: { kind: "standard", title: "Choose an accessible design", titleArabic: "اختر تصميماً متاحاً للجميع", objective: "Evaluate two public-space proposals and select cost-aware measures that improve access and inclusion.", objectiveArabic: "قيّم اقتراحين لمساحة عامة واختر إجراءات تراعي التكلفة وتحسن الوصول والشمول.", stage: "guided-practice", semantic: "activity", minutes: 18, sentencePatterns: ["Proposal A would benefit …, whereas …", "The most urgent measure would be … because …", "A lower-cost alternative would be …, provided that …"] },
  128: { kind: "speaking", title: "Make participation fairer", titleArabic: "اجعل المشاركة أكثر عدلاً", objective: "Explain whose voice is missing in a consultation, answer an opposing view, and propose a fairer participation route.", objectiveArabic: "اشرح صوت من الغائب في استشارة، وأجب عن رأي مخالف، واقترح مساراً أكثر عدلاً للمشاركة.", stage: "real-context", semantic: "activity", minutes: 17, speakingLines: [{ id: "official", speaker: "Official", text: "The consultation was open to everyone, so the current procedure is already fair.", textArabic: "كانت الاستشارة مفتوحة للجميع، لذلك فإن الإجراء الحالي عادل بالفعل." }, { id: "you", speaker: "You", text: "Open access is a useful start. However, the attendance record suggests that … . We could make participation fairer by … .", textArabic: "إتاحة الوصول بداية مفيدة. لكن سجل الحضور يشير إلى أن… . يمكننا جعل المشاركة أكثر عدلاً من خلال… ." }] },
  129: { kind: "writing", title: "Build the case for reform", titleArabic: "ابنِ حجة للإصلاح", objective: "Write a focused evidence-based reform proposal that anticipates and refutes the strongest objection.", objectiveArabic: "اكتب اقتراح إصلاح مركزاً قائماً على الدليل يتوقع أقوى اعتراض ويرد عليه.", stage: "independent-practice", semantic: "assessment", minutes: 24, prompt: "Write 200–240 words responding to a newspaper letter opposing a local reform. State the evidence, propose one specific change, acknowledge the strongest objection, and refute it without dismissing the writer.", promptArabic: "اكتب 200–240 كلمة رداً على رسالة صحفية تعارض إصلاحاً محلياً. اذكر الدليل، واقترح تغييراً محدداً، واعترف بأقوى اعتراض، ورد عليه دون التقليل من كاتب الرسالة." },
  130: { kind: "assessment", title: "Respond to risk without panic", titleArabic: "استجب للخطر دون هلع", objective: "Complete the ten-lesson checkpoint by evaluating evidence, acknowledging uncertainty, proposing practical action, and answering a counterargument.", objectiveArabic: "أكمل نقطة التحقق بعد عشرة دروس بتقييم الدليل والاعتراف بعدم اليقين واقتراح إجراء عملي والرد على حجة مضادة.", stage: "assessment", semantic: "assessment", minutes: 28, prompt: "Write 220–260 words for a public health newsletter responding to a reader who says an activity is too risky. Use two evidence points, one calibrated claim, one concession, a practical safeguard, and a qualified conclusion.", promptArabic: "اكتب 220–260 كلمة لنشرة صحية عامة رداً على قارئ يقول إن نشاطاً ما شديد الخطورة. استخدم نقطتي دليل، وادعاءً مضبوطاً، وتنازلاً، وضمانة عملية، وخلاصة مقيدة." },
  131: { kind: "listening", title: "Judge expertise and trust", titleArabic: "احكم على الخبرة والثقة", objective: "Evaluate competing expert voices, report their positions fairly, and propose a trust policy for readers and editors.", objectiveArabic: "قيّم أصوات الخبراء المتنافسة، وانقل مواقفهم بعدل، واقترح سياسة للثقة للقراء والمحررين.", stage: "independent-practice", semantic: "example", minutes: 22, speakingLines: [{ id: "panel", speaker: "Panel host", text: "The clinician explains the limits of the evidence. The influencer cites one dramatic case. A reader asks whether expertise alone should settle the question. The editor proposes showing the evidence, the uncertainty, and the source's relevant experience.", textArabic: "يشرح الطبيب حدود الدليل. ويذكر المؤثر حالة درامية واحدة. يسأل قارئ عما إذا كانت الخبرة وحدها يجب أن تحسم السؤال. يقترح المحرر عرض الدليل وعدم اليقين والخبرة ذات الصلة للمصدر." }] },
  132: { kind: "interaction", title: "Negotiate a fair compromise", titleArabic: "تفاوض على تسوية عادلة", objective: "Weigh stakeholder interests, disagree diplomatically, and formulate a conditional compromise.", objectiveArabic: "وازن مصالح أصحاب المصلحة، واختلف دبلوماسياً، وصغ تسوية مشروطة.", stage: "real-context", semantic: "activity", minutes: 19, interactionTurns: [{ id: "resident", speaker: "Resident", text: "The redevelopment must create jobs, even if the old market disappears.", textArabic: "يجب أن يخلق التطوير وظائف، حتى لو اختفى السوق القديم.", purpose: "State one priority." }, { id: "you", speaker: "You", text: "I see why jobs matter. Could we protect the market's essential features while allowing development, provided that …?", textArabic: "أفهم أهمية الوظائف. هل يمكننا حماية العناصر الأساسية للسوق مع السماح بالتطوير، بشرط أن…؟", purpose: "Acknowledge, challenge, and condition." }] },
  133: { kind: "writing", title: "Connect attention to consequence", titleArabic: "اربط الانتباه بالعاقبة", objective: "Write an opinion piece connecting platform causes and consequences, addressing a counterargument, and proposing a practical alternative.", objectiveArabic: "اكتب مقال رأي يربط أسباب المنصة وعواقبها ويتناول حجة مضادة ويقترح بديلاً عملياً.", stage: "real-context", semantic: "grammar", minutes: 25, prompt: "Write 200–260 words for a newspaper editor evaluating a proposal to limit persuasive design in apps. Use two clear cause–effect links, one participle clause, a counterargument, and one practical alternative.", promptArabic: "اكتب 200–260 كلمة لمحرر صحيفة تقيّم فيها اقتراحاً للحد من التصميم الإقناعي في التطبيقات. استخدم رابطين واضحين بين السبب والنتيجة، وعبارة اسم فاعل، وحجة مضادة، وبديلاً عملياً." , sentencePatterns: ["Designed to increase …, the feature can also …", "By encouraging …, the platform …", "Although critics argue …, a practical alternative would be …"] },
  134: { kind: "reading", title: "Ask who benefits from progress", titleArabic: "اسأل من يستفيد من التقدم", objective: "Evaluate who benefits from an innovation, concede its strengths, and propose concrete amendments for fair access.", objectiveArabic: "قيّم من يستفيد من ابتكار، واعترف بنقاط قوته، واقترح تعديلات ملموسة للوصول العادل.", stage: "independent-practice", semantic: "example", minutes: 22, readingText: "A local technology initiative gives residents faster access to public services. Early users praise the design, while people with limited data, older devices, or mobility barriers report difficulty. The feature is promising; nevertheless, the council should add an offline route, staffed support, and an accessibility review before expanding it.", readingTextArabic: "يمنح مبادرة تقنية محلية السكان وصولاً أسرع إلى الخدمات العامة. يمدح المستخدمون الأوائل التصميم، بينما يواجه الأشخاص ذوو البيانات المحدودة أو الأجهزة القديمة أو عوائق الحركة صعوبة. الميزة واعدة؛ ومع ذلك، ينبغي للمجلس إضافة مسار غير متصل ودعم من الموظفين ومراجعة لإتاحة الوصول قبل التوسع." },
  135: { kind: "assessment", title: "Translate culture with judgement", titleArabic: "ترجم الثقافة بحُكم", objective: "Propose a nuanced translation strategy that weighs cultural trade-offs and responds respectfully to a literal-fidelity objection.", objectiveArabic: "اقترح استراتيجية ترجمة دقيقة توازن المفاضلات الثقافية وترد باحترام على اعتراض يفضل الترجمة الحرفية.", stage: "assessment", semantic: "assessment", minutes: 30, prompt: "Write 240–300 words to a cultural magazine proposing how to translate humour, local idioms, and a community celebration. Explain two trade-offs, hedge one generalisation, and answer a critic who prefers literal fidelity.", promptArabic: "اكتب 240–300 كلمة إلى مجلة ثقافية تقترح فيها كيفية ترجمة الفكاهة والتعابير المحلية ومشهد احتفال مجتمعي. اشرح مفاضلتين، وقيّد تعميماً واحداً، وأجب عن ناقد يفضل الترجمة الحرفية." }
};

const check = (lesson: number): NonNullable<LessonActivity["retrievalCheck"]> => ({ prompt: `Retrieve one evidence, qualification, or decision move from Lesson ${lesson}.`, promptArabic: `استرجع حركة دليل أو تقييد أو قرار واحدة من الدرس ${lesson}.`, expectedEvidence: "A concise response that directly serves the lesson's primary objective.", expectedEvidenceArabic: "إجابة موجزة تخدم الهدف الأساسي للدرس مباشرة." });

export const B2_MODULE_9_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([key, spec]) => { const lesson = Number(key); const activity: LessonActivity = { id: `b2-m9-${lesson}`, kind: spec.kind, title: spec.title, titleArabic: spec.titleArabic, objective: spec.objective, objectiveArabic: spec.objectiveArabic, stage: spec.stage, estimatedMinutes: spec.minutes, semantic: spec.semantic, progressiveSupports: spec.kind === "reading" ? ["word-support", "arabic-help"] : spec.kind === "listening" ? ["transcript", "worked-example"] : spec.kind === "assessment" ? ["worked-example", "tip"] : ["worked-example", "word-support"], retrievalCheck: check(lesson), ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}), ...(spec.readingText ? { readingText: spec.readingText, readingTextArabic: spec.readingTextArabic } : {}), ...(spec.speakingLines ? { speakingLines: spec.speakingLines } : {}), ...(spec.interactionTurns ? { interactionTurns: spec.interactionTurns } : {}), ...(spec.sentencePatterns ? { sentencePatterns: spec.sentencePatterns } : {}) }; return [lesson, [activity]]; })) as Record<number, LessonActivity[]>;
