import type { LessonExperience } from "./types";
import { createLessonExperience } from "./lesson-experience";

export const B2_MODULE_9_EXPERIENCES: Record<number, LessonExperience> = {
  121: createLessonExperience({ archetype: "notice", density: "normal", archetypeRationale: "The opening lesson isolates claim, evidence, and uncertainty before the learner produces a recommendation.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "next-bridge"], firstView: { whatItIs: "A public-claim triage task.", whatToDo: "Separate what is claimed from what is actually shown.", whatMatters: "Verification protects the reader from overconfident conclusions.", whatNext: "Read about the costs hidden behind convenience." }, progressiveSupports: ["worked-example", "arabic-help", "tip"] }),
  122: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A layered source is needed to evaluate convenience alongside labour and community costs.", selectedStages: ["orientation", "encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A hidden-cost reading.", whatToDo: "Track who benefits and who carries the cost.", whatMatters: "A convenient result can still be unfairly distributed.", whatNext: "Ask workplace questions that reveal values." }, progressiveSupports: ["word-support", "arabic-help", "tip"] }),
  123: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Values and priorities are best made visible through a bounded workplace exchange.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A workplace-values interview.", whatToDo: "Ask, reformulate, and propose one improvement.", whatMatters: "Good questions turn vague promises into discussable evidence.", whatNext: "Listen through a service failure." }, progressiveSupports: ["worked-example", "tip"] }),
  124: createLessonExperience({ archetype: "listening", density: "normal", archetypeRationale: "The sequence and responsibility of an incident belong in an audio-first briefing.", selectedStages: ["orientation", "encounter", "notice", "retrieval", "next-bridge"], firstView: { whatItIs: "An audio-first incident briefing.", whatToDo: "Listen for sequence, consequence, and next action.", whatMatters: "Responsible response depends on what happened first.", whatNext: "Read how a number can mislead." }, progressiveSupports: ["transcript", "worked-example", "word-support"] }),
  125: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "The objective is disciplined statistical interpretation rather than another production task.", selectedStages: ["orientation", "encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A statistic-and-context reading.", whatToDo: "Identify the measure, comparison, and missing information.", whatMatters: "A number is not a conclusion by itself.", whatNext: "Write a difficult decision note." }, progressiveSupports: ["word-support", "arabic-help", "tip"] }),
  126: createLessonExperience({ archetype: "writing", density: "normal", archetypeRationale: "A concise decision note transfers the first five lessons into an audience-specific choice.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A decision note for a community director.", whatToDo: "Acknowledge interests, constraints, and one defensible plan.", whatMatters: "A good recommendation shows what it costs and how it will be reviewed.", whatNext: "Design an accessible public space." }, progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"] }),
  127: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "The proposal comparison needs a practical decision map, not a long essay.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A public-space design choice.", whatToDo: "Compare proposals and choose cost-aware access measures.", whatMatters: "Inclusion becomes real through concrete design decisions.", whatNext: "Make the consultation fairer." }, progressiveSupports: ["worked-example", "word-support", "tip"] }),
  128: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Missing voices and fair participation are best rehearsed in a live-feeling council exchange.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A consultation speaking task.", whatToDo: "Qualify an opposing view and propose a fairer route.", whatMatters: "Being invited is not the same as being heard.", whatNext: "Build a focused case for reform." }, progressiveSupports: ["worked-example", "tip"] }),
  129: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A focused reform proposal requires sustained evidence, objection handling, and audience control.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "An evidence-led reform response.", whatToDo: "Propose, anticipate, and refute.", whatMatters: "Answering the strongest objection makes a case more credible.", whatNext: "Complete the ten-lesson risk checkpoint." }, progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"] }),
  130: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The ten-lesson checkpoint measures transfer of evidence, qualification, consequence, and public response.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A ten-lesson public-risk checkpoint.", whatToDo: "Respond calmly, use evidence, and propose a safeguard.", whatMatters: "A qualified response can be both careful and useful.", whatNext: "Judge expertise and trust." }, progressiveSupports: ["worked-example", "tip", "external-ai-prompt"] }),
  131: createLessonExperience({ archetype: "listening", density: "deep", archetypeRationale: "Competing expert voices require listening for stance before the learner synthesises a trust policy.", selectedStages: ["orientation", "encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "An audio-first expertise panel.", whatToDo: "Track each voice's evidence, limits, and confidence.", whatMatters: "Expertise is relevant, but it does not remove the need for evidence.", whatNext: "Negotiate a compromise." }, progressiveSupports: ["transcript", "worked-example", "arabic-help"] }),
  132: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A conditional compromise depends on responsive listening and diplomatic disagreement.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A redevelopment negotiation.", whatToDo: "Recognise a priority and attach a fair condition.", whatMatters: "A compromise is a design for living with trade-offs.", whatNext: "Write about attention and consequence." }, progressiveSupports: ["worked-example", "tip"] }),
  133: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The opinion piece integrates causal grammar with a defined editorial audience and practical proposal.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "An attention-economy opinion piece.", whatToDo: "Connect design choices to consequences and an alternative.", whatMatters: "Clear causal links make a policy argument testable.", whatNext: "Read who benefits from progress." }, progressiveSupports: ["worked-example", "word-support", "external-ai-prompt"] }),
  134: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "The innovation source supports a final evidence-based access evaluation before module assessment.", selectedStages: ["orientation", "encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "An equitable-progress reading.", whatToDo: "Compare early benefits with barriers and amendments.", whatMatters: "Progress should be judged by who can actually use it.", whatNext: "Translate culture with judgement." }, progressiveSupports: ["word-support", "arabic-help", "tip"] }),
  135: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The module assessment asks for independent cultural, audience, and trade-off judgement rather than a copied public-policy response.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A B2 culture-and-judgement assessment.", whatToDo: "Propose a translation strategy and answer a reasonable objection.", whatMatters: "Faithful communication can preserve meaning without copying every word.", whatNext: "Move into the next B2 module." }, progressiveSupports: ["worked-example", "tip", "external-ai-prompt"] }),
};

export const B2_MODULE_9_EXPERIENCES_SUMMARY = "Compact Module 9 routes move from information triage to public-choice writing, audio-first trust evaluation, negotiation, and a culturally sensitive transfer assessment without a universal lesson sequence.";

export default B2_MODULE_9_EXPERIENCES;

void B2_MODULE_9_EXPERIENCES_SUMMARY;
