import type { LessonActivity, LessonProgressionStage, LessonType } from "./types";

type Spec = {
  kind: LessonType;
  title: string;
  titleArabic: string;
  objective: string;
  objectiveArabic: string;
  stage: LessonProgressionStage;
  semantic: "objective" | "example" | "tip" | "common-mistake" | "vocabulary" | "grammar" | "activity" | "retrieval" | "assessment";
  minutes: number;
  prompt?: string;
  promptArabic?: string;
  readingText?: string;
  readingTextArabic?: string;
  speakingLines?: LessonActivity["speakingLines"];
  interactionTurns?: LessonActivity["interactionTurns"];
  sentencePatterns?: string[];
};

const specs: Record<number, Spec> = {
  106: { kind: "standard", title: "Calibrate a risk", titleArabic: "عاير درجة الخطر", objective: "Use hedging to respond to a concern without exaggerating or dismissing the risk.", objectiveArabic: "استخدم لغة التحفظ للرد على قلق من دون مبالغة في الخطر أو تجاهله.", stage: "guided-practice", semantic: "grammar", minutes: 16, sentencePatterns: ["The risk appears to be …", "It may be worth …, provided that …", "I would not rule out …, although …"] },
  107: { kind: "reading", title: "Decide who to trust", titleArabic: "قرّر بمن تثق", objective: "Compare two expertise claims and report each source with an appropriate stance marker.", objectiveArabic: "قارن بين ادعاءين عن الخبرة وانقل كل مصدر باستخدام علامة موقف مناسبة.", stage: "explanation", semantic: "example", minutes: 20, readingText: "A fictional report compares a university researcher with a popular commentator. The researcher explains the limits of a small study, while the commentator presents one dramatic example as decisive. The report recommends trusting the careful claim, not the louder voice.", readingTextArabic: "يقارن تقرير خيالي بين باحث جامعي ومعلّق مشهور. يشرح الباحث حدود دراسة صغيرة، بينما يقدم المعلّق مثالاً درامياً واحداً كأنه حاسم. يوصي التقرير بالثقة في الادعاء الدقيق، لا في الصوت الأعلى." },
  108: { kind: "interaction", title: "Negotiate a fair compromise", titleArabic: "تفاوض على حل وسط عادل", objective: "Disagree diplomatically and propose a conditional compromise that recognises two competing priorities.", objectiveArabic: "اعترض بطريقة دبلوماسية واقترح حلاً وسطاً مشروطاً يعترف بأولويتين متنافستين.", stage: "real-context", semantic: "activity", minutes: 17, interactionTurns: [{ id: "partner", speaker: "Colleague", text: "The plan must either cut costs or protect every service.", textArabic: "يجب أن تخفض الخطة التكاليف أو تحمي كل خدمة.", purpose: "State a false choice." }, { id: "you", speaker: "You", text: "I take your point, but could we protect the essential service while reducing …? That would work provided that … .", textArabic: "أتفهم وجهة نظرك، لكن هل يمكننا حماية الخدمة الأساسية مع تقليل…؟ سينجح ذلك بشرط أن… .", purpose: "Challenge and negotiate." }] },
  109: { kind: "standard", title: "Trace attention and consequence", titleArabic: "تتبّع الانتباه والنتيجة", objective: "Use participle clauses to connect a platform design choice with its consequences and a practical proposal.", objectiveArabic: "استخدم عبارات اسم الفاعل لربط اختيار تصميم المنصة بعواقبه واقتراح عملي.", stage: "guided-practice", semantic: "grammar", minutes: 15, sentencePatterns: ["By encouraging users to …, the platform …", "Designed to …, the feature can also …", "Having increased …, the service should now …"] },
  110: { kind: "reading", title: "Ask who benefits", titleArabic: "اسأل من المستفيد", objective: "Evaluate who gains from an innovation and qualify a fair-access recommendation with concession and contrast.", objectiveArabic: "قيّم من يستفيد من ابتكار وقيّد توصية للوصول العادل باستخدام التنازل والمقارنة.", stage: "explanation", semantic: "example", minutes: 21, readingText: "A fictional city introduces a smart transport pass. Frequent commuters save time, but residents without smartphones struggle to register. The article calls the innovation promising; nevertheless, it argues that a paper route and staffed support are necessary.", readingTextArabic: "تطلق مدينة خيالية بطاقة نقل ذكية. يوفر الركاب المتكررون الوقت، لكن السكان الذين لا يملكون هواتف ذكية يواجهون صعوبة في التسجيل. يصف المقال الابتكار بأنه واعد، ومع ذلك يجادل بضرورة توفير مسار ورقي ودعم من الموظفين." },
  111: { kind: "writing", title: "Translate with care", titleArabic: "ترجم بعناية", objective: "Write a qualified recommendation about a translation choice that affects cultural identity.", objectiveArabic: "اكتب توصية مقيدة حول اختيار ترجمة يؤثر في الهوية الثقافية.", stage: "real-context", semantic: "activity", minutes: 22, prompt: "Write 170–210 words advising a museum on how to translate one culturally specific phrase. Explain the trade-off, hedge one generalisation, and recommend a respectful solution.", promptArabic: "اكتب 170–210 كلمة تنصح فيها متحفاً بكيفية ترجمة عبارة خاصة بثقافة ما. اشرح المفاضلة، وقيّد تعميماً واحداً، واقترح حلاً محترماً." },
  112: { kind: "listening", title: "Listen for belonging and exclusion", titleArabic: "استمع إلى الانتماء والاستبعاد", objective: "Distinguish a community claim from the qualification and question of who is included or excluded.", objectiveArabic: "ميّز بين ادعاء عن المجتمع والتحفظ وسؤال من يَدخل فيه ومن يُستبعد.", stage: "explanation", semantic: "common-mistake", minutes: 16, speakingLines: [{ id: "host", speaker: "Host", text: "The company says its members are a community, not simply customers. That may be true to some extent, but what kind of belonging is being created, and who is left out?", textArabic: "تقول الشركة إن أعضاءها مجتمع وليسوا مجرد عملاء. قد يكون ذلك صحيحاً إلى حد ما، لكن أي نوع من الانتماء يتم إنشاؤه، ومن يُستبعد؟" }] },
  113: { kind: "assessment", title: "Build a strong case", titleArabic: "ابنِ حجة قوية", objective: "Evaluate evidence, anticipate a counterargument, and make a balanced public-policy recommendation.", objectiveArabic: "قيّم الأدلة وتوقع حجة مضادة وقدّم توصية متوازنة في سياسة عامة.", stage: "assessment", semantic: "assessment", minutes: 27, prompt: "Write 220–260 words to a fictional council. Use two evidence points, one concession, one rebuttal, and a recommendation that includes a review measure.", promptArabic: "اكتب 220–260 كلمة إلى مجلس خيالي. استخدم نقطتي دليل وتنازلاً ورداً وتوصية تتضمن مقياساً للمراجعة." },
  114: { kind: "reading", title: "Question the automated decision", titleArabic: "تساءل عن القرار الآلي", objective: "Identify evidence of algorithmic bias and propose safeguards using passive and relative-clause framing.", objectiveArabic: "حدّد دليل التحيز الخوارزمي واقترح ضمانات باستخدام المبني للمجهول والجمل الموصولة.", stage: "explanation", semantic: "common-mistake", minutes: 22, readingText: "A fictional housing system rejects more applications from one neighbourhood. The vendor says the model was trained on historical data, which may reproduce earlier inequality. The review recommends that decisions be checked by staff and that affected applicants be given an explanation.", readingTextArabic: "يرفض نظام إسكان خيالي طلبات أكثر من حي واحد. تقول الشركة إن النموذج دُرّب على بيانات تاريخية قد تعيد إنتاج عدم مساواة سابقة. توصي المراجعة بأن يفحص الموظفون القرارات وأن يحصل المتأثرون على تفسير." },
  115: { kind: "writing", title: "Write a review that matters", titleArabic: "اكتب مراجعة مؤثرة", objective: "Write a concise evaluative response that weighs evidence, addresses a counterpoint, and gives a qualified recommendation.", objectiveArabic: "اكتب رداً تقييمياً موجزاً يوازن الأدلة ويتناول نقطة مضادة ويقدم توصية مقيدة.", stage: "real-context", semantic: "activity", minutes: 21, prompt: "Write 160–200 words reviewing a fictional public service. Weigh one benefit and one limitation, answer a reasonable counterpoint, and recommend a next step.", promptArabic: "اكتب 160–200 كلمة تراجع فيها خدمة عامة خيالية. وازن بين فائدة وحدّ، وأجب عن نقطة مضادة معقولة، واقترح خطوة تالية." },
  116: { kind: "interaction", title: "Disagree and keep learning", titleArabic: "اختلف واستمر في التعلم", objective: "Reformulate another person’s view accurately before making an evidence-based respectful challenge.", objectiveArabic: "أعد صياغة رأي شخص آخر بدقة قبل تقديم اعتراض محترم قائم على الدليل.", stage: "real-context", semantic: "activity", minutes: 16, interactionTurns: [{ id: "partner", speaker: "Partner", text: "The proposal is popular, so it must be the right choice.", textArabic: "الاقتراح شائع، لذلك لا بد أن يكون الخيار الصحيح.", purpose: "Offer a popularity claim." }, { id: "you", speaker: "You", text: "If I understand you correctly, you value public support. I agree that it matters, but the evidence also suggests … .", textArabic: "إذا فهمتك بشكل صحيح، فأنت تقدر الدعم العام. أتفق على أهميته، لكن الدليل يشير أيضاً إلى… .", purpose: "Reformulate and challenge." }] },
  117: { kind: "standard", title: "Predict a proposal's consequences", titleArabic: "تنبأ بعواقب اقتراح", objective: "Recommend a modified policy and predict likely outcomes using formal hedging and evidence.", objectiveArabic: "أوصِ بسياسة معدلة وتنبأ بالنتائج المحتملة باستخدام التحفظ الرسمي والدليل.", stage: "guided-practice", semantic: "grammar", minutes: 17, sentencePatterns: ["The revised plan is likely to …", "This would appear to address …, although …", "If the council were to …, it might …"] },
  118: { kind: "reading", title: "Balance work and purpose", titleArabic: "وازن بين العمل والغاية", objective: "Evaluate evidence and trade-offs in a workplace wellbeing proposal before recommending a practical plan.", objectiveArabic: "قيّم الأدلة والمفاضلات في اقتراح لرفاه مكان العمل قبل التوصية بخطة عملية.", stage: "explanation", semantic: "example", minutes: 21, readingText: "A fictional employer proposes meeting-free afternoons to reduce burnout. Staff surveys support the idea, but some teams need rapid coordination. The article recommends a trial with clear exceptions and a review after six weeks.", readingTextArabic: "يقترح صاحب عمل خيالي فترات بعد الظهر بلا اجتماعات لتقليل الإرهاق. تدعم استطلاعات الموظفين الفكرة، لكن بعض الفرق تحتاج إلى تنسيق سريع. يوصي المقال بتجربة مع استثناءات واضحة ومراجعة بعد ستة أسابيع." },
  119: { kind: "interaction", title: "Preserve what matters", titleArabic: "حافظ على ما يهم", objective: "Balance heritage, development, and sustainability in a justified conditional compromise.", objectiveArabic: "وازن بين التراث والتنمية والاستدامة في حل وسط مشروط ومبرر.", stage: "real-context", semantic: "activity", minutes: 20, interactionTurns: [{ id: "planner", speaker: "Planner", text: "The old building cannot remain unchanged, but demolition would erase a community landmark.", textArabic: "لا يمكن أن يبقى المبنى القديم دون تغيير، لكن هدمه سيمحو معلماً مجتمعياً.", purpose: "Present competing priorities." }, { id: "you", speaker: "You", text: "If the structure were adapted rather than replaced, it could …, provided that … .", textArabic: "لو جرى تكييف الهيكل بدلاً من استبداله، فقد… بشرط أن… .", purpose: "Propose a conditional compromise." }] },
  120: { kind: "assessment", title: "Defend a position", titleArabic: "دافع عن موقف", objective: "Write a concise persuasive response that concedes valid points and defends a justified recommendation.", objectiveArabic: "اكتب رداً إقناعياً موجزاً يعترف بالنقاط الصحيحة ويدافع عن توصية مبررة.", stage: "assessment", semantic: "assessment", minutes: 28, prompt: "Write 200–260 words for a real reader on a public-choice issue. Evaluate two views, concede one valid point, and finish with a qualified recommendation using cohesive links.", promptArabic: "اكتب 200–260 كلمة لقارئ حقيقي حول قضية اختيار عام. قيّم رأيين، واعترف بنقطة صحيحة واحدة، واختتم بتوصية مقيدة باستخدام روابط متماسكة." }
};

const check = (lesson: number): NonNullable<LessonActivity["retrievalCheck"]> => ({ prompt: `Retrieve one decision or discourse move from Lesson ${lesson}.`, promptArabic: `استرجع حركة قرار أو خطاب واحدة من الدرس ${lesson}.`, expectedEvidence: "A concise response that serves the lesson's primary objective.", expectedEvidenceArabic: "إجابة موجزة تخدم الهدف الأساسي للدرس." });

export const B2_MODULE_8_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([key, spec]) => { const lesson = Number(key); const activity: LessonActivity = { id: `b2-m8-${lesson}`, kind: spec.kind, title: spec.title, titleArabic: spec.titleArabic, objective: spec.objective, objectiveArabic: spec.objectiveArabic, stage: spec.stage, estimatedMinutes: spec.minutes, semantic: spec.semantic, progressiveSupports: spec.kind === "reading" ? ["word-support", "arabic-help"] : spec.kind === "listening" ? ["transcript", "worked-example"] : spec.kind === "assessment" ? ["worked-example", "tip"] : ["worked-example", "word-support"], retrievalCheck: check(lesson), ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}), ...(spec.readingText ? { readingText: spec.readingText, readingTextArabic: spec.readingTextArabic } : {}), ...(spec.speakingLines ? { speakingLines: spec.speakingLines } : {}), ...(spec.interactionTurns ? { interactionTurns: spec.interactionTurns } : {}), ...(spec.sentencePatterns ? { sentencePatterns: spec.sentencePatterns } : {}) }; return [lesson, [activity]]; })) as Record<number, LessonActivity[]>;
