import type { LessonExperience } from "./types";
import { createLessonExperience } from "./lesson-experience";

export const B2_MODULE_6_EXPERIENCES: Record<number, LessonExperience> = {
  76: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "Responsibility language needs a focused noticing route before longer source work.", selectedStages: ["orientation", "notice", "retrieval", "next-bridge"], firstView: { whatItIs: "A responsibility-language focus.", whatToDo: "Notice who acts and who receives action.", whatMatters: "Clear attribution prevents vague blame.", whatNext: "Read a statistic with limits." }, progressiveSupports: ["worked-example", "tip"] }),
  77: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "The statistic lesson is an evidence-reading task, not a general skills survey.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A statistic-reading investigation.", whatToDo: "Separate result, comparison, and limitation.", whatMatters: "A number needs a fair frame.", whatNext: "Choose under uncertainty." }, progressiveSupports: ["word-support", "tip"] }),
  78: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A constrained choice is best rehearsed through a short conditional exchange.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A constrained-choice exchange.", whatToDo: "State a choice and one consequence.", whatMatters: "Ethical decisions carry trade-offs.", whatNext: "Draft an accessible proposal." }, progressiveSupports: ["worked-example", "tip"] }),
  79: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The first sustained proposal consolidates access language without adding unrelated skills.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "An accessible-space proposal.", whatToDo: "Recommend two changes and one priority.", whatMatters: "A practical proposal names constraints.", whatNext: "Make a missing voice heard." }, progressiveSupports: ["worked-example", "word-support"] }),
  80: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Cleft sentences become useful when a speaker must foreground an absent perspective.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A missing-voice speaking task.", whatToDo: "Emphasise who or what is absent.", whatMatters: "Good consultation notices silence.", whatNext: "Build a written case." }, progressiveSupports: ["worked-example"] }),
  81: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "This is a focused evidence-and-rebuttal writing performance.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "An evidence-led reform proposal.", whatToDo: "Use evidence, answer an objection, and set a measure.", whatMatters: "A recommendation should be testable.", whatNext: "Listen for risk calibration." }, progressiveSupports: ["worked-example", "word-support"] }),
  82: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "Likelihood language needs a short audio-first discrimination route.", selectedStages: ["orientation", "encounter", "notice", "retrieval"], firstView: { whatItIs: "A risk-language listening focus.", whatToDo: "Sort likely, possible, and unsupported claims.", whatMatters: "Calibrated language protects judgement.", whatNext: "Decide whom to trust." }, progressiveSupports: ["transcript", "worked-example"] }),
  83: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Trust is tested by comparing expertise, evidence, and stance in a short source.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "An expertise-and-trust reading.", whatToDo: "Separate source role from proof.", whatMatters: "Expertise is not a substitute for evidence.", whatNext: "Negotiate a compromise." }, progressiveSupports: ["word-support", "tip"] }),
  84: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Conditional compromise belongs in a bounded negotiation, not a full lesson bundle.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A fair-compromise negotiation.", whatToDo: "Offer a condition and a review point.", whatMatters: "A compromise can be principled.", whatNext: "Connect cause and consequence." }, progressiveSupports: ["worked-example", "tip"] }),
  85: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "Participle clauses are practised as a compact cause-and-consequence focus.", selectedStages: ["encounter", "notice", "supported-practice", "retrieval"], firstView: { whatItIs: "A cause-and-consequence grammar focus.", whatToDo: "Join a cause to its consequence precisely.", whatMatters: "Compact grammar can sharpen explanation.", whatNext: "Ask who benefits." }, progressiveSupports: ["worked-example", "tip"] }),
  86: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Uneven benefit requires a short critical reading with concession.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A progress-for-whom reading.", whatToDo: "Compare benefit and barrier.", whatMatters: "Overall improvement may hide unequal access.", whatNext: "Listen to a translation choice." }, progressiveSupports: ["word-support", "tip"] }),
  87: createLessonExperience({ archetype: "listening", density: "normal", archetypeRationale: "Respectful qualification is best heard in a short authentic-feeling explanation.", selectedStages: ["orientation", "encounter", "notice", "retrieval"], firstView: { whatItIs: "A careful-translation listening task.", whatToDo: "Notice qualification and cultural respect.", whatMatters: "Precision can protect people and meaning.", whatNext: "Evaluate belonging strategies." }, progressiveSupports: ["transcript", "tip"] }),
  88: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The belonging task needs a sustained comparison and measured recommendation.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A community-building evaluation.", whatToDo: "Compare strategies and define trust.", whatMatters: "Belonging cannot be reduced to branding.", whatNext: "Make the B2 case." }, progressiveSupports: ["worked-example", "word-support"] }),
  89: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "This transfer assessment consolidates evidence, rebuttal, and recommendation without becoming the module test.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A public-policy argument check.", whatToDo: "Make and qualify a strong case.", whatMatters: "Persuasion needs fair reasoning.", whatNext: "Complete the technology checkpoint." }, progressiveSupports: ["tip", "worked-example"] }),
  90: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The module checkpoint asks for independent ethical evaluation and responsible safeguards.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A B2 technology-and-fairness checkpoint.", whatToDo: "Evaluate evidence and propose safeguards.", whatMatters: "Responsible judgement balances fairness and consequence.", whatNext: "Carry these habits into Module 7." }, progressiveSupports: ["tip", "worked-example"] }),
};
