import type { LessonActivity, LessonProgressionStage, LessonType } from "./types";

type Spec = { kind: LessonType; title: string; titleArabic: string; objective: string; objectiveArabic: string; stage: LessonProgressionStage; semantic: "objective" | "example" | "tip" | "common-mistake" | "vocabulary" | "grammar" | "activity" | "retrieval" | "assessment"; minutes: number; prompt?: string; promptArabic?: string; readingText?: string; readingTextArabic?: string; speakingLines?: LessonActivity["speakingLines"]; interactionTurns?: LessonActivity["interactionTurns"]; sentencePatterns?: string[] };

const specs: Record<number, Spec> = {
  61: { kind: "reading", title: "Read the frame around the news", titleArabic: "اقرأ إطار الخبر", objective: "Separate reported evidence from a feature writer's framing.", objectiveArabic: "افصل الدليل المنقول عن تأطير كاتب المقال.", stage: "explanation", semantic: "example", minutes: 16, readingText: "A fictional feature reports that speed has increased while context is often reduced; it does not claim that one format is always better.", readingTextArabic: "يذكر مقال خيالي زيادة السرعة ونقص السياق دون الحكم بأن طريقة واحدة أفضل دائماً." },
  62: { kind: "interaction", title: "Ask: progress for whom?", titleArabic: "اسأل: التقدم لمن؟", objective: "Qualify an improvement claim by naming both benefit and cost.", objectiveArabic: "تحفظ على ادعاء التحسين بذكر الفائدة والتكلفة.", stage: "real-context", semantic: "activity", minutes: 15, interactionTurns: [{ id: "brief", speaker: "Officer", text: "The new link will shorten journeys and attract investment.", textArabic: "سيختصر الخط الجديد الرحلات ويجذب الاستثمار.", purpose: "Present a benefit." }, { id: "you", speaker: "You", text: "Although it could …, the council should also examine … .", textArabic: "رغم أنه قد …، ينبغي للمجلس أن يفحص أيضاً … .", purpose: "Balance benefit and cost." }] },
  63: { kind: "listening", title: "Listen for respectful qualification", titleArabic: "استمع إلى التحفظ باحترام", objective: "Identify how a translator avoids a cultural generalisation.", objectiveArabic: "حدد كيف يتجنب المترجم تعميماً ثقافياً.", stage: "explanation", semantic: "common-mistake", minutes: 13, speakingLines: [{ id: "audio", speaker: "Translator", text: "Readers may recognise the image, but not necessarily the association behind it. I would avoid saying that one interpretation represents everyone.", textArabic: "قد يتعرف القراء على الصورة، لكن ليس بالضرورة على دلالتها. سأتجنب القول إن تفسيراً واحداً يمثل الجميع.", pronunciationHint: "Listen for may, not necessarily, and avoid." }] },
  64: { kind: "writing", title: "Evaluate the business of belonging", titleArabic: "قيّم تجارة الانتماء", objective: "Recommend one accountable change to a fictional inclusion campaign.", objectiveArabic: "أوصِ بتغيير مسؤول في حملة شمول خيالية.", stage: "real-context", semantic: "activity", minutes: 21, prompt: "Write 180–220 words: identify one credible inclusion action, one risk of tokenism, and one measurable change.", promptArabic: "اكتب 180–220 كلمة: حدد إجراء شمول حقيقياً وخطر الاستعراض وتغييراً قابلاً للقياس." },
  65: { kind: "assessment", title: "Build a case that can answer back", titleArabic: "ابن حجة تجيب عن الاعتراض", objective: "Write a recommendation with evidence, rebuttal, and a measurable outcome.", objectiveArabic: "اكتب توصية بدليل ورد على اعتراض ونتيجة قابلة للقياس.", stage: "assessment", semantic: "assessment", minutes: 24, prompt: "Advise a fictional council about extending a four-day-workweek pilot; use two evidence points, one objection, and one success measure.", promptArabic: "انصح مجلساً خيالياً بتوسيع تجربة أسبوع العمل من أربعة أيام؛ استخدم دليلين واعتراضاً ومقياس نجاح." },
  66: { kind: "standard", title: "Put responsibility into the sentence", titleArabic: "ضع المسؤولية في الجملة", objective: "Use relative clauses and passives to make responsibility for an automated decision visible.", objectiveArabic: "استخدم جمل الوصل والمبني للمجهول لإظهار المسؤولية عن قرار آلي.", stage: "guided-practice", semantic: "grammar", minutes: 14, sentencePatterns: ["The system, which was trained on …, may …", "Applicants were informed that …", "The organisation remains responsible for …"] },
  67: { kind: "reading", title: "Notice when a review changes the story", titleArabic: "لاحظ كيف يغير التقييم القصة", objective: "Distinguish appraisal language from evidence in a critical review.", objectiveArabic: "ميّز لغة التقييم عن الدليل في مراجعة نقدية.", stage: "explanation", semantic: "example", minutes: 17, readingText: "A fictional review calls an exhibition daring and uneven, praises accessible design, and quotes two visitors who disagree. Its broad audience claim rests on a small sample.", readingTextArabic: "تصف مراجعة خيالية معرضاً بأنه جريء وغير متساوٍ، وتمدح التصميم المتاح، وتستند في حكمها العام إلى عينة صغيرة." },
  68: { kind: "review", title: "Disagree without closing the door", titleArabic: "اختلف دون إغلاق الباب", objective: "Acknowledge a valid point before reformulating an absolute claim.", objectiveArabic: "اعترف بنقطة صحيحة قبل إعادة صياغة ادعاء مطلق.", stage: "review", semantic: "activity", minutes: 12, interactionTurns: [{ id: "view", speaker: "Community member", text: "The proposal is either perfect or useless.", textArabic: "المقترح إما مثالي أو عديم الفائدة.", purpose: "Offer an absolute claim." }, { id: "you", speaker: "You", text: "I can see why … . That said, the evidence also suggests … .", textArabic: "أفهم لماذا … . مع ذلك، تشير الأدلة أيضاً إلى … .", purpose: "Acknowledge and qualify." }] },
  69: { kind: "writing", title: "Project the consequences", titleArabic: "توقع العواقب", objective: "Compare two policy options and name a condition for review.", objectiveArabic: "قارن خيارين سياسيين وحدد شرطاً للمراجعة.", stage: "real-context", semantic: "activity", minutes: 23, prompt: "Compare two low-traffic-neighbourhood options, identify who may gain or lose, and recommend a phased plan with a six-month review.", promptArabic: "قارن خيارين لحي منخفض المرور، وحدد المستفيد والمتضرر، وأوص بخطة مرحلية ومراجعة بعد ستة أشهر." },
  70: { kind: "speaking", title: "Explain purpose under pressure", titleArabic: "اشرح الغاية تحت الضغط", objective: "Explain a workplace concern using a precise distinction and a qualified response.", objectiveArabic: "اشرح مشكلة عمل باستخدام تمييز دقيق واستجابة متحفظة.", stage: "real-context", semantic: "activity", minutes: 16, speakingLines: [{ id: "case", speaker: "Colleague", text: "I understand my role, but the workload leaves no time to do it well.", textArabic: "أفهم دوري، لكن عبء العمل لا يترك وقتاً لأؤديه جيداً.", pronunciationHint: "Notice purpose versus pressure." }, { id: "you", speaker: "You", text: "The issue is not so much … as … . One realistic response would be …", textArabic: "المشكلة ليست … بقدر ما هي … . ومن الاستجابات الواقعية …", pronunciationHint: "Give one distinction and one response." }] },
  71: { kind: "reading", title: "Decide what should be preserved", titleArabic: "قرر ما ينبغي الحفاظ عليه", objective: "Weigh heritage, access, and future use in a city debate.", objectiveArabic: "وازن بين التراث والوصول والاستخدام المستقبلي في نقاش مدني.", stage: "explanation", semantic: "example", minutes: 17, readingText: "A fictional council weighs replacing a historic market. The report records repair needs, affordable traders, local history, and access for older residents, then presents three options.", readingTextArabic: "يوازن مجلس خيالي بين استبدال سوق تاريخي واحتياجات الإصلاح والتجار والتاريخ المحلي والوصول لكبار السن." },
  72: { kind: "assessment", title: "Defend a position worth hearing", titleArabic: "دافع عن موقف يستحق الاستماع", objective: "Write a cohesive public letter with evidence and a credible counterpoint.", objectiveArabic: "اكتب رسالة عامة متماسكة بدليل ونقطة مضادة معقولة.", stage: "assessment", semantic: "assessment", minutes: 25, prompt: "Write to a fictional newspaper about selling a central library; use two evidence points, one financial concern, and a reviewable alternative.", promptArabic: "اكتب إلى صحيفة خيالية حول بيع مكتبة مركزية؛ استخدم دليلين ومخاوف مالية وبديلًا قابلاً للمراجعة." },
  73: { kind: "listening", title: "Report information under pressure", titleArabic: "انقل المعلومات تحت الضغط", objective: "Separate a reported claim, a verified finding, and an unresolved possibility.", objectiveArabic: "افصل بين ادعاء منقول ونتيجة مؤكدة واحتمال غير محسوم.", stage: "explanation", semantic: "common-mistake", minutes: 15, speakingLines: [{ id: "briefing", speaker: "Editor", text: "The post was widely shared, but the figures do not establish that the policy caused the change. The department confirms the dates; the explanation remains under review.", textArabic: "انتشر المنشور، لكن الأرقام لا تثبت أن السياسة سببت التغير. تؤكد الوزارة التواريخ، ويبقى التفسير قيد المراجعة.", pronunciationHint: "Listen for confirms, do not establish, and remains under review." }] },
  74: { kind: "writing", title: "Qualify the price of convenience", titleArabic: "تحفظ في سعر السهولة", objective: "Balance convenience with social and environmental trade-offs.", objectiveArabic: "وازن بين السهولة والمقايضات الاجتماعية والبيئية.", stage: "real-context", semantic: "activity", minutes: 22, prompt: "Recommend one habit change and one city policy while acknowledging delivery benefits and one trade-off.", promptArabic: "أوص بتغيير عادة وسياسة مدنية مع الاعتراف بفوائد التوصيل ومقايضة واحدة." },
  75: { kind: "assessment", title: "Propose a workplace worth joining", titleArabic: "اقترح مكان عمل يستحق الانضمام إليه", objective: "Evaluate workplace culture and propose a measurable flexible-hours pilot.", objectiveArabic: "قيّم ثقافة العمل واقترح تجربة ساعات مرنة قابلة للقياس.", stage: "assessment", semantic: "assessment", minutes: 28, prompt: "Write to a fictional HR director: evaluate culture, argue for a three-month flexible-hours pilot, acknowledge one objection, and state a success criterion.", promptArabic: "اكتب إلى مدير موارد بشرية خيالي: قيّم الثقافة، ودافع عن تجربة ساعات مرنة، واعترف باعتراض، وحدد معيار نجاح." },
};

const check = (n: number): NonNullable<LessonActivity["retrievalCheck"]> => ({ prompt: `Retrieve one useful idea from Lesson ${n}.`, promptArabic: `استرجع فكرة مفيدة من الدرس ${n}.`, expectedEvidence: "A concise response connected to the primary objective.", expectedEvidenceArabic: "إجابة مختصرة مرتبطة بالهدف الأساسي." });

export const B2_MODULE_5_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([key, spec]) => { const lesson = Number(key); const activity: LessonActivity = { id: `b2-m5-${lesson}`, kind: spec.kind, title: spec.title, titleArabic: spec.titleArabic, objective: spec.objective, objectiveArabic: spec.objectiveArabic, stage: spec.stage, estimatedMinutes: spec.minutes, semantic: spec.semantic, progressiveSupports: spec.kind === "listening" ? ["transcript", "worked-example"] : ["worked-example", "word-support"], retrievalCheck: check(lesson), ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}), ...(spec.readingText ? { readingText: spec.readingText, readingTextArabic: spec.readingTextArabic } : {}), ...(spec.speakingLines ? { speakingLines: spec.speakingLines } : {}), ...(spec.interactionTurns ? { interactionTurns: spec.interactionTurns } : {}), ...(spec.sentencePatterns ? { sentencePatterns: spec.sentencePatterns } : {}) }; return [lesson, [activity]]; })) as Record<number, LessonActivity[]>;
