import type { LessonExperience } from "./types";
import { createLessonExperience } from "./lesson-experience";

export const B2_MODULE_7_EXPERIENCES: Record<number, LessonExperience> = {
  91: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Nuanced appraisal is established through a short review-reading route.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A balanced-review reading.", whatToDo: "Separate praise, criticism, and qualification.", whatMatters: "Good judgement is rarely absolute.", whatNext: "Represent another view fairly." }, progressiveSupports: ["word-support", "tip"] }),
  92: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Accurate disagreement begins in a bounded reformulation exchange.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A respectful-disagreement exchange.", whatToDo: "Restate before challenging.", whatMatters: "Fair representation strengthens critique.", whatNext: "Recommend with consequences." }, progressiveSupports: ["worked-example", "tip"] }),
  93: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "Recommendation grammar needs a focused precision lesson.", selectedStages: ["encounter", "notice", "supported-practice", "retrieval"], firstView: { whatItIs: "A formal-recommendation focus.", whatToDo: "Connect a proposal to its likely result.", whatMatters: "A recommendation should show its reasoning.", whatNext: "Hear certainty under pressure." }, progressiveSupports: ["worked-example", "tip"] }),
  94: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "Purpose and pressure are best noticed in an audio-first briefing.", selectedStages: ["orientation", "encounter", "notice", "retrieval"], firstView: { whatItIs: "A pressured-briefing listening task.", whatToDo: "Notice emphasis and responsibility.", whatMatters: "Sound can signal what matters most.", whatNext: "Read what should be preserved." }, progressiveSupports: ["transcript", "worked-example"] }),
  95: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A balanced public-choice source provides the context for conditional consequences.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A preservation-and-change reading.", whatToDo: "Follow a recommendation and its conditions.", whatMatters: "Change can protect what matters.", whatNext: "Defend a position worth hearing." }, progressiveSupports: ["word-support", "tip"] }),
  96: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A brief public position makes concession and recommendation audible.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A public-position briefing.", whatToDo: "State, concede, and return to your case.", whatMatters: "Nuance can remain decisive.", whatNext: "Listen for certainty." }, progressiveSupports: ["worked-example"] }),
  97: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "Certainty calibration requires a short distinction task rather than a full production lesson.", selectedStages: ["encounter", "notice", "retrieval"], firstView: { whatItIs: "A certainty-and-evidence listening focus.", whatToDo: "Sort claim, admission, and uncertainty.", whatMatters: "Careful language protects trust.", whatNext: "Write the cost of convenience." }, progressiveSupports: ["transcript", "tip"] }),
  98: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A comparison gives learners one sustained opportunity to qualify a cost.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A convenience-and-cost comparison.", whatToDo: "Compare, concede, and recommend.", whatMatters: "Convenience has consequences.", whatNext: "Interpret workplace expectations." }, progressiveSupports: ["worked-example", "word-support"] }),
  99: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Workplace policy language is rehearsed as a practical response.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A workplace-policy exchange.", whatToDo: "Respond with measured obligation and inference.", whatMatters: "Policies reveal intended values.", whatNext: "Repair a failed system." }, progressiveSupports: ["worked-example", "tip"] }),
  100: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "Retrieval consolidates reporting, evaluation, and counterfactual language before new source work.", selectedStages: ["orientation", "retrieval", "next-bridge"], firstView: { whatItIs: "A compact system-repair review.", whatToDo: "Retrieve three useful distinctions.", whatMatters: "Review makes later reasoning faster.", whatNext: "Find the story behind a statistic." }, progressiveSupports: ["worked-example"] }),
  101: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Statistics need a context-rich critical-reading route.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A statistic-in-context reading.", whatToDo: "State what a figure proves and cannot prove.", whatMatters: "Numbers need boundaries.", whatNext: "Decide through counterfactuals." }, progressiveSupports: ["word-support", "tip"] }),
  102: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Mixed conditionals become meaningful in a difficult decision exchange.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A consequence-and-decision exchange.", whatToDo: "Connect a past choice to a present result.", whatMatters: "Reflection can inform action.", whatNext: "Design public space." }, progressiveSupports: ["worked-example", "tip"] }),
  103: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A formal proposal is the right scale for translating public needs into trade-offs.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A public-space proposal.", whatToDo: "Name priorities, trade-offs, and review.", whatMatters: "Practical writing makes choices visible.", whatNext: "Make every voice heard." }, progressiveSupports: ["worked-example", "word-support"] }),
  104: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Cleft sentences serve one clear purpose: foregrounding missing evidence or people.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A missing-voice statement.", whatToDo: "Emphasise what the evidence omitted.", whatMatters: "Attention can correct an incomplete picture.", whatNext: "Make the case for change." }, progressiveSupports: ["worked-example"] }),
  105: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The module checkpoint transfers evidence, concession, refutation, and recommendation to a new public case.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A change-and-evidence checkpoint.", whatToDo: "Build and qualify a public case.", whatMatters: "Responsible persuasion stays reviewable.", whatNext: "Carry the method forward." }, progressiveSupports: ["worked-example", "tip"] }),
};
