import type { LessonExperience } from "./types";
import { createLessonExperience } from "./lesson-experience";

export const B2_MODULE_8_EXPERIENCES: Record<number, LessonExperience> = {
  106: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "The opening lesson builds a source-based cultural lens before production.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A culture-and-perspective reading.", whatToDo: "Separate observation from interpretation.", whatMatters: "Respectful language leaves room for difference.", whatNext: "Notice how context changes meaning." }, progressiveSupports: ["word-support", "tip"] }),
  107: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "The lesson isolates contrastive discourse choices instead of adding another production task.", selectedStages: ["orientation", "notice", "retrieval"], firstView: { whatItIs: "A contrast-and-context focus.", whatToDo: "Choose the connector that fits the relationship.", whatMatters: "Small linking choices clarify nuance.", whatNext: "Use the pattern in an exchange." }, progressiveSupports: ["worked-example"] }),
  108: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Meaning repair is best practised as a short, realistic exchange.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A misunderstanding-repair exchange.", whatToDo: "Clarify without blaming.", whatMatters: "Good repair protects the relationship and the meaning.", whatNext: "Interpret a public conversation." }, progressiveSupports: ["worked-example", "tip"] }),
  109: createLessonExperience({ archetype: "listening", density: "normal", archetypeRationale: "The authentic spoken sample develops inference without requiring a full written response.", selectedStages: ["orientation", "encounter", "notice", "retrieval"], firstView: { whatItIs: "A listening-for-attitude task.", whatToDo: "Listen for stance and hesitation.", whatMatters: "Tone can qualify the words.", whatNext: "Read the same issue in print." }, progressiveSupports: ["transcript", "word-support"] }),
  110: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The mid-module writing task transfers context-sensitive language into a defined audience response.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A context-aware response.", whatToDo: "Write for a specific reader and purpose.", whatMatters: "Register is a choice, not decoration.", whatNext: "Compare competing interpretations." }, progressiveSupports: ["worked-example", "word-support"] }),
  111: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A short spoken comparison makes perspective and emphasis audible.", selectedStages: ["orientation", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A perspective comparison.", whatToDo: "Compare two reasonable readings of an issue.", whatMatters: "Precision is more useful than certainty.", whatNext: "Trace evidence across a source." }, progressiveSupports: ["worked-example"] }),
  112: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "The source asks learners to follow layered claims and implied assumptions.", selectedStages: ["encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A layered-argument reading.", whatToDo: "Track claim, support, and implication.", whatMatters: "An implied idea still needs testing.", whatNext: "Turn the analysis into a question." }, progressiveSupports: ["word-support", "tip"] }),
  113: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "The task rehearses asking for clarification and negotiating shared meaning.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A collaborative meaning check.", whatToDo: "Ask, restate, and confirm.", whatMatters: "Understanding is jointly built.", whatNext: "Make a careful recommendation." }, progressiveSupports: ["worked-example", "tip"] }),
  114: createLessonExperience({ archetype: "real-world", density: "normal", archetypeRationale: "A practical public-facing task gives the language a concrete consequence.", selectedStages: ["orientation", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A public-information choice.", whatToDo: "Adapt a message for its audience.", whatMatters: "Clarity includes what the reader needs next.", whatNext: "Review the language of responsibility." }, progressiveSupports: ["word-support", "tip"] }),
  115: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "A deliberate retrieval lesson consolidates the module’s discourse and perspective language.", selectedStages: ["orientation", "retrieval", "next-bridge"], firstView: { whatItIs: "A perspective-language review.", whatToDo: "Retrieve and sort the strongest expressions.", whatMatters: "Retrieval makes nuanced language available.", whatNext: "Use it under a new constraint." }, progressiveSupports: ["tip"] }),
  116: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "The grammar focus supports controlled concession and qualification for the upcoming tasks.", selectedStages: ["orientation", "notice", "supported-practice", "retrieval"], firstView: { whatItIs: "A qualification-pattern focus.", whatToDo: "Notice how concession changes force.", whatMatters: "A qualified claim can be stronger.", whatNext: "Apply it to a disagreement." }, progressiveSupports: ["worked-example", "word-support"] }),
  117: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "The learner must make a concise, audience-aware recommendation aloud.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A recommendation briefing.", whatToDo: "State a choice, reason, and limitation.", whatMatters: "Listeners need a usable conclusion.", whatNext: "Write the longer version." }, progressiveSupports: ["worked-example"] }),
  118: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A sustained response consolidates the module’s perspective, evidence, and register work.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A balanced position paper.", whatToDo: "Develop a view for a defined audience.", whatMatters: "Coherence is built sentence by sentence.", whatNext: "Test the transfer in the checkpoint." }, progressiveSupports: ["worked-example", "word-support"] }),
  119: createLessonExperience({ archetype: "assessment", density: "normal", archetypeRationale: "A short pre-checkpoint transfer task reveals what still needs retrieval.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A transfer rehearsal.", whatToDo: "Respond to an unfamiliar but related prompt.", whatMatters: "Transfer matters more than recognition.", whatNext: "Complete the module checkpoint." }, progressiveSupports: ["tip"] }),
  120: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The module checkpoint evaluates perspective, evidence, interaction, and controlled production without forcing every skill into one screen.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A B2 perspective-and-context checkpoint.", whatToDo: "Interpret, choose, and justify a response.", whatMatters: "Context-sensitive English supports responsible participation.", whatNext: "Move into the next B2 module." }, progressiveSupports: ["tip", "worked-example"] }),
};

export const B2_MODULE_8_EXPERIENCES_SUMMARY = "Compact Module 8 routes balance cultural interpretation, listening, interaction, writing, review, and assessment without using a universal lesson sequence.";

export default B2_MODULE_8_EXPERIENCES;

/*
  Module 8 is intentionally not a universal template. The selected route is the
  dominant learner experience; activities provide only the supporting evidence
  needed for that objective and retain a short retrieval check in the corpus.
*/

void B2_MODULE_8_EXPERIENCES_SUMMARY;
