import type { LessonActivity, LessonProgressionStage, LessonType } from "./types";

type Spec = {
  kind: LessonType;
  title: string;
  titleArabic: string;
  objective: string;
  objectiveArabic: string;
  stage: LessonProgressionStage;
  semantic: "objective" | "example" | "tip" | "common-mistake" | "vocabulary" | "grammar" | "activity" | "retrieval" | "assessment";
  minutes: number;
  prompt?: string;
  promptArabic?: string;
  readingText?: string;
  readingTextArabic?: string;
  speakingLines?: LessonActivity["speakingLines"];
  interactionTurns?: LessonActivity["interactionTurns"];
  sentencePatterns?: string[];
};

const specs: Record<number, Spec> = {
  91: { kind: "reading", title: "Notice what changes a review", titleArabic: "لاحظ ما الذي يغيّر المراجعة", objective: "Distinguish nuanced appraisal from praise or criticism that is too absolute.", objectiveArabic: "ميّز التقييم الدقيق من المدح أو النقد المطلق أكثر من اللازم.", stage: "explanation", semantic: "example", minutes: 19, readingText: "A fictional review of a public library pilot calls the quieter study rooms a meaningful improvement, but notes that the booking system remains confusing. The writer praises the staff response while qualifying the overall success.", readingTextArabic: "تصف مراجعة خيالية لتجربة في مكتبة عامة غرف الدراسة الهادئة بأنها تحسن مهم، لكنها تلاحظ أن نظام الحجز لا يزال مربكاً. يمدح الكاتب استجابة الموظفين مع تقييد الحكم على النجاح العام." },
  92: { kind: "interaction", title: "Learn through disagreement", titleArabic: "تعلّم من خلال الخلاف", objective: "Represent another person’s position accurately before offering a respectful challenge.", objectiveArabic: "مثّل موقف الشخص الآخر بدقة قبل تقديم اعتراض محترم.", stage: "real-context", semantic: "activity", minutes: 16, interactionTurns: [{ id: "partner", speaker: "Colleague", text: "I think the proposal is too expensive to consider.", textArabic: "أعتقد أن الاقتراح مكلف جداً بحيث لا يمكن النظر فيه.", purpose: "State a strong disagreement." }, { id: "you", speaker: "You", text: "If I understand you correctly, your concern is … . I agree that …, but could we also consider …?", textArabic: "إذا فهمتك بشكل صحيح، فإن قلقك هو… . أتفق أن…، لكن هل يمكننا أيضاً النظر في…؟", purpose: "Reformulate before challenging." }] },
  93: { kind: "standard", title: "Recommend with consequences", titleArabic: "أوصِ مع بيان العواقب", objective: "Use formal recommendation language to connect a proposal with likely consequences.", objectiveArabic: "استخدم لغة التوصية الرسمية لربط الاقتراح بالعواقب المحتملة.", stage: "guided-practice", semantic: "grammar", minutes: 15, sentencePatterns: ["I recommend that the council …", "This would be likely to …, although …", "If introduced gradually, the proposal could …"] },
  94: { kind: "listening", title: "Hear purpose and pressure", titleArabic: "استمع إلى المعنى والضغط", objective: "Identify emphasis and complex verb patterns when a speaker describes work pressure and purpose.", objectiveArabic: "حدّد التركيز وأنماط الأفعال المركبة عندما يصف متحدث ضغط العمل والغاية منه.", stage: "explanation", semantic: "common-mistake", minutes: 16, speakingLines: [{ id: "manager", speaker: "Manager", text: "What the team needs is time to solve the problem properly, rather than another urgent meeting. We are expected to respond quickly, but we are not meant to hide the risks.", textArabic: "ما يحتاجه الفريق هو وقت لحل المشكلة بشكل صحيح، وليس اجتماعاً عاجلاً آخر. من المتوقع أن نستجيب بسرعة، لكن ليس من المفترض أن نخفي المخاطر.", pronunciationHint: "Listen for emphasis and expected responsibility." }] },
  95: { kind: "reading", title: "Read what should be preserved", titleArabic: "اقرأ ما ينبغي الحفاظ عليه", objective: "Follow a balanced argument and identify how conditional consequences support its recommendation.", objectiveArabic: "تابع حجة متوازنة وحدد كيف تدعم العواقب الشرطية توصيتها.", stage: "explanation", semantic: "example", minutes: 20, readingText: "A fictional town is considering replacing a historic market with a transport hub. The proposal would reduce congestion, provided the design protects small traders and pedestrian access. The article argues that preservation need not mean refusing every change.", readingTextArabic: "تدرس بلدة خيالية استبدال سوق تاريخي بمركز نقل. سيقلل الاقتراح الازدحام إذا حمى التصميم التجار الصغار ووصول المشاة. وتجادل المقالة بأن الحفاظ لا يعني رفض كل تغيير." },
  96: { kind: "speaking", title: "Defend a position worth hearing", titleArabic: "دافع عن موقف يستحق الاستماع", objective: "Deliver a short structured position with appropriate register, cohesion, and one qualified concession.", objectiveArabic: "قدّم موقفاً منظماً قصيراً بسجل لغوي وترابط مناسبين وتنازل مقيد واحد.", stage: "real-context", semantic: "activity", minutes: 17, speakingLines: [{ id: "brief", speaker: "Chair", text: "The committee wants a clear recommendation, but it also wants to hear the strongest concern about it.", textArabic: "تريد اللجنة توصية واضحة، لكنها تريد أيضاً سماع أقوى تحفظ عليها.", pronunciationHint: "State your position, concede one concern, then return to your recommendation." }, { id: "you", speaker: "You", text: "On balance, I support …, although I accept that … . The strongest reason is … .", textArabic: "بناءً على الموازنة، أؤيد…، رغم أنني أقبل أن… . والسبب الأقوى هو… .", pronunciationHint: "Use a calm public register." }] },
  97: { kind: "listening", title: "Listen for certainty under pressure", titleArabic: "استمع إلى درجات التأكد تحت الضغط", objective: "Distinguish claims, admissions, and qualified uncertainty in a pressured information briefing.", objectiveArabic: "ميّز بين الادعاءات والاعترافات وعدم اليقين المقيد في إحاطة معلوماتية تحت الضغط.", stage: "explanation", semantic: "common-mistake", minutes: 17, speakingLines: [{ id: "briefing", speaker: "Analyst", text: "The early figures suggest a decline, but they do not prove a long-term trend. Officials claim the change is temporary; the independent review says that conclusion remains uncertain.", textArabic: "تشير الأرقام الأولية إلى انخفاض، لكنها لا تثبت اتجاهاً طويل الأمد. يزعم المسؤولون أن التغيير مؤقت؛ وتقول المراجعة المستقلة إن هذا الاستنتاج لا يزال غير مؤكد.", pronunciationHint: "Listen for suggest, claim, do not prove, and remains uncertain." }] },
  98: { kind: "writing", title: "Count the price of convenience", titleArabic: "احسب ثمن السهولة", objective: "Write a qualified comparison that acknowledges convenience while explaining a significant cost.", objectiveArabic: "اكتب مقارنة مقيدة تعترف بالسهولة مع شرح تكلفة مهمة.", stage: "real-context", semantic: "activity", minutes: 22, prompt: "Write 180–220 words comparing a convenient digital service with a slower community alternative. Concede one benefit, qualify one claim, and recommend an option.", promptArabic: "اكتب 180–220 كلمة تقارن بين خدمة رقمية سهلة وبديل مجتمعي أبطأ. اعترف بفائدة واحدة، وقيّد ادعاءً واحداً، وأوصِ بخيار." },
  99: { kind: "interaction", title: "Join a workplace worth joining", titleArabic: "انضم إلى مكان عمل يستحق الانضمام", objective: "Interpret workplace expectations and respond with measured obligation, criticism, or inference.", objectiveArabic: "فسّر توقعات مكان العمل واستجب بالتزام أو نقد أو استنتاج متزن.", stage: "real-context", semantic: "activity", minutes: 16, interactionTurns: [{ id: "policy", speaker: "Supervisor", text: "The new policy requires teams to record decisions, even when the meeting is informal.", textArabic: "تتطلب السياسة الجديدة من الفرق تسجيل القرارات حتى عندما يكون الاجتماع غير رسمي.", purpose: "Present an obligation." }, { id: "you", speaker: "You", text: "That seems reasonable, although the process might … . The policy must be intended to … .", textArabic: "يبدو ذلك معقولاً، رغم أن الإجراء قد… . لا بد أن هدف السياسة هو… .", purpose: "Respond with criticism and inference." }] },
  100: { kind: "review", title: "Repair a failed system", titleArabic: "أصلح نظاماً فاشلاً", objective: "Retrieve and repair reporting, evaluation, and consequence language in a system-failure case.", objectiveArabic: "استرجع وأصلح لغة الإبلاغ والتقييم والعواقب في حالة فشل نظام.", stage: "guided-practice", semantic: "retrieval", minutes: 15, sentencePatterns: ["It was reported that …", "The evidence appears to …", "If the process had been …, the result might have …"] },
  101: { kind: "reading", title: "Find the story behind a statistic", titleArabic: "اعثر على القصة وراء الإحصائية", objective: "Interpret a statistic in context and explain what it does and does not prove.", objectiveArabic: "فسّر إحصائية في سياقها واشرح ما تثبته وما لا تثبته.", stage: "explanation", semantic: "example", minutes: 21, readingText: "A fictional report states that complaints fell by 30% after a service redesign. The figure covers only online complaints, while phone complaints were recorded differently. The report calls the change encouraging but says the evidence is not yet conclusive.", readingTextArabic: "يذكر تقرير خيالي أن الشكاوى انخفضت 30٪ بعد إعادة تصميم خدمة. يغطي الرقم الشكاوى الإلكترونية فقط، بينما سُجلت الشكاوى الهاتفية بطريقة مختلفة. يصف التقرير التغيير بأنه مشجع لكنه يقول إن الدليل غير حاسم بعد." },
  102: { kind: "interaction", title: "Decide through counterfactuals", titleArabic: "قرّر من خلال الافتراضات المضادة للواقع", objective: "Use mixed conditionals to explore a difficult decision and its present consequences.", objectiveArabic: "استخدم الشرط المختلط لاستكشاف قرار صعب وعواقبه الحالية.", stage: "real-context", semantic: "activity", minutes: 18, interactionTurns: [{ id: "case", speaker: "Friend", text: "We accepted the contract last year, but the current terms are now hurting the team.", textArabic: "قبلنا العقد العام الماضي، لكن الشروط الحالية تضر الفريق الآن.", purpose: "Present a past decision with a present effect." }, { id: "you", speaker: "You", text: "If we had checked …, we would not now be … . Given the situation, I would … .", textArabic: "لو تحققنا من…، لما كنا الآن… . وبالنظر إلى الوضع، سأ… .", purpose: "Use a mixed conditional and decide." }] },
  103: { kind: "writing", title: "Design public space", titleArabic: "صمّم مساحة عامة", objective: "Write a formal proposal that turns public needs into priorities, actions, and trade-offs.", objectiveArabic: "اكتب اقتراحاً رسمياً يحوّل احتياجات الجمهور إلى أولويات وإجراءات ومفاضلات.", stage: "real-context", semantic: "activity", minutes: 23, prompt: "Write 190–230 words proposing one redesign for a public space. Use formal proposal language, name two trade-offs, and state how success would be reviewed.", promptArabic: "اكتب 190–230 كلمة تقترح إعادة تصميم لمساحة عامة. استخدم لغة اقتراح رسمية، واذكر مفاضلتين، وحدد كيفية مراجعة النجاح." },
  104: { kind: "speaking", title: "Make sure every voice is heard", titleArabic: "تأكد من سماع كل صوت", objective: "Use cleft sentences to emphasise overlooked evidence or stakeholders in a public statement.", objectiveArabic: "استخدم جمل التركيز لإبراز دليل أو أصحاب مصلحة تم تجاهلهم في بيان عام.", stage: "real-context", semantic: "activity", minutes: 16, speakingLines: [{ id: "brief", speaker: "Facilitator", text: "The consultation was large, but people with caring responsibilities rarely attended.", textArabic: "كانت المشاورة واسعة، لكن الأشخاص ذوي مسؤوليات الرعاية نادراً ما حضروا.", pronunciationHint: "Emphasise the missing group or evidence." }, { id: "you", speaker: "You", text: "What the consultation has not shown is … . It is … who need … .", textArabic: "ما لم تظهره المشاورة هو… . إن … هم الذين يحتاجون إلى… .", pronunciationHint: "Use the cleft structure to focus attention." }] },
  105: { kind: "assessment", title: "Make the case for change", titleArabic: "قدّم حجة للتغيير", objective: "Integrate evidence, concession, refutation, and a qualified recommendation in a final case for change.", objectiveArabic: "ادمج الدليل والتنازل والرد والتوصية المقيدة في حجة نهائية للتغيير.", stage: "assessment", semantic: "assessment", minutes: 28, prompt: "Write 240–280 words to a fictional public committee arguing for or against one reform. Use two evidence points, one concession, one refutation, and a qualified recommendation with a review measure.", promptArabic: "اكتب 240–280 كلمة إلى لجنة عامة خيالية تجادل فيها مع إصلاح واحد أو ضده. استخدم دليلين وتنازلاً ورداً وتوصية مقيدة مع مقياس للمراجعة." },
};

const check = (n: number): NonNullable<LessonActivity["retrievalCheck"]> => ({ prompt: `Retrieve one useful distinction from Lesson ${n}.`, promptArabic: `استرجع تمييزاً مفيداً واحداً من الدرس ${n}.`, expectedEvidence: "A concise response connected to the primary objective.", expectedEvidenceArabic: "إجابة مختصرة مرتبطة بالهدف الأساسي." });

export const B2_MODULE_7_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([key, spec]) => { const lesson = Number(key); const activity: LessonActivity = { id: `b2-m7-${lesson}`, kind: spec.kind, title: spec.title, titleArabic: spec.titleArabic, objective: spec.objective, objectiveArabic: spec.objectiveArabic, stage: spec.stage, estimatedMinutes: spec.minutes, semantic: spec.semantic, progressiveSupports: spec.kind === "listening" ? ["transcript", "worked-example"] : ["worked-example", "word-support"], retrievalCheck: check(lesson), ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}), ...(spec.readingText ? { readingText: spec.readingText, readingTextArabic: spec.readingTextArabic } : {}), ...(spec.speakingLines ? { speakingLines: spec.speakingLines } : {}), ...(spec.interactionTurns ? { interactionTurns: spec.interactionTurns } : {}), ...(spec.sentencePatterns ? { sentencePatterns: spec.sentencePatterns } : {}) }; return [lesson, [activity]]; })) as Record<number, LessonActivity[]>;
