import type { LessonActivity, LessonProgressionStage, LessonType } from "./types";

type Spec = { kind: LessonType; title: string; titleArabic: string; objective: string; objectiveArabic: string; stage: LessonProgressionStage; semantic: "objective" | "example" | "tip" | "common-mistake" | "vocabulary" | "grammar" | "activity" | "retrieval" | "assessment"; minutes: number; prompt?: string; promptArabic?: string; readingText?: string; readingTextArabic?: string; speakingLines?: LessonActivity["speakingLines"]; interactionTurns?: LessonActivity["interactionTurns"]; sentencePatterns?: string[] };

const specs: Record<number, Spec> = {
76: { kind: "standard", title: "Make responsibility visible", titleArabic: "اجعل المسؤولية واضحة", objective: "Use passive reporting and impersonal structures to identify institutional responsibility and propose a remedy.", objectiveArabic: "استخدم التقارير بالمبني للمجهول والتراكيب غير الشخصية لتحديد مسؤولية المؤسسة واقتراح علاج.", stage: "guided-practice", semantic: "grammar", minutes: 15, sentencePatterns: ["It was reported that …", "Responsibility should be assigned to …", "The procedure is expected to be reviewed by …"] },
77: { kind: "reading", title: "Read the story behind a statistic", titleArabic: "اقرأ القصة وراء الإحصائية", objective: "Evaluate what a headline statistic shows, limits, and leaves uncertain.", objectiveArabic: "قيّم ما تظهره الإحصائية الرئيسية وما تحدّه وما تتركه غير محسوم.", stage: "explanation", semantic: "example", minutes: 19, readingText: "A fictional report says library visits rose by 18% after a late-opening pilot. The figure covers six branches and compares one season with an unusually quiet previous season. Visits by older residents fell slightly.", readingTextArabic: "يذكر تقرير خيالي أن زيارات المكتبات ارتفعت 18٪ بعد تجربة فتح مسائي. يغطي الرقم ستة فروع ويقارن موسماً بموسم سابق هادئ، كما انخفضت زيارات كبار السن قليلاً." },
78: { kind: "interaction", title: "Choose under uncertainty", titleArabic: "اختر في ظل عدم اليقين", objective: "State and justify an ethical choice while anticipating a plausible consequence.", objectiveArabic: "عبّر عن اختيار أخلاقي وعلّله مع توقع نتيجة محتملة.", stage: "real-context", semantic: "activity", minutes: 16, interactionTurns: [{ id: "case", speaker: "Chair", text: "The emergency fund can support either the youth centre or the transport link this year.", textArabic: "يمكن للصندوق الطارئ دعم مركز الشباب أو وصلة النقل هذا العام.", purpose: "Present a constrained choice." }, { id: "you", speaker: "You", text: "If we prioritised …, we would …, but we might also … . On balance, I would … .", textArabic: "إذا أعطينا الأولوية لـ… فسوف…، لكن قد… أيضاً. وبناءً على ذلك سأ… .", purpose: "Justify a conditional choice." }] },
79: { kind: "writing", title: "Design an accessible public space", titleArabic: "صمّم مساحة عامة متاحة", objective: "Write a concise formal proposal balancing access, inclusion, and a budget constraint.", objectiveArabic: "اكتب اقتراحاً رسمياً موجزاً يوازن بين الوصول والشمول وقيد الميزانية.", stage: "real-context", semantic: "activity", minutes: 22, prompt: "Write 180–220 words proposing two design changes for a small public square. Use nominalisation, acknowledge a budget limit, and recommend one priority.", promptArabic: "اكتب 180–220 كلمة تقترح تغييرين لساحة عامة صغيرة. استخدم تحويل الأفعال إلى أسماء، واعترف بقيد الميزانية، وأوصِ بأولوية واحدة." },
80: { kind: "speaking", title: "Make a missing voice heard", titleArabic: "اجعل صوتاً غائباً مسموعاً", objective: "Use cleft sentences to emphasise whose experience is missing from a local decision.", objectiveArabic: "استخدم جمل التركيز لإبراز تجربة الغائبين عن قرار محلي.", stage: "real-context", semantic: "activity", minutes: 16, speakingLines: [{ id: "brief", speaker: "Facilitator", text: "The consultation received many responses, but evening workers and carers were rarely present.", textArabic: "تلقت المشاورة ردوداً كثيرة، لكن العاملين مساءً ومقدمي الرعاية نادراً ما حضروا.", pronunciationHint: "Notice who is missing." }, { id: "you", speaker: "You", text: "What the consultation has not shown is … . It is evening workers who … .", textArabic: "ما لم تظهره المشاورة هو… . إن العاملين مساءً هم الذين… .", pronunciationHint: "Emphasise the missing evidence, then propose access." }] },
81: { kind: "writing", title: "Build a case for change", titleArabic: "ابنِ حجة للتغيير", objective: "Write an evidence-based reform proposal that anticipates and refutes one objection.", objectiveArabic: "اكتب اقتراح إصلاح قائم على الدليل يتوقع اعتراضاً ويرد عليه.", stage: "assessment", semantic: "assessment", minutes: 24, prompt: "Write 220–260 words recommending one reform to a fictional public service. Use two evidence points, one anticipated objection, a rebuttal, and a review measure.", promptArabic: "اكتب 220–260 كلمة توصي بإصلاح واحد لخدمة عامة خيالية. استخدم دليلين واعتراضاً متوقعاً ورداً عليه ومقياس مراجعة." },
82: { kind: "listening", title: "Listen for calibrated risk", titleArabic: "استمع إلى المخاطر بدرجات دقيقة", objective: "Distinguish likely, possible, and unsupported claims in a risk briefing.", objectiveArabic: "ميّز بين الادعاءات المرجحة والممكنة وغير المدعومة في إحاطة عن المخاطر.", stage: "explanation", semantic: "common-mistake", minutes: 15, speakingLines: [{ id: "briefing", speaker: "Analyst", text: "The change is likely to reduce delays, although the evidence is limited. A cost increase is possible, but the claim that it will bankrupt the service is not supported by the pilot.", textArabic: "من المرجح أن يقلل التغيير التأخيرات، رغم أن الدليل محدود. قد ترتفع التكلفة، لكن الادعاء بأنه سيفلس الخدمة لا تدعمه التجربة.", pronunciationHint: "Listen for likely, possible, and not supported." }] },
83: { kind: "reading", title: "Decide whom to trust", titleArabic: "قرر من تثق به", objective: "Evaluate an expertise claim by separating reported views, evidence, and stance.", objectiveArabic: "قيّم ادعاء الخبرة بالفصل بين الآراء المنقولة والدليل والموقف.", stage: "explanation", semantic: "example", minutes: 19, readingText: "A fictional article quotes a university researcher, a campaign group, and a service manager about a housing pilot. The researcher reports a small study, the group argues from three cases, and the manager acknowledges that the data cannot yet show long-term effects.", readingTextArabic: "يقتبس مقال خيالي باحثاً جامعياً ومجموعة حملات ومدير خدمة حول تجربة إسكان. ينقل الباحث دراسة صغيرة، وتستند المجموعة إلى ثلاث حالات، ويقر المدير بأن البيانات لا تظهر الآثار طويلة المدى بعد." },
84: { kind: "interaction", title: "Negotiate a fair compromise", titleArabic: "تفاوض على تسوية عادلة", objective: "Use conditional language and diplomatic disagreement to create a reviewable compromise.", objectiveArabic: "استخدم لغة شرطية واختلافاً دبلوماسياً لإنشاء تسوية قابلة للمراجعة.", stage: "real-context", semantic: "activity", minutes: 17, interactionTurns: [{ id: "proposal", speaker: "Resident", text: "The whole street should close to cars immediately.", textArabic: "ينبغي إغلاق الشارع كله أمام السيارات فوراً.", purpose: "Make a strong proposal." }, { id: "you", speaker: "You", text: "I can see the benefit. If we began with … and reviewed …, we could … without … .", textArabic: "أفهم الفائدة. إذا بدأنا بـ… وراجعنا…، فيمكننا… دون… .", purpose: "Disagree diplomatically and propose a condition." }] },
85: { kind: "standard", title: "Connect cause to consequence", titleArabic: "اربط السبب بالنتيجة", objective: "Use participle clauses to explain how an attention policy produces consequences.", objectiveArabic: "استخدم جمل اسم الفاعل أو اسم المفعول لشرح كيف تنتج سياسة الانتباه عواقب.", stage: "guided-practice", semantic: "grammar", minutes: 14, sentencePatterns: ["Designed to keep users scrolling, the feature …", "Having reduced interruptions, the service …", "Encouraged by the reward, users …"] },
86: { kind: "reading", title: "Ask: progress for whom?", titleArabic: "اسأل: التقدم لمن؟", objective: "Evaluate who benefits from an innovation and qualify the comparison with concession.", objectiveArabic: "قيّم من يستفيد من ابتكار وقيّد المقارنة باستخدام التنازل.", stage: "explanation", semantic: "example", minutes: 19, readingText: "A fictional mobility app makes journeys faster for people with reliable smartphones, while users with older devices face sign-in failures. The new route is more efficient overall, although the improvement is uneven across neighbourhoods.", readingTextArabic: "يجعل تطبيق تنقل خيالي الرحلات أسرع لمن يملكون هواتف موثوقة، بينما يواجه مستخدمو الأجهزة القديمة فشل تسجيل الدخول. المسار الجديد أكثر كفاءة عموماً، رغم أن التحسن غير متساوٍ بين الأحياء." },
87: { kind: "listening", title: "Translate with care", titleArabic: "ترجم بعناية", objective: "Identify respectful qualification when a speaker discusses cultural identity and translation choices.", objectiveArabic: "حدد التحفظ المحترم عندما يتحدث متحدث عن الهوية الثقافية واختيارات الترجمة.", stage: "explanation", semantic: "common-mistake", minutes: 16, speakingLines: [{ id: "translator", speaker: "Translator", text: "Some readers may recognise the celebration, but that does not mean one translation represents every community. I would preserve the humour while explaining the local reference in a note.", textArabic: "قد يتعرف بعض القراء على الاحتفال، لكن هذا لا يعني أن ترجمة واحدة تمثل كل المجتمعات. سأحافظ على الفكاهة مع شرح المرجع المحلي في ملاحظة.", pronunciationHint: "Listen for may, does not mean, and I would." }] },
88: { kind: "writing", title: "Evaluate the business of belonging", titleArabic: "قيّم تجارة الانتماء", objective: "Recommend a community-building strategy while evaluating the risk of tokenism.", objectiveArabic: "أوصِ باستراتيجية لبناء المجتمع مع تقييم خطر الاستعراض.", stage: "real-context", semantic: "activity", minutes: 22, prompt: "Write 180–220 words for a fictional clothing brand. Compare two community-building strategies, recommend one, and acknowledge one risk and one measure of trust.", promptArabic: "اكتب 180–220 كلمة لعلامة ملابس خيالية. قارن استراتيجيتين لبناء المجتمع، وأوصِ بإحداهما، واعترف بخطر ومقياس للثقة." },
89: { kind: "assessment", title: "Make a strong case", titleArabic: "ابنِ حجة قوية", objective: "Construct a persuasive public-policy argument with evidence, rebuttal, and a balanced recommendation.", objectiveArabic: "ابنِ حجة مقنعة في سياسة عامة بدليل ورد على اعتراض وتوصية متوازنة.", stage: "assessment", semantic: "assessment", minutes: 26, prompt: "Write 240–280 words to a fictional local council about a four-day workweek pilot. Evaluate evidence, rebut one objection, and recommend whether the pilot should expand.", promptArabic: "اكتب 240–280 كلمة إلى مجلس محلي خيالي حول تجربة أسبوع العمل من أربعة أيام. قيّم الدليل، ورد على اعتراض، وأوصِ بالتوسيع أو عدمه." },
90: { kind: "assessment", title: "When technology decides", titleArabic: "حين تقرر التكنولوجيا", objective: "Evaluate evidence of algorithmic bias and propose responsible safeguards using ethical framing.", objectiveArabic: "قيّم دليل تحيز خوارزمي واقترح ضوابط مسؤولة باستخدام إطار أخلاقي.", stage: "assessment", semantic: "assessment", minutes: 29, prompt: "Write 260–320 words to a fictional council and newspaper reader. Evaluate a benefits-allocation AI pilot, argue for or against deployment, and propose safeguards balancing fairness and practical consequences.", promptArabic: "اكتب 260–320 كلمة إلى مجلس خيالي وقرّاء صحيفة. قيّم تجربة ذكاء اصطناعي لتوزيع المساعدات، وجادل مع أو ضد النشر، واقترح ضوابط توازن بين العدالة والعواقب العملية." },
};

const check = (n: number): NonNullable<LessonActivity["retrievalCheck"]> => ({ prompt: `Retrieve one useful distinction from Lesson ${n}.`, promptArabic: `استرجع تمييزاً مفيداً واحداً من الدرس ${n}.`, expectedEvidence: "A concise response connected to the primary objective.", expectedEvidenceArabic: "إجابة مختصرة مرتبطة بالهدف الأساسي." });

export const B2_MODULE_6_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([key, spec]) => { const lesson = Number(key); const activity: LessonActivity = { id: `b2-m6-${lesson}`, kind: spec.kind, title: spec.title, titleArabic: spec.titleArabic, objective: spec.objective, objectiveArabic: spec.objectiveArabic, stage: spec.stage, estimatedMinutes: spec.minutes, semantic: spec.semantic, progressiveSupports: spec.kind === "listening" ? ["transcript", "worked-example"] : ["worked-example", "word-support"], retrievalCheck: check(lesson), ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}), ...(spec.readingText ? { readingText: spec.readingText, readingTextArabic: spec.readingTextArabic } : {}), ...(spec.speakingLines ? { speakingLines: spec.speakingLines } : {}), ...(spec.interactionTurns ? { interactionTurns: spec.interactionTurns } : {}), ...(spec.sentencePatterns ? { sentencePatterns: spec.sentencePatterns } : {}) }; return [lesson, [activity]]; })) as Record<number, LessonActivity[]>;
