import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"],
  density: LessonExperience["density"],
  rationale: string,
  stages: LessonExperience["selectedStages"],
  whatItIs: string,
  whatToDo: string,
  whatMatters: string,
  whatNext: string,
  progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({
  archetype,
  density,
  archetypeRationale: rationale,
  selectedStages: stages,
  firstView: { whatItIs, whatToDo, whatMatters, whatNext },
  progressiveSupports,
});

export const b2Module10Experiences: Record<number, LessonExperience> = {
  136: experience("reading", "normal", "A close reading introduces the module through a concrete public-facing argument rather than a vocabulary list.", ["orientation", "encounter", "notice", "evidence"], "A critical reading about community branding.", "Read once for the claim, then return to the questions about benefit, motive, and publicity.", "A responsible judgement separates social value from promotional language.", "Use the same test when you write your own public case.", ["word-support", "extended-rationale"]),
  137: experience("writing", "deep", "The learner now turns evaluative reading into a structured civic argument with a real reader and explicit counterargument work.", ["orientation", "supported-practice", "meaningful-use", "evidence"], "A guided policy argument for a city council.", "Plan two evidence points, anticipate one objection, rebut it, and qualify your recommendation.", "Balance is not indecision: it is a justified position that shows what the evidence can support.", "Test the same reasoning in a dialogue about automated decisions.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  138: experience("interaction", "normal", "A short ethical exchange gives the learner a spoken route into algorithmic bias without adding a second written essay.", ["orientation", "encounter", "meaningful-use"], "A conversation about an automated decision.", "Take the engineer's observation, name the risk, and propose one safeguard aloud or in notes.", "Use relative clauses to connect evidence to consequences clearly.", "Read a review that weighs evidence and recommendation.", ["worked-example", "tip"]),
  139: experience("reading", "light", "This reading deliberately asks for a mental verdict, giving retrieval space after two demanding production tasks.", ["orientation", "encounter", "notice", "retrieval"], "A review that recommends change cautiously.", "Mark the praise, limitation, acknowledgement, and recommendation before deciding whether the review persuades you.", "Qualified recommendations often become stronger because they state their limits.", "Prepare to disagree with a view without misrepresenting it.", ["word-support", "extended-rationale"]),
  140: experience("speaking", "normal", "A fairness-first speaking task develops respectful disagreement through reformulation rather than debate performance.", ["orientation", "encounter", "meaningful-use"], "A respectful disagreement with a partner's policy view.", "Restate the partner's point fairly, agree with its strongest part, then challenge it with evidence.", "A good challenge preserves the other person's meaning before it adds pressure.", "Predict consequences in a written policy response.", ["worked-example", "tip"]),
  141: experience("writing", "deep", "The second writing task moves from argument structure to consequence and uncertainty, increasing independence without becoming an essay bundle.", ["orientation", "supported-practice", "meaningful-use", "evidence"], "A transport proposal that needs modification.", "Recommend a change, predict short- and long-term outcomes, and hedge claims where evidence is limited.", "Hedging tells a reader how strongly the evidence supports a prediction.", "Carry the trade-off into a workplace negotiation.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  142: experience("interaction", "normal", "A workplace negotiation makes trade-offs immediate and human after the abstract policy writing.", ["orientation", "encounter", "meaningful-use"], "A planning conversation about burnout and meetings.", "Identify the inclusion-pressure trade-off and propose a shorter meeting plus a written update.", "A workable solution protects the goal that the first proposal might accidentally damage.", "Apply conditional reasoning to a place-development decision.", ["worked-example", "tip"]),
  143: experience("real-world", "normal", "The real-world route asks the learner to mediate between heritage, housing, and identity through conditional consequences.", ["orientation", "encounter", "meaningful-use", "evidence"], "A development decision about a historic market.", "Offer a compromise, then state what could happen if the safeguard is rejected.", "Conditional language makes the cost of a decision visible without pretending certainty.", "Defend a position for a public reader.", ["worked-example", "extended-rationale"]),
  144: experience("writing", "deep", "This public-facing writing task consolidates the module's argument skills through concession, cohesion, and recommendation.", ["orientation", "supported-practice", "meaningful-use", "evidence"], "A newspaper response on short-term rentals.", "Evaluate both views, concede one valid point, and recommend a policy with connected reasoning.", "Concession builds credibility when it leads to a clearer conclusion.", "Listen for how contested information should be verified.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  145: experience("listening", "normal", "The audio-first briefing creates a different mode of evidence evaluation and keeps the transcript subordinate to listening.", ["orientation", "encounter", "notice", "evidence"], "A news briefing with competing claims.", "Listen for each source's position, then reveal the transcript only to verify a detail or phrase.", "Do not turn an unverified claim into a fact simply because it is repeated.", "Write about the trade-offs behind everyday convenience.", ["transcript", "tip", "extended-rationale"]),
  146: experience("writing", "deep", "A consumer-facing proposal transfers the evidence habits into a familiar choice with visible costs and alternatives.", ["orientation", "supported-practice", "meaningful-use", "evidence"], "A balanced consumer magazine proposal.", "Compare benefits and costs, make one concession, and offer an alternative that reduces the main harm.", "A practical alternative is more useful than a criticism with no next step.", "Speak about what makes a workplace worth joining.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  147: experience("speaking", "normal", "The workplace judgement task asks for informed inference and obligation language in a compact spoken exchange.", ["orientation", "encounter", "meaningful-use"], "A conversation about workplace culture.", "Separate an attractive benefit from a warning sign, then state what the employer ought to publish or explain.", "Use modals to distinguish duty, criticism, and cautious inference.", "Read what happens when a system fails.", ["worked-example", "tip"]),
  148: experience("reading", "normal", "A systems-failure report provides authentic passive reporting for responsibility and remedy analysis.", ["orientation", "encounter", "notice", "evidence"], "A report on delayed applications and institutional responsibility.", "Trace what was found, reported, stated, and recommended; then judge which remedy matters most.", "Passive reporting can foreground evidence while leaving responsibility open for investigation.", "Find the story behind a headline statistic.", ["word-support", "extended-rationale"]),
  149: experience("reading", "light", "A compact statistics reading retrieves the module's evidence discipline before the final assessment.", ["orientation", "encounter", "retrieval", "next-bridge"], "A headline claim tested against its underlying survey.", "Compare the headline with the method, then rewrite the claim with appropriate caution.", "A statistic is only as strong as the question, sample, and comparison behind it.", "Use the full judgement toolkit in the final decision.", ["word-support", "extended-rationale"]),
  150: experience("assessment", "deep", "The module closes with an ethical decision that requires transfer across evidence, counterargument, conditionals, safeguards, and consequence.", ["orientation", "meaningful-use", "evidence", "next-bridge"], "A cumulative ethical decision for an expert panel.", "Evaluate competing duties, decide what should happen now, use counterfactual reasoning, and propose safeguards.", "A strong B2 response is specific, fair to opposing evidence, and proportionate to uncertainty.", "Review the feedback, record one transferable strength, and prepare for the next level challenge.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default b2Module10Experiences;
