import { B2_LESSONS, getB2Lesson } from "./b2";
import type { QuizQuestion } from "./quiz";

function rotate<T>(items: T[], offset: number) { const start = items.length ? offset % items.length : 0; return [...items.slice(start), ...items.slice(0, start)]; }
function spellingChoices(target: string) { const word = target.toLowerCase(); const removed = word.length > 8 ? `${word.slice(0, 4)}${word.slice(5)}` : `${word}e`; const swapped = word.length > 6 ? `${word.slice(0, 2)}${word.slice(3, 4)}${word.slice(2, 3)}${word.slice(4)}` : `${word}s`; return [word, removed, swapped, `${word}e`].filter((choice, index, values) => values.indexOf(choice) === index).slice(0, 4); }
function meaningQuestion(lessonNumber: number, wordIndex: number): QuizQuestion { const lesson = getB2Lesson(lessonNumber)!; const target = lesson.words[wordIndex % lesson.words.length]; const alternatives = rotate(lesson.words.filter((word) => word.id !== target.id), wordIndex + 3).slice(0, 3).map((word) => word.word); return { id: `b2-l${lessonNumber}-meaning-${target.id}`, type: "meaning", prompt: `Which B2 word or expression most precisely means “${target.arabic}”?`, promptArabic: `أي كلمة أو عبارة من مستوى B2 تعبّر بدقة عن «${target.arabic}»؟`, choices: rotate([target.word, ...alternatives], wordIndex), answer: target.word, reviewItemKey: target.id, reviewItemType: "vocabulary" }; }
function spellingQuestion(lessonNumber: number, wordIndex: number): QuizQuestion { const lesson = getB2Lesson(lessonNumber)!; const target = lesson.words[wordIndex % lesson.words.length]; return { id: `b2-l${lessonNumber}-spelling-${target.id}`, type: "spelling", prompt: `Choose the accurate spelling for this B2 item: ${target.arabic}`, promptArabic: `اختر التهجئة الدقيقة لهذه العبارة من مستوى B2: ${target.arabic}`, choices: rotate(spellingChoices(target.word), wordIndex), answer: target.word.toLowerCase(), reviewItemKey: target.id, reviewItemType: "vocabulary" }; }
function grammarQuestion(lessonNumber: number): QuizQuestion { const lesson = getB2Lesson(lessonNumber)!; const alternatives = rotate(B2_LESSONS.filter((item) => item.lessonNumber !== lessonNumber), lessonNumber).slice(0, 3).map((item) => item.grammar.topic); return { id: `b2-l${lessonNumber}-grammar`, type: "grammar", prompt: `Which grammar or discourse focus helps qualify this B2 claim? “${lesson.grammar.examples[0].en}”`, promptArabic: `أي قاعدة أو أداة ربط تساعدك على تأهيل هذا الادعاء بدقة؟ «${lesson.grammar.examples[0].ar}»`, choices: rotate([lesson.grammar.topic, ...alternatives], lessonNumber), answer: lesson.grammar.topic, reviewItemKey: lesson.grammar.id, reviewItemType: "grammar" }; }
export function buildB2LessonQuiz(lessonNumber: number): QuizQuestion[] { if (!getB2Lesson(lessonNumber)) return []; return [0, 3, 6, 9].map((index) => meaningQuestion(lessonNumber, index)).concat([spellingQuestion(lessonNumber, 1), spellingQuestion(lessonNumber, 8), grammarQuestion(lessonNumber)]); }
export function buildB2ModuleTest(moduleNumber: number): QuizQuestion[] { return B2_LESSONS.filter((lesson) => lesson.moduleNumber === moduleNumber).flatMap((lesson) => [meaningQuestion(lesson.lessonNumber, 1), meaningQuestion(lesson.lessonNumber, 7), spellingQuestion(lesson.lessonNumber, 10), grammarQuestion(lesson.lessonNumber)]); }
