import rawDraft from "./b2-draft.json";
import type { CourseDefinition, GrammarTopic, LessonDefinition, LessonExperience, LessonStep, VocabularyItem } from "./types";
import { enrichLesson } from "./activity-plan";
import { buildModuleDefinitions } from "./module-definitions";
import { createLessonExperience } from "./lesson-experience";
import { B2_MODULE_1_ACTIVITIES } from "./b2-module-1-authored-activities";
import { B2_MODULE_2_ACTIVITIES } from "./b2-module-2-authored-activities";
import { B2_MODULE_3_ACTIVITIES } from "./b2-module-3-authored-activities";
import { B2_MODULE_4_ACTIVITIES } from "./b2-module-4-authored-activities";
import { B2_MODULE_5_ACTIVITIES } from "./b2-module-5-authored-activities";
import { B2_MODULE_6_ACTIVITIES } from "./b2-module-6-authored-activities";
import { B2_MODULE_6_EXPERIENCES } from "./b2-module-6-experiences";
import { B2_MODULE_7_ACTIVITIES } from "./b2-module-7-authored-activities";
import { B2_MODULE_7_EXPERIENCES } from "./b2-module-7-experiences";
import { B2_MODULE_8_ACTIVITIES } from "./b2-module-8-authored-activities";
import { B2_MODULE_8_EXPERIENCES } from "./b2-module-8-experiences";
import { B2_MODULE_9_ACTIVITIES } from "./b2-module-9-authored-activities";
import { B2_MODULE_9_EXPERIENCES } from "./b2-module-9-experiences";

type DraftVocabulary = { word: string; arabic: string; partOfSpeech: string; definition: string; exampleEN: string; exampleAR: string };
type DraftLesson = {
  lessonNumber: number; title: string; titleArabic: string;
  outcome: { canDo: string; canDoArabic: string; scenario: string; scenarioArabic: string };
  retrieval: Array<{ language: string; prompt: string; purpose: string }>;
  network: { theme: string; themeArabic: string; anchor: string; relatedWords: string[]; chunks: string[]; collocations: string[]; register: "neutral" | "informal" | "formal" | "mixed"; priorLevelLinks: string[]; learningNote: string; learningNoteArabic: string; wordFamilies: Array<{ headword: string; forms: string[]; note: string; noteArabic: string }> };
  vocabulary: DraftVocabulary[];
  grammar: { topic: string; arabicName: string; concept: string; arabicComparison: string; structure: string; commonError: string; exampleEN: string; exampleAR: string };
  readingBrief: string; writingPrompt: string;
};

const STEPS: LessonStep[] = [
  { id: "start", title: "Start here", titleArabic: "ابدأ هنا", purpose: "Take a defensible position and reactivate B1 language for the issue.", estimatedMinutes: 7 },
  { id: "explore", title: "Explore", titleArabic: "استكشف", purpose: "Study precise B2 chunks, collocations, word families, register, and stance.", estimatedMinutes: 14 },
  { id: "notice", title: "Notice", titleArabic: "لاحظ", purpose: "Trace how grammar, evidence, and discourse choices shape a nuanced argument.", estimatedMinutes: 14 },
  { id: "build", title: "Build", titleArabic: "ابنِ", purpose: "Construct a coherent evaluation, proposal, rebuttal, or formal response.", estimatedMinutes: 17 },
  { id: "respond", title: "Respond", titleArabic: "استجب", purpose: "Interpret an original source critically and respond for a defined audience and purpose.", estimatedMinutes: 24 },
  { id: "prove", title: "Prove it", titleArabic: "أثبت إتقانك", purpose: "Transfer the language to a new task, justify choices, receive feedback, and schedule review.", estimatedMinutes: 18 },
];

function asVocabularyItem(item: DraftVocabulary, lessonNumber: number, index: number): VocabularyItem {
  return { id: `b2-${lessonNumber}-${index + 1}`, word: item.word, arabic: item.arabic, ipa: "", phoneticRespelling: item.word, partOfSpeech: item.partOfSpeech, definition: item.definition, exampleEN: item.exampleEN, exampleAR: item.exampleAR };
}

function asGrammarTopic(lesson: DraftLesson): GrammarTopic {
  const grammar = lesson.grammar;
  return {
    id: `b2-grammar-${lesson.lessonNumber}`, lessonNumber: lesson.lessonNumber, topic: grammar.topic, arabicName: grammar.arabicName,
    concept: grammar.concept, represents: "Use this B2 pattern to qualify claims, connect evidence, and make your position precise.", arabicComparison: grammar.arabicComparison,
    useWhen: ["you need to weigh evidence or acknowledge a counterpoint", "the B2 task calls for a controlled formal, neutral, or persuasive register"],
    doNotUseWhen: ["a shorter B1 structure already conveys the exact intended meaning without losing nuance"],
    commonMistakes: [{ wrong: grammar.commonError, correct: grammar.structure, explanation: "Check how form, register, and connection between ideas affect the strength of the claim." }],
    structure: { positive: grammar.structure, negative: `Check the limiting, concessive, or negative form in: ${grammar.exampleEN}`, question: `Ask an AI follow-up question about ${grammar.topic}` },
    examples: [{ en: grammar.exampleEN, ar: grammar.exampleAR }], practice: [],
  };
}

const B2_MODULE_1_EXPERIENCES: Record<number, LessonExperience> = {
  1: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Learners need source discipline before forming a view under pressure.", selectedStages: ["orientation", "encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A source-reading investigation.", whatToDo: "Separate fact, attribution, and uncertainty.", whatMatters: "Careful claims protect trust.", whatNext: "Weigh a service trade-off." }, progressiveSupports: ["word-support", "tip"] }),
  2: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The convenience debate calls for a measured written judgement.", selectedStages: ["orientation", "notice", "meaningful-use", "evidence"], firstView: { whatItIs: "A balanced service evaluation.", whatToDo: "Write a qualified recommendation.", whatMatters: "A benefit does not erase a cost.", whatNext: "Test workplace promises." }, progressiveSupports: ["worked-example", "word-support"] }),
  3: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Evidence-seeking questions are best rehearsed as a realistic exchange.", selectedStages: ["orientation", "encounter", "supported-practice", "next-bridge"], firstView: { whatItIs: "A workplace-claim interview.", whatToDo: "Ask one specific evidence question.", whatMatters: "Polite questions can reveal substance.", whatNext: "Trace a system failure." }, progressiveSupports: ["worked-example", "tip"] }),
  4: createLessonExperience({ archetype: "notice", density: "normal", archetypeRationale: "Causal precision is the focus, not a full production task.", selectedStages: ["encounter", "notice", "supported-practice", "next-bridge"], firstView: { whatItIs: "A system-failure trace.", whatToDo: "Follow the causal chain.", whatMatters: "Attribute what is known and unknown.", whatNext: "Question a statistic." }, progressiveSupports: ["word-support", "tip"] }),
  5: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "This is a focused evidence habit that prepares later argument.", selectedStages: ["orientation", "notice", "retrieval"], firstView: { whatItIs: "A statistic check.", whatToDo: "Ask three limiting questions.", whatMatters: "Numbers need a context.", whatNext: "Present a difficult decision." }, progressiveSupports: ["worked-example", "tip"] }),
  6: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A concise spoken recommendation makes trade-offs audible.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A one-minute decision briefing.", whatToDo: "Name groups, a constraint, and a trade-off.", whatMatters: "A defensible choice is not a perfect choice.", whatNext: "Design public space." }, progressiveSupports: ["worked-example"] }),
  7: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "Public-space priorities require practical negotiation.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A public-design negotiation.", whatToDo: "Offer a phased, conditional priority.", whatMatters: "Access and safety need concrete choices.", whatNext: "Ask who is absent." }, progressiveSupports: ["worked-example", "word-support"] }),
  8: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Representation is best examined in a short consultation source.", selectedStages: ["encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A consultation-source reading.", whatToDo: "Identify represented and missing voices.", whatMatters: "Silence can limit a conclusion.", whatNext: "Build a case for change." }, progressiveSupports: ["word-support"] }),
  9: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The proposal consolidates evidence, rebuttal, and recommendation.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A concise evidence-led proposal.", whatToDo: "Make, test, and qualify a case.", whatMatters: "Acknowledge the strongest objection.", whatNext: "Communicate risk." }, progressiveSupports: ["worked-example", "word-support"] }),
  10: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "Risk language needs a compact precision lesson before transfer.", selectedStages: ["orientation", "notice", "supported-practice"], firstView: { whatItIs: "A calm risk-language focus.", whatToDo: "Separate likelihood, harm, and precaution.", whatMatters: "Accuracy avoids panic and complacency.", whatNext: "Test expert advice." }, progressiveSupports: ["worked-example"] }),
  11: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Respectful challenge is practised best through a bounded exchange.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "An expertise-and-trust exchange.", whatToDo: "Ask about scope and uncertainty.", whatMatters: "Trust includes asking good questions.", whatNext: "Negotiate a compromise." }, progressiveSupports: ["tip", "transcript"] }),
  12: createLessonExperience({ archetype: "interaction", density: "deep", archetypeRationale: "Conditional language serves a concrete negotiation problem.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A fair-compromise negotiation.", whatToDo: "Offer a conditional solution.", whatMatters: "Legitimate interests can be balanced.", whatNext: "Analyse platform attention." }, progressiveSupports: ["worked-example", "tip"] }),
  13: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Platform design needs critical cause-effect reading before policy claims.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "An attention-economy argument.", whatToDo: "Trace cause and identify an assumption.", whatMatters: "Design shapes choices without determining them.", whatNext: "Evaluate who benefits." }, progressiveSupports: ["word-support", "tip"] }),
  14: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Access-focused evaluation requires a sustained response.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "An equitable-access evaluation.", whatToDo: "Compare benefits and barriers.", whatMatters: "Progress may be unevenly shared.", whatNext: "Complete the module checkpoint." }, progressiveSupports: ["worked-example", "word-support"] }),
  15: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint asks learners to transfer the module’s evidence habits.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A B2 informed-judgement checkpoint.", whatToDo: "Write a qualified public recommendation.", whatMatters: "Evidence and uncertainty belong together.", whatNext: "Move into the next B2 module." }, progressiveSupports: ["tip"] }),
};

const B2_MODULE_2_EXPERIENCES: Record<number, LessonExperience> = {
  16: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Belonging claims need evidence-led reading.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A belonging-claim reading.", whatToDo: "Separate claim from evidence.", whatMatters: "Community language can persuade.", whatNext: "Build a strong case." }, progressiveSupports: ["word-support", "tip"] }),
  17: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Policy argument needs a sustained authored response.", selectedStages: ["orientation", "notice", "meaningful-use", "evidence"], firstView: { whatItIs: "An evidence-led policy case.", whatToDo: "Write, limit, and answer a case.", whatMatters: "Strong arguments acknowledge limits.", whatNext: "Audit automated decisions." }, progressiveSupports: ["worked-example", "word-support"] }),
  18: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Algorithmic accountability is practised through questions.", selectedStages: ["orientation", "encounter", "supported-practice", "next-bridge"], firstView: { whatItIs: "An automated-decision audit.", whatToDo: "Ask about oversight and fairness.", whatMatters: "Efficiency needs accountability.", whatNext: "Read a qualified review." }, progressiveSupports: ["worked-example", "tip"] }),
  19: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A review models qualified judgement.", selectedStages: ["encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A changing-minds review.", whatToDo: "Find recommendation and reservations.", whatMatters: "A conclusion may be cautious.", whatNext: "Learn from disagreement." }, progressiveSupports: ["word-support"] }),
  20: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "Fair paraphrase precedes respectful challenge.", selectedStages: ["orientation", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A disagreement skill.", whatToDo: "Paraphrase, then challenge.", whatMatters: "Respect strengthens critique.", whatNext: "Plan a proposal." }, progressiveSupports: ["worked-example"] }),
  21: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Consequences must be planned in a proposal.", selectedStages: ["orientation", "notice", "meaningful-use", "evidence"], firstView: { whatItIs: "A consequence-aware proposal.", whatToDo: "Plan impacts and mitigations.", whatMatters: "Implementation shapes outcomes.", whatNext: "Discuss pressure at work." }, progressiveSupports: ["worked-example", "word-support"] }),
  22: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Workplace pressure benefits from an empathetic exchange.", selectedStages: ["encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A purposeful-work conversation.", whatToDo: "Respond with empathy and options.", whatMatters: "Pressure deserves practical care.", whatNext: "Weigh preservation." }, progressiveSupports: ["tip"] }),
  23: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Urban preservation requires balanced source analysis.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "An urban-change reading.", whatToDo: "Weigh connected priorities.", whatMatters: "No interest is cost-free.", whatNext: "Defend a position." }, progressiveSupports: ["word-support", "tip"] }),
  24: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A nuanced position gains force when voiced.", selectedStages: ["orientation", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A nuanced position briefing.", whatToDo: "Defend and qualify a view.", whatMatters: "Nuance is not indecision.", whatNext: "Test information." }, progressiveSupports: ["worked-example"] }),
  25: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Primary-source checking protects public reasoning.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A source-verification task.", whatToDo: "Trace and correct a claim.", whatMatters: "The source changes the claim.", whatNext: "Price convenience." }, progressiveSupports: ["word-support", "tip"] }),
  26: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "Concession language benefits from focused practice.", selectedStages: ["orientation", "notice", "retrieval"], firstView: { whatItIs: "A convenience trade-off focus.", whatToDo: "Use degree and concession.", whatMatters: "Convenience has conditions.", whatNext: "Evaluate a workplace." }, progressiveSupports: ["worked-example"] }),
  27: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "Workplace evaluation needs measured evidence.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A workplace evaluation.", whatToDo: "Use observable indicators.", whatMatters: "Claims need concrete support.", whatNext: "Respond to a failure." }, progressiveSupports: ["worked-example", "word-support"] }),
  28: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "System-failure language transfers to a public response.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A system-failure response.", whatToDo: "Separate facts, action, and process.", whatMatters: "Accountability needs due process.", whatNext: "Question a statistic." }, progressiveSupports: ["worked-example", "tip"] }),
  29: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "Statistics require contextual critical reading.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A statistic-source analysis.", whatToDo: "Check context and causation.", whatMatters: "Correlation is not proof.", whatNext: "Complete the decision checkpoint." }, progressiveSupports: ["word-support", "tip"] }),
  30: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint combines ethics, evidence, and decision-making.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A difficult B2 decision checkpoint.", whatToDo: "Make a reviewable recommendation.", whatMatters: "Defensible choices name conditions.", whatNext: "Move to the next B2 module." }, progressiveSupports: ["tip"] }),
};

const B2_MODULE_3_EXPERIENCES: Record<number, LessonExperience> = {
  31: createLessonExperience({ archetype: "discover", density: "normal", archetypeRationale: "The module opens by making system pressure visible before asking for judgement.", selectedStages: ["orientation", "encounter", "notice", "next-bridge"], firstView: { whatItIs: "A system-pressure investigation.", whatToDo: "Map the stakeholders and constraints.", whatMatters: "Pressure is shared unevenly.", whatNext: "Trace a claim precisely." }, progressiveSupports: ["word-support", "tip"] }),
  32: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Hedging and attribution are a focused precision tool, not a full production route.", selectedStages: ["encounter", "notice", "supported-practice", "retrieval"], firstView: { whatItIs: "A claim-precision focus.", whatToDo: "Adjust certainty and attribution.", whatMatters: "Careful language protects evidence.", whatNext: "Read a workplace account." }, progressiveSupports: ["worked-example", "tip"] }),
  33: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A compact contrast lesson prepares learners to detect false certainty.", selectedStages: ["orientation", "notice", "retrieval"], firstView: { whatItIs: "A certainty check.", whatToDo: "Spot what a source can and cannot show.", whatMatters: "A limit changes a conclusion.", whatNext: "Question an official response." }, progressiveSupports: ["worked-example"] }),
  34: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Responsible challenge is learned in a bounded meeting exchange.", selectedStages: ["orientation", "encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A professional challenge.", whatToDo: "Ask a precise, fair question.", whatMatters: "Challenge can remain constructive.", whatNext: "Evaluate a policy source." }, progressiveSupports: ["worked-example", "transcript"] }),
  35: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "A dense source gives learners space to track evidence, assumptions, and omitted voices.", selectedStages: ["orientation", "encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A policy-source analysis.", whatToDo: "Separate evidence, assumption, and implication.", whatMatters: "A persuasive source still has limits.", whatNext: "Give a measured briefing." }, progressiveSupports: ["word-support", "tip"] }),
  36: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "The issue calls for a concise spoken recommendation rather than another essay.", selectedStages: ["orientation", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A decision briefing.", whatToDo: "Recommend one proportionate step.", whatMatters: "State the condition as well as the benefit.", whatNext: "Write a response for a public audience." }, progressiveSupports: ["worked-example"] }),
  37: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "The formal response consolidates evidence, concession, and accountable recommendation.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A formal public response.", whatToDo: "Build and qualify a recommendation.", whatMatters: "A defensible proposal names its trade-off.", whatNext: "Test an implementation problem." }, progressiveSupports: ["worked-example", "word-support"] }),
  38: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "A constrained implementation task makes abstract systems language usable.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "An implementation response.", whatToDo: "Prioritise action under constraints.", whatMatters: "A plan needs owners and review points.", whatNext: "Read the effects on people." }, progressiveSupports: ["worked-example", "tip"] }),
  39: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A human-impact account counterbalances the prior systems task.", selectedStages: ["encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "An impact-account reading.", whatToDo: "Trace cause, effect, and perspective.", whatMatters: "Experience can reveal a policy gap.", whatNext: "Mediate between priorities." }, progressiveSupports: ["word-support"] }),
  40: createLessonExperience({ archetype: "integration", density: "deep", archetypeRationale: "This lesson deliberately uses existing language to reconcile competing perspectives.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A perspective-mediation task.", whatToDo: "Represent two interests fairly.", whatMatters: "Fair summary precedes a solution.", whatNext: "Refine a limitation." }, progressiveSupports: ["worked-example", "tip"] }),
  41: createLessonExperience({ archetype: "notice", density: "light", archetypeRationale: "A brief rhetoric focus prevents formulaic overstatement before later transfer.", selectedStages: ["orientation", "notice", "supported-practice"], firstView: { whatItIs: "A rhetoric-and-register focus.", whatToDo: "Replace an inflated claim.", whatMatters: "Strength comes from fit, not exaggeration.", whatNext: "Negotiate an accountable revision." }, progressiveSupports: ["worked-example"] }),
  42: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Negotiation brings the module's evidence habits into a live, responsive exchange.", selectedStages: ["encounter", "supported-practice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "An accountable revision meeting.", whatToDo: "Offer and test a revision.", whatMatters: "Agreement should preserve the concern.", whatNext: "Write a final evaluation." }, progressiveSupports: ["worked-example", "transcript"] }),
  43: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A final evaluation asks for sustained, audience-aware judgement.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A critical evaluation.", whatToDo: "Judge a proposal against evidence.", whatMatters: "A conclusion should remain reviewable.", whatNext: "Retrieve the module's decision language." }, progressiveSupports: ["worked-example", "word-support"] }),
  44: createLessonExperience({ archetype: "review", density: "normal", archetypeRationale: "Retrieval is purposeful here: it readies learners to select—not repeat—language in assessment.", selectedStages: ["retrieval", "supported-practice", "next-bridge"], firstView: { whatItIs: "A selective retrieval review.", whatToDo: "Choose the right evidence phrase for a new case.", whatMatters: "Recall should change your next decision.", whatNext: "Complete the module checkpoint." }, progressiveSupports: ["tip"] }),
  45: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The checkpoint transfers source discipline, negotiation, and qualified recommendation to an unfamiliar case.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A B2 systems-and-judgement checkpoint.", whatToDo: "Make an evidence-led recommendation.", whatMatters: "Explain limits as well as action.", whatNext: "Move to the next B2 module." }, progressiveSupports: ["tip"] }),
};

const B2_MODULE_4_EXPERIENCES: Record<number, LessonExperience> = {
  46: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "A bounded verb-pattern and emphasis contrast gives learners precision before the module’s public decisions.", selectedStages: ["encounter", "notice", "supported-practice"], firstView: { whatItIs: "A workplace-language repair.", whatToDo: "Choose the accurate verb pattern and emphasis.", whatMatters: "Precision makes a recommendation credible.", whatNext: "Weigh a heritage trade-off." }, progressiveSupports: ["worked-example", "tip"] }),
  47: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "Heritage and transport require a conditional compromise with real trade-offs rather than a single correct view.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A fictional city consultation.", whatToDo: "Weigh two priorities and offer a conditional compromise.", whatMatters: "A fair plan explains its cost and review point.", whatNext: "Defend a public resource." }, progressiveSupports: ["worked-example", "word-support"] }),
  48: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A public letter requires a sustained position, a genuine concession, and an evidence-bound alternative.", selectedStages: ["orientation", "retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A public-resource response.", whatToDo: "Write a fair, evidence-led letter.", whatMatters: "Your recommendation must answer a real constraint.", whatNext: "Check a contested claim." }, progressiveSupports: ["worked-example", "word-support"] }),
  49: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Source ranking is a distinct comprehension task that establishes verification habits before later data interpretation.", selectedStages: ["encounter", "notice", "evidence", "next-bridge"], firstView: { whatItIs: "A claim-verification reading.", whatToDo: "Rank what each source can establish.", whatMatters: "A strong claim needs a proportionate source.", whatNext: "Calibrate a consumer claim." }, progressiveSupports: ["word-support", "tip"] }),
  50: createLessonExperience({ archetype: "vocabulary", density: "light", archetypeRationale: "Comparison and concession lexis needs a compact calibration route before learners make another public case.", selectedStages: ["encounter", "supported-practice", "retrieval"], firstView: { whatItIs: "A claim-strength vocabulary focus.", whatToDo: "Choose language that keeps a trade-off visible.", whatMatters: "Qualification protects a useful conclusion.", whatNext: "Test a workplace pilot." }, progressiveSupports: ["arabic-help", "word-support"] }),
  51: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Advanced modals become meaningful in a bounded staff-panel recommendation, not an isolated exercise.", selectedStages: ["orientation", "encounter", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A workplace-pilot panel.", whatToDo: "Recommend a measured trial and condition.", whatMatters: "Modals can show duty, caution, and evidence.", whatNext: "Trace responsibility in a report." }, progressiveSupports: ["worked-example", "tip"] }),
  52: createLessonExperience({ archetype: "notice", density: "normal", archetypeRationale: "Attribution choices are best noticed and repaired before learners write or speak about institutional responsibility.", selectedStages: ["encounter", "notice", "supported-practice", "next-bridge"], firstView: { whatItIs: "A responsibility-language check.", whatToDo: "Compare direct and impersonal reporting.", whatMatters: "Grammar can obscure or clarify accountability.", whatNext: "Read a statistic beyond its headline." }, progressiveSupports: ["worked-example", "tip"] }),
  53: createLessonExperience({ archetype: "reading", density: "deep", archetypeRationale: "The statistic task needs space for headline, data, limitation, and proportionate conclusion to remain distinct.", selectedStages: ["orientation", "encounter", "notice", "evidence"], firstView: { whatItIs: "A data-bound reading.", whatToDo: "Map what the statistic supports and limits.", whatMatters: "A number is not a conclusion by itself.", whatNext: "Review an ethical decision." }, progressiveSupports: ["word-support", "worked-example"] }),
  54: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A short decision review makes the past choice, present impact, and feasible revision audible and connected.", selectedStages: ["orientation", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A difficult-decision briefing.", whatToDo: "Connect a past choice to a present effect.", whatMatters: "A revision needs more than hindsight.", whatNext: "Plan access in public space." }, progressiveSupports: ["worked-example"] }),
  55: createLessonExperience({ archetype: "real-world", density: "deep", archetypeRationale: "An access proposal turns formal language into specific public measures, constraints, and reviewable action.", selectedStages: ["orientation", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A fictional park consultation.", whatToDo: "Propose practical access measures.", whatMatters: "Access needs specific, reviewable choices.", whatNext: "Make participation visible." }, progressiveSupports: ["worked-example", "word-support"] }),
  56: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "Reframing an invitation gives emphasis grammar an ethical and practical communication purpose.", selectedStages: ["encounter", "notice", "meaningful-use", "next-bridge"], firstView: { whatItIs: "A participation-invitation revision.", whatToDo: "Foreground a missing access route.", whatMatters: "Inclusion starts with who can respond.", whatNext: "Build a fair reform case." }, progressiveSupports: ["worked-example", "arabic-help"] }),
  57: createLessonExperience({ archetype: "integration", density: "normal", archetypeRationale: "Claim, evidence, concession, and rebuttal need deliberate assembly before the final assessment—not another full essay.", selectedStages: ["retrieval", "encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A reform-argument sequence.", whatToDo: "Connect evidence, objection, and response.", whatMatters: "A fair objection can strengthen a case.", whatNext: "Communicate risk calmly." }, progressiveSupports: ["worked-example", "word-support"] }),
  58: createLessonExperience({ archetype: "grammar", density: "normal", archetypeRationale: "Calibrated risk language is a precision tool that prevents panic or complacency before source review.", selectedStages: ["encounter", "notice", "supported-practice"], firstView: { whatItIs: "A calm-risk language focus.", whatToDo: "Replace an absolute message proportionately.", whatMatters: "Uncertainty belongs in public communication.", whatNext: "Trace a statement to its source." }, progressiveSupports: ["worked-example", "tip"] }),
  59: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "Selective sorting rehearses the module’s evidence trail while keeping cognitive load low before assessment.", selectedStages: ["retrieval", "supported-practice", "next-bridge"], firstView: { whatItIs: "A source-and-stance review.", whatToDo: "Separate report, evidence, evaluation, and next question.", whatMatters: "Good judgement shows its evidence trail.", whatNext: "Make a reviewable compromise." }, progressiveSupports: ["tip"] }),
  60: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The final position paper transfers conditional compromise, source limits, qualification, and review conditions to a new fictional dispute.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A B2 public-compromise checkpoint.", whatToDo: "Evaluate options and recommend a conditional plan.", whatMatters: "A defensible choice is evidence-led and reviewable.", whatNext: "Move into the next B2 module." }, progressiveSupports: ["tip"] }),
};
const B2_MODULE_5_EXPERIENCES: Record<number, LessonExperience> = {
  61: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A compact source-framing reading establishes the module's evidence lens.", selectedStages: ["encounter", "notice", "evidence"], firstView: { whatItIs: "A news-framing reading.", whatToDo: "Separate report from interpretation.", whatMatters: "A frame is not the same as proof.", whatNext: "Qualify a progress claim." }, progressiveSupports: ["word-support", "worked-example"] }),
  62: createLessonExperience({ archetype: "interaction", density: "normal", archetypeRationale: "A bounded consultation makes benefit-cost qualification usable.", selectedStages: ["retrieval", "encounter", "meaningful-use"], firstView: { whatItIs: "A local progress consultation.", whatToDo: "Name benefit and cost.", whatMatters: "Progress affects different people differently.", whatNext: "Listen for respectful qualification." }, progressiveSupports: ["worked-example", "word-support"] }),
  63: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "Listening for a cultural qualification adds authentic skill variation without adding a second production task.", selectedStages: ["encounter", "notice", "retrieval"], firstView: { whatItIs: "A translator's careful qualification.", whatToDo: "Listen for what is avoided.", whatMatters: "Precision prevents cultural overclaiming.", whatNext: "Evaluate belonging language." }, progressiveSupports: ["transcript", "worked-example"] }),
  64: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A focused recommendation gives belonging language a measurable civic purpose.", selectedStages: ["retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "An inclusion-campaign evaluation.", whatToDo: "Recommend one accountable change.", whatMatters: "Belonging needs evidence, not slogans.", whatNext: "Build a case that answers back." }, progressiveSupports: ["worked-example", "word-support"] }),
  65: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The first checkpoint asks for transfer of evidence, rebuttal, and measurement.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A recommendation checkpoint.", whatToDo: "Build a case with a rebuttal.", whatMatters: "A credible recommendation can be reviewed.", whatNext: "Make responsibility visible in grammar." }, progressiveSupports: ["worked-example", "tip"] }),
  66: createLessonExperience({ archetype: "grammar", density: "light", archetypeRationale: "Accountability grammar is isolated so the lesson does not become another full writing task.", selectedStages: ["encounter", "notice", "supported-practice"], firstView: { whatItIs: "A responsibility-language focus.", whatToDo: "Make the responsible actor visible.", whatMatters: "Grammar can hide or clarify accountability.", whatNext: "Read appraisal beside evidence." }, progressiveSupports: ["worked-example", "tip"] }),
  67: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "Critical review language extends the evidence-versus-judgement distinction through a new text.", selectedStages: ["encounter", "notice", "evidence"], firstView: { whatItIs: "A reviewer's evidence check.", whatToDo: "Label judgement and detail.", whatMatters: "A confident adjective is not proof.", whatNext: "Disagree without closing the door." }, progressiveSupports: ["word-support", "worked-example"] }),
  68: createLessonExperience({ archetype: "review", density: "light", archetypeRationale: "Retrieval through respectful disagreement consolidates the module's qualification language.", selectedStages: ["retrieval", "supported-practice", "next-bridge"], firstView: { whatItIs: "A respectful disagreement review.", whatToDo: "Acknowledge then qualify.", whatMatters: "Nuance keeps dialogue open.", whatNext: "Project policy consequences." }, progressiveSupports: ["worked-example", "arabic-help"] }),
  69: createLessonExperience({ archetype: "writing", density: "deep", archetypeRationale: "A phased policy comparison gives conditional consequence language a practical purpose.", selectedStages: ["encounter", "meaningful-use", "evidence"], firstView: { whatItIs: "A neighbourhood options brief.", whatToDo: "Compare and recommend a phased plan.", whatMatters: "A plan needs a review condition.", whatNext: "Explain purpose under pressure." }, progressiveSupports: ["worked-example", "word-support"] }),
  70: createLessonExperience({ archetype: "speaking", density: "normal", archetypeRationale: "A short workplace explanation makes precise distinction audible without adding reading or writing.", selectedStages: ["encounter", "supported-practice", "meaningful-use"], firstView: { whatItIs: "A workplace concern briefing.", whatToDo: "Distinguish purpose from pressure.", whatMatters: "A measured explanation invites action.", whatNext: "Decide what a city should preserve." }, progressiveSupports: ["worked-example", "tip"] }),
  71: createLessonExperience({ archetype: "reading", density: "normal", archetypeRationale: "A heritage debate reading balances access, history, and future use.", selectedStages: ["encounter", "notice", "evidence"], firstView: { whatItIs: "A heritage decision reading.", whatToDo: "Weigh competing public values.", whatMatters: "Preservation choices affect access.", whatNext: "Defend a position worth hearing." }, progressiveSupports: ["word-support", "worked-example"] }),
  72: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "A public letter tests evidence and counterpoint before the final workplace proposal.", selectedStages: ["retrieval", "meaningful-use", "evidence", "next-bridge"], firstView: { whatItIs: "A public-letter checkpoint.", whatToDo: "Defend a position and answer a concern.", whatMatters: "A public argument must remain reviewable.", whatNext: "Report certainty under pressure." }, progressiveSupports: ["worked-example", "tip"] }),
  73: createLessonExperience({ archetype: "listening", density: "light", archetypeRationale: "A briefing trains certainty calibration as a listening skill distinct from speaking.", selectedStages: ["encounter", "notice", "retrieval"], firstView: { whatItIs: "An editor's certainty briefing.", whatToDo: "Separate confirmed from unresolved.", whatMatters: "Reporting verbs carry evidence weight.", whatNext: "Qualify the price of convenience." }, progressiveSupports: ["transcript", "worked-example"] }),
  74: createLessonExperience({ archetype: "writing", density: "normal", archetypeRationale: "A concise city-magazine recommendation balances a benefit and a trade-off.", selectedStages: ["retrieval", "meaningful-use", "evidence"], firstView: { whatItIs: "A convenience trade-off note.", whatToDo: "Qualify a useful recommendation.", whatMatters: "Convenience has a social cost.", whatNext: "Propose a workplace worth joining." }, progressiveSupports: ["worked-example", "word-support"] }),
  75: createLessonExperience({ archetype: "assessment", density: "deep", archetypeRationale: "The module assessment transfers qualification, culture evaluation, and measurable piloting to a new workplace case.", selectedStages: ["orientation", "retrieval", "evidence", "next-bridge"], firstView: { whatItIs: "A workplace-culture assessment.", whatToDo: "Propose a measurable flexible-hours pilot.", whatMatters: "A good proposal names its success test.", whatNext: "Move into the next B2 module." }, progressiveSupports: ["worked-example", "tip"] }),
};

export const B2_LESSONS: LessonDefinition[] = (rawDraft as DraftLesson[]).map((draft) => ({
  level: "B2" as const, lessonNumber: draft.lessonNumber, moduleNumber: Math.ceil(draft.lessonNumber / 15), title: draft.title, titleArabic: draft.titleArabic,
  words: draft.vocabulary.map((item, index) => asVocabularyItem(item, draft.lessonNumber, index)), grammar: asGrammarTopic(draft),
  learningPlan: { outcome: draft.outcome, steps: STEPS, retrieval: draft.retrieval.map((item) => ({ sourceLevel: "B1" as const, language: item.language, prompt: item.prompt, purpose: item.purpose })), englishFirst: true, studio: "Evidence & Influence Studio" },
  lexicalNetworks: [{ id: `b2-network-${draft.lessonNumber}`, theme: draft.network.theme, themeArabic: draft.network.themeArabic, anchor: draft.network.anchor, wordFamilies: draft.network.wordFamilies, relatedWords: draft.network.relatedWords, chunks: draft.network.chunks, collocations: draft.network.collocations, register: draft.network.register, priorLevelLinks: draft.network.priorLevelLinks, learningNote: draft.network.learningNote, learningNoteArabic: draft.network.learningNoteArabic }],
  practiceBrief: { readingBrief: draft.readingBrief, writingPrompt: draft.writingPrompt },
})).map(enrichLesson).map((lesson) => ({
  ...lesson,
  activities: B2_MODULE_1_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_2_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_3_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_4_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_5_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_6_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_7_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_8_ACTIVITIES[lesson.lessonNumber] ?? B2_MODULE_9_ACTIVITIES[lesson.lessonNumber] ?? lesson.activities,
  experience: B2_MODULE_1_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_2_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_3_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_4_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_5_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_6_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_7_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_8_EXPERIENCES[lesson.lessonNumber] ?? B2_MODULE_9_EXPERIENCES[lesson.lessonNumber] ?? lesson.experience,
}));

export const B2_VOCABULARY = B2_LESSONS.flatMap((lesson) => lesson.words);
export const B2_GRAMMAR = B2_LESSONS.map((lesson) => lesson.grammar);
export const B2_COURSE: CourseDefinition = { level: "B2", title: "Evidence, influence, and informed judgement", titleArabic: "الأدلة والتأثير والحكم الواعي", totalLessons: 150, lessonsPerModule: 15, estimatedMinutes: 380 * 60, lessons: B2_LESSONS, modules: buildModuleDefinitions("B2", B2_LESSONS) };
export function getB2Lesson(lessonNumber: number) { return B2_LESSONS.find((lesson) => lesson.lessonNumber === lessonNumber); }
