import type { LessonActivity } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & { minutes: number; prompt?: string; promptArabic?: string };

const specs: Record<number, Spec> = {
  1: { kind: "reading", title: "Read between the lines", titleArabic: "اقرأ بين السطور", objective: "Identify implication and framing across two sources before making a cautious attribution.", objectiveArabic: "حدّد الإيحاء والتأطير في مصدرين قبل أن تنسب المعنى بحذر.", stage: "introduction", semantic: "example", minutes: 24, readingText: "A feature article praises a city’s green corridors as a simple answer to heat, while a planning extract notes that the first pilot served wealthier streets. Neither text states that the policy is unfair. The implication emerges through what each source foregrounds, omits, and assumes about access.", readingTextArabic: "يمدح مقال صحفي الممرات الخضراء في مدينة باعتبارها حلاً بسيطاً للحرارة، بينما يذكر مقتطف تخطيطي أن التجربة الأولى خدمت الشوارع الأكثر ثراءً. لا يصرّح أي نص بأن السياسة غير عادلة؛ بل يظهر الإيحاء من خلال ما يبرزه كل مصدر وما يغفله ويفترضه عن الوصول.", sentencePatterns: ["The source implies that …", "By foregrounding …, the writer frames …", "It is plausible to attribute this view to …"] },
  2: { kind: "standard", title: "Put a claim under scrutiny", titleArabic: "أخضع ادعاءً للتدقيق", objective: "Separate a contested claim from the method and limitations behind it.", objectiveArabic: "افصل الادعاء المتنازع عليه عن المنهج والحدود التي تقف وراءه.", stage: "explanation", semantic: "grammar", minutes: 18, sentencePatterns: ["The claim rests on …", "The method does not necessarily establish …", "A limitation that should be acknowledged is …"] },
  3: { kind: "listening", title: "Calibrate uncertainty", titleArabic: "اضبط درجة اليقين", objective: "Report what a speaker knows, suspects, and cannot yet establish using calibrated probability language.", objectiveArabic: "انقل ما يعرفه المتحدث وما يشك فيه وما لا يستطيع إثباته بعد باستخدام لغة احتمالية دقيقة.", stage: "guided-practice", semantic: "activity", minutes: 22, speakingLines: [{ id: "analyst", speaker: "Analyst", text: "The early figures may point to a change, but the sample is too small to show whether the pattern will continue.", textArabic: "قد تشير الأرقام الأولية إلى تغير، لكن العينة صغيرة جداً لإظهار ما إذا كان النمط سيستمر." }], sentencePatterns: ["The speaker appears to suggest …", "The evidence may indicate …, but it does not establish …", "At this stage, it would be premature to conclude …"] },
  4: { kind: "reading", title: "When sources disagree", titleArabic: "عندما تختلف المصادر", objective: "Synthesize disagreement by identifying bias, evidence gaps, and a defensible common question.", objectiveArabic: "ركّب الاختلاف بتحديد التحيز وفجوات الدليل وسؤال مشترك يمكن الدفاع عنه.", stage: "real-context", semantic: "example", minutes: 25, readingText: "One report measures the number of visitors a public service attracts; another interviews people who stopped using it. The reports appear to contradict each other until their populations and purposes are compared. Together they suggest reach and accessibility are related but not identical outcomes.", readingTextArabic: "يقيس تقرير عدد زوار خدمة عامة، بينما يجري تقرير آخر مقابلات مع أشخاص توقفوا عن استخدامها. يبدوان متناقضين حتى تُقارن الفئات والأغراض. ويشير التقريرين معاً إلى أن الانتشار وسهولة الوصول نتيجتان مرتبطتان لكنهما غير متطابقتين.", sentencePatterns: ["The apparent contradiction disappears when …", "The sources differ in …", "Taken together, they suggest …"] },
  5: { kind: "writing", title: "Write a conclusion, not a slogan", titleArabic: "اكتب خلاصة لا شعاراً", objective: "Write a proportionate evidence-led conclusion that concedes a plausible objection and recommends a measured next step.", objectiveArabic: "اكتب خلاصة متناسبة مع الدليل تعترف باعتراض معقول وتقترح خطوة تالية مدروسة.", stage: "guided-practice", semantic: "grammar", minutes: 30, prompt: "Write 220–260 words for a municipal committee concluding whether a neighbourhood greening pilot should expand. Use two evidence points, one concession, and a recommendation that reflects uncertainty.", promptArabic: "اكتب 220–260 كلمة للجنة بلدية تختتم فيها ما إذا كان ينبغي توسيع تجربة تخضير حيّ. استخدم نقطتي دليل وتنازلاً واحداً وتوصية تعكس عدم اليقين.", sentencePatterns: ["The evidence supports …, although …", "A reasonable objection is …", "On balance, the committee should …"] },
  6: { kind: "interaction", title: "Hear the public issue personally", titleArabic: "استمع إلى القضية العامة كما تُعاش", objective: "Combine policy evidence with first-hand testimony and negotiate a position that respects both forms of knowledge.", objectiveArabic: "اجمع بين دليل السياسة والشهادة المباشرة وتفاوض على موقف يحترم نوعي المعرفة.", stage: "real-context", semantic: "activity", minutes: 22, interactionTurns: [{ id: "resident", speaker: "Resident", text: "The new service looks efficient on paper, but the nearest branch is now too far for my mother to reach.", textArabic: "تبدو الخدمة الجديدة فعالة على الورق، لكن أقرب فرع أصبح بعيداً جداً عن والدتي." , purpose: "Notice lived experience." }, { id: "you", speaker: "You", text: "The figures suggest efficiency, but your account shows what the average obscures. I would recommend … .", textArabic: "تشير الأرقام إلى الكفاءة، لكن قصتك توضح ما يخفيه المتوسط. أوصي بـ … .", purpose: "Balance evidence and testimony." }] },
  7: { kind: "speaking", title: "Question the ethics of convenience", titleArabic: "ناقش أخلاقيات السهولة", objective: "Evaluate a technological convenience through counterfactual reasoning about consent and responsibility.", objectiveArabic: "قيّم سهولة تقنية من خلال التفكير الافتراضي في الموافقة والمسؤولية.", stage: "real-context", semantic: "activity", minutes: 20, speakingLines: [{ id: "colleague", speaker: "Colleague", text: "The app saves time for everyone, so asking users to review every data permission would defeat the purpose.", textArabic: "يوفر التطبيق الوقت للجميع، ولذلك فإن مطالبة المستخدمين بمراجعة كل إذن للبيانات ستلغي الغرض منه." }, { id: "you", speaker: "You", text: "If convenience had been the only value, that might follow. But where consent is meaningful, the design should … .", textArabic: "لو كانت السهولة هي القيمة الوحيدة، لربما صح ذلك. لكن حين تكون الموافقة حقيقية، ينبغي للتصميم أن … ." }] },
  8: { kind: "reading", title: "Read beyond a single story", titleArabic: "اقرأ أبعد من رواية واحدة", objective: "Challenge a prevailing representation respectfully by comparing whose perspective is visible and whose is absent.", objectiveArabic: "تحدَّ تمثيلاً سائداً باحترام من خلال مقارنة المنظور الظاهر بالمنظور الغائب.", stage: "real-context", semantic: "example", minutes: 24, readingText: "A tourism campaign presents a historic district as timeless and welcoming. A residents’ archive describes rising rents, changing work, and the loss of informal meeting places. The second account need not cancel the first; it makes the picture more accountable by asking who gets to define the district’s identity.", readingTextArabic: "يعرض إعلان سياحي حياً تاريخياً بوصفه خالداً ومرحّباً. ويصف أرشيف للسكان ارتفاع الإيجارات وتغير العمل وفقدان أماكن اللقاء غير الرسمية. لا يلغي الحساب الثاني الأول بالضرورة؛ بل يجعل الصورة أكثر مسؤولية بسؤاله من يملك حق تعريف هوية الحي.", sentencePatterns: ["The first account presents … as …", "The archive complicates this picture by …", "A respectful critique would acknowledge … while questioning …"] },
  9: { kind: "writing", title: "Define what counts as progress", titleArabic: "حدّد ما الذي يُعدّ تقدماً", objective: "Synthesize competing indicators and recommend a definition of progress for a public reader.", objectiveArabic: "ركّب مؤشرات متنافسة واقترح تعريفاً للتقدم لقارئ عام.", stage: "guided-practice", semantic: "grammar", minutes: 30, prompt: "Write 230–280 words for a public policy magazine explaining which indicators should count as progress in a city. Balance economic, environmental, and lived-experience evidence.", promptArabic: "اكتب 230–280 كلمة لمجلة سياسات عامة تشرح فيها أي مؤشرات ينبغي أن تُعد تقدماً في مدينة. وازن بين الدليل الاقتصادي والبيئي وتجربة السكان.", sentencePatterns: ["If progress is defined solely as …, …", "A fuller measure would also take … into account.", "The most proportionate recommendation is …"] },
  10: { kind: "reading", title: "Trace the cost of a decision", titleArabic: "تتبّع كلفة القرار", objective: "Analyse allocation trade-offs and identify an unintended effect that a policy should mitigate.", objectiveArabic: "حلّل مفاضلات تخصيص الموارد وحدد أثراً غير مقصود ينبغي للسياسة تخفيفه.", stage: "guided-practice", semantic: "example", minutes: 23, readingText: "A council funds a rapid transport link by delaying repairs to smaller routes. The headline benefit is visible in shorter journeys, but the delayed routes serve people with fewer alternatives. A responsible policy would compare both gains and distributional costs before announcing success.", readingTextArabic: "تموّل بلدية خط نقل سريعاً من خلال تأجيل إصلاح الطرق الأصغر. تظهر الفائدة الرئيسية في تقصير الرحلات، لكن الطرق المؤجلة تخدم أشخاصاً لديهم بدائل أقل. وتقارن السياسة المسؤولة بين المكاسب وتكاليف التوزيع قبل إعلان النجاح.", sentencePatterns: ["The decision prioritises … at the expense of …", "An unintended effect could be …", "The mitigation should target …"] },
  11: { kind: "interaction", title: "Design a space for disagreement", titleArabic: "صمّم مساحة للاختلاف", objective: "Plan a public deliberation that uses hedged persuasion and diplomatic rebuttal.", objectiveArabic: "خطط لحوار عام يستخدم الإقناع المتحفظ والرد الدبلوماسي.", stage: "real-context", semantic: "activity", minutes: 21, interactionTurns: [{ id: "chair", speaker: "Chair", text: "If we allow every concern onto the agenda, the meeting will never reach a decision.", textArabic: "إذا سمحنا لكل قلق بأن يدخل جدول الأعمال، فلن يصل الاجتماع إلى قرار أبداً.", purpose: "Recognise a practical concern." }, { id: "you", speaker: "You", text: "That concern is understandable. A structured agenda could preserve time while ensuring that affected groups … .", textArabic: "هذا القلق مفهوم. ويمكن لجدول أعمال منظم أن يحافظ على الوقت ويضمن في الوقت نفسه أن … .", purpose: "Offer a diplomatic design." }] },
  12: { kind: "review", title: "Let history inform the argument", titleArabic: "دع التاريخ يضيء الحجة", objective: "Retrieve historical evidence and connect precedent to a present consequence without treating analogy as proof.", objectiveArabic: "استرجع دليلاً تاريخياً واربط السابقة بأثر حاضر دون اعتبار القياس برهاناً.", stage: "review", semantic: "retrieval", minutes: 18, sentencePatterns: ["The precedent is relevant because …", "The analogy is limited by …", "History can inform the decision, but it cannot by itself …"] },
  13: { kind: "listening", title: "Adapt culture in motion", titleArabic: "كيّف الحديث عن ثقافة متحركة", objective: "Reframe a cultural-change explanation for different public audiences using metaphor and qualification.", objectiveArabic: "أعد صياغة شرح التغير الثقافي لجمهورين عامين باستخدام الاستعارة والتقييد.", stage: "real-context", semantic: "activity", minutes: 22, speakingLines: [{ id: "curator", speaker: "Curator", text: "Culture is not a museum case; it is a conversation in which old meanings are revised by new speakers.", textArabic: "الثقافة ليست صندوق عرض في متحف؛ إنها حوار يعيد متحدثون جدد فيه صياغة المعاني القديمة." }], sentencePatterns: ["For a general audience, I would explain …", "This metaphor is useful insofar as …", "The change should not be portrayed as …"] },
  14: { kind: "reading", title: "Test the limits of expertise", titleArabic: "اختبر حدود الخبرة", objective: "Attribute expert claims responsibly while distinguishing authority, evidence, and remaining uncertainty.", objectiveArabic: "انسب ادعاءات الخبراء بمسؤولية مع التمييز بين السلطة والدليل وعدم اليقين المتبقي.", stage: "independent-practice", semantic: "example", minutes: 25, readingText: "Three specialists support a new flood model, but each statement is based on a different data set. One describes a high-confidence trend; another calls the result promising but preliminary; the third asks for independent replication. A careful brief preserves those differences instead of turning expertise into a single voice.", readingTextArabic: "يدعم ثلاثة متخصصين نموذجاً جديداً للفيضانات، لكن كل تصريح يستند إلى مجموعة بيانات مختلفة. يصف أحدهم اتجاهاً عالي الثقة، ويسمي آخر النتيجة واعدة لكنها أولية، ويطلب الثالث تكراراً مستقلاً. وتحافظ الإحاطة الدقيقة على هذه الفروق بدلاً من تحويل الخبرة إلى صوت واحد.", sentencePatterns: ["X reports that …", "According to X, the evidence is …", "This claim should be treated cautiously because …"] },
  15: { kind: "writing", title: "Write a review with consequences", titleArabic: "اكتب مراجعة لها تبعات", objective: "Produce a recommendation that balances criticism, concession, and likely consequences.", objectiveArabic: "قدّم توصية توازن بين النقد والتنازل والعواقب المحتملة.", stage: "independent-practice", semantic: "example", minutes: 30, prompt: "Write 230–280 words reviewing a public service redesign. Balance one strength, two limitations, one concession, and a recommendation with consequences for users.", promptArabic: "اكتب 230–280 كلمة تراجع فيها إعادة تصميم خدمة عامة. وازن بين نقطة قوة وقيدين وتنازل واحد وتوصية مع عواقبها على المستخدمين.", sentencePatterns: ["The redesign succeeds insofar as …", "A legitimate criticism is …", "If adopted, the recommendation would likely …"] },
  16: { kind: "assessment", title: "Make complexity readable", titleArabic: "اجعل التعقيد قابلاً للقراءة", objective: "Transform specialist material into an audience-appropriate brief that preserves uncertainty, trade-offs, and evidence weight.", objectiveArabic: "حوّل مادة متخصصة إلى إحاطة مناسبة للجمهور تحافظ على عدم اليقين والمفاضلات ووزن الدليل.", stage: "assessment", semantic: "assessment", minutes: 34, prompt: "Write 260–320 words for a city committee from a specialist dossier. Explain the central finding, qualify one uncertain claim, compare two trade-offs, and recommend a course of action with a review condition.", promptArabic: "اكتب 260–320 كلمة للجنة مدينة اعتماداً على ملف متخصص. اشرح النتيجة الأساسية، وقيّد ادعاءً غير مؤكد، وقارن مفاضلتين، واقترح مسار عمل مع شرط للمراجعة.", sentencePatterns: ["The dossier establishes …, while … remains uncertain.", "The main trade-off is between … and … .", "I recommend …, subject to a review of … ."] },
};

const check = (lesson: number): NonNullable<LessonActivity["retrievalCheck"]> => ({ prompt: `Retrieve one evidence, attribution, qualification, or counterargument move from earlier B2 study and apply it to Lesson ${lesson}.`, promptArabic: `استرجع حركة دليل أو نسبة أو تقييد أو حجة مضادة من دراسة B2 السابقة وطبّقها في الدرس ${lesson}.`, expectedEvidence: "A concise response that uses the retrieved move in a relevant C1 context.", expectedEvidenceArabic: "إجابة موجزة تستخدم الحركة المسترجعة في سياق C1 مناسب." });

export const C1_MODULE_1_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([key, spec]) => {
  const lesson = Number(key);
  const activity: LessonActivity = {
    id: `c1-m1-${lesson}`,
    kind: spec.kind,
    title: spec.title,
    titleArabic: spec.titleArabic,
    objective: spec.objective,
    objectiveArabic: spec.objectiveArabic,
    stage: spec.stage,
    estimatedMinutes: spec.minutes,
    semantic: spec.semantic,
    progressiveSupports: spec.kind === "reading" ? ["word-support", "arabic-help"] : spec.kind === "listening" ? ["transcript", "worked-example"] : spec.kind === "assessment" ? ["worked-example", "tip"] : ["worked-example", "word-support"],
    retrievalCheck: check(lesson),
    ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}),
    ...(spec.readingText ? { readingText: spec.readingText, readingTextArabic: spec.readingTextArabic } : {}),
    ...(spec.speakingLines ? { speakingLines: spec.speakingLines } : {}),
    ...(spec.interactionTurns ? { interactionTurns: spec.interactionTurns } : {}),
    ...(spec.sentencePatterns ? { sentencePatterns: spec.sentencePatterns } : {}),
  };
  return [lesson, [activity]];
})) as Record<number, LessonActivity[]>;
