import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_8_EXPERIENCES: Record<number, LessonExperience> = {
  113: experience("reading", "deep", "The module begins with a cultural change that makes description and judgement visibly different before more technical scrutiny begins.", ["orientation", "encounter", "notice", "evidence", "retrieval"], "A culture-in-motion reading studio.", "Separate what each account describes from the value judgement it adds.", "A shared description does not guarantee a shared evaluation.", "Limit an expert claim.", ["word-support", "arabic-help", "extended-rationale"]),
  114: experience("grammar", "normal", "A narrow language lab gives the learner a practical way to place boundaries around expertise.", ["retrieval", "notice", "supported-practice", "meaningful-use"], "An expertise-boundary language lab.", "Name the field, support the claim, and state what it cannot settle.", "Expertise becomes trustworthy when its scope is visible.", "Hear a consequential review.", ["worked-example", "tip", "arabic-help"]),
  115: experience("listening", "normal", "The review briefing makes balanced evaluation audible and withholds the transcript until after a first listening attempt.", ["encounter", "notice", "retrieval"], "A review-with-consequences listening briefing.", "Listen for achievement, limitation, and the consequence proposed for the next review.", "A positive result can still require a better question next time.", "Make complexity readable.", ["transcript", "worked-example"]),
  116: experience("writing", "deep", "The writing studio transfers specialist precision into public clarity without rewarding oversimplification.", ["retrieval", "meaningful-use", "evidence"], "A public-explanation writing studio.", "Rewrite a technical explanation, preserving its method and one limitation.", "Clarity is responsible when it keeps the uncertainty that matters.", "Defend a proposal under pressure.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  117: experience("interaction", "normal", "A live timing objection makes conditional recommendation language concrete before the checkpoint synthesis.", ["orientation", "encounter", "meaningful-use", "retrieval"], "A pressured consultation interaction.", "Concede the timing risk, propose a limited pilot, and preserve a review safeguard.", "A safeguard can make action possible without pretending risk is absent.", "Make the case against certainty.", ["worked-example", "tip", "arabic-help"]),
  118: experience("reading", "deep", "The paired survey and interview evidence moves the learner from rhetorical confidence to method-sensitive confidence.", ["retrieval", "notice", "supported-practice", "evidence"], "A confidence-and-evidence reading.", "Compare what broad and deep sources can each establish.", "Different limitations do not make evidence useless; they make its use specific.", "Find a voice in the debate.", ["word-support", "worked-example", "extended-rationale"]),
  119: experience("listening", "normal", "The crowded debate requires tracking both the stated position and the safeguard hidden inside a concession.", ["encounter", "notice", "supported-practice", "retrieval"], "A multi-voice access debate.", "Identify position, interruption pressure, concession, and unresolved disagreement.", "Good listening follows the boundary of a claim, not only its headline.", "Synthesize with integrity.", ["transcript", "worked-example"]),
  120: experience("integration", "deep", "The ten-lesson checkpoint asks the learner to preserve different source questions while producing an actionable synthesis.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A culture-and-evidence synthesis checkpoint.", "Compare reach, curatorial depth, and user experience, then recommend one next step.", "Integrity means keeping a relevant cost visible when it complicates success.", "Read between the lines.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  121: experience("reading", "deep", "The public statement and staff memo reveal how register and omission shape a reader's sense of welcome and cost.", ["encounter", "notice", "evidence", "retrieval"], "A register-and-omission reading studio.", "Mark what each text foregrounds, suppresses, and assumes about its audience.", "Framing changes salience even when it does not change every fact.", "Put a claim under scrutiny.", ["word-support", "arabic-help", "extended-rationale"]),
  122: experience("reading", "deep", "Method and provenance scrutiny follows framing so the learner can test a persuasive headline rather than merely paraphrase it.", ["retrieval", "notice", "supported-practice", "evidence"], "A claim-scrutiny reading lab.", "Trace the measure, population, scope, and plausible alternative explanation.", "A headline can be directionally useful while still exceeding its evidence.", "Use the language of uncertainty.", ["word-support", "worked-example", "extended-rationale"]),
  123: experience("grammar", "normal", "The lesson isolates stance adverbials and reporting verbs as tools for useful, non-evasive uncertainty.", ["retrieval", "notice", "supported-practice", "meaningful-use"], "An uncertainty-language workshop.", "Choose wording that reflects the strength and limit of the evidence.", "Calibrated language protects both truth and usefulness.", "Compare conflicting sources.", ["worked-example", "tip", "arabic-help"]),
  124: experience("listening", "normal", "Two speakers answer different questions, so the learner must compare legitimate scope rather than declare a winner; the transcript remains hidden initially.", ["encounter", "notice", "supported-practice", "retrieval"], "A conflicting-sources listening lab.", "Identify what each source can establish and where neither source can go.", "A fair report can hold complementary limits together.", "Write a conclusion, not a slogan.", ["transcript", "worked-example", "tip"]),
  125: experience("writing", "deep", "The conclusion task turns the module's source and uncertainty moves into a concise recommendation with a revision trigger.", ["retrieval", "meaningful-use", "evidence"], "A proportionate-conclusion writing studio.", "State support, concede access concern, and define what would change your advice.", "A conclusion is stronger when it shows how it could be revised.", "Hold a public issue close.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  126: experience("reading", "deep", "Paired personal accounts keep distribution and lived burden visible without turning anecdote into prevalence.", ["encounter", "notice", "evidence", "retrieval"], "A public-policy-and-lived-experience reading.", "Use personal accounts as illustrations while retaining the need for wider evidence.", "Human detail can reveal a burden without becoming a universal statistic.", "Question the ethics of convenience.", ["word-support", "arabic-help", "extended-rationale"]),
  127: experience("real-world", "normal", "A counterfactual interaction turns ethical convenience into a practical design decision with a group-specific consequence.", ["retrieval", "encounter", "meaningful-use"], "An ethics-of-convenience design dilemma.", "Test who benefits, who pays, and what review safeguard should remain.", "Efficiency is not a sufficient justification when an avoidable burden is shifted.", "Move beyond a single story.", ["worked-example", "arabic-help", "tip"]),
  128: experience("assessment", "deep", "The fresh cultural dossier transfers description, limitation, comparison, human consequence, and review into one formal recommendation.", ["orientation", "retrieval", "encounter", "meaningful-use", "evidence", "next-bridge"], "A beyond-the-single-story synthesis challenge.", "Attribute several sources, preserve uncertainty, explain unequal consequence, and set a review trigger.", "C1 judgement combines accurate attribution, humane representation, calibrated confidence, and responsible action.", "Carry one evidence habit into Module 9.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_8_EXPERIENCES;
