import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_10_EXPERIENCES: Record<number, LessonExperience> = {
  145: experience("reading", "deep", "The final module opens by making invisible distributional costs visible before the learner begins synthesis.", ["orientation", "encounter", "notice", "evidence", "retrieval"], "A public-benefit reading studio.", "Compare the headline gain with the people paying the transition cost.", "A responsible account shows both reach and burden.", "Turn evidence into proportion.", ["word-support", "arabic-help", "extended-rationale"]),
  146: experience("grammar", "normal", "A focused language lab gives the learner precise structures for bounded causal and evaluative claims.", ["retrieval", "notice", "supported-practice", "meaningful-use"], "A proportion-and-context language workshop.", "Use nominalisation and context to avoid universal conclusions.", "Precision keeps an abstract claim connected to its conditions.", "Question the convenient choice.", ["worked-example", "tip", "arabic-help"]),
  147: experience("interaction", "normal", "The convenience dilemma turns ethical conditionals into a spoken decision tool rather than a grammar exercise.", ["orientation", "encounter", "meaningful-use", "retrieval"], "An ethical-technology decision exchange.", "Challenge convenience respectfully and propose a reversible safeguard.", "A fast option is not automatically a fair option.", "Challenge a single story.", ["worked-example", "arabic-help", "tip"]),
  148: experience("reading", "deep", "The representation case asks the learner to critique a narrow public story while documenting agency instead of replacing one simplification with another.", ["encounter", "notice", "evidence", "retrieval"], "A representation-and-agency reading studio.", "Identify the frame, its omission, and the evidence for a fuller account.", "Respectful critique makes the missing agency visible.", "Ask what progress means.", ["word-support", "extended-rationale", "arabic-help"]),
  149: experience("reading", "deep", "Competing metrics make the learner combine aggregate, service, and distributional evidence without pretending they answer one question.", ["retrieval", "notice", "supported-practice", "evidence"], "A progress-dashboard analysis lab.", "Match each indicator to its question and recommend a transparent combination.", "A dashboard earns trust by publishing purpose and limits.", "Map the cost of a decision.", ["word-support", "worked-example", "arabic-help"]),
  150: experience("writing", "deep", "The allocation studio transfers the first five lessons into a concise proposal with an explicit safeguard and review trigger.", ["retrieval", "meaningful-use", "evidence"], "A resource-allocation writing studio.", "Explain the gain, burden, affected group, and mitigation in a formal proposal.", "A recommendation is accountable when its cost is named.", "Make disagreement usable.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  151: experience("speaking", "normal", "The deliberation exchange reframes disagreement as evidence that can improve decision design.", ["orientation", "encounter", "meaningful-use", "retrieval"], "A deliberation-design interaction.", "Acknowledge urgency while using disagreement to identify a condition or safeguard.", "Good process converts conflict into a more answerable choice.", "Use memory without myth.", ["worked-example", "arabic-help", "tip"]),
  152: experience("reading", "deep", "The historical account prevents the learner from extracting a heroic slogan from a mixed precedent.", ["encounter", "notice", "evidence", "retrieval"], "A history-and-transfer reading studio.", "Carry achievement, cost, and changed conditions into a present judgement.", "History disciplines transfer when its corrections remain visible.", "Reframe culture in motion.", ["word-support", "extended-rationale", "arabic-help"]),
  153: experience("listening", "normal", "A two-voice cultural discussion requires the learner to hear metaphor and qualification before interpreting the disagreement.", ["encounter", "notice", "retrieval"], "A culture-in-motion listening route.", "Track what the metaphor highlights and the condition that limits it.", "A useful frame can still need a boundary.", "Limit expertise responsibly.", ["transcript", "worked-example", "arabic-help"]),
  154: experience("reading", "deep", "The expertise case makes domain boundaries explicit and distinguishes technical evidence from public value judgement.", ["retrieval", "notice", "evidence"], "An expertise-boundary reading lab.", "Match each expert claim to its legitimate question and name the remaining public judgement.", "Expertise informs a decision; it does not settle its meaning alone.", "Write a review that changes action.", ["word-support", "arabic-help", "extended-rationale"]),
  155: experience("writing", "deep", "The review studio requires a consequential judgement that acknowledges success, limitation, concession, and change.", ["retrieval", "meaningful-use", "evidence"], "A consequence-aware review studio.", "Write a review whose recommendation follows from both achievement and criticism.", "Concession strengthens a recommendation when it is evidence-led.", "Make complexity readable.", ["external-ai-prompt", "worked-example", "extended-rationale"]),
  156: experience("grammar", "normal", "A compact register lesson prepares the learner to translate specialist material without deleting scope or uncertainty.", ["retrieval", "notice", "supported-practice", "meaningful-use"], "A public-clarity language workshop.", "Simplify a technical claim while retaining its limitation and implication.", "Readable language is not simpler thinking; it is clearer responsibility.", "Propose under pressure.", ["worked-example", "tip", "arabic-help"]),
  157: experience("real-world", "normal", "The deadline prompt makes conditional and contingency language functional under pressure.", ["orientation", "encounter", "meaningful-use", "retrieval"], "A rapid decision proposal.", "Recommend one action, state its condition, and define a contingency.", "A reversible plan is stronger than unsupported certainty.", "Argue for humility.", ["external-ai-prompt", "worked-example", "tip"]),
  158: experience("reading", "deep", "The epistemic-humility reading makes the relationship between confidence language and study design visible.", ["encounter", "notice", "evidence", "retrieval"], "An uncertainty-and-claim reading lab.", "Calibrate a public claim to the sample, comparison, and alternative explanations.", "Trust grows when confidence matches evidence.", "Enter the crowded debate.", ["word-support", "worked-example", "extended-rationale"]),
  159: experience("listening", "normal", "The crowded debate listening route asks the learner to hear weighting rules, dissent, and revision as parts of one intervention.", ["encounter", "notice", "supported-practice", "retrieval"], "A multi-stakeholder public-debate route.", "Track the position, weighting rule, dissent note, and review point.", "A public voice becomes credible when it remains revisable.", "Synthesis with integrity.", ["transcript", "worked-example", "arabic-help"]),
  160: experience("assessment", "deep", "The final C1 challenge transfers the whole programme into a source-aware, reversible, formally written judgement.", ["orientation", "retrieval", "encounter", "meaningful-use", "evidence", "next-bridge"], "A final conflicting-sources judgement challenge.", "Attribute sources, weigh unequal effects, preserve dissent, and recommend a reviewable action.", "C1 mastery joins methodological care with responsibility for consequences.", "Carry one evidence habit into C2.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_10_EXPERIENCES;
