import type { LessonActivity, ProgressiveSupport } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & {
  minutes: number;
  prompt?: string;
  promptArabic?: string;
  retrieval: { prompt: string; promptArabic: string; expectedEvidence: string; expectedEvidenceArabic: string };
  supports?: ProgressiveSupport[];
};

const specs: Record<number, Spec> = {
  113: {
    kind: "reading", title: "Read culture in motion", titleArabic: "اقرأ الثقافة وهي تتحرك", objective: "Distinguish cultural description from cultural judgement while tracing change across generations.", objectiveArabic: "ميّز بين وصف الثقافة والحكم عليها مع تتبع التغير عبر الأجيال.", stage: "introduction", semantic: "example", minutes: 26,
    readingText: "A community archive describes a market where older traders once negotiated prices face to face. A younger vendor now uses a phone and serves customers from several neighbourhoods. One commentator calls the change a loss of community; another calls it an expansion of access. The accounts describe real differences, but the judgement depends on which value the writer places first.", readingTextArabic: "يصف أرشيف مجتمعي سوقاً كان التجار الأكبر سناً يتفاوضون فيه وجهاً لوجه. أما البائع الأصغر سناً فيستخدم الهاتف الآن ويخدم زبائن من أحياء متعددة. يسمي أحد المعلقين التغير فقداناً للمجتمع؛ ويسميه آخر توسعاً في الوصول. تصف الروايتان اختلافات حقيقية، لكن الحكم يعتمد على القيمة التي يضعها الكاتب أولاً.",
    readingChecks: [{ id: "inference", type: "inference", prompt: "Why do the two commentators judge the same change differently?", promptArabic: "لماذا يحكم المعلقان على التغير نفسه بطريقة مختلفة؟", answer: "They prioritise different values when interpreting the change.", explanation: "The description can be shared while the evaluative frame differs." }],
    sentencePatterns: ["The account describes … without necessarily judging …", "The commentator foregrounds … because …", "A fair comparison should distinguish … from …"], retrieval: { prompt: "Retrieve the difference between describing a source and endorsing its judgement.", promptArabic: "استرجع الفرق بين وصف المصدر وتأييد حكمه.", expectedEvidence: "Description reports what is present; judgement evaluates it through a value or standard.", expectedEvidenceArabic: "يبلغ الوصف عما هو موجود؛ أما الحكم فيقيّمه من خلال قيمة أو معيار." }, supports: ["word-support", "arabic-help", "extended-rationale"],
  },
  114: {
    kind: "standard", title: "Limit the expert claim", titleArabic: "حدّد ادعاء الخبير", objective: "Qualify expertise claims by naming the domain, evidence boundary, and relevant concession.", objectiveArabic: "عاير ادعاءات الخبرة بذكر المجال وحدود الدليل والتنازل المناسب.", stage: "explanation", semantic: "grammar", minutes: 20,
    sentencePatterns: ["Within this field, the evidence supports …", "The specialist can establish …, but not …", "Although the analysis is authoritative on …, it does not settle …"], retrieval: { prompt: "Turn an earlier expert claim into a sentence that names its domain and limitation.", promptArabic: "حوّل ادعاء خبير سابق إلى جملة تذكر مجاله وحده.", expectedEvidence: "A domain marker, a support statement, and a clear boundary.", expectedEvidenceArabic: "محدد للمجال، وعبارة دعم، وحد واضح." }, supports: ["worked-example", "tip", "arabic-help"],
  },
  115: {
    kind: "listening", title: "Hear a review with consequences", titleArabic: "استمع إلى مراجعة لها تبعات", objective: "Identify how a reviewer balances achievement, limitation, and consequence without collapsing into praise or blame.", objectiveArabic: "حدد كيف يوازن المراجع بين الإنجاز والقيد والنتيجة دون التحول إلى مدح أو لوم.", stage: "guided-practice", semantic: "activity", minutes: 23,
    speakingLines: [{ id: "reviewer", speaker: "Reviewer", text: "The programme reached more learners than expected, although the evaluation did not follow those who stopped attending. That is a meaningful achievement, but the missing voices should shape the next review rather than disappear from it.", textArabic: "وصل البرنامج إلى متعلمين أكثر من المتوقع، رغم أن التقييم لم يتابع من توقفوا عن الحضور. وهذا إنجاز مهم، لكن ينبغي للأصوات الغائبة أن تشكل المراجعة التالية لا أن تختفي منها." }], sentencePatterns: ["The reviewer acknowledges … while noting …", "The missing voices matter because …", "The next review should therefore …"], supports: ["transcript", "worked-example"], retrieval: { prompt: "What is the difference between recognising an achievement and treating it as complete proof of success?", promptArabic: "ما الفرق بين الاعتراف بإنجاز واعتباره دليلاً كاملاً على النجاح؟", expectedEvidence: "Recognition can coexist with an evaluation boundary or missing evidence.", expectedEvidenceArabic: "يمكن أن يتعايش الاعتراف مع حد تقييمي أو دليل مفقود." },
  },
  116: {
    kind: "writing", title: "Make complexity readable", titleArabic: "اجعل التعقيد قابلاً للقراءة", objective: "Rewrite a specialist explanation for an informed public while preserving its uncertainty and causal limits.", objectiveArabic: "أعد كتابة شرح متخصص لجمهور عام مطلع مع الحفاظ على عدم اليقين وحدود السببية.", stage: "independent-practice", semantic: "activity", minutes: 31,
    prompt: "Write 240–300 words for a museum newsletter explaining why one survey result cannot describe every visitor. Define the method in accessible language, preserve one limitation, and end with a useful implication.", promptArabic: "اكتب 240–300 كلمة لنشرة متحف تشرح لماذا لا يستطيع استبيان واحد وصف كل زائر. عرّف الطريقة بلغة مفهومة، وحافظ على قيد واحد، وأنهِ بنتيجة مفيدة.", sentencePatterns: ["In simple terms, the survey measures …", "This result should not be read as …", "The practical implication is …"], retrieval: { prompt: "Retrieve one way to simplify language without simplifying away an important limitation.", promptArabic: "استرجع طريقة واحدة لتبسيط اللغة دون حذف قيد مهم.", expectedEvidence: "A plain-language definition followed by an explicit boundary.", expectedEvidenceArabic: "تعريف بلغة بسيطة يليه حد واضح." }, supports: ["worked-example", "external-ai-prompt", "extended-rationale"],
  },
  117: {
    kind: "interaction", title: "Defend a proposal under pressure", titleArabic: "دافع عن مقترح تحت الضغط", objective: "Respond to an urgent objection while keeping a conditional recommendation and safeguard visible.", objectiveArabic: "أجب عن اعتراض عاجل مع إبقاء التوصية المشروطة والضمانة واضحتين.", stage: "real-context", semantic: "activity", minutes: 24,
    interactionTurns: [{ id: "director", speaker: "Director", text: "If we add another consultation stage, the programme may miss the season when visitors are most interested.", textArabic: "إذا أضفنا مرحلة استشارة أخرى فقد يفوت البرنامج الموسم الذي يهتم فيه الزوار أكثر.", purpose: "State the timing objection." }, { id: "you", speaker: "You", text: "I accept the timing risk. I would begin a limited pilot now, but publish the consultation findings before making the full change permanent.", textArabic: "أقبل خطر التوقيت. سأبدأ تجربة محدودة الآن، لكنني سأنشر نتائج الاستشارة قبل جعل التغيير الكامل دائماً.", purpose: "Concede the risk and preserve a consultation safeguard." }], sentencePatterns: ["I accept the risk, but …", "The pilot should remain conditional on …", "A permanent change would require …"], retrieval: { prompt: "Retrieve a concession-plus-safeguard pattern and use it for a rushed public decision.", promptArabic: "استرجع نمط التنازل والضمانة واستخدمه لقرار عام متسرع.", expectedEvidence: "An acknowledged risk followed by a conditional safeguard.", expectedEvidenceArabic: "خطر معترف به يتبعه ضمان مشروط." }, supports: ["worked-example", "tip", "arabic-help"],
  },
  118: {
    kind: "reading", title: "Make the case against certainty", titleArabic: "قدّم الحجة ضد اليقين", objective: "Compare confidence, evidence, and uncertainty when a persuasive case exceeds what its sources establish.", objectiveArabic: "قارن بين الثقة والدليل وعدم اليقين عندما يتجاوز عرض مقنع ما تثبته مصادره.", stage: "guided-practice", semantic: "example", minutes: 27,
    readingText: "A national survey finds that visitors value local interpretation. A small interview study finds that some visitors prefer no explanation at all. The first source supports a broad pattern but cannot explain every preference; the second offers depth but cannot estimate prevalence. A confident policy can use both, provided it does not turn either into a universal rule.", readingTextArabic: "يجد استبيان وطني أن الزوار يقدّرون التفسير المحلي. وتجد دراسة مقابلات صغيرة أن بعض الزوار يفضلون عدم وجود شرح على الإطلاق. يدعم المصدر الأول نمطاً عاماً لكنه لا يستطيع تفسير كل تفضيل؛ ويقدم الثاني عمقاً لكنه لا يستطيع تقدير الانتشار. يمكن لسياسة واثقة أن تستخدم كليهما إذا لم تحول أياً منهما إلى قاعدة عامة.",
    readingChecks: [{ id: "method", type: "multiple-choice", prompt: "What limitation applies to the interview study?", promptArabic: "ما القيد الذي ينطبق على دراسة المقابلات؟", choices: ["It cannot estimate how common the preference is.", "It has no individual experiences.", "It proves the survey false."], answer: "It cannot estimate how common the preference is.", explanation: "Depth and prevalence answer different questions." }], sentencePatterns: ["The evidence supports a pattern, not …", "This source offers depth but cannot estimate …", "A cautious policy would …"], retrieval: { prompt: "State why two limited sources can still support a useful decision.", promptArabic: "اذكر لماذا يمكن لمصدرين محدودين أن يدعما قراراً مفيداً.", expectedEvidence: "They answer different questions and their limits remain explicit.", expectedEvidenceArabic: "يجيبان عن سؤالين مختلفين وتبقى حدودهما واضحة." }, supports: ["word-support", "worked-example", "extended-rationale"],
  },
  119: {
    kind: "listening", title: "Find a voice in the debate", titleArabic: "اعثر على صوت في النقاش", objective: "Track position, interruption, concession, and unresolved disagreement in a crowded debate.", objectiveArabic: "تتبع الموقف والمقاطعة والتنازل والاختلاف غير المحسوم في نقاش مزدحم.", stage: "guided-practice", semantic: "activity", minutes: 24,
    speakingLines: [{ id: "chair", speaker: "Chair", text: "We have heard a strong case for access, but we have not yet heard how the proposal affects the people who cannot use the new platform.", textArabic: "سمعنا حجة قوية للوصول، لكننا لم نسمع بعد كيف يؤثر المقترح في الأشخاص الذين لا يستطيعون استخدام المنصة الجديدة." }, { id: "designer", speaker: "Designer", text: "That is a fair challenge. I cannot promise equal uptake, but I can commit to a parallel offline route and a public review of its reach.", textArabic: "هذا اعتراض عادل. لا أستطيع أن أعد بإقبال متساوٍ، لكنني أستطيع الالتزام بمسار موازٍ دون اتصال ومراجعة عامة لمداه." }], sentencePatterns: ["The speaker concedes … but commits to …", "The unresolved question is …", "The proposed safeguard would …"], supports: ["transcript", "worked-example"], retrieval: { prompt: "Retrieve the difference between answering an objection and pretending it has disappeared.", promptArabic: "استرجع الفرق بين الإجابة عن اعتراض والتظاهر بأنه اختفى.", expectedEvidence: "A response can acknowledge an unresolved risk and offer a safeguard.", expectedEvidenceArabic: "يمكن للاستجابة أن تعترف بخطر غير محسوم وتقدم ضمانة." },
  },
  120: {
    kind: "assessment", title: "Synthesize with integrity", titleArabic: "ركّب الأفكار بنزاهة", objective: "Combine cultural, expert, and public perspectives while preserving attribution, uncertainty, and consequence.", objectiveArabic: "اجمع بين وجهات النظر الثقافية والخبرائية والعامة مع الحفاظ على الإسناد وعدم اليقين والنتيجة.", stage: "assessment", semantic: "assessment", minutes: 32,
    readingText: "A cultural centre's report celebrates wider attendance after a programme change. A curator's note warns that the new format reduced time for local interpretation. A visitor group accepts the broader reach but describes confusion among people who relied on the old orientation. The sources answer different questions: scale, curatorial depth, and user experience.", readingTextArabic: "يحتفل تقرير مركز ثقافي بزيادة الحضور بعد تغيير البرنامج. وتحذر مذكرة أمين المعرض من أن الشكل الجديد قلل وقت التفسير المحلي. وتقبل مجموعة زوار الاتساع الأكبر لكنها تصف ارتباكاً لدى من اعتمدوا على التوجيه القديم. تجيب المصادر عن أسئلة مختلفة: الحجم، والعمق، وتجربة المستخدم.", readingChecks: [{ id: "main", type: "main-idea", prompt: "What must an ethical synthesis keep distinct?", promptArabic: "ما الذي يجب أن يبقيه التركيب الأخلاقي متميزاً؟", answer: "Scale, curatorial depth, and user experience.", explanation: "The sources are complementary rather than interchangeable." }], prompt: "Write 220–280 words synthesising the three sources for a centre director. Attribute each perspective, state one uncertainty, and recommend one proportionate next step.", promptArabic: "اكتب 220–280 كلمة تركّب فيها المصادر الثلاثة لمدير المركز. انسب كل وجهة نظر، واذكر حالة عدم يقين، وأوصِ بخطوة تالية متناسبة.", sentencePatterns: ["The report indicates …, whereas the note cautions …", "Taken together, the accounts suggest …", "A proportionate next step would be …"], retrieval: { prompt: "Name the three evidence questions this checkpoint keeps separate.", promptArabic: "اذكر أسئلة الدليل الثلاثة التي يبقيها هذا الاختبار منفصلة.", expectedEvidence: "Scale, interpretation depth, and user experience.", expectedEvidenceArabic: "الحجم، وعمق التفسير، وتجربة المستخدم." }, supports: ["external-ai-prompt", "worked-example", "extended-rationale"],
  },
  121: {
    kind: "reading", title: "Read between the lines", titleArabic: "اقرأ بين السطور", objective: "Infer how framing, omission, and register shape the meaning of a public cultural text.", objectiveArabic: "استنتج كيف يشكل التأطير والحذف والسجل معنى نص ثقافي عام.", stage: "introduction", semantic: "example", minutes: 25,
    readingText: "A press release calls a cultural redesign an invitation to everyone. A staff memo describes reduced opening hours and fewer specialist sessions. The public wording foregrounds welcome; the internal wording foregrounds capacity. Neither text is necessarily dishonest, but their registers make different costs visible.", readingTextArabic: "يسمي بيان صحفي إعادة تصميم ثقافية دعوة للجميع. وتصف مذكرة للموظفين تقليص ساعات العمل وتقليل الجلسات المتخصصة. تبرز الصياغة العامة الترحيب؛ بينما تبرز الصياغة الداخلية القدرة المحدودة. ليس أي نص بالضرورة مخادعاً، لكن سجلهما يجعل تكاليف مختلفة مرئية.", readingChecks: [{ id: "inference", type: "inference", prompt: "What cost is omitted from the public wording?", promptArabic: "ما التكلفة المحذوفة من الصياغة العامة؟", answer: "Reduced access to hours and specialist sessions.", explanation: "The memo supplies the operational limitation missing from the invitation." }], sentencePatterns: ["The public register foregrounds … while omitting …", "A cautious inference is …", "The two texts differ in audience and …"], retrieval: { prompt: "Retrieve one way register can change what a reader notices without changing every fact.", promptArabic: "استرجع طريقة يمكن للسجل بها أن يغير ما يلاحظه القارئ دون تغيير كل الحقائق.", expectedEvidence: "Register selects emphasis, audience, and degree of explicitness.", expectedEvidenceArabic: "يحدد السجل التركيز والجمهور ودرجة التصريح." }, supports: ["word-support", "arabic-help", "extended-rationale"],
  },
  122: {
    kind: "reading", title: "Put the claim under scrutiny", titleArabic: "أخضع الادعاء للتدقيق", objective: "Test a claim by tracing provenance, method, scope, and alternative explanations.", objectiveArabic: "اختبر ادعاءً بتتبع المصدر والطريقة والنطاق والتفسيرات البديلة.", stage: "guided-practice", semantic: "example", minutes: 27,
    readingText: "A headline says that a new cultural app doubled engagement. The technical report counts visits to a landing page, while a follow-up survey reaches only users who completed the sign-up process. The headline may be directionally useful, but the available evidence cannot show whether occasional visitors became regular participants or whether the measure changed.", readingTextArabic: "يقول عنوان إن تطبيقاً ثقافياً جديداً ضاعف التفاعل. ويحسب التقرير التقني زيارات صفحة البداية، بينما يصل استبيان لاحق إلى المستخدمين الذين أكملوا التسجيل فقط. قد يكون العنوان مفيداً من حيث الاتجاه، لكن الدليل المتاح لا يبين ما إذا أصبح الزوار العرضيون مشاركين منتظمين أو ما إذا تغير المقياس.", readingChecks: [{ id: "method", type: "multiple-choice", prompt: "What cannot the evidence establish?", promptArabic: "ما الذي لا يستطيع الدليل إثباته؟", choices: ["Whether occasional visitors became regular participants.", "That visits were counted.", "That a survey was conducted."], answer: "Whether occasional visitors became regular participants.", explanation: "The measures show visits and selected survey responses, not sustained participation." }], sentencePatterns: ["The source establishes …, but not …", "The measure may overstate … because …", "An alternative explanation is …"], retrieval: { prompt: "Retrieve the four checks for a claim: provenance, method, scope, and what else?", promptArabic: "استرجع الفحوص الأربعة للادعاء: المصدر والطريقة والنطاق وماذا أيضاً؟", expectedEvidence: "The learner adds alternative explanations or counter-evidence.", expectedEvidenceArabic: "يضيف المتعلم التفسيرات البديلة أو الدليل المضاد." }, supports: ["word-support", "worked-example", "extended-rationale"],
  },
  123: {
    kind: "standard", title: "Use the language of uncertainty", titleArabic: "استخدم لغة عدم اليقين", objective: "Use stance adverbials and reporting verbs to express uncertainty precisely and usefully.", objectiveArabic: "استخدم ظروف الموقف وأفعال الإسناد للتعبير عن عدم اليقين بدقة وفائدة.", stage: "explanation", semantic: "grammar", minutes: 20,
    sentencePatterns: ["The available evidence appears to indicate …", "The authors cautiously attribute … to …", "It would be premature to conclude …"], retrieval: { prompt: "Turn one overconfident sentence from the scrutiny lesson into a calibrated statement.", promptArabic: "حوّل جملة واثقة أكثر من اللازم من درس التدقيق إلى عبارة معايرة.", expectedEvidence: "A stance phrase or reporting verb plus a specific limitation.", expectedEvidenceArabic: "عبارة موقف أو فعل إسناد مع قيد محدد." }, supports: ["worked-example", "tip", "arabic-help"],
  },
  124: {
    kind: "listening", title: "When sources disagree", titleArabic: "عندما تختلف المصادر", objective: "Compare conflicting speakers and identify what each source can legitimately establish.", objectiveArabic: "قارن بين متحدثين مختلفين وحدد ما يستطيع كل مصدر إثباته بصورة مشروعة.", stage: "guided-practice", semantic: "activity", minutes: 24,
    speakingLines: [{ id: "historian", speaker: "Historian", text: "The attendance figures suggest wider reach, but they say little about whether the programme changed understanding.", textArabic: "تشير أرقام الحضور إلى وصول أوسع، لكنها لا تقول الكثير عن ما إذا كان البرنامج قد غير الفهم." }, { id: "educator", speaker: "Educator", text: "The interviews reveal deeper engagement for some learners, although we cannot treat those accounts as a measure of everyone.", textArabic: "تكشف المقابلات عن تفاعل أعمق لدى بعض المتعلمين، رغم أننا لا نستطيع التعامل مع تلك الروايات كمقياس للجميع." }], sentencePatterns: ["Speaker A can establish …, whereas Speaker B can show …", "Neither source can establish …", "A transparent report should …"], retrieval: { prompt: "State why the two speakers should not be forced into one winner.", promptArabic: "اذكر لماذا لا ينبغي إجبار المتحدثين على اختيار فائز واحد.", expectedEvidence: "They answer different questions and have different limits.", expectedEvidenceArabic: "يجيبان عن سؤالين مختلفين ولهما حدود مختلفة." }, supports: ["transcript", "worked-example", "tip"],
  },
  125: {
    kind: "writing", title: "Write a conclusion, not a slogan", titleArabic: "اكتب خلاصة لا شعاراً", objective: "Produce a proportionate conclusion that acknowledges an objection and names a review trigger.", objectiveArabic: "اكتب خلاصة متناسبة تعترف باعتراض وتذكر شرطاً للمراجعة.", stage: "guided-practice", semantic: "activity", minutes: 30,
    prompt: "Write 240–300 words advising a cultural board on a proposed digital exhibition. State what the evidence supports, concede one access concern, and specify what result would make you revise the recommendation.", promptArabic: "اكتب 240–300 كلمة تنصح فيها مجلساً ثقافياً بشأن معرض رقمي مقترح. اذكر ما يدعمه الدليل، واعترف بقلق يتعلق بالوصول، وحدد نتيجة ستجعلك تراجع التوصية.", sentencePatterns: ["The evidence supports …, although …", "I recommend … subject to …", "This recommendation should be revisited if …"], retrieval: { prompt: "Retrieve the difference between a conclusion and a slogan.", promptArabic: "استرجع الفرق بين الخلاصة والشعار.", expectedEvidence: "A conclusion connects evidence to action and includes a condition for revision.", expectedEvidenceArabic: "تربط الخلاصة الدليل بالفعل وتتضمن شرطاً للمراجعة." }, supports: ["worked-example", "external-ai-prompt", "extended-rationale"],
  },
  126: {
    kind: "reading", title: "Hold a public issue close", titleArabic: "اقترب من قضية عامة", objective: "Connect public policy to unequal personal experience without treating one account as universal proof.", objectiveArabic: "اربط السياسة العامة بتجربة شخصية غير متساوية دون اعتبار رواية واحدة دليلاً شاملاً.", stage: "guided-practice", semantic: "example", minutes: 27,
    readingText: "A city describes its new ticketing system as convenient. A caregiver explains that the nearest assisted machine is now farther away, while a student says the mobile app made late travel easier. These accounts do not settle the overall impact, but they show why an average convenience score can hide different burdens.", readingTextArabic: "تصف مدينة نظام التذاكر الجديد بأنه مريح. ويشرح مقدم رعاية أن أقرب آلة مساعدة أصبحت أبعد، بينما يقول طالب إن التطبيق سهّل السفر المتأخر. لا تحسم هذه الروايات الأثر العام، لكنها تبين لماذا قد يخفي متوسط الراحة أعباء مختلفة.", readingChecks: [{ id: "main", type: "main-idea", prompt: "What do the personal accounts add to the average score?", promptArabic: "ماذا تضيف الروايات الشخصية إلى المتوسط؟", answer: "They reveal unequal burdens and benefits hidden by the average.", explanation: "Personal accounts make distribution visible without proving overall prevalence." }], sentencePatterns: ["The account illustrates … without proving …", "The average may conceal …", "A fair evaluation should combine …"], retrieval: { prompt: "Retrieve the difference between using an anecdote as an illustration and using it as universal proof.", promptArabic: "استرجع الفرق بين استخدام الحكاية للتوضيح واستخدامها دليلاً شاملاً.", expectedEvidence: "An anecdote can reveal a possible burden while not measuring its prevalence.", expectedEvidenceArabic: "قد تكشف الحكاية عبئاً محتملاً دون أن تقيس انتشاره." }, supports: ["word-support", "arabic-help", "extended-rationale"],
  },
  127: {
    kind: "interaction", title: "Question the ethics of convenience", titleArabic: "ساءل أخلاقيات السهولة", objective: "Use counterfactual and consequence language to test whether convenience justifies an avoidable unequal cost.", objectiveArabic: "استخدم لغة الشرط والنتيجة لاختبار ما إذا كانت السهولة تبرر تكلفة غير متساوية يمكن تجنبها.", stage: "real-context", semantic: "activity", minutes: 24,
    interactionTurns: [{ id: "manager", speaker: "Manager", text: "The automated route is faster for most users, so the assisted route can be removed.", textArabic: "المسار الآلي أسرع لمعظم المستخدمين، لذلك يمكن إزالة المسار المساعد.", purpose: "State the convenience argument." }, { id: "you", speaker: "You", text: "If the assisted route were removed, people who need it would pay the largest cost for a convenience designed for others. I would retain it and review its use rather than remove it unseen.", textArabic: "إذا أزيل المسار المساعد فسيدفع من يحتاجون إليه أكبر تكلفة من أجل راحة صممت لغيرهم. سأبقيه وأراجع استخدامه بدلاً من إزالته دون ملاحظة.", purpose: "Use a counterfactual and propose a reviewable safeguard." }], sentencePatterns: ["If … were removed, … would …", "The benefit is distributed …, whereas the cost falls on …", "I would retain … subject to …"], retrieval: { prompt: "Retrieve one counterfactual that exposes who bears an unintended cost.", promptArabic: "استرجع شرطاً يكشف من يتحمل تكلفة غير مقصودة.", expectedEvidence: "A conditional sentence linking a design change to a group-specific consequence.", expectedEvidenceArabic: "جملة شرطية تربط تغيير التصميم بنتيجة تخص مجموعة معينة." }, supports: ["worked-example", "arabic-help", "tip"],
  },
  128: {
    kind: "assessment", title: "Move beyond a single story", titleArabic: "تجاوز الرواية الواحدة", objective: "Evaluate a fresh cultural dossier and defend a reviewable recommendation that preserves competing perspectives.", objectiveArabic: "قيّم ملفاً ثقافياً جديداً ودافع عن توصية قابلة للمراجعة تحافظ على وجهات النظر المتنافسة.", stage: "assessment", semantic: "assessment", minutes: 40,
    readingText: "A cultural institution's annual report celebrates a new programme for bringing more people through the door. A specialist review praises the reach but questions whether local histories were reduced to short labels. A visitor account describes feeling welcomed yet unable to recognise their community's complexity. A funding memo recommends keeping the format because it is efficient. The board must decide how to expand access without turning efficiency into the only definition of success.", readingTextArabic: "يحتفل التقرير السنوي لمؤسسة ثقافية ببرنامج جديد أدخل أشخاصاً أكثر عبر الأبواب. وتشيد مراجعة متخصصة بالوصول لكنها تتساءل عما إذا كانت التواريخ المحلية قد اختزلت إلى عبارات قصيرة. وتصف رواية زائر شعوره بالترحيب لكنه لم يستطع التعرف إلى تعقيد مجتمعه. وتوصي مذكرة تمويل بالإبقاء على الشكل لأنه فعال. على المجلس أن يقرر كيف يوسع الوصول دون تحويل الكفاءة إلى التعريف الوحيد للنجاح.", readingChecks: [{ id: "source", type: "detail", prompt: "Which source questions the reduction of local histories?", promptArabic: "أي مصدر يشكك في اختزال التواريخ المحلية؟", answer: "The specialist review.", explanation: "It examines curatorial depth rather than only attendance." }, { id: "inference", type: "inference", prompt: "What tension must the board address?", promptArabic: "ما التوتر الذي يجب على المجلس معالجته؟", answer: "Wider access and efficiency must be balanced with local complexity and representation.", explanation: "The dossier presents benefits and costs that cannot be reduced to one measure." }], prompt: "Write a 360–440 word formal recommendation to the cultural institution. Attribute at least three sources, distinguish what each can establish, acknowledge one uncertainty, explain an unequal consequence, and propose one concrete review trigger.", promptArabic: "اكتب توصية رسمية من 360–440 كلمة للمؤسسة الثقافية. انسب ثلاثة مصادر على الأقل، وميز ما يستطيع كل مصدر إثباته، واعترف بحالة عدم يقين، واشرح نتيجة غير متساوية، واقترح شرط مراجعة ملموساً.", sentencePatterns: ["The annual report establishes …, whereas the review cautions …", "The visitor account illustrates … without proving …", "I therefore recommend … subject to review if …"], retrieval: { prompt: "Before the assessment, retrieve the five Module 8 moves: describe, limit, compare, humanise, and review.", promptArabic: "قبل التقييم، استرجع حركات الوحدة الخمس: صف، وحدد، وقارن، وأنسن، وراجع.", expectedEvidence: "The learner names all five moves and connects them to a concrete writing action.", expectedEvidenceArabic: "يسمي المتعلم الحركات الخمس ويربطها بفعل كتابي ملموس." }, supports: ["external-ai-prompt", "extended-rationale", "worked-example"],
  },
};

function buildActivity(lessonNumber: number, spec: Spec): LessonActivity {
  const { minutes, retrieval, supports, prompt, promptArabic, ...activity } = spec;
  return { ...activity, id: `c1-module-8-${lessonNumber}`, estimatedMinutes: minutes, ...(prompt ? { writingPrompt: prompt, writingPromptArabic: promptArabic } : {}), retrievalCheck: retrieval, progressiveSupports: supports ?? ["arabic-help", "word-support"] };
}

export const C1_MODULE_8_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([lessonNumber, spec]) => [Number(lessonNumber), [buildActivity(Number(lessonNumber), spec)]]));
export default C1_MODULE_8_ACTIVITIES;
