import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_4_EXPERIENCES: Record<number, LessonExperience> = {
  49: experience("reading", "deep", "The module opens by separating explicit claims from persuasive assumptions, giving the learner a disciplined entry into contested evidence.", ["orientation", "encounter", "notice", "evidence"], "A source-reading studio about public claims.", "Mark the explicit claim, the hidden assumption, and the consequence of accepting it.", "An argument can sound certain while depending on an untested premise.", "Compare how the same issue is framed for different audiences.", ["word-support", "arabic-help", "extended-rationale"]),
  50: experience("notice", "normal", "A paired-frame comparison makes audience and emphasis visible before the learner studies attribution language.", ["retrieval", "notice", "meaningful-use"], "A two-source framing comparison.", "Underline what each source foregrounds and explain which audience each frame serves.", "Different frames can describe one event without using the same decision question.", "Attribute a source before agreeing with it.", ["worked-example", "tip"]),
  51: experience("grammar", "normal", "Reporting verbs are taught as a precision tool for separating evidence ownership from the learner's own judgement.", ["retrieval", "notice", "supported-practice"], "An attribution language workshop.", "Revise sentences so the source, the claim, and your evaluation remain distinct.", "Attribution protects both accuracy and intellectual honesty.", "Hear how a briefing marks confidence.", ["worked-example", "tip", "arabic-help"]),
  52: experience("listening", "normal", "The audio route makes confidence and provisional causation audible, with transcript disclosure reserved for verification.", ["encounter", "notice", "retrieval"], "An audio evidence briefing.", "Listen twice for the claim, then for the boundary between compatibility and proof.", "The listener must hear uncertainty rather than erase it.", "Ask a speaker for method evidence.", ["transcript", "worked-example"]),
  53: experience("interaction", "normal", "Focused questions turn source criticism into a practical committee skill without requiring a full debate performance.", ["retrieval", "meaningful-use"], "A method-question exchange.", "Ask one question about the measure, one about selection, and one about independent corroboration.", "A precise question can test a claim without attacking the person.", "Audit a paired dossier.", ["worked-example", "tip"]),
  54: experience("review", "deep", "The dossier review consolidates claim, framing, evidence, and attribution before the module moves into method comparison.", ["retrieval", "notice", "evidence"], "A paired-source audit.", "Record what each source establishes, how it frames the issue, and what evidence is missing.", "Evidence appraisal is a chain of decisions, not a single credibility label.", "Compare methods rather than rhetorical volume.", ["word-support", "arabic-help", "extended-rationale"]),
  55: experience("reading", "deep", "Method comparison raises the level from what a source says to what its design can legitimately support.", ["encounter", "notice", "evidence"], "A breadth-and-depth methods reading.", "Compare sample, measure, scope, and limitation before deciding what each source can establish.", "A confident tone cannot repair a method that cannot answer the question.", "Calibrate conflicting forecasts.", ["word-support", "worked-example", "extended-rationale"]),
  56: experience("listening", "normal", "Forecast language gives the learner a second audio encounter with probability, range, and editorial overstatement.", ["encounter", "notice", "meaningful-use"], "A briefing on competing forecasts.", "Track the difference between likely, planned, and inevitable.", "Probability words change the strength and responsibility of a public claim.", "Qualify a recommendation without losing its point.", ["transcript", "worked-example", "tip"]),
  57: experience("writing", "deep", "The writing route is bounded around one qualified position so advanced prose grows through control rather than overload.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A qualified policy paragraph.", "Write a position with one concession, two calibrated claims, one limitation, and one action.", "Qualification should make a recommendation more defensible, not less useful.", "Classify the kind of disagreement in a committee exchange.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  58: experience("interaction", "normal", "The committee exchange separates factual, value, and data disagreements before the learner drafts a short brief.", ["retrieval", "meaningful-use"], "A disagreement-classification meeting.", "Name which part is factual, which reflects values, and which requires more data.", "Not every disagreement can be solved by adding more vocabulary or more confidence.", "Write the mini-brief.", ["worked-example", "tip"]),
  59: experience("writing", "normal", "The mini-brief creates a short synthesis checkpoint with a single proportionate action and a defined next evidence need.", ["retrieval", "meaningful-use", "evidence"], "A municipal advisory mini-brief.", "Compare two sources, state one limitation, recommend one action, and specify the next data need.", "A useful brief makes its uncertainty actionable.", "Trace provenance and possible bias.", ["worked-example", "external-ai-prompt"]),
  60: experience("reading", "deep", "Provenance analysis introduces source accountability without asking the learner to infer misconduct from incomplete information.", ["encounter", "notice", "evidence"], "A provenance and corroboration reading.", "Mark the disclosed interest, the missing comparison, and the claim that remains possible but unproven.", "Responsible scepticism names questions rather than inventing conclusions.", "Represent a stakeholder fairly.", ["word-support", "arabic-help", "extended-rationale"]),
  61: experience("listening", "normal", "A stakeholder audio route develops fair representation and prevents the public briefing from becoming an abstract evidence exercise.", ["encounter", "notice", "meaningful-use"], "A stakeholder meeting extract.", "Listen for the accepted goal, the burden described, and the requested adjustment.", "Representing a position accurately is not the same as endorsing it.", "Draft the executive recommendation.", ["transcript", "worked-example", "tip"]),
  62: experience("writing", "deep", "The executive recommendation connects appraisal, stakeholder impact, a modest pilot, and explicit review conditions.", ["retrieval", "meaningful-use", "evidence"], "A formal committee recommendation.", "Write the recommendation and a short assumptions-and-data annex.", "A policy proposal earns trust by showing how it can be checked and revised.", "Defend the recommendation under challenge.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  63: experience("speaking", "normal", "The speaking rehearsal asks the learner to defend a qualified recommendation orally and answer one principled challenge.", ["retrieval", "meaningful-use", "next-bridge"], "A committee defence rehearsal.", "State the recommendation, answer why action can precede certainty, and name the safeguard.", "A reversible, monitored pilot is a different claim from an irreversible rollout.", "Transfer the process to a new contested policy.", ["worked-example", "tip"]),
  64: experience("assessment", "deep", "The capstone transfers the entire source-aware decision process to a new dossier and audience without packing every routine into earlier lessons.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A public-committee source synthesis challenge.", "Identify claims, appraise evidence, acknowledge impact, recommend proportionate action, and explain one audience choice.", "C1 judgement is accurate, calibrated, audience-aware, and open to revision.", "Record one transferable evidence skill before Module 5.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_4_EXPERIENCES;
