import type { LessonActivity } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & { minutes: number; prompt?: string; promptArabic?: string };

const specs: Record<number, Spec> = {
  81: { kind: "reading", title: "Read between the lines", titleArabic: "اقرأ ما بين السطور", objective: "Identify implication and framing across two sources about urban greening.", objectiveArabic: "حدّد الإيحاء والتأطير عبر مصدرين عن تخضير المدن.", stage: "introduction", semantic: "example", minutes: 24, readingText: "A feature praises tree-lined streets as a shared investment, while a budget note describes the same plan as a redistribution of maintenance costs. Neither source states its priorities openly; word choice reveals whose benefits and burdens are foregrounded.", readingTextArabic: "يمدح مقال الشوارع المشجرة بوصفها استثماراً مشتركاً، بينما تصف مذكرة الميزانية الخطة نفسها بأنها إعادة توزيع لتكاليف الصيانة. لا يصرّح أي مصدر بأولوياته علناً؛ بل تكشف الكلمات منافع من تُبرز وأعباء من تُحمّل.", sentencePatterns: ["The source frames the issue as …", "This implication is suggested by …", "A cautious attribution would be …"] },
  82: { kind: "reading", title: "Put a claim under scrutiny", titleArabic: "أخضع الادعاء للتدقيق", objective: "Compare the methods behind competing evidence before accepting a contested claim.", objectiveArabic: "قارن بين منهجيات الأدلة المتنافسة قبل قبول ادعاء متنازع عليه.", stage: "guided-practice", semantic: "example", minutes: 25, readingText: "One report compares treated districts with a national average; another follows matched districts over time. The headline conclusion is similar, but the second design better addresses local change. Method does not settle every question, yet it changes how confidently the claim can travel.", readingTextArabic: "يقارن أحد التقريرين المناطق المعالجة بمتوسط وطني، بينما يتابع الآخر مناطق مماثلة عبر الزمن. تبدو الخلاصة الرئيسية متشابهة، لكن التصميم الثاني يعالج التغير المحلي بصورة أفضل. لا تحسم المنهجية كل سؤال، لكنها تغير مدى الثقة التي يمكن أن ينتقل بها الادعاء.", sentencePatterns: ["The stronger comparison is … because …", "The evidence supports … but does not establish …", "Methodological caution is necessary when …"] },
  83: { kind: "standard", title: "Calibrate uncertainty", titleArabic: "عاير درجة اليقين", objective: "Express probabilistic claims with language proportionate to the evidence.", objectiveArabic: "عبّر عن الادعاءات الاحتمالية بلغة تتناسب مع الدليل.", stage: "explanation", semantic: "grammar", minutes: 19, sentencePatterns: ["The evidence is consistent with …", "It is plausible, though not certain, that …", "The estimate should be interpreted as …"] },
  84: { kind: "listening", title: "When sources disagree", titleArabic: "عندما تختلف المصادر", objective: "Extract disagreement, omission, and confidence from a spoken policy briefing.", objectiveArabic: "استخرج الاختلاف والحذف ودرجة الثقة من إحاطة سياسات مسموعة.", stage: "guided-practice", semantic: "activity", minutes: 22, speakingLines: [{ id: "analyst", speaker: "Analyst", text: "The two reports cannot both be read as a definitive account. One captures short-term change; the other questions whether the comparison is fair.", textArabic: "لا يمكن قراءة التقريرين معاً بوصفهما وصفاً نهائياً. يرصد أحدهما التغير قصير الأجل، بينما يشكك الآخر في عدالة المقارنة." }], sentencePatterns: ["The analyst gives more weight to … because …", "The disagreement concerns … rather than …", "A responsible briefing would acknowledge …"] },
  85: { kind: "writing", title: "Reach a conclusion, not a slogan", titleArabic: "توصل إلى خلاصة لا شعار", objective: "Write a proportionate conclusion that concedes a plausible objection and recommends one measured action.", objectiveArabic: "اكتب خلاصة متناسبة تعترف باعتراض معقول وتوصي بإجراء متزن واحد.", stage: "guided-practice", semantic: "grammar", minutes: 30, prompt: "Write 220–280 words advising a council on a proportional congestion charge. State what the evidence supports, concede one objection, and recommend one reviewable action.", promptArabic: "اكتب 220–280 كلمة تنصح فيها مجلساً بشأن رسوم ازدحام متناسبة. اذكر ما يدعمه الدليل، واعترف باعتراض واحد، وأوصِ بإجراء واحد قابل للمراجعة.", sentencePatterns: ["On balance, the evidence suggests …", "A reasonable objection is …", "I nevertheless recommend …"] },
  86: { kind: "reading", title: "Hear the public issue", titleArabic: "استمع إلى القضية العامة", objective: "Combine technical evidence with first-hand testimony without collapsing one into the other.", objectiveArabic: "اجمع بين الدليل التقني والشهادة المباشرة دون اختزال أحدهما في الآخر.", stage: "real-context", semantic: "example", minutes: 24, readingText: "The technical note reports fewer delays; residents describe longer journeys for people who cannot change their working hours. The accounts answer different questions. A fair proposal preserves the measurable result while asking who pays the adjustment cost.", readingTextArabic: "تسجل المذكرة الفنية تأخيرات أقل؛ بينما يصف السكان رحلات أطول لمن لا يستطيعون تغيير ساعات عملهم. تجيب الروايتان عن سؤالين مختلفين. ويحافظ المقترح العادل على النتيجة القابلة للقياس مع التساؤل عمن يدفع تكلفة التكيف.", sentencePatterns: ["The testimony adds … to the technical finding.", "The unequal burden falls on …", "A balanced response would …"] },
  87: { kind: "standard", title: "Question convenience", titleArabic: "ساءل الراحة", objective: "Use counterfactual conditionals to evaluate a convenient technology’s consent and responsibility risks.", objectiveArabic: "استخدم الشرطيات الافتراضية لتقييم مخاطر الموافقة والمسؤولية في تقنية مريحة.", stage: "explanation", semantic: "grammar", minutes: 20, sentencePatterns: ["If consent were genuinely informed, …", "Had the service disclosed …, users might …", "Convenience would not justify … unless …"] },
  88: { kind: "reading", title: "Challenge the single story", titleArabic: "تحدَّ السردية الواحدة", objective: "Synthesize multiple perspectives on representation and propose a respectful programme change.", objectiveArabic: "ركّب وجهات نظر متعددة حول التمثيل واقترح تغييراً محترماً في البرنامج.", stage: "independent-practice", semantic: "example", minutes: 26, readingText: "A museum statement celebrates inclusion through one headline exhibition. A community statement notes that the same artists were invited only after the programme was fixed. The disagreement is not solved by choosing a side; it requires examining who had decision-making power.", readingTextArabic: "يحتفي بيان المتحف بالشمول عبر معرض رئيسي واحد. ويشير بيان مجتمعي إلى أن الفنانين أنفسهم دُعوا فقط بعد تثبيت البرنامج. لا يُحل الاختلاف باختيار طرف؛ بل بفحص من امتلك سلطة اتخاذ القرار.", sentencePatterns: ["The central representational gap is …", "The sources converge on … but differ about …", "A respectful reform would …"] },
  89: { kind: "listening", title: "What counts as progress?", titleArabic: "ما الذي يُعد تقدماً؟", objective: "Distinguish competing indicators and infer the trade-off a speaker is making.", objectiveArabic: "ميّز بين مؤشرات متنافسة واستنتج المفاضلة التي يجريها المتحدث.", stage: "guided-practice", semantic: "activity", minutes: 23, speakingLines: [{ id: "director", speaker: "Development director", text: "A single growth figure is easy to communicate, but a composite measure may reveal whether the gains are shared.", textArabic: "يسهل إيصال رقم نمو واحد، لكن المقياس المركب قد يكشف ما إذا كانت المكاسب مشتركة." }], sentencePatterns: ["The speaker values … but recognises …", "The indicator would conceal …", "A defensible strategy would combine …"] },
  90: { kind: "writing", title: "Count the cost of a decision", titleArabic: "احسب تكلفة القرار", objective: "Write a formal proposal that anticipates an unintended effect and specifies mitigation.", objectiveArabic: "اكتب مقترحاً رسمياً يتوقع أثراً غير مقصود ويحدد تخفيفاً له.", stage: "independent-practice", semantic: "grammar", minutes: 32, prompt: "Write 280–340 words advising a council on shifting resources from acute care to early intervention. Weigh two sources, predict one knock-on effect, and specify a mitigation measure.", promptArabic: "اكتب 280–340 كلمة تنصح فيها مجلساً بنقل موارد من الرعاية الحادة إلى التدخل المبكر. وازن بين مصدرين، وتوقع أثراً متتابعاً واحداً، وحدد إجراء تخفيف.", sentencePatterns: ["The reallocation could yield …, although …", "The principal unintended effect may be …", "This could be mitigated by …"] },
  91: { kind: "interaction", title: "Design for disagreement", titleArabic: "صمّم للاختلاف", objective: "Propose a deliberative forum while diplomatically anticipating counterarguments.", objectiveArabic: "اقترح منتدى تداولياً مع توقع الاعتراضات دبلوماسياً.", stage: "real-context", semantic: "activity", minutes: 24, interactionTurns: [{ id: "stakeholder", speaker: "Stakeholder", text: "A forum may simply give opponents another stage without changing the plan.", textArabic: "قد يمنح المنتدى المعارضين منصة أخرى دون أن يغير الخطة.", purpose: "Anticipate a counterargument." }, { id: "you", speaker: "You", text: "That risk is real unless the process gives participants a defined decision point and publishes how their evidence was handled.", textArabic: "هذا الخطر حقيقي ما لم تمنح العملية المشاركين نقطة قرار محددة وتنشر كيفية التعامل مع أدلتهم.", purpose: "Answer with a design safeguard." }] },
  92: { kind: "reading", title: "Translate expertise for a public", titleArabic: "ترجم الخبرة للجمهور", objective: "Recast specialist evidence for a public audience without removing essential limitations.", objectiveArabic: "أعد صياغة الدليل المتخصص لجمهور عام دون حذف القيود الأساسية.", stage: "real-context", semantic: "example", minutes: 25, readingText: "The technical report describes a confidence interval and a sensitivity analysis. The public summary calls the result reliable but explains neither term. A trustworthy translation keeps the practical meaning and states what could still change.", readingTextArabic: "يصف التقرير الفني فترة ثقة وتحليلاً للحساسية. وتصف الخلاصة العامة النتيجة بأنها موثوقة دون شرح أي من المصطلحين. وتحافظ الترجمة الجديرة بالثقة على المعنى العملي وتذكر ما قد يتغير.", sentencePatterns: ["In practical terms, this means …", "The limitation remains that …", "The public version should avoid saying …"] },
  93: { kind: "review", title: "Retrieve the evidence moves", titleArabic: "استرجع حركات الدليل", objective: "Retrieve calibrated comparison, attribution, and mitigation language in a new policy scenario.", objectiveArabic: "استرجع لغة المقارنة والنسب والتخفيف الدقيقة في سيناريو سياسات جديد.", stage: "review", semantic: "retrieval", minutes: 18, sentencePatterns: ["The source indicates … rather than proves …", "This interpretation is attributable to …", "The risk could be reduced by …"] },
  94: { kind: "speaking", title: "Give the public judgement", titleArabic: "قدّم الحكم العام", objective: "Deliver a two-minute recommendation that separates evidence, judgement, and next action.", objectiveArabic: "قدّم توصية مدتها دقيقتان تفصل بين الدليل والحكم والإجراء التالي.", stage: "independent-practice", semantic: "activity", minutes: 24, speakingLines: [{ id: "chair", speaker: "Committee chair", text: "What should we approve, what should we monitor, and what would make you revise the recommendation?", textArabic: "ماذا ينبغي أن نوافق عليه، وماذا ينبغي أن نراقب، وما الذي سيجعلك تراجع التوصية؟" }, { id: "you", speaker: "You", text: "I recommend … because … . I would monitor … . I would revise this if … .", textArabic: "أوصي بـ … لأن … . وسأراقب … . وسأراجع ذلك إذا … ." }] },
  95: { kind: "writing", title: "Draft the source-aware proposal", titleArabic: "اكتب المقترح الواعي بالمصادر", objective: "Produce a formal proposal that balances competing perspectives and preserves uncertainty.", objectiveArabic: "أنتج مقترحاً رسمياً يوازن بين وجهات النظر المتنافسة ويحافظ على عدم اليقين.", stage: "independent-practice", semantic: "grammar", minutes: 34, prompt: "Write 300–360 words proposing a monitored public intervention. Synthesize two sources, state one uncertainty, answer one objection, and define a review trigger.", promptArabic: "اكتب 300–360 كلمة تقترح فيها تدخلاً عاماً مراقباً. ركّب مصدرين، واذكر عدم يقين واحداً، وأجب عن اعتراض واحد، وحدد محفزاً للمراجعة.", sentencePatterns: ["Taken together, the sources …", "This recommendation should not be read as …", "The review should be triggered when …"] },
  96: { kind: "assessment", title: "Public judgement checkpoint", titleArabic: "نقطة تحقق: الحكم العام", objective: "Synthesize implication, uncertainty, disagreement, lived experience, and proposal design in one defensible public recommendation.", objectiveArabic: "ركّب الإيحاء وعدم اليقين والاختلاف والتجربة المعاشة وتصميم المقترح في توصية عامة يمكن الدفاع عنها.", stage: "assessment", semantic: "assessment", minutes: 36, prompt: "Prepare a 340–400 word source-aware proposal and a two-minute spoken briefing for a public committee. Distinguish findings from inferences, include one counterargument, and define a safeguard and review condition.", promptArabic: "حضّر مقترحاً واعياً بالمصادر من 340–400 كلمة وإحاطة شفهية مدتها دقيقتان للجنة عامة. ميّز بين النتائج والاستنتاجات، وأدرج اعتراضاً واحداً، وحدد ضمانة وشرط مراجعة.", sentencePatterns: ["The evidence establishes …, while the inference is …", "The strongest objection is …", "Approval should be conditional on …"] },
};

const check = (lesson: number): LessonActivity["retrievalCheck"] => ({
  prompt: `Before leaving, state the public-judgement move from Lesson ${lesson} in one precise English sentence.`,
  promptArabic: `قبل المغادرة، اذكر حركة الحكم العام من الدرس ${lesson} في جملة إنجليزية دقيقة واحدة.`,
  expectedEvidence: "A concise, qualified English sentence that applies the lesson's evidence, uncertainty, or deliberation move.",
  expectedEvidenceArabic: "جملة إنجليزية موجزة ومقيدة تطبق حركة الدليل أو عدم اليقين أو التداول في الدرس.",
});
const supports = (_lesson: number): NonNullable<LessonActivity["progressiveSupports"]> => ["worked-example", "tip", "external-ai-prompt"];

export const c1Module6AuthoredActivities: Record<number, LessonActivity[]> = Object.fromEntries(
  Object.entries(specs).map(([lesson, spec]) => {
    const lessonNumber = Number(lesson);
    return [lessonNumber, [{ ...spec, id: `c1-module-6-${lessonNumber}`, estimatedMinutes: spec.minutes, retrievalCheck: check(lessonNumber), progressiveSupports: supports(lessonNumber), ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}) }]];
  }),
) as Record<number, LessonActivity[]>;

export default c1Module6AuthoredActivities;

