import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_9_EXPERIENCES: Record<number, LessonExperience> = {
  129: experience("reading", "deep", "The module opens with competing progress indicators so the learner must choose a measure without confusing aggregate success with lived distribution.", ["orientation", "encounter", "notice", "evidence", "retrieval"], "A progress-metrics reading studio.", "Compare the dashboard with the community evidence and recommend a reviewable measure.", "A headline number is not the same as an equitable outcome.", "Count the cost of a decision.", ["word-support", "arabic-help", "extended-rationale"]),
  130: experience("reading", "deep", "The allocation case makes trade-offs concrete and asks who benefits, who bears a cost, and which safeguard can be tested.", ["retrieval", "encounter", "notice", "evidence"], "A public-budget trade-off lab.", "Name the benefit, burden, and mitigation before recommending a mixed pilot.", "Efficiency becomes responsible only when its distribution is visible.", "Design disagreement well.", ["worked-example", "tip", "arabic-help"]),
  131: experience("interaction", "normal", "A distrustful resident forces the learner to design an accountable process rather than defend consultation as a label.", ["orientation", "encounter", "meaningful-use", "retrieval"], "A deliberation-design interaction.", "Acknowledge distrust, publish criteria, and make the response process answerable.", "Participation is credible when people can see what their input changes.", "Read an argument with a memory.", ["worked-example", "arabic-help", "tip"]),
  132: experience("reading", "deep", "The historical case prevents the learner from turning a complicated precedent into a universal slogan.", ["encounter", "notice", "evidence", "retrieval"], "A precedent-and-memory reading.", "Separate historical conditions from the present claim before transferring a lesson.", "A precedent disciplines judgement only when its conditions remain visible.", "Follow culture in motion.", ["word-support", "extended-rationale", "arabic-help"]),
  133: experience("reading", "deep", "Three audiences frame one cultural change differently, making register and value selection visible.", ["retrieval", "notice", "supported-practice", "evidence"], "A culture-and-framing reading studio.", "Mark which value and audience each source foregrounds, then adapt a balanced account.", "Framing changes what a public reader notices first.", "Limit the expert voice.", ["word-support", "worked-example", "arabic-help"]),
  134: experience("grammar", "normal", "A focused attribution lab gives the learner a reusable syntax for expert claims, boundaries, and provisional conclusions.", ["retrieval", "notice", "supported-practice", "meaningful-use"], "An expert-claim calibration workshop.", "Attribute the source, name its domain, and prevent an overgeneralised conclusion.", "Trust grows when expertise does not pretend to answer every question.", "Hear a review with consequences.", ["worked-example", "tip", "arabic-help"]),
  135: experience("listening", "normal", "The review briefing makes achievement and limitation audible while withholding the transcript until after first listening.", ["encounter", "notice", "retrieval"], "A consequence-aware review briefing.", "Listen for the gain, the missing evidence, and the consequence for the next review.", "A positive result can still require a narrower claim.", "Make complexity readable.", ["transcript", "worked-example", "arabic-help"]),
  136: experience("writing", "deep", "The writing studio converts technical material into public clarity without deleting the method or its uncertainty.", ["retrieval", "meaningful-use", "evidence"], "A public-brief writing studio.", "Explain one measure plainly, retain a limitation, and recommend a proportionate next step.", "Readable language is responsible when it preserves what the evidence cannot establish.", "Propose under pressure.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  137: experience("real-world", "normal", "The urgent committee exchange makes conditional proposal language useful under a real time constraint.", ["orientation", "encounter", "meaningful-use", "retrieval"], "A deadline-driven proposal dilemma.", "Concede urgency while preserving a safeguard and a condition for expansion.", "A limited action can be more accountable than a confident leap.", "Argue against certainty.", ["worked-example", "tip", "arabic-help"]),
  138: experience("reading", "deep", "The overstated word unquestionably gives the learner a visible test of how grammar can outrun evidence.", ["encounter", "notice", "evidence", "retrieval"], "An epistemic-humility reading lab.", "Compare the claim's certainty with the survey design and rewrite it with calibrated force.", "Useful uncertainty is precise about both confidence and limitation.", "Speak into a crowded debate.", ["word-support", "worked-example", "extended-rationale"]),
  139: experience("listening", "normal", "A multi-voice debate requires the learner to hear a position, a stakeholder concern, and a safeguard without reducing the exchange to winners and losers.", ["encounter", "notice", "supported-practice", "retrieval"], "A crowded public-debate listening route.", "Track the main position, overlooked stakeholder, and review question.", "A defensible voice makes room for the concern that could change its design.", "Synthesize with integrity.", ["transcript", "worked-example", "arabic-help"]),
  140: experience("integration", "deep", "The ten-lesson checkpoint asks the learner to combine measurement, distribution, attribution, and review in a formal judgement.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A progress-and-consequence synthesis checkpoint.", "Attribute four sources, identify an evidence gap, and propose a conditional next step.", "Integrity keeps an aggregate gain and an unequal burden in the same frame.", "Read between the lines.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  141: experience("reading", "deep", "The official release demonstrates how universal language and missing participation data can shape a reader's inference.", ["encounter", "notice", "evidence", "retrieval"], "An implication-and-omission reading studio.", "Identify what is foregrounded, what is absent, and what the omission can legitimately suggest.", "An unanswered question limits a conclusion without proving a motive.", "Scrutinise the claim.", ["word-support", "arabic-help", "extended-rationale"]),
  142: experience("reading", "deep", "Comparing a controlled trial with interviews moves the learner from source ranking to method-question matching.", ["retrieval", "notice", "supported-practice", "evidence"], "A methods-and-scope scrutiny lab.", "Match each source to the question it can answer and combine their complementary limits.", "The strongest source depends on the question being asked.", "Use the language of uncertainty.", ["worked-example", "tip", "arabic-help"]),
  143: experience("grammar", "normal", "The uncertainty workshop turns probabilistic meaning into precise, usable proposal language rather than vague hedging.", ["retrieval", "notice", "supported-practice", "meaningful-use"], "A calibrated-probability language lab.", "Replace an absolute claim with a confidence phrase and an evidence-based reason.", "Uncertainty is informative when the reason and degree are visible.", "When sources disagree.", ["worked-example", "tip", "arabic-help"]),
  144: experience("assessment", "deep", "The fresh development dossier transfers the entire module from metrics and methods to an accountable recommendation with a review trigger.", ["orientation", "retrieval", "encounter", "meaningful-use", "evidence", "next-bridge"], "A conflicting-sources public decision challenge.", "Attribute sources, expose a gap, represent uncertainty, explain who bears the consequence, and recommend a reviewable action.", "C1 judgement combines methodological care, calibrated language, and responsibility for unequal effects.", "Carry one evidence habit into the next module.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_9_EXPERIENCES;
