import type { LessonActivity, ProgressiveSupport } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & {
  minutes: number;
  prompt?: string;
  promptArabic?: string;
  retrieval: { prompt: string; promptArabic: string; expectedEvidence: string; expectedEvidenceArabic: string };
  supports?: ProgressiveSupport[];
};

const specs: Record<number, Spec> = {
  145: { kind: "reading", title: "Name the invisible cost", titleArabic: "سمِّ التكلفة غير المرئية", objective: "Interpret how a public proposal distributes benefits and burdens beyond its headline outcome.", objectiveArabic: "فسّر كيف يوزّع المقترح العام المنافع والأعباء خارج نتيجته الرئيسية.", stage: "introduction", semantic: "example", minutes: 27,
    readingText: "A new library is celebrated for serving more visitors each month. A quieter account notes that the old branch closed during construction, that carers now travel farther, and that evening access was reduced for staff reasons. The project may still be worthwhile, but its public story is incomplete unless the people paying the transition cost are visible.", readingTextArabic: "يُحتفى بمكتبة جديدة لأنها تخدم زواراً أكثر كل شهر. لكن رواية أهدأ تذكر أن الفرع القديم أُغلق أثناء البناء، وأن مقدمي الرعاية يسافرون الآن مسافة أطول، وأن الوصول المسائي انخفض لأسباب تتعلق بالموظفين. قد يظل المشروع جديراً، لكن قصته العامة ناقصة ما لم يظهر من يدفع تكلفة الانتقال.",
    readingChecks: [{ id: "burden", type: "inference", prompt: "Why is the public story incomplete?", promptArabic: "لماذا تظل القصة العامة ناقصة؟", answer: "It celebrates aggregate reach while hiding who bears the transition costs.", explanation: "A conclusion becomes more responsible when it names both beneficiaries and affected groups." }], sentencePatterns: ["The proposal benefits …, while shifting … onto …", "The headline result does not reveal …", "A fairer account would include …"], retrieval: { prompt: "Retrieve the difference between a headline benefit and a distributed burden.", promptArabic: "استرجع الفرق بين المنفعة الرئيسية والعبء الموزّع.", expectedEvidence: "A headline benefit is an aggregate gain; a distributed burden shows which people absorb the cost.", expectedEvidenceArabic: "المنفعة الرئيسية مكسب إجمالي؛ أما العبء الموزّع فيُظهر من يتحمل التكلفة." }, supports: ["word-support", "arabic-help", "extended-rationale"] },
  146: { kind: "standard", title: "Turn evidence into proportion", titleArabic: "حوّل الدليل إلى تناسب", objective: "Use abstract noun phrases and precise contextualisation to express causal and evaluative nuance.", objectiveArabic: "استخدم العبارات الاسمية المجردة والتحديد السياقي للتعبير عن السببية والتقييم بدقة.", stage: "explanation", semantic: "grammar", minutes: 22,
    sentencePatterns: ["The expansion of … has resulted in … within …", "The significance of … depends on …", "This outcome should be interpreted in light of …"], retrieval: { prompt: "Reframe a simple claim about a policy as a proportionate claim with context.", promptArabic: "أعد صياغة ادعاء بسيط عن سياسة في صورة ادعاء متناسب مع السياق.", expectedEvidence: "A nominalised process, a bounded context, and a conclusion that avoids universal wording.", expectedEvidenceArabic: "عملية مصاغة اسمياً، وسياق محدد، واستنتاج يتجنب التعميم." }, supports: ["worked-example", "tip", "arabic-help"] },
  147: { kind: "interaction", title: "Question the convenient choice", titleArabic: "اسأل عن الخيار المريح", objective: "Evaluate a technological convenience choice using counterfactual reasoning and ethical conditionals.", objectiveArabic: "قيّم خياراً تقنياً مريحاً باستخدام التفكير الافتراضي والشروط الأخلاقية.", stage: "real-context", semantic: "activity", minutes: 26,
    interactionTurns: [{ id: "product", speaker: "Product lead", text: "The default setting saves people time. Asking for consent at every step would make the service feel slow.", textArabic: "الإعداد الافتراضي يوفر وقت الناس. طلب الموافقة في كل خطوة سيجعل الخدمة بطيئة.", purpose: "Frame convenience as the decisive value." }, { id: "reviewer", speaker: "Reviewer", text: "It may be convenient, but if the data reveals sensitive habits, speed should not replace meaningful choice. We could test a clear opt-in route before scaling.", textArabic: "قد يكون مريحاً، لكن إذا كشفت البيانات عادات حساسة فلا ينبغي للسرعة أن تحل محل الاختيار الحقيقي. يمكننا اختبار مسار موافقة واضح قبل التوسع.", purpose: "Introduce an ethical condition and a reversible safeguard." }], sentencePatterns: ["If the data were …, convenience would not justify …", "The choice would be defensible provided that …", "Before scaling, we should test whether …"], retrieval: { prompt: "Retrieve the structure of an ethical conditional.", promptArabic: "استرجع بنية الشرط الأخلاقي.", expectedEvidence: "A stated condition, its ethical consequence, and a safeguard or test.", expectedEvidenceArabic: "شرط واضح ونتيجته الأخلاقية وضمان أو اختبار." }, supports: ["worked-example", "arabic-help", "tip"] },
  148: { kind: "reading", title: "Challenge a single story", titleArabic: "تحدَّ القصة الواحدة", objective: "Synthesize multiple representations into a respectful critique that makes an alternative visible.", objectiveArabic: "ركّب تمثيلات متعددة في نقد محترم يجعل البديل مرئياً.", stage: "guided-practice", semantic: "example", minutes: 29,
    readingText: "A campaign presents one neighbourhood as a place of need and rescue. Local artists describe mutual aid, humour, and skilled organising that existed before the campaign arrived. Neither account should be treated as the whole truth. The critique is strongest when it shows how the first story narrows agency and then documents what residents already do.", readingTextArabic: "تقدم حملة حياً واحداً بوصفه مكاناً للحاجة والإنقاذ. ويصف فنانون محليون المساعدة المتبادلة والفكاهة والتنظيم الماهر الذي كان موجوداً قبل وصول الحملة. لا ينبغي اعتبار أي رواية الحقيقة كاملة. يكون النقد أقوى عندما يوضح كيف تضيق الرواية الأولى مساحة الفاعلية ثم يوثق ما يفعله السكان أصلاً.",
    readingChecks: [{ id: "agency", type: "inference", prompt: "What does the alternative account restore?", promptArabic: "ماذا تعيد الرواية البديلة؟", answer: "It restores residents' agency, existing knowledge, and collective action.", explanation: "Respectful critique changes the frame without inventing a perfect counter-story." }], sentencePatterns: ["The first account foregrounds … but obscures …", "A more complete representation would acknowledge …", "This critique challenges … without dismissing …"], retrieval: { prompt: "Retrieve how to challenge a public representation respectfully.", promptArabic: "استرجع كيفية تحدي تمثيل عام باحترام.", expectedEvidence: "Name the framing choice, show what it omits, and support an alternative with evidence.", expectedEvidenceArabic: "سمِّ خيار التأطير، وأظهر ما يغفله، وادعم بديلاً بالدليل." }, supports: ["word-support", "extended-rationale", "arabic-help"] },
  149: { kind: "reading", title: "Ask what progress means", titleArabic: "اسأل ماذا يعني التقدم", objective: "Compare competing progress metrics and recommend a transparent combination of indicators.", objectiveArabic: "قارن مؤشرات التقدم المتنافسة وأوصِ بمزيج شفاف من المقاييس.", stage: "guided-practice", semantic: "example", minutes: 28,
    readingText: "A minister cites productivity growth as proof of progress. A public-health team cites reduced waiting time, while a workers' group asks whether the gains are shared. The metrics are not enemies: they answer different questions. A credible dashboard should state its purpose, publish disaggregated results, and explain which trade-offs remain unresolved.", readingTextArabic: "يستشهد وزير بنمو الإنتاجية دليلاً على التقدم. ويستشهد فريق الصحة العامة بانخفاض وقت الانتظار، بينما تسأل مجموعة عمالية عما إذا كانت المكاسب مشتركة. ليست المقاييس أعداء؛ فهي تجيب عن أسئلة مختلفة. ينبغي للوحة الموثوقة أن توضح غرضها، وتنشر نتائج مفصلة، وتشرح المفاضلات التي لم تُحسم.",
    readingChecks: [{ id: "dashboard", type: "main-idea", prompt: "What makes a dashboard credible?", promptArabic: "ما الذي يجعل لوحة المؤشرات موثوقة؟", answer: "A stated purpose, disaggregated results, and transparent unresolved trade-offs.", explanation: "Transparency includes limits, not only attractive numbers." }], sentencePatterns: ["This indicator is useful for … but insufficient for …", "The dashboard should disaggregate …", "The unresolved trade-off concerns …"], retrieval: { prompt: "Retrieve two safeguards against using one metric as total progress.", promptArabic: "استرجع ضمانين ضد استخدام مقياس واحد بوصفه التقدم كله.", expectedEvidence: "State the purpose of the metric and add disaggregated or lived-experience evidence.", expectedEvidenceArabic: "اذكر غرض المقياس وأضف دليلاً مفصلاً أو دليلاً من التجربة المعيشة." }, supports: ["word-support", "worked-example", "arabic-help"] },
  150: { kind: "writing", title: "Map the cost of a decision", titleArabic: "ارسم تكلفة القرار", objective: "Write a concise formal proposal that anticipates allocation consequences and mitigation.", objectiveArabic: "اكتب مقترحاً رسمياً موجزاً يتوقع نتائج توزيع الموارد وإجراءات التخفيف.", stage: "independent-practice", semantic: "activity", minutes: 32, prompt: "Write 250–320 words for a committee deciding whether to fund a visible central service or a smaller mobile alternative. Explain the gain, the burden, the group affected, and one mitigation with a review trigger.", promptArabic: "اكتب 250–320 كلمة للجنة تقرر تمويل خدمة مركزية ظاهرة أو بديل متنقل أصغر. اشرح المكسب والعبء والمجموعة المتأثرة وإجراء تخفيف واحد مع شرط مراجعة.", sentencePatterns: ["The allocation would improve … but may impose …", "The risk is concentrated among …", "I recommend … subject to …"], retrieval: { prompt: "Retrieve the four moves for a responsible allocation proposal.", promptArabic: "استرجع الحركات الأربع لمقترح توزيع مسؤول.", expectedEvidence: "Name the gain, burden, affected group, and mitigation or review trigger.", expectedEvidenceArabic: "اذكر المكسب والعبء والمجموعة المتأثرة وإجراء التخفيف أو شرط المراجعة." }, supports: ["external-ai-prompt", "worked-example", "extended-rationale"] },
  151: { kind: "interaction", title: "Make disagreement usable", titleArabic: "اجعل الاختلاف مفيداً", objective: "Design a deliberation process using hedged persuasion and diplomatic rebuttal.", objectiveArabic: "صمّم عملية مداولة باستخدام الإقناع المتحفظ والرد الدبلوماسي.", stage: "real-context", semantic: "activity", minutes: 26,
    interactionTurns: [{ id: "chair", speaker: "Chair", text: "We should avoid reopening the question; disagreement will only delay the decision.", textArabic: "ينبغي ألا نعيد فتح السؤال؛ فالاختلاف لن يؤدي إلا إلى تأخير القرار.", purpose: "Treat disagreement as an obstacle." }, { id: "facilitator", speaker: "Facilitator", text: "I see the need for a decision. A short evidence round could still reveal which condition would make the proposal acceptable to those who bear the cost.", textArabic: "أفهم الحاجة إلى قرار. ومع ذلك يمكن لجولة أدلة قصيرة أن تكشف الشرط الذي يجعل المقترح مقبولاً لمن يتحملون التكلفة.", purpose: "Reframe disagreement as decision-relevant evidence." }], sentencePatterns: ["I can see why …; nevertheless, …", "A limited review would allow us to …", "The proposal becomes more credible if …"], retrieval: { prompt: "Retrieve one way deliberation improves a decision rather than merely delaying it.", promptArabic: "استرجع طريقة واحدة تجعل المداولة القرار أفضل لا أبطأ فقط.", expectedEvidence: "It identifies conditions, evidence gaps, or safeguards that change the decision's design.", expectedEvidenceArabic: "تحدد شروطاً أو فجوات دليل أو ضمانات تغيّر تصميم القرار." }, supports: ["worked-example", "arabic-help", "tip"] },
  152: { kind: "reading", title: "Use memory without myth", titleArabic: "استخدم الذاكرة دون أسطورة", objective: "Evaluate historical claims and connect precedent, interpretation, and contemporary consequence.", objectiveArabic: "قيّم الادعاءات التاريخية واربط السابقة بالتفسير والنتيجة المعاصرة.", stage: "guided-practice", semantic: "example", minutes: 29,
    readingText: "A speech invokes a former reform as proof that bold central action always succeeds. A historian agrees that the reform widened access but notes its coercive implementation and the later correction that made the gains durable. The precedent is valuable only when its achievement, cost, and changed conditions are carried together into the present.", readingTextArabic: "يستدعي خطاب إصلاحاً سابقاً دليلاً على أن العمل المركزي الجريء ينجح دائماً. ويوافق مؤرخ على أن الإصلاح وسّع الوصول لكنه يذكر تنفيذه القسري والتصحيح اللاحق الذي جعل المكاسب مستدامة. لا تكون السابقة مفيدة إلا عندما تُنقل إنجازاتها وتكلفتها والظروف المتغيرة معاً إلى الحاضر.",
    readingChecks: [{ id: "memory", type: "inference", prompt: "Why is the later correction important?", promptArabic: "لماذا كان التصحيح اللاحق مهماً؟", answer: "It helped make the original gains durable and changes what the precedent teaches.", explanation: "Historical learning includes the repair that followed an intervention." }], sentencePatterns: ["The precedent is instructive insofar as …", "Its achievement came with …", "The present context differs because …"], retrieval: { prompt: "Retrieve the three parts of a responsible historical reference.", promptArabic: "استرجع الأجزاء الثلاثة للإشارة التاريخية المسؤولة.", expectedEvidence: "Achievement, cost or limitation, and the changed condition affecting transfer.", expectedEvidenceArabic: "الإنجاز والتكلفة أو القيد والظرف المتغير الذي يؤثر في النقل." }, supports: ["word-support", "extended-rationale", "arabic-help"] },
  153: { kind: "listening", title: "Reframe culture in motion", titleArabic: "أعد تأطير الثقافة المتحركة", objective: "Track metaphor, qualification, and register shifts in a discussion about cultural change.", objectiveArabic: "تتبّع الاستعارة والمعايرة وتبدّل الأسلوب في نقاش عن التغير الثقافي.", stage: "guided-practice", semantic: "activity", minutes: 24,
    speakingLines: [{ id: "curator", speaker: "Curator", text: "The festival is not a museum piece; it is a living language that changes when new speakers enter it.", textArabic: "المهرجان ليس قطعة في متحف؛ بل هو لغة حية تتغير عندما يدخلها متحدثون جدد." }, { id: "elder", speaker: "Elder", text: "That metaphor is helpful, provided that change does not become an excuse to discard the memory that gives the event its meaning.", textArabic: "هذه الاستعارة مفيدة بشرط ألا يصبح التغير ذريعة للتخلص من الذاكرة التي تمنح الحدث معناه." }], sentencePatterns: ["The metaphor foregrounds … while qualifying …", "For a public brief, I would replace … with …", "Change need not mean … provided that …"], retrieval: { prompt: "Retrieve how qualification protects a cultural argument from overstatement.", promptArabic: "استرجع كيف تحمي المعايرة حجة ثقافية من المبالغة.", expectedEvidence: "It narrows the claim and states the condition under which change remains acceptable.", expectedEvidenceArabic: "تضيّق الادعاء وتذكر الشرط الذي يبقى فيه التغير مقبولاً." }, supports: ["transcript", "worked-example", "arabic-help"] },
  154: { kind: "reading", title: "Limit expertise responsibly", titleArabic: "حدّد الخبرة بمسؤولية", objective: "Evaluate expert claims, domain boundaries, and the uncertainty that remains for decision-makers.", objectiveArabic: "قيّم ادعاءات الخبراء وحدود المجال وعدم اليقين المتبقي لصانعي القرار.", stage: "guided-practice", semantic: "example", minutes: 28,
    readingText: "An engineer can estimate the structural risk of a bridge, but cannot alone decide whether a community should accept the relocation needed to build it. A social researcher can describe displacement patterns, but cannot certify the bridge's load capacity. Responsible advice attributes each claim to the field that can support it and marks the judgement that still belongs to the public.", readingTextArabic: "يستطيع مهندس تقدير الخطر الإنشائي لجسر، لكنه لا يستطيع وحده أن يقرر ما إذا كان ينبغي لمجتمع قبول الانتقال اللازم لبنائه. ويستطيع باحث اجتماعي وصف أنماط الإزاحة، لكنه لا يستطيع اعتماد قدرة الجسر على التحمل. تنسب النصيحة المسؤولة كل ادعاء إلى المجال الذي يستطيع دعمه وتحدد الحكم الذي لا يزال ملكاً للجمهور.",
    readingChecks: [{ id: "domain", type: "main-idea", prompt: "What boundary does responsible advice mark?", promptArabic: "ما الحد الذي تضعه النصيحة المسؤولة؟", answer: "It separates technical expertise from the public value judgement that remains to be made.", explanation: "Expertise informs a decision; it does not automatically settle its ethical meaning." }], sentencePatterns: ["The specialist is well placed to assess …, whereas …", "This evidence should inform … but not determine …", "The remaining judgement concerns …"], retrieval: { prompt: "Retrieve the difference between expert evidence and public judgement.", promptArabic: "استرجع الفرق بين دليل الخبير والحكم العام.", expectedEvidence: "Expert evidence answers a bounded technical question; public judgement weighs values and consequences.", expectedEvidenceArabic: "يجيب دليل الخبير عن سؤال تقني محدود؛ أما الحكم العام فيزن القيم والنتائج." }, supports: ["word-support", "arabic-help", "extended-rationale"] },
  155: { kind: "writing", title: "Write a review that changes action", titleArabic: "اكتب مراجعة تغيّر الفعل", objective: "Synthesize achievement, criticism, concession, and recommendation in a consequential review.", objectiveArabic: "ركّب الإنجاز والنقد والتنازل والتوصية في مراجعة ذات أثر.", stage: "independent-practice", semantic: "activity", minutes: 31, prompt: "Write 260–330 words reviewing a public programme. Acknowledge one measurable gain, identify one evidence limitation, concede a legitimate counterpoint, and recommend a proportionate change.", promptArabic: "اكتب 260–330 كلمة تراجع فيها برنامجاً عاماً. اعترف بمكسب قابل للقياس، وحدد قيداً في الدليل، واذكر نقطة مضادة مشروعة، وأوصِ بتغيير متناسب.", sentencePatterns: ["The programme has achieved …, although …", "This criticism is valid insofar as …", "I therefore recommend … rather than …"], retrieval: { prompt: "Retrieve the balance between criticism and concession in a review.", promptArabic: "استرجع التوازن بين النقد والتنازل في المراجعة.", expectedEvidence: "Name a real achievement, accept a valid criticism, and let the recommendation follow the evidence.", expectedEvidenceArabic: "اذكر إنجازاً حقيقياً واقبل نقداً صحيحاً واجعل التوصية ناتجة عن الدليل." }, supports: ["external-ai-prompt", "worked-example", "extended-rationale"] },
  156: { kind: "standard", title: "Make complexity readable", titleArabic: "اجعل التعقيد مقروءاً", objective: "Control information structure when translating specialist material for a mixed public audience.", objectiveArabic: "اضبط بنية المعلومات عند تحويل مادة متخصصة لجمهور عام متنوع.", stage: "explanation", semantic: "grammar", minutes: 23,
    sentencePatterns: ["In plain terms, this means …", "The technical finding is limited to …", "For readers deciding …, the practical implication is …"], retrieval: { prompt: "Simplify a specialist claim without deleting its limitation.", promptArabic: "بسّط ادعاءً متخصصاً دون حذف قيده.", expectedEvidence: "A plain-language restatement that retains scope, uncertainty, and practical implication.", expectedEvidenceArabic: "إعادة صياغة بلغة واضحة تحافظ على النطاق وعدم اليقين والأثر العملي." }, supports: ["worked-example", "tip", "arabic-help"] },
  157: { kind: "writing", title: "Propose under pressure", titleArabic: "اقترح تحت الضغط", objective: "Defend a course of action quickly while stating conditions and contingency measures.", objectiveArabic: "دافع بسرعة عن مسار عمل مع ذكر الشروط وإجراءات الطوارئ.", stage: "independent-practice", semantic: "activity", minutes: 30, prompt: "Write 250–320 words for a decision-maker who must act this week. Recommend one course, state the condition that makes it defensible, and define a contingency if the evidence moves against it.", promptArabic: "اكتب 250–320 كلمة لصانع قرار يجب أن يتصرف هذا الأسبوع. أوصِ بمسار واحد، واذكر الشرط الذي يجعله قابلاً للدفاع، وحدد إجراءً بديلاً إذا اتجه الدليل ضده.", sentencePatterns: ["Given the time constraint, I recommend …", "This is defensible provided that …", "If the early evidence shows …, we should …"], retrieval: { prompt: "Retrieve the proposal-under-pressure structure.", promptArabic: "استرجع بنية المقترح تحت الضغط.", expectedEvidence: "A recommendation, a condition, and a contingency tied to observable evidence.", expectedEvidenceArabic: "توصية وشرط وإجراء بديل مرتبط بدليل قابل للملاحظة." }, supports: ["external-ai-prompt", "worked-example", "tip"] },
  158: { kind: "reading", title: "Argue for humility", titleArabic: "جادل من أجل التواضع المعرفي", objective: "Interrogate contested claims and control layered hedges and boosters in public communication.", objectiveArabic: "افحص الادعاءات المتنازع عليها واضبط درجات التحفظ والتوكيد في التواصل العام.", stage: "guided-practice", semantic: "example", minutes: 29,
    readingText: "A commentator calls a pilot unquestionably successful after one favourable month. The evaluation team says the result is encouraging but provisional: the sample is small, the comparison group changed, and seasonal effects remain possible. Public trust is not protected by sounding certain; it is protected by matching the language of confidence to the evidence available.", readingTextArabic: "يصف معلق تجربة بأنها ناجحة بلا شك بعد شهر إيجابي واحد. ويقول فريق التقييم إن النتيجة مشجعة لكنها مؤقتة: العينة صغيرة، ومجموعة المقارنة تغيرت، ولا تزال التأثيرات الموسمية ممكنة. لا تُحمى الثقة العامة بإظهار اليقين؛ بل بمواءمة لغة الثقة مع الدليل المتاح.",
    readingChecks: [{ id: "certainty", type: "inference", prompt: "Why is unquestionably too strong?", promptArabic: "لماذا تُعد كلمة بلا شك قوية أكثر من اللازم؟", answer: "The evidence is small, provisional, and exposed to alternative explanations.", explanation: "Layered qualification keeps a claim useful without making it evasive." }], sentencePatterns: ["The result is encouraging, but it does not yet establish …", "It is highly likely that …, although …", "The claim should be weakened because …"], retrieval: { prompt: "Retrieve when to use a hedge instead of a booster.", promptArabic: "استرجع متى تستخدم التحفظ بدلاً من التوكيد.", expectedEvidence: "Use a hedge when scope, sample, comparison, or alternative explanations limit confidence.", expectedEvidenceArabic: "استخدم التحفظ عندما يحد النطاق أو العينة أو المقارنة أو التفسيرات البديلة من الثقة." }, supports: ["word-support", "extended-rationale", "arabic-help"] },
  159: { kind: "listening", title: "Enter the crowded debate", titleArabic: "ادخل النقاش المزدحم", objective: "Foreground a defensible position and guide mixed stakeholders through a cohesive argument.", objectiveArabic: "قدّم موقفاً يمكن الدفاع عنه وقُد أصحاب المصلحة المختلفين خلال حجة متماسكة.", stage: "real-context", semantic: "activity", minutes: 26,
    speakingLines: [{ id: "moderator", speaker: "Moderator", text: "Every group says its evidence should decide the matter. The committee needs more than a louder voice; it needs a rule for weighing relevance, reliability, and consequence.", textArabic: "تقول كل مجموعة إن دليلها يجب أن يحسم الأمر. تحتاج اللجنة إلى أكثر من صوت أعلى؛ إنها تحتاج إلى قاعدة لوزن الصلة والموثوقية والنتيجة." }, { id: "speaker", speaker: "Speaker", text: "I recommend a transparent weighting rule, a published dissent note, and a review date so that today's judgement remains open to better evidence.", textArabic: "أوصي بقاعدة وزن شفافة ومذكرة اختلاف منشورة وموعد مراجعة حتى يبقى حكم اليوم منفتحاً على دليل أفضل." }], sentencePatterns: ["The central question is not … but …", "I would give greater weight to … because …", "This judgement should remain open to …"], retrieval: { prompt: "Retrieve the three moves that make a public intervention reviewable.", promptArabic: "استرجع الحركات الثلاث التي تجعل التدخل العام قابلاً للمراجعة.", expectedEvidence: "State a weighting rule, make disagreement visible, and set a review point.", expectedEvidenceArabic: "اذكر قاعدة للوزن، واجعل الاختلاف مرئياً، وحدد نقطة للمراجعة." }, supports: ["transcript", "worked-example", "arabic-help"] },
  160: { kind: "assessment", title: "Synthesis with integrity", titleArabic: "التركيب بنزاهة", objective: "Integrate multiple sources into an original judgement and formal proposal with precise attribution and flexible register.", objectiveArabic: "ادمج مصادر متعددة في حكم أصيل ومقترح رسمي مع إسناد دقيق وأسلوب مرن.", stage: "assessment", semantic: "assessment", minutes: 44,
    readingText: "A city report claims that a new service has improved access. A community account shows that the benefit is uneven and that one group now bears a hidden cost. An expert note explains what the available method can estimate but warns that it cannot settle the value question. A historical comparison offers a useful precedent but also records a correction that changed the outcome. The decision-maker must recommend a course while preserving uncertainty, dissent, and the possibility of revision.", readingTextArabic: "يدعي تقرير للمدينة أن خدمة جديدة حسنت الوصول. وتظهر رواية مجتمعية أن المنفعة غير متساوية وأن مجموعة واحدة تتحمل الآن تكلفة خفية. وتشرح مذكرة خبير ما يستطيع المنهج المتاح تقديره لكنها تحذر من أنه لا يستطيع حسم سؤال القيمة. وتقدم مقارنة تاريخية سابقة مفيدة لكنها تسجل أيضاً تصحيحاً غيّر النتيجة. يجب على صانع القرار أن يوصي بمسار مع الحفاظ على عدم اليقين والاختلاف وإمكانية المراجعة.",
    readingChecks: [{ id: "synthesis", type: "main-idea", prompt: "What must the final proposal preserve?", promptArabic: "ما الذي يجب أن يحافظ عليه المقترح النهائي؟", answer: "The aggregate gain, uneven cost, expert limits, historical qualification, dissent, and revision route.", explanation: "Integrity is a structure for making a judgement answerable, not a refusal to decide." }, { id: "attribution", type: "inference", prompt: "Why should the sources not be collapsed into one claim?", promptArabic: "لماذا لا ينبغي دمج المصادر في ادعاء واحد؟", answer: "Each source answers a different question and has different authority and limits.", explanation: "Precise attribution protects the boundary between evidence and judgement." }], prompt: "Write a 380–460-word formal proposal for a mixed committee. Attribute at least four sources, distinguish aggregate benefit from distributional cost, state what the expert method can and cannot establish, use a qualified historical comparison, represent dissent, and recommend a reversible action with a concrete review trigger.", promptArabic: "اكتب مقترحاً رسمياً من 380–460 كلمة للجنة متنوعة. انسب أربعة مصادر على الأقل، وميّز بين المنفعة الإجمالية والتكلفة التوزيعية، واذكر ما يستطيع منهج الخبير إثباته وما لا يستطيع، واستخدم مقارنة تاريخية معايرة، ومثّل الاختلاف، وأوصِ بفعل قابل للعكس مع شرط مراجعة ملموس.", sentencePatterns: ["The report establishes …, whereas …", "The expert evidence is relevant to … but cannot determine …", "I recommend … subject to a review of …"], retrieval: { prompt: "Retrieve the final C1 synthesis sequence: measure, distribute, attribute, qualify, deliberate, revise.", promptArabic: "استرجع تسلسل تركيب C1 النهائي: قِس، ووزّع، وانسب، وعاير، وتداول، وراجع.", expectedEvidence: "The learner applies all six moves to a source-aware proposal rather than listing them in isolation.", expectedEvidenceArabic: "يطبق المتعلم الحركات الست كلها على مقترح واعٍ بالمصادر بدلاً من سردها منفصلة." }, supports: ["external-ai-prompt", "extended-rationale", "worked-example"] },
};

function buildActivity(lessonNumber: number, spec: Spec): LessonActivity {
  const { minutes, retrieval, supports, prompt, promptArabic, ...activity } = spec;
  return { ...activity, id: `c1-module-10-${lessonNumber}`, estimatedMinutes: minutes, ...(prompt ? { writingPrompt: prompt, writingPromptArabic: promptArabic } : {}), retrievalCheck: retrieval, progressiveSupports: supports ?? ["arabic-help", "word-support"] };
}

export const C1_MODULE_10_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([lessonNumber, spec]) => [Number(lessonNumber), [buildActivity(Number(lessonNumber), spec)]]));
export default C1_MODULE_10_ACTIVITIES;
