import type { LessonActivity } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & { minutes: number; prompt?: string; promptArabic?: string };

const specs: Record<number, Spec> = {
  17: { kind: "standard", title: "Read the room of an institution", titleArabic: "اقرأ سياق المؤسسة", objective: "Distinguish a formal institutional position from a personal recommendation.", objectiveArabic: "ميّز بين موقف مؤسسي رسمي وتوصية شخصية.", stage: "introduction", semantic: "example", minutes: 18, sentencePatterns: ["The institution formally recognises …", "My recommendation would go further by …", "The distinction matters because …"] },
  18: { kind: "reading", title: "Follow a public responsibility", titleArabic: "تتبّع مسؤولية عامة", objective: "Trace how a public document assigns responsibility across actors and stages.", objectiveArabic: "تتبّع كيف يوزّع نص عام المسؤولية بين الجهات والمراحل.", stage: "explanation", semantic: "example", minutes: 25, readingText: "A public review describes a service failure without assigning blame to one employee. It distinguishes the decision that created the risk, the warning that was missed, and the later response that contained the damage. This structure makes responsibility traceable without pretending that a complex failure has a single cause.", readingTextArabic: "يصف تقرير عام فشل خدمة دون تحميل موظف واحد المسؤولية. ويميّز بين القرار الذي أوجد الخطر، والتحذير الذي لم يُنتبه إليه، والاستجابة اللاحقة التي حدّت من الضرر. ويجعل هذا البناء المسؤولية قابلة للتتبع دون التظاهر بأن الفشل المعقد له سبب واحد.", sentencePatterns: ["The review assigns responsibility by …", "The evidence does not establish that …", "A more accountable reading would …"] },
  19: { kind: "standard", title: "Attribute without overclaiming", titleArabic: "انسب دون مبالغة", objective: "Use source markers and calibrated stance language to report a claim responsibly.", objectiveArabic: "استخدم علامات المصدر ولغة موقف دقيقة لنقل ادعاء بمسؤولية.", stage: "guided-practice", semantic: "grammar", minutes: 20, sentencePatterns: ["According to the review, …", "The evidence appears to suggest …", "This should not be taken to mean that …"] },
  20: { kind: "listening", title: "Hear the obligation beneath the words", titleArabic: "استمع إلى الالتزام الكامن", objective: "Identify explicit obligation, recommendation, and uncertainty in a public briefing.", objectiveArabic: "حدّد الالتزام والتوصية وعدم اليقين في إحاطة عامة.", stage: "guided-practice", semantic: "activity", minutes: 22, speakingLines: [{ id: "director", speaker: "Director", text: "The department should publish the figures this quarter, although the interpretation may need to change when the fuller sample is available.", textArabic: "ينبغي للدائرة نشر الأرقام هذا الربع، رغم أن التفسير قد يحتاج إلى تغيير عندما تتوفر العينة الكاملة." }], sentencePatterns: ["The speaker requires …", "The speaker recommends … rather than …", "The qualification limits the claim by …"] },
  21: { kind: "interaction", title: "Clarify without escalating", titleArabic: "وضّح دون تصعيد", objective: "Ask a precise clarification question and acknowledge a concern before challenging an assumption.", objectiveArabic: "اطرح سؤال توضيح دقيقاً واعترف بقلق قبل تحدي افتراض.", stage: "real-context", semantic: "activity", minutes: 21, interactionTurns: [{ id: "colleague", speaker: "Colleague", text: "The proposal is obviously the fairest option.", textArabic: "من الواضح أن الاقتراح هو الخيار الأكثر عدلاً.", purpose: "Notice an unsupported certainty." }, { id: "you", speaker: "You", text: "I can see why it appears fair. Which groups were included in that comparison, and what evidence would alter the conclusion?", textArabic: "أفهم لماذا يبدو عادلاً. ما الفئات التي أُدرجت في المقارنة، وما الدليل الذي قد يغيّر النتيجة؟", purpose: "Clarify diplomatically." }] },
  22: { kind: "standard", title: "Choose the exact institutional word", titleArabic: "اختر الكلمة المؤسسية الدقيقة", objective: "Differentiate obligation, recommendation, expectation, and contingency in formal vocabulary.", objectiveArabic: "ميّز بين الالتزام والتوصية والتوقع والشرط في المفردات الرسمية.", stage: "guided-practice", semantic: "vocabulary", minutes: 18, sentencePatterns: ["The policy requires …", "The committee recommends …", "Implementation is contingent on …"] },
  23: { kind: "reading", title: "Compare consultation with response", titleArabic: "قارن بين التشاور والاستجابة", objective: "Compare what a consultation summary says with how a policy response reframes it.", objectiveArabic: "قارن بين ما يقوله ملخص التشاور وكيف تعيد الاستجابة السياسية صياغته.", stage: "real-context", semantic: "example", minutes: 26, readingText: "A consultation summary records repeated concern about unequal access. The policy response accepts the concern but recasts it as a question of implementation efficiency. The shift is not necessarily dishonest, yet it changes the decision-maker’s attention from distribution to delivery. A careful reader should name that shift before evaluating the response.", readingTextArabic: "يسجل ملخص التشاور قلقاً متكرراً بشأن عدم تكافؤ الوصول. وتقبل الاستجابة السياسية القلق لكنها تعيد صياغته كسؤال عن كفاءة التنفيذ. وليس التحول مخادعاً بالضرورة، لكنه ينقل انتباه صانع القرار من التوزيع إلى التنفيذ. وعلى القارئ الدقيق تسمية هذا التحول قبل تقييم الاستجابة.", sentencePatterns: ["The consultation foregrounds …", "The response reframes this as …", "That reframing matters because …"] },
  24: { kind: "writing", title: "Recommend with conditions", titleArabic: "قدّم توصية بشروط", objective: "Write a proportionate recommendation that names evidence, uncertainty, and a review condition.", objectiveArabic: "اكتب توصية متناسبة تسمّي الدليل وعدم اليقين وشرط المراجعة.", stage: "guided-practice", semantic: "grammar", minutes: 30, prompt: "Write 240–300 words for a public committee recommending whether to adopt a small service change. Attribute two claims, acknowledge one uncertainty, and include a measurable review condition.", promptArabic: "اكتب 240–300 كلمة للجنة عامة توصي فيها باعتماد تغيير صغير في خدمة. انسب ادعاءين، واعترف بحالة عدم يقين، وأدرج شرط مراجعة قابلاً للقياس.", sentencePatterns: ["The available evidence supports …, although …", "I recommend a limited pilot subject to …", "The decision should be reviewed when …"] },
  25: { kind: "review", title: "Retrieve the accountable move", titleArabic: "استرجع الحركة المسؤولة", objective: "Retrieve attribution, qualification, and counterargument moves and apply them to a new institutional scenario.", objectiveArabic: "استرجع حركات النسبة والتقييد والحجة المضادة وطبّقها في موقف مؤسسي جديد.", stage: "review", semantic: "retrieval", minutes: 20, sentencePatterns: ["The source reports …, but this does not establish …", "A reasonable objection would be …", "The next evidence needed is …"] },
  26: { kind: "speaking", title: "Explain a decision in public", titleArabic: "اشرح قراراً أمام الجمهور", objective: "Deliver a concise public explanation that foregrounds rationale without hiding trade-offs.", objectiveArabic: "قدّم شرحاً عاماً موجزاً يبرز المبررات دون إخفاء المفاضلات.", stage: "real-context", semantic: "activity", minutes: 22, speakingLines: [{ id: "you", speaker: "You", text: "We are proposing a limited change because the current evidence points to a practical benefit, but we recognise that access may remain uneven. We will therefore publish the results and revise the approach if … .", textArabic: "نقترح تغييراً محدوداً لأن الأدلة الحالية تشير إلى فائدة عملية، لكننا ندرك أن الوصول قد يبقى غير متساوٍ. لذلك سننشر النتائج ونراجع النهج إذا … ." }], sentencePatterns: ["The rationale is …", "The principal trade-off is …", "We will revise the approach if …"] },
  27: { kind: "listening", title: "Track a concession in debate", titleArabic: "تتبّع تنازلاً في نقاش", objective: "Identify a speaker’s concession, rebuttal, and remaining condition during a committee exchange.", objectiveArabic: "حدّد تنازل المتحدث وردّه والشرط المتبقي في نقاش لجنة.", stage: "real-context", semantic: "activity", minutes: 24, speakingLines: [{ id: "member", speaker: "Member", text: "I accept that the pilot could improve access in the short term. My concern is that, unless the funding model is transparent, the apparent gain may not be sustainable.", textArabic: "أقبل بأن التجربة قد تحسن الوصول على المدى القصير. لكن قلقي هو أنه ما لم يكن نموذج التمويل شفافاً، فقد لا يكون المكسب الظاهر مستداماً." }], sentencePatterns: ["The concession is …", "The rebuttal shifts attention to …", "The remaining condition is …"] },
  28: { kind: "standard", title: "Translate expertise for the public", titleArabic: "انقل الخبرة إلى الجمهور", objective: "Mediate specialist language into a clear public explanation while preserving its limits.", objectiveArabic: "انقل لغة متخصصة إلى شرح عام واضح مع الحفاظ على حدودها.", stage: "real-context", semantic: "example", minutes: 23, readingText: "A technical report says that the intervention has a statistically significant association with improved outcomes, but it cannot establish that the intervention caused every improvement. A public explanation should keep both parts: the pattern is meaningful, and the causal claim remains limited.", readingTextArabic: "يقول تقرير تقني إن التدخل يرتبط ارتباطاً ذا دلالة إحصائية بتحسن النتائج، لكنه لا يستطيع إثبات أن التدخل سبب كل تحسن. وينبغي للشرح العام أن يحافظ على الجزأين: النمط مهم، والادعاء السببي ما زال محدوداً.", sentencePatterns: ["In plain language, this means …", "The report supports a relationship, not necessarily …", "The important limitation is …"] },
  29: { kind: "standard", title: "Concede and reposition", titleArabic: "اعترف وأعد توجيه الحجة", objective: "Use concessive clauses to acknowledge a valid objection before narrowing or repositioning the claim.", objectiveArabic: "استخدم جمل التنازل للاعتراف باعتراض صحيح قبل تضييق الادعاء أو إعادة توجيهه.", stage: "guided-practice", semantic: "grammar", minutes: 21, sentencePatterns: ["Although the concern is valid, it does not follow that …", "Granted, …; nevertheless, …", "The objection changes the scope of the recommendation rather than …"] },
  30: { kind: "reading", title: "Weigh evidence and audience", titleArabic: "وازن الدليل والجمهور", objective: "Evaluate how evidence selection and audience expectations shape a public argument.", objectiveArabic: "قيّم كيف يؤثر اختيار الدليل وتوقعات الجمهور في حجة عامة.", stage: "independent-practice", semantic: "example", minutes: 27, readingText: "A ministerial speech uses a vivid case study to justify a reform, while an accompanying technical note presents a more conditional picture. The speech may be appropriate for motivating action, but the note is the better guide for estimating scale and risk. The responsible reader asks what each genre is designed to do before treating either as the whole case.", readingTextArabic: "يستخدم خطاب وزاري حالة مؤثرة لتبرير إصلاح، بينما تعرض مذكرة تقنية مرافقة صورة أكثر شرطية. قد يكون الخطاب مناسباً لتحفيز العمل، لكن المذكرة أفضل لتقدير الحجم والمخاطر. ويسأل القارئ المسؤول ما الذي صُمم كل نوع نصي لإنجازه قبل اعتباره الصورة الكاملة.", sentencePatterns: ["The speech is designed to …", "The technical note is stronger evidence for …", "A balanced judgement should combine …"] },
  31: { kind: "writing", title: "Revise for a different reader", titleArabic: "راجع النص لقارئ مختلف", objective: "Recast an evidence-aware recommendation for a public audience while preserving its qualifications.", objectiveArabic: "أعد صياغة توصية قائمة على الدليل لجمهور عام مع الحفاظ على قيودها.", stage: "independent-practice", semantic: "grammar", minutes: 30, prompt: "Write 220–280 words explaining the same institutional recommendation first to senior officials and then in a shorter public-facing version. Preserve attribution, uncertainty, and the practical next step.", promptArabic: "اكتب 220–280 كلمة تشرح التوصية المؤسسية نفسها أولاً لكبار المسؤولين ثم في نسخة أقصر للجمهور. حافظ على النسبة وعدم اليقين والخطوة العملية التالية.", sentencePatterns: ["For a specialist reader, I would emphasise …", "For the public, this can be expressed as …", "The qualification must remain because …"] },
  32: { kind: "assessment", title: "Build an accountable public response", titleArabic: "ابنِ استجابة عامة مسؤولة", objective: "Synthesize paired sources into a formal, audience-sensitive response with accountable recommendation and review condition.", objectiveArabic: "ركّب مصدرين في استجابة رسمية مناسبة للجمهور تتضمن توصية مسؤولة وشرط مراجعة.", stage: "assessment", semantic: "assessment", minutes: 36, prompt: "Write 280–360 words for a public committee using a paired consultation and policy dossier. Identify the central disagreement, attribute at least three claims, acknowledge one limitation, recommend a proportionate action, and state what evidence should trigger a review.", promptArabic: "اكتب 280–360 كلمة للجنة عامة باستخدام ملف تشاور وسياسة مزدوج. حدّد الخلاف الأساسي، وانسب ثلاثة ادعاءات على الأقل، واعترف بحد واحد، واقترح إجراءً متناسباً، واذكر الدليل الذي ينبغي أن يفعّل المراجعة.", sentencePatterns: ["The sources agree that …, but differ over …", "The most defensible recommendation is …", "This position should be reviewed if …"] },
};

const check = (lesson: number): NonNullable<LessonActivity["retrievalCheck"]> => ({ prompt: `Retrieve one attribution, qualification, concession, or audience-shift move from earlier C1 study and apply it to Lesson ${lesson}.`, promptArabic: `استرجع حركة نسبة أو تقييد أو تنازل أو تغيير جمهور من دراسة C1 السابقة وطبّقها في الدرس ${lesson}.`, expectedEvidence: "A concise response that uses the retrieved move accurately in a new institutional context.", expectedEvidenceArabic: "إجابة موجزة تستخدم الحركة المسترجعة بدقة في سياق مؤسسي جديد." });

export const C1_MODULE_2_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([key, spec]) => {
  const lesson = Number(key);
  const activity: LessonActivity = {
    id: `c1-m2-${lesson}`,
    kind: spec.kind,
    title: spec.title,
    titleArabic: spec.titleArabic,
    objective: spec.objective,
    objectiveArabic: spec.objectiveArabic,
    stage: spec.stage,
    estimatedMinutes: spec.minutes,
    semantic: spec.semantic,
    progressiveSupports: spec.kind === "reading" ? ["word-support", "arabic-help"] : spec.kind === "listening" ? ["transcript", "worked-example"] : spec.kind === "assessment" ? ["worked-example", "tip"] : ["worked-example", "word-support"],
    retrievalCheck: check(lesson),
    ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}),
    ...(spec.readingText ? { readingText: spec.readingText, readingTextArabic: spec.readingTextArabic } : {}),
    ...(spec.speakingLines ? { speakingLines: spec.speakingLines } : {}),
    ...(spec.interactionTurns ? { interactionTurns: spec.interactionTurns } : {}),
    ...(spec.sentencePatterns ? { sentencePatterns: spec.sentencePatterns } : {}),
  };
  return [lesson, [activity]];
})) as Record<number, LessonActivity[]>;
