import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_3_EXPERIENCES: Record<number, LessonExperience> = {
  33: experience("reading", "deep", "The module opens by separating headline framing from the evidence underneath it, so later policy work begins with disciplined interpretation.", ["orientation", "encounter", "notice", "evidence"], "A source-comparison reading studio.", "Read for the central claim, the framing, and the assumption that needs testing.", "A persuasive frame is not the same as proof.", "Trace what the source leaves unsaid.", ["word-support", "arabic-help", "extended-rationale"]),
  34: experience("notice", "light", "A short omission-mapping task gives the learner one precise analytical move before the module increases source density.", ["retrieval", "notice", "next-bridge"], "An omission-mapping exercise.", "Mark what the source names, what it omits, and why the omission changes interpretation.", "Responsible reading notices silence without inventing facts.", "Hear how an expert calibrates confidence.", ["worked-example", "tip"]),
  35: experience("listening", "normal", "Audio makes degrees of confidence audible; the transcript remains a verification tool rather than the first route.", ["encounter", "notice", "retrieval"], "An expert briefing on early evidence.", "Listen twice: first for the claim, then for the boundary between evidence, inference, and speculation.", "Professional listening includes uncertainty markers.", "Calibrate your own evidence sentence.", ["transcript", "worked-example"]),
  36: experience("grammar", "normal", "Evidential verbs and modal language are taught as choices about intellectual honesty, not as a detached grammar list.", ["retrieval", "notice", "supported-practice"], "A calibration workshop.", "Choose language that matches the strength of the evidence, then revise one overconfident sentence.", "Small modal choices change the truth conditions of a claim.", "Mediate two perspectives without flattening them.", ["worked-example", "tip"]),
  37: experience("interaction", "normal", "The mediation route turns source interpretation into a respectful public skill with two legitimate but incomplete accounts.", ["encounter", "meaningful-use"], "A resident and official explain the same service change.", "Name the shared fact, preserve each perspective, and state the unresolved evidence question.", "Balance does not mean pretending the accounts are identical.", "Compare testimony with policy language.", ["worked-example", "tip"]),
  38: experience("reading", "deep", "A paired testimony-and-policy text makes evidential roles visible before the learner must synthesize them independently.", ["encounter", "notice", "meaningful-use", "evidence"], "Two sources about an eligibility rule.", "Assign the testimony and policy extract different jobs, then combine their contributions accurately.", "A source can establish consequences without establishing intent.", "Build a multi-factor causal chain.", ["word-support", "arabic-help", "extended-rationale"]),
  39: experience("grammar", "normal", "Causal language follows source comparison so learners can distinguish contribution from direct causation in meaningful context.", ["retrieval", "notice", "supported-practice"], "A causal-chain language lab.", "Arrange causes, contributing conditions, and outcomes; test whether each verb overstates the relationship.", "Complex outcomes rarely have one sufficient cause.", "Turn the chain into clear prose.", ["worked-example", "tip"]),
  40: experience("writing", "deep", "The first extended writing route asks for a bounded causal explanation with one explicit uncertainty, keeping the objective narrow.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A concise public-service explanation.", "Write a causal account with precise abstract noun phrases and a clear limitation.", "Good analysis makes uncertainty usable rather than evasive.", "Test the explanation with a counterfactual.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  41: experience("speaking", "normal", "Counterfactual speaking lets the learner test a proposed explanation aloud before applying it to ethical conditions.", ["encounter", "meaningful-use"], "A counterfactual explanation rehearsal.", "State what would change, what might follow, and what the scenario suggests about the original cause.", "A counterfactual is a test of reasoning, not a prediction presented as fact.", "Listen for a condition that limits a recommendation.", ["worked-example", "tip"]),
  42: experience("listening", "normal", "The ethical-condition briefing adds authentic conditional reasoning while keeping transcript disclosure secondary.", ["encounter", "notice", "meaningful-use", "retrieval"], "A committee briefing on a pilot.", "Listen for the safeguards that make the recommendation acceptable and the trigger that would stop it.", "Ethical language connects permission to conditions.", "Synthesize a policy pair.", ["transcript", "worked-example"]),
  43: experience("reading", "deep", "Paired policy and community sources prepare the learner for synthesis by requiring shared intention, disagreement, and testable evidence.", ["encounter", "notice", "evidence"], "A policy extract beside a community statement.", "Identify the shared aim, locate the disagreement, and name the evidence that could test the concern.", "Synthesis delays judgment until the relevant difference is visible.", "Recommend a measurable safeguard.", ["word-support", "arabic-help", "extended-rationale"]),
  44: experience("writing", "deep", "A formal recommendation combines attribution, limitation, and measurement without adding unrelated objectives.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A recommendation for a municipal committee.", "Use two sources, propose one safeguard, acknowledge one limit, and define the review method.", "A recommendation earns trust through traceable evidence and a future check.", "Retrieve the module's evidence moves.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  45: experience("review", "normal", "The review lesson reorganises the module's analytical language before the cumulative challenge, using a new public scenario rather than repetition.", ["retrieval", "notice", "next-bridge"], "An evidence-move retrieval studio.", "Apply attribution, qualification, causal, and conditional language to a fresh situation.", "Retrieval becomes durable when the context changes but the reasoning move remains.", "Reconcile policy and experience.", ["worked-example", "tip"]),
  46: experience("integration", "deep", "The synthesis route asks the learner to reconcile policy and testimony while preserving both evidence roles.", ["retrieval", "meaningful-use", "evidence"], "A balanced local-council proposal.", "State the shared aim, explain the tension, and recommend proportionate action with revision conditions.", "A balanced proposal can be decisive without pretending certainty.", "Defend a conditional technology policy.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  47: experience("assessment", "deep", "This assessment tests conditional judgement across multiple sources and makes consent a substantive criterion rather than a vocabulary target.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A data-protection board response.", "Weigh sources, address a counterargument, state the consent condition, and define unacceptable harm.", "C1 judgement connects benefit, evidence, consent, and limits.", "Challenge a single public story.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  48: experience("assessment", "deep", "The module capstone requires respectful interpretation of conflicting narratives and a concrete proposal, integrating the full arc without packing every routine into earlier lessons.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A city arts-council synthesis challenge.", "Evaluate three sources, identify competing narratives, and propose respectful institutional change.", "Advanced writing can hold standards and representation together.", "Record one transferable synthesis strength before Module 4.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_3_EXPERIENCES;

