import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_6_EXPERIENCES: Record<number, LessonExperience> = {
  81: experience("reading", "deep", "The module opens by making implication visible across sources rather than treating headlines as neutral summaries.", ["orientation", "encounter", "notice", "evidence"], "An implication-reading studio.", "Mark what each source states, suggests, and leaves unresolved.", "Framing changes what an audience believes the evidence means.", "Test a contested claim's method.", ["word-support", "arabic-help", "extended-rationale"]),
  82: experience("reading", "deep", "Method comparison gives the learner a disciplined route through disagreement.", ["retrieval", "notice", "evidence"], "A methods-comparison reading.", "Compare samples, timeframes, and comparison groups before judging the headline.", "Evidence quality depends on how the comparison was built.", "Calibrate the confidence of a claim.", ["word-support", "worked-example", "extended-rationale"]),
  83: experience("grammar", "normal", "Advanced grammar becomes a tool for proportional confidence rather than a display of complexity.", ["retrieval", "notice", "supported-practice"], "A calibrated-stance language workshop.", "Rewrite absolute claims so probability and limits remain explicit.", "A precise hedge can preserve truth rather than weaken the argument.", "Listen for cautious policy language.", ["worked-example", "tip", "arabic-help"]),
  84: experience("listening", "normal", "The audio briefing lets the learner hear how disagreement and omission are signalled before reading a transcript.", ["encounter", "notice", "retrieval"], "An audio disagreement briefing.", "Listen once for the finding and again for the boundary of the speaker's claim.", "Listening for refusal and qualification is part of source evaluation.", "Write a proportionate conclusion.", ["transcript", "worked-example"]),
  85: experience("writing", "deep", "The conclusion route bounds synthesis around one recommendation and one concession.", ["retrieval", "meaningful-use", "evidence"], "A proportionate-conclusion workshop.", "State what the evidence supports, concede one objection, and recommend one action.", "A conclusion should be defensible, not merely confident.", "Combine technical evidence with testimony.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  86: experience("reading", "deep", "The paired accounts require the learner to keep lived experience and measured outcomes in view together.", ["encounter", "notice", "evidence"], "A technical-and-lived-experience reading.", "Record what each account answers and where the burden falls.", "Different kinds of evidence can answer different questions without cancelling each other.", "Question convenience and responsibility.", ["word-support", "worked-example", "extended-rationale"]),
  87: experience("grammar", "normal", "Counterfactual conditionals make responsibility and consent risks discussable with precision.", ["retrieval", "notice", "supported-practice"], "A responsibility-and-conditionals workshop.", "Build conditional claims that show what would have changed the risk.", "Conditional form can separate a missed safeguard from a proven breach.", "Challenge a single story.", ["worked-example", "tip"]),
  88: experience("reading", "deep", "Representation becomes an evidence-and-power problem rather than a slogan.", ["retrieval", "notice", "evidence"], "A representation and decision-power reading.", "Trace who was invited, who decided, and what each source omits.", "Fair synthesis asks who had power over the process.", "Compare indicators of progress.", ["word-support", "arabic-help", "extended-rationale"]),
  89: experience("listening", "normal", "The spoken route develops inference about indicator choice and the trade-off it hides.", ["encounter", "notice", "meaningful-use"], "An indicators briefing.", "Listen for the measure being privileged and the outcome it may conceal.", "A metric is also a decision about what counts.", "Write a resource-allocation proposal.", ["transcript", "worked-example", "tip"]),
  90: experience("writing", "deep", "The allocation proposal makes unintended effects and mitigation part of formal reasoning.", ["retrieval", "meaningful-use", "evidence"], "A resource-allocation proposal.", "Balance two sources, predict a knock-on effect, and specify mitigation.", "Responsible proposals plan for effects beyond the headline benefit.", "Design a deliberative forum.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  91: experience("interaction", "normal", "Deliberation becomes a concrete design problem when the learner must answer a sceptical stakeholder.", ["retrieval", "meaningful-use"], "A deliberative-design negotiation.", "Acknowledge the risk, then add a decision point and public evidence trail.", "Participation needs a mechanism, not just an invitation.", "Translate expertise for a public.", ["worked-example", "tip"]),
  92: experience("reading", "deep", "The translation route preserves limitations while changing register for a public audience.", ["encounter", "notice", "evidence"], "A specialist-to-public translation lab.", "Rewrite technical findings in accessible language without deleting uncertainty.", "Clarity is not simplification if the limits survive.", "Retrieve the evidence moves.", ["word-support", "worked-example", "extended-rationale"]),
  93: experience("review", "normal", "Retrieval reactivates the module's evidence moves before the learner performs under audience pressure.", ["retrieval", "notice", "meaningful-use"], "A public-judgement retrieval lab.", "Apply attribution, calibration, and mitigation language to a new case.", "Old precision becomes useful when it transfers to a new decision.", "Deliver a public judgement.", ["worked-example", "tip"]),
  94: experience("speaking", "normal", "The briefing rehearsal separates evidence, judgement, and action in a live exchange.", ["retrieval", "meaningful-use"], "A committee judgement briefing.", "Answer what should be approved, monitored, and revised.", "A responsible speaker can act while keeping revision conditions visible.", "Draft the source-aware proposal.", ["worked-example", "tip"]),
  95: experience("writing", "deep", "The proposal route integrates source synthesis, uncertainty, objection, and reviewability.", ["retrieval", "meaningful-use", "evidence"], "A source-aware proposal studio.", "Draft the proposal, then test every condition against the evidence.", "A formal recommendation earns trust through its review trigger.", "Complete the public-judgement checkpoint.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  96: experience("assessment", "deep", "The checkpoint transfers judgement to a fresh dossier and audience rather than rewarding recall of one model text.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A public-judgement synthesis challenge.", "Appraise sources, preserve uncertainty, answer an objection, and defend a reviewable proposal.", "C1 judgement combines accurate attribution, fair representation, calibrated confidence, and responsible action.", "Record one evidence skill to carry into the next module.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_6_EXPERIENCES;
