import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_5_EXPERIENCES: Record<number, LessonExperience> = {
  65: experience("reading", "deep", "The module begins with a formal proposal whose confidence must be tested against its accountability gaps.", ["orientation", "encounter", "notice", "evidence"], "A source-reading studio about integrity in formal proposals.", "Mark the proposal's stated value, hidden assumption, and missing safeguard.", "A plausible proposal is not yet a trustworthy one.", "Separate foreseeable risk from established wrongdoing.", ["word-support", "arabic-help", "extended-rationale"]),
  66: experience("grammar", "normal", "Conditional language gives advanced learners a precise way to distinguish risk, evidence, and breach.", ["retrieval", "notice", "supported-practice"], "A precision-language workshop.", "Rewrite claims so their conditions and limits remain visible.", "Careful grammar protects the difference between suspicion and proof.", "Hear how a compliance officer calibrates disclosure.", ["worked-example", "tip", "arabic-help"]),
  67: experience("listening", "normal", "The audio route makes cautious compliance language audible before the learner sees the transcript.", ["encounter", "notice", "retrieval"], "An audio compliance briefing.", "Listen twice: first for the finding, then for what the speaker refuses to claim.", "Responsible listening preserves degrees of certainty.", "Compare the reach and enforceability of two safeguards.", ["transcript", "worked-example"]),
  68: experience("reading", "deep", "A paired mechanism comparison raises the decision from moral reaction to proportional governance design.", ["retrieval", "notice", "evidence"], "A safeguards comparison.", "Compare reach, cost, timing, and enforceability before recommending a combination.", "No safeguard is free; proportionality requires showing the trade-off.", "Frame a formal objection without overstating it.", ["word-support", "worked-example", "extended-rationale"]),
  69: experience("writing", "deep", "The objection route bounds formal writing around one material weakness and one remedy rather than demanding a complete report.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A formal objection letter.", "State the weakness, acknowledge what remains unknown, and request one remedy.", "A strong objection can be firm without making an allegation it cannot support.", "Negotiate a disclosure standard under operational constraints.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  70: experience("interaction", "normal", "The negotiation makes integrity practical by forcing the learner to balance a public safeguard with a real implementation constraint.", ["retrieval", "meaningful-use"], "A disclosure-standard negotiation.", "Recognise the delay concern, then propose a minimum public standard.", "A proportionate safeguard is more useful than an impossible ideal.", "Answer an adversarial public question.", ["worked-example", "tip"]),
  71: experience("speaking", "normal", "The challenge-response rehearsal develops calm qualification under pressure rather than debate performance.", ["retrieval", "meaningful-use"], "An adversarial question rehearsal.", "Concede the limit of your claim and return to the evidence that warrants action.", "Tone and precision can protect an argument from polarisation.", "Reconstruct the audit trail behind a decision.", ["worked-example", "tip"]),
  72: experience("reading", "deep", "The audit-trail reading shows how omission can manufacture certainty without requiring a fabricated source.", ["encounter", "notice", "evidence"], "A decision-accountability reading.", "Trace the movement from pilot evidence to public announcement and mark the weakening point.", "Accountability is lost through changes in representation as well as through falsehood.", "Retrieve the language of restraint.", ["word-support", "arabic-help", "extended-rationale"]),
  73: experience("review", "normal", "A retrieval lesson consolidates calibrated reporting before the module returns to new stakeholder pressure.", ["retrieval", "notice", "meaningful-use"], "A language-of-restraint retrieval lab.", "Apply three earlier qualification moves to a new integrity scenario.", "Retrieval should make old precision available for new judgement.", "Listen for the assumption a speaker leaves unstated.", ["worked-example", "tip"]),
  74: experience("listening", "normal", "The second audio route trains inference about omission while explicitly separating a plausible assumption from a factual finding.", ["encounter", "notice", "meaningful-use"], "An implied-assumption briefing.", "Listen for what the consultant treats as already settled and phrase your inference cautiously.", "Advanced listening includes noticing the boundary of what was not said.", "Protect a dissenting voice in a meeting.", ["transcript", "worked-example", "tip"]),
  75: experience("interaction", "normal", "The dissent route makes fair representation a communicative action before disagreement becomes rebuttal.", ["retrieval", "meaningful-use"], "A dissent-protection meeting.", "Restate the concern accurately, then propose a response that keeps the concern visible.", "You can answer a position without weakening or caricaturing it.", "Evaluate a formal recommendation.", ["worked-example", "tip"]),
  76: experience("reading", "deep", "A formal recommendation reading models a proposal whose strength lies in reviewability rather than certainty.", ["encounter", "notice", "evidence"], "A recommendation and safeguards reading.", "Check whether the scope, evidence, and review trigger match one another.", "A claim becomes more trustworthy when it can be tested and revised.", "Draft the formal proposal.", ["word-support", "worked-example", "extended-rationale"]),
  77: experience("writing", "deep", "The formal-proposal route combines evidence, uncertainty, safeguards, implementation, and review in one bounded document.", ["retrieval", "meaningful-use", "evidence"], "A monitored pilot proposal.", "Draft the proposal, then inspect each condition for evidence and accountability.", "Integrity is designed into the process, not added as a closing slogan.", "Test whether each safeguard is proportionate.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  78: experience("grammar", "normal", "Concessive and comparative structures let the learner test proportionality without losing formal control.", ["retrieval", "notice", "supported-practice"], "A proportionality language workshop.", "Revise one safeguard argument so risk, intrusion, and alternative are explicit.", "Complex syntax should clarify a trade-off rather than obscure it.", "Deliver the integrity briefing.", ["worked-example", "tip"]),
  79: experience("speaking", "normal", "The briefing rehearsal transfers the module from drafting to accountable public delivery.", ["retrieval", "meaningful-use", "next-bridge"], "A three-minute integrity briefing.", "Separate what is established, what is uncertain, and what you recommend.", "A defensible speaker shows the limits of the claim while still enabling a decision.", "Complete the integrity proposal checkpoint.", ["worked-example", "tip"]),
  80: experience("assessment", "deep", "The checkpoint asks for a new dossier and audience so the learner demonstrates transferable judgement rather than recalling one model text.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A formal integrity-proposal challenge.", "Appraise the evidence, protect dissent, propose a monitored action, and defend its safeguards.", "C1 integrity means accurate attribution, calibrated confidence, fair representation, and reviewable action.", "Record one transferable evidence skill before the next module.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_5_EXPERIENCES;
