import type { LessonActivity, ProgressiveSupport } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & {
  minutes: number;
  prompt?: string;
  promptArabic?: string;
  retrieval: { prompt: string; promptArabic: string; expectedEvidence: string; expectedEvidenceArabic: string };
  supports?: ProgressiveSupport[];
};

const specs: Record<number, Spec> = {
  129: { kind: "reading", title: "Measure progress carefully", titleArabic: "قِس التقدم بعناية", objective: "Interpret competing development indicators and recommend which measures should count as progress.", objectiveArabic: "فسّر مؤشرات التنمية المتنافسة وأوصِ بالمقاييس التي ينبغي أن تُعد تقدماً.", stage: "introduction", semantic: "example", minutes: 28,
    readingText: "A city reports progress through faster transport, while a neighbourhood survey reports longer journeys for residents displaced by construction. Both measures are real, but they answer different questions. The transport dashboard captures system speed; the survey captures distributional experience. A responsible proposal must state which outcome it values, whose experience is missing, and when the measure should be reviewed.", readingTextArabic: "تعلن مدينة عن التقدم من خلال سرعة النقل، بينما يذكر استطلاع حيّ أن السكان الذين أُبعدوا بسبب البناء يقطعون رحلات أطول. كلا المقياسين حقيقي، لكنهما يجيبان عن سؤالين مختلفين. تلتقط لوحة النقل سرعة النظام؛ ويلتقط الاستطلاع تجربة التوزيع. يجب أن يوضح المقترح المسؤول النتيجة التي يقدرها، وتجربة من تغيب، وموعد مراجعة المقياس.",
    readingChecks: [{ id: "contrast", type: "inference", prompt: "Why are the two measures not interchangeable?", promptArabic: "لماذا لا يمكن اعتبار المقياسين متبادلين؟", answer: "They measure system speed and unequal lived experience, which are different outcomes.", explanation: "A headline indicator cannot replace evidence about who benefits or pays." }], sentencePatterns: ["The indicator captures … but leaves … unmeasured.", "Progress should count as … only if …", "A review trigger would be …"], retrieval: { prompt: "Retrieve the difference between a headline indicator and a distributional outcome.", promptArabic: "استرجع الفرق بين المؤشر الرئيسي والنتيجة التوزيعية.", expectedEvidence: "A headline indicator describes an aggregate pattern; a distributional outcome shows who experiences the benefit or cost.", expectedEvidenceArabic: "يصف المؤشر الرئيسي نمطاً إجمالياً؛ أما النتيجة التوزيعية فتظهر من يعيش المنفعة أو التكلفة." }, supports: ["word-support", "arabic-help", "extended-rationale"] },
  130: { kind: "reading", title: "Count the cost of a decision", titleArabic: "احسب تكلفة القرار", objective: "Analyse allocation trade-offs, anticipate unintended effects, and propose mitigation.", objectiveArabic: "حلّل المفاضلات في توزيع الموارد، وتوقّع الآثار غير المقصودة، واقترح التخفيف.", stage: "guided-practice", semantic: "example", minutes: 27,
    readingText: "A council funds a high-visibility clinic because it can serve many appointments quickly. A smaller mobile service would reach fewer people on paper but would serve residents who cannot travel. The choice is not simply efficiency versus waste: it is a decision about which access barrier the budget recognises. A mixed pilot could protect the headline service while testing whether the mobile route prevents exclusion.", readingTextArabic: "يموّل مجلس عيادة ظاهرة لأنها تستطيع تقديم مواعيد كثيرة بسرعة. أما خدمة متنقلة أصغر فقد تصل إلى عدد أقل على الورق لكنها تخدم السكان الذين لا يستطيعون السفر. لا يتعلق الاختيار بالكفاءة مقابل الهدر فقط، بل بالحاجز الذي يعترف به الميزان المالي. يمكن لتجربة مختلطة أن تحمي الخدمة الرئيسية وتختبر ما إذا كان المسار المتنقل يمنع الاستبعاد.",
    readingChecks: [{ id: "tradeoff", type: "main-idea", prompt: "What does the mixed pilot protect and test?", promptArabic: "ماذا تحمي التجربة المختلطة وماذا تختبر؟", answer: "It protects the high-volume service while testing whether mobile access prevents exclusion.", explanation: "The proposal keeps a visible benefit while gathering evidence about the overlooked cost." }], sentencePatterns: ["The allocation favours … at the risk of …", "The unintended effect may fall on …", "A mitigation measure would be …"], retrieval: { prompt: "Name the benefit, the burden, and one mitigation in an allocation decision.", promptArabic: "اذكر المنفعة والعبء وإجراء تخفيف واحد في قرار توزيع.", expectedEvidence: "A concrete benefit, the group or outcome bearing the cost, and a proportionate safeguard.", expectedEvidenceArabic: "منفعة ملموسة، والمجموعة أو النتيجة التي تتحمل التكلفة، وضمان متناسب." }, supports: ["worked-example", "tip", "arabic-help"] },
  131: { kind: "interaction", title: "Design disagreement well", titleArabic: "صمّم الاختلاف جيداً", objective: "Design and present a deliberation process using hedged persuasion and diplomatic rebuttal.", objectiveArabic: "صمّم وقدّم عملية مداولة باستخدام الإقناع المتحفظ والرد الدبلوماسي.", stage: "real-context", semantic: "activity", minutes: 25,
    interactionTurns: [{ id: "resident", speaker: "Resident", text: "The consultation is already decided. Why should we spend another evening speaking?", textArabic: "لقد حُسمت الاستشارة مسبقاً. لماذا نقضي أمسية أخرى في الحديث؟", purpose: "Challenge the legitimacy of the process." }, { id: "you", speaker: "You", text: "I understand why it appears symbolic. I cannot promise that every request will be accepted, but I can propose published criteria, a recorded response to each theme, and a review date.", textArabic: "أتفهم لماذا تبدو رمزية. لا أستطيع أن أعد بقبول كل طلب، لكنني أستطيع اقتراح معايير منشورة ورد مسجل على كل موضوع وموعد مراجعة.", purpose: "Acknowledge distrust and make the process answerable." }], sentencePatterns: ["It is understandable that …; however, …", "I cannot promise …, but I can commit to …", "The process would be credible if …"], retrieval: { prompt: "Retrieve one difference between consultation and accountable deliberation.", promptArabic: "استرجع فرقاً واحداً بين الاستشارة والمداولة الخاضعة للمساءلة.", expectedEvidence: "Deliberation makes criteria, responses, and consequences visible rather than merely collecting opinions.", expectedEvidenceArabic: "تجعل المداولة المعايير والردود والنتائج واضحة بدلاً من جمع الآراء فقط." }, supports: ["worked-example", "arabic-help", "tip"] },
  132: { kind: "reading", title: "Read an argument with a memory", titleArabic: "اقرأ حجة تحمل ذاكرة", objective: "Evaluate historical claims, distinguish precedent from interpretation, and connect memory to present consequence.", objectiveArabic: "قيّم الادعاءات التاريخية، وميّز بين السابقة والتفسير، واربط الذاكرة بالنتيجة الحالية.", stage: "guided-practice", semantic: "example", minutes: 29,
    readingText: "A policy brief invokes a former housing scheme as proof that central planning always fails. An archivist notes that the scheme changed twice, was underfunded in its final years, and produced different results across districts. The archive does not erase the failure, but it complicates the lesson. Historical precedent can discipline a proposal only when its conditions and limits are named.", readingTextArabic: "يستدعي موجز سياسات مخطط إسكان سابقاً دليلاً على أن التخطيط المركزي يفشل دائماً. ويذكر أمين الأرشيف أن المخطط تغير مرتين، ونقص تمويله في سنواته الأخيرة، وأنتج نتائج مختلفة بين المناطق. لا يمحو الأرشيف الفشل، لكنه يعقّد الدرس. يمكن للسابقة التاريخية أن تضبط المقترح فقط عندما تُذكر شروطها وحدودها.",
    readingChecks: [{ id: "precedent", type: "inference", prompt: "Why does the archive complicate the policy brief's conclusion?", promptArabic: "لماذا يعقّد الأرشيف استنتاج موجز السياسة؟", answer: "The historical case had changing conditions and uneven results, so it cannot support an absolute rule.", explanation: "A precedent is evidence about a situated case, not automatic proof of a universal claim." }], sentencePatterns: ["The precedent shows … under … conditions.", "It should not be treated as proof that …", "The contemporary consequence is …"], retrieval: { prompt: "Retrieve the difference between a precedent and a universal rule.", promptArabic: "استرجع الفرق بين السابقة والقاعدة العامة.", expectedEvidence: "A precedent is a situated example whose conditions must be compared before transfer.", expectedEvidenceArabic: "السابقة مثال مرتبط بظروف يجب مقارنتها قبل نقله." }, supports: ["word-support", "extended-rationale", "arabic-help"] },
  133: { kind: "reading", title: "Follow culture in motion", titleArabic: "تابع الثقافة وهي تتحرك", objective: "Analyse how cultural change is framed across sources and adapt register for different public audiences.", objectiveArabic: "حلّل كيفية تأطير التغير الثقافي عبر المصادر وكيّف الأسلوب لجمهور عام مختلف.", stage: "guided-practice", semantic: "example", minutes: 26,
    readingText: "A youth organisation describes a festival as becoming more open because new performers joined. A heritage group describes the same change as a loss of ritual control. A funding announcement calls it successful because attendance rose. The descriptions do not simply disagree about facts; each frame selects a different audience, value, and measure of change.", readingTextArabic: "تصف منظمة شبابية مهرجاناً بأنه أصبح أكثر انفتاحاً لأن مؤدين جدد انضموا. وتصفه جماعة تراثية بأنه فقد السيطرة الطقسية. ويصفه إعلان تمويل بأنه ناجح لأن الحضور ارتفع. لا تختلف الأوصاف حول الحقائق فقط؛ فكل تأطير يختار جمهوراً وقيمة ومقياساً مختلفاً للتغير.",
    readingChecks: [{ id: "frame", type: "detail", prompt: "Which source uses attendance as its main measure?", promptArabic: "أي مصدر يستخدم الحضور مقياساً رئيسياً؟", answer: "The funding announcement.", explanation: "Its evaluation foregrounds numerical reach rather than ritual control or participation." }], sentencePatterns: ["For a public audience, I would foreground … while retaining …", "The frame values … over …", "A balanced account should …"], retrieval: { prompt: "Retrieve how audience and value can change the framing of the same event.", promptArabic: "استرجع كيف يمكن للجمهور والقيمة تغيير تأطير الحدث نفسه.", expectedEvidence: "The same facts can be selected and evaluated differently according to whose concern is foregrounded.", expectedEvidenceArabic: "يمكن اختيار الحقائق نفسها وتقييمها بشكل مختلف بحسب همّ من يُقدّم إلى الواجهة." }, supports: ["word-support", "worked-example", "arabic-help"] },
  134: { kind: "standard", title: "Limit the expert voice", titleArabic: "حدّد صوت الخبير", objective: "Attribute expert claims responsibly while acknowledging uncertainty and domain limits.", objectiveArabic: "انسب ادعاءات الخبراء بمسؤولية مع الاعتراف بعدم اليقين وحدود المجال.", stage: "explanation", semantic: "grammar", minutes: 21,
    sentencePatterns: ["According to …, the evidence suggests …", "The specialist is well placed to assess …, although …", "This conclusion remains provisional because …"], retrieval: { prompt: "Rewrite an expert claim with a source attribution and one domain boundary.", promptArabic: "أعد صياغة ادعاء خبير مع إسناد إلى مصدر وحدّ مجالي واحد.", expectedEvidence: "A reporting phrase, the relevant field, and a boundary that prevents overgeneralisation.", expectedEvidenceArabic: "عبارة إسناد، والمجال المعني، وحد يمنع التعميم الزائد." }, supports: ["worked-example", "tip", "arabic-help"] },
  135: { kind: "listening", title: "Hear a review with consequences", titleArabic: "استمع إلى مراجعة لها نتائج", objective: "Synthesize achievement, criticism, concession, and likely consequence in a public review.", objectiveArabic: "ركّب الإنجاز والنقد والتنازل والنتيجة المحتملة في مراجعة عامة.", stage: "guided-practice", semantic: "activity", minutes: 23,
    speakingLines: [{ id: "reviewer", speaker: "Reviewer", text: "The programme improved access in the central districts, although the evaluation did not follow residents at the edge of the service area. That omission does not cancel the gain, but it limits how confidently we can describe the programme as equitable.", textArabic: "حسّن البرنامج الوصول في المناطق المركزية، رغم أن التقييم لم يتابع السكان على أطراف منطقة الخدمة. لا يلغي هذا الإغفال المكسب، لكنه يحد من مدى ثقتنا في وصف البرنامج بأنه عادل." }], sentencePatterns: ["The review recognises … while limiting …", "This omission matters because …", "The likely consequence is …"], retrieval: { prompt: "What can a review acknowledge without treating its evidence as complete?", promptArabic: "ماذا يمكن للمراجعة أن تعترف به دون اعتبار دليلها كاملاً؟", expectedEvidence: "It can acknowledge a gain while naming missing evidence and limiting the conclusion.", expectedEvidenceArabic: "يمكنها الاعتراف بمكسب مع ذكر الدليل المفقود وتحديد الاستنتاج." }, supports: ["transcript", "worked-example", "arabic-help"] },
  136: { kind: "writing", title: "Make complexity readable", titleArabic: "اجعل التعقيد مقروءاً", objective: "Transform specialist material into an audience-appropriate brief while preserving uncertainty, trade-offs, and evidence weight.", objectiveArabic: "حوّل مادة متخصصة إلى موجز مناسب للجمهور مع الحفاظ على عدم اليقين والمفاضلات ووزن الدليل.", stage: "independent-practice", semantic: "activity", minutes: 32,
    prompt: "Write 250–320 words for a public briefing explaining why a single progress dashboard cannot represent every community. Define one technical measure plainly, preserve one limitation, compare one lived outcome, and end with a reviewable recommendation.", promptArabic: "اكتب 250–320 كلمة لموجز عام تشرح فيه لماذا لا تستطيع لوحة تقدم واحدة تمثيل كل مجتمع. عرّف مقياساً تقنياً بلغة واضحة، وحافظ على قيد واحد، وقارن نتيجة معيشة واحدة، وأنهِ بتوصية قابلة للمراجعة.", sentencePatterns: ["In practical terms, the measure records …", "It should not be interpreted as …", "The recommendation is proportionate because …"], retrieval: { prompt: "Retrieve one technique for simplifying specialist material without deleting its uncertainty.", promptArabic: "استرجع تقنية واحدة لتبسيط المادة المتخصصة دون حذف عدم اليقين فيها.", expectedEvidence: "Define the concept plainly, then state what the evidence cannot establish.", expectedEvidenceArabic: "عرّف المفهوم بوضوح ثم اذكر ما لا يستطيع الدليل إثباته." }, supports: ["worked-example", "external-ai-prompt", "extended-rationale"] },
  137: { kind: "interaction", title: "Propose under pressure", titleArabic: "اقترح تحت الضغط", objective: "Defend a conditional proposal under time pressure and specify contingency measures.", objectiveArabic: "دافع عن مقترح مشروط تحت ضغط الوقت وحدد تدابير الطوارئ.", stage: "real-context", semantic: "activity", minutes: 25,
    interactionTurns: [{ id: "chair", speaker: "Chair", text: "We need a decision tonight. If we wait for every missing statistic, the funding window will close.", textArabic: "نحتاج إلى قرار الليلة. إذا انتظرنا كل إحصاء مفقود فستغلق نافذة التمويل.", purpose: "State the urgency objection." }, { id: "you", speaker: "You", text: "I accept the deadline, but I would approve a limited phase with a published evidence gap, a safeguard for the most affected group, and a fixed review before expansion.", textArabic: "أقبل الموعد النهائي، لكنني سأوافق على مرحلة محدودة مع نشر فجوة الدليل وضمان للمجموعة الأكثر تأثراً ومراجعة محددة قبل التوسع.", purpose: "Concede urgency while preserving conditions and review." }], sentencePatterns: ["Given the deadline, I would … provided that …", "The contingency measure would …", "Expansion should depend on …"], retrieval: { prompt: "Retrieve a conditional proposal that includes urgency, a safeguard, and a review trigger.", promptArabic: "استرجع مقترحاً مشروطاً يتضمن الاستعجال وضماناً وشرط مراجعة.", expectedEvidence: "A time-sensitive action with a named protection and a condition for continuation.", expectedEvidenceArabic: "إجراء حساس للوقت مع حماية مسماة وشرط للاستمرار." }, supports: ["worked-example", "tip", "arabic-help"] },
  138: { kind: "reading", title: "Argue against certainty", titleArabic: "حاجج ضد اليقين", objective: "Interrogate contested claims and use layered hedges and boosters to argue for epistemic humility.", objectiveArabic: "استجوب الادعاءات المتنازع عليها واستخدم أدوات تحفّظ وتقوية متدرجة للحجاج من أجل تواضع معرفي.", stage: "guided-practice", semantic: "grammar", minutes: 29,
    readingText: "One commentator claims that the new programme unquestionably restored trust. The underlying survey shows a strong improvement among respondents who attended, but it did not include non-attenders and did not measure trust before the launch. The claim may be directionally plausible, yet the adverb unquestionably outruns the design. A more responsible account would distinguish promising evidence from settled causation.", readingTextArabic: "يدعي أحد المعلقين أن البرنامج الجديد أعاد الثقة بلا شك. ويظهر الاستطلاع الأساسي تحسناً قوياً بين المستجيبين الذين حضروا، لكنه لم يشمل غير الحاضرين ولم يقس الثقة قبل الإطلاق. قد يكون الادعاء معقولاً في اتجاهه، لكن كلمة بلا شك تتجاوز التصميم. يميز العرض المسؤول بين دليل واعد وسببية محسومة.",
    readingChecks: [{ id: "certainty", type: "inference", prompt: "Why does unquestionably overstate the survey?", promptArabic: "لماذا تبالغ كلمة بلا شك في وصف الاستطلاع؟", answer: "The design lacks a comparison over time and excludes non-attenders, so it cannot establish settled causation.", explanation: "Strong wording must match the strength and scope of the design." }], sentencePatterns: ["The evidence strongly suggests …, although …", "It would be premature to claim …", "The most defensible conclusion is …"], retrieval: { prompt: "Retrieve the difference between promising evidence and settled causation.", promptArabic: "استرجع الفرق بين الدليل الواعد والسببية المحسومة.", expectedEvidence: "Promising evidence supports a qualified direction; settled causation requires stronger comparison and scope.", expectedEvidenceArabic: "يدعم الدليل الواعد اتجاهاً مشروطاً؛ أما السببية المحسومة فتتطلب مقارنة ونطاقاً أقوى." }, supports: ["word-support", "worked-example", "extended-rationale"] },
  139: { kind: "listening", title: "Speak into a crowded debate", titleArabic: "تحدث في نقاش مزدحم", objective: "Foreground a defensible position in a contested debate while tracking stakeholder priorities.", objectiveArabic: "قدّم موقفاً يمكن الدفاع عنه في نقاش متنازع عليه مع تتبع أولويات أصحاب المصلحة.", stage: "real-context", semantic: "activity", minutes: 25,
    speakingLines: [{ id: "moderator", speaker: "Moderator", text: "The proposal promises wider participation, but the groups who already organise the work fear that their role will become invisible.", textArabic: "يعد المقترح بمشاركة أوسع، لكن المجموعات التي تنظم العمل أصلاً تخشى أن يصبح دورها غير مرئي." }, { id: "advocate", speaker: "Advocate", text: "I support the expansion in principle. It should be accompanied by named recognition, transparent funding criteria, and a review of who speaks for the programme after launch.", textArabic: "أدعم التوسع من حيث المبدأ. وينبغي أن يصاحبه اعتراف واضح ومعايير تمويل شفافة ومراجعة لمن يتحدث باسم البرنامج بعد إطلاقه." }], sentencePatterns: ["In principle, I support …, provided that …", "The overlooked stakeholder is …", "The review should ask whether …"], retrieval: { prompt: "Retrieve how to foreground a position without erasing a stakeholder's concern.", promptArabic: "استرجع كيف تقدم موقفاً دون محو قلق أحد أصحاب المصلحة.", expectedEvidence: "State the position, name the concern, and attach a safeguard or review question.", expectedEvidenceArabic: "اذكر الموقف، وسمّ القلق، واربطهما بضمان أو سؤال مراجعة." }, supports: ["transcript", "worked-example", "arabic-help"] },
  140: { kind: "assessment", title: "Synthesize with integrity", titleArabic: "ركّب الأفكار بنزاهة", objective: "Integrate multiple sources into an original judgement and a register-appropriate formal proposal.", objectiveArabic: "ادمج مصادر متعددة في حكم أصيل ومقترح رسمي مناسب للأسلوب.", stage: "assessment", semantic: "assessment", minutes: 34,
    readingText: "A city dashboard reports faster access after a public investment. A community survey finds that residents on the edge of the service area still spend more time travelling. A budget note praises the programme's efficiency but does not measure who was displaced by construction. A local organiser supports expansion if the next phase includes an access guarantee and a public review.", readingTextArabic: "تعلن لوحة مدينة عن وصول أسرع بعد استثمار عام. ويجد استطلاع مجتمعي أن السكان على أطراف منطقة الخدمة ما زالوا يقضون وقتاً أطول في السفر. وتشيد مذكرة الميزانية بكفاءة البرنامج لكنها لا تقيس من أُبعد بسبب البناء. ويدعم منظم محلي التوسع إذا تضمنت المرحلة التالية ضماناً للوصول ومراجعة عامة.",
    readingChecks: [{ id: "sources", type: "main-idea", prompt: "What does each source contribute to the judgement?", promptArabic: "ماذا يضيف كل مصدر إلى الحكم؟", answer: "The dashboard shows aggregate speed, the survey shows distributional experience, the budget note shows efficiency but a gap, and the organiser proposes a safeguard.", explanation: "An ethical synthesis keeps evidence functions distinct." }], prompt: "Write 280–340 words for a city committee. Attribute the four sources, distinguish aggregate progress from distributional impact, identify one evidence gap, and recommend a conditional next step with a review trigger.", promptArabic: "اكتب 280–340 كلمة للجنة المدينة. انسب المصادر الأربعة، وميّز بين التقدم الإجمالي والأثر التوزيعي، وحدد فجوة دليل واحدة، وأوصِ بخطوة تالية مشروطة مع شرط مراجعة.", sentencePatterns: ["The dashboard establishes …, whereas …", "The evidence is promising but incomplete because …", "I recommend … subject to review if …"], retrieval: { prompt: "Retrieve the Module 9 synthesis moves: measure, distribute, qualify, protect, review.", promptArabic: "استرجع حركات تركيب الوحدة التاسعة: قِس، ووزّع، وعاير، واحمِ، وراجع.", expectedEvidence: "The learner names all five moves and connects each to a proposal sentence.", expectedEvidenceArabic: "يسمي المتعلم الحركات الخمس ويربط كل واحدة بجملة في المقترح." }, supports: ["external-ai-prompt", "extended-rationale", "worked-example"] },
  141: { kind: "reading", title: "Read between the lines", titleArabic: "اقرأ ما بين السطور", objective: "Identify implication, framing, and omission across sources before making cautious attribution.", objectiveArabic: "حدد الإيحاء والتأطير والإغفال عبر المصادر قبل تقديم إسناد حذر.", stage: "guided-practice", semantic: "example", minutes: 28,
    readingText: "An official release says that the programme gave every household a voice. It reports the number of meetings but not who attended or which proposals changed the design. A participant account describes genuine listening in one district, while a watchdog notes that the release's universal language hides unequal access. The omission does not prove bad faith, but it limits the claim's reach.", readingTextArabic: "يقول بيان رسمي إن البرنامج منح كل أسرة صوتاً. ويذكر عدد الاجتماعات لكنه لا يذكر من حضر أو أي المقترحات غيرت التصميم. وتصف رواية مشارك إصغاءً حقيقياً في منطقة واحدة، بينما يلاحظ مراقب أن اللغة الشاملة في البيان تخفي وصولاً غير متساوٍ. لا يثبت الإغفال سوء النية، لكنه يحد من مدى الادعاء.",
    readingChecks: [{ id: "omission", type: "inference", prompt: "What does the official release leave unknown?", promptArabic: "ما الذي يتركه البيان الرسمي مجهولاً؟", answer: "Who participated and whether participation changed the design.", explanation: "Counting meetings is not the same as demonstrating representative influence." }], sentencePatterns: ["The source implies … without establishing …", "The omission matters because …", "It is safer to attribute the claim to …"], retrieval: { prompt: "Retrieve the difference between an omission and proof of bad faith.", promptArabic: "استرجع الفرق بين الإغفال وإثبات سوء النية.", expectedEvidence: "An omission limits what can be concluded; it does not by itself establish motive.", expectedEvidenceArabic: "يحد الإغفال مما يمكن استنتاجه؛ ولا يثبت الدافع وحده." }, supports: ["word-support", "arabic-help", "extended-rationale"] },
  142: { kind: "reading", title: "Scrutinise the claim", titleArabic: "دقّق في الادعاء", objective: "Compare methods, scope, and limitations behind competing claims.", objectiveArabic: "قارن بين المناهج والنطاق والقيود وراء الادعاءات المتنافسة.", stage: "guided-practice", semantic: "example", minutes: 29,
    readingText: "A controlled trial reports a modest improvement after a new service, while interviews explain why some users found it useful. The trial is stronger for estimating an average effect; the interviews are stronger for describing mechanisms and exceptions. Neither source alone can show how the service will work in every district. A careful proposal combines their strengths without pretending that they answer the same question.", readingTextArabic: "تعلن تجربة مضبوطة عن تحسن متواضع بعد خدمة جديدة، بينما تشرح المقابلات لماذا وجدها بعض المستخدمين مفيدة. تكون التجربة أقوى في تقدير الأثر المتوسط؛ وتكون المقابلات أقوى في وصف الآليات والاستثناءات. لا يستطيع أي مصدر وحده إظهار كيفية عمل الخدمة في كل منطقة. يجمع المقترح الحذر بين قوتهما دون التظاهر بأنهما يجيبان عن السؤال نفسه.",
    readingChecks: [{ id: "method", type: "detail", prompt: "Which source is stronger for estimating an average effect?", promptArabic: "أي مصدر أقوى في تقدير الأثر المتوسط؟", answer: "The controlled trial.", explanation: "Its design supports a more direct estimate of average change." }], sentencePatterns: ["This method is better suited to …", "The interviews add … but cannot …", "Taken together, the sources justify … rather than …"], retrieval: { prompt: "Match a method to the question it can legitimately answer.", promptArabic: "طابق المنهج مع السؤال الذي يستطيع الإجابة عنه بشكل مشروع.", expectedEvidence: "The trial estimates an average effect; interviews illuminate mechanisms and exceptions.", expectedEvidenceArabic: "تقدر التجربة الأثر المتوسط؛ وتوضح المقابلات الآليات والاستثناءات." }, supports: ["worked-example", "tip", "arabic-help"] },
  143: { kind: "standard", title: "Use the language of uncertainty", titleArabic: "استخدم لغة عدم اليقين", objective: "Communicate probabilistic claims and uncertainty without becoming vague or evasive.", objectiveArabic: "عبّر عن الادعاءات الاحتمالية وعدم اليقين دون الغموض أو التهرب.", stage: "explanation", semantic: "grammar", minutes: 21,
    sentencePatterns: ["The evidence makes it more likely that …", "There is a reasonable possibility that …, although …", "On the available evidence, I would assign greater weight to …"], retrieval: { prompt: "Convert an absolute claim into a calibrated probabilistic claim with a reason.", promptArabic: "حوّل ادعاءً مطلقاً إلى ادعاء احتمالي معاير مع ذكر السبب.", expectedEvidence: "A degree-of-confidence phrase plus the evidence or limitation that justifies it.", expectedEvidenceArabic: "عبارة لدرجة الثقة مع الدليل أو القيد الذي يبررها." }, supports: ["worked-example", "tip", "arabic-help"] },
  144: { kind: "assessment", title: "When sources disagree", titleArabic: "عندما تختلف المصادر", objective: "Synthesise conflicting sources, identify likely bias or gaps, and defend a reviewable course of action.", objectiveArabic: "ركّب المصادر المتعارضة، وحدد التحيز أو الفجوات المحتملة، ودافع عن مسار عمل قابل للمراجعة.", stage: "assessment", semantic: "assessment", minutes: 42,
    readingText: "A development agency reports that a new transport corridor reduced average journey time. A community dossier shows that residents moved from the construction zone now travel farther to reach work. A historical account argues that similar projects previously improved central access while displacing peripheral communities. A methods review warns that the agency's sample excludes people who stopped using the route. The committee must decide whether to expand the corridor, redesign access, or pause for evidence.", readingTextArabic: "تعلن وكالة تنمية أن ممر نقل جديد خفض متوسط وقت الرحلة. ويظهر ملف مجتمعي أن السكان الذين نُقلوا من منطقة البناء يسافرون الآن مسافات أطول إلى العمل. وتقول رواية تاريخية إن مشاريع مشابهة حسنت الوصول المركزي سابقاً لكنها أزاحت مجتمعات الأطراف. وتحذر مراجعة منهجية من أن عينة الوكالة تستبعد من توقفوا عن استخدام المسار. يجب على اللجنة أن تقرر التوسع أو إعادة تصميم الوصول أو التوقف لجمع الدليل.",
    readingChecks: [{ id: "gap", type: "inference", prompt: "What gap limits the agency's claim?", promptArabic: "ما الفجوة التي تحد من ادعاء الوكالة؟", answer: "Its sample excludes people who stopped using the route, including potentially affected residents.", explanation: "Average journey time cannot stand for everyone if non-users are missing." }, { id: "action", type: "main-idea", prompt: "What must a responsible recommendation preserve?", promptArabic: "ما الذي يجب أن تحافظ عليه التوصية المسؤولة؟", answer: "The aggregate gain, the unequal cost, the historical warning, and a review condition.", explanation: "The dossier requires proportionate action rather than a slogan for expansion or pause." }], prompt: "Write a 360–440-word formal proposal to the committee. Attribute at least three sources, explain what each can and cannot establish, identify a likely gap or bias, represent uncertainty, explain who bears a consequence, and recommend expansion, redesign, or pause with a concrete review trigger.", promptArabic: "اكتب مقترحاً رسمياً من 360–440 كلمة للجنة. انسب ثلاثة مصادر على الأقل، واشرح ما يستطيع كل مصدر إثباته وما لا يستطيع، وحدد فجوة أو تحيزاً محتملاً، ومثّل عدم اليقين، واشرح من يتحمل النتيجة، وأوصِ بالتوسع أو إعادة التصميم أو التوقف مع شرط مراجعة ملموس.", sentencePatterns: ["The agency establishes …, but its sample cannot show …", "The historical account suggests … under conditions that may differ from …", "I recommend … subject to a review of …"], retrieval: { prompt: "Before the module assessment, retrieve the five moves: measure, distribute, attribute, qualify, review.", promptArabic: "قبل تقييم الوحدة، استرجع الحركات الخمس: قِس، ووزّع، وانسب، وعاير، وراجع.", expectedEvidence: "The learner names the five moves and applies them to a conflicting-source recommendation.", expectedEvidenceArabic: "يسمي المتعلم الحركات الخمس ويطبقها على توصية مبنية على مصادر متعارضة." }, supports: ["external-ai-prompt", "extended-rationale", "worked-example"] },
};

function buildActivity(lessonNumber: number, spec: Spec): LessonActivity {
  const { minutes, retrieval, supports, prompt, promptArabic, ...activity } = spec;
  return { ...activity, id: `c1-module-9-${lessonNumber}`, estimatedMinutes: minutes, ...(prompt ? { writingPrompt: prompt, writingPromptArabic: promptArabic } : {}), retrievalCheck: retrieval, progressiveSupports: supports ?? ["arabic-help", "word-support"] };
}

export const C1_MODULE_9_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(Object.entries(specs).map(([lessonNumber, spec]) => [Number(lessonNumber), [buildActivity(Number(lessonNumber), spec)]]));
export default C1_MODULE_9_ACTIVITIES;
