import type { LessonActivity } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & { minutes: number; prompt?: string; promptArabic?: string };

const specs: Record<number, Spec> = {
  33: { kind: "reading", title: "Name the claim beneath the headline", titleArabic: "سمِّ الادعاء خلف العنوان", objective: "Separate a public source's central claim from its framing and implied assumptions.", objectiveArabic: "ميّز بين الادعاء المركزي في مصدر عام وتأطيره وافتراضاته الضمنية.", stage: "introduction", semantic: "example", minutes: 24, readingText: "A city report describes a new transport scheme as a success because average journey times fell. A community note accepts the improvement but points out that the routes serving low-income neighbourhoods were changed less often. The two texts do not necessarily contradict one another; they answer different questions about what counts as success.", readingTextArabic: "يصف تقرير للمدينة مخطط نقل جديداً بأنه ناجح لأن متوسط أوقات الرحلات انخفض. وتقبل مذكرة مجتمعية هذا التحسن لكنها تشير إلى أن المسارات التي تخدم الأحياء منخفضة الدخل تغيّرت بوتيرة أقل. ولا تتناقض النصوص بالضرورة؛ فهي تجيب عن سؤالين مختلفين حول معنى النجاح.", sentencePatterns: ["The source's central claim is …", "The framing gives priority to …", "An assumption that needs testing is …"] },
  34: { kind: "standard", title: "Map what a source leaves unsaid", titleArabic: "ارسم ما يتركه المصدر دون قول", objective: "Identify an omission that changes how a public claim should be interpreted.", objectiveArabic: "حدّد حذفاً يغيّر طريقة تفسير ادعاء عام.", stage: "explanation", semantic: "activity", minutes: 19, sentencePatterns: ["The source mentions … but omits …", "That omission matters because …", "A fuller account would ask …"] },
  35: { kind: "listening", title: "Hear the confidence level", titleArabic: "استمع إلى درجة الثقة", objective: "Distinguish evidence, inference, and speculation in an expert briefing.", objectiveArabic: "ميّز بين الدليل والاستنتاج والتخمين في إحاطة خبير.", stage: "guided-practice", semantic: "activity", minutes: 23, speakingLines: [{ id: "analyst", speaker: "Analyst", text: "The early figures are consistent with an improvement, but they do not yet demonstrate that the intervention caused it. We can be reasonably confident about the pattern; the explanation remains provisional.", textArabic: "تتوافق الأرقام الأولية مع وجود تحسن، لكنها لا تثبت بعد أن التدخل سببه. ويمكننا أن نكون واثقين إلى حد معقول من النمط، أما التفسير فما زال مؤقتاً." }], sentencePatterns: ["The speaker is confident that …", "The evidence does not yet demonstrate …", "The explanation remains provisional because …"] },
  36: { kind: "standard", title: "Calibrate the sentence", titleArabic: "اضبط درجة الجملة", objective: "Use evidential verbs and modal language to avoid overstating a conclusion.", objectiveArabic: "استخدم أفعال الدليل ولغة الاحتمال لتجنب المبالغة في النتيجة.", stage: "guided-practice", semantic: "grammar", minutes: 21, sentencePatterns: ["The findings indicate … rather than prove …", "This may reflect …", "The conclusion should be treated as …"] },
  37: { kind: "interaction", title: "Mediate two voices", titleArabic: "توسّط بين صوتين", objective: "Summarise a disagreement between testimony and an institutional account without erasing either perspective.", objectiveArabic: "لخّص خلافاً بين شهادة وحساب مؤسسي دون إلغاء أي منظور.", stage: "real-context", semantic: "activity", minutes: 22, interactionTurns: [{ id: "resident", speaker: "Resident", text: "The service was redesigned without asking the people who depend on it.", textArabic: "أُعيد تصميم الخدمة دون سؤال الأشخاص الذين يعتمدون عليها.", purpose: "Represent lived experience." }, { id: "official", speaker: "Official", text: "The redesign followed the published consultation process and met the stated efficiency target.", textArabic: "اتبع التصميم الجديد عملية التشاور المنشورة وحقق هدف الكفاءة المعلن.", purpose: "Represent institutional evidence." }, { id: "you", speaker: "You", text: "The accounts agree on the change but differ over whose evidence defines a successful outcome.", textArabic: "يتفق الحسابان على حدوث التغيير لكنهما يختلفان حول الدليل الذي يحدد النتيجة الناجحة.", purpose: "Mediate without flattening." }] },
  38: { kind: "reading", title: "Compare testimony with policy", titleArabic: "قارن الشهادة بالسياسة", objective: "Assign different evidential roles to first-hand testimony and an institutional policy extract.", objectiveArabic: "امنح الشهادة المباشرة ومقتطف السياسة المؤسسية أدواراً مختلفة في الدليل.", stage: "real-context", semantic: "example", minutes: 26, readingText: "A resident describes the practical burden of an eligibility rule, while the policy extract explains why the rule was introduced. The testimony makes consequences visible; the extract establishes the intended design. A responsible synthesis keeps both roles in view before recommending a change.", readingTextArabic: "يصف أحد السكان العبء العملي لقاعدة أهلية، بينما يشرح مقتطف السياسة سبب إدخال القاعدة. وتجعل الشهادة العواقب مرئية؛ ويثبت المقتطف التصميم المقصود. ويحافظ التركيب المسؤول على الدورين قبل التوصية بتغيير.", sentencePatterns: ["The testimony contributes …", "The policy extract establishes …", "A fair synthesis would …"] },
  39: { kind: "standard", title: "Build a causal chain", titleArabic: "ابنِ سلسلة سببية", objective: "Represent a complex public cause-and-effect relationship without reducing it to one factor.", objectiveArabic: "مثّل علاقة سببية عامة معقدة دون اختزالها في عامل واحد.", stage: "explanation", semantic: "grammar", minutes: 20, sentencePatterns: ["The initial decision created …", "This contributed to … rather than directly causing …", "The outcome was shaped by …"] },
  40: { kind: "writing", title: "Turn causes into clear prose", titleArabic: "حوّل الأسباب إلى نثر واضح", objective: "Write a concise causal explanation using precise abstract noun phrases.", objectiveArabic: "اكتب شرحاً سببياً موجزاً باستخدام تراكيب اسمية مجردة دقيقة.", stage: "guided-practice", semantic: "grammar", minutes: 29, prompt: "Write 220–270 words explaining why a public service produced an uneven outcome. Use three precise abstract noun phrases, distinguish contribution from direct causation, and name one uncertainty.", promptArabic: "اكتب 220–270 كلمة تشرح لماذا أنتجت خدمة عامة نتيجة غير متساوية. استخدم ثلاثة تراكيب اسمية مجردة دقيقة، وميّز بين المساهمة والسبب المباشر، واذكر حالة عدم يقين واحدة.", sentencePatterns: ["The uneven outcome arose from …", "The policy's implementation contributed to …", "It would be premature to conclude that …"] },
  41: { kind: "speaking", title: "Explain a counterfactual", titleArabic: "اشرح حالة افتراضية", objective: "Use counterfactual reasoning to test whether a proposed intervention addresses the claimed cause.", objectiveArabic: "استخدم التفكير الافتراضي لاختبار ما إذا كان التدخل المقترح يعالج السبب المزعوم.", stage: "real-context", semantic: "activity", minutes: 23, speakingLines: [{ id: "you", speaker: "You", text: "If the access barrier were removed without changing the information provided, the result might improve only for people who already understand the system. That counterfactual suggests that access and explanation must be addressed together.", textArabic: "لو أزيل عائق الوصول دون تغيير المعلومات المقدمة، فقد تتحسن النتيجة فقط لمن يفهمون النظام أصلاً. ويشير هذا الافتراض المضاد إلى ضرورة معالجة الوصول والشرح معاً." }], sentencePatterns: ["If … were changed, … might …", "That counterfactual suggests …", "The intervention would not be sufficient unless …"] },
  42: { kind: "listening", title: "Follow an ethical condition", titleArabic: "تتبّع شرطاً أخلاقياً", objective: "Identify the condition that makes a speaker's recommendation ethically acceptable.", objectiveArabic: "حدّد الشرط الذي يجعل توصية المتحدث مقبولة أخلاقياً.", stage: "real-context", semantic: "activity", minutes: 24, speakingLines: [{ id: "chair", speaker: "Chair", text: "The pilot could proceed, provided that participation is genuinely voluntary, the data-use notice is understandable, and an independent review can stop the trial if harms emerge.", textArabic: "يمكن أن تبدأ التجربة بشرط أن تكون المشاركة طوعية حقاً، وأن يكون إشعار استخدام البيانات مفهوماً، وأن تتمكن مراجعة مستقلة من إيقاف التجربة إذا ظهرت أضرار." }], sentencePatterns: ["The recommendation is conditional on …", "The ethical safeguard protects …", "The trial should stop if …"] },
  43: { kind: "reading", title: "Synthesize a policy pair", titleArabic: "ركّب زوجاً من المصادر السياسية", objective: "Combine a policy extract and a community statement into one accurately attributed account.", objectiveArabic: "ادمج مقتطف سياسة وبياناً مجتمعياً في عرض واحد منسوب بدقة.", stage: "guided-practice", semantic: "example", minutes: 27, readingText: "The policy extract promises equal access through a standardised process. The community statement argues that equal rules can still produce unequal results when people begin with different resources. A synthesis should not choose a winner too early: it should state the shared intention, locate the disagreement, and identify what evidence would test the concern.", readingTextArabic: "يعد مقتطف السياسة بوصول متساوٍ عبر عملية موحدة. ويجادل البيان المجتمعي بأن القواعد المتساوية قد تنتج نتائج غير متساوية عندما يبدأ الناس بموارد مختلفة. ولا ينبغي للتركيب أن يختار فائزاً مبكراً؛ بل يذكر النية المشتركة، ويحدد موضع الخلاف، ويبين الدليل الذي يختبر القلق.", sentencePatterns: ["Both sources share …", "They diverge over …", "The relevant test would examine …"] },
  44: { kind: "writing", title: "Recommend a safeguard", titleArabic: "اقترح ضمانة", objective: "Write a formal recommendation that attributes evidence, acknowledges a limitation, and proposes a measurable safeguard.", objectiveArabic: "اكتب توصية رسمية تنسب الدليل وتعترف بحد وتقترح ضمانة قابلة للقياس.", stage: "real-context", semantic: "grammar", minutes: 31, prompt: "Write 250–320 words for a municipal committee using two provided sources. Recommend one safeguard, attribute two claims, acknowledge a limitation, and specify how its effect should be reviewed.", promptArabic: "اكتب 250–320 كلمة للجنة بلدية باستخدام مصدرين مقدمين. اقترح ضمانة واحدة، وانسب ادعاءين، واعترف بحد، وحدد كيف ينبغي مراجعة أثرها.", sentencePatterns: ["The evidence supports …, although …", "I recommend a safeguard requiring …", "Its effect should be reviewed by …"] },
  45: { kind: "review", title: "Retrieve the evidence moves", titleArabic: "استرجع حركات الدليل", objective: "Retrieve claim, qualification, attribution, causal, and conditional language in a new public scenario.", objectiveArabic: "استرجع لغة الادعاء والتقييد والنسبة والسبب والشرط في موقف عام جديد.", stage: "review", semantic: "retrieval", minutes: 22, sentencePatterns: ["The source establishes … but not …", "This may be explained by …", "The recommendation is defensible provided that …"] },
  46: { kind: "standard", title: "Reconcile policy and experience", titleArabic: "وفّق بين السياسة والتجربة", objective: "Synthesize policy evidence and first-hand testimony into a balanced formal proposal.", objectiveArabic: "ركّب دليل السياسة والشهادة المباشرة في اقتراح رسمي متوازن.", stage: "assessment", semantic: "assessment", minutes: 34, prompt: "Write 280–360 words for a local council committee reconciling a policy extract with testimony from affected residents. State the shared aim, explain the tension, recommend two practical interventions, and preserve appropriate uncertainty.", promptArabic: "اكتب 280–360 كلمة للجنة مجلس محلي توفّق بين مقتطف سياسة وشهادات السكان المتضررين. اذكر الهدف المشترك، واشرح التوتر، واقترح تدخلين عمليين، وحافظ على عدم اليقين المناسب.", sentencePatterns: ["The policy aims to …, whereas the testimony reveals …", "A balanced response would …", "The proposal should remain open to revision if …"] },
  47: { kind: "assessment", title: "Judge convenience and consent", titleArabic: "قيّم الراحة والموافقة", objective: "Defend a conditional position on a technology policy using counterfactual reasoning and multiple sources.", objectiveArabic: "دافع عن موقف مشروط من سياسة تقنية باستخدام التفكير الافتراضي ومصادر متعددة.", stage: "assessment", semantic: "assessment", minutes: 38, prompt: "Write 300–380 words to a data-protection board about a contactless convenience service. Weigh two sources, address a counterargument, state the consent condition, and explain what would make the policy unacceptable.", promptArabic: "اكتب 300–380 كلمة لمجلس حماية البيانات حول خدمة راحة لا تلامسية. وازن مصدرين، وعالج حجة مضادة، واذكر شرط الموافقة، واشرح ما الذي يجعل السياسة غير مقبولة.", sentencePatterns: ["The service could be justified if …", "Even if the benefit is real, …", "The policy would become unacceptable when …"] },
  48: { kind: "assessment", title: "Challenge a single story", titleArabic: "تحدَّ السردية الواحدة", objective: "Interpret conflicting sources about public representation and propose respectful, concrete change.", objectiveArabic: "فسّر مصادر متعارضة حول تمثيل عام واقترح تغييراً محترماً وملموساً.", stage: "assessment", semantic: "assessment", minutes: 40, prompt: "Write 320–400 words for a city arts council using a feature article, community statement, and museum policy extract. Identify the competing narratives, evaluate their evidence, and propose changes that address representational gaps without discarding artistic standards.", promptArabic: "اكتب 320–400 كلمة لمجلس فنون المدينة باستخدام مقال وبيان مجتمعي ومقتطف سياسة متحف. حدّد السرديات المتنافسة، وقيّم أدلتها، واقترح تغييرات تعالج فجوات التمثيل دون التخلي عن المعايير الفنية.", sentencePatterns: ["The prevailing narrative assumes …", "A more complete account would include …", "The proposed change is justified because …"] },
};

const check = (lesson: number): NonNullable<LessonActivity["retrievalCheck"]> => ({
  prompt: `Before leaving, explain the main evidence move from Lesson ${lesson} in one sentence.`,
  promptArabic: `قبل المغادرة، اشرح حركة الدليل الأساسية من الدرس ${lesson} في جملة واحدة.`,
  expectedEvidence: "A concise, qualified English sentence that names the lesson's evidence move.",
  expectedEvidenceArabic: "جملة إنجليزية موجزة ومقيدة تسمّي حركة الدليل في الدرس.",
});

const supports = (_lesson: number): NonNullable<LessonActivity["progressiveSupports"]> => [
  "worked-example",
  "tip",
  "external-ai-prompt",
];

export const c1Module3AuthoredActivities: Record<number, LessonActivity[]> = Object.fromEntries(
  Object.entries(specs).map(([lesson, spec]) => {
    const lessonNumber = Number(lesson);
    return [lessonNumber, [{
      ...spec,
      id: `c1-module-3-${lessonNumber}`,
      estimatedMinutes: spec.minutes,
      retrievalCheck: check(lessonNumber),
      progressiveSupports: supports(lessonNumber),
      ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}),
    }]];
  }),
) as Record<number, LessonActivity[]>;
