import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_2_EXPERIENCES: Record<number, LessonExperience> = {
  17: experience("notice", "light", "The module begins with a small distinction that makes institutional voice visible before the learner has to produce it.", ["orientation", "encounter", "notice", "next-bridge"], "A distinction between an institution's position and a personal recommendation.", "Sort the sentences, then explain what changes when the speaker moves from reporting to recommending.", "Formal voice carries responsibility for who is speaking and on what basis.", "Trace responsibility through a public document.", ["worked-example", "tip"]),
  18: experience("reading", "deep", "A responsibility-tracing document lets the learner follow a complex failure without collapsing it into a single blame claim.", ["encounter", "notice", "evidence"], "A public review of a service failure.", "Read for the decision, missed warning, and later response; mark how each contributes to responsibility.", "Accountable reading preserves complexity while still naming what could have been done.", "Report a claim with calibrated attribution.", ["word-support", "arabic-help", "extended-rationale"]),
  19: experience("grammar", "normal", "Stance grammar is taught as a decision about evidence weight rather than as an isolated list of modal forms.", ["retrieval", "notice", "supported-practice"], "A stance-and-attribution workshop.", "Choose the source marker and degree of certainty that fit each claim.", "A small grammatical choice can prevent a large overclaim.", "Hear obligation and recommendation in a public briefing.", ["worked-example", "tip"]),
  20: experience("listening", "normal", "The audio-first briefing makes obligation and qualification audible; transcript support stays secondary.", ["orientation", "encounter", "notice", "retrieval"], "A public briefing with a clear requirement and a qualified interpretation.", "Listen for what must happen and what may still change; reveal the transcript only to verify.", "Professional listening includes noticing how certainty is limited.", "Ask for clarification without escalating.", ["transcript", "worked-example"]),
  21: experience("interaction", "normal", "The interaction route rehearses clarification as a respectful public skill rather than a debate victory.", ["encounter", "meaningful-use"], "A colleague's confident policy claim.", "Acknowledge the concern, ask which groups were included, and request the evidence that could change the view.", "A precise question can widen the evidence without humiliating the speaker.", "Compare consultation language with policy response.", ["worked-example", "tip"]),
  22: experience("vocabulary", "light", "A short lexical comparison reduces overload while giving the learner control over institutional distinctions that recur in later writing.", ["retrieval", "notice", "next-bridge"], "A precision lab for formal recommendation words.", "Place obligation, recommendation, expectation, and contingency in realistic sentences.", "Near-synonyms differ in force, not only in dictionary meaning.", "Read how a response reframes public consultation.", ["worked-example", "word-support"]),
  23: experience("reading", "deep", "The paired-source route makes reframing visible and keeps the learner from treating policy language as a neutral mirror of consultation.", ["encounter", "notice", "meaningful-use", "evidence"], "A consultation summary beside a policy response.", "Identify what the public foregrounds and what the response turns into an implementation problem.", "A reframing may be legitimate, but it still changes what decision-makers see.", "Write a conditional recommendation.", ["word-support", "arabic-help", "extended-rationale"]),
  24: experience("writing", "deep", "The first formal production task asks for an accountable recommendation with a review condition, not a slogan.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A committee recommendation for a small service change.", "Attribute two claims, name uncertainty, and state what evidence should trigger review.", "A recommendation becomes trustworthy when its limits and future test are visible.", "Retrieve the accountable move across the module.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  25: experience("review", "normal", "The review lesson deliberately lowers density so the learner can reorganise the module's discourse moves before more public performance.", ["retrieval", "notice", "next-bridge"], "An accountable-language retrieval studio.", "Apply attribution, qualification, and counterargument to a new institutional scenario.", "Retrieval is strongest when a familiar move works in an unfamiliar context.", "Explain a decision in public.", ["worked-example", "tip"]),
  26: experience("speaking", "normal", "The speaking route converts the module's analysis into a concise public explanation with visible trade-offs.", ["encounter", "meaningful-use"], "A short public decision explanation.", "State the rationale, name the trade-off, and give a condition for revising the approach.", "Public clarity is not the same as hiding complexity.", "Listen for a concession in committee debate.", ["worked-example", "tip"]),
  27: experience("listening", "deep", "A committee exchange makes concession and rebuttal audible as a sequence rather than as isolated discourse markers.", ["encounter", "notice", "meaningful-use", "evidence"], "A disagreement about a service pilot.", "Listen for the accepted point, the remaining concern, and the condition attached to it.", "A concession can narrow a disagreement without ending it.", "Mediate expertise for a public audience.", ["transcript", "worked-example", "extended-rationale"]),
  28: experience("real-world", "normal", "The mediation route makes register choice practical by asking the learner to carry a technical limitation into public language.", ["retrieval", "encounter", "meaningful-use"], "A specialist finding that needs public explanation.", "Explain the meaningful pattern and preserve the causal limitation in plain English.", "Good mediation simplifies access, not the truth conditions of a claim.", "Concede and reposition a public argument.", ["worked-example", "word-support"]),
  29: experience("grammar", "normal", "Concession grammar is placed after several public reasoning tasks so its value is felt as a rhetorical move.", ["retrieval", "notice", "supported-practice"], "A concession-and-reposition workshop.", "Acknowledge a valid objection, then narrow the claim or redirect the recommendation.", "A concession can make a position stronger by showing what it can survive.", "Evaluate evidence and audience together.", ["worked-example", "tip"]),
  30: experience("reading", "deep", "The paired speech and technical note prepare the learner for assessment by separating genre purpose from evidence weight.", ["encounter", "notice", "evidence"], "A ministerial speech beside a technical note.", "Ask what each genre is designed to do, then combine their useful evidence without treating either as complete.", "Audience and evidence interact, but persuasive force is not proof.", "Revise the same recommendation for another reader.", ["word-support", "arabic-help", "extended-rationale"]),
  31: experience("writing", "deep", "Audience revision provides a final independent production rehearsal before the module synthesis assessment.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "One recommendation written for two audiences.", "Keep attribution and uncertainty while changing register, explicitness, and next-step framing.", "Adaptation changes the route into the idea, not the integrity of the idea.", "Build an accountable public response.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  32: experience("assessment", "deep", "The module assessment integrates source comparison, accountable stance, audience awareness, and review conditions in one defensible response.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A source-aware public response.", "Identify the disagreement, attribute claims, qualify a limit, recommend proportionate action, and state the review trigger.", "C1 institutional voice is precise, transparent, and willing to revise.", "Record one transferable strength before Module 3.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_2_EXPERIENCES;
