import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_1_EXPERIENCES: Record<number, LessonExperience> = {
  1: experience("reading", "normal", "The module begins with paired sources so implication is discovered through contrast rather than announced as a rule.", ["orientation", "encounter", "notice", "evidence"], "A paired-source reading about green corridors.", "Read once for the central difference, then mark what each source foregrounds and leaves unsaid.", "C1 interpretation includes the frame around a claim, not only the claim itself.", "Test a contested claim's method and limits.", ["word-support", "extended-rationale"]),
  2: experience("notice", "light", "A short claim audit creates a deliberate pause after the opening reading and isolates method from conclusion.", ["retrieval", "notice", "next-bridge"], "A claim-and-method inspection.", "Match each assertion to the method and limitation that qualifies it.", "A confident sentence can still rest on a narrow method.", "Listen for how a speaker calibrates uncertainty.", ["worked-example", "tip"]),
  3: experience("listening", "normal", "An audio-first analyst briefing makes probability language a listening-and-reporting skill; the transcript remains secondary.", ["orientation", "encounter", "notice", "retrieval"], "A briefing about early evidence.", "Listen for what is known, suspected, and unresolved; reveal the transcript only to verify.", "Small changes in probability language change the weight of a report.", "Compare disagreement between written sources.", ["transcript", "worked-example"]),
  4: experience("reading", "normal", "The learner synthesises two apparently conflicting reports instead of choosing a winner too early.", ["encounter", "notice", "meaningful-use", "evidence"], "A source-comparison reading.", "Compare populations, purposes, and omissions before proposing a shared question.", "Disagreement may reveal different measures rather than a simple error.", "Write a proportionate conclusion.", ["word-support", "extended-rationale"]),
  5: experience("writing", "deep", "The first production checkpoint asks for a formal conclusion with a concession and measured next step.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A committee conclusion about a greening pilot.", "Use two evidence points, concede one objection, and recommend a proportionate next step.", "A conclusion should show what the evidence supports and where it stops.", "Bring policy evidence together with lived experience.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  6: experience("interaction", "normal", "A human testimony exchange prevents the evidence work from becoming abstract and rehearses respectful negotiation.", ["orientation", "encounter", "meaningful-use"], "A public-service conversation.", "Acknowledge the resident's experience, then balance it with the policy figures.", "Averages can hide access costs that testimony makes visible.", "Question convenience through an ethical counterfactual.", ["worked-example", "tip"]),
  7: experience("speaking", "normal", "The speaking route uses a compact ethical dilemma to practise counterfactual reasoning without adding another long essay.", ["retrieval", "encounter", "meaningful-use"], "A spoken challenge about data convenience.", "State the strongest convenience argument, then test it against consent and responsibility.", "Counterfactuals expose the value a convenient design may be sacrificing.", "Read a representation that needs more than one story.", ["worked-example", "tip"]),
  8: experience("reading", "normal", "A paired-perspective reading develops respectful critique and prepares the learner to define progress through competing indicators.", ["encounter", "notice", "meaningful-use", "evidence"], "A tourism story and a residents' archive.", "Identify the visible perspective, the absent perspective, and the question that joins them.", "Adding a perspective can make a judgement more accountable rather than simply negative.", "Write a definition of progress for a public reader.", ["word-support", "extended-rationale"]),
  9: experience("writing", "deep", "The second writing task widens the evidence frame and asks the learner to define a contested concept for a public audience.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A policy-magazine definition of progress.", "Balance economic, environmental, and lived-experience indicators in one recommendation.", "Definitions carry hidden priorities; make those priorities visible.", "Trace the distributional cost of a decision.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  10: experience("reading", "normal", "A concrete transport case makes allocation trade-offs visible without requiring a second production task immediately after writing.", ["encounter", "notice", "evidence"], "A reading about routes, speed, and access.", "Map the headline gain, the unintended effect, and the mitigation the policy owes users.", "A policy can be efficient overall while distributing costs unfairly.", "Design a space where disagreement can work productively.", ["word-support", "extended-rationale"]),
  11: experience("interaction", "normal", "The deliberation route shifts from analysing public decisions to designing a process that can hear disagreement.", ["orientation", "encounter", "meaningful-use"], "A meeting-design negotiation.", "Recognise the chair's time concern and propose a structure that keeps affected voices present.", "Diplomatic rebuttal protects both decision quality and practical constraints.", "Retrieve how historical precedent can inform, but not prove, an argument.", ["worked-example", "tip"]),
  12: experience("review", "light", "A compact retrieval lesson gives the learner a lower-load return to earlier evidence habits before the final stretch.", ["retrieval", "notice", "next-bridge"], "A historical-precedent retrieval studio.", "Connect one precedent to a present consequence and name the limit of the analogy.", "Historical relevance is not the same as historical proof.", "Reframe cultural change for different audiences.", ["worked-example", "tip"]),
  13: experience("listening", "normal", "An audio-first curator explanation develops audience adaptation and keeps cultural analysis from becoming a static definition exercise.", ["encounter", "notice", "meaningful-use"], "A curator's explanation of culture in motion.", "Listen for the metaphor, then adapt the explanation for a general audience and a specialist audience.", "Audience changes what must be made explicit, not what must be made simplistic.", "Attribute expert claims with appropriate caution.", ["transcript", "worked-example", "extended-rationale"]),
  14: experience("reading", "normal", "The specialist dossier distinguishes authority from evidence and makes uncertainty an object of careful reading.", ["encounter", "notice", "evidence"], "A reading about three flood-model specialists.", "Track each expert's confidence, data basis, and request for corroboration.", "Expert status does not erase differences in evidence weight.", "Write a review whose recommendation has consequences.", ["word-support", "extended-rationale"]),
  15: experience("writing", "deep", "The final meaningful-use writing task prepares the learner for assessment by balancing critique, concession, and user consequences.", ["retrieval", "supported-practice", "meaningful-use", "evidence"], "A public-service redesign review.", "Write for a real reader: name a strength, limitations, concession, recommendation, and likely consequence.", "A useful review makes the next decision more responsible.", "Transform specialist material into a readable brief.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  16: experience("assessment", "deep", "The module checkpoint requires transfer across implication, uncertainty, trade-offs, attribution, and audience-sensitive recommendation.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A source-aware public brief.", "Explain the finding, qualify uncertainty, compare trade-offs, and recommend action with a review condition.", "C1 judgement is precise without pretending complexity has disappeared.", "Record one transferable strength before Module 2.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_1_EXPERIENCES;
