import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string,
  stages: LessonExperience["selectedStages"], whatItIs: string, whatToDo: string, whatMatters: string,
  whatNext: string, progressiveSupports: LessonExperience["progressiveSupports"],
): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages: stages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

export const C1_MODULE_7_EXPERIENCES: Record<number, LessonExperience> = {
  97: experience("interaction", "normal", "The module opens with a live objection so proposal language is experienced as a social responsibility, not a formula.", ["orientation", "encounter", "meaningful-use", "retrieval"], "A proposal-under-pressure negotiation.", "Acknowledge the concern, defend one conditional recommendation, and name its safeguard.", "A careful proposal can remain actionable without pretending that risk has disappeared.", "Question the certainty of a claim.", ["worked-example", "arabic-help", "tip"]),
  98: experience("grammar", "normal", "A focused stance workshop gives the learner a precise language tool before the next listening task.", ["retrieval", "notice", "supported-practice"], "A certainty-calibration workshop.", "Rewrite an absolute claim so the wording matches the evidence.", "Hedging is not weakness when it tells the truth about limits.", "Follow a crowded debate.", ["worked-example", "tip", "arabic-help"]),
  99: experience("listening", "normal", "The short exchange foregrounds concession and implied priority before the learner must synthesize written sources.", ["encounter", "notice", "retrieval"], "A crowded-debate listening briefing.", "Listen first for the finding, then for what the speaker refuses to claim.", "A responsible listener tracks boundaries as well as conclusions.", "Synthesize two perspectives with integrity.", ["transcript", "worked-example"]),
  100: experience("integration", "deep", "The first ten-lesson checkpoint asks the learner to combine evidence and consequence without turning the work into a full module test.", ["orientation", "retrieval", "meaningful-use", "evidence", "next-bridge"], "A synthesis checkpoint.", "Compare two accounts, preserve their different questions, and write a proportionate next step.", "Integrity means retaining a relevant limitation when it complicates the headline.", "Read framing and omission more closely.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  101: experience("reading", "deep", "The paired framing task makes omission and foregrounding visible through a bounded public controversy.", ["encounter", "notice", "evidence", "retrieval"], "A between-the-lines reading studio.", "Mark what each source states, foregrounds, and leaves implicit.", "Interpretation begins with noticing what the wording makes easier to see.", "Put a research claim under scrutiny.", ["word-support", "arabic-help", "extended-rationale"]),
  102: experience("reading", "deep", "Method comparison follows framing so the learner moves from language-level interpretation to evidence-level scrutiny.", ["retrieval", "notice", "supported-practice", "evidence"], "A methods-comparison reading.", "Compare samples, timeframes, and comparison groups before calibrating the claim.", "A stronger design changes confidence; it does not erase every uncertainty.", "Make uncertainty audible.", ["word-support", "worked-example", "extended-rationale"]),
  103: experience("grammar", "normal", "The language focus is deliberately narrow: stance adverbials and reporting verbs become tools for accurate public reasoning.", ["retrieval", "notice", "supported-practice", "meaningful-use"], "A stance-and-reporting language lab.", "Choose a reporting verb and stance phrase that fit the strength of the evidence.", "Precision lets a speaker be useful without becoming overconfident.", "Hear disagreement in a real exchange.", ["worked-example", "tip", "arabic-help"]),
  104: experience("listening", "normal", "A two-voice briefing makes disagreement audible and keeps the transcript behind a deliberate disclosure step.", ["encounter", "notice", "supported-practice", "retrieval"], "An evidence-disagreement listening lab.", "Identify each speaker's evidence, reservation, and proposed transparency measure.", "Disagreement can become a better review design when its basis is made explicit.", "Write a conclusion rather than a slogan.", ["transcript", "worked-example", "tip"]),
  105: experience("writing", "deep", "The conclusion task concentrates the module's evidence moves into a bounded formal recommendation with a review date.", ["retrieval", "meaningful-use", "evidence"], "A proportionate-conclusion writing studio.", "State the support, concede an objection, and recommend one reviewable action.", "A conclusion earns trust by showing what would change it.", "Combine technical evidence with lived experience.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
  106: experience("reading", "deep", "The lesson protects the difference between measured outcome and lived burden through paired accounts.", ["encounter", "notice", "evidence", "retrieval"], "A technical-and-lived-experience reading.", "Record the question each account answers and the burden it makes visible.", "Different kinds of evidence can remain distinct and still belong in one fair proposal.", "Question the ethics of convenience.", ["word-support", "worked-example", "extended-rationale"]),
  107: experience("real-world", "normal", "A conditional interaction turns abstract consent language into a practical design decision about convenience and responsibility.", ["retrieval", "encounter", "meaningful-use"], "A consent-and-convenience design dilemma.", "Use a counterfactual to test whether a benefit justifies an avoidable cost.", "A possible benefit is not automatically a sufficient ethical justification.", "Challenge a single story.", ["worked-example", "arabic-help", "tip"]),
  108: experience("reading", "deep", "Representation is treated as a process-and-power question, requiring synthesis rather than a slogan about inclusion.", ["retrieval", "notice", "evidence", "next-bridge"], "A representation and decision-power reading.", "Trace who was invited, who decided, and when participation became possible.", "Visibility in the final product is not the same as influence over the process.", "Compare competing measures of progress.", ["word-support", "arabic-help", "extended-rationale"]),
  109: experience("listening", "normal", "The indicators briefing lets the learner infer the trade-off hidden inside a seemingly neutral metric.", ["encounter", "notice", "meaningful-use", "retrieval"], "An indicators-and-distribution listening briefing.", "Listen for the metric being privileged and the outcome it may conceal.", "Choosing a metric is also choosing what a public decision will count.", "Retrieve the costs of a decision.", ["transcript", "worked-example", "tip"]),
  110: experience("review", "normal", "A transfer review deliberately reuses the module's evidence moves in a fresh allocation problem rather than adding another theory lesson.", ["retrieval", "meaningful-use", "evidence"], "A resource-allocation retrieval lab.", "Compare sources, forecast one knock-on effect, and attach one mitigation.", "Retrieval becomes durable when a familiar move travels to a new decision.", "Design a forum for disagreement.", ["worked-example", "external-ai-prompt"]),
  111: experience("speaking", "normal", "The forum proposal requires live diplomatic rebuttal and makes participation mechanisms concrete.", ["retrieval", "meaningful-use", "evidence"], "A deliberative-design speaking rehearsal.", "Answer a sceptical stakeholder, define decision points, and explain the evidence trail.", "Participation needs a mechanism, not merely an invitation.", "Complete the historical-claim assessment.", ["worked-example", "tip"]),
  112: experience("assessment", "deep", "The module closes with a fresh archival dossier and a consequential recommendation, transferring every major evidence move to a new context.", ["orientation", "retrieval", "encounter", "meaningful-use", "evidence", "next-bridge"], "A historical-judgement synthesis challenge.", "Compare provenance, qualify uncertainty, answer an objection, and defend a reviewable recommendation.", "C1 judgement combines precise attribution, fair representation, calibrated confidence, and responsible action.", "Record one evidence skill to carry into Module 8.", ["worked-example", "external-ai-prompt", "extended-rationale"]),
};

export default C1_MODULE_7_EXPERIENCES;
