import type { LessonActivity } from "./types";

type Spec = Omit<LessonActivity, "id" | "estimatedMinutes" | "retrievalCheck" | "progressiveSupports" | "writingPrompt" | "writingPromptArabic"> & { minutes: number; prompt?: string; promptArabic?: string };

const specs: Record<number, Spec> = {
  65: { kind: "reading", title: "Map the integrity problem", titleArabic: "ارسم خريطة لمشكلة النزاهة", objective: "Identify the competing values and hidden assumptions in a formal proposal.", objectiveArabic: "حدّد القيم المتنافسة والافتراضات الخفية في مقترح رسمي.", stage: "introduction", semantic: "example", minutes: 24, readingText: "A procurement brief celebrates speed, while its appendix records that the fastest supplier has never disclosed how subcontractors are paid. The proposal is not automatically corrupt, but its confidence exceeds the evidence. A responsible reader asks which safeguards would make the recommendation trustworthy.", readingTextArabic: "يحتفي موجز مشتريات بالسرعة، بينما يسجل ملحقه أن أسرع مورّد لم يوضح قط كيف تُدفع أجور المتعاقدين الفرعيين. لا يعني ذلك أن المقترح فاسد تلقائياً، لكن ثقته تتجاوز دليله. ويسأل القارئ المسؤول عن الضمانات التي تجعل التوصية جديرة بالثقة.", sentencePatterns: ["The proposal assumes that …", "The missing safeguard is …", "Its confidence is disproportionate to …"] },
  66: { kind: "standard", title: "Distinguish risk from wrongdoing", titleArabic: "ميّز بين الخطر والخطأ", objective: "Use precise conditional language to distinguish a foreseeable risk from an established breach.", objectiveArabic: "استخدم لغة شرطية دقيقة للتمييز بين خطر متوقع ومخالفة مثبتة.", stage: "explanation", semantic: "grammar", minutes: 19, sentencePatterns: ["If the disclosure is incomplete, …", "This would constitute a breach only if …", "The risk should not be treated as proof that …"] },
  67: { kind: "listening", title: "Hear the cautious disclosure", titleArabic: "استمع إلى الإفصاح الحذر", objective: "Extract degrees of certainty and responsibility from a compliance officer’s spoken briefing.", objectiveArabic: "استخرج درجات اليقين والمسؤولية من إحاطة شفوية لمسؤول امتثال.", stage: "guided-practice", semantic: "activity", minutes: 22, speakingLines: [{ id: "officer", speaker: "Compliance officer", text: "We have not found evidence of deliberate concealment, although the reporting gap is serious enough to require an independent review.", textArabic: "لم نجد دليلاً على إخفاء متعمد، رغم أن فجوة الإبلاغ خطيرة بما يكفي لتتطلب مراجعة مستقلة." }], sentencePatterns: ["The officer rules out … but maintains that …", "The wording is cautious because …", "The appropriate next step would be …"] },
  68: { kind: "reading", title: "Compare safeguards", titleArabic: "قارن بين الضمانات", objective: "Compare two governance mechanisms by weighing their reach, cost, and enforceability.", objectiveArabic: "قارن بين آليتي حوكمة من خلال موازنة نطاقهما وتكلفتهما وقابليتهما للإنفاذ.", stage: "real-context", semantic: "example", minutes: 25, readingText: "One safeguard requires suppliers to publish an annual statement; another gives an independent panel access to live records. The first is visible and inexpensive but delayed. The second is intrusive and costly yet capable of detecting problems before a public failure. Neither mechanism is sufficient in every context.", readingTextArabic: "تُلزم إحدى الضمانات المورّدين بنشر بيان سنوي، بينما تمنح أخرى لجنة مستقلة حق الوصول إلى السجلات الحية. الأولى واضحة وقليلة التكلفة لكنها متأخرة. والثانية تدخلية ومكلفة لكنها قادرة على اكتشاف المشكلات قبل فشل علني. ولا تكفي أي آلية في كل سياق.", sentencePatterns: ["The advantage of … is offset by …", "Compared with …, the panel would …", "A proportionate design would combine …"] },
  69: { kind: "writing", title: "Frame a defensible objection", titleArabic: "صغ اعتراضاً يمكن الدفاع عنه", objective: "Write a formal objection that identifies a material weakness without overstating the case.", objectiveArabic: "اكتب اعتراضاً رسمياً يحدد نقطة ضعف جوهرية دون المبالغة في القضية.", stage: "guided-practice", semantic: "grammar", minutes: 30, prompt: "Write 220–260 words to a review committee objecting to a proposal whose conflict-of-interest disclosure is incomplete. State the concern, acknowledge what remains unknown, and request one proportionate remedy.", promptArabic: "اكتب 220–260 كلمة إلى لجنة مراجعة تعترض فيها على مقترح إفصاحه عن تضارب المصالح غير مكتمل. اذكر القلق، واعترف بما لا يزال مجهولاً، واطلب علاجاً واحداً متناسباً.", sentencePatterns: ["The concern is not that … but that …", "It would be premature to allege …", "I therefore recommend that …"] },
  70: { kind: "interaction", title: "Negotiate a disclosure standard", titleArabic: "تفاوض على معيار للإفصاح", objective: "Negotiate a minimum disclosure standard while recognising operational constraints.", objectiveArabic: "تفاوض على حد أدنى للإفصاح مع الاعتراف بالقيود التشغيلية.", stage: "real-context", semantic: "activity", minutes: 23, interactionTurns: [{ id: "director", speaker: "Director", text: "A full disclosure register would delay the launch by three months.", textArabic: "سيؤخر سجل الإفصاح الكامل الإطلاق ثلاثة أشهر.", purpose: "Recognise the constraint." }, { id: "you", speaker: "You", text: "A complete register may be impractical at this stage, but a public minimum could require … .", textArabic: "قد يكون السجل الكامل غير عملي في هذه المرحلة، لكن حداً أدنى علنياً يمكن أن يطلب … .", purpose: "Propose a proportionate standard." }] },
  71: { kind: "speaking", title: "Answer an adversarial question", titleArabic: "أجب عن سؤال عدائي", objective: "Respond calmly to a challenge by conceding a limit and returning to the evidence.", objectiveArabic: "أجب بهدوء عن تحدٍّ من خلال الاعتراف بحدّ وإعادة النقاش إلى الدليل.", stage: "real-context", semantic: "activity", minutes: 20, speakingLines: [{ id: "journalist", speaker: "Journalist", text: "Are you accusing the organisation of misconduct, or are you simply creating a scandal?", textArabic: "هل تتهم المنظمة بسوء السلوك أم أنك تخلق فضيحة فحسب؟" }, { id: "you", speaker: "You", text: "I am not claiming misconduct has been established. I am saying the evidence warrants … .", textArabic: "لا أقول إن سوء السلوك ثبت. أقول إن الدليل يبرر … ." }] },
  72: { kind: "reading", title: "Follow the audit trail", titleArabic: "تتبّع مسار التدقيق", objective: "Reconstruct how a decision moved from evidence to recommendation and locate the point where accountability weakened.", objectiveArabic: "أعد بناء انتقال القرار من الدليل إلى التوصية وحدد النقطة التي ضعفت فيها المساءلة.", stage: "real-context", semantic: "example", minutes: 24, readingText: "The audit trail begins with a small pilot, passes through an internal summary, and ends in a public announcement that presents the result as settled. The critical shift occurs when the summary removes the pilot’s comparison group. The announcement is not fabricated, but its apparent certainty has been manufactured by omission.", readingTextArabic: "يبدأ مسار التدقيق بتجربة صغيرة، ويمر عبر ملخص داخلي، وينتهي بإعلان عام يعرض النتيجة كأنها محسومة. يحدث التحول الحاسم حين يحذف الملخص مجموعة المقارنة في التجربة. الإعلان ليس مختلقاً، لكن يقينه الظاهر صُنِع بالحذف.", sentencePatterns: ["The decision changes register when …", "Accountability weakens at the point where …", "The omission matters because …"] },
  73: { kind: "review", title: "Retrieve the language of restraint", titleArabic: "استرجع لغة التحفظ", objective: "Retrieve calibrated reporting language and apply it to a new integrity scenario.", objectiveArabic: "استرجع لغة الإبلاغ الدقيقة وطبقها على سيناريو جديد للنزاهة.", stage: "review", semantic: "retrieval", minutes: 18, sentencePatterns: ["The evidence suggests … rather than proves …", "It remains unclear whether …", "A defensible conclusion would be …"] },
  74: { kind: "listening", title: "Listen for what is not said", titleArabic: "استمع إلى ما لم يُقل", objective: "Infer a speaker’s omitted assumption without presenting an inference as a fact.", objectiveArabic: "استنتج الافتراض المحذوف لدى المتحدث دون عرض الاستنتاج كحقيقة.", stage: "guided-practice", semantic: "activity", minutes: 23, speakingLines: [{ id: "consultant", speaker: "Consultant", text: "The framework is ready for adoption. The remaining questions can be resolved during implementation.", textArabic: "الإطار جاهز للتطبيق. ويمكن حل الأسئلة المتبقية أثناء التنفيذ." }], sentencePatterns: ["The speaker appears to assume …", "This may be reasonable if …", "However, the unresolved question concerns …"] },
  75: { kind: "interaction", title: "Protect a dissenting voice", titleArabic: "احمِ صوتاً مخالفاً", objective: "Facilitate disagreement by reformulating a dissenting concern accurately before responding.", objectiveArabic: "أدر الاختلاف بإعادة صياغة القلق المخالف بدقة قبل الرد عليه.", stage: "real-context", semantic: "activity", minutes: 22, interactionTurns: [{ id: "reviewer", speaker: "Reviewer", text: "The proposal treats affected people as data points rather than participants.", textArabic: "يعامل المقترح الأشخاص المتأثرين كبيانات لا كمشاركين.", purpose: "Represent dissent fairly." }, { id: "you", speaker: "You", text: "Your concern is that consultation is being used to legitimise a decision already made. We could respond by … .", textArabic: "قلقك هو أن التشاور يُستخدم لإضفاء الشرعية على قرار اتُخذ مسبقاً. ويمكننا الرد عبر … .", purpose: "Clarify and respond." }] },
  76: { kind: "reading", title: "Read a formal recommendation", titleArabic: "اقرأ توصية رسمية", objective: "Evaluate whether a formal recommendation matches its evidence, scope, and stated safeguards.", objectiveArabic: "قيّم ما إذا كانت توصية رسمية تتوافق مع دليلها ونطاقها وضماناتها المعلنة.", stage: "independent-practice", semantic: "example", minutes: 26, readingText: "The recommendation asks the board to approve a limited pilot, publish its data, and review the result after six months. Its evidence is local rather than universal, but its wording preserves that limitation. The strongest feature is not certainty; it is the mechanism that allows the claim to be tested.", readingTextArabic: "تطلب التوصية من المجلس الموافقة على تجربة محدودة ونشر بياناتها ومراجعة النتيجة بعد ستة أشهر. دليلها محلي لا شامل، لكن صياغتها تحافظ على هذا الحد. وقوتها الأساسية ليست اليقين، بل الآلية التي تسمح باختبار الادعاء.", sentencePatterns: ["The recommendation stays within scope by …", "Its safeguard makes the claim …", "The remaining limitation is …"] },
  77: { kind: "writing", title: "Draft the formal proposal", titleArabic: "اكتب المقترح الرسمي", objective: "Draft a formal proposal that links evidence, safeguards, implementation, and review.", objectiveArabic: "اكتب مقترحاً رسمياً يربط بين الدليل والضمانات والتنفيذ والمراجعة.", stage: "independent-practice", semantic: "grammar", minutes: 32, prompt: "Write 260–320 words proposing a limited public-sector pilot. Include the evidence base, one material uncertainty, two safeguards, an implementation condition, and a review trigger.", promptArabic: "اكتب 260–320 كلمة تقترح فيها تجربة محدودة في القطاع العام. أدرج قاعدة الدليل، وعدم يقين جوهرياً واحداً، وضمانتين، وشرطاً للتنفيذ، ومحفزاً للمراجعة.", sentencePatterns: ["The proposal is based on …", "Implementation should proceed only if …", "The pilot should be reviewed when …"] },
  78: { kind: "standard", title: "Test proportionality", titleArabic: "اختبر التناسب", objective: "Use concessive and comparative structures to test whether a safeguard is proportionate to a risk.", objectiveArabic: "استخدم تراكيب التنازل والمقارنة لاختبار ما إذا كانت الضمانة متناسبة مع الخطر.", stage: "explanation", semantic: "grammar", minutes: 19, sentencePatterns: ["Although the risk is …, the safeguard may be …", "A less intrusive measure would …", "The requirement is proportionate insofar as …"] },
  79: { kind: "speaking", title: "Deliver the integrity briefing", titleArabic: "قدّم إحاطة عن النزاهة", objective: "Deliver a concise oral briefing that distinguishes findings, inferences, and recommendations.", objectiveArabic: "قدّم إحاطة شفوية موجزة تميز بين النتائج والاستنتاجات والتوصيات.", stage: "independent-practice", semantic: "activity", minutes: 24, speakingLines: [{ id: "briefing", speaker: "Briefing chair", text: "You have three minutes. What has been established, what remains uncertain, and what should we do next?", textArabic: "لديك ثلاث دقائق. ما الذي ثبت، وما الذي لا يزال غير مؤكد، وماذا ينبغي أن نفعل تالياً؟" }, { id: "you", speaker: "You", text: "The evidence establishes … . It does not establish … . I therefore recommend … .", textArabic: "يثبت الدليل … . لكنه لا يثبت … . ولذلك أوصي بـ … ." }] },
  80: { kind: "assessment", title: "Integrity proposal checkpoint", titleArabic: "نقطة تحقق: مقترح النزاهة", objective: "Synthesize the module’s evidence, restraint, dialogue, and formal proposal skills in one defensible recommendation.", objectiveArabic: "ركّب مهارات الدليل والتحفظ والحوار والمقترح الرسمي في توصية واحدة يمكن الدفاع عنها.", stage: "assessment", semantic: "assessment", minutes: 35, prompt: "Prepare a 300–360 word recommendation and a 90-second spoken summary for a review board deciding whether to approve a monitored pilot.", promptArabic: "حضّر توصية من 300–360 كلمة وملخصاً شفوياً مدته 90 ثانية لمجلس مراجعة يقرر ما إذا كان سيوافق على تجربة مراقبة.", sentencePatterns: ["The evidence is sufficient to … but not to …", "The integrity condition is …", "The recommendation should be revisited if …"] },
};

const check = (lesson: number): LessonActivity["retrievalCheck"] => ({
  prompt: `Before leaving, state the integrity move from Lesson ${lesson} in one precise English sentence.`,
  promptArabic: `قبل المغادرة، اذكر حركة النزاهة من الدرس ${lesson} في جملة إنجليزية دقيقة واحدة.`,
  expectedEvidence: "A concise, qualified English sentence that applies the lesson's evidence or accountability move.",
  expectedEvidenceArabic: "جملة إنجليزية موجزة ومقيدة تطبق حركة الدليل أو المساءلة في الدرس.",
});

const supports = (_lesson: number): NonNullable<LessonActivity["progressiveSupports"]> => ["worked-example", "tip", "external-ai-prompt"];

export const c1Module5AuthoredActivities: Record<number, LessonActivity[]> = Object.fromEntries(
  Object.entries(specs).map(([lesson, spec]) => {
    const lessonNumber = Number(lesson);
    return [lessonNumber, [{ ...spec, id: `c1-module-5-${lessonNumber}`, estimatedMinutes: spec.minutes, retrievalCheck: check(lessonNumber), progressiveSupports: supports(lessonNumber), ...(spec.prompt ? { writingPrompt: spec.prompt, writingPromptArabic: spec.promptArabic } : {}) }]];
  }),
) as Record<number, LessonActivity[]>;

export default c1Module5AuthoredActivities;

