import type { LessonExperience } from "./types";
const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages: LessonExperience["intentionallyOmittedStages"] = []): LessonExperience => ({ archetype, density, archetypeRationale: rationale, selectedStages, intentionallyOmittedStages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });
export const C2_MODULE_3_EXPERIENCES: Record<number, LessonExperience> = {
31: experience("interaction", "normal", "The module begins with an institutional question that must expose stakes before evidence is selected.", "A public-question framing studio / استوديو صياغة السؤال العام", "Turn the contested problem into a question, then test who is affected and what remains unresolved.", "A precise question prevents a polished answer from solving the wrong problem.", "Carry visible stakes into institutional reading.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
32: experience("reading", "deep", "Institutional prose is read for agency, responsibility, and risk hidden by calm wording.", "An accountability reading lab / مختبر قراءة المساءلة", "Annotate what the text says, omits, and leaves assignable without inventing facts.", "Critical reading restores agency cautiously; it does not replace evidence with suspicion.", "Hear how uncertainty is qualified under pressure.", ["orientation","encounter","notice","supported-practice","retrieval","evidence","next-bridge"], ["word-support","extended-rationale","arabic-help"]),
33: experience("listening", "normal", "The audio route makes qualification audible when the audience presses for a binary answer.", "An uncertainty listening lab / مختبر الاستماع إلى عدم اليقين", "Listen once for the finding and again for its boundary; reveal the transcript after notes.", "Responsible confidence answers usefully without erasing conditions.", "Make hidden conditions explicit in grammar.", ["orientation","encounter","notice","retrieval","evidence","next-bridge"], ["transcript","arabic-help","tip"], [{ stage: "supported-practice", reason: "The first pass is deliberately unaided." }]),
34: experience("grammar", "light", "Conditional inversion and concession are used as judgement tools, not isolated grammar drills.", "A condition-and-concession clinic / عيادة الشرط والتنازل", "Revise absolute claims so their conditions and limits are visible.", "Form carries epistemic responsibility when evidence is conditional.", "Use the calibration in a public recommendation.", ["orientation","notice","supported-practice","retrieval","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "encounter", reason: "The examples carry the context." }]),
35: experience("writing", "deep", "The learner must make one defensible recommendation while naming values, risk, and revision evidence.", "A constrained-judgement memo / مذكرة حكم في ظل القيود", "Write the recommendation, strongest competing value, implementation risk, and revision trigger.", "A judgement is stronger when its limits are inspectable.", "Explain the position aloud to a mixed audience.", ["orientation","notice","supported-practice","meaningful-use","retrieval","evidence","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
36: experience("speaking", "normal", "Public explanation is treated as respectful mediation between expertise and concern.", "A mixed-audience explanation rehearsal / تدريب شرح لجمهور متنوع", "Deliver a short explanation that reduces processing effort without patronising the listener.", "Accessibility is not simplification of thought; it is careful design of the route into it.", "Compare aggregate and situated evidence.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "supported-practice", reason: "One model and one rehearsal are enough for this speaking objective." }]),
37: experience("reading", "deep", "Two evidence types are compared by what each can show, not by an automatic hierarchy.", "A triangulation reading studio / استوديو قراءة التثليث", "Compare the indicator and testimony, then state the question each source answers.", "Pattern and lived experience become more useful when their scopes are explicit.", "Negotiate a reviewable compromise.", ["orientation","encounter","notice","supported-practice","retrieval","evidence","next-bridge"], ["word-support","extended-rationale","arabic-help"]),
38: experience("interaction", "normal", "The compromise route turns principles into measurable conditions, dates, and revision points.", "A reviewable-compromise dialogue / حوار الحل القابل للمراجعة", "Negotiate what is preserved, conceded, measured, and revisited.", "A compromise is honest when its costs and review conditions are visible.", "Hear how public positions shift under challenge.", ["orientation","encounter","meaningful-use","retrieval","evidence","next-bridge"], ["worked-example","arabic-help","extended-rationale"]),
39: experience("listening", "normal", "The interview requires tracking stance shifts and repair rather than merely spotting contradiction.", "A contested-interview listening lab / مختبر الاستماع إلى مقابلة متنازع عليها", "Listen for the initial claim, pressure, wording shift, and whether the repair clarifies responsibility.", "Advanced listening follows discourse movement and motive without assuming motive is proven.", "Control information density in writing.", ["orientation","encounter","notice","retrieval","evidence","next-bridge"], ["transcript","extended-rationale","arabic-help"]),
40: experience("grammar", "light", "Information structure and punctuation guide a reader through dense reasoning.", "An information-density clinic / عيادة كثافة المعلومات", "Reorder one dense paragraph and test whether the main claim and qualification are easy to follow.", "Clear structure preserves nuance better than a wall of detail.", "Mediate two conflicting reports.", ["orientation","notice","supported-practice","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
41: experience("writing", "deep", "Mediation requires fair representation of disagreement and a clear boundary around inference.", "A contested-report mediation studio / استوديو توسيط التقرير", "Write for a public audience: common ground, disagreement, stronger inference, unknowns.", "Plain language must not become false certainty.", "Defend and revise a position orally.", ["orientation","notice","supported-practice","meaningful-use","retrieval","evidence","next-bridge"], ["external-ai-prompt","worked-example","arabic-help"]),
42: experience("speaking", "normal", "The speaking route tests whether a learner can revise scope in response to an objection without collapsing the argument.", "A position-and-revision rehearsal / تدريب الموقف والمراجعة", "State a position, answer an objection, and revise its scope or condition.", "Revision is disciplined responsiveness, not rhetorical retreat.", "Trace consequences across time.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
43: experience("reading", "deep", "The reading makes delayed and transferred consequences visible beyond the first headline result.", "A time-horizon reading lab / مختبر قراءة الآفاق الزمنية", "Trace immediate gain, delayed cost, and durable institutional effect.", "A complete judgement follows effects beyond the reporting window.", "Retrieve the module’s judgement toolkit.", ["orientation","encounter","notice","supported-practice","retrieval","evidence","next-bridge"], ["word-support","extended-rationale","arabic-help"]),
44: experience("review", "light", "The review retrieves the module’s operations before synthesis without introducing another dense source.", "A judgement-toolkit review / مراجعة أدوات الحكم", "Retrieve framing, evidence comparison, qualification, affected experience, and revision conditions.", "Transfer depends on seeing how language, evidence, and consequences connect.", "Publish the final defensible judgement.", ["orientation","notice","retrieval","evidence","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "encounter", reason: "Retrieval uses prior artefacts rather than a new source." }]),
45: experience("assessment", "deep", "The transfer task asks for a public judgement whose evidence, limits, and review conditions remain examinable.", "A defensible-public-judgement assessment / تقييم الحكم العام القابل للدفاع", "Synthesize the sources, recommend a decision, acknowledge the strongest objection, and define review.", "C2 performance is precise, audience-aware, revisable, and accountable.", "Carry the judgement studio into the next C2 module.", ["orientation","encounter","notice","supported-practice","meaningful-use","retrieval","evidence","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
};
