import type { InteractionTurn, LessonActivity, LessonRetrievalCheck, ReadingCheck, SpeakingLine } from "./types";

type Spec = {
  kind: LessonActivity["kind"];
  title: string;
  titleArabic: string;
  objective: string;
  objectiveArabic: string;
  stage: LessonActivity["stage"];
  semantic: NonNullable<LessonActivity["semantic"]>;
  minutes: number;
  retrieval: LessonRetrievalCheck;
  sentencePatterns: string[];
  supports: LessonActivity["progressiveSupports"];
  readingText?: string;
  readingTextArabic?: string;
  readingChecks?: ReadingCheck[];
  writingPrompt?: string;
  writingPromptArabic?: string;
  suggestedVocabulary?: string[];
  speakingLines?: SpeakingLine[];
  interactionTurns?: InteractionTurn[];
};

const retrieval = (prompt: string, promptArabic: string, expectedEvidence: string, expectedEvidenceArabic: string): LessonRetrievalCheck => ({ prompt, promptArabic, expectedEvidence, expectedEvidenceArabic });

const specs: Record<number, Spec> = {
  1: { kind: "reading", title: "Audit the argument", titleArabic: "دقّق في الحجة", objective: "Distinguish a premise, a concession, and a conclusion before judging whether evidence warrants the claim.", objectiveArabic: "ميّز بين المقدمة والإقرار والنتيجة قبل الحكم على ما إذا كان الدليل يبرر الادعاء.", stage: "guided-practice", semantic: "activity", minutes: 28, readingText: "A city report claims that a new transport hub will reduce inequality because it will serve more passengers. A quieter paragraph notes that the routes serving low-income districts will be reduced during construction and that the estimate assumes stable fares. The proposal may still be defensible, but its conclusion is stronger than its evidence unless those conditions are addressed.", readingTextArabic: "يدّعي تقرير بلدي أن مركز النقل الجديد سيقلل عدم المساواة لأنه سيخدم عدداً أكبر من الركاب. لكن فقرة أكثر هدوءاً تذكر أن الخطوط التي تخدم الأحياء منخفضة الدخل ستنخفض أثناء البناء وأن التقدير يفترض استقرار الأسعار. قد يظل المقترح قابلاً للدفاع، لكن نتيجته أقوى من دليله ما لم تُعالج هذه الشروط.", readingChecks: [{ id: "claim", type: "inference", prompt: "Why is the conclusion stronger than the evidence?", promptArabic: "لماذا تبدو النتيجة أقوى من الدليل؟", answer: "It treats passenger numbers as proof of reduced inequality while leaving access and fare conditions unresolved.", explanation: "A qualified argument names the conditions that connect evidence to conclusion." }], retrieval: retrieval("Retrieve the difference between a claim and the evidence that warrants it.", "استرجع الفرق بين الادعاء والدليل الذي يبرره.", "A claim is a conclusion; evidence warrants it only when the reasoning link and limits are visible.", "الادعاء نتيجة؛ ولا يبرره الدليل إلا عندما تكون صلة الاستدلال وحدوده واضحة."), sentencePatterns: ["The evidence supports … only insofar as …", "The conclusion would be warranted if …", "A serious concession is …"], supports: ["word-support", "arabic-help", "extended-rationale"] },
  2: { kind: "interaction", title: "Set a boundary for automation", titleArabic: "ضع حدوداً للأتمتة", objective: "Negotiate an automation decision by weighing autonomy, efficiency, and unintended fallout.", objectiveArabic: "تفاوض حول قرار أتمتة بموازنة الاستقلالية والكفاءة والتداعيات غير المقصودة.", stage: "real-context", semantic: "activity", minutes: 26, interactionTurns: [{ id: "director", speaker: "Service director", text: "The automated route is faster, so it should become the default for everyone.", textArabic: "المسار المؤتمت أسرع، ولذلك ينبغي أن يصبح الخيار الافتراضي للجميع.", purpose: "Present efficiency as sufficient justification." }, { id: "reviewer", speaker: "Ethics reviewer", text: "Speed is relevant, but the default should remain defensible for people whose circumstances the system cannot recognise.", textArabic: "السرعة مهمة، لكن ينبغي أن يظل الخيار الافتراضي قابلاً للدفاع بالنسبة لمن لا يستطيع النظام فهم ظروفهم.", purpose: "Reintroduce autonomy and a condition of legitimacy." }], retrieval: retrieval("Retrieve one condition that makes convenience ethically defensible.", "استرجع شرطاً واحداً يجعل الراحة مبررة أخلاقياً.", "The choice must preserve meaningful alternatives, disclose consequences, and allow review for affected users.", "ينبغي أن يحافظ الخيار على بدائل حقيقية ويكشف النتائج ويتيح المراجعة للمتأثرين."), sentencePatterns: ["Efficiency should not come at the expense of …", "The default is defensible provided that …", "A meaningful alternative would …"], supports: ["worked-example", "arabic-help", "tip"] },
  3: { kind: "reading", title: "Mediate an ecological threshold", titleArabic: "بسّط عتبة بيئية", objective: "Translate dense ecological explanation into accessible public language without erasing uncertainty or causal limits.", objectiveArabic: "حوّل شرحاً بيئياً كثيفاً إلى لغة عامة واضحة دون محو عدم اليقين أو حدود السببية.", stage: "real-context", semantic: "example", minutes: 30, readingText: "Wetland resilience is not an unlimited capacity. When drainage, heat, and nutrient loss interact, a system can cross a threshold after which restoration is slower and more expensive. The evidence indicates heightened risk, not an exact date of collapse; stewardship therefore means reducing pressure before certainty arrives.", readingTextArabic: "ليست مرونة الأراضي الرطبة قدرة غير محدودة. فعندما يتفاعل التصريف والحرارة وفقدان المغذيات قد يعبر النظام عتبة تصبح بعدها الاستعادة أبطأ وأكثر كلفة. يشير الدليل إلى ارتفاع الخطر، لا إلى تاريخ دقيق للانهيار؛ ولذلك تعني الرعاية تقليل الضغط قبل وصول اليقين.", readingChecks: [{ id: "threshold", type: "main-idea", prompt: "What does the explanation preserve while becoming more accessible?", promptArabic: "ما الذي يحافظ عليه الشرح رغم جعله أسهل؟", answer: "It preserves interaction among causes, the possibility of a threshold, and uncertainty about timing.", explanation: "Mediation changes audience and density, not the truth conditions of the source." }], retrieval: retrieval("Retrieve the difference between a symptom and a system-level explanation.", "استرجع الفرق بين العرض والشرح على مستوى النظام.", "A symptom is a visible outcome; a system explanation connects interacting causes and delayed consequences.", "العرض نتيجة ظاهرة؛ أما الشرح النظامي فيربط الأسباب المتفاعلة والنتائج المتأخرة."), sentencePatterns: ["The evidence indicates … rather than …", "In plain terms, this means …", "The risk becomes more serious when …"], supports: ["word-support", "extended-rationale", "arabic-help"] },
  4: { kind: "writing", title: "Curate competing memories", titleArabic: "نسّق ذكريات متنافسة", objective: "Write an interpretive note that acknowledges conflicting memories without treating one account as neutral fact.", objectiveArabic: "اكتب ملاحظة تفسيرية تعترف بالذكريات المتعارضة دون تقديم رواية واحدة كحقيقة محايدة.", stage: "independent-practice", semantic: "activity", minutes: 34, writingPrompt: "Write 350–450 words for a bilingual museum label about one event remembered differently by a family archive and a public institution. Identify the vantage point, name one omission, and explain why the difference matters without declaring a final winner.", writingPromptArabic: "اكتب 350–450 كلمة لبطاقة متحف ثنائية اللغة حول حدث تتذكره أرشيفات عائلية ومؤسسة عامة بشكل مختلف. حدّد زاوية النظر واذكر إغفالاً واحداً واشرح أهمية الاختلاف دون إعلان فائز نهائي.", suggestedVocabulary: ["recollection", "collective", "reconcile", "vantage point"], retrieval: retrieval("Retrieve how a responsible interpretation handles an inherited narrative.", "استرجع كيفية تعامل التفسير المسؤول مع رواية موروثة.", "It identifies whose perspective shaped the account, acknowledges what it cannot prove, and makes another perspective visible.", "يحدد المنظور الذي شكّل الرواية ويعترف بما لا تثبته ويجعل منظوراً آخر مرئياً."), sentencePatterns: ["From the vantage point of …", "What tends to be overlooked is …", "The accounts can be reconciled only if …"], supports: ["external-ai-prompt", "worked-example", "extended-rationale"] },
  5: { kind: "listening", title: "Hear the value judgement in the figures", titleArabic: "استمع إلى الحكم القيمي خلف الأرقام", objective: "Separate economic indicators, assumptions, and value judgements in a spoken policy briefing.", objectiveArabic: "افصل بين المؤشرات الاقتصادية والافتراضات والأحكام القيمية في إحاطة سياسية مسموعة.", stage: "guided-practice", semantic: "example", minutes: 27, speakingLines: [{ id: "briefing", speaker: "Briefing", text: "The latest figures show higher productivity, but they do not show who absorbed the insecurity required to achieve it. A fair assessment must therefore ask both whether the output rose and whether the livelihood became more precarious.", textArabic: "تظهر أحدث الأرقام ارتفاع الإنتاجية، لكنها لا تظهر من تحمّل انعدام الأمان اللازم لتحقيقه. لذلك ينبغي للتقييم العادل أن يسأل هل ارتفع الإنتاج وهل أصبح مصدر الرزق أكثر هشاشة.", audioText: "The latest figures show higher productivity, but they do not show who absorbed the insecurity required to achieve it." }], retrieval: retrieval("Retrieve the difference between a measured indicator and a value judgement.", "استرجع الفرق بين المؤشر المقاس والحكم القيمي.", "An indicator describes a measurable change; a value judgement decides why that change matters or whether it is fair.", "يصف المؤشر تغيراً قابلاً للقياس؛ أما الحكم القيمي فيقرر لماذا يهم التغير أو هل هو عادل."), sentencePatterns: ["The figures indicate …, but they do not establish …", "From a worker's perspective …", "A fair assessment would ask …"], supports: ["transcript", "word-support", "arabic-help"] },
  6: { kind: "standard", title: "Make institutional agency visible", titleArabic: "اجعل فاعل المؤسسة مرئياً", objective: "Choose active and passive structures deliberately to show responsibility, process, or legitimate uncertainty.", objectiveArabic: "اختر المعلوم والمجهول عمداً لإظهار المسؤولية أو الإجراء أو عدم اليقين المشروع.", stage: "explanation", semantic: "grammar", minutes: 23, retrieval: retrieval("Retrieve one reason a passive can be ethical and one reason it can be evasive.", "استرجع سبباً يجعل المبني للمجهول أخلاقياً وسبباً يجعله مراوغاً.", "It can foreground a process when the agent is shared or irrelevant; it can evade accountability when the agent matters.", "قد يبرز الإجراء عندما يكون الفاعل مشتركاً أو غير مهم؛ وقد يتهرب من المساءلة عندما يكون الفاعل مهماً."), sentencePatterns: ["Residents were consulted before …", "The agency decided to …", "Responsibility remains with …"], supports: ["worked-example", "arabic-help", "tip"] },
  7: { kind: "reading", title: "Defend an interpretation without closing it", titleArabic: "دافع عن تفسير دون إغلاقه", objective: "Build an evidence-based interpretation of an ambiguous artwork while keeping alternative readings alive.", objectiveArabic: "ابنِ تفسيراً قائماً على الدليل لعمل فني ملتبس مع إبقاء القراءات البديلة ممكنة.", stage: "guided-practice", semantic: "example", minutes: 29, readingText: "The repeated doorway may suggest escape, exclusion, or simply the artist's interest in interrupted movement. The strongest reading is not the most confident one; it is the one that connects the motif to the composition while admitting what the image cannot settle.", readingTextArabic: "قد يوحي الباب المتكرر بالهروب أو الإقصاء أو بمجرد اهتمام الفنان بالحركة المتقطعة. ليست القراءة الأقوى هي الأكثر ثقة، بل التي تربط العنصر المتكرر بالتكوين وتعترف بما لا تحسمه الصورة.", readingChecks: [{ id: "ambiguity", type: "inference", prompt: "What makes the interpretation responsible?", promptArabic: "ما الذي يجعل التفسير مسؤولاً؟", answer: "It links a plausible reading to observable evidence while acknowledging unresolved alternatives.", explanation: "Interpretation is disciplined possibility, not unrestricted opinion." }], retrieval: retrieval("Retrieve how to state a C2 interpretation without overstating certainty.", "استرجع كيفية صياغة تفسير C2 دون مبالغة في اليقين.", "Use evidence-based language such as may suggest, is consistent with, and cannot by itself establish.", "استخدم لغة قائمة على الدليل مثل قد يوحي ويتسق مع ولا يثبت وحده."), sentencePatterns: ["The motif may suggest …", "This reading is consistent with …", "The image cannot by itself establish …"], supports: ["word-support", "extended-rationale", "arabic-help"] },
  8: { kind: "writing", title: "Explain uncertainty honestly", titleArabic: "اشرح عدم اليقين بصدق", objective: "Write a public evidence note that distinguishes findings, interpretation, and what remains unknown.", objectiveArabic: "اكتب مذكرة دليل عامة تميّز بين النتائج والتفسير وما يزال مجهولاً.", stage: "independent-practice", semantic: "activity", minutes: 33, writingPrompt: "Write 300–400 words for a general audience about a study that found a correlation. Explain what the finding suggests, why it does not prove causation, and what a useful next study would test.", writingPromptArabic: "اكتب 300–400 كلمة لجمهور عام عن دراسة وجدت ارتباطاً. اشرح ما يوحي به الاكتشاف ولماذا لا يثبت السببية وما الذي ستختبره دراسة لاحقة مفيدة.", suggestedVocabulary: ["replicate", "correlation", "causation", "robust", "provisional"], retrieval: retrieval("Retrieve the three layers of a careful evidence explanation.", "استرجع الطبقات الثلاث لشرح دليل دقيق.", "Separate observation, interpretation, and the limits or next question.", "افصل بين الملاحظة والتفسير والحدود أو السؤال التالي."), sentencePatterns: ["The findings suggest rather than prove …", "This interpretation is provisional because …", "Further research would need to …"], supports: ["external-ai-prompt", "worked-example", "extended-rationale"] },
  9: { kind: "interaction", title: "Mediate belonging", titleArabic: "توسّط في حوار الانتماء", objective: "Represent competing experiences of integration accurately and propose a reciprocal next step.", objectiveArabic: "مثّل تجارب الاندماج المتنافسة بدقة واقترح خطوة تالية متبادلة.", stage: "real-context", semantic: "activity", minutes: 28, interactionTurns: [{ id: "resident", speaker: "Long-term resident", text: "People should adapt to the community they join.", textArabic: "ينبغي للناس أن يتكيفوا مع المجتمع الذي ينضمون إليه.", purpose: "Frame integration as one-way adaptation." }, { id: "mediator", speaker: "Mediator", text: "Adaptation may be necessary on both sides; the question is which institutions make reciprocity possible rather than merely asking newcomers to absorb the cost.", textArabic: "قد يكون التكيف ضرورياً من الطرفين؛ والسؤال هو أي المؤسسات تجعل التبادلية ممكنة بدلاً من مطالبة الوافدين وحدهم بتحمل التكلفة.", purpose: "Reframe integration as reciprocal and institutional." }], retrieval: retrieval("Retrieve one language choice that avoids reducing people to a label.", "استرجع اختياراً لغوياً واحداً يتجنب اختزال الناس في تسمية.", "Describe people as agents with varied experiences, and avoid speaking for a group as if it were uniform.", "صف الناس بوصفهم فاعلين ذوي تجارب متنوعة وتجنب الحديث باسم جماعة كأنها متجانسة."), sentencePatterns: ["Rather than speaking for …, we should …", "The terms on which people meet include …", "A two-way process would require …"], supports: ["worked-example", "arabic-help", "tip"] },
  10: { kind: "listening", title: "Lead through uncertainty", titleArabic: "قد في وسط عدم اليقين", objective: "Identify reassurance, omission, and contingency in a calm crisis update.", objectiveArabic: "حدّد الطمأنة والإغفال وخطة الطوارئ في تحديث هادئ أثناء أزمة.", stage: "guided-practice", semantic: "assessment", minutes: 27, speakingLines: [{ id: "update", speaker: "Crisis update", text: "We have confirmed the disruption, not its full cause. Teams are protecting the most vulnerable sites, and we will publish the next update at six. If conditions worsen, the contingency route will be activated.", textArabic: "أكدنا الاضطراب، لا سببه الكامل. تحمي الفرق المواقع الأكثر عرضة للخطر، وسننشر التحديث التالي عند السادسة. إذا ساءت الظروف فسيُفعّل مسار الطوارئ.", audioText: "We have confirmed the disruption, not its full cause. Teams are protecting the most vulnerable sites." }], retrieval: retrieval("Retrieve the four moves of a credible crisis message.", "استرجع الحركات الأربع للرسالة الموثوقة أثناء الأزمة.", "State what is known, what is unknown, what is being done, and what will happen next.", "اذكر ما هو معروف وما هو مجهول وما يجري فعله وما سيحدث تالياً."), sentencePatterns: ["We know …, but we do not yet know …", "As a precautionary measure …", "Should circumstances change …"], supports: ["transcript", "arabic-help", "tip"] },
  11: { kind: "reading", title: "Expose the frame", titleArabic: "اكشف الإطار", objective: "Analyse how labels and omissions shape public narratives, then rewrite one passage from another vantage point.", objectiveArabic: "حلّل كيف تشكل التسميات والإغفالات السرديات العامة ثم أعد كتابة مقطع من زاوية أخرى.", stage: "real-context", semantic: "example", minutes: 31, readingText: "A headline calls a neighbourhood 'uncooperative' after residents reject a timetable set without consultation. The label turns a disagreement about process into a character judgement. A more accountable frame would describe the decision, the missing consultation, and the reasons residents gave.", readingTextArabic: "تصف عناوين حياً بأنه غير متعاون بعد أن رفض السكان جدولاً زمنياً وُضع دون تشاور. تحول التسمية خلافاً حول الإجراء إلى حكم على الشخصية. أما التأطير الأكثر مساءلة فيصف القرار والتشاور المفقود والأسباب التي قدمها السكان.", readingChecks: [{ id: "frame", type: "inference", prompt: "What does the label make harder to see?", promptArabic: "ما الذي تجعل التسمية رؤيته أكثر صعوبة؟", answer: "It hides the procedural dispute and makes residents appear personally defective.", explanation: "Framing is a choice about what becomes salient and what disappears." }], retrieval: retrieval("Retrieve how a label can legitimise a particular response.", "استرجع كيف يمكن لتسمية أن تمنح شرعية لاستجابة معينة.", "It presents one interpretation as natural, making some interventions seem necessary and other voices seem unreasonable.", "تقدم تفسيراً واحداً بوصفه طبيعياً فتجعل بعض التدخلات ضرورية وأصواتاً أخرى غير معقولة."), sentencePatterns: ["The label frames … as …", "The effect is to obscure …", "From another angle, the passage could say …"], supports: ["word-support", "extended-rationale", "arabic-help"] },
  12: { kind: "speaking", title: "Reframe the future of work", titleArabic: "أعد تأطير مستقبل العمل", objective: "Give a concise spoken recommendation that separates a forecast from the evidence and names transferable expertise.", objectiveArabic: "قدّم توصية شفوية موجزة تفصل التوقع عن الدليل وتحدد الخبرة القابلة للنقل.", stage: "independent-practice", semantic: "activity", minutes: 25, speakingLines: [{ id: "model", speaker: "Model", text: "The role was expected to disappear, but it has since evolved. A durable learning plan should therefore combine technical upskilling with expertise that transfers across changing contexts.", textArabic: "كان متوقعاً أن يختفي الدور، لكنه تطور منذ ذلك الحين. لذلك ينبغي لخطة التعلم المستدامة أن تجمع بين تطوير المهارات التقنية والخبرة القابلة للنقل بين السياقات المتغيرة.", pronunciationHint: "Stress expected, evolved, durable, and transfers to signal the contrast." }], retrieval: retrieval("Retrieve the difference between a forecast and a current result.", "استرجع الفرق بين التوقع والنتيجة الحالية.", "A forecast belongs to an earlier expectation; a current result reports what has happened since and may revise it.", "ينتمي التوقع إلى انتظار سابق؛ أما النتيجة الحالية فتصف ما حدث منذ ذلك وقد تراجعه."), sentencePatterns: ["The role was expected to …, but it has since …", "A transferable foundation would …", "The forecast rests on …"], supports: ["worked-example", "arabic-help", "tip"] },
  13: { kind: "reading", title: "Balance competing rights", titleArabic: "وازن بين الحقوق المتنافسة", objective: "Compare the strongest arguments in a rights conflict and recommend a proportionate remedy.", objectiveArabic: "قارن أقوى الحجج في تعارض حقوق واقترح وسيلة انتصاف متناسبة.", stage: "guided-practice", semantic: "assessment", minutes: 32, readingText: "A court must decide whether a security measure that limits privacy is justified by a serious risk. One side invokes public safety; the other argues that the measure is too broad and lacks review. A proportionate remedy would define the jurisdiction, narrow the intrusion, and require evidence-based renewal.", readingTextArabic: "يتعين على محكمة أن تقرر هل يبرر خطر خطير إجراءً أمنياً يحد من الخصوصية. يستند أحد الطرفين إلى السلامة العامة؛ ويجادل الآخر بأن الإجراء واسع جداً ويفتقر إلى المراجعة. يحدد العلاج المتناسب الاختصاص ويضيق التدخل ويشترط التجديد القائم على الدليل.", readingChecks: [{ id: "remedy", type: "main-idea", prompt: "What makes the proposed remedy proportionate?", promptArabic: "ما الذي يجعل وسيلة الانتصاف المقترحة متناسبة؟", answer: "It limits the intrusion, defines authority, and requires review rather than treating the restriction as permanent.", explanation: "Proportionality connects the scale of a remedy to the harm and the evidence." }], retrieval: retrieval("Retrieve the three questions for a proportionate public remedy.", "استرجع الأسئلة الثلاثة لوسيلة انتصاف عامة متناسبة.", "What authority exists, how much intrusion is necessary, and when will the decision be reviewed?", "ما السلطة الموجودة؟ ما مقدار التدخل الضروري؟ ومتى ستتم مراجعة القرار؟"), sentencePatterns: ["The right is not absolute, but …", "A proportionate response would …", "The remedy should be subject to …"], supports: ["word-support", "worked-example", "arabic-help"] },
  14: { kind: "writing", title: "Design for the people missed", titleArabic: "صمّم لمن لا يُرى عادةً", objective: "Write a public design brief that anticipates access, displacement, and liveability trade-offs.", objectiveArabic: "اكتب موجز تصميم عام يتوقع مفاضلات الوصول والإزاحة وقابلية العيش.", stage: "independent-practice", semantic: "activity", minutes: 35, writingPrompt: "Write 400–500 words for an urban design team choosing between a high-density redevelopment and a slower retrofit. Define the users usually missed, compare access and displacement risks, and propose a review measure that residents can understand.", writingPromptArabic: "اكتب 400–500 كلمة لفريق تصميم حضري يختار بين إعادة تطوير عالية الكثافة وتعديل أبطأ للمباني القائمة. حدّد المستخدمين الذين يُغفلون عادةً وقارن مخاطر الوصول والإزاحة واقترح مقياس مراجعة يستطيع السكان فهمه.", suggestedVocabulary: ["infrastructure", "accessibility", "density", "displace", "liveability", "retrofitting"], retrieval: retrieval("Retrieve how design becomes an ethical decision rather than a technical one.", "استرجع كيف يصبح التصميم قراراً أخلاقياً لا تقنياً فقط.", "Design allocates access, comfort, risk, and displacement across people with different power and needs.", "يوزع التصميم الوصول والراحة والخطر والإزاحة بين أشخاص مختلفين في القوة والاحتياجات."), sentencePatterns: ["The design would improve … but may displace …", "Accessibility requires …", "The review measure should reveal …"], supports: ["external-ai-prompt", "worked-example", "extended-rationale"] },
  15: { kind: "review", title: "Synthesize precision into judgement", titleArabic: "ركّب الدقة في حكم", objective: "Transfer C2 control of evidence, stance, framing, uncertainty, and audience into one defensible recommendation.", objectiveArabic: "انقل التحكم في الدليل والموقف والتأطير وعدم اليقين والجمهور إلى توصية واحدة قابلة للدفاع.", stage: "assessment", semantic: "assessment", minutes: 38, readingText: "A public institution must choose whether to deploy a predictive system, publish a limited pilot, or delay the decision. The evidence is promising but provisional; the system may improve access while reproducing hidden disparities. A responsible recommendation must make its assumptions, safeguards, affected groups, and review trigger visible.", readingTextArabic: "يتعين على مؤسسة عامة أن تختار بين نشر نظام تنبؤي أو إعلان تجربة محدودة أو تأجيل القرار. الدليل واعد لكنه مؤقت؛ وقد يحسن النظام الوصول مع إعادة إنتاج تفاوتات خفية. ينبغي للتوصية المسؤولة أن تظهر افتراضاتها وضماناتها والمجموعات المتأثرة وشرط المراجعة.", readingChecks: [{ id: "transfer", type: "inference", prompt: "What must a defensible recommendation make visible?", promptArabic: "ما الذي ينبغي للتوصية القابلة للدفاع أن تجعله مرئياً؟", answer: "Its evidence limits, assumptions, affected groups, safeguards, and condition for review.", explanation: "C2 judgement is proportionate, audience-aware, and open to revision." }], writingPrompt: "Write 450–600 words recommending deployment, a limited pilot, or delay. Use at least one concession, one qualified claim, one explicit responsibility, and one review condition. Then add a 60-word public summary for non-specialists.", writingPromptArabic: "اكتب 450–600 كلمة توصي بالنشر أو بتجربة محدودة أو بالتأجيل. استخدم إقراراً واحداً على الأقل وادعاءً مقيداً ومسؤولية واضحة وشرط مراجعة واحداً. ثم أضف ملخصاً عاماً من 60 كلمة لغير المتخصصين.", suggestedVocabulary: ["provisional", "scrutiny", "transparency", "proportionality", "uncertainty"], retrieval: retrieval("Retrieve the C2 judgement checklist before you begin.", "استرجع قائمة حكم C2 قبل أن تبدأ.", "State the claim, qualify it, show evidence and limits, name who is affected, and specify a safeguard or review trigger.", "اذكر الادعاء وقيده وأظهر الدليل والحدود وسمِّ المتأثرين وحدد ضمانة أو شرط مراجعة."), sentencePatterns: ["On balance, I recommend … subject to …", "The evidence warrants … but not …", "Responsibility would remain with …"], supports: ["external-ai-prompt", "worked-example", "extended-rationale"] },
};

function toActivity(lessonNumber: number, spec: Spec): LessonActivity {
  return {
    id: `c2-authored-${lessonNumber}`,
    kind: spec.kind,
    title: spec.title,
    titleArabic: spec.titleArabic,
    objective: spec.objective,
    objectiveArabic: spec.objectiveArabic,
    stage: spec.stage,
    estimatedMinutes: spec.minutes,
    semantic: spec.semantic,
    retrievalCheck: spec.retrieval,
    sentencePatterns: spec.sentencePatterns,
    progressiveSupports: spec.supports,
    readingText: spec.readingText,
    readingTextArabic: spec.readingTextArabic,
    readingChecks: spec.readingChecks,
    writingPrompt: spec.writingPrompt,
    writingPromptArabic: spec.writingPromptArabic,
    suggestedVocabulary: spec.suggestedVocabulary,
    speakingLines: spec.speakingLines,
    interactionTurns: spec.interactionTurns,
  };
}

export const C2_MODULE_1_AUTHORED_ACTIVITIES: Record<number, LessonActivity[]> = Object.fromEntries(
  Object.entries(specs).map(([lessonNumber, spec]) => [Number(lessonNumber), [toActivity(Number(lessonNumber), spec)]])
);
