import type { LessonExperience } from "./types";
const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], archetypeRationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages?: LessonExperience["intentionallyOmittedStages"]): LessonExperience => ({ archetype, density, archetypeRationale, selectedStages, intentionallyOmittedStages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });
const C2_MODULE_8_EXPERIENCES: Record<number, LessonExperience> = {
106: experience("reading", "normal", "Reliability requires close attention to the gap between voice and evidence.", "A narrative-reliability reading.", "Read once for the narrator's claim, then again for contradiction and uncertainty.", "Confidence is part of a voice, not proof of accuracy.", "Use reporting language to control viewpoint.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","extended-rationale","arabic-help"]),
107: experience("grammar", "light", "The lesson gives the learner precise language for marking stance without overloading the literary arc.", "A viewpoint and reporting-verb studio.", "Recast observations as reports, inferences, and accusations, then test how certainty changes.", "Grammar controls ethical precision.", "Hear reliability in an audio narrative.", ["orientation","encounter","supported-practice","retrieval","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "supported-practice", reason: "Independent interpretation follows in Lesson 109." }]),
108: experience("listening", "normal", "Audio makes contradiction and self-correction perceptible before the transcript supplies wording.", "An audio-first unreliable-narrator task.", "Listen for what is asserted, softened, omitted, and revised; reveal the transcript after the first attempt.", "The listener must separate silence from agreement.", "Write an evidence-based interpretation.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["transcript","arabic-help","worked-example"], [{ stage: "supported-practice", reason: "Transcript support follows the initial listening attempt." }]),
109: experience("writing", "deep", "Interpretation is a compact but demanding C2 writing task that rewards evidence control rather than invented psychology.", "An interpretive-note workshop.", "Write from three textual details, mark one contradiction, and use the external-AI prompt only after your own draft.", "A plausible reading must remain answerable to the text.", "Consolidate the narrative distinctions.", ["orientation","encounter","meaningful-use","evidence","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
110: experience("review", "light", "A checkpoint prevents the literary arc from becoming a vocabulary list and makes the reasoning portable.", "A narrative-reliability checkpoint.", "Answer the four questions: claim, support, contradiction, unresolved possibility.", "Good interpretation is disciplined openness.", "Move from narrative uncertainty to interpersonal repair.", ["orientation","retrieval","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "encounter", reason: "The checkpoint retrieves established distinctions." }]),
111: experience("reading", "normal", "Repair requires comparison across institutional language, lived harm, and proposed action.", "A repair-and-redress comparison reading.", "Compare what the apology names, what the survivor reports, and what the proposal changes.", "Acknowledgement, compensation, and participation are different forms of response.", "Practise keeping repair open in dialogue.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","extended-rationale","arabic-help"]),
112: experience("interaction", "normal", "The objective is relational: respond without accepting premature closure or escalating the exchange.", "A mediated repair conversation.", "Acknowledge the apology, ask for concrete repair, and specify who can test whether it works.", "Tone and structure can preserve dignity while keeping accountability active.", "Hear conditional agreement under diplomatic pressure.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
113: experience("listening", "normal", "Diplomatic meaning often sits in conditions and refusals rather than explicit agreement.", "An audio-first negotiation hearing.", "Listen for non-negotiables, concessions, conditions, and what remains unresolved; reveal the transcript after the attempt.", "Compromise can prevent harm without erasing disagreement.", "Draft a repair agreement.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["transcript","arabic-help","extended-rationale"], [{ stage: "supported-practice", reason: "Written language support follows listening." }]),
114: experience("writing", "deep", "A repair agreement forces the learner to turn ethical language into observable action and review conditions.", "A repair-agreement drafting studio.", "Write the agreement, then use external feedback to test whether responsibility, participation, and revision are explicit.", "Repair must be actionable and monitorable.", "Consolidate negotiation without erasure.", ["orientation","encounter","meaningful-use","evidence","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
115: experience("review", "light", "The checkpoint consolidates diplomacy as structured movement rather than forced consensus.", "A repair-and-negotiation checkpoint.", "Retrieve harm, condition, disagreement, participation, and observability.", "A solution can move forward while leaving history contested.", "Translate expertise for a public audience.", ["orientation","retrieval","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "encounter", reason: "The checkpoint retrieves rather than introduces content." }]),
116: experience("reading", "normal", "Mediation begins by reading where a technical report is conditional and where a public explanation might overstate it.", "A technical-to-public mediation reading.", "Mark the finding, its modelled conditions, its limits, and the practical implication.", "Useful simplification must preserve uncertainty.", "Explain the same evidence in two registers.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","extended-rationale","arabic-help"]),
117: experience("speaking", "normal", "Register control is best tested through two spoken versions of the same evidence.", "A two-audience explanation rehearsal.", "Record a specialist version and a community version; compare whether the causal claim and limits stayed stable.", "Accessibility changes expression, not accountability.", "Hear the ethics of simplification.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
118: experience("listening", "normal", "The audio task makes ethical simplification audible as a balance between clarity and caution.", "An audio-first public-explainer analysis.", "Listen for practical clarity, conditions, overpromising, and the public's ability to check the claim; reveal the transcript after the attempt.", "A clear promise can still be misleading.", "Build a mediation dossier.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["transcript","arabic-help","worked-example"], [{ stage: "supported-practice", reason: "Transcript support follows active listening." }]),
119: experience("writing", "deep", "The dossier integrates technical evidence, lived experience, and institutional constraint for a real audience.", "A public-mediation dossier workshop.", "Write the plain-language summary, limitations note, and resident action guide, then review the evidence boundary.", "Making knowledge usable does not mean making it certain.", "Complete the ethical-persuasion assessment.", ["orientation","encounter","meaningful-use","evidence","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
120: experience("assessment", "deep", "The final task tests whether the learner can persuade while keeping evidence, harm, uncertainty, and audience agency visible.", "An ethical-persuasion transfer assessment.", "Use the source pack to produce a transparent campaign or briefing with a safeguard against manipulation.", "Responsible persuasion leaves the audience able to judge.", "Review external feedback before the next C2 arc.", ["orientation","encounter","meaningful-use","evidence","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"])
};
export { C2_MODULE_8_EXPERIENCES };
