import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"],
  density: LessonExperience["density"],
  rationale: string,
  whatItIs: string,
  whatToDo: string,
  whatMatters: string,
  whatNext: string,
  selectedStages: LessonExperience["selectedStages"],
  progressiveSupports: LessonExperience["progressiveSupports"],
  omitted: LessonExperience["intentionallyOmittedStages"] = [],
): LessonExperience => ({
  archetype,
  density,
  archetypeRationale: rationale,
  selectedStages,
  intentionallyOmittedStages: omitted,
  firstView: { whatItIs, whatToDo, whatMatters, whatNext },
  progressiveSupports,
});

export const C2_MODULE_1_EXPERIENCES: Record<number, LessonExperience> = {
  1: experience("reading", "deep", "Argument auditing is the opening C2 operation: evidence must be tested before language is admired.", "A source-audit studio / ورشة تدقيق مصدر", "Read once for the position, then mark the premise, concession, and unsupported leap.", "A strong claim is proportionate to what the evidence can actually warrant.", "Move from diagnosis to your own qualified recommendation.", ["orientation", "encounter", "notice", "supported-practice", "retrieval", "evidence", "next-bridge"], ["word-support", "arabic-help", "extended-rationale"]),
  2: experience("interaction", "normal", "Automation becomes meaningful when the learner must negotiate a boundary rather than recite an ethical principle.", "A public-service consultation / استشارة حول خدمة عامة", "Take the director's position, then respond as a reviewer who must protect meaningful choice.", "Efficiency is not a complete justification when agency and unequal impact are at stake.", "Carry the boundary into ecological and institutional decisions.", ["orientation", "encounter", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "notice", reason: "The lesson prioritises live negotiation over extended form analysis." }]),
  3: experience("reading", "deep", "C2 mediation requires preserving causal relationships and uncertainty while lowering unnecessary technical density.", "A science-to-public mediation lab / مختبر نقل العلم إلى الجمهور", "Map interacting causes, threshold language, and the point where evidence stops.", "Accessible language must not turn risk into false certainty.", "Use the same discipline when curating human memory.", ["orientation", "encounter", "notice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  4: experience("writing", "deep", "Conflicting memories demand a composed interpretive product, not a fact-list or forced reconciliation.", "A bilingual exhibit-writing studio / استوديو كتابة معرض ثنائي اللغة", "Draft an interpretive note that names vantage point and omission before you seek elegance.", "Fairness can mean making competing accounts visible without pretending they are identical.", "Next, listen for how numerical language can also hide values.", ["orientation", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"], [{ stage: "encounter", reason: "The lesson begins from the learner's comparison of inherited accounts." }]),
  5: experience("listening", "normal", "The briefing is audio-first because the C2 challenge is hearing the value judgement beneath apparently neutral figures.", "An audio policy briefing / إحاطة سياسية مسموعة", "Listen for the indicator, the hidden assumption, and the human cost before revealing the transcript.", "Numbers describe change; they do not decide whether the change is fair.", "Make that distinction explicit in the next grammar lesson.", ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], ["transcript", "word-support", "arabic-help"], [{ stage: "supported-practice", reason: "The first pass deliberately tests unaided listening and inference." }]),
  6: experience("grammar", "light", "Form is studied as accountable rhetorical choice: passive voice can focus a process or conceal an agent.", "A responsibility-and-voice clinic / عيادة المسؤولية والصوت", "Compare active and passive versions and decide what each makes visible.", "C2 grammar changes the reader's understanding of responsibility, not only sentence shape.", "Return to close interpretation where viewpoint is less stable.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The examples carry the context; no separate source is needed." }, { stage: "meaningful-use", reason: "Application is kept short so the lesson remains a precision clinic." }]),
  7: experience("reading", "normal", "Ambiguity is treated as disciplined possibility, so the learner must defend an interpretation without closing alternatives.", "A close-reading studio / استوديو قراءة دقيقة", "Annotate the motif, then write a claim whose confidence matches the evidence.", "Interpretation is strongest when it is specific, revisable, and text-grounded.", "Transfer that calibration to public evidence.", ["orientation", "encounter", "notice", "supported-practice", "retrieval", "evidence", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  8: experience("writing", "deep", "The learner must make uncertainty useful to a non-specialist audience rather than hide it behind technical confidence.", "A public-evidence note / مذكرة دليل للجمهور", "Separate observation, interpretation, and the next test; then revise for reader effort.", "Honest uncertainty gives an audience a better basis for action.", "Use reciprocal dialogue when the issue becomes belonging and identity.", ["orientation", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  9: experience("interaction", "normal", "Belonging is learned through mediation: accurately representing both sides matters before proposing a shared step.", "A facilitated belonging dialogue / حوار انتماء مُيسّر", "Restate each position without caricature, then identify an institutional condition for reciprocity.", "Do not make adaptation a one-way demand or speak for a group as if it were uniform.", "Listen for how a credible institution leads in crisis.", ["orientation", "encounter", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "notice", reason: "The central work is pragmatic representation and repair." }]),
  10: experience("listening", "normal", "Crisis language is assessed through sequence, omission, reassurance, and contingency rather than vocabulary recall alone.", "A crisis-update listening lab / مختبر الاستماع لتحديث أزمة", "Listen once for known and unknown facts, then again for action and review triggers before opening the transcript.", "Credibility depends on saying what is known without manufacturing certainty.", "Analyse how public frames can distort what people hear.", ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], ["transcript", "arabic-help", "tip"], [{ stage: "supported-practice", reason: "The first response must come from listening, not reading." }]),
  11: experience("notice", "normal", "Framing becomes visible when the learner compares a label with the process and voices it hides.", "A framing-analysis lab / مختبر تحليل التأطير", "Circle what the label foregrounds, what it omits, and what response it makes seem natural.", "A single adjective can convert a procedural dispute into a judgement about character.", "Use framing responsibly in a spoken recommendation about work.", ["orientation", "encounter", "notice", "supported-practice", "retrieval", "evidence", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"], [{ stage: "meaningful-use", reason: "The rewrite is brief and subordinate to noticing the frame." }]),
  12: experience("speaking", "normal", "C2 speaking here is controlled public recommendation: concise, qualified, and explicit about transferable expertise.", "A future-of-work briefing / إحاطة حول مستقبل العمل", "Deliver a one-minute recommendation, stressing the contrast between forecast and current result.", "Precision includes pacing and emphasis as well as grammar and vocabulary.", "Test that judgement against a rights conflict.", ["orientation", "encounter", "notice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "supported-practice", reason: "The model line is enough support; the learner's delivery is the evidence." }]),
  13: experience("reading", "deep", "Rights conflicts require comparative reading and a remedy scaled to harm, authority, and review.", "A proportionate-remedy case studio / استوديو وسيلة الانتصاف المتناسبة", "State the strongest argument on each side before recommending a constrained, reviewable remedy.", "Fairness is not merely choosing a side; it is making the decision's scope accountable.", "Convert the principle into a design brief for people often missed.", ["orientation", "encounter", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["word-support", "worked-example", "arabic-help"]),
  14: experience("writing", "deep", "Urban design makes distributional choices tangible and demands a product that names users, burdens, and measures.", "A public design brief / موجز تصميم عام", "Compare two options, identify who bears the cost, and propose a measure residents can understand.", "Design is an ethical allocation of access, comfort, risk, and displacement.", "Bring all of the module's judgement operations into the final transfer assessment.", ["orientation", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  15: experience("assessment", "deep", "The final transfer asks the learner to use C2 language as a responsible decision instrument across evidence, audience, framing, and uncertainty.", "A C2 judgement transfer / مهمة نقل الحكم في C2", "Choose a position, qualify it, name affected groups, and produce both an expert recommendation and a public summary.", "The goal is not maximum density; it is a proportionate, revisable, audience-aware judgement.", "Carry this studio habit into C2 Module 2 and increasingly independent projects.", ["orientation", "encounter", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
};
