import type { LessonExperience } from "./types";

const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages?: LessonExperience["intentionallyOmittedStages"]): LessonExperience => ({ archetype, density, archetypeRationale: rationale, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, selectedStages, progressiveSupports, intentionallyOmittedStages });

const C2_MODULE_7_EXPERIENCES: Record<number, LessonExperience> = {
  91: experience("reading", "deep", "The learner must infer whose expertise counts from measurement and omission.", "A close reading of a transition plan.", "Mark formal measures, situated expertise, and the consequences of leaving knowledge uncounted.", "A measurable plan can still define competence too narrowly.", "Question whether access is genuinely fair.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  92: experience("interaction", "normal", "A short exchange makes equality and equity usable as decision language.", "A transition-access interrogation.", "Ask which barriers make an apparently open opportunity difficult to use.", "Formal openness is not proof of practical access.", "Hear how an institution qualifies its promise.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  93: experience("listening", "normal", "The task is to hear qualification and revision conditions in institutional speech.", "An audio announcement lab.", "Listen once for the promise, then reveal the transcript and mark limits, measures, and revision points.", "Credibility depends on what an institution is prepared to check.", "Write a case for learning access.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "arabic-help", "worked-example"], [{ stage: "supported-practice", reason: "Transcript support follows the first listening attempt." }]),
  94: experience("writing", "deep", "A recommendation must combine audience, evidence, trade-off, and review condition.", "An access-recommendation workshop.", "Draft a board note, then use the external-AI prompt to check qualification and source fidelity.", "A strong recommendation is useful because it is limited and revisable.", "Consolidate the transition arc.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  95: experience("review", "light", "The checkpoint should retrieve the control questions without adding a new dense source.", "A transition-and-access checkpoint.", "Retrieve expertise, barrier, access, evidence, and revision condition.", "The next arc applies the same precision to rights and remedies.", "Distinguish rights from remedies.", ["orientation", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "No new source is introduced." }]),
  96: experience("reading", "deep", "Rights reasoning requires separating recognition of an interference from justification and remedy.", "A rights-and-remedies reading studio.", "Trace jurisdiction, purpose, harm, proportionality, and remedy in the judgment extract.", "Recognising a right begins analysis; it does not finish it.", "Hear proportionality in a rights hearing.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  97: experience("listening", "normal", "Proportionality is a sequence of weighed decisions best heard as reasoning in motion.", "A rights-hearing listening lab.", "Listen for aim, effectiveness, alternatives, and remaining impact before revealing the transcript.", "Fairness depends on comparing means, not merely praising aims.", "Read precedent as reasoning.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "arabic-help", "extended-rationale"], [{ stage: "supported-practice", reason: "The transcript appears after the first pass." }]),
  98: experience("reading", "deep", "The learner must compare principle, facts, procedure, and remedy rather than memorise the word precedent.", "A precedent-comparison studio.", "Separate what the earlier decision establishes from what the later case changes.", "A precedent can guide without dictating when circumstances differ.", "Write a fair analysis of competing rights.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "worked-example", "arabic-help"]),
  99: experience("writing", "deep", "Competing rights require a full argumentative route with a serious opposing case.", "A proportionality briefing workshop.", "Present both interests, test the restriction, and recommend a limited remedy.", "Fair representation does not require false equivalence.", "Consolidate rights reasoning.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  100: experience("review", "light", "A compact checkpoint protects the module's legal-reasoning distinctions before the shift into design.", "A rights-and-proportionality checkpoint.", "Retrieve right, authority, interference, purpose, alternative, and remedy.", "The final arc asks how fairness becomes visible in designed space.", "Hear access in a design briefing.", ["orientation", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The checkpoint consolidates existing reasoning." }]),
  101: experience("listening", "normal", "Access is often absent from models, so the learner must hear who the evidence excludes.", "An audio-first urban design briefing.", "Listen for movement, time, safety, dignity, and missing participants; reveal the transcript after the attempt.", "A design model cannot infer every lived consequence.", "Compare equal treatment with liveable design.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "arabic-help", "worked-example"], [{ stage: "supported-practice", reason: "Written support follows listening." }]),
  102: experience("reading", "deep", "The contrast between a single metric and differentiated access needs close comparison.", "A liveability comparison reading.", "Compare the two design arguments and identify what the average metric cannot establish.", "A useful metric is not automatically a sufficient account of human consequence.", "Recommend an ethical design change.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  103: experience("writing", "deep", "Ethical design is a synthesis task requiring beneficiaries, displacement risk, safeguard, and trigger.", "An ethical-design recommendation workshop.", "Write to a design committee and use the external-AI prompt to test whether costs and omissions remain visible.", "Design quality includes who can live with the result.", "Read the city plan against its omissions.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  104: experience("reading", "normal", "The final reading prepares the learner to distinguish persuasive presentation from complete evidence.", "A city-plan omission audit.", "Compare stated benefits with rent, displacement, livelihood, heat, and access questions left unanswered.", "Omissions matter when they could change who benefits or bears the cost.", "Design a fair public future.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  105: experience("assessment", "deep", "The transfer task must mediate rights, access, expertise, and design without collapsing uncertainty.", "A fair-public-future transfer assessment.", "Use the source pack to identify competing interests, protect access, propose a safeguard, and state a revision trigger.", "A C2 recommendation is precise, humane, proportionate, and revisable.", "Continue to the next C2 arc after reviewing external feedback.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"])
};

export { C2_MODULE_7_EXPERIENCES };
