import type { LessonExperience } from "./types";

const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages?: LessonExperience["intentionallyOmittedStages"]): LessonExperience => ({ archetype, density, archetypeRationale: rationale, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, selectedStages, progressiveSupports, intentionallyOmittedStages });

const C2_MODULE_4_EXPERIENCES: Record<number, LessonExperience> = {
  46: experience("reading", "deep", "The learner must reconcile scale rather than complete a vocabulary drill.", "A source-reading studio on probability and lived exposure.", "Compare what the forecast measures with what the testimony makes visible.", "A low aggregate probability does not erase concentrated harm.", "Move to a mediated perspective-taking task.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  47: experience("interaction", "normal", "The objective is mediation between identities, so the dialogue is the centre of gravity.", "A bilingual mediation exchange about inclusion and assimilation.", "Reframe the disagreement while protecting both belonging and difference.", "Inclusive language must not silently demand sameness.", "Listen for how public language manages risk.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  48: experience("listening", "normal", "The learner needs to hear a risk briefing as an ordered reasoning chain.", "An audio-first risk communication lab.", "Listen once for the structure, then reveal the transcript to verify the four distinctions.", "Hazard, likelihood, exposure, and action are related but not interchangeable.", "Make institutional agency visible in the next grammar lesson.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "arabic-help"], [{ stage: "supported-practice", reason: "The first pass preserves authentic listening pressure before written support." }]),
  49: experience("grammar", "light", "This is a precision lesson: one grammatical lens clarifies who can act.", "A grammar clinic on agency and nominalisation.", "Turn an abstract institutional phrase into an accountable sentence.", "Clear grammar can reveal responsibility without overstating blame.", "Apply the distinction in a public clarification.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  50: experience("writing", "deep", "The primary objective is controlled public writing, not completion of every skill.", "A concise crisis-clarification workshop.", "Draft a bounded clarification, then use the external-AI prompt to check evidence, limits, and tone.", "Responsible reassurance names uncertainty and action.", "Rehearse the same logic aloud for a mixed audience.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  51: experience("speaking", "normal", "Layered briefing is best learned through an intentional spoken route.", "A mixed-audience briefing rehearsal.", "Lead with the decision and add the qualification different listeners need.", "Audience-aware sequencing is part of accuracy.", "Examine fairness in a policy trade-off.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  52: experience("reading", "deep", "The passage asks the learner to compare outcome and procedural fairness.", "A policy-reading studio on efficiency, equality, and voice.", "Annotate what the proposal distributes and who participated in its design.", "A fair outcome cannot be evaluated only by volume delivered.", "Deliberate across competing rights.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  53: experience("interaction", "deep", "The rights conflict requires turn-taking and explicit thresholds.", "A rights-sensitive deliberation.", "Name the right, the public aim, the threshold, and an auditable safeguard.", "A safeguard must protect consent rather than merely perform legitimacy.", "Qualify a principled recommendation.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "extended-rationale"]),
  54: experience("grammar", "light", "The lesson isolates concession and scalar language as tools for ethical precision.", "A grammar clinic on qualified recommendations.", "Write three recommendations with different levels of certainty.", "Moral seriousness still needs proportionality and revision conditions.", "Listen for evidence becoming advocacy.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  55: experience("listening", "normal", "The key skill is hearing the boundary between observed evidence and value judgement.", "An audio-first evidence-versus-advocacy lab.", "Identify the sentence where description becomes recommendation, then reveal the transcript.", "Data inform judgement but do not dictate the values assigned to action.", "Triangulate a contested account.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "extended-rationale"], [{ stage: "supported-practice", reason: "Transcript support appears after the first listening pass." }]),
  56: experience("reading", "deep", "Triangulation is an interpretive practice, so the lesson foregrounds source comparison.", "A three-source reading studio.", "Mark what the dataset, interview, and memo each measure, name, or omit.", "Apparent contradiction may be a difference in visibility or cost.", "Draft a source-mediated recommendation.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  57: experience("writing", "deep", "The learner must synthesize heterogeneous evidence into one accountable recommendation.", "A source-mediated recommendation workshop.", "Write for a review panel and specify a trigger for revision.", "A recommendation is credible when it preserves source limits and affected experience.", "Defend the recommendation under challenge.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  58: experience("speaking", "normal", "The hostile follow-up creates a realistic test of nuanced advocacy.", "A public-question rehearsal.", "Acknowledge the limitation, explain the cost of delay, narrow the action, and name review conditions.", "Nuance is not evasion when it still produces a decision.", "Rehearse the complete public synthesis.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  59: experience("review", "light", "This is a compact retrieval rehearsal before transfer, not a second content lecture.", "A five-move synthesis rehearsal.", "Retrieve, compare, represent, recommend, and revise using one source prompt.", "The review makes the assessment strategy visible.", "Deliver an accountable public position.", ["orientation", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "No new lesson content is introduced." }]),
  60: experience("assessment", "deep", "The final lesson transfers the module’s judgement work into a credible public product.", "A C2 public-position transfer assessment.", "Choose a briefing or recommendation route and make the evidence, ethics, audience, and revision trigger explicit.", "A strong position is qualified, source-faithful, representative, and open to revision.", "Carry this public-judgement practice into the next module.", ["orientation", "evidence", "meaningful-use", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"], [{ stage: "encounter", reason: "The source pack is supplied by the assessment prompt rather than pre-taught." }, { stage: "supported-practice", reason: "External feedback is optional and remains outside the product." }])
};

export { C2_MODULE_4_EXPERIENCES };
