import type { LessonExperience } from "./types";
const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], archetypeRationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages?: LessonExperience["intentionallyOmittedStages"]): LessonExperience => ({ archetype, density, archetypeRationale, selectedStages, intentionallyOmittedStages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });
const C2_MODULE_10_EXPERIENCES: Record<number, LessonExperience> = {
  136: experience("review", "normal", "The capstone begins with a visible map so the learner can coordinate the whole C2 system.", "An argument-mapping studio.", "Place evidence, assumptions, values, and consequences on one map.", "A position becomes defensible when its hidden moves are visible.", "Compare how a position travels across genres.", ["orientation","encounter","supported-practice","retrieval","next-bridge"], ["worked-example","arabic-help","extended-rationale"]),
  137: experience("reading", "normal", "The learner needs source comparison before public mediation.", "A cross-genre reading.", "Read the research brief, testimony, and editorial; mark each text's job.", "Different genres contribute different kinds of authority.", "Control information density for a chosen audience.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","worked-example","extended-rationale"]),
  138: experience("grammar", "light", "Audience design requires a precise choice between compression and explicit clauses.", "An information-density language studio.", "Rewrite dense statements for a public audience and compare the processing cost.", "Clarity is not simplification of thought; it is responsible routing of thought.", "Hear authority without overclaiming.", ["orientation","encounter","supported-practice","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
  139: experience("listening", "normal", "The capstone needs audio evidence of qualified authority before learners speak publicly.", "An audio-first authority hearing.", "Listen for confidence, qualification, and the boundary around the recommendation; reveal the transcript after the first attempt.", "A limit can increase trust when it is connected to action.", "Answer the strongest objection.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["transcript","worked-example","arabic-help"], [{ stage: "supported-practice", reason: "Transcript support follows active listening." }]),
  140: experience("interaction", "normal", "A serious objection is the first social test of the learner's capstone position.", "An objection-and-concession exchange.", "Acknowledge the objection, preserve what it changes, and offer a revisable safeguard.", "Concession must alter the argument's shape.", "Give a public explanation.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
  141: experience("speaking", "normal", "Public explanation follows objection handling so the learner speaks with tested boundaries.", "A concise public briefing.", "Explain the evidence path to a non-specialist audience without erasing uncertainty.", "Mediation changes route and register, not evidence conditions.", "Draft for two audiences.", ["orientation","encounter","supported-practice","meaningful-use","retrieval","next-bridge"], ["worked-example","external-ai-prompt","arabic-help"]),
  142: experience("writing", "deep", "Audience transfer is a capstone skill and needs enough space for two deliberate versions.", "A two-audience writing studio.", "Write specialist and public versions of one position, keeping evidence boundaries constant.", "The same truth can require different doors into it.", "Audit the position before release.", ["orientation","encounter","supported-practice","meaningful-use","retrieval","next-bridge"], ["worked-example","external-ai-prompt","extended-rationale"]),
  143: experience("review", "normal", "Before the capstone becomes public, the learner needs an ethical release check.", "A pre-release audit.", "Find overclaiming, missing perspectives, hidden values, and unclear review conditions.", "A polished position can still be irresponsible.", "Read dissent as information.", ["orientation","retrieval","supported-practice","next-bridge"], ["worked-example","external-ai-prompt","extended-rationale"], [{ stage: "encounter", reason: "The draft itself supplies the encounter." }]),
  144: experience("reading", "normal", "Dissent must be interpreted before the learner can revise fairly.", "A dissent-analysis reading.", "Separate evidence objections from value-priority objections.", "Not every disagreement can be solved by adding data.", "Listen for repair under pressure.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","worked-example","extended-rationale"]),
  145: experience("listening", "normal", "Repair under pressure gives the learner a model for correcting an overstatement without collapse.", "An audio-first repair hearing.", "Track the earlier claim, the correction, and the changed next step; reveal transcript support later.", "Visible correction protects trust better than silent editing.", "Negotiate a revisable agreement.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["transcript","worked-example","arabic-help"], [{ stage: "supported-practice", reason: "Transcript is delayed until listening evidence is attempted." }]),
  146: experience("interaction", "normal", "The capstone becomes civic when disagreement can become a reviewable agreement.", "A provisional-agreement negotiation.", "Record the boundary, unresolved disagreement, monitoring plan, and review date.", "Agreement is stronger when dissent remains visible.", "Revise after principled challenge.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
  147: experience("writing", "deep", "Revision after challenge is the bridge from competent performance to independent judgement.", "A principled revision studio.", "Rewrite the position after an evidence objection and a values objection.", "Changing the claim when support changes is intellectual action.", "Rehearse the C2 position.", ["orientation","encounter","supported-practice","meaningful-use","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
  148: experience("review", "normal", "The rehearsal lesson makes the final success criteria explicit without doing the work for the learner.", "A capstone rehearsal board.", "Plan the claim, evidence route, objection, affected perspectives, and review trigger.", "A clear plan protects the final response from becoming a list of impressive fragments.", "Defend a position under scrutiny.", ["orientation","retrieval","supported-practice","next-bridge"], ["worked-example","external-ai-prompt","extended-rationale"], [{ stage: "encounter", reason: "The learner's accumulated work supplies the encounter." }]),
  149: experience("assessment", "deep", "The penultimate assessment tests whether the learner can defend a position after the full capstone preparation.", "A position-under-scrutiny assessment.", "Submit a dossier or briefing with evidence, limits, perspectives, objection, and review trigger.", "C2 control is judged by responsible effect, not ornamental complexity.", "Complete the final level challenge.", ["orientation","encounter","evidence","meaningful-use","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
  150: experience("assessment", "deep", "The final lesson must be independent, integrative, and consequential rather than another content lesson.", "The C2 level challenge.", "Analyse a mixed source pack and produce a position that can withstand scrutiny.", "Language serves independent judgement and humane mediation.", "Review the journey and choose a next practice route.", ["orientation","encounter","evidence","meaningful-use","retrieval"], ["external-ai-prompt","worked-example","extended-rationale"], [{ stage: "next-bridge", reason: "This is the terminal authored lesson for the current C2 course." }])
};
export { C2_MODULE_10_EXPERIENCES };
