import type { LessonExperience } from "./types";
const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages?: LessonExperience["intentionallyOmittedStages"]): LessonExperience => ({ archetype, density, archetypeRationale: rationale, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, selectedStages, progressiveSupports, intentionallyOmittedStages });
const C2_MODULE_6_EXPERIENCES: Record<number, LessonExperience> = {
  76: experience("listening", "normal", "Risk distinctions must be heard as a decision sequence before they are reduced to definitions.", "An audio-first risk briefing lab.", "Listen for hazard, exposure, likelihood, consequence, and the action they justify; reveal the transcript after the first pass.", "A proportionate response depends on separating these concepts.", "Challenge an overconfident risk claim.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "arabic-help", "worked-example"], [{ stage: "supported-practice", reason: "Written support follows the initial listening attempt." }]),
  77: experience("interaction", "normal", "The objective is accountable questioning, so a short exchange is more useful than a lecture on risk vocabulary.", "A risk-claim interrogation.", "Ask who is covered, what baseline applies, and what decision follows without manufacturing alarm.", "Precision protects both public trust and public safety.", "Read a crisis update for its commitments.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  78: experience("reading", "deep", "Institutional promises are understood through scope and omission, so the learner needs a close-reading route.", "A crisis-update reading studio.", "Mark what the statement promises, to whom, and what it leaves conditional.", "Careful wording can create a duty while preserving flexibility.", "Speak under uncertainty without pretending certainty.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  79: experience("speaking", "normal", "Responsible leadership is a public action under uncertainty, not a vocabulary display.", "A crisis leadership speaking rehearsal.", "Acknowledge what is unknown, name an immediate action, and set a revision point.", "Calm becomes credible when it includes a checkable next update.", "Rehearse the risk checkpoint.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  80: experience("review", "light", "This checkpoint consolidates the control questions rather than introducing another dense source.", "A risk-communication checkpoint.", "Retrieve hazard, exposure, uncertainty, proportionate action, and revision timing.", "The final module task will test whether these distinctions guide action.", "Notice agency in public narratives.", ["orientation", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "No new source content is introduced." }]),
  81: experience("reading", "deep", "Agency is inferred from grammar, quotation, and omission, so the lesson needs evidence marking.", "A public-narrative agency studio.", "Identify who acts, who is acted upon, and whose refusal or choice disappears.", "A passive success story can hide active subjects.", "Make presupposition visible.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  82: experience("grammar", "light", "Presupposition is isolated so the learner can control framing without packing another content-heavy lesson.", "A grammar clinic on loaded questions.", "Find what a question treats as already accepted, then reformulate it more fairly.", "Changing the question can change the space of possible answers.", "Rewrite a public narrative for agency.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The examples carry the new content." }]),
  83: experience("writing", "deep", "Reframing requires evidence discipline and audience control, so the learner needs a full drafting route.", "An agency-preserving rewrite workshop.", "Rewrite the passage, explain the original frame, and flag what the evidence does not establish.", "Ethical reframing clarifies agency without inventing motives.", "Negotiate a public label.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  84: experience("interaction", "normal", "The objective is negotiated wording under disagreement, not a list of synonyms.", "A public-label negotiation.", "Compare labels, identify what each foregrounds, and agree on wording that keeps cost visible.", "Optimism must not erase conflict or affected people.", "Hear responsibility in institutional wording.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  85: experience("listening", "normal", "Power in institutional language is easiest to notice when the learner listens before seeing the nouns and passive forms written down.", "An audio-first institutional-language lab.", "Listen for passive voice, nominalisation, euphemism, and the responsibility each one obscures; reveal the transcript afterward.", "Grammar can distribute responsibility without naming a single actor.", "Distinguish expertise from status.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "arabic-help", "extended-rationale"], [{ stage: "supported-practice", reason: "The transcript remains hidden until the first listening pass." }]),
  86: experience("reading", "deep", "Expertise is distributed across models, operations, and lived consequences, so comparison is central.", "A distributed-expertise reading studio.", "Compare what each source knows and why no single status marker is enough.", "Relevant knowledge includes consequences and accountability, not only credentials.", "Explain a changing profession.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  87: experience("speaking", "normal", "The learner must explain change without reducing workers to output, so a human-facing speaking route is appropriate.", "A changing-profession explanation rehearsal.", "Describe changed tasks, retained judgement, risks, and the support needed for adaptation.", "A humane account makes expertise visible rather than treating people as replaceable.", "Write a lifelong-learning proposal.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  88: experience("writing", "deep", "A credible learning proposal must connect evidence to access, time, and institutional support.", "A lifelong-learning policy workshop.", "Propose a pathway, identify constraints, and name evidence that would show whether it works.", "Adaptation is credible only when practice is accessible and outcomes are humane.", "Rehearse the module's transfer questions.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  89: experience("review", "light", "A short rehearsal protects the final assessment from becoming a memory test.", "A risk, power, and adaptation review.", "Retrieve the six transfer questions and apply them to one unfamiliar scenario.", "The final recommendation must connect risk, agency, expertise, and revision.", "Design an accountable adaptation.", ["orientation", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The learner supplies an unfamiliar transfer scenario." }]),
  90: experience("assessment", "deep", "The final task combines source mediation, responsibility, expertise, and adaptation for a defined public audience.", "A C2 accountable-adaptation transfer assessment.", "Choose a briefing or spoken recommendation route, preserve source limits, make responsibility visible, and state a revision trigger.", "Strong performance is calibrated, agency-preserving, expertise-sensitive, accessible, and revisable.", "Carry this control into Module 7.", ["orientation", "evidence", "meaningful-use", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"], [{ stage: "encounter", reason: "The assessment source pack supplies the encounter." }, { stage: "supported-practice", reason: "External feedback remains optional and outside the product." }])
};
export { C2_MODULE_6_EXPERIENCES };
