import type { LessonExperience } from "./types";

const experience = (
  archetype: LessonExperience["archetype"],
  density: LessonExperience["density"],
  rationale: string,
  whatItIs: string,
  whatToDo: string,
  whatMatters: string,
  whatNext: string,
  selectedStages: LessonExperience["selectedStages"],
  progressiveSupports: LessonExperience["progressiveSupports"],
  omitted: LessonExperience["intentionallyOmittedStages"] = [],
): LessonExperience => ({
  archetype,
  density,
  archetypeRationale: rationale,
  selectedStages,
  intentionallyOmittedStages: omitted,
  firstView: { whatItIs, whatToDo, whatMatters, whatNext },
  progressiveSupports,
});

export const C2_MODULE_2_EXPERIENCES: Record<number, LessonExperience> = {
  16: experience("reading", "deep", "The module opens by testing how headline figures can conceal distribution, labour conditions, and value judgements.", "A public-economy reading studio / استوديو قراءة الاقتصاد العام", "Compare the data commentary with the worker account, then separate measurement from lived impact.", "A figure is evidence about one dimension, not a complete account of a life.", "Carry the distinction into institutional language and public trust.", ["orientation", "encounter", "notice", "supported-practice", "retrieval", "evidence", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  17: experience("writing", "deep", "The learner must turn economic analysis into a balanced memo without hiding the distributional stakes.", "A precarious-work policy memo / مذكرة سياسة عن العمل غير المستقر", "State the indicator, identify who bears the risk, and qualify the recommendation with evidence.", "Balance is not false equivalence; it is explicit attention to competing effects.", "Rewrite institutional language so responsibility is visible.", ["orientation", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["external-ai-prompt", "worked-example", "arabic-help"], [{ stage: "encounter", reason: "The writing brief is the central encounter and source comparison is embedded in planning." }]),
  18: experience("grammar", "light", "Modality is treated as an ethical calibration tool: certainty should reflect the quality of evidence.", "A certainty-calibration clinic / عيادة معايرة اليقين", "Rank claims from tentative to strong, then revise modal verbs and reporting adverbs.", "The grammar choice tells readers how much confidence the evidence deserves.", "Apply the calibration to a public institutional notice.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The examples provide the full context for this short precision clinic." }, { stage: "meaningful-use", reason: "A short revision set is sufficient before the next applied lesson." }]),
  19: experience("interaction", "normal", "Institutional trust becomes concrete when the learner must revise evasive language for an affected public.", "A public-notice revision dialogue / حوار مراجعة إشعار عام", "Take the institutional and resident perspectives, then negotiate wording that preserves agency and due process.", "A polite tone cannot replace clear responsibility, limits, and redress.", "Move from public wording to artistic interpretation and the limits of meaning.", ["orientation", "encounter", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "notice", reason: "The dialogue itself exposes the hidden agency the learner must notice." }]),
  20: experience("reading", "deep", "Aesthetic judgement requires evidence-led interpretation while allowing ambiguity to remain productive.", "A bilingual gallery-guide studio / استوديو دليل معرض ثنائي اللغة", "Compare the review and artist statement, then defend one reading and name a plausible alternative.", "A strong interpretation is specific without pretending to be the only possible meaning.", "Use the same discipline when explaining scientific uncertainty.", ["orientation", "encounter", "notice", "supported-practice", "retrieval", "evidence", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  21: experience("speaking", "normal", "Fronting is useful here only when it creates a deliberate rhetorical focus in a critical review.", "A gallery-guide speaking rehearsal / تدريب شفهي لدليل معرض", "Deliver a short interpretation, foregrounding one formal detail and acknowledging another reading.", "Rhetorical emphasis should guide attention, not decorate every sentence.", "Listen for how scientific speakers position their sources.", ["orientation", "encounter", "notice", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "supported-practice", reason: "One model and one rehearsal are enough; delivery is the evidence." }]),
  22: experience("listening", "normal", "The scientific briefing is audio-first because C2 listeners must hear the distinction between correlation, causation, and provisional interpretation.", "An evidence-explanation listening lab / مختبر الاستماع لشرح الدليل", "Listen once for the finding, again for the limitation, and reveal the transcript only after your notes are complete.", "Credible uncertainty is precise about both what is supported and what remains unknown.", "Mediate the same evidence for a general audience in writing.", ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], ["transcript", "word-support", "arabic-help"], [{ stage: "supported-practice", reason: "The first pass deliberately tests unaided listening and inference." }]),
  23: experience("writing", "deep", "Public explanation is a mediation task: simplify density without weakening causal or evidential relationships.", "A science-to-public evidence note / مذكرة دليل علمية للجمهور", "Write what the study shows, what it does not show, and what a better next test would examine.", "Plain language must not become false certainty.", "Use culturally careful representation in the migration dialogue.", ["orientation", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  24: experience("interaction", "normal", "Migration and belonging are learned through reciprocal mediation rather than a one-sided exchange of opinions.", "A facilitated belonging dialogue / حوار انتماء مُيسّر", "Represent residents and newcomers accurately, then identify a shared condition for usable inclusion.", "Do not speak for a group as though it were uniform or make adaptation a one-way demand.", "Carry the attention to power into crisis communication.", ["orientation", "encounter", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "notice", reason: "The structural assumption is uncovered through the dialogue rather than a separate lecture." }]),
  25: experience("listening", "normal", "Crisis language is assessed through sequence, omission, reassurance, and contingency rather than vocabulary recall alone.", "A crisis-update listening lab / مختبر الاستماع لتحديث أزمة", "Listen for known facts, unknowns, actions, and review triggers before opening the transcript.", "Calm communication is credible when it does not manufacture certainty.", "Use mixed conditionals to explain how past choices shape present risk.", ["orientation", "encounter", "notice", "retrieval", "evidence", "next-bridge"], ["transcript", "arabic-help", "tip"], [{ stage: "supported-practice", reason: "The first response must come from listening, not reading." }]),
  26: experience("grammar", "normal", "Mixed conditionals make counterfactual responsibility visible across time in crisis reasoning.", "A counterfactual-risk clinic / عيادة التفكير الافتراضي في المخاطر", "Connect a past decision to a present consequence, then test whether the implied time reference is clear.", "Advanced grammar should clarify responsibility and contingency, not obscure it.", "Analyse how public labels frame the next lesson’s debate.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The conditional models carry the crisis context." }, { stage: "meaningful-use", reason: "Application stays focused on precision rather than a second full task." }]),
  27: experience("reading", "deep", "Framing becomes visible when the learner compares labels, processes, and the social consequences a phrase makes natural.", "A discourse-and-power reading lab / مختبر قراءة الخطاب والسلطة", "Annotate what the label foregrounds, omits, legitimises, and polarises.", "A single label can turn a procedural dispute into a judgement about character.", "Turn the analysis into a careful spoken recommendation about work and value.", ["orientation", "encounter", "notice", "supported-practice", "retrieval", "evidence", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  28: experience("speaking", "normal", "Public narrative is transferred through a concise recommendation that makes framing choices audible.", "A public-narrative briefing / إحاطة حول السردية العامة", "Deliver a one-minute recommendation, identifying the frame you reject and the frame you propose.", "Precision includes emphasis, register, and the ethical consequences of naming.", "Review the module’s reasoning operations before the transfer assessment.", ["orientation", "encounter", "notice", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "supported-practice", reason: "A model line supports delivery without replacing the learner’s judgement." }]),
  29: experience("review", "light", "The review consolidates calibration, agency, distribution, framing, and uncertainty before the final public transfer.", "A C2 judgement review / مراجعة الحكم في C2", "Choose one earlier claim, revise its certainty, name its affected group, and add a review condition.", "Transfer depends on seeing the relationship between language, evidence, and consequences.", "Complete the final public-narrative assessment.", ["orientation", "notice", "retrieval", "evidence", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The learner retrieves from prior module artefacts rather than meeting a new source." }, { stage: "meaningful-use", reason: "The review remains deliberately light before assessment." }]),
  30: experience("assessment", "deep", "The transfer assessment asks the learner to mediate conflict and public value without flattening uncertainty or responsibility.", "A public-narrative transfer assessment / تقييم نقل السردية العامة", "Produce an expert recommendation, a public summary, and a short rationale explaining your framing and evidence limits.", "C2 performance is proportionate, audience-aware, revisable, and accountable.", "Carry this judgement studio into C2 Module 3 and increasingly independent work.", ["orientation", "encounter", "notice", "supported-practice", "meaningful-use", "retrieval", "evidence", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
};
