import type { LessonExperience } from "./types";

const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], archetypeRationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages?: LessonExperience["intentionallyOmittedStages"]): LessonExperience => ({ archetype, density, archetypeRationale, selectedStages, intentionallyOmittedStages, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, progressiveSupports });

const C2_MODULE_9_EXPERIENCES: Record<number, LessonExperience> = {
  121: experience("reading", "normal", "Epistemic responsibility begins by separating probability from proof before the learner is asked to make a recommendation.", "A probability-and-proof reading.", "Read once for the claim, then mark what is measured, inferred, and still unknown.", "A calibrated estimate is not a promise or a fact about the present.", "Match language of certainty to evidence.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","worked-example","arabic-help"]),
  122: experience("grammar", "light", "Precise modal and reporting language gives the learner a compact tool for epistemic calibration.", "An epistemic-claim language studio.", "Recast strong claims as supported, tentative, or conditional claims and compare the change in responsibility.", "Grammar can prevent an inference from pretending to be proof.", "Hear uncertainty in expert speech.", ["orientation","encounter","supported-practice","retrieval","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "meaningful-use", reason: "Independent calibration follows in the listening and writing tasks." }]),
  123: experience("listening", "normal", "Expert uncertainty is easier to notice when conditions, confidence, and recommended action arrive through audio before transcript support.", "An audio-first uncertainty hearing.", "Listen for the model's condition, confidence level, and justified action; reveal the transcript only after your first attempt.", "Careful listening distinguishes caution from evasion.", "Compare expert and local knowledge.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["transcript","arabic-help","worked-example"], [{ stage: "supported-practice", reason: "The transcript follows active listening rather than replacing it." }]),
  124: experience("reading", "normal", "Plural knowledge requires comparison without forcing distinct vantage points into a false contradiction.", "An expert-and-local-knowledge comparison reading.", "Mark what each source can observe, what each cannot establish alone, and where combined testing is possible.", "Different evidence sources can be complementary without being interchangeable.", "Ask whose evidence is missing.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","worked-example","extended-rationale"]),
  125: experience("interaction", "normal", "The lesson turns epistemic responsibility into a question sequence that reveals absence without becoming accusatory.", "A missing-evidence inquiry.", "Ask who was represented, who was absent, and what conclusion must be delayed until the gap is addressed.", "A fair question can widen the evidence before it narrows the decision.", "Reconcile measurement, testimony, and interpretation.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
  126: experience("speaking", "normal", "Spoken synthesis tests whether the learner can preserve distinctions while making a complex evidence set usable.", "A three-source synthesis rehearsal.", "Give a short spoken account that separates measurement, testimony, and interpretation before drawing a qualified conclusion.", "Clarity should not flatten the differences that make the conclusion defensible.", "Frame a plausible future.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","external-ai-prompt"]),
  127: experience("grammar", "light", "Scenario language bridges epistemic humility and future-oriented reasoning without treating possibility as prediction.", "A plausible-future framing studio.", "Write conditional statements for a future under named assumptions, then identify what would make the scenario less plausible.", "A scenario is useful when its conditions remain visible.", "Compare time horizons.", ["orientation","encounter","supported-practice","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
  128: experience("reading", "normal", "A time-horizon comparison makes delayed consequences visible and prepares the learner for a multi-scenario brief.", "A short-, medium-, and long-term consequences reading.", "Track the benefit, obligation, and shifted cost across three time horizons.", "A real immediate gain does not complete a long-term appraisal.", "Write two plausible scenarios.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["word-support","worked-example","extended-rationale"]),
  129: experience("writing", "deep", "The scenario brief asks the learner to turn uncertainty into a useful decision aid without inventing certainty.", "A two-scenario policy brief workshop.", "Draft two plausible futures, name assumptions, and recommend an early-warning indicator; use external feedback after your own draft.", "Good foresight makes conditions and revision signals observable.", "Name the value choice behind priority.", ["orientation","encounter","meaningful-use","evidence","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
  130: experience("review", "light", "The checkpoint separates empirical description from the value judgement that turns information into priority.", "A measurement-versus-value checkpoint.", "Classify statements as measurement, inference, or value choice, then explain the transition between them.", "A priority is never only a number; it needs a publicly defensible reason.", "Hear intergenerational responsibility.", ["orientation","retrieval","next-bridge"], ["worked-example","arabic-help","tip"], [{ stage: "encounter", reason: "The checkpoint retrieves the distinctions built across Lessons 121–129." }]),
  131: experience("listening", "normal", "Intergenerational responsibility is carried by conditions and distributed costs that the learner must hear before seeing the transcript.", "An audio-first responsibility hearing.", "Listen for present benefit, deferred burden, and the safeguard that keeps future stakeholders visible; reveal the transcript afterward.", "Responsibility means making who carries risk visible, not rejecting every present benefit.", "Negotiate a fair trade-off.", ["orientation","encounter","notice","evidence","retrieval","next-bridge"], ["transcript","arabic-help","worked-example"], [{ stage: "supported-practice", reason: "Transcript support follows the initial listening attempt." }]),
  132: experience("interaction", "normal", "Fair trade-offs need conditional concessions that change the proposal rather than merely soften its tone.", "A distributive-fairness negotiation.", "State unequal exposure, propose a concrete safeguard, and make agreement conditional on a testable protection.", "Acknowledgement becomes repair only when it changes action or process.", "Chair plural deliberation.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","arabic-help","tip"]),
  133: experience("speaking", "normal", "Chairing a plural deliberation makes disagreement, evidence gaps, and decision rules audible as a coordinated public skill.", "A multi-voice deliberation rehearsal.", "Name the majority preference, minority risk, unresolved evidence gap, and rule that will govern the trade-off.", "A decision can be clear without pretending disagreement has disappeared.", "Rehearse accountable decision language.", ["orientation","encounter","meaningful-use","retrieval","next-bridge"], ["worked-example","external-ai-prompt","arabic-help"]),
  134: experience("writing", "deep", "The accountable-decision revision task turns the module's epistemic, future-facing, and fairness distinctions into observable language.", "An accountable decision-statement studio.", "Revise a policy statement so it names evidence, uncertainty, affected groups, fairness conditions, and a review trigger.", "Accountability includes a credible path for revision.", "Design a decision people can question.", ["orientation","encounter","meaningful-use","evidence","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"]),
  135: experience("assessment", "deep", "The transfer assessment requires a defensible collective decision that keeps evidence, uncertainty, values, affected people, and revision visible.", "An accountable collective-choice dossier.", "Use the source pack to produce a decision dossier or briefing, then make the dissent, safeguard, and review condition explicit.", "A decision is stronger when people can understand, question, and revisit it.", "Review external feedback before the final C2 arc.", ["orientation","encounter","meaningful-use","evidence","retrieval","next-bridge"], ["external-ai-prompt","worked-example","extended-rationale"])
};

export { C2_MODULE_9_EXPERIENCES };
