import type { LessonExperience } from "./types";
const experience = (archetype: LessonExperience["archetype"], density: LessonExperience["density"], rationale: string, whatItIs: string, whatToDo: string, whatMatters: string, whatNext: string, selectedStages: LessonExperience["selectedStages"], progressiveSupports: LessonExperience["progressiveSupports"], intentionallyOmittedStages?: LessonExperience["intentionallyOmittedStages"]): LessonExperience => ({ archetype, density, archetypeRationale: rationale, firstView: { whatItIs, whatToDo, whatMatters, whatNext }, selectedStages, progressiveSupports, intentionallyOmittedStages });
const C2_MODULE_5_EXPERIENCES: Record<number, LessonExperience> = {
  61: experience("reading", "deep", "Interpretation must be argued from evidence rather than announced as taste.", "A close-reading studio on artistic meaning.", "Trace which details support the interpretation and which remain open.", "A persuasive reading shows its evidence and its limits.", "Negotiate a competing reading next.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  62: experience("interaction", "normal", "The objective is disagreement with intellectual generosity, so the exchange is central.", "A bilingual interpretation negotiation.", "Name common evidence, then qualify the rival inference.", "Keeping a question open is not the same as avoiding a position.", "Hear uncertainty in a scientific explanation.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  63: experience("listening", "normal", "The learner must hear the sequence from data to model to action before seeing it written.", "An audio-first science explanation lab.", "Listen for observation, model, confidence, and implication; reveal the transcript after the first pass.", "Uncertainty can guide proportionate action rather than stop explanation.", "Mediate the expertise for the public.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "arabic-help", "extended-rationale"], [{ stage: "supported-practice", reason: "Written support follows the initial listening attempt." }]),
  64: experience("writing", "deep", "Mediation is the main challenge: preserve distinctions while changing the route to understanding.", "A public-explanation workshop.", "Write for an informed non-specialist and mark the limits of the claim.", "Clear language does not require false certainty.", "Use concession to protect precision.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  65: experience("grammar", "light", "The lesson isolates concession because the module needs qualified claims, not another content-heavy task.", "A grammar clinic on contrast and qualification.", "Transform blunt claims into accurate concessions and contrasts.", "A concession should change the reasoning, not merely soften the tone.", "Compare institutional and personal belonging.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "The examples carry the new content." }]),
  66: experience("reading", "deep", "The two accounts measure belonging differently and require comparison rather than recall.", "A paired-source reading studio on belonging.", "Compare attendance, voice, dissent, and agency across the accounts.", "Participation without agency can be mistaken for belonging.", "Listen to leadership under crisis.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  67: experience("listening", "normal", "Crisis leadership is heard as an ordered promise of what is known, useful now, and revisable.", "An audio-first crisis briefing.", "Listen once for the unknown and actionable known; reveal the transcript to check the sequence.", "Calm is credible when it includes a revision route.", "Answer the difficult public question.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["transcript", "worked-example", "arabic-help"], [{ stage: "supported-practice", reason: "The transcript remains hidden until the first listening pass." }]),
  68: experience("speaking", "normal", "The task requires a public answer under pressure, not a rehearsed vocabulary display.", "A difficult-question speaking rehearsal.", "Acknowledge the harm, limit the claim, and give an inspectable action.", "Accountability is stronger than reassurance because it can be checked.", "Analyse how labels frame responsibility.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  69: experience("reading", "deep", "The passage makes discourse framing visible through contrasting labels and remedies.", "A public-language framing studio.", "Mark what each label foregrounds, hides, and makes actionable.", "Word choice can distribute responsibility and time.", "Consolidate the module's control questions.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  70: experience("review", "light", "This is retrieval and transfer rehearsal, not another lecture before the assessment.", "A five-question meaning checkpoint.", "Retrieve observation, inference, representation, framing, and revision.", "The checkpoint makes the final assessment strategy explicit.", "Study rhetorical structures for adaptation.", ["orientation", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"], [{ stage: "encounter", reason: "No new source content is introduced." }]),
  71: experience("grammar", "normal", "Rhetorical structure is isolated so the learner can control public reasoning without overpacking the lesson.", "A grammar clinic on inquiry and parallelism.", "Use rhetorical questions and parallel structures to guide an adaptation argument.", "Rhetorical force must open reasoning, not replace evidence.", "Write an adaptation memo.", ["orientation", "notice", "supported-practice", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "tip"]),
  72: experience("writing", "deep", "The learner must turn mixed results into a revision plan with a testable next step.", "A learning-oriented adaptation memo.", "Diagnose the evidence, propose a change, and name the next signal.", "Learning from failure links interpretation to changed action.", "Test reliability in narrative voice.", ["orientation", "encounter", "meaningful-use", "evidence", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"]),
  73: experience("reading", "deep", "Reliability is an inference from scope, omission, and external fit, so the learner needs a close-reading route.", "A narrative-reliability studio.", "Compare the narrator's confidence with what the account leaves out.", "A confident voice is not automatically a reliable voice.", "Repair a damaged conversation.", ["orientation", "encounter", "notice", "evidence", "retrieval", "next-bridge"], ["word-support", "extended-rationale", "arabic-help"]),
  74: experience("speaking", "normal", "Repair requires a live sequence of acknowledgement, specificity, and a credible next step.", "A trust-repair conversation rehearsal.", "Name the impact, make the record visible, and offer a checkable action.", "Repair does not require pretending the harm was small.", "Complete the Module 5 transfer.", ["orientation", "encounter", "meaningful-use", "retrieval", "next-bridge"], ["worked-example", "arabic-help", "extended-rationale"]),
  75: experience("assessment", "deep", "The final task transfers interpretation, uncertainty, framing, representation, and repair into one audience-aware product.", "A C2 public-meaning transfer assessment.", "Choose an explainer or recommendation route and mediate the source pack with visible limits and a revision trigger.", "Difficult knowledge becomes useful when it remains faithful, ethical, and actionable.", "Carry this meaning-under-pressure practice into Module 6.", ["orientation", "evidence", "meaningful-use", "retrieval", "next-bridge"], ["external-ai-prompt", "worked-example", "extended-rationale"], [{ stage: "encounter", reason: "The assessment source pack supplies the encounter." }, { stage: "supported-practice", reason: "External feedback remains optional and outside the product." }])
};
export { C2_MODULE_5_EXPERIENCES };
