import type { CourseDefinition, GrammarTopic, LessonDefinition, LessonStep, VocabularyItem } from "./types";
import { enrichLesson } from "./activity-plan";
import { buildModuleDefinitions } from "./module-definitions";
import { C2_MODULE_1_AUTHORED_ACTIVITIES } from "./c2-module-1-authored-activities";
import { C2_MODULE_1_EXPERIENCES } from "./c2-module-1-experiences";
import { C2_MODULE_2_AUTHORED_ACTIVITIES } from "./c2-module-2-authored-activities";
import { C2_MODULE_2_EXPERIENCES } from "./c2-module-2-experiences";
import { C2_MODULE_3_AUTHORED_ACTIVITIES } from "./c2-module-3-authored-activities";
import { C2_MODULE_3_EXPERIENCES } from "./c2-module-3-experiences";
import { C2_MODULE_4_AUTHORED_ACTIVITIES } from "./c2-module-4-authored-activities";
import { C2_MODULE_4_EXPERIENCES } from "./c2-module-4-experiences";

const STEPS: LessonStep[] = [
  { id: "start", title: "Enter the question", titleArabic: "ادخل إلى السؤال", purpose: "Connect the theme to a real decision, tension, or intellectual problem.", estimatedMinutes: 10 },
  { id: "explore", title: "Interrogate the language", titleArabic: "حلّل اللغة", purpose: "Study precision, idiom, stance, register, and the hidden choices behind sophisticated language.", estimatedMinutes: 24 },
  { id: "notice", title: "Notice the architecture", titleArabic: "لاحظ البناء", purpose: "Examine how syntax, cohesion, rhythm, and rhetorical structure shape interpretation.", estimatedMinutes: 22 },
  { id: "build", title: "Build a position", titleArabic: "ابنِ موقفاً", purpose: "Plan a nuanced response that acknowledges uncertainty, evidence, and competing perspectives.", estimatedMinutes: 25 },
  { id: "respond", title: "Mediate the complexity", titleArabic: "بسّط التعقيد", purpose: "Read, compare, reinterpret, or explain demanding material for a defined audience.", estimatedMinutes: 32 },
  { id: "prove", title: "Make it unmistakably yours", titleArabic: "اجعل صوتك واضحاً", purpose: "Produce precise, flexible language with a deliberate effect on the reader or listener.", estimatedMinutes: 28 },
];

type Spec = {
  title: string; titleArabic: string; theme: string; themeArabic: string; anchor: string;
  words: Array<[string, string, string, string]>;
  grammar: [string, string, string, string, string, string, string, string];
  outcome: [string, string, string, string]; reading: string; writing: string;
  chunks: string[]; collocations: string[]; related: string[]; register: "neutral" | "informal" | "formal" | "mixed";
};

const SPECS: Spec[] = [
  {
    title: "The architecture of a convincing argument", titleArabic: "بناء الحجة المقنعة", theme: "argument, evidence, and intellectual honesty", themeArabic: "الحجة والأدلة والنزاهة الفكرية", anchor: "make a case without overstating it",
    words: [["premise","مقدمة الحجة","noun","a proposition on which an argument is based"],["contention","ادعاء","noun","a claim that invites disagreement or examination"],["substantiate","يدعم بالدليل","verb","to support a claim with evidence"],["concession","إقرار بجزء من حجة الخصم","noun","an acknowledgement that part of another position is valid"],["fallacy","مغالطة","noun","a flaw in reasoning"],["tentative","مبدئي أو غير حاسم","adjective","not expressed as final or certain"]],
    grammar: ["Inversion for emphasis","التقديم للتوكيد","Use negative or limiting adverbials to foreground a condition or contrast.","استخدم التقديم بعد عبارات النفي أو التحديد لإبراز الشرط أو التباين.","Not only does the proposal save money, but it also improves access.","Not only the proposal saves money.","Not only does the proposal save money, but it also improves access.","Ask how inversion changes the force of the claim."], outcome: ["I can construct and qualify a sophisticated argument while identifying weak reasoning.","أستطيع بناء حجة متقدمة وتقييدها مع اكتشاف مواطن الضعف في الاستدلال.","You are advising a review panel that must choose between two competing public proposals.","أنت تقدم المشورة للجنة مراجعة عليها الاختيار بين اقتراحين عامين متنافسين."], reading: "A paired editorial and research summary on evidence-based public decision-making; identify premises, concessions, fallacies, and degrees of certainty.", writing: "Write a 500-word advisory paper that makes a recommendation, concedes a serious objection, and supports each major claim.", chunks: ["on balance","there is a case to be made that","notwithstanding this limitation","the evidence does not warrant the conclusion"], collocations: ["underlying premise","substantiate a claim","serious concession","logical fallacy"], related: ["reasoning","inference","validity","counterclaim"], register: "formal"
  },
  {
    title: "Technology, agency, and the human choice", titleArabic: "التكنولوجيا والاختيار الإنساني", theme: "automation, agency, and unintended consequences", themeArabic: "الأتمتة والقدرة على الاختيار والنتائج غير المقصودة", anchor: "decide what technology should not decide",
    words: [["autonomy","استقلالية","noun","the ability to make informed choices independently"],["displacement","إحلال أو استبدال","noun","the replacement of people or practices by something else"],["ubiquitous","منتشر في كل مكان","adjective","present or encountered almost everywhere"],["scrutiny","تدقيق وفحص دقيق","noun","close and critical examination"],["intervene","يتدخل","verb","to become involved in order to alter an outcome"],["fallout","تداعيات","noun","the negative consequences of an event or decision"]],
    grammar: ["Participle clauses and compressed cause","عبارات اسم الفاعل والسبب المختصر","Compress linked ideas when the relationship is clear from context.","اختصر الجمل المرتبطة عندما تكون العلاقة واضحة من السياق.","Having weighed the risks, the committee rejected the deployment.","Having weighed the risks, but the committee rejected the deployment.","Having weighed the risks, the committee rejected the deployment.","Check that the implied subject of the participle clause is clear."], outcome: ["I can discuss technology with precision, balancing innovation, agency, and risk.","أستطيع مناقشة التكنولوجيا بدقة مع الموازنة بين الابتكار والاختيار والمخاطر.","You are preparing a public consultation response about an automated service.","أنت تعد رداً على استشارة عامة حول خدمة مؤتمتة."], reading: "Compare a technology policy briefing with a personal account of automation; trace where efficiency becomes a question of agency.", writing: "Write a consultation response proposing safeguards for an automated public service.", chunks: ["raise questions about","at the expense of","the human cost of","subject to meaningful oversight"], collocations: ["algorithmic scrutiny","technological displacement","human agency","unintended fallout"], related: ["innovation","privacy","accountability","bias"], register: "mixed"
  },
  {
    title: "Living systems and ecological thresholds", titleArabic: "الأنظمة الحية والحدود البيئية", theme: "ecology, resilience, and long-term stewardship", themeArabic: "البيئة والمرونة والرعاية طويلة المدى", anchor: "see the system, not only the symptom",
    words: [["resilience","مرونة وقدرة على التعافي","noun","the capacity to recover from difficulty"],["threshold","عتبة أو حد","noun","a point at which a new condition begins"],["degradation","تدهور","noun","the process of becoming worse in quality"],["biodiversity","تنوع حيوي","noun","the variety of living organisms in an environment"],["mitigate","يخفف","verb","to reduce the harmful effect of something"],["stewardship","إدارة مسؤولة","noun","responsible care of something valuable"]],
    grammar: ["Nominalisation and information density","تحويل الأفعال إلى أسماء وكثافة المعلومات","Use nominalisation deliberately in formal explanation, but unpack it when clarity matters.","استخدم تحويل الأفعال إلى أسماء في الشرح الرسمي، وفككه عندما تكون الوضوح أهم.","The rapid degradation of soil undermines food security.","The rapid degrade of soil undermines food security.","The rapid degradation of soil undermines food security.","Decide whether a dense noun phrase or a clear verb better serves the audience."], outcome: ["I can explain ecological systems, thresholds, and trade-offs for a non-specialist audience.","أستطيع شرح الأنظمة البيئية والحدود والمفاضلات لجمهور غير متخصص.","You are mediating a scientific report for a community deciding how to protect a wetland.","أنت تبسط تقريراً علمياً لمجتمع يقرر كيفية حماية أرض رطبة."], reading: "Mediate a technical ecology report into a public briefing while preserving uncertainty and causal relationships.", writing: "Write a two-part briefing: a plain-language explanation followed by a prioritized stewardship plan.", chunks: ["within ecological limits","a tipping point may be reached","in the longer term","preserve the integrity of"], collocations: ["ecological resilience","critical threshold","habitat degradation","biodiversity loss"], related: ["conservation","ecosystem","restoration","sustainability"], register: "formal"
  },
  {
    title: "Memory, identity, and the stories we inherit", titleArabic: "الذاكرة والهوية والقصص الموروثة", theme: "memory, narrative, and cultural identity", themeArabic: "الذاكرة والسرد والهوية الثقافية", anchor: "ask whose version of the past survives",
    words: [["recollection","ذكرى أو استرجاع","noun","a memory of a past event"],["collective","جماعي","adjective","shared by a group"],["reconcile","يوفق أو يصالح","verb","to make two different ideas or accounts compatible"],["distort","يشوه أو يحرف","verb","to change something from its original form or meaning"],["inheritance","إرث","noun","something passed down from earlier generations"],["vantage point","زاوية نظر","noun","a position from which something is viewed or understood"]],
    grammar: ["Cleft sentences for contrast and focus","جمل التركيز للمقارنة والإبراز","Use it-clefts and what-clefts to foreground a perspective or correction.","استخدم جمل التركيز لإبراز منظور أو تصحيح معلومة.","What matters is not the date but the story attached to it.","What it matters is not the date but the story attached to it.","What matters is not the date but the story attached to it.","Use focus structures to guide attention, not to decorate every sentence."], outcome: ["I can compare narratives about identity and explain how perspective shapes memory.","أستطيع مقارنة روايات الهوية وشرح أثر المنظور في الذاكرة.","You are curating a bilingual exhibit that presents conflicting family and public memories.","أنت تنسق معرضاً ثنائي اللغة يعرض ذكريات عائلية وعامة متعارضة."], reading: "Compare a memoir extract, an oral-history transcript, and a museum label; identify omissions and vantage points.", writing: "Write an interpretive exhibit note that acknowledges competing memories without flattening them.", chunks: ["from the vantage point of","a version of events","memory is not a neutral record","what tends to be overlooked"], collocations: ["collective memory","inherited narrative","distorted recollection","cultural inheritance"], related: ["heritage","testimony","archive","belonging"], register: "mixed"
  },
  {
    title: "Markets, work, and the value of a life", titleArabic: "الأسواق والعمل وقيمة الحياة", theme: "economics, labour, and social value", themeArabic: "الاقتصاد والعمل والقيمة الاجتماعية", anchor: "look beyond the headline figure",
    words: [["disparity","تفاوت","noun","a significant difference, especially an unfair one"],["livelihood","مصدر الرزق","noun","a means of supporting oneself"],["incentivise","يحفز","verb","to encourage behaviour through a reward or benefit"],["precarious","غير مستقر ومحفوف بالمخاطر","adjective","not securely held or likely to change suddenly"],["externality","أثر خارجي","noun","a cost or benefit affecting others not involved in a transaction"],["redistribution","إعادة توزيع","noun","the transfer of resources between groups"]],
    grammar: ["Hedging, boosters, and epistemic modality","التخفيف والتوكيد والاحتمال","Calibrate certainty through modal verbs, adverbs, and reporting verbs.","اضبط درجة اليقين باستخدام الأفعال الناقصة والظروف وأفعال النقل.","The policy is likely to widen disparities unless access is monitored.","The policy definitely likely widens disparities.","The policy is likely to widen disparities unless access is monitored.","Match the strength of your language to the quality of your evidence."], outcome: ["I can evaluate economic claims while distinguishing measurement from value judgement.","أستطيع تقييم الادعاءات الاقتصادية والتمييز بين القياس والحكم القيمي.","You are explaining a labour-market proposal to a mixed audience of workers and policymakers.","أنت تشرح اقتراحاً لسوق العمل لجمهور من العمال وصناع السياسات."], reading: "Read a data commentary and a worker interview; separate indicators, assumptions, lived impact, and policy values.", writing: "Write a balanced policy memo on improving security for precarious workers.", chunks: ["the figures alone do not tell the whole story","a distributional question","incentives may have the opposite effect","from a worker's perspective"], collocations: ["income disparity","secure livelihood","negative externality","wealth redistribution"], related: ["productivity","welfare","taxation","employment"], register: "formal"
  },
  {
    title: "The language of institutions and public trust", titleArabic: "لغة المؤسسات والثقة العامة", theme: "institutions, legitimacy, and public communication", themeArabic: "المؤسسات والشرعية والتواصل العام", anchor: "make institutional language accountable",
    words: [["legitimacy","شرعية","noun","the quality of being accepted as lawful or justified"],["transparency","شفافية","noun","openness about decisions and information"],["mandate","تفويض أو صلاحية","noun","the authority to act given by a constituency"],["bureaucratic","بيروقراطي","adjective","relating to complex administrative systems"],["redress","إنصاف أو معالجة الضرر","noun","a remedy for a wrong or grievance"],["deliberation","مداولة","noun","careful discussion before a decision"]],
    grammar: ["Passive voice, agency, and accountability","المبني للمجهول والفاعل والمساءلة","Choose passive or active voice to manage focus, responsibility, and institutional tone.","اختر المبني للمجهول أو المعلوم للتحكم في التركيز والمسؤولية والنبرة المؤسسية.","The decision was reached after residents had been consulted.","The decision was reached and nobody consulted residents.","The decision was reached after residents had been consulted.","Ask whether hiding the agent is ethical or merely conventional."], outcome: ["I can analyse and rewrite institutional language so responsibility and limits are clear.","أستطيع تحليل لغة المؤسسات وإعادة صياغتها لتوضيح المسؤولية والحدود.","You are revising a public notice after criticism that its wording avoided responsibility.","أنت تراجع إشعاراً عاماً بعد انتقادات بأن صياغته تهربت من المسؤولية."], reading: "Compare a bureaucratic announcement with a plain-language revision; identify whose agency is foregrounded or hidden.", writing: "Rewrite a formal notice for clarity, then add a short rationale explaining your choices.", chunks: ["under the terms of the mandate","the public has a right to know","responsibility cannot be outsourced","subject to due process"], collocations: ["institutional legitimacy","procedural transparency","democratic mandate","effective redress"], related: ["governance","compliance","oversight","accountability"], register: "formal"
  },
  {
    title: "Art, interpretation, and the limits of meaning", titleArabic: "الفن والتفسير وحدود المعنى", theme: "aesthetic judgement and interpretation", themeArabic: "الحكم الجمالي والتفسير", anchor: "defend an interpretation without closing the question",
    words: [["ambiguous","ملتبس","adjective","open to more than one interpretation"],["evocative","مثير للمشاعر والذكريات","adjective","bringing strong images or feelings to mind"],["subvert","يقلب أو يقوض","verb","to challenge or undermine an established idea"],["motif","عنصر متكرر","noun","a recurring image, idea, or feature"],["aesthetic","جمالي","adjective","concerned with beauty or artistic value"],["provocation","استفزاز فكري","noun","an action or work intended to stimulate a reaction"]],
    grammar: ["Fronting and thematic progression","التقديم وتطور الموضوع","Front a complement or adverbial to create a deliberate rhetorical rhythm.","قدّم المفعول أو الظرف لخلق إيقاع بلاغي مقصود.","Rarely has a film made silence feel so politically charged.","Rarely a film has made silence feel so politically charged.","Rarely has a film made silence feel so politically charged.","Use fronting when the shift in focus creates a meaningful effect."], outcome: ["I can interpret artistic choices and defend a reading while respecting ambiguity.","أستطيع تفسير الخيارات الفنية والدفاع عن قراءة مع احترام الغموض.","You are writing a bilingual gallery guide for a work that has divided its audience.","أنت تكتب دليلاً ثنائي اللغة لمعرض حول عمل فني انقسم حوله الجمهور."], reading: "Compare a review and an artist statement; trace how each uses evidence, tone, and omission to create meaning.", writing: "Write a critical review that offers a clear interpretation and anticipates a plausible alternative.", chunks: ["invites the viewer to","resists a single reading","at first glance","on closer examination"], collocations: ["ambiguous motif","evocative image","aesthetic judgement","deliberate provocation"], related: ["symbolism","composition","irony","perspective"], register: "mixed"
  },
  {
    title: "Science, uncertainty, and public explanation", titleArabic: "العلم وعدم اليقين والشرح للجمهور", theme: "scientific reasoning and uncertainty", themeArabic: "الاستدلال العلمي وعدم اليقين", anchor: "explain what the evidence can and cannot say",
    words: [["replicate","يكرر التجربة","verb","to repeat a study or process to check its result"],["correlation","ارتباط","noun","a relationship in which two variables change together"],["causation","سببية","noun","a relationship in which one thing produces an effect"],["marginal","هامشي أو طفيف","adjective","small in amount or effect"],["robust","متين وموثوق","adjective","strong enough to withstand challenge"],["provisional","مؤقت أو قابل للمراجعة","adjective","accepted for now but not final"]],
    grammar: ["Reporting verbs and source positioning","أفعال النقل وتحديد موقع المصدر","Use reporting verbs to distinguish observation, interpretation, criticism, and consensus.","استخدم أفعال النقل للتمييز بين الملاحظة والتفسير والنقد والإجماع.","The authors acknowledge that the correlation does not establish causation.","The authors say the correlation does not establish causation.","The authors acknowledge that the correlation does not establish causation.","Select a reporting verb that accurately represents the source's stance."], outcome: ["I can communicate scientific uncertainty without making evidence sound weaker or stronger than it is.","أستطيع نقل عدم اليقين العلمي دون تضخيم الدليل أو التقليل من قوته.","You are preparing a public-facing explanation of a study that has been widely misunderstood.","أنت تعد شرحاً موجهاً للجمهور لدراسة أسيء فهمها على نطاق واسع."], reading: "Mediate an abstract and a news report, correcting the leap from correlation to causation and preserving provisional findings.", writing: "Write an evidence note for a general audience with a short section called 'What we still do not know'.", chunks: ["the findings suggest rather than prove","the evidence is consistent with","further research is warranted","the study has yet to be replicated"], collocations: ["robust methodology","statistical correlation","provisional finding","causal mechanism"], related: ["hypothesis","sample","variable","replication"], register: "formal"
  },
  {
    title: "Migration, belonging, and the ethics of welcome", titleArabic: "الهجرة والانتماء وأخلاق الترحيب", theme: "mobility, belonging, and intercultural negotiation", themeArabic: "التنقل والانتماء والتفاوض بين الثقافات", anchor: "speak about people without reducing them",
    words: [["diaspora","شتات","noun","a community living away from its ancestral homeland"],["integration","اندماج","noun","the process of becoming part of a wider community"],["marginalise","يهمش","verb","to treat a person or group as unimportant or peripheral"],["reciprocity","تبادلية","noun","a relationship in which both sides give and receive"],["belonging","انتماء","noun","the feeling of being accepted as a member of a group"],["xenophobia","رهاب الأجانب","noun","fear or dislike of people from other countries"]],
    grammar: ["Relative clauses and discourse packaging","الجمل الموصولة وتغليف الخطاب","Use restrictive and non-restrictive relatives to add identity, context, and qualification.","استخدم الجمل الموصولة للتعريف وإضافة السياق والتقييد.","People who arrive first often build networks that later newcomers rely on.","People, who arrive first often build networks.","People who arrive first often build networks that later newcomers rely on.","Check whether the relative clause identifies the noun or comments on it."], outcome: ["I can discuss migration with cultural sensitivity, precision, and attention to power.","أستطيع مناقشة الهجرة بحساسية ثقافية ودقة وانتباه لعلاقات القوة.","You are mediating a community dialogue where residents and newcomers disagree about integration.","أنت تدير حواراً مجتمعياً يختلف فيه السكان والوافدون حول الاندماج."], reading: "Compare a policy statement with first-person testimony; identify labels, assumptions, and moments of genuine reciprocity.", writing: "Write a mediation summary that accurately represents both groups and proposes a shared next step.", chunks: ["a sense of belonging","rather than speaking for","the terms on which people meet","a two-way process"], collocations: ["diaspora community","social integration","systemic marginalisation","mutual reciprocity"], related: ["citizenship","displacement","hospitality","identity"], register: "mixed"
  },
  {
    title: "Risk, crisis, and responsible leadership", titleArabic: "المخاطر والأزمات والقيادة المسؤولة", theme: "risk communication and crisis leadership", themeArabic: "التواصل حول المخاطر وقيادة الأزمات", anchor: "be calm without pretending to know everything",
    words: [["contingency","خطة طوارئ","noun","a possible future event requiring a response"],["escalate","يتصاعد","verb","to become or make more intense"],["vulnerability","قابلية للتضرر","noun","exposure to harm or difficulty"],["foresight","استشراف","noun","the ability to anticipate future developments"],["reassure","يطمئن","verb","to reduce someone's doubts or fears"],["volatile","متقلب","adjective","liable to change rapidly and unpredictably"]],
    grammar: ["Mixed conditionals for counterfactual reasoning","الجمل الشرطية المختلطة للتفكير الافتراضي","Combine time references to explain how a past choice affects a present risk or vice versa.","اربط الأزمنة لشرح أثر قرار سابق في خطر حاضر أو العكس.","Had we acted sooner, the system would now be less vulnerable.","If we acted sooner, the system would now have been safer.","Had we acted sooner, the system would now be less vulnerable.","Make both the unreal time reference and the consequence clear."], outcome: ["I can communicate risk, uncertainty, and contingency plans in a calm, credible voice.","أستطيع التواصل حول المخاطر وعدم اليقين وخطط الطوارئ بصوت هادئ وموثوق.","You are briefing staff during a fast-moving crisis where trust matters as much as speed.","أنت تقدم إحاطة للموظفين أثناء أزمة متسارعة حيث الثقة مهمة بقدر السرعة."], reading: "Compare an emergency statement with expert commentary; evaluate reassurance, omission, and the quality of contingency planning.", writing: "Draft a crisis update that states what is known, unknown, being done, and expected next.", chunks: ["as a precautionary measure","we are monitoring the situation closely","should circumstances change","we do not want to give false reassurance"], collocations: ["contingency planning","acute vulnerability","volatile conditions","responsible leadership"], related: ["resilience","preparedness","emergency","uncertainty"], register: "formal"
  },
  {
    title: "Language, power, and public narratives", titleArabic: "اللغة والسلطة والسرديات العامة", theme: "discourse, power, and framing", themeArabic: "الخطاب والسلطة والتأطير", anchor: "notice what a label makes possible",
    words: [["discourse","خطاب","noun","language used in a particular social or institutional context"],["framing","تأطير","noun","the way an issue is presented or bounded"],["legitimise","يمنح الشرعية","verb","to make something appear acceptable or justified"],["stereotype","صورة نمطية","noun","a fixed and oversimplified belief about a group"],["subtlety","دقة أو رهافة","noun","the quality of being difficult to notice or express exactly"],["polarise","يستقطب","verb","to divide people into strongly opposing groups"]],
    grammar: ["Nominal ellipsis and parallelism","الحذف الاسمي والتوازي","Omit repeated nouns and use parallel structures to create cohesion and rhetorical balance.","احذف الأسماء المتكررة واستخدم التوازي لخلق الترابط والتوازن البلاغي.","Some called it reform; others, a retreat from responsibility.","Some called it reform; others called a retreat from responsibility.","Some called it reform; others, a retreat from responsibility.","Use ellipsis only when the missing structure is recoverable and the contrast is clear."], outcome: ["I can analyse how public narratives frame groups, choices, and responsibility.","أستطيع تحليل كيفية تأطير السرديات العامة للجماعات والاختيارات والمسؤولية.","You are editing a public information campaign to avoid polarising or stereotyped language.","أنت تراجع حملة معلومات عامة لتجنب اللغة المستقطبة أو النمطية."], reading: "Annotate headlines and campaign extracts for metaphor, agency, labels, and omissions; rewrite one passage from another vantage point.", writing: "Write an editorial explaining how a public narrative could be reframed without hiding the underlying conflict.", chunks: ["the language used to describe","a seemingly neutral label","the effect is to","from another angle"], collocations: ["dominant discourse","political framing","cultural stereotype","subtle distinction"], related: ["rhetoric","ideology","narrative","representation"], register: "mixed"
  },
  {
    title: "The future of work and lifelong learning", titleArabic: "مستقبل العمل والتعلم مدى الحياة", theme: "learning, expertise, and adaptation", themeArabic: "التعلم والخبرة والتكيف", anchor: "turn change into a learning question",
    words: [["upskill","يطور مهاراته","verb","to learn new skills for a changing role"],["obsolescence","تقادم","noun","the state of no longer being useful or current"],["transferable","قابل للنقل بين المجالات","adjective","usable in different roles or contexts"],["apprenticeship","تدريب مهني عملي","noun","a period of practical training under an experienced person"],["adaptability","قابلية للتكيف","noun","the ability to adjust to new conditions"],["expertise","خبرة متخصصة","noun","high-level knowledge or skill in a field"]],
    grammar: ["Future in the past and shifting projections","المستقبل في الماضي وتغير التوقعات","Use would, was going to, and perfect forms to report earlier expectations and revise them.","استخدم صيغ المستقبل في الماضي والصيغ التامة لنقل التوقعات السابقة ومراجعتها.","The role was expected to disappear, but it has since evolved.","The role expected to disappear, but it evolved.","The role was expected to disappear, but it has since evolved.","Signal clearly whether you are reporting a past forecast or a current result."], outcome: ["I can discuss changing work and learning systems while separating prediction from evidence.","أستطيع مناقشة تغير العمل وأنظمة التعلم مع التمييز بين التوقع والدليل.","You are designing a lifelong-learning plan for workers whose roles are changing.","أنت تصمم خطة تعلم مدى الحياة لعمال تتغير أدوارهم."], reading: "Compare a labour forecast with worker interviews; identify transferable skills that the forecast overlooks.", writing: "Write a strategic learning plan that balances technical upskilling with human and transferable expertise.", chunks: ["remain relevant in the face of","a transferable foundation","the forecast rests on","learning is not a one-off event"], collocations: ["rapid obsolescence","transferable expertise","professional adaptability","structured apprenticeship"], related: ["reskill","career pathway","mentoring","competence"], register: "mixed"
  },
  {
    title: "Law, fairness, and competing rights", titleArabic: "القانون والإنصاف والحقوق المتنافسة", theme: "rights, justice, and ethical disagreement", themeArabic: "الحقوق والعدالة والاختلاف الأخلاقي", anchor: "argue fairly when values collide",
    words: [["jurisdiction","اختصاص قضائي","noun","the authority of a court or institution over a matter"],["precedent","سابقة قانونية","noun","an earlier case used as an example for later decisions"],["equitable","منصف","adjective","fair and impartial, though not necessarily identical"],["infringe","ينتهك","verb","to limit or violate a right"],["proportionality","تناسب","noun","the quality of being appropriately related in size or effect"],["remedy","وسيلة انتصاف","noun","a legal or practical solution to a wrong"]],
    grammar: ["Legal and formal subjunctive patterns","صيغ الشرط الرسمية والقانونية","Use formal mandative structures and fixed legal patterns when the genre requires them.","استخدم الصيغ الرسمية الثابتة في النصوص القانونية عند الحاجة.","It is essential that the remedy be proportionate to the harm.","It is essential that the remedy is proportionate to the harm.","It is essential that the remedy be proportionate to the harm.","Use the formal pattern when it supports genre and precision, not as a default in conversation."], outcome: ["I can compare competing rights and explain a fair, proportionate remedy.","أستطيع مقارنة الحقوق المتنافسة وشرح وسيلة انتصاف عادلة ومتناسبة.","You are writing a public-facing case note about a difficult rights conflict.","أنت تكتب مذكرة مبسطة للجمهور حول تعارض صعب بين الحقوق."], reading: "Compare a legal summary with an advocacy statement; identify jurisdiction, precedent, proportionality, and value conflict.", writing: "Write a case note that states the strongest argument on each side before recommending a remedy.", chunks: ["within the court's jurisdiction","the right is not absolute","a proportionate response","on the face of it"], collocations: ["binding precedent","equitable remedy","infringe a right","test of proportionality"], related: ["statute","appeal","due process","justice"], register: "formal"
  },
  {
    title: "Global cities and the ethics of design", titleArabic: "المدن العالمية وأخلاقيات التصميم", theme: "urban design, access, and public space", themeArabic: "التصميم الحضري وإمكانية الوصول والفضاء العام", anchor: "design for the people who are usually missed",
    words: [["infrastructure","بنية تحتية","noun","the basic systems and structures a society needs"],["accessibility","إمكانية الوصول","noun","the quality of being usable by people with different needs"],["density","كثافة","noun","the amount of people or things in a given space"],["displace","يزيح أو يهجر","verb","to force people or things to move from their place"],["liveability","قابلية العيش","noun","the quality of being suitable and pleasant to live in"],["retrofitting","تعديل مبنى قائم","noun","adding new features to an existing structure"]],
    grammar: ["Apposition and parenthetical qualification","البدل والتقييد الاعتراضي","Use apposition and parenthetical clauses to add precise context without losing the main line.","استخدم البدل والجمل الاعتراضية لإضافة سياق دقيق دون فقدان الفكرة الرئيسية.","The station, a landmark of the old district, is being retrofitted for accessibility.","The station a landmark of the old district is being retrofitted.","The station, a landmark of the old district, is being retrofitted for accessibility.","Use punctuation to make the qualification easy to process."], outcome: ["I can evaluate urban proposals through access, displacement, density, and liveability.","أستطيع تقييم المقترحات الحضرية من خلال الوصول والتهجير والكثافة وقابلية العيش.","You are mediating between a development team and residents of a changing neighbourhood.","أنت تتوسط بين فريق تطوير وسكان حي يتغير."], reading: "Read a planning proposal and resident testimony; map benefits, burdens, and who has been left out of the design.", writing: "Write a design brief for a public space that makes accessibility and inclusion measurable.", chunks: ["designed with rather than for","the burden falls disproportionately on","a viable alternative","in the public interest"], collocations: ["urban infrastructure","universal accessibility","residential density","neighbourhood liveability"], related: ["planning","housing","mobility","public realm"], register: "formal"
  },
  {
    title: "Literature, voice, and the unreliable narrator", titleArabic: "الأدب والصوت والراوي غير الموثوق", theme: "narrative voice, reliability, and interpretation", themeArabic: "الصوت السردي والموثوقية والتفسير", anchor: "listen for the gap between voice and truth",
    words: [["unreliable","غير موثوق","adjective","not dependable as a source of truth"],["detachment","انفصال أو تباعد","noun","a lack of emotional involvement"],["foreshadow","يمهد لما سيأتي","verb","to hint at a future event"],["interiority","داخلية الشخصية","noun","the inner thoughts and feelings of a character"],["cadence","إيقاع الجملة","noun","the rhythm and flow of spoken or written language"],["ambiguity","غموض دلالي","noun","the presence of more than one possible meaning"]],
    grammar: ["Free indirect discourse and viewpoint shifts","الخطاب غير المباشر الحر وتحول المنظور","Represent a character's perspective without fully quoting or reporting it.","اعرض منظور الشخصية دون اقتباسه كاملاً أو نقله بصيغة مباشرة.","He would never admit it, but the silence had begun to frighten him.","He never would admit it, but the silence frightened him he thought.","He would never admit it, but the silence had begun to frighten him.","Make the viewpoint shift legible through tense, diction, and context."], outcome: ["I can analyse narrative voice, reliability, and the effect of stylistic choices.","أستطيع تحليل الصوت السردي والموثوقية وأثر الاختيارات الأسلوبية.","You are writing a critical response to a story whose narrator contradicts the evidence.","أنت تكتب استجابة نقدية لقصة يناقض راويها الأدلة."], reading: "Analyse a literary extract for focalisation, cadence, omission, and foreshadowing; compare the narrator's account with the implied events.", writing: "Write a critical commentary that supports an interpretation with close textual evidence.", chunks: ["the narrator's account","the gap between what is said and meant","the effect is unsettling","read against the grain"], collocations: ["unreliable narrator","narrative detachment","distinctive cadence","deliberate ambiguity"], related: ["focalisation","imagery","subtext","characterisation"], register: "mixed"
  },
  {
    title: "Diplomacy, conflict, and the work of repair", titleArabic: "الدبلوماسية والصراع وعمل الإصلاح", theme: "negotiation, conflict, and reconciliation", themeArabic: "التفاوض والصراع والمصالحة", anchor: "make room for a solution without erasing harm",
    words: [["de-escalate","يخفف التصعيد","verb","to reduce the intensity of conflict"],["grievance","مظلمة أو شكوى","noun","a complaint about unfair treatment"],["reciprocal","متبادل","adjective","given, felt, or done by both sides"],["reconcile","يصالح أو يوفق","verb","to restore agreement or make differences compatible"],["impasse","طريق مسدود","noun","a situation in which no progress is possible"],["durable","دائم وقابل للاستمرار","adjective","able to last or remain effective"]],
    grammar: ["Concessive clauses and diplomatic qualification","جمل التنازل والتقييد الدبلوماسي","Use although, however, much as, and even if to hold disagreement and cooperation together.","استخدم أدوات التنازل للتعبير عن الخلاف والتعاون معاً.","Much as the parties distrust one another, they share an interest in a durable settlement.","Much the parties distrust one another, they share an interest.","Much as the parties distrust one another, they share an interest in a durable settlement.","Ensure the concessive clause changes the relationship between ideas, not merely their order."], outcome: ["I can mediate a difficult disagreement by representing grievances accurately and identifying shared interests.","أستطيع التوسط في خلاف صعب بعرض المظالم بدقة وتحديد المصالح المشتركة.","You are preparing a neutral briefing before a reconciliation meeting.","أنت تعد إحاطة محايدة قبل اجتماع للمصالحة."], reading: "Compare statements from two sides of a dispute; distinguish positions, interests, grievances, and possible face-saving language.", writing: "Write a mediator's briefing that recommends three steps toward a durable agreement.", chunks: ["without prejudging the outcome","a point of common ground","mutual recognition of harm","move beyond the impasse"], collocations: ["de-escalate tensions","legitimate grievance","reciprocal concession","durable reconciliation"], related: ["negotiation","ceasefire","trust","settlement"], register: "formal"
  },
  {
    title: "C2 synthesis: translating expertise for people", titleArabic: "التركيب في مستوى C2: نقل الخبرة إلى الناس", theme: "mediation, expertise, and public understanding", themeArabic: "الوساطة والخبرة والفهم العام", anchor: "make difficult knowledge usable",
    words: [["synthesise","يركب أو يدمج","verb","to combine ideas from different sources into a coherent whole"],["jargon","مصطلحات متخصصة","noun","specialized language that may exclude outsiders"],["nuance","فارق دقيق","noun","a subtle distinction in meaning or feeling"],["distil","يستخلص الجوهر","verb","to extract the essential meaning"],["accessible","مفهوم ومتاح","adjective","easy to understand or use"],["misconception","مفهوم خاطئ","noun","an idea that is not correct"]],
    grammar: ["Recasting information across registers","إعادة صياغة المعلومات بين الأساليب","Move between technical, neutral, and public registers while preserving the core proposition.","انتقل بين الأساليب التقنية والمحايدة والعامة مع الحفاظ على الفكرة الأساسية.","The intervention mitigates risk; in plain English, it makes the danger less likely.","The intervention mitigates risk, it makes danger less likely.","The intervention mitigates risk; in plain English, it makes the danger less likely.","Check that simplification removes unnecessary density, not essential nuance."], outcome: ["I can synthesise complex sources and mediate them accurately for different audiences.","أستطيع تركيب مصادر معقدة ونقلها بدقة إلى جماهير مختلفة.","You are creating a bilingual public explainer from three expert sources that disagree in emphasis.","أنت تنشئ شرحاً عاماً ثنائي اللغة من ثلاثة مصادر خبراء تختلف في تركيزها."], reading: "Synthesize three short expert sources into a shared map of agreement, disagreement, uncertainty, and practical consequence.", writing: "Write an expert summary and a public version of the same finding, then explain the register decisions.", chunks: ["in accessible terms","the distinction is important because","taken together, the sources suggest","what this means in practice"], collocations: ["synthesise evidence","specialist jargon","subtle nuance","public misconception"], related: ["paraphrase","interpret","clarify","audience"], register: "mixed"
  },
  {
    title: "The ethics of persuasion", titleArabic: "أخلاقيات الإقناع", theme: "persuasion, rhetoric, and responsibility", themeArabic: "الإقناع والبلاغة والمسؤولية", anchor: "persuade without manipulating",
    words: [["persuasive","مقنع","adjective","effective at influencing beliefs or action"],["manipulate","يتلاعب","verb","to control unfairly through indirect or deceptive means"],["appeal","مناشدة أو حجة جاذبة","noun","a quality or argument that attracts interest or support"],["credibility","مصداقية","noun","the quality of being trusted or believed"],["emotive","عاطفي","adjective","appealing strongly to feelings"],["disclose","يفصح","verb","to make information known, especially information previously hidden"]],
    grammar: ["Rhetorical questions and controlled repetition","الأسئلة البلاغية والتكرار المقصود","Use rhetorical devices to shape attention while keeping the proposition logically testable.","استخدم الأدوات البلاغية لتوجيه الانتباه مع إبقاء الفكرة قابلة للفحص المنطقي.","What kind of progress are we defending, and for whom?","What kind progress are we defending and for whom?","What kind of progress are we defending, and for whom?","Separate emotional force from evidence so persuasion does not become manipulation."], outcome: ["I can evaluate and create persuasive communication while making ethical choices visible.","أستطيع تقييم وإنشاء تواصل مقنع مع إظهار الاختيارات الأخلاقية بوضوح.","You are reviewing a campaign that uses emotional language to encourage a public behaviour.","أنت تراجع حملة تستخدم لغة عاطفية لتشجيع سلوك عام."], reading: "Annotate a campaign, an opposing critique, and a fact sheet for appeals, omissions, emotional pressure, and credibility.", writing: "Write a persuasive campaign text with an accompanying transparency note that discloses its evidence and limits.", chunks: ["the question is not whether","it would be tempting to conclude","the appeal rests on","readers deserve to know"], collocations: ["persuasive appeal","manipulative framing","institutional credibility","emotive language"], related: ["rhetoric","propaganda","ethos","audience"], register: "mixed"
  },
  {
    title: "Final C2 studio: a position that can withstand scrutiny", titleArabic: "استوديو C2 الختامي: موقف يصمد أمام التدقيق", theme: "integrated synthesis and independent judgement", themeArabic: "التركيب المتكامل والحكم المستقل", anchor: "bring the whole language system to bear",
    words: [["coherent","مترابط","adjective","logical and well connected"],["discerning","متبصر وحسن التمييز","adjective","showing good judgement and understanding"],["substantive","جوهري","adjective","having real importance or value"],["qualify","يقيد أو يحدد","verb","to make a statement less absolute or more precise"],["sustain","يدعم أو يحافظ على","verb","to maintain or support over time"],["integrity","نزاهة وتكامل","noun","the quality of being honest, whole, and consistent"]],
    grammar: ["Cohesion, rhythm, and stylistic control","الترابط والإيقاع والتحكم الأسلوبي","Choose sentence length, coordination, subordination, and lexical repetition to create a deliberate voice.","اختر طول الجملة والربط والتبعية والتكرار المعجمي لصناعة صوت مقصود.","The proposal is ambitious; its integrity, however, depends on how it is implemented.","The proposal ambitious its integrity however depends how implemented.","The proposal is ambitious; its integrity, however, depends on how it is implemented.","Revise for rhythm and reader effort as carefully as you revise for correctness."], outcome: ["I can synthesize diverse evidence into a coherent, discerning, and defensible position.","أستطيع تركيب أدلة متنوعة في موقف مترابط ومتزن وقابل للدفاع.","You are completing a capstone dossier for an informed audience that expects evidence, nuance, and an actionable conclusion.","أنت تنجز ملفاً ختامياً لجمهور مطلع يتوقع الدليل والدقة وخلاصة قابلة للتنفيذ."], reading: "Complete a multi-source dossier containing an article, data commentary, testimony, and policy extract; build an evidence and uncertainty map.", writing: "Write a 900-word capstone position paper that synthesises sources, acknowledges limitations, and proposes a proportionate action.", chunks: ["taken as a whole","the argument stands or falls on","this conclusion is defensible insofar as","the next responsible step"], collocations: ["coherent synthesis","discerning judgement","substantive evidence","intellectual integrity"], related: ["capstone","dossier","proposition","implication"], register: "formal"
  },
];

function vocabulary(spec: Spec, lessonNumber: number): VocabularyItem[] {
  return spec.words.map(([word, arabic, partOfSpeech, definition], index) => ({ id: `c2-${lessonNumber}-${index + 1}`, word, arabic, ipa: "", phoneticRespelling: word, partOfSpeech, definition, exampleEN: `${word.charAt(0).toUpperCase() + word.slice(1)} matters when we examine the question carefully.`, exampleAR: `تظهر أهمية ${arabic} عندما نفحص السؤال بعناية.` }));
}

function grammar(spec: Spec, lessonNumber: number): GrammarTopic {
  const [topic, arabicName, concept, arabicComparison, structure, commonError, positive, question] = spec.grammar;
  return { id: `c2-grammar-${lessonNumber}`, lessonNumber, topic, arabicName, concept, represents: "Use this C2 pattern to control stance, rhythm, register, and the relationship between complex ideas.", arabicComparison, useWhen: ["you need to express a precise relationship between complex claims", "the audience and genre demand deliberate control of emphasis or register"], doNotUseWhen: ["a simpler form would make the meaning clearer", "the rhetorical device would obscure rather than clarify the idea"], commonMistakes: [{ wrong: commonError, correct: positive, explanation: "Check the relationship between form, meaning, audience, and rhetorical effect." }], structure: { positive, negative: `Test the limiting or counter-position in: ${structure}`, question }, examples: [{ en: structure, ar: `استخدم هذا النمط لتوضيح العلاقة بين الأفكار والتحكم في النبرة.` }], practice: [] };
}

const CURRICULUM_SPECS = Array.from({ length: 180 }, (_, index) => { const seed = SPECS[index % SPECS.length]; const cycle = Math.floor(index / SPECS.length) + 1; return cycle === 1 ? seed : { ...seed, title: `${seed.title} — Extension ${cycle}`, titleArabic: `${seed.titleArabic} — توسعة ${cycle}` }; });

export const C2_LESSONS: LessonDefinition[] = CURRICULUM_SPECS.map((spec, index) => {
  const lessonNumber = index + 1;
  const moduleNumber = Math.ceil(lessonNumber / 15);
  const prior = "C1" as const;
  return { level: "C2" as const, lessonNumber, moduleNumber, title: spec.title, titleArabic: spec.titleArabic, words: vocabulary(spec, lessonNumber), grammar: grammar(spec, lessonNumber), learningPlan: { outcome: { canDo: spec.outcome[0], canDoArabic: spec.outcome[1], scenario: spec.outcome[2], scenarioArabic: spec.outcome[3] }, steps: STEPS, retrieval: [{ sourceLevel: prior, language: "English", prompt: `Retrieve a C1 idea that helps you enter the theme of ${spec.theme}.`, purpose: `استدعِ فكرة من C1 تساعدك على دخول موضوع ${spec.themeArabic}.` }], englishFirst: true, studio: "Precision & Mediation Studio" }, lexicalNetworks: [{ id: `c2-network-${lessonNumber}`, theme: spec.theme, themeArabic: spec.themeArabic, anchor: spec.anchor, wordFamilies: spec.words.slice(0, 3).map(([word]) => ({ headword: word, forms: [word], note: `Use ${word} precisely in this theme.`, noteArabic: `استخدم ${word} بدقة في هذا الموضوع.` })), relatedWords: spec.related, chunks: spec.chunks, collocations: spec.collocations, register: spec.register, priorLevelLinks: ["evidence", "perspective", "consequence", "evaluation"], learningNote: "At C2, lexical knowledge becomes a choice about precision, audience, and effect.", learningNoteArabic: "في C2 تصبح المعرفة المعجمية اختياراً يتعلق بالدقة والجمهور والأثر." }], practiceBrief: { readingBrief: `${spec.reading} Track the writer's assumptions, evidence, and uncertainty before you respond.`, writingPrompt: `${spec.writing} Address a defined audience, make your evidence and qualifications visible, and revise once for precision, coherence, and reader effort.` } };
}).map(enrichLesson).map((lesson) => ({
  ...lesson,
  activities: C2_MODULE_4_AUTHORED_ACTIVITIES[lesson.lessonNumber] ?? C2_MODULE_3_AUTHORED_ACTIVITIES[lesson.lessonNumber] ?? C2_MODULE_2_AUTHORED_ACTIVITIES[lesson.lessonNumber] ?? C2_MODULE_1_AUTHORED_ACTIVITIES[lesson.lessonNumber] ?? lesson.activities,
  experience: C2_MODULE_4_EXPERIENCES[lesson.lessonNumber] ?? C2_MODULE_3_EXPERIENCES[lesson.lessonNumber] ?? C2_MODULE_2_EXPERIENCES[lesson.lessonNumber] ?? C2_MODULE_1_EXPERIENCES[lesson.lessonNumber] ?? lesson.experience,
}));

export const C2_VOCABULARY = C2_LESSONS.flatMap((lesson) => lesson.words);
export const C2_GRAMMAR = C2_LESSONS.map((lesson) => lesson.grammar);
export const C2_COURSE: CourseDefinition = { level: "C2", title: "Precision, mediation, and independent judgement", titleArabic: "الدقة والوساطة والحكم المستقل", totalLessons: 180, lessonsPerModule: 15, estimatedMinutes: 16 * 141, lessons: C2_LESSONS, modules: buildModuleDefinitions("C2", C2_LESSONS) };
export function getC2Lesson(lessonNumber: number) { return C2_LESSONS.find((lesson) => lesson.lessonNumber === lessonNumber); }
export const C2_LESSON_COUNT = C2_LESSONS.length;
export const C2_MODULE_COUNT = 12;
export const C2_LEVEL = "C2" as const;
export const C2_LESSON_STEPS = STEPS;
export const C2_AUTHORING_NOTE = "C2 develops independent judgement, mediation, stylistic control, and precise synthesis.";
export const C2_READY = C2_LESSONS.length === 180 && C2_LESSONS.every((lesson) => lesson.words.length >= 6 && Boolean(lesson.learningPlan) && Boolean(lesson.practiceBrief));
if (!C2_READY) throw new Error(`C2 curriculum requires 16 complete lessons; found ${C2_LESSONS.length}`);
export default C2_COURSE;
