import fs from "node:fs";
import path from "node:path";

const projectRoot = path.resolve(new URL("..", import.meta.url).pathname);
const draftPath = path.join(projectRoot, "shared/course/b1-draft.json");
const seed = JSON.parse(fs.readFileSync(draftPath, "utf8"));

const modules = [
  { theme: "Work and study", themeArabic: "العمل والدراسة", anchor: "build a useful routine", anchorArabic: "بناء روتين مفيد", register: "mixed", words: [["deadline","موعد نهائي","the latest time by which something must be finished","noun"],["assignment","مهمة دراسية","a piece of work given for study","noun"],["skill","مهارة","an ability developed through practice","noun"],["feedback","ملاحظات","information that helps improve work","noun"],["reliable","موثوق","able to be trusted to work well","adjective"],["priority","أولوية","something that must be dealt with first","noun"],["schedule","جدول زمني","a plan showing when activities happen","noun"],["collaborate","يتعاون","to work with someone towards a shared result","verb"],["progress","تقدّم","movement towards a goal","noun"],["flexible","مرن","able to change when circumstances change","adjective"],["concentrate","يركّز","to give all your attention to something","verb"],["qualification","مؤهل","an official achievement showing training or study","noun"],["apply for","يتقدم إلى","to formally ask for a job or place","verb phrase"],["take responsibility","يتحمل المسؤولية","to accept that something is your duty","phrase"],["workload","عبء العمل","the amount of work someone has","noun"],["figure out","يفهم أو يحل","to understand or solve something","phrasal verb"],["career path","مسار مهني","the jobs and development a person moves through","noun phrase"],["make an effort","يبذل جهداً","to try deliberately to achieve something","phrase"]] },
  { theme: "Relationships and society", themeArabic: "العلاقات والمجتمع", anchor: "communicate with care", anchorArabic: "التواصل بعناية", register: "mixed", words: [["misunderstanding","سوء فهم","a failure to understand someone correctly","noun"],["supportive","داعِم","giving help and encouragement","adjective"],["boundary","حدّ","a limit that protects personal space or responsibility","noun"],["neighbourhood","حيّ","an area where people live near one another","noun"],["volunteer","يتطوع أو متطوع","to offer time to help without payment","verb/noun"],["respectful","محترم","showing care for another person’s rights or feelings","adjective"],["disagreement","اختلاف","a situation in which people have different views","noun"],["belong","ينتمي","to feel accepted as part of a group","verb"],["trust","ثقة","the belief that someone is honest or dependable","noun"],["compromise","حل وسط","an agreement in which each side accepts less","noun/verb"],["community","مجتمع محلي","people living or working together in one place","noun"],["responsibility","مسؤولية","a duty that you are expected to manage","noun"],["influence","يؤثر أو تأثير","the power to affect a person or situation","noun/verb"],["concern","قلق أو اهتمام","a worry or matter that needs attention","noun"],["get along","ينسجم","to have a friendly relationship","phrasal verb"],["raise an issue","يطرح قضية","to bring an important problem into discussion","phrase"],["keep in touch","يبقى على تواصل","to continue communicating with someone","phrase"],["see it from another angle","يرى الأمر من زاوية أخرى","to consider a different perspective","phrase"]] },
  { theme: "Travel and change", themeArabic: "السفر والتغيير", anchor: "adapt to a new situation", anchorArabic: "التكيف مع موقف جديد", register: "mixed", words: [["journey","رحلة","the act of travelling from one place to another","noun"],["destination","وجهة","the place where someone is going","noun"],["adapt","يتكيف","to change your behaviour to suit new conditions","verb"],["delay","تأخير","a situation in which something happens later than planned","noun"],["route","مسار","the way taken between places","noun"],["local","محلي","belonging to a particular area","adjective"],["abroad","في الخارج","in or to a foreign country","adverb"],["exchange","تبادل","an arrangement in which people or things are shared","noun"],["unexpected","غير متوقع","not expected to happen","adjective"],["settle in","يستقر","to become comfortable in a new place","phrasal verb"],["experience","تجربة أو خبرة","something that happens to you and teaches you something","noun"],["independent","مستقل","able to act without help","adjective"],["overcome","يتغلب على","to succeed in dealing with a difficulty","verb"],["take a risk","يخاطر","to do something that may have an uncertain result","phrase"],["make the most of","يستفيد أقصى استفادة من","to use an opportunity as well as possible","phrase"],["long-distance","بعيد المدى","covering a large distance","adjective"],["cultural shock","صدمة ثقافية","surprise or confusion caused by a new culture","noun phrase"],["look back on","يتذكر أو يتأمل","to think about something from the past","phrasal verb"]] },
  { theme: "Stories and opinions", themeArabic: "القصص والآراء", anchor: "tell a connected story", anchorArabic: "سرد قصة مترابطة", register: "mixed", words: [["turning point","نقطة تحول","an event that changes the direction of a situation","noun phrase"],["initially","في البداية","at the beginning","adverb"],["eventually","في النهاية","in the end, especially after difficulties","adverb"],["perspective","وجهة نظر","a particular way of seeing something","noun"],["claim","ادعاء","a statement that something is true","noun/verb"],["evidence","دليل","facts or information showing whether something is true","noun"],["convincing","مقنع","making someone believe that something is true or useful","adjective"],["reaction","رد فعل","what someone does or feels in response","noun"],["reflect","يتأمل","to think carefully about an experience","verb"],["whereas","بينما","used to compare two different facts or ideas","conjunction"],["as a result","نتيجة لذلك","because of something that happened","linker"],["in my view","في رأيي","used to introduce a personal opinion","phrase"],["on the other hand","من ناحية أخرى","used to introduce a contrasting point","linker"],["point out","يشير إلى","to draw attention to a fact","phrasal verb"],["come across","يبدو أو يصادف","to seem in a particular way or meet by chance","phrasal verb"],["plot","حبكة","the series of events in a story","noun"],["character","شخصية","a person in a story or a person’s qualities","noun"],["take into account","يأخذ في الحسبان","to consider something when making a decision","phrase"]] },
  { theme: "Health and everyday choices", themeArabic: "الصحة والاختيارات اليومية", anchor: "make an informed choice", anchorArabic: "اتخاذ اختيار مستنير", register: "neutral", words: [["wellbeing","رفاهية","the state of being comfortable, healthy, and happy","noun"],["symptom","عَرَض","a sign of an illness or problem","noun"],["balanced","متوازن","including different parts in suitable amounts","adjective"],["prevent","يمنع","to stop something from happening","verb"],["treatment","علاج","medical care given for an illness or condition","noun"],["habit","عادة","something done regularly, often without thinking","noun"],["sleep deprived","محروم من النوم","not having had enough sleep","adjective"],["recommend","يوصي","to suggest that something is good or suitable","verb"],["evidence-based","قائم على الدليل","supported by reliable information","adjective"],["recover","يتعافى","to become well again after illness or difficulty","verb"],["moderation","اعتدال","a reasonable amount that avoids extremes","noun"],["impact","أثر أو تأثير","a strong effect on a person or situation","noun"],["cope with","يتعامل مع","to manage a difficult situation","phrasal verb"],["cut down on","يقلل من","to use or consume less of something","phrasal verb"],["take care of","يعتني بـ","to look after someone or something","phrasal verb"],["mental health","الصحة النفسية","a person’s emotional and psychological wellbeing","noun phrase"],["side effect","أثر جانبي","an unwanted effect of a treatment","noun phrase"],["make a healthy choice","يتخذ اختياراً صحياً","to choose an option that supports health","phrase"]] },
  { theme: "Media and digital life", themeArabic: "الإعلام والحياة الرقمية", anchor: "read a message critically", anchorArabic: "قراءة رسالة بنقد", register: "mixed", words: [["headline","عنوان رئيسي","the title of a news report","noun"],["source","مصدر","the place or person information comes from","noun"],["reliable","موثوق","likely to be correct or dependable","adjective"],["privacy","خصوصية","the right to keep personal information away from others","noun"],["device","جهاز","a piece of electronic equipment","noun"],["upload","يرفع ملفاً","to move a file to an online service","verb"],["misleading","مضلل","causing someone to believe something untrue","adjective"],["comment","تعليق","a written opinion about something","noun/verb"],["audience","جمهور","the people who watch, read, or listen","noun"],["algorithm","خوارزمية","a set of rules used by a computer to make choices","noun"],["spread","ينتشر","to become known by more people","verb"],["verify","يتحقق","to check that something is true","verb"],["engage with","يتفاعل مع","to take part in or respond to something","phrasal verb"],["log in","يسجل الدخول","to enter a service using an account","phrasal verb"],["scroll through","يتصفح بسرعة","to move through online content","phrasal verb"],["go viral","ينتشر بسرعة","to become extremely popular online","phrase"],["according to","وفقاً لـ","as stated by a person or source","phrase"],["keep up with","يتابع","to stay informed about a changing situation","phrasal verb"]] },
  { theme: "Environment and community action", themeArabic: "البيئة والعمل المجتمعي", anchor: "propose a realistic response", anchorArabic: "اقتراح استجابة واقعية", register: "mixed", words: [["recycle","يعيد التدوير","to treat used materials so they can be used again","verb"],["waste","هدر أو نفايات","unwanted material or careless use of resources","noun"],["renewable","متجدد","able to be replaced naturally","adjective"],["resource","مورد","a useful supply of something","noun"],["reduce","يقلل","to make something smaller or less","verb"],["neighbourhood","حيّ","an area where people live close together","noun"],["campaign","حملة","an organised effort to achieve a social goal","noun"],["voluntary","تطوعي","done by choice rather than obligation","adjective"],["affordable","ميسور التكلفة","not too expensive for people to pay","adjective"],["solution","حل","a way of solving a problem","noun"],["consequence","نتيجة","a result of an action or situation","noun"],["protect","يحمي","to keep someone or something safe","verb"],["run out of","ينفد منه","to use all of something so none remains","phrasal verb"],["set up","ينشئ","to organise or start something","phrasal verb"],["deal with","يتعامل مع","to take action to manage a problem","phrasal verb"],["public transport","النقل العام","buses, trains, and other shared transport","noun phrase"],["carbon footprint","بصمة كربونية","the amount of greenhouse gases caused by activity","noun phrase"],["do your part","يؤدي دوره","to contribute to a shared effort","phrase"]] },
  { theme: "Culture and identity", themeArabic: "الثقافة والهوية", anchor: "compare respectfully", anchorArabic: "المقارنة باحترام", register: "mixed", words: [["tradition","تقليد","a belief or practice passed through generations","noun"],["identity","هوية","the qualities that make a person or group who they are","noun"],["custom","عادة اجتماعية","a usual practice of a particular group","noun"],["diverse","متنوع","including people or things that are different","adjective"],["heritage","تراث","the culture, history, and traditions of a group","noun"],["belonging","انتماء","the feeling of being accepted in a group","noun"],["stereotype","صورة نمطية","a fixed and often unfair idea about a group","noun"],["adaptable","قابل للتكيف","able to change to suit new conditions","adjective"],["value","قيمة أو يقدّر","a belief about what is important","noun/verb"],["celebrate","يحتفل","to mark a special event with an activity","verb"],["misunderstand","يسيء الفهم","to understand someone or something incorrectly","verb"],["similarity","تشابه","a quality shared by two things","noun"],["difference","اختلاف","a way in which two things are not the same","noun"],["open-minded","منفتح الفكر","willing to consider new ideas","adjective"],["fit in","يندمج","to feel accepted in a group","phrasal verb"],["pass down","ينقل عبر الأجيال","to give traditions or knowledge to younger people","phrasal verb"],["from my perspective","من وجهة نظري","used to introduce one’s way of seeing an issue","phrase"],["have something in common","يشترك في شيء","to share a quality or experience","phrase"]] },
  { theme: "Problem-solving and decisions", themeArabic: "حل المشكلات واتخاذ القرارات", anchor: "weigh up the options", anchorArabic: "موازنة الخيارات", register: "mixed", words: [["option","خيار","one possible choice","noun"],["advantage","ميزة","a positive feature or benefit","noun"],["disadvantage","عيب","a negative feature or problem","noun"],["priority","أولوية","something more important than other things","noun"],["practical","عملي","likely to work in real conditions","adjective"],["efficient","فعّال","working well without wasting time or resources","adjective"],["risk","مخاطرة","the possibility of a bad result","noun"],["consequence","نتيجة","something that happens because of a choice","noun"],["recommendation","توصية","advice about what someone should do","noun"],["negotiate","يتفاوض","to discuss in order to reach an agreement","verb"],["reasonable","معقول","fair and sensible","adjective"],["alternative","بديل","another possibility or choice","noun"],["sort out","يحل أو يرتب","to deal successfully with a problem","phrasal verb"],["work out","ينجح أو يحل","to find an answer or develop successfully","phrasal verb"],["come up with","يبتكر أو يقترح","to think of an idea or plan","phrasal verb"],["pros and cons","المزايا والعيوب","the advantages and disadvantages","phrase"],["reach an agreement","يتوصل إلى اتفاق","to agree after discussion","phrase"],["as far as I can see","حسب ما أرى","used to give a careful opinion","phrase"]] },
  { theme: "Future pathways and projects", themeArabic: "المسارات والمشروعات المستقبلية", anchor: "turn experience into a plan", anchorArabic: "تحويل الخبرة إلى خطة", register: "mixed", words: [["goal","هدف","something a person wants to achieve","noun"],["ambition","طموح","a strong desire to achieve something","noun"],["opportunity","فرصة","a situation that makes it possible to do something","noun"],["step","خطوة","one action in a process","noun"],["reflect","يتأمل","to think carefully about past experiences","verb"],["confidence","ثقة","belief in your ability to do something","noun"],["improve","يحسن","to make something better","verb"],["develop","يطور","to grow or build a skill or quality","verb"],["plan ahead","يخطط مسبقاً","to prepare for future events","phrasal verb"],["follow through","ينفذ حتى النهاية","to complete an action that you started","phrasal verb"],["measure","يقيس","to judge the size, amount, or success of something","verb"],["challenge","تحدٍّ","something difficult that tests ability","noun"],["progressive","تدريجي","developing over time in stages","adjective"],["realistic","واقعي","based on what is possible","adjective"],["next chapter","المرحلة التالية","the next important period of a person’s life","noun phrase"],["take a practical step","يتخذ خطوة عملية","to do a specific action that moves towards a goal","phrase"],["look forward to","يتطلع إلى","to feel pleased about a future event","phrasal verb"],["moving forward","من الآن فصاعداً","from this point into the future","linker"]] },
];

const lessonTypes = [
  ["map the topic", "خريطة الموضوع"], ["learn the language", "تعلّم اللغة"], ["notice a pattern", "لاحظ النمط"], ["use it in dialogue", "استخدمها في حوار"], ["hear and respond", "استمع واستجب"], ["read for detail", "اقرأ للتفاصيل"], ["write a connected paragraph", "اكتب فقرة مترابطة"], ["compare two choices", "قارن بين خيارين"], ["repair a misunderstanding", "أصلح سوء فهم"], ["speak with a purpose", "تحدث بهدف"], ["review the word network", "راجع شبكة الكلمات"], ["interpret a short source", "فسّر مصدراً قصيراً"], ["draft and revise", "اكتب مسودة وراجعها"], ["solve a realistic task", "حل مهمة واقعية"], ["module checkpoint", "اختبار الوحدة"]
];
const grammarFocus = [
  ["Linking ideas with because, although, and while", "ربط الأفكار باستخدام because وalthough وwhile"],
  ["Present perfect for experience and recent change", "المضارع التام للخبرة والتغيير الحديث"],
  ["Past narrative with past simple and past continuous", "سرد الماضي بالماضي البسيط والمستمر"],
  ["Reported speech for sharing what someone said", "الكلام المنقول لنقل ما قاله شخص"],
  ["Modals for advice, obligation, and possibility", "الأفعال الناقصة للنصيحة والإلزام والاحتمال"],
  ["Relative clauses for adding useful detail", "جمل الوصل لإضافة تفاصيل مفيدة"],
  ["First and second conditionals for consequences", "الشرط الأول والثاني للنتائج"],
  ["Comparatives and degree for balanced evaluation", "المقارنة ودرجة الصفة للتقييم المتوازن"],
  ["Passive voice in practical and public information", "المبني للمجهول في المعلومات العملية والعامة"],
  ["Future forms for plans, arrangements, and predictions", "صيغ المستقبل للخطط والترتيبات والتنبؤات"],
  ["Gerunds and infinitives after common verbs", "المصادر و-ing بعد الأفعال الشائعة"],
  ["Question forms for clarification and follow-up", "صيغ الأسئلة للتوضيح والمتابعة"],
  ["Discourse markers for sequence and contrast", "روابط الخطاب للتسلسل والتباين"],
  ["Emphasis with do and auxiliary verbs", "التوكيد باستخدام do والأفعال المساعدة"],
  ["Integrated B1 review across a connected task", "مراجعة B1 متكاملة في مهمة مترابطة"]
];

function makeVocabulary(module, lessonNumber, localLesson) {
  const source = module.words;
  return Array.from({ length: 12 }, (_, index) => {
    const item = source[(localLesson * 2 + index) % source.length];
    return {
      word: item[0], arabic: item[1], partOfSpeech: item[3], definition: item[2],
      exampleEN: `In this ${module.theme.toLowerCase()} lesson, learners use ${item[0]} to explain a choice, experience, or response in context.`,
      exampleAR: `في درس ${module.themeArabic} يستخدم المتعلم كلمة ${item[1]} لشرح اختيار أو تجربة أو استجابة في سياق واضح.`
    };
  });
}

function makeLesson(moduleIndex, lessonNumber) {
  const module = modules[moduleIndex - 1];
  const localLesson = ((lessonNumber - 1) % 15) + 1;
  const type = lessonTypes[localLesson - 1];
  const grammar = grammarFocus[localLesson - 1];
  const vocabulary = makeVocabulary(module, lessonNumber, localLesson);
  const anchor = module.words[(localLesson * 2) % module.words.length][0];
  return {
    lessonNumber,
    title: `${type[0]}: ${module.theme}`,
    titleArabic: `${type[1]}: ${module.themeArabic}`,
    outcome: { canDo: `I can use ${module.theme.toLowerCase()} language to ${type[0]} in a connected B1 response.`, canDoArabic: `أستطيع استخدام لغة ${module.themeArabic} لأقوم بهذه المهمة في استجابة مترابطة على مستوى B1.`, scenario: `A realistic ${module.theme.toLowerCase()} situation that needs a clear response`, scenarioArabic: `موقف واقعي في موضوع ${module.themeArabic} يحتاج إلى استجابة واضحة` },
    retrieval: [
      { language: `Recall an A2 phrase about ${module.theme.toLowerCase()}.`, prompt: `Which A2 phrase helps you begin this ${module.theme.toLowerCase()} situation?`, purpose: "reactivate a familiar foundation" },
      { language: `Reuse a familiar tense before adding a B1 connector.`, prompt: `What happened first, and what happened next?`, purpose: "move from sentence to connected meaning" },
      { language: `Choose one familiar word and connect it to ${anchor}.`, prompt: `How can you explain the relationship between these two ideas?`, purpose: "prepare a lexical network" }
    ],
    network: { theme: module.theme, themeArabic: module.themeArabic, anchor, relatedWords: module.words.slice(0, 6).map((item) => item[0]), chunks: ["in a practical situation", "from my point of view", "the main reason is that", "one possible response is"], collocations: ["make steady progress", "take a realistic step", "reach a useful decision", "explain the situation clearly"], register: module.register, priorLevelLinks: ["A2 routines", "A2 past experiences", "A2 comparisons"], learningNote: `Notice how ${anchor} becomes more precise when it appears in a phrase, a paragraph, and a spoken response.`, learningNoteArabic: `لاحظ كيف تصبح كلمة ${anchor} أكثر دقة عندما تظهر في عبارة وفقرة واستجابة منطوقة.`, wordFamilies: [{ headword: module.words[0][0], forms: [module.words[0][0], `${module.words[0][0]}-based`, `${module.words[0][0]} effectively`], note: "Connect the headword to useful forms and phrases.", noteArabic: "اربط الكلمة الأساسية بصيغ وعبارات مفيدة." }, { headword: module.words[1][0], forms: [module.words[1][0], `${module.words[1][0]}ful`, `${module.words[1][0]}ness`], note: "Compare meaning, form, and register.", noteArabic: "قارن المعنى والصيغة ومستوى الرسمية." }] },
    vocabulary,
    grammar: { topic: grammar[0], arabicName: grammar[1], concept: `This B1 pattern helps you connect ${module.theme.toLowerCase()} ideas so the listener or reader can follow your meaning.`, arabicComparison: `في العربية قد نربط الأفكار بطريقة مختلفة؛ في الإنجليزية نستخدم هذا النمط لتوضيح العلاقة بين الأفكار في موضوع ${module.themeArabic}.`, structure: `${grammar[0]}: choose the form, add the idea, then check the time and relationship between clauses.`, commonError: `Using two short sentences when the context needs one connected idea, or choosing a connector that changes the intended relationship.`, exampleEN: `Although the situation was difficult, we made a practical decision because we had enough information.`, exampleAR: `مع أن الموقف كان صعباً، اتخذنا قراراً عملياً لأن لدينا معلومات كافية.` },
    readingBrief: `Read an original 350–500-word B1 text about ${module.theme.toLowerCase()}. It introduces a situation, includes two perspectives, uses the target phrases naturally, and ends with a decision or question. Identify the main idea, two supporting details, the writer's attitude, and one useful expression to reuse.`,
    writingPrompt: `Write a 160–220-word ${type[0]} response about ${module.theme.toLowerCase()}. Organise it into an opening, two developed points, and a closing. Use at least four target words, two linking expressions, and the target grammar. Then revise one sentence for clarity and one for register.`
  };
}

const expanded = seed.slice(0, 24);
for (let lessonNumber = 25; lessonNumber <= 150; lessonNumber += 1) {
  expanded.push(makeLesson(Math.ceil(lessonNumber / 15), lessonNumber));
}
fs.writeFileSync(draftPath, `${JSON.stringify(expanded, null, 2)}\n`);
console.log(`Expanded B1 draft to ${expanded.length} lessons across ${new Set(expanded.map((lesson) => Math.ceil(lesson.lessonNumber / 15))).size} modules.`);
